SideCar: SideCar::Algorithms::ABTrackerUtils::Track Class Reference
SideCar::Algorithms::ABTrackerUtils::Track Class Reference
Representation of a track managed by the ABTracker.
#include </Users/howes/src/sidecar/Algorithms/ABTracker/Track.h>
Public Types
enum State {
kInitiating, kAlive, kDropping, kUninitiating,
kNumStates
}
Public Member Functions
Track (ABTracker &owner, uint32_t id, double when, const Geometry::Vector &pos)
Constructor.
const std::string & getId () const
Obtain the track's unique ID tag.
double getProximityTo (double when, const Geometry::Vector &pos)
Determine how close this track is from a given position.
bool isAlive () const
Determine if the track is alive (not initiating and not dropping).
bool isDropping () const
Determine if the track is dropping.
void updatePosition (double when, const Geometry::Vector &pos)
Update the track with a new position report.
bool emitPosition ()
Send out a TSPI message with the current position.
void drop ()
Change the track state to kDropping and send out a TSPI message with the current position.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for Track messages.
Detailed Description
Representation of a track managed by the ABTracker.
Definition at line 18 of file Track.h.
Member Enumeration Documentation
enum SideCar::Algorithms::ABTrackerUtils::Track::State
Enumerator
kInitiating
Track needs more reports to be active.
kAlive
Track is active and emitting reports.
kDropping
Track is dropping.
kUninitiating
Track failed to initiate.
Definition at line 22 of file Track.h.
Constructor & Destructor Documentation
Track::Track (ABTracker & owner, uint32_t id, double when, const Geometry::Vector & pos)
Constructor.
Parameters
owner ABTracker reference
id unique integer ID for this track
when time of creation
pos initial position of the track
Definition at line 21 of file Track.cc.
References kAlive, Log(), and LOGINFO.
Member Function Documentation
bool Track::emitPosition ()
Send out a TSPI message with the current position.
Returns
true if successful
Definition at line 178 of file Track.cc.
References SideCar::Algorithms::Algorithm::getName(), kDropping, kInitiating, and SideCar::Algorithms::Algorithm::send().
Referenced by drop(), and SideCar::Algorithms::ABTracker::shutdown().
const std::string& SideCar::Algorithms::ABTrackerUtils::Track::getId () const inline
Obtain the track's unique ID tag.
Returns
track ID tag
Definition at line 53 of file Track.h.
Referenced by SideCar::Algorithms::ABTracker::shutdown().
double Track::getProximityTo (double when, const Geometry::Vector & pos)
Determine how close this track is from a given position.
Estimates the track's position at the given time, and then calculates magnitude^2 between the estimationed positon and the given one.
Parameters
when time to use for estimation
pos position to compare against
Returns
magnitude^2 value
Definition at line 67 of file Track.cc.
References SideCar::Geometry::Vector::getMagnitudeSquared(), kAlive, kDropping, kInitiating, kUninitiating, Log(), LOGDEBUG, and LOGINFO.
Referenced by SideCar::Algorithms::ABTracker::shutdown().
bool SideCar::Algorithms::ABTrackerUtils::Track::isAlive () const inline
Determine if the track is alive (not initiating and not dropping).
Returns
true if so
Definition at line 70 of file Track.h.
bool SideCar::Algorithms::ABTrackerUtils::Track::isDropping () const inline
Determine if the track is dropping.
Returns
true if so
Definition at line 76 of file Track.h.
Referenced by SideCar::Algorithms::ABTracker::shutdown().
Logger::Log & Track::Log () static
Obtain the log device for Track messages.
Returns
Log device
Definition at line 15 of file Track.cc.
References Logger::Log::Find().
Referenced by getProximityTo(), Track(), and updatePosition().
void Track::updatePosition (double when, const Geometry::Vector & pos)
Update the track with a new position report.
Parameters
when time associated with the new report
pos location to update with
Definition at line 110 of file Track.cc.
References kInitiating, Log(), LOGDEBUG, and LOGINFO.
Referenced by SideCar::Algorithms::ABTracker::shutdown().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/ABTracker/Track.h
/Users/howes/src/sidecar/Algorithms/ABTracker/Track.cc