SideCar: SideCar::IO::ProcessingState Class Reference
SideCar::IO::ProcessingState Class Reference
Representation of a processing state in the SideCar system.
#include </Users/howes/src/sidecar/IO/ProcessingState.h>
Data Structures
struct Initializer
Public Types
enum Value {
kInvalid = 0, kInitialize, kAutoDiagnostic, kCalibrate,
kRun, kStop, kFailure, kNumStates
}
Static Public Member Functions
static const char *const * GetNames ()
static const char * GetName (Value state)
Class method that obtains the textual name of a given state constant.
static Value GetValue (std::string name)
Class method that attempts to locate the state index for a given name.
static bool IsNormal (ProcessingState::Value state)
Determine if the given state index is a non-failure state.
static bool IsActive (ProcessingState::Value state)
Determine if the given state index is a active processing state.
Detailed Description
Representation of a processing state in the SideCar system.
Defines a Value qenumeration which defines the valid integral values for a processing state. Also provides class methods for converting the enumerated value to/from a string.
Definition at line 14 of file ProcessingState.h.
Member Enumeration Documentation
enum SideCar::IO::ProcessingState::Value
Enumerator
kInitialize
Task initialized to known state.
kAutoDiagnostic
Task performing auto-diagnostics.
kCalibrate
Task doing calibration processing.
kRun
Task doing normal data processing.
kStop
Task stopped.
kFailure
Task has detected a serious problem.
Definition at line 17 of file ProcessingState.h.
Member Function Documentation
const char * ProcessingState::GetName (Value state) static
Class method that obtains the textual name of a given state constant.
Parameters
state value to look for
Returns
text value
Definition at line 52 of file ProcessingState.cc.
Referenced by SideCar::IO::Task::enterProcessingState(), SideCar::GUI::Master::CollectionItem::getStateDataValue(), SideCar::GUI::Master::TaskItem::getStateDataValue(), and SideCar::GUI::Master::MainWindow::MainWindow().
ProcessingState::Value ProcessingState::GetValue (std::string name) static
Class method that attempts to locate the state index for a given name.
Ignores case when searching.
Parameters
name the state name to search for
Returns
state index if found, or kInvalid
Definition at line 58 of file ProcessingState.cc.
Referenced by SideCar::Runner::App::App().
static bool SideCar::IO::ProcessingState::IsActive (ProcessingState::Value state) inline static
Determine if the given state index is a active processing state.
Parameters
state the state to test
Returns
true if kAutoDiagnostic, kCalibrate, or kRun
Definition at line 61 of file ProcessingState.h.
References kAutoDiagnostic, and kRun.
static bool SideCar::IO::ProcessingState::IsNormal (ProcessingState::Value state) inline static
Determine if the given state index is a non-failure state.
Parameters
state the state to test
Returns
true if kInitialize, kAutoDiagnostic, kCalibrate, kRun, or kStop
Definition at line 52 of file ProcessingState.h.
References kInitialize, and kStop.
Referenced by SideCar::IO::Task::enterProcessingState().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/ProcessingState.h
/Users/howes/src/sidecar/IO/ProcessingState.cc