SideCar: SideCar::IO::Preamble Class Reference
SideCar::IO::Preamble Class Reference
Definition of the preamble found at the beginning of all SideCar messages, regardless of content type.
#include </Users/howes/src/sidecar/IO/Preamble.h>
Public Types
enum { kCDRStreamSize = sizeof(int32_t) * 2, kMagicTag = 0xAAAA }
Public Member Functions
Preamble ()
Constructor.
Preamble (uint32_t size, int byteOrder=ACE_CDR_BYTE_ORDER)
Primary constructor.
Preamble (ACE_InputCDR &cdr)
Conversion constructor for ACE_InputCDR objects.
bool isValid () const
Determine if the data seen so far matches a proper Preamble.
uint16_t getMagicTag () const
Obtain the 'magic' tag of the preamble.
uint16_t getByteOrder () const
Obtain the byte ordering in use.
size_t getSize () const
Obtain the size of the message body.
ACE_InputCDR & load (ACE_InputCDR &cdr)
Obtain new instance data from a CDR input stream.
ACE_OutputCDR & write (ACE_OutputCDR &cdr) const
Write out the header to a CDR output stream.
Static Public Member Functions
static Logger::Log & Log ()
Log device for Preamble objects.
Detailed Description
Definition of the preamble found at the beginning of all SideCar messages, regardless of content type.
The preamble consists of 8 bytes (2 32-bit integers): the first indicates byte-ordering as defined by the ACE Common Data Representation (CDR) classes, and the second gives the number of bytes in the message body.
Unlike the IP standard to always put things in network byte-order (big-endian), the CDR classes assume that the machine performing the writing (using ACE_OutputCDR) represents the optimal byte ordering. Thus, a program running on an Intel system (little-endian) that writes data to disk or network will do so with little-endian formatting (ie no byte-swapping). If the recipient of the message does not have the byte-ordering of the incoming message, ACE_InputCDR will perform the byte-swapping necessary to properly read the data of the message.
Definition at line 22 of file Preamble.h.
Member Enumeration Documentation
anonymous enum
Enumerator
kCDRStreamSize
Number of bytes in preamble.
kMagicTag
Magic value at start of msg.
Definition at line 32 of file Preamble.h.
Constructor & Destructor Documentation
SideCar::IO::Preamble::Preamble () inline
Constructor.
Acquires the ACE CDR byte order for the running architecture. Initial size is set to zero. Used when writing new records to disk or network.
Definition at line 40 of file Preamble.h.
SideCar::IO::Preamble::Preamble (uint32_t size, int byteOrder = ACE_CDR_BYTE_ORDER) inline
Primary constructor.
Acquires the ACE CDR byte order for the running architecture by default.
Parameters
size size to hold
byteOrder little-endian (non-zero) or big-endian byte order
Definition at line 50 of file Preamble.h.
SideCar::IO::Preamble::Preamble (ACE_InputCDR & cdr) inline
Conversion constructor for ACE_InputCDR objects.
Reads in the magicTag_ and byteOrder_ attributes from the CDR object, and potentially changes the ACE_InputCDR to new byte ordering.
Parameters
cdr the ACE input CDR to use for data.
Definition at line 58 of file Preamble.h.
Member Function Documentation
uint16_t SideCar::IO::Preamble::getByteOrder () const inline
Obtain the byte ordering in use.
Returns
ACE CDR byte order
Definition at line 77 of file Preamble.h.
uint16_t SideCar::IO::Preamble::getMagicTag () const inline
Obtain the 'magic' tag of the preamble.
Returns
initial 4-byte value of message
Definition at line 71 of file Preamble.h.
size_t SideCar::IO::Preamble::getSize () const inline
Obtain the size of the message body.
Returns
size in bytes
Definition at line 83 of file Preamble.h.
Referenced by SideCar::IO::Decoder::Decoder().
bool SideCar::IO::Preamble::isValid () const inline
Determine if the data seen so far matches a proper Preamble.
Returns
true if so
Definition at line 64 of file Preamble.h.
Referenced by SideCar::IO::Decoder::decode().
ACE_InputCDR & Preamble::load (ACE_InputCDR & cdr)
Obtain new instance data from a CDR input stream.
Parameters
cdr stream to read from
Returns
stream read from
Definition at line 14 of file Preamble.cc.
References Log(), and LOGDEBUG.
Referenced by SideCar::IO::Decoder::Decoder().
Logger::Log & Preamble::Log () static
Log device for Preamble objects.
Returns
log device
Definition at line 7 of file Preamble.cc.
References Logger::Log::Find().
Referenced by load().
ACE_OutputCDR & Preamble::write (ACE_OutputCDR & cdr) const
Write out the header to a CDR output stream.
NOTE: by design we only write out our time stamp – the byte order and size are handled by one of the IO::Sink classes.
Parameters
cdr CDR stream to write to
Returns
CDR stream written to
Definition at line 30 of file Preamble.cc.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/Preamble.h
/Users/howes/src/sidecar/IO/Preamble.cc