SideCar: SideCar::GUI::PPIDisplay::PPIWidget Class Reference
SideCar::GUI::PPIDisplay::PPIWidget Class Reference
Derivation of a QGLWidget widget that acts like a simple PPI display.
#include </Users/howes/src/sidecar/GUI/PPIDisplay/PPIWidget.h>
Public Slots
void addMagnifier (MagnifierWindow *magnifier)
Associate a new magnifier window with this view.
void removeMagnifier (MagnifierWindow *magnifier=0)
Remove a magnifier window from this view.
void saveMagnifiers (QSettings &settings) const
Save associated magnifier view settings.
void raiseMagnifiers ()
Make sure all magnifier windows hover above our window.
void centerAtCursor ()
Obtain the real-world coordinates of the current mouse cursor position, and then pan the viewport so that the coordinates are found at the center of the windoow.
void clearAll ()
Clear all of the layers: video, binary, extractions, bug plots, and TSPI plots.
void clearVideoBuffer ()
Clear the video data layer.
void clearBinaryBuffer ()
Clear the binary data layer.
void clearExtractions ()
Clear the extractions plot layer.
void clearRangeTruths ()
Clear the TSPI plot layer.
void clearBugPlots ()
Clear the user bug plot layer.
void redisplayVideo ()
Repaint all of the video data for the current rotation.
void redisplayBinary ()
Repaint all of the binary video data for the current rotation.
void processVideo (const MessageList &data)
Process one or more Video messages.
void processBinary (const MessageList &data)
Process one or more BinaryVideo messages.
void processExtractions (const MessageList &data)
Process one or more target Extractions messages.
void processRangeTruths (const MessageList &data)
Process one or more TSPI messages.
void processBugPlots (const MessageList &data)
Process one or more user plot messages.
void setPhantomCursor (const QPointF &pos)
Set the location of the phantom cursor.
void showPhantomCursor (bool state)
Change the visibility state of the phantom cursor.
void setCursorPosition (const QString &value)
void setShowCursorPosition (bool state)
Signals
void currentMessage (Messages::PRIMessage::Ref msg)
Notification of the latest incomin message received.
void currentCursorPosition (const QPointF &pos)
Notification of the current mouse position in real-world coordinates.
Public Member Functions
PPIWidget (QWidget *parent=0)
Constructor.
~PPIWidget ()
Destructor.
void localToRealWorld (int inX, int inY, GLdouble &outX, GLdouble &outY) const
Convert local (mouse) coordinates into real-world values.
void updateCursorPosition (CursorPosition &pos)
void pan (double xf, double yf)
Pan the view by fractions of the existing viewport dimensions.
void changeZoom (int change)
Change the zoom level for the viewport.
void initializeContext (GLdouble *modelViewMatrix)
Initialize a view context, either ourselves or that of a Magnifier object.
void renderScene (QGLWidget *widget)
Render a display into the given widget.
bool getShowPhantomCursor () const
Obtain the visibility of the phantom cursor.
bool getShowCursorPosition () const
Obtain the visibility of the cursor position tooltip.
void setSettingsKey (const QString &settingsKey)
Set the settings group key for us to use later when we must restore settings from a QSettings object.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the Log device to use for objects of this classs.
static QGLFormat GetGLFormat ()
Obtain the OpenGL configuration we want to use.
Detailed Description
Derivation of a QGLWidget widget that acts like a simple PPI display.
Incoming data arrives via the processVideo(), processBinary(), and processExtractions() slots. Each slot takes a reference to a MessageBlockList object which contains one or more ACE_Message_Block objects created by a separate reader thread. The incoming slot obtains a message object from the raw ACE_Message_Block, adds it to the History object, and if necessary, generates data for future display.
The Video and BinaryVideo processing paths render into an OffscreenBuffer object, using an OpenGL pixel buffer or a framebuffer object to do the dirty work. The paintGL() method of the PPIWidget uses the offscreen renderings to create the PPI display. Extraction reports exist as a list of points, which the paintGL() method renders directly to the main view.
This class supports the loading of an image file, which gets blended with the PPI image. The image has an associated opacity value (as do all of the other rendering images), which may be changed through the application's ConfigurationWindow object. For best results, the image file should be square, centered at the radar's center, and with a dimension 2 * rangeMax, the maximum range of the incoming radar reports.
Viewport Control
The user may manipulate the view by panning or zooming. Panning is accomplished by clicking the left mouse button while holding the SHIFT key down and then moving the mouse, or by using the arrow keys of the keyboard. The zoom level is controlled via the mouse scroll wheel, or by the letter keys 'I' and 'O' for zooming in and out.
Magnifiers
Instead of zooming the entire display, one can create a separate view window that only shows a subsection of the main view. To create a new magnification view, click the left mouse button down and then move the mouse to create a rectangle on the screen. When the left mouse button is released, a new Magnifier window object will pop up, showing the area circumscribed by the rectangle on the screen.
Definition at line 80 of file PPIWidget.h.
Constructor & Destructor Documentation
PPIWidget::PPIWidget (QWidget * parent = 0)
Constructor.
Do some construction here, but most of the OpenGL initialization is performed in the
initializeGL() method.
Parameters
parent parent object for automatic destruction
Definition at line 63 of file PPIWidget.cc.
References Log(), and LOGINFO.
PPIWidget::~PPIWidget ()
Destructor.
Clean up OpenGL objects not handled by Qt.
Definition at line 84 of file PPIWidget.cc.
References SideCar::GUI::PPIDisplay::ViewSettings::getRangeMax(), SideCar::GUI::OffscreenBuffer::getTexture(), SideCar::GUI::OffscreenBuffer::isValid(), Log(), and LOGINFO.
Member Function Documentation
void PPIWidget::addMagnifier (MagnifierWindow * magnifier) slot
Associate a new magnifier window with this view.
Parameters
magnifier MagnifierWindow object to associate
Definition at line 1575 of file PPIWidget.cc.
void PPIWidget::centerAtCursor () slot
Obtain the real-world coordinates of the current mouse cursor position, and then pan the viewport so that the coordinates are found at the center of the windoow.
Contrary to human factors orthodoxy, we also move the mouse pointer to the center of the window.
Definition at line 1431 of file PPIWidget.cc.
References clearBinaryBuffer(), clearVideoBuffer(), currentMessage(), localToRealWorld(), Log(), LOGINFO, and SideCar::GUI::PPIDisplay::ViewSettings::moveTo().
void PPIWidget::changeZoom (int change)
Change the zoom level for the viewport.
Zoom is represented as a zoom factor raised by a zoom power. This method affects the zoom power.
Parameters
change amount to change the zoom power
Definition at line 1230 of file PPIWidget.cc.
References SideCar::GUI::PPIDisplay::History::addBugPlot(), SideCar::GUI::PPIDisplay::ViewSettings::getZoomPower(), SideCar::GUI::MainWindowBase::initialize(), localToRealWorld(), Log(), LOGDEBUG, LOGINFO, LOGTIN, SideCar::GUI::PPIDisplay::ViewSettings::setZoomPower(), SideCar::GUI::PPIDisplay::ViewSettings::shift(), and SideCar::GUI::MainWindowBase::showAndRaise().
void SideCar::GUI::PPIDisplay::PPIWidget::currentCursorPosition (const QPointF & pos) signal
Notification of the current mouse position in real-world coordinates.
Parameters
pos real-world position
Referenced by initializeContext(), and localToRealWorld().
void SideCar::GUI::PPIDisplay::PPIWidget::currentMessage (Messages::PRIMessage::Ref msg) signal
Notification of the latest incomin message received.
Parameters
msg the last message
Referenced by centerAtCursor().
QGLFormat PPIWidget::GetGLFormat () static
Obtain the OpenGL configuration we want to use.
Returns
OpenGL format
Definition at line 54 of file PPIWidget.cc.
bool SideCar::GUI::PPIDisplay::PPIWidget::getShowCursorPosition () const inline
Obtain the visibility of the cursor position tooltip.
Returns
true if the tooltip is shown in the view
Definition at line 161 of file PPIWidget.h.
bool SideCar::GUI::PPIDisplay::PPIWidget::getShowPhantomCursor () const inline
Obtain the visibility of the phantom cursor.
Returns
true if the phantom cursor is visible in the view
Definition at line 155 of file PPIWidget.h.
void PPIWidget::initializeContext (GLdouble * modelViewMatrix)
Initialize a view context, either ourselves or that of a Magnifier object.
Parameters
modelViewMatrix storage for the model view matrix
Definition at line 179 of file PPIWidget.cc.
References SideCar::GUI::OffscreenBuffer::clearBuffer(), currentCursorPosition(), SideCar::GUI::VertexColorArray::draw(), SideCar::GUI::PPIDisplay::App::GetApp(), SideCar::GUI::ChannelImaging::getColor(), SideCar::GUI::PPIDisplay::BackgroundImageSettings::getFiltered(), SideCar::GUI::PPIDisplay::ViewSettings::getRangeMax(), SideCar::GUI::PPIDisplay::ViewSettings::getRangeMaxMax(), SideCar::GUI::ChannelImaging::getSize(), SideCar::GUI::OffscreenBuffer::getTexture(), SideCar::GUI::CLUT::getType(), SideCar::GUI::MainWindowBase::initialize(), Log(), LOGDEBUG, LOGERROR, LOGINFO, Utils::SineCosineLUT::lookup(), processBinary(), processBugPlots(), processExtractions(), processRangeTruths(), processVideo(), SideCar::GUI::VertexColorArray::push_back(), redisplayBinary(), redisplayVideo(), SideCar::GUI::RangeMap::render(), setPhantomCursor(), Logger::ProcLog::thrower(), and SideCar::GUI::Color::use().
Referenced by SideCar::GUI::PPIDisplay::MagnifierView::MagnifierView().
void PPIWidget::localToRealWorld (int inX, int inY, GLdouble & outX, GLdouble & outY) const
Convert local (mouse) coordinates into real-world values.
Parameters
inX local X value
inY local Y value
outX real-world X value output
outY real-world Y value output
Definition at line 1386 of file PPIWidget.cc.
References currentCursorPosition(), SideCar::GUI::OnOffSettingsBlock::isEnabled(), and SideCar::GUI::UnProjectPoint().
Referenced by centerAtCursor(), and changeZoom().
Logger::Log & PPIWidget::Log () static
Obtain the Log device to use for objects of this classs.
Returns
Loggger::Log reference
Definition at line 47 of file PPIWidget.cc.
References Logger::Log::Find().
Referenced by centerAtCursor(), changeZoom(), initializeContext(), PPIWidget(), processBinary(), processBugPlots(), processExtractions(), processRangeTruths(), processVideo(), raiseMagnifiers(), renderScene(), saveMagnifiers(), and ~PPIWidget().
void PPIWidget::pan (double xf, double yf)
Pan the view by fractions of the existing viewport dimensions.
For instance, pan(0.5, 0.25) will pan horizontally by 1/2 of the width, and 1/4 of the height of the viewport. Positive values move right and up, whereas negative values move left and down.
Parameters
xf horizontal fraction to pan
yf vertical fraction to pan
Definition at line 1224 of file PPIWidget.cc.
References SideCar::GUI::PPIDisplay::ViewSettings::shift().
void PPIWidget::processBinary (const MessageList & data) slot
Process one or more BinaryVideo messages.
Parameters
data container of BinarVideo message references
Definition at line 778 of file PPIWidget.cc.
References SideCar::GUI::PPIDisplay::History::addBinary(), Log(), LOGDEBUG, LOGINFO, LOGWARNING, and SideCar::GUI::PPIDisplay::History::showingLiveEntry().
Referenced by initializeContext().
void PPIWidget::processBugPlots (const MessageList & data) slot
Process one or more user plot messages.
Parameters
data container of user plot message references
Definition at line 854 of file PPIWidget.cc.
References SideCar::GUI::PPIDisplay::History::addBugPlot(), SideCar::GUI::PPIDisplay::History::Entry::getBugPlots(), SideCar::GUI::PPIDisplay::History::Entry::getExtractions(), SideCar::GUI::PPIDisplay::History::Entry::getRangeTruths(), SideCar::GUI::PPIDisplay::History::getViewedEntry(), Log(), LOGDEBUG, LOGINFO, SideCar::GUI::TargetPlotImaging::render(), and renderScene().
Referenced by initializeContext().
void PPIWidget::processExtractions (const MessageList & data) slot
Process one or more target Extractions messages.
Parameters
data container of Extractions message references
Definition at line 817 of file PPIWidget.cc.
References SideCar::GUI::PPIDisplay::History::addExtractions(), Log(), and LOGINFO.
Referenced by initializeContext().
void PPIWidget::processRangeTruths (const MessageList & data) slot
Process one or more TSPI messages.
Parameters
data container of TSPI message references
Definition at line 834 of file PPIWidget.cc.
References SideCar::GUI::PPIDisplay::History::addRangeTruth(), Log(), LOGDEBUG, and LOGINFO.
Referenced by initializeContext().
void PPIWidget::processVideo (const MessageList & data) slot
Process one or more Video messages.
Parameters
data container of Video message references
Definition at line 727 of file PPIWidget.cc.
References SideCar::GUI::PPIDisplay::History::addVideo(), SideCar::GUI::PPIDisplay::ViewSettings::getRangeFactor(), Log(), LOGINFO, LOGWARNING, SideCar::GUI::PPIDisplay::ViewSettings::setRangeFactorAndMax(), and SideCar::GUI::PPIDisplay::History::showingLiveEntry().
Referenced by initializeContext().
void PPIWidget::removeMagnifier (MagnifierWindow * magnifier = 0) slot
Remove a magnifier window from this view.
Parameters
magnifier MagnifierWindow object to remove
Definition at line 1581 of file PPIWidget.cc.
void PPIWidget::renderScene (QGLWidget * widget)
Render a display into the given widget.
Parameters
widget where to render
Definition at line 941 of file PPIWidget.cc.
References SideCar::GUI::PPIDisplay::ViewSettings::getRangeMax(), SideCar::GUI::PPIDisplay::History::getViewedEntry(), SideCar::GUI::PPIDisplay::ViewSettings::getX(), SideCar::GUI::PPIDisplay::ViewSettings::getY(), SideCar::GUI::PPIDisplay::ViewSettings::getZoom(), SideCar::GUI::OnOffSettingsBlock::isEnabled(), Log(), LOGINFO, Utils::SineCosineLUT::lookup(), redisplayBinary(), redisplayVideo(), SideCar::GUI::PPIDisplay::History::showingLiveEntry(), and SideCar::GUI::StencilBufferState::use().
Referenced by SideCar::GUI::PPIDisplay::MagnifierView::MagnifierView(), and processBugPlots().
void PPIWidget::saveMagnifiers (QSettings & settings) const slot
Save associated magnifier view settings.
Parameters
settings QSettings object to write into
Definition at line 1591 of file PPIWidget.cc.
References Log(), and LOGINFO.
void PPIWidget::setPhantomCursor (const QPointF & pos) slot
Set the location of the phantom cursor.
Parameters
pos location of the phantom cursor in real-world coordinates
Definition at line 1566 of file PPIWidget.cc.
Referenced by initializeContext().
void SideCar::GUI::PPIDisplay::PPIWidget::setSettingsKey (const QString & settingsKey) inline
Set the settings group key for us to use later when we must restore settings from a QSettings object.
Parameters
settingsKey group key to apply before accessing setting values
Definition at line 167 of file PPIWidget.h.
void PPIWidget::showPhantomCursor (bool state) slot
Change the visibility state of the phantom cursor.
Parameters
state true if the phantom cursor is shown
Definition at line 1605 of file PPIWidget.cc.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/PPIDisplay/PPIWidget.h
/Users/howes/src/sidecar/GUI/PPIDisplay/PPIWidget.cc