SideCar: UnitTest::TestObj Class Reference
UnitTest::TestObj Class Reference
Interface and baseline functionality for all unit test objects.
#include </Users/howes/src/sidecar/UnitTest/TestObj.h>
Public Member Functions
TestObj () throw ()
Default contructor.
TestObj (const std::string &name) throw ()
Contructor.
virtual ~TestObj ()
Destructor.
virtual int numTests () const throw ()
Get the number of tests perfomed by this object.
virtual RunResults & run (RunResults &rr) throw ()
Execute the unit test(s) this object represents.
virtual int mainRun (std::ostream *os=&std::cerr) throw ()
Utility method useful in main() to run unit tests.
void setTestName (const std::string &name) throw ()
Set the test name to the given value.
const std::string & testName () const throw ()
Get the name of this test object.
void _assertTrue (bool value, const char *expr, const char *file, int line) const throw (UnitTestException)
Assertion for a true value.
void _assertTrue (std::istream &value, const char *expr, const char *file, int line) const throw (UnitTestException)
Assertion for a good std::istream value.
void _assertFalse (bool value, const char *expr, const char *file, int line) const throw (UnitTestException)
Assertion for a false value.
void _assertFalse (std::istream &value, const char *expr, const char *file, int line) const throw (UnitTestException)
Assertion for a good std::istream value.
template<typename T >
void _assertEqual (const T &expected, const T &actual, const char *file, int line) const throw (UnitTestException)
Assertion that two values of some type T are equal.
template<typename T >
void _assertEqual (const T *expected, const T *actual, const char *file, int line) const throw (UnitTestException)
Assertion that two values of some type pointer are equal.
void _assertEqual (std::string expected, std::string actual, const char *file, int line) const throw (UnitTestException)
Assertion that two strings are equal.
void _assertEqual (double expected, double actual, const char *file, int line) const throw (UnitTestException)
void _assertEqual (double expected, double actual, double epsilon, const char *file, int line) const throw (UnitTestException)
Assertion that two values are equal within some tolerance factor.
template<typename T >
void _assertNotEqual (const T &expected, const T &actual, const char *file, int line) const throw (UnitTestException)
Assertion that two values are NOT equal.
template<typename T >
void _assertNotEqual (const T *expected, const T *actual, const char *file, int line) const throw (UnitTestException)
void _assertNotEqual (std::string expected, std::string actual, const char *file, int line) const throw (UnitTestException)
Assertion that two strings are NOT equal.
void _assertNotEqual (double expected, double actual, const char *file, int line) const throw (UnitTestException)
void _assertNotEqual (double expected, double actual, double epsilon, const char *file, int line) const throw (UnitTestException)
Assertion that two values are NOT equal within some tolerance factor.
Protected Member Functions
virtual void test ()
Method to perform the unit test.
Detailed Description
Interface and baseline functionality for all unit test objects.
Can be used as a simple unit test by subclassing and overriding TestObj::test() method. Here's a simple check to make sure that 1 is really one.
struct Foo : public TestObj
{
Foo() : one_(1) {}
void test() { assertEqual(1, one_); }
int one_;
};
int
main()
{
return Foo().mainRun();  // run the above test
}
Please note that assertEqual above is not a member of TestObj or of Foo. Rather, it is a C preprocessor function macro found in TestObj.h. Although this is a gross violation of standard coding practices, these C preprocessor function macros allow a unit test to record the file and line number where the test was if it failed. They do so by using the values of the FILE and LINE C preprocessor value macros as arguments to the TestObj methods they invoke (the alternative would be to have the developer type in FILE and LINE for each invocation of _assertEqual() or its kin)
See TestObj Function Macros for a documentation on these function macros.
Definition at line 214 of file TestObj.h.
Constructor & Destructor Documentation
UnitTest::TestObj::TestObj (const std::string & name) throw () inline
Contructor.
Takes the given name as its own. Note that test names may be changed by a container object.
Parameters
name name of this unit test object.
Definition at line 226 of file TestObj.h.
Member Function Documentation
template<typename T > void UnitTest::TestObj::_assertEqual (const T & expected, const T & actual, const char * file, int line) const throw (UnitTestException) inline
Assertion that two values of some type T are equal.
Raises a UnitTestException exception if they are different. Attempts to compare the values to each other. If they are different, then compare their string representations.
Parameters
expected value that was expected in the unit test
actual value that was obtained from the unit test
file name of the file in which the assertion was made
line line number of the file where the assertion was made
Definition at line 342 of file TestObj.h.
template<typename T > void UnitTest::TestObj::_assertEqual (const T * expected, const T * actual, const char * file, int line) const throw (UnitTestException) inline
Assertion that two values of some type pointer are equal.
Raises a UnitTestException exception if they are different. Attempts to compare the values to each other. If they are different, then compare their string representations.
Parameters
expected value that was expected in the unit test
actual value that was obtained from the unit test
file name of the file in which the assertion was made
line line number of the file where the assertion was made
Definition at line 363 of file TestObj.h.
void UnitTest::TestObj::_assertEqual (std::string expected, std::string actual, const char * file, int line) const throw (UnitTestException) inline
Assertion that two strings are equal.
Raises a UnitTestException exception if they are different.
Parameters
expected value that was expected in the unit test
actual value that was obtained from the unit test
file name of the file in which the assertion was made
line line number of the file where the assertion was made
Definition at line 381 of file TestObj.h.
void TestObj::_assertEqual (double expected, double actual, double epsilon, const char * file, int line) const throw (UnitTestException)
Assertion that two values are equal within some tolerance factor.
Raises a UnitTestException exception if two values differ more than the given epsilon value. Passes other arguments to exception constructor.
Parameters
expected value that was expected in the unit test
actual value that was obtained from the unit test
epsilon tolerance factor used for testing
file name of the file in which the assertion was made
line line number of the file where the assertion was made
Definition at line 90 of file TestObj.cc.
References UnitTest::UnitTestException::file(), and UnitTest::UnitTestException::line().
void UnitTest::TestObj::_assertFalse (bool value, const char * expr, const char * file, int line) const throw (UnitTestException) inline
Assertion for a false value.
Raises a UnitTestException exception if the given value is true. Passes other arguments to exception constructor.
Parameters
value value to check
expr string representation of value
file name of the file in which the assertion was made
line line number of the file where the assertion was made
Definition at line 310 of file TestObj.h.
void UnitTest::TestObj::_assertFalse (std::istream & value, const char * expr, const char * file, int line) const throw (UnitTestException) inline
Assertion for a good std::istream value.
Raises a UnitTestException exception if the given value is not true. Passes other arguments to exception constructor.
Parameters
value value to check
expr string representation of value
file name of the file in which the assertion was made
line line number of the file where the assertion was made
Definition at line 325 of file TestObj.h.
template<typename T > void UnitTest::TestObj::_assertNotEqual (const T & expected, const T & actual, const char * file, int line) const throw (UnitTestException) inline
Assertion that two values are NOT equal.
Raises a UnitTestException exception if two values are exactly the same. Equality is checked using the '!=' operator, and then by comparing the textual representations of the given values (using the toString() template method). Passes other arguments to exception constructor.
Parameters
expected value that was expected in the unit test
actual value that was obtained from the unit test
file name of the file in which the assertion was made
line line number of the file where the assertion was made
Definition at line 418 of file TestObj.h.
void UnitTest::TestObj::_assertNotEqual (std::string expected, std::string actual, const char * file, int line) const throw (UnitTestException) inline
Assertion that two strings are NOT equal.
Raises a UnitTestException exception if they are the same.
Parameters
expected value that was expected in the unit test
actual value that was obtained from the unit test
file name of the file in which the assertion was made
line line number of the file where the assertion was made
Definition at line 447 of file TestObj.h.
void TestObj::_assertNotEqual (double expected, double actual, double epsilon, const char * file, int line) const throw (UnitTestException)
Assertion that two values are NOT equal within some tolerance factor.
Raises a UnitTestException exception if two values do not differ more than the given epsilon value. Passes other arguments to exception constructor.
Parameters
expected value that was expected in the unit test
actual value that was obtained from the unit test
epsilon tolerance factor used for testing
file name of the file in which the assertion was made
line line number of the file where the assertion was made
Definition at line 98 of file TestObj.cc.
References UnitTest::UnitTestException::file(), UnitTest::UnitTestException::line(), UnitTest::UnitTestException::testName(), and UnitTest::UnitTestException::UnitTestException().
void UnitTest::TestObj::_assertTrue (bool value, const char * expr, const char * file, int line) const throw (UnitTestException) inline
Assertion for a true value.
Raises a UnitTestException exception if the given value is not true. Passes other arguments to exception constructor.
Parameters
value value to check
expr string representation of value
file name of the file in which the assertion was made
line line number of the file where the assertion was made
Definition at line 281 of file TestObj.h.
void UnitTest::TestObj::_assertTrue (std::istream & value, const char * expr, const char * file, int line) const throw (UnitTestException) inline
Assertion for a good std::istream value.
Raises a UnitTestException exception if the given value is not true. Passes other arguments to exception constructor.
Parameters
value value to check
expr string representation of value
file name of the file in which the assertion was made
line line number of the file where the assertion was made
Definition at line 295 of file TestObj.h.
int TestObj::mainRun (std::ostream * os = &std::cerr) throw () virtual
Utility method useful in main() to run unit tests.
Prints out the unit test results to the given stream (if not NULL), and then returns EXIT_SUCCESS or EXIT_FAILURE depending on whether all the test pass.
Parameters
os stream to write the unit test results to.
Returns
EXIT_SUCCESS if all tests pass; otherwise EXIT_FAILURE.
Definition at line 130 of file TestObj.cc.
References UnitTest::UnitTestException::testName().
virtual int UnitTest::TestObj::numTests () const throw () inline virtual
Get the number of tests perfomed by this object.
Subclasses that represent multiple test would return something different.
Returns
the number of unit tests this object represents.
Reimplemented in UnitTest::ProcSuite< T >, and UnitTest::Suite.
Definition at line 237 of file TestObj.h.
RunResults & TestObj::run (RunResults & rr) throw () virtual
Execute the unit test(s) this object represents.
This is basically a wrapper for the protected TestObj::test method that traps an records any exceptions that occur during the unit test.
Parameters
rr collector of run statistics
Returns
value of input parameter
Reimplemented in UnitTest::ProcSuite< T >, and UnitTest::Suite.
Definition at line 62 of file TestObj.cc.
References UnitTest::UnitTestException::testName(), and UnitTest::UnitTestException::UnitTestException().
Referenced by UnitTest::ProcSuite< T >::run().
void UnitTest::TestObj::setTestName (const std::string & name) throw () inline
Set the test name to the given value.
Derived classes and container clases use this to manipulate the test name.
Parameters
name new name to assume
Definition at line 262 of file TestObj.h.
Referenced by UnitTest::ProcSuite< T >::run().
virtual void UnitTest::TestObj::test () inline protected virtual
Method to perform the unit test.
Derived classes must override to do something useful. Default behavior is to assert false, which always raises an exception.
Reimplemented in UnitTest::ProcSuite< T >, and SideCar::Algorithms::TestBase.
Definition at line 477 of file TestObj.h.
References assertTrue.
const std::string& UnitTest::TestObj::testName () const throw () inline
Get the name of this test object.
Returns
test name
Definition at line 268 of file TestObj.h.
Referenced by UnitTest::ProcSuite< T >::run(), and UnitTest::ProcSuite< T >::test().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/UnitTest/TestObj.h
/Users/howes/src/sidecar/UnitTest/TestObj.cc