SideCar: Utils::AtomicOp Class Reference
Utils::AtomicOp Class Reference
Class that increments and decrements an integral value in an atomic way, thus safe for use in threaded processing.
#include </Users/howes/src/sidecar/Utils/AtomicOp.h>
Public Types
using ValueType = long
Public Member Functions
AtomicOp (ValueType value=0)
Constructor.
void operator++ ()
Atomically increment the held counter value.
ValueType operator-- ()
Atomically decrement the held counter value.
ValueType getValue () const
Obtain the current value.
bool operator< (const AtomicOp &rhs) const
Determine if held value is less than the value of another AtomicOp.
bool operator== (const AtomicOp &rhs) const
Determine if held value is the same as the value of another AtomicOp.
Detailed Description
Class that increments and decrements an integral value in an atomic way, thus safe for use in threaded processing.
Definition at line 12 of file AtomicOp.h.
Constructor & Destructor Documentation
Utils::AtomicOp::AtomicOp (ValueType value = 0) inline
Constructor.
Parameters
value initial value for the counter
Definition at line 21 of file AtomicOp.h.
Member Function Documentation
ValueType Utils::AtomicOp::getValue () const inline
Obtain the current value.
Returns
current value
Definition at line 37 of file AtomicOp.h.
Referenced by operator<(), and operator==().
ValueType Utils::AtomicOp::operator-- () inline
Atomically decrement the held counter value.
Returns
true if new counter value is zero
Definition at line 31 of file AtomicOp.h.
bool Utils::AtomicOp::operator< (const AtomicOp & rhs) const inline
Determine if held value is less than the value of another AtomicOp.
Parameters
rhs value to compare
Returns
true if so
Definition at line 45 of file AtomicOp.h.
References getValue().
bool Utils::AtomicOp::operator== (const AtomicOp & rhs) const inline
Determine if held value is the same as the value of another AtomicOp.
Parameters
rhs value to compare
Returns
true if so
Definition at line 53 of file AtomicOp.h.
References getValue().
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/Utils/AtomicOp.h