SideCar: SideCar::Algorithms::TChannelBuffer< T > Class Template Reference
SideCar::Algorithms::TChannelBuffer< T > Class Template Reference
Templated class for a input channel buffer.
#include </Users/howes/src/sidecar/Algorithms/ChannelBuffer.h>
Public Member Functions
TChannelBuffer (ManyInAlgorithm &owner, size_t channelIndex, size_t maxBufferSize)
Constructor.
T::Ref getFront () const
Obtain the oldest message in the queue.
T::Ref popFront ()
Remove the oldest message in the queue return it.
void getSlice (int offset, int span, VsipComplexVector &slice, bool doPop)
Obtain a slide of the data, copying it into a VSIPL vector.
Public Member Functions inherited from SideCar::Algorithms::ChannelBuffer
ChannelBuffer (ManyInAlgorithm &processor, size_t channelIndex, size_t maxBufferSize)
Constructor.
virtual ~ChannelBuffer ()
Destructor.
size_t getChannelIndex () const
Obtain the channel index for this object.
size_t getMaxBufferSize () const
Obtain the maximum number of messages to hold.
size_t size () const
Obtain the number of messages in the buffer.
bool isEmpty () const
Determine if the buffer is empty.
bool isEnabled () const
Determine if the buffer is enabled.
uint32_t getNextSequenceCounter () const
Obtain the sequence counter of the first message in the queue.
bool pruneToSequenceCounter (uint32_t sequenceCounter)
Remove messages from the front of the queue whose sequence counter values are less than the given value.
virtual void setMaxBufferSize (size_t maxBufferSize)
Change the maximum number of messages to hold.
virtual void setEnabled (bool value)
Change the enabled state.
virtual void reset ()
Reset the buffer by forgetting any held messagess.
bool addData (const Messages::PRIMessage::Ref &msg)
Add a message to the queue.
virtual bool makeEnabledParameter ()
Create a runtime parameter to control the channel enabled state.
virtual bool makeEnabledParameter (const std::string &shortName, const std::string &longName)
Create a runtime parameter to control the channel enabled state.
const_iterator begin () const
Obtain read-only iterator to the first sample value in the message.
const_iterator end () const
Obtain read-only iterator to the last + 1 sample value in the message.
Messages::PRIMessage::Ref getFront () const
Obtain the oldest message in the queue.
Messages::PRIMessage::Ref popFront ()
Remove the oldest message in the queue.
Public Member Functions inherited from SideCar::Algorithms::TProcessor< TChannelBuffer< T >, T >
TProcessor (TChannelBuffer< T > *obj, Proc proc)
Constructor.
bool process (const Messages::Header::Ref &msg)
Implementation of the Processor base class method.
Public Member Functions inherited from SideCar::Algorithms::Processor
virtual ~Processor ()
Destructor.
Additional Inherited Members
Public Types inherited from SideCar::Algorithms::ChannelBuffer
using Container = std::deque< Messages::PRIMessage::Ref >
using const_iterator = Container::const_iterator
Public Types inherited from SideCar::Algorithms::TProcessor< TChannelBuffer< T >, T >
using Proc = boost::function< bool(TChannelBuffer< T > *, typename T::Ref)>
Type definition for a method of class P that can process messages of class M.
Static Public Member Functions inherited from SideCar::Algorithms::ChannelBuffer
static std::string MakeGenericShortName (int index)
Create generic short name for the input channel.
static std::string MakeGenericLongName (int index)
Create generic long name for the input channel.
Protected Member Functions inherited from SideCar::Algorithms::ChannelBuffer
void popFrontInternal ()
Remove the oldest message from the queue.
void pruneToMaxBufferSize ()
Remove messages until the size of the buffer is less than or equal to maxBufferSize_.
virtual void enabledChanged (const Parameter::BoolValue &parameter)
Callback invoked when the 'enabled' parameter state changes.
Detailed Description
template<typename T>
class SideCar::Algorithms::TChannelBuffer< T >
Templated class for a input channel buffer.
Primary use is for algorithms that take in more than one input channel. It provides an API that allows the algorithm to obtain messsages across all channels synchronized by their sequence number.`
Definition at line 228 of file ChannelBuffer.h.
Constructor & Destructor Documentation
template<typename _T > SideCar::Algorithms::TChannelBuffer< _T >::TChannelBuffer (ManyInAlgorithm & owner, size_t channelIndex, size_t maxBufferSize)
Constructor.
Registers ourselves with the owner as the processor for the channel.
Parameters
master the algorithm doing the processing
channelIndex the index of the channel we are processing
maxBufferSize the maximum number of messages to queue
Definition at line 323 of file ChannelBuffer.h.
References SideCar::Algorithms::Algorithm::addProcessor().
Member Function Documentation
template<typename T> T::Ref SideCar::Algorithms::TChannelBuffer< T >::getFront () const inline
Obtain the oldest message in the queue.
NOTE: only call if the queue is not empty.
Returns
T reference
Definition at line 246 of file ChannelBuffer.h.
Referenced by SideCar::Algorithms::SimpleOp::SimpleOp(), and SideCar::Algorithms::Summer::Summer().
template<typename T> void SideCar::Algorithms::TChannelBuffer< T >::getSlice (int offset, int span, VsipComplexVector & slice, bool doPop) inline virtual
Obtain a slide of the data, copying it into a VSIPL vector.
NOTE: only valid if isEmpty() is false. Always works on the first message in the FIFO queue. Implementation of ChannelBuffer API.
Treats the message data as interleved I/Q data. Creates complex values from subsequent values and adds them to the given VSIPL vector container. If the message is too short to accomodate the span parameter, pads the VSIPL vector with 0,0 complex values.
Parameters
offset index of the first sample value to use
span count of sample values to gather
slice container to hold the resulting complex values
doPop if true, remove the first message from the queue after working with it
Implements SideCar::Algorithms::ChannelBuffer.
Definition at line 281 of file ChannelBuffer.h.
template<typename T> T::Ref SideCar::Algorithms::TChannelBuffer< T >::popFront () inline
Remove the oldest message in the queue return it.
NOTE: only call if the queue is not empty.
Returns
T reference
Definition at line 256 of file ChannelBuffer.h.
Referenced by SideCar::Algorithms::ManyInAlgorithm::getNumInfoSlots(), SideCar::Algorithms::MatchedFilter::reset(), SideCar::Algorithms::MatchedFilter::shutdown(), SideCar::Algorithms::SimpleOp::SimpleOp(), and SideCar::Algorithms::Summer::Summer().
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/Algorithms/ChannelBuffer.h