SideCar: SideCar::IO::GatherWriter Class Reference
SideCar::IO::GatherWriter Class Reference
Collector of CDR-encoded SideCar messages for writing to a IO::Writer device once some limit has been reached.
#include </Users/howes/src/sidecar/IO/GatherWriter.h>
Public Member Functions
GatherWriter (Writer &writer)
Default constructor.
GatherWriter (Writer &writer, size_t sizeLimit, size_t countLimit)
Constructor.
~GatherWriter ()
Destructor.
size_t getSizeLimit () const
Obtain the current message size limit.
void setSizeLimit (size_t sizeLimit)
Change the message size limit.
size_t getCountLimit () const
Obtain the current message count limit.
void setCountLimit (size_t countLimit)
Change the message count limit.
bool add (ACE_Message_Block *data)
Add encoded message data to the cache.
void flush ()
Force the write of any cached encoded message data.
bool isOK () const
Determine if all writes have succeeded so far.
size_t getSize () const
Obtain the current accumulated message size.
size_t getCount () const
Obtain the current accumulated message count.
Static Public Member Functions
static Logger::Log & Log ()
Log device to use for GatherWriter object messages.
Detailed Description
Collector of CDR-encoded SideCar messages for writing to a IO::Writer device once some limit has been reached.
Contains two parameters that control how many messages it collects before ending to the IO::Writer device:
sizeLimit – number of bytes to collect before sending
countLimit – number of messages to collect before sending
If neither limit is set, or both are set to zero, then the collector will simply write each message as it receives them.
Definition at line 21 of file GatherWriter.h.
Constructor & Destructor Documentation
GatherWriter::GatherWriter (Writer & writer)
Default constructor.
Initializes limits to zero, disabling caching.
Parameters
writer device to use to write out message data
Definition at line 14 of file GatherWriter.cc.
SideCar::IO::GatherWriter::GatherWriter (Writer & writer, size_t sizeLimit, size_t countLimit)
Constructor.
Initializes limits to given values.
Parameters
writer device to use to write out message data
sizeLimit number of bytes to collect before sending
countLimit number of messages to collect before sending
GatherWriter::~GatherWriter ()
Destructor.
Flushes any held data.
Definition at line 21 of file GatherWriter.cc.
References flush().
Member Function Documentation
bool GatherWriter::add (ACE_Message_Block * data)
Add encoded message data to the cache.
Parameters
data encoded message data
Returns
true if no error
Definition at line 70 of file GatherWriter.cc.
References flush(), Log(), LOGDEBUG, LOGERROR, and LOGINFO.
Referenced by SideCar::Algorithms::Recorder::stop(), and SideCar::IO::FileWriterTask::svc().
size_t SideCar::IO::GatherWriter::getCount () const inline
Obtain the current accumulated message count.
Returns
held message count
Definition at line 103 of file GatherWriter.h.
size_t SideCar::IO::GatherWriter::getCountLimit () const inline
Obtain the current message count limit.
Returns
count limit
Definition at line 67 of file GatherWriter.h.
size_t SideCar::IO::GatherWriter::getSize () const inline
Obtain the current accumulated message size.
Returns
held message byte count
Definition at line 97 of file GatherWriter.h.
size_t SideCar::IO::GatherWriter::getSizeLimit () const inline
Obtain the current message size limit.
Returns
size limit
Definition at line 55 of file GatherWriter.h.
bool SideCar::IO::GatherWriter::isOK () const inline
Determine if all writes have succeeded so far.
Returns
true if so.
Definition at line 91 of file GatherWriter.h.
Referenced by SideCar::Algorithms::Recorder::stop(), and SideCar::IO::FileWriterTask::svc().
Logger::Log & GatherWriter::Log () static
Log device to use for GatherWriter object messages.
Has the name "SideCar.IO.GatherWriter.
Returns
log device to use
Definition at line 8 of file GatherWriter.cc.
References Logger::Log::Find().
Referenced by add(), flush(), setCountLimit(), and setSizeLimit().
void GatherWriter::setCountLimit (size_t countLimit)
Change the message count limit.
Parameters
countLimit new count limit
Definition at line 36 of file GatherWriter.cc.
References flush(), Log(), and LOGINFO.
void GatherWriter::setSizeLimit (size_t sizeLimit)
Change the message size limit.
Parameters
sizeLimit new size limit
Definition at line 27 of file GatherWriter.cc.
References flush(), Log(), and LOGINFO.
Referenced by SideCar::Algorithms::Recorder::stop(), and SideCar::IO::FileWriterTask::svc().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/GatherWriter.h
/Users/howes/src/sidecar/IO/GatherWriter.cc