SideCar: SideCar::IO::Decoder Class Reference
SideCar::IO::Decoder Class Reference
Demarshalling class that converts raw bytes from readers into objects.
#include </Users/howes/src/sidecar/IO/Decoder.h>
Public Member Functions
Decoder (ACE_Message_Block *data)
Constructor.
~Decoder ()
Destructor.
template<typename T >
boost::shared_ptr< T > decode ()
Type-specific extractor for objects.
const Preamble & getPreamble () const
bool isValid () const
size_t getMessageSize () const
Obtain the message size as found in the message Preamble header.
Static Public Member Functions
static Logger::Log & Log ()
Log device for Decoder objects.
Detailed Description
Demarshalling class that converts raw bytes from readers into objects.
Contains template methods which rely on object facilities to do the actual extraction from a CDR stream.
Definition at line 17 of file Decoder.h.
Constructor & Destructor Documentation
Decoder::Decoder (ACE_Message_Block * data)
Constructor.
Initializes an input CDR stream with data. Makes a "duplicate" of the ACE_Data_Block object held by the given ACE_Message_Block, which just increments the reference count in the ACE_Data_Block object. This results in sharing of the raw data between the given ACE_Message_Block and the ACE_InputCDR object. Extracts the first sizeof(Preamble) bytes into the preamble_ attribute.
Parameters
data container with the data to decode. NOTE: assumes ownership of the give message block. Use data->duplicate() to keep ownership of the message block.
Definition at line 20 of file Decoder.cc.
References SideCar::IO::Preamble::getSize(), SideCar::IO::Preamble::load(), Log(), and LOGDEBUG.
Decoder::~Decoder ()
Destructor.
Releases held data block.
Definition at line 39 of file Decoder.cc.
Member Function Documentation
template<typename T > boost::shared_ptr<T> SideCar::IO::Decoder::decode () inline
Type-specific extractor for objects.
Relies on the object type to create itself using data found in a CDR stream. The template parameter must provide a Make factory method that takes a Decoder reference as its sole argument.
Returns
reference to created message.
Definition at line 48 of file Decoder.h.
References SideCar::IO::Preamble::isValid().
size_t SideCar::IO::Decoder::getMessageSize () const inline
Obtain the message size as found in the message Preamble header.
Returns
message size
Definition at line 58 of file Decoder.h.
Referenced by SideCar::IO::StreamReader::fetchInput().
Logger::Log & Decoder::Log () static
Log device for Decoder objects.
Returns
log device
Definition at line 12 of file Decoder.cc.
References Logger::Log::Find().
Referenced by Decoder().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/Decoder.h
/Users/howes/src/sidecar/IO/Decoder.cc