SideCar: SideCar::IO::ZeroconfRegistry Class Reference
SideCar::IO::ZeroconfRegistry Class Reference
Registry of Zeroconf types values used within the SideCar system.
#include </Users/howes/src/sidecar/IO/ZeroconfRegistry.h>
Public Types
enum ID {
kPublisher = 0, kSubscriber, kRunnerStatusCollector, kRunnerStatusEmitter,
kStateEmitter, kStateCollector, kRunnerRemoteController, kNumTypes
}
Defined Zeroconf types.
Static Public Member Functions
static const char * GetType (ID id)
Obtain the Zeroconf type string for a given ID.
static ID GetTwin (ID id)
Locate the twin of this ID.
static std::string MakeZeroconfType (const char *type, const std::string &subType)
Construct a valid SideCar Zeroconf type string for a type and a subtype.
Detailed Description
Registry of Zeroconf types values used within the SideCar system.
Collected here to make it easier to find the actual values used; previously, they were scattered around the source tree.
Definition at line 12 of file ZeroconfRegistry.h.
Member Enumeration Documentation
enum SideCar::IO::ZeroconfRegistry::ID
Defined Zeroconf types.
Entries here should be entered in pairs, at least at the start of the list: the 'twin' logic below depends on pair diffences existing only in the least significant bit.
Definition at line 19 of file ZeroconfRegistry.h.
Member Function Documentation
static ID SideCar::IO::ZeroconfRegistry::GetTwin (ID id) inline static
Locate the twin of this ID.
A subscriber's twin is its publisher, and a status collector's twin is its emitter
Parameters
id the value to work with
Returns
the twin value
Definition at line 49 of file ZeroconfRegistry.h.
References MakeZeroconfType().
Referenced by SideCar::IO::ZeroconfTypes::TZCType< id >::GetTwinZeroconfType().
const char * ZeroconfRegistry::GetType (ID id) static
Obtain the Zeroconf type string for a given ID.
NOTE: DO NOT inline this, or the kTypes_ member may not initialize properly.
Parameters
id which type to obtain
Returns
NULL-terminated C string
Definition at line 20 of file ZeroconfRegistry.cc.
Referenced by SideCar::Algorithms::BugCollectorUtils::BugPlotSubscriber::BugPlotSubscriber(), SideCar::Runner::StatusEmitter::GetCollectorType(), SideCar::Runner::StatusEmitter::GetEmitterType(), SideCar::IO::ZeroconfTypes::TZCType< id >::GetTwinZeroconfType(), SideCar::IO::ZeroconfTypes::TZCType< id >::GetZeroconfType(), and SideCar::GUI::ZeroconfMonitor::MainWindow::MainWindow().
std::string ZeroconfRegistry::MakeZeroconfType (const char * type, const std::string & subType) static
Construct a valid SideCar Zeroconf type string for a type and a subtype.
Parameters
type the main type to use (eg. _scPub._tcp)
subType the data type restriction (eg. Video)
Returns
combined type + subtype (eg. _scPub._tcp,_Video)
Definition at line 26 of file ZeroconfRegistry.cc.
Referenced by SideCar::Algorithms::BugCollectorUtils::BugPlotSubscriber::BugPlotSubscriber(), GetTwin(), SideCar::IO::ZeroconfTypes::TZCType< id >::MakeTwinZeroconfType(), and SideCar::IO::ZeroconfTypes::TZCType< id >::MakeZeroconfType().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/ZeroconfRegistry.h
/Users/howes/src/sidecar/IO/ZeroconfRegistry.cc