SideCar: SideCar::GUI::Master::ControllerItem Class Reference
SideCar::GUI::Master::ControllerItem Class Reference
Derivation of TaskItem that represents an Algorithms::Controller object of an IO::Stream.
#include </Users/howes/src/sidecar/GUI/Master/ControllerItem.h>
Public Member Functions
ControllerItem (const Algorithms::ControllerStatus &status, StreamItem *parent)
Constructor.
QVariant getNameDataValue (int role) const
Obtain the data value for the ServicesModel::kName column, which displays the name of the TreeViewItem.
QVariant getRecordingDataValue (int role) const
Override of TreeViewItem method.
QVariant getPendingCountValue (int role) const
Obtain the data value for the ServicesModel::kPending column, which displays the pending queue size of this item.
QVariant getRateDataValue (int role) const
Obtain the data value for the ServicesModel::kRate column, which displays the message processing rate of the TreeViewItem.
QVariant getInfoDataValue (int role) const
Override of TreeViewItem method.
bool canRecord () const
bool willRecord () const
bool isRecording () const
bool canEdit () const
Override of TreeViewItem method.
int getRecordingQueueCount () const
bool getParameters (XmlRpc::XmlRpcValue &definition) const
Obtain the current runtime parameter values from the XML-RPC server of the runner process hosting the Controller.
bool setParameters (const XmlRpc::XmlRpcValue &updates) const
Submit new runtime parameter values to the XML-RPC server of the runner process hosting the Controller.
QString getFormattedProcessingTime (double time) const
int getDropCount () const
int getDupeCount () const
Public Member Functions inherited from SideCar::GUI::Master::TaskItem
TaskItem (const IO::TaskStatus &status, StreamItem *parent)
Constructor.
void updateCollectionStats (CollectionStats &stats) const
Prototype for method to update a CollectionStats object with statistics provided by a TreeViewItem derivative.
QVariant getNameDataValue (int role) const
Obtain the data value for the ServicesModel::kName column, which displays the name of the TreeViewItem.
QVariant getStateDataValue (int role) const
Obtain the data value for the ServicesModel::kState column, which displays the processing state of the TreeViewItem.
QVariant getPendingCountValue (int role) const
Obtain the data value for the ServicesModel::kPending column, which displays the pending queue size of this item.
QVariant getRateDataValue (int role) const
Obtain the data value for the fourth column, which displays the message processing rate of the TaskItem.
QVariant getErrorDataValue (int role) const
Obtain the data value for the ServicesModel::kError column, which displays any error text from the TreeViewItem.
QVariant getInfoDataValue (int role) const
Obtain the data value for the ServicesModel::kInfo column, which displays miscellaneous informational data of the TreeViewItem.
IO::ProcessingState::Value getProcessingState () const
const QString & getError () const
const QString & getConnectionInfo () const
int getMessageCount () const
Obtain the message count from the last status entry.
int getByteRate () const
Obtain the byte rate from the last status container.
int getMessageRate () const
Obtain the message rate from the last status container.
int getPendingQueueCount () const
bool isUsingData () const
StreamItem * getParent () const
void formatChangedParameters (const XmlRpc::XmlRpcValue &definitions, QStringList &changes) const
QString getParameterChangedHeading () const
Public Member Functions inherited from SideCar::GUI::Master::TreeViewItem
~TreeViewItem ()
Destructor.
virtual void initialize ()
Initialize this object's internal state.
const IO::StatusBase & getStatus () const
Obtain the latest IO::StatusBase object received for this object.
bool update (const IO::StatusBase &status)
Update the TreeViewItem held status.
bool isOK () const
bool isProcessing () const
Determine if the object is in a 'processing' state: auto-diagnostic, calibration, or run.
ActiveState getActiveState () const
Obtain the current ActiveState value for this object.
QVariant getData (int column, int role) const
Obtain the data point to use for a specific role in a given column.
virtual QVariant getHostDataValue (int role) const
Obtain the data value for the ServicesModel::kHost column, which displays the host name of the machine where the object is running.
virtual QColor getForegroundColor (int column) const
Obtain the foreground color to use for the contents of a given column.
virtual QFont getFont (int column) const
Obtain the font to use for the contents of a given column.
virtual int getAlignment (int columnt) const
Obtain the alignment (horizontal and vertical) to use for the contents of a given column.
virtual bool canExpand () const
Determine if the TreeViewItem is expandable.
const QString & getName () const
Obtain the object's name.
const QString & getFullName () const
Get the full name of the item.
void insertChild (int row, TreeViewItem *child)
Insert a child, renumbering the indices of all children after it.
void appendChild (TreeViewItem *child)
Add a child.
void removeChild (int index)
Remove the child at a given index.
TreeViewItem * getChild (int index) const
Obtain the child associated with a given index value.
int getNumChildren () const
Obtain the number of children.
int getIndex () const
Obtain the index of this object in the context of our parent's children array.
TreeViewItem * getParent () const
Obtain the parent of this TreeViewItem object.
int getParentIndex () const
Obtain the index value of the parent object (equivalent to getParent()->getIndex().
ChildrenIterator getChildrenIterator () const
Obtain a Java-style iterator for the children array.
bool isExpanded () const
Determine if the object is expanded.
void setExpanded (bool expanded)
Change the expansion attribute of the object.
int getInsertionPoint (const QString &name) const
Obtain the row where the given name could be inserted without disturbing the ordering of the existing rows.
virtual bool isFiltered (const QString &filter) const
Determine if this item contains the given filter string.
Protected Member Functions
void fillCollectionStats (CollectionStats &stats) const
void afterUpdate ()
Override of TreeViewItem method.
const Algorithms::ControllerStatus & getStatus () const
Obtain the type-cast status container sent by a Algorithms::Controller object.
Protected Member Functions inherited from SideCar::GUI::Master::TaskItem
void beforeUpdate ()
Hook invoked before a status update.
void afterUpdate ()
Hook invoked after a status update.
Protected Member Functions inherited from SideCar::GUI::Master::TreeViewItem
TreeViewItem ()
Constructor for the RootItem object (which has no parent).
TreeViewItem (const IO::StatusBase &status, TreeViewItem *parent)
Constructor for all derived classes except RootItem.
void setName (const QString &name)
void setOK (bool ok)
void setProcessing (bool processing)
void setProcessingState (IO::ProcessingState::Value state)
void setActiveState (ActiveState activeState)
template<typename T >
const T & getStatusT () const
virtual void childAdded (TreeViewItem *child)
virtual void childRemoved (TreeViewItem *child)
Additional Inherited Members
Public Types inherited from SideCar::GUI::Master::TreeViewItem
enum ActiveState { kIdle, kPartial, kActive, kNotUsingData }
using Children = QList< TreeViewItem * >
using ChildrenIterator = QListIterator< TreeViewItem * >
Static Public Member Functions inherited from SideCar::GUI::Master::TaskItem
static Logger::Log & Log ()
Static Public Member Functions inherited from SideCar::GUI::Master::TreeViewItem
static QVariant GetRecordingDataValue (bool canRecord, int role)
Utility class method that returns an appropriate value for the recording state depicted by the two arguments.
static QColor GetTextColor ()
Class method that returns the default (black) text color for all Qt::Foreground roles.
static QColor GetOKColor ()
Class method that returns the OK text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetWarningColor ()
Class method that returns the 'warning text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetFailureColor ()
Class method that returns the 'failure' text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetRecordingColor ()
Class method that returns the text color to use to show when a task is currently recording.
static QFont GetTextFont ()
Obtain the normal font to use for displayed text.
Detailed Description
Derivation of TaskItem that represents an Algorithms::Controller object of an IO::Stream.
Redefines the display in the recording status and info data columns. The status object from a Algorithms::Controller object contains the name of an InfoFormatter object to use to format info data from the Algorithm object managed by the controller.
Also supports runtime parameter queries and updates.
Definition at line 23 of file ControllerItem.h.
Constructor & Destructor Documentation
ControllerItem::ControllerItem (const Algorithms::ControllerStatus & status, StreamItem * parent)
Constructor.
Parameters
status initial status value of the item
parent parent node for this item
Definition at line 14 of file ControllerItem.cc.
Member Function Documentation
void ControllerItem::afterUpdate () protected virtual
Override of TreeViewItem method.
Verifies that the held InfoFormatter object is valid for the new status.
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Definition at line 110 of file ControllerItem.cc.
References SideCar::GUI::Master::TaskItem::afterUpdate(), SideCar::GUI::Master::InfoFormatter::Find(), SideCar::GUI::Master::InfoFormatter::getName(), and getStatus().
Referenced by canEdit().
bool SideCar::GUI::Master::ControllerItem::canEdit () const inline virtual
Override of TreeViewItem method.
Determine if the object supports editing of runtime parameter values.
Returns
true if so
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Definition at line 73 of file ControllerItem.h.
References afterUpdate(), getParameters(), getStatus(), and setParameters().
QVariant ControllerItem::getInfoDataValue (int role) const virtual
Override of TreeViewItem method.
Obtain the data value for the last column, which displays Algorithm-specific information.
Parameters
role the display role that determines the type of data to return
Returns
formatted Algorithm data if role is Qt::DisplayRole
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Reimplemented in SideCar::GUI::Master::RawPRIItem.
Definition at line 101 of file ControllerItem.cc.
References SideCar::GUI::Master::InfoFormatter::format(), SideCar::GUI::Master::TaskItem::getInfoDataValue(), and getStatus().
QVariant ControllerItem::getNameDataValue (int role) const virtual
Obtain the data value for the ServicesModel::kName column, which displays the name of the TreeViewItem.
Parameters
role the display role that determines the type of data to return
Returns
object name if role is Qt::DisplayRole
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Definition at line 31 of file ControllerItem.cc.
bool ControllerItem::getParameters (XmlRpc::XmlRpcValue & definition) const
Obtain the current runtime parameter values from the XML-RPC server of the runner process hosting the Controller.
Parameters
definition container to hold the returned value
Returns
true if successful
Definition at line 119 of file ControllerItem.cc.
References SideCar::GUI::Master::TreeViewItem::getIndex(), and SideCar::GUI::Master::StreamItem::getParameters().
Referenced by canEdit().
QVariant ControllerItem::getPendingCountValue (int role) const virtual
Obtain the data value for the ServicesModel::kPending column, which displays the pending queue size of this item.
Parameters
role the display role that determines the type of data to return
Returns
null QVariant
null QVariant
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Definition at line 91 of file ControllerItem.cc.
References SideCar::GUI::Master::TaskItem::getPendingCountValue().
QVariant ControllerItem::getRateDataValue (int role) const virtual
Obtain the data value for the ServicesModel::kRate column, which displays the message processing rate of the TreeViewItem.
Parameters
role the display role that determines the type of data to return
Returns
returns "Active" if the message counts of the last two status updates are different.
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Definition at line 43 of file ControllerItem.cc.
References SideCar::GUI::Master::TaskItem::getMessageRate(), SideCar::GUI::Master::TaskItem::getRateDataValue(), and getStatus().
QVariant ControllerItem::getRecordingDataValue (int role) const virtual
Override of TreeViewItem method.
Obtain a representation of the recording status of the controller.
Parameters
role the display role that determines the type of data to return
Returns
returns a character icon depicting the recording status.
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Definition at line 37 of file ControllerItem.cc.
References SideCar::GUI::Master::TreeViewItem::GetRecordingDataValue(), and getStatus().
const Algorithms::ControllerStatus& SideCar::GUI::Master::ControllerItem::getStatus () const inline protected
Obtain the type-cast status container sent by a Algorithms::Controller object.
Returns
read-only Algorithms::ControllerStatus reference
Definition at line 114 of file ControllerItem.h.
Referenced by afterUpdate(), canEdit(), getInfoDataValue(), getRateDataValue(), and getRecordingDataValue().
bool ControllerItem::setParameters (const XmlRpc::XmlRpcValue & updates) const
Submit new runtime parameter values to the XML-RPC server of the runner process hosting the Controller.
Parameters
updates container holding the new settings
Returns
true if successful
Definition at line 125 of file ControllerItem.cc.
References SideCar::GUI::Master::TreeViewItem::getIndex(), SideCar::GUI::Master::CollectionStats::kIsRecordingCount, SideCar::GUI::Master::CollectionStats::kRecordingQueueCount, SideCar::GUI::Master::CollectionStats::kWillRecordCount, and SideCar::GUI::Master::StreamItem::setParameters().
Referenced by canEdit().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/ControllerItem.h
/Users/howes/src/sidecar/GUI/Master/ControllerItem.cc