SideCar: SideCar::IO::RecordIndex Class Reference
SideCar::IO::RecordIndex Class Reference
Public Types
using const_iterator = const off_t *
Public Member Functions
RecordIndex (const std::string &path)
Constructor.
off_t operator[] (size_t index) const
bool empty () const
size_t size () const
const_iterator begin () const
const_iterator end () const
Static Public Member Functions
static Logger::Log & Log ()
static std::string const & GetIndexFileSuffix ()
Detailed Description
Definition at line 13 of file RecordIndex.h.
Constructor & Destructor Documentation
RecordIndex::RecordIndex (const std::string & path)
Constructor.
Parameters
path location of index file to use
Definition at line 31 of file RecordIndex.cc.
References Utils::FilePath::c_str(), Utils::Exception::err(), Utils::FilePath::exists(), LOGDEBUG, LOGERROR, LOGINFO, and Logger::ProcLog::thrower().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/RecordIndex.h
/Users/howes/src/sidecar/IO/RecordIndex.cc