SideCar: SideCar::GUI::Master::ConfigurationController Class Reference
SideCar::GUI::Master::ConfigurationController Class Reference
Controller class for the ConfigurationModel and the QTableView used to show loaded configuration files.
#include </Users/howes/src/sidecar/GUI/Master/ConfigurationController.h>
Public Slots
void foundRunner (const RunnerItem *added)
void lostRunner (const RunnerItem *removed)
void recordingStatusChanged (const QStringList &name, bool isRecording)
Signals
void activeConfigurationsChanged (const QStringList &active)
void selectedConfigurationChanged (const ConfigurationInfo *info)
Public Member Functions
ConfigurationController (MainWindow &window, ConfigurationSettings &settings)
Constructor.
QStringList restore ()
QStringList getAllConfigurations () const
QStringList getViewableConfigurations () const
QStringList getViewableRunningConfigurations () const
QStringList getRecordableConfigurations () const
ConfigurationInfo * getConfigurationInfo (const QString &name) const
QStringList getInvalidRecordingDirectories () const
bool isAnyRecording () const
Static Public Member Functions
static Logger::Log & Log ()
Log device to use for RecordingController log messages.
Detailed Description
Controller class for the ConfigurationModel and the QTableView used to show loaded configuration files.
Starts/stops configurations and keeps track of SideCar runner status for the running configurations.
Definition at line 28 of file ConfigurationController.h.
Constructor & Destructor Documentation
ConfigurationController::ConfigurationController (MainWindow & window, ConfigurationSettings & settings)
Constructor.
Parameters
window
settings
Definition at line 40 of file ConfigurationController.cc.
References SideCar::GUI::Master::ConfigurationInfo::canRecord(), SideCar::GUI::Master::ConfigurationInfo::foundRunner(), SideCar::GUI::Master::App::GetApp(), SideCar::GUI::Master::RunnerItem::getConfigName(), SideCar::GUI::Master::ConfigurationInfo::getEditor(), SideCar::GUI::Master::ConfigurationInfo::getHostNames(), SideCar::GUI::Master::ConfigurationInfo::getName(), SideCar::GUI::Master::ConfigurationInfo::getPath(), SideCar::GUI::Master::ConfigurationInfo::getRecordingsDirectory(), SideCar::GUI::Master::RunnerItem::getServiceName(), SideCar::GUI::Master::ConfigurationInfo::getStatus(), SideCar::GUI::Master::ConfigurationInfo::hasError(), SideCar::GUI::Master::ConfigurationInfo::hasValidRecordingDirectory(), SideCar::GUI::Master::ConfigurationInfo::isNotRunning(), SideCar::GUI::Master::ConfigurationInfo::isRunning(), SideCar::GUI::Master::ConfigurationInfo::isShuttingDown(), SideCar::GUI::Master::ConfigurationInfo::isStartingUp(), SideCar::GUI::Master::ConfigurationInfo::isViewable(), SideCar::GUI::Master::ConfigurationInfo::kNotRunning, SideCar::GUI::Master::ConfigurationInfo::load(), Log(), LOGDEBUG, LOGINFO, SideCar::GUI::Master::ConfigurationInfo::lostRunner(), SideCar::GUI::Master::ConfigurationInfo::setRecordingState(), SideCar::GUI::Master::ConfigurationInfo::setStatus(), SideCar::GUI::MainWindowBase::showAndRaise(), SideCar::GUI::Master::ConfigurationInfo::shuttingDown(), SideCar::GUI::Master::Cleaner::start(), and SideCar::GUI::Master::ConfigurationInfo::startup().
Member Function Documentation
Logger::Log & ConfigurationController::Log () static
Log device to use for RecordingController log messages.
Returns
Log device
Definition at line 33 of file ConfigurationController.cc.
References Logger::Log::Find().
Referenced by ConfigurationController().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/ConfigurationController.h
/Users/howes/src/sidecar/GUI/Master/ConfigurationController.cc