SideCar: SideCar::GUI::BScope::PPIWidget Class Reference
SideCar::GUI::BScope::PPIWidget Class Reference
Derivation of an OpenGL widget that acts like a simple PPI display.
#include </Users/howes/src/sidecar/GUI/BScope/PPIWidget.h>
Public Types
enum RenderType { kMainWindow, kMagnifierWindow, kCaptureBuffer }
Public Slots
void addMagnifier (MagnifierWindow *magnifier)
void removeMagnifier (MagnifierWindow *magnifier=0)
void saveMagnifiers (QSettings &settings) const
void raiseMagnifiers ()
void clearAll ()
void clearVideoBuffer ()
void clearBinaryBuffer ()
void clearExtractions ()
void clearRangeTruths ()
void clearBugPlots ()
void redisplayAll ()
void redisplayVideo ()
void redisplayBinary ()
void processVideo (const MessageList &data)
void processBinary (const MessageList &data)
void processExtractions (const MessageList &data)
void processRangeTruths (const MessageList &data)
void processBugPlots (const MessageList &data)
void showPhantomCursor (bool state)
void setPhantomCursor (const QPointF &pos)
void setCursorPosition (const QString &value)
void setShowCursorPosition (bool state)
Signals
void currentMessage (Messages::PRIMessage::Ref msg)
void currentCursorPosition (const QPointF &pos)
void transformChanged ()
Public Member Functions
PPIWidget (QWidget *parent=0)
Constructor.
void localToRealWorld (int x, int y, GLdouble &azimuth, GLdouble &range) const
void updateCursorPosition (CursorPosition &pos)
void initializeContext ()
void renderScene (QGLWidget *widget, RenderType renderType)
bool getShowPhantomCursor () const
bool getShowCursorPosition () const
void setSettingsKey (const QString &settingsKey)
Static Public Member Functions
static Logger::Log & Log ()
static QGLFormat GetGLFormat ()
Obtain the OpenGL configuration we want to use.
Detailed Description
Derivation of an OpenGL widget that acts like a simple PPI display.
Incoming data arrives via the processVideo(), processBinary(), and processExtractions() slots. Each slot takes a reference to a MessageBlockList object which contains one or more ACE_Message_Block objects created in a separate reader thread. The incoming slot obtains a message object from the raw ACE_Message_Block, adds it to the History object, and if necessary, generates data for future display.
The Video and BinaryVideo processing paths render into an OffscreenBuffer object, using an OpenGL pixel buffer or a framebuffer object to do the dirty work. The paintGL() method of the PPIWidget uses the offscreen renderings to create the PPI display. Extraction reports exist as a list of points, which the paintGL() method renders directly to the main view.
This class supports the loading of an image file, which gets blended with the PPI image. The image has an associated opacity value (as do all of the other rendering images), which may be changed through the application's ConfigurationWindow object. For best results, the image file should be square, centered at the radar's center, and with a dimension 2 * rangeMax, the maximum range of the incoming radar reports.
The user may manipulate the view by panning or zooming. Currently
Definition at line 64 of file PPIWidget.h.
Constructor & Destructor Documentation
PPIWidget::PPIWidget (QWidget * parent = 0)
Constructor.
Parameters
parent parent object
Definition at line 60 of file PPIWidget.cc.
References SideCar::GUI::BScope::History::addBinary(), SideCar::GUI::BScope::History::addBugPlot(), SideCar::GUI::BScope::History::addExtractions(), SideCar::GUI::BScope::History::addRangeTruth(), SideCar::GUI::BScope::History::addVideo(), SideCar::GUI::BScope::History::clear(), SideCar::GUI::OffscreenBuffer::clearBuffer(), SideCar::GUI::VertexColorArray::draw(), SideCar::GUI::BScope::App::GetApp(), SideCar::GUI::BScope::History::getBinary(), SideCar::GUI::BScope::History::getBugPlots(), SideCar::GUI::ChannelImaging::getColor(), SideCar::GUI::BScope::History::getExtractions(), SideCar::GUI::BScope::History::getRangeTruths(), SideCar::GUI::ChannelImaging::getSize(), SideCar::GUI::OffscreenBuffer::getTexture(), SideCar::GUI::BScope::History::getVideo(), SideCar::GUI::MainWindowBase::initialize(), SideCar::GUI::OnOffSettingsBlock::isEnabled(), SideCar::GUI::OffscreenBuffer::isValid(), LOGDEBUG, LOGERROR, LOGINFO, LOGWARNING, SideCar::GUI::VertexColorArray::push_back(), SideCar::GUI::RangeMap::render(), SideCar::GUI::TargetPlotImaging::render(), SideCar::GUI::MainWindowBase::showAndRaise(), Logger::ProcLog::thrower(), SideCar::GUI::StencilBufferState::use(), and SideCar::GUI::Color::use().
Member Function Documentation
QGLFormat PPIWidget::GetGLFormat () static
Obtain the OpenGL configuration we want to use.
Returns
OpenGL format
Definition at line 48 of file PPIWidget.cc.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/BScope/PPIWidget.h
/Users/howes/src/sidecar/GUI/BScope/PPIWidget.cc