SideCar: SideCar::GUI::Master::StreamItem Class Reference
SideCar::GUI::Master::StreamItem Class Reference
TreeViewItem that represents an IO::Stream object of a runner process.
#include </Users/howes/src/sidecar/GUI/Master/StreamItem.h>
Public Member Functions
StreamItem (const IO::StreamStatus &status, RunnerItem *parent)
Constructor.
RunnerItem * getParent () const
Obtain the item's RunnerItem parent.
TaskItem * getChild (int index) const
Obtain a TaskItem child.
bool getParameters (int taskIndex, XmlRpc::XmlRpcValue &definition) const
Obtain an XML description of the runtime parameter values for a particular child TaskItem.
bool setParameters (int taskIndex, const XmlRpc::XmlRpcValue &updates) const
Change one or more runtime parameter values of a particular child TaskItem.
void formatChangedParameters (const XmlRpc::XmlRpcValue &definitions, QStringList &changes) const
Public Member Functions inherited from SideCar::GUI::Master::CollectionItem
void updateCollectionStats (CollectionStats &stats) const
Prototype for method to update a CollectionStats object with statistics provided by a TreeViewItem derivative.
bool canExpand () const
Determine if the TreeViewItem is expandable.
QVariant getNameDataValue (int role) const
Obtain the data value for the ServicesModel::kName column, which displays the name of the TreeViewItem.
QVariant getStateDataValue (int role) const
Obtain the data value for the ServicesModel::kState column, which displays the processing state of the TreeViewItem.
QVariant getRecordingDataValue (int role) const
Obtain the data value for the ServicesModel::kRecording column, which displays the recording state of the TreeViewItem.
QVariant getPendingCountValue (int role) const
Obtain the data value for the ServicesModel::kPending column, which displays the pending queue size of this item.
QVariant getRateDataValue (int role) const
Obtain the data value for the ServicesModel::kRate column, which displays the message processing rate of the TreeViewItem.
QVariant getErrorDataValue (int role) const
Obtain the data value for the ServicesModel::kError column, which displays any error text from the TreeViewItem.
IO::ProcessingState::Value getProcessingState () const
const CollectionStats & getCollectionStats () const
bool canRecord () const
bool willRecord () const
bool isRecording () const
void recalculateStats ()
Public Member Functions inherited from SideCar::GUI::Master::TreeViewItem
~TreeViewItem ()
Destructor.
virtual void initialize ()
Initialize this object's internal state.
const IO::StatusBase & getStatus () const
Obtain the latest IO::StatusBase object received for this object.
bool update (const IO::StatusBase &status)
Update the TreeViewItem held status.
bool isOK () const
bool isProcessing () const
Determine if the object is in a 'processing' state: auto-diagnostic, calibration, or run.
ActiveState getActiveState () const
Obtain the current ActiveState value for this object.
QVariant getData (int column, int role) const
Obtain the data point to use for a specific role in a given column.
virtual QVariant getHostDataValue (int role) const
Obtain the data value for the ServicesModel::kHost column, which displays the host name of the machine where the object is running.
virtual QVariant getInfoDataValue (int role) const
Obtain the data value for the ServicesModel::kInfo column, which displays miscellaneous informational data of the TreeViewItem.
virtual QColor getForegroundColor (int column) const
Obtain the foreground color to use for the contents of a given column.
virtual QFont getFont (int column) const
Obtain the font to use for the contents of a given column.
virtual int getAlignment (int columnt) const
Obtain the alignment (horizontal and vertical) to use for the contents of a given column.
virtual bool canEdit () const
Determine if the TreeViewItem supports editing of runtime parameter values.
const QString & getName () const
Obtain the object's name.
const QString & getFullName () const
Get the full name of the item.
void insertChild (int row, TreeViewItem *child)
Insert a child, renumbering the indices of all children after it.
void appendChild (TreeViewItem *child)
Add a child.
void removeChild (int index)
Remove the child at a given index.
TreeViewItem * getChild (int index) const
Obtain the child associated with a given index value.
int getNumChildren () const
Obtain the number of children.
int getIndex () const
Obtain the index of this object in the context of our parent's children array.
TreeViewItem * getParent () const
Obtain the parent of this TreeViewItem object.
int getParentIndex () const
Obtain the index value of the parent object (equivalent to getParent()->getIndex().
ChildrenIterator getChildrenIterator () const
Obtain a Java-style iterator for the children array.
bool isExpanded () const
Determine if the object is expanded.
void setExpanded (bool expanded)
Change the expansion attribute of the object.
int getInsertionPoint (const QString &name) const
Obtain the row where the given name could be inserted without disturbing the ordering of the existing rows.
virtual bool isFiltered (const QString &filter) const
Determine if this item contains the given filter string.
Static Public Member Functions
static Logger::Log & Log ()
Static Public Member Functions inherited from SideCar::GUI::Master::TreeViewItem
static QVariant GetRecordingDataValue (bool canRecord, int role)
Utility class method that returns an appropriate value for the recording state depicted by the two arguments.
static QColor GetTextColor ()
Class method that returns the default (black) text color for all Qt::Foreground roles.
static QColor GetOKColor ()
Class method that returns the OK text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetWarningColor ()
Class method that returns the 'warning text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetFailureColor ()
Class method that returns the 'failure' text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetRecordingColor ()
Class method that returns the text color to use to show when a task is currently recording.
static QFont GetTextFont ()
Obtain the normal font to use for displayed text.
Additional Inherited Members
Public Types inherited from SideCar::GUI::Master::TreeViewItem
enum ActiveState { kIdle, kPartial, kActive, kNotUsingData }
using Children = QList< TreeViewItem * >
using ChildrenIterator = QListIterator< TreeViewItem * >
Protected Member Functions inherited from SideCar::GUI::Master::CollectionItem
CollectionItem (const IO::StatusBase &status, TreeViewItem *parent)
void beforeUpdate ()
Hook invoked before a status update.
void afterUpdate ()
Hook invoked after a status update.
void accumulateChildStats (TreeViewItem *child)
Protected Member Functions inherited from SideCar::GUI::Master::TreeViewItem
TreeViewItem ()
Constructor for the RootItem object (which has no parent).
TreeViewItem (const IO::StatusBase &status, TreeViewItem *parent)
Constructor for all derived classes except RootItem.
void setName (const QString &name)
void setOK (bool ok)
void setProcessing (bool processing)
void setProcessingState (IO::ProcessingState::Value state)
void setActiveState (ActiveState activeState)
template<typename T >
const T & getStatusT () const
Detailed Description
TreeViewItem that represents an IO::Stream object of a runner process.
An IO::Stream contains IO::Modules, which is a simple container for an IO::Task object.
Definition at line 21 of file StreamItem.h.
Constructor & Destructor Documentation
StreamItem::StreamItem (const IO::StreamStatus & status, RunnerItem * parent)
Constructor.
Parameters
status initial status value of the item
parent parent node for this item
Definition at line 20 of file StreamItem.cc.
References SideCar::GUI::Master::TreeViewItem::appendChild(), getChild(), SideCar::GUI::Master::TreeViewItem::getNumChildren(), and SideCar::GUI::Master::TreeViewItem::update().
Member Function Documentation
TaskItem * StreamItem::getChild (int index) const
Obtain a TaskItem child.
Parameters
index which TaskItem to fetch
Returns
TaskItem object
Definition at line 78 of file StreamItem.cc.
References SideCar::GUI::Master::TreeViewItem::getChild(), SideCar::GUI::Master::TreeViewItem::getNumChildren(), LOGDEBUG, LOGINFO, and XmlRpc::XmlRpcValue::toXml().
Referenced by StreamItem().
bool StreamItem::getParameters (int taskIndex, XmlRpc::XmlRpcValue & definition) const
Obtain an XML description of the runtime parameter values for a particular child TaskItem.
Parameters
taskIndex which TaskItem to work with
definition XML container update with the XML description
Returns
true if successful
Definition at line 64 of file StreamItem.cc.
References SideCar::GUI::Master::RunnerItem::getParameters(), and getParent().
Referenced by SideCar::GUI::Master::ControllerItem::getParameters().
RunnerItem * StreamItem::getParent () const
Obtain the item's RunnerItem parent.
Returns
RunnerItem object
Definition at line 58 of file StreamItem.cc.
References SideCar::GUI::Master::TreeViewItem::getParent().
Referenced by getParameters(), and setParameters().
bool StreamItem::setParameters (int taskIndex, const XmlRpc::XmlRpcValue & updates) const
Change one or more runtime parameter values of a particular child TaskItem.
Parameters
taskIndex which TaskItem to work with
definition XML container containing the parameter changes to apply
Returns
true if successful
Definition at line 71 of file StreamItem.cc.
References getParent(), and SideCar::GUI::Master::RunnerItem::setParameters().
Referenced by SideCar::GUI::Master::ControllerItem::setParameters().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/StreamItem.h
/Users/howes/src/sidecar/GUI/Master/StreamItem.cc