SideCar: Logger::LogMap Class Reference
Logger::LogMap Class Reference
Public Member Functions
LogMap ()
Constructor.
~LogMap ()
Destructor.
Log * find (const std::string &name) const
Locate a registered Log device for a given name.
bool add (Log *log)
Attempt to insert a new Log device into the map.
std::vector< std::string > getNames ()
std::vector< std::string > getNames (Log::NewLogNotifier notifier)
Detailed Description
Definition at line 31 of file Log.cc.
Constructor & Destructor Documentation
LogMap::~LogMap ()
Destructor.
Deletes all held Log devices.
Definition at line 79 of file Log.cc.
Member Function Documentation
bool LogMap::add (Log * log)
Attempt to insert a new Log device into the map.
Parameters
log the Log device to insert
Returns
true if successful
Definition at line 94 of file Log.cc.
References Logger::Log::fullName(), and Logger::Log::isHidden().
Referenced by Logger::Log::GetNames().
Log * LogMap::find (const std::string & name) const
Locate a registered Log device for a given name.
Parameters
name the fully-qualified name to look for
Returns
found Log device or NULL
Definition at line 86 of file Log.cc.
Referenced by Logger::Log::GetNames().
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/Logger/Log.cc