SideCar: SideCar::GUI::VertexColorArray Class Reference
SideCar::GUI::VertexColorArray Class Reference
Resizable array of Vertex/Color pairs, interleaved in hopes of getting the best performance out of glVertexPointer and glColorPointer operations.
#include </Users/howes/src/sidecar/GUI/VertexColorArray.h>
Public Member Functions
VertexColorArray ()
Constructor.
bool empty () const
void clear ()
void draw (int type) const
Invoke glDrawArrays with the given primitive type.
size_t size () const
Number of Vertex/Color pairs present in the array.
void checkCapacity (size_t request)
Check if the given request can be handled by the current capacity of the array.
void push_back (const Vertex &vertex)
Append a new VertexColor object with the given values.
void push_back (const Vertex &vertex, const Color &color)
Append a new VertexColor object with the given values.
VertexColor & operator[] (size_t index)
Static Public Member Functions
static Logger::Log & Log ()
Log device to use for VertexColorArray messages.
Detailed Description
Resizable array of Vertex/Color pairs, interleaved in hopes of getting the best performance out of glVertexPointer and glColorPointer operations.
Definition at line 31 of file VertexColorArray.h.
Constructor & Destructor Documentation
VertexColorArray::VertexColorArray ()
Constructor.
Parameters
capacity initial capacity for the vector.
Definition at line 14 of file VertexColorArray.cc.
References Log(), and LOGINFO.
Member Function Documentation
void VertexColorArray::checkCapacity (size_t request)
Check if the given request can be handled by the current capacity of the array.
If expansion is perfomed, this will invoke glVertexPointer and glColorPointer to use the new pointer values. NOTE: because of this side-effect, this method must be called inside a valid OpenGL context.
Parameters
request number of VertexColor objects to store
Definition at line 29 of file VertexColorArray.cc.
References Log(), LOGDEBUG, and LOGINFO.
Referenced by SideCar::GUI::Spectrum::SpectrographWidget::SpectrographWidget().
void VertexColorArray::draw (int type) const
Invoke glDrawArrays with the given primitive type.
Parameters
type the primitive to draw
Definition at line 63 of file VertexColorArray.cc.
References Log().
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::initializeContext(), SideCar::GUI::BScope::PPIWidget::PPIWidget(), SideCar::GUI::TargetPlotImaging::render(), SideCar::GUI::OffscreenBuffer::renderPoints(), and SideCar::GUI::Spectrum::SpectrographWidget::SpectrographWidget().
Logger::Log & VertexColorArray::Log () static
Log device to use for VertexColorArray messages.
Returns
Log device
Definition at line 7 of file VertexColorArray.cc.
References Logger::Log::Find().
Referenced by checkCapacity(), draw(), and VertexColorArray().
void SideCar::GUI::VertexColorArray::push_back (const Vertex & vertex) inline
Append a new VertexColor object with the given values.
Parameters
vertex Vertex object to store
color Color object to store
Definition at line 77 of file VertexColorArray.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::initializeContext(), SideCar::GUI::BScope::PPIWidget::PPIWidget(), SideCar::GUI::TargetPlotImaging::render(), and SideCar::GUI::Spectrum::SpectrographWidget::SpectrographWidget().
void SideCar::GUI::VertexColorArray::push_back (const Vertex & vertex, const Color & color) inline
Append a new VertexColor object with the given values.
Parameters
vertex Vertex object to store
color Color object to store
Definition at line 86 of file VertexColorArray.h.
size_t SideCar::GUI::VertexColorArray::size () const inline
Number of Vertex/Color pairs present in the array.
Returns
array size
Definition at line 61 of file VertexColorArray.h.
Referenced by SideCar::GUI::TargetPlotImaging::render().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/VertexColorArray.h
/Users/howes/src/sidecar/GUI/VertexColorArray.cc