SideCar: SideCar::GUI::Playback::Clock Class Reference
SideCar::GUI::Playback::Clock Class Reference
Playback clock for the Playback application.
#include </Users/howes/src/sidecar/GUI/Playback/Clock.h>
Public Slots
void start ()
Start the playback clock.
void stop ()
Stop the playback clock.
void setPlaybackClockStart (const Time::TimeStamp &playbackClockStart)
Change the playback clock so that it will start at a new time.
Signals
void tick (const Time::TimeStamp &playbackTime, const Time::TimeStamp &elapsed)
Notification sent out when the clock ticks.
void started ()
Notification sent out when the playback clock has started.
void stopped ()
Notification sent out when the playback clock has stopped.
void playbackClockStartChanged (const Time::TimeStamp &playbackClockStart)
Notification sent out when he start time of the playback clock has changed.
Public Member Functions
Clock (QObject *parent, int tickBeat, double wallClockRate)
Constructor.
Time::TimeStamp getPlaybackClock ()
Obtain the playback clock value for the current wall clock time.
Time::TimeStamp getWallClockDurationUntil (const Time::TimeStamp &when)
Obtain the number of seconds in wall clock time before the event with the given will occur.
void setClockRange (const Time::TimeStamp &start, const Time::TimeStamp &end)
Set the time frame of the playback clock.
void setTickRate (int msecs)
Set the periodic tick rate.
void setWallClockRate (double rate)
Set the wall clock rate.
bool isRunning () const
Determine if the clock is currently running.
QString formatTimeStamp (const Time::TimeStamp &when)
Obtain a formatted QString for a given absolute TimeStamp value.
QString formatDuration (const Time::TimeStamp &duration)
Obtain a formatted QString for a given duration TimeStamp value value.
Static Public Member Functions
static Logger::Log & Log ()
Detailed Description
Playback clock for the Playback application.
There are two time frames of reference in use in the Playback application. The first is the time frame of the recorded data. Timestamps in the recorded data are UTC time values that indicate when the data was recorded. One can subtract one of these values from another to obtain their delta in seconds or microseconds. Note that these values not only indicate the clock time of the recording, but they also indicate the date on which the recording took place.
The second time frame refers to the time when playback starts, and the number of seconds that have elapsed during data playback. The getPlaybackClock() and getWallClockDurationUntil() methods manage the two time frames in order to provide a fairly accurate reproduction of the message emission that was seen on the original system when the data was recorded. The Clock class supports playback rates that are faster and slower than real time. Calling setWallClockRate() with a value greater than one will result in playback that is faster than real time; likewise, giving setWallClockRate() a non-zero value less than one will result in playback that is slower than real time.
Definition at line 32 of file Clock.h.
Constructor & Destructor Documentation
Clock::Clock (QObject * parent, int tickBeat, double wallClockRate)
Constructor.
Parameters
parent object that acquires ownership of this one
tickBeat number of milliseconds between tick() signal emissions
Definition at line 16 of file Clock.cc.
Member Function Documentation
QString Clock::formatDuration (const Time::TimeStamp & duration)
Obtain a formatted QString for a given duration TimeStamp value value.
Parameters
duration value to format
Returns
the formatted value in HH:MM:SS format
Definition at line 182 of file Clock.cc.
Referenced by SideCar::GUI::Playback::MainWindow::getWallClockRate(), SideCar::GUI::Playback::MainWindow::MainWindow(), and SideCar::GUI::Playback::Emitter::setEmitting().
QString Clock::formatTimeStamp (const Time::TimeStamp & when)
Obtain a formatted QString for a given absolute TimeStamp value.
The given value is reduced by the midnight_ value.
Parameters
when the time to format
Returns
the formatted value in HH:MM:SS format
Definition at line 176 of file Clock.cc.
Referenced by SideCar::GUI::Playback::MainWindow::getWallClockRate(), SideCar::GUI::Playback::MainWindow::MainWindow(), and SideCar::GUI::Playback::Emitter::setEmitting().
Time::TimeStamp Clock::getPlaybackClock ()
Obtain the playback clock value for the current wall clock time.
Returns
Definition at line 25 of file Clock.cc.
References LOGDEBUG, and SideCar::Time::TimeStamp::Now().
Referenced by getWallClockDurationUntil(), SideCar::GUI::Playback::MainWindow::MainWindow(), SideCar::GUI::Playback::Emitter::setEmitting(), setWallClockRate(), and stop().
Time::TimeStamp Clock::getWallClockDurationUntil (const Time::TimeStamp & when)
Obtain the number of seconds in wall clock time before the event with the given will occur.
Accounts for non-unity playback rate, so the value is valid for use with sleep() or usleep().
Parameters
when the time to check
Returns
wall time duration until event
Definition at line 53 of file Clock.cc.
References getPlaybackClock(), LOGDEBUG, and LOGINFO.
Referenced by SideCar::GUI::Playback::Emitter::setEmitting().
bool SideCar::GUI::Playback::Clock::isRunning () const inline
Determine if the clock is currently running.
Returns
true if so
Definition at line 92 of file Clock.h.
Referenced by SideCar::GUI::Playback::Emitter::setEmitting().
void SideCar::GUI::Playback::Clock::playbackClockStartChanged (const Time::TimeStamp & playbackClockStart) signal
Notification sent out when he start time of the playback clock has changed.
Parameters
playbackClockStart
Referenced by setPlaybackClockStart().
void Clock::setClockRange (const Time::TimeStamp & start, const Time::TimeStamp & end)
Set the time frame of the playback clock.
A playback clock with an elapsed time greater than the set duration value will stop, unless looping is enabled in which case the clock will keep running and just jump back to the start time after the entire duration has elapsed.
Parameters
start the start of the time frame
start the end of the time frame
Definition at line 79 of file Clock.cc.
References LOGINFO, setPlaybackClockStart(), and start().
Referenced by SideCar::GUI::Playback::MainWindow::MainWindow().
void Clock::setPlaybackClockStart (const Time::TimeStamp & playbackClockStart) slot
Change the playback clock so that it will start at a new time.
Parameters
playbackClockStart
Definition at line 114 of file Clock.cc.
References LOGINFO, playbackClockStartChanged(), start(), and stop().
Referenced by SideCar::GUI::Playback::MainWindow::getWallClockRate(), SideCar::GUI::Playback::MainWindow::MainWindow(), and setClockRange().
void SideCar::GUI::Playback::Clock::setTickRate (int msecs) inline
Set the periodic tick rate.
Parameters
msecs milliseconds between tick() signal emissions.
Definition at line 77 of file Clock.h.
void Clock::setWallClockRate (double rate)
Set the wall clock rate.
Values must be greater than zero. Values greater than one will result in a playback clock that runs faster than real-time, while values less than one will give one that runs slower than real-time. NOTE: it is OK to call this while the clock is running
Parameters
rate wall clock rate
Definition at line 89 of file Clock.cc.
References getPlaybackClock(), LOGERROR, LOGINFO, and SideCar::Time::TimeStamp::Now().
Referenced by SideCar::GUI::Playback::MainWindow::getWallClockRate().
void Clock::start () slot
Start the playback clock.
Starts an internal QTimer to perform ticking, and emits the started() signal.
Definition at line 138 of file Clock.cc.
References LOGINFO, SideCar::Time::TimeStamp::Now(), and started().
Referenced by SideCar::GUI::Playback::MainWindow::getWallClockRate(), SideCar::GUI::Playback::MainWindow::MainWindow(), setClockRange(), and setPlaybackClockStart().
void Clock::stop () slot
Stop the playback clock.
Stops the internal QTimer used to perform ticking, and emits the stopped() signal.
Definition at line 155 of file Clock.cc.
References getPlaybackClock(), LOGINFO, stopped(), and tick().
Referenced by SideCar::GUI::Playback::MainWindow::getWallClockRate(), SideCar::GUI::Playback::MainWindow::MainWindow(), and setPlaybackClockStart().
void SideCar::GUI::Playback::Clock::tick (const Time::TimeStamp & playbackTime, const Time::TimeStamp & elapsed) signal
Notification sent out when the clock ticks.
Emits the current playback clock time, and the amount of time that has elapsed in the playback.
Parameters
playbackTime current playback clock time
elapsed playback duration
Referenced by stop().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Playback/Clock.h
/Users/howes/src/sidecar/GUI/Playback/Clock.cc