SideCar: SideCar::IO::RecipientList Class Reference
SideCar::IO::RecipientList Class Reference
Maintain a shared list of the task IDs and their input channels which should receive a message.
#include </Users/howes/src/sidecar/IO/RecipientList.h>
Public Types
using TaskRef = boost::shared_ptr< Task >
Public Member Functions
RecipientList ()
Default constructor.
void add (const TaskRef &task, size_t channelIndex)
Adds a recipient to this list.
size_t size () const
Obtain the number of Entry objects.
bool deliver (ACE_Message_Block *data) const
Distribute a message to each registered recipient Task object.
std::ostream & print (std::ostream &os) const
Print out the task/channel entries to a C++ text output stream.
bool areAnyTasksUsingData () const
Determine if there are any recipients actively processing data.
Static Public Member Functions
static Logger::Log & Log ()
Log device for RecipientList messages.
Detailed Description
Maintain a shared list of the task IDs and their input channels which should receive a message.
When a Task object emits a message, it adds a set of recipients to the message via MessageManager::setRecipients(). The recipient list contains a 2-tuple for each recipent that contains the unique task ID of the Task object to receive the next message, and the index of the Task's channel to deliver to.
The deliver() method distributes ACE_Message_Block message objects to registred recipients. However, it only deliver a message to if the recipient desired data.
Definition at line 25 of file RecipientList.h.
Constructor & Destructor Documentation
RecipientList::RecipientList ()
Default constructor.
Creates an empty vector of Entry objects.
Definition at line 17 of file RecipientList.cc.
Member Function Documentation
void RecipientList::add (const TaskRef & task, size_t channelIndex)
Adds a recipient to this list.
NOTE: there is no check for duplicate entries (assumed done elsewhere)
Parameters
taskIndex unique recipient index
channelIndex input channel index of task
Definition at line 24 of file RecipientList.cc.
References Log(), and LOGINFO.
bool RecipientList::areAnyTasksUsingData () const
Determine if there are any recipients actively processing data.
If so, then deliver() will distribute data. Otherewise, it does nothing.
Returns
true if at least one recipient wants data
Definition at line 114 of file RecipientList.cc.
bool RecipientList::deliver (ACE_Message_Block * data) const
Distribute a message to each registered recipient Task object.
Parameters
data the message to deliver
Returns
false if any delivery failed
Definition at line 45 of file RecipientList.cc.
References Log(), and LOGINFO.
Logger::Log & RecipientList::Log () static
Log device for RecipientList messages.
Returns
Log device
Definition at line 11 of file RecipientList.cc.
References Logger::Log::Find().
Referenced by add(), and deliver().
std::ostream & RecipientList::print (std::ostream & os) const
Print out the task/channel entries to a C++ text output stream.
Parameters
os stream to write to
Returns
stream written to
Definition at line 35 of file RecipientList.cc.
size_t SideCar::IO::RecipientList::size () const inline
Obtain the number of Entry objects.
Returns
Definition at line 53 of file RecipientList.h.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/RecipientList.h
/Users/howes/src/sidecar/IO/RecipientList.cc