SideCar: SideCar::IO::TCPDataPublisher Class Reference
SideCar::IO::TCPDataPublisher Class Reference
Publisher of data using TCP transport.
#include </Users/howes/src/sidecar/IO/TCPDataPublisher.h>
Public Types
using Self = TCPDataPublisher
using Ref = boost::shared_ptr< Self >
Public Types inherited from SideCar::IO::DataPublisher
using Self = DataPublisher
using Ref = boost::shared_ptr< Self >
Public Types inherited from SideCar::IO::Task
enum { kDefaultThreadFlags = THR_NEW_LWP | THR_JOINABLE | THR_SCHED_DEFAULT | THR_INHERIT_SCHED }
Default flags to use for processing threads.
using Ref = boost::shared_ptr< Task >
Shared reference counter for Task objects.
using ParameterMap = std::map< std::string, size_t >
Container of Parameter object references.
using ParameterVector = std::vector< Parameter::Ref >
Public Types inherited from SideCar::IO::ZeroconfRegistry
enum ID {
kPublisher = 0, kSubscriber, kRunnerStatusCollector, kRunnerStatusEmitter,
kStateEmitter, kStateCollector, kRunnerRemoteController, kNumTypes
}
Defined Zeroconf types.
Public Member Functions
bool openAndInit (const std::string &key, const std::string &serviceName, uint16_t port=0, int bufferSize=0, long threadFlags=kDefaultThreadFlags, long threadPriority=ACE_DEFAULT_THREAD_PRIORITY)
Open a server connection on a particular port.
int close (u_long flags=0)
Override of DataPublisher method.
size_t getConnectionCount () const
Public Member Functions inherited from SideCar::IO::DataPublisher
~DataPublisher ()
Destructor.
void setTransport (const std::string &transport)
void setIP (const std::string &ip)
void setType (const std::string &type)
Set the Zeroconf type used by the publisher.
void setHost (const std::string &host)
void setPort (uint16_t port)
void setInterface (uint32_t interface)
std::string getType () const
uint16_t getPort () const
uint32_t getInterface () const
bool isPublished () const
bool publish (const std::string &serviceName)
Begin publishing connection information under a specific name.
int close (u_long flags=0) override
Override of IOTask.
Zeroconf::Publisher::Ref getConnectionPublisher () const
Obtain reference to the Zeroconf::Publisher used by this object.
const std::string & getServiceName () const
Public Member Functions inherited from SideCar::IO::IOTask
const Messages::MetaTypeInfo * getMetaTypeInfo () const
Obtain the MetaTypeInfo object registered with the task.
const std::string & getMetaTypeInfoKeyName () const
Obtain the message type name.
Messages::MetaTypeInfo::Value getMetaTypeInfoKey () const
Obtain the message type key.
Messages::MetaTypeInfo::CDRLoader getMetaTypeInfoCDRLoader () const
Obtain the loader for the message type.
Messages::MetaTypeInfo::XMLLoader getMetaTypeInfoXMLLoader () const
Obtain the loader for the message type.
virtual void establishedConnection ()
Notification that a valid connection to a data source/sink has been made.
virtual void acquireExternalMessage (ACE_Message_Block *data)
Acquire a message from an external source.
Public Member Functions inherited from SideCar::IO::Task
Task (bool usingData=false)
Constructor.
~Task ()
Destructor.
const std::string & getTaskName () const
Obtain the name of the task.
void setTaskName (const std::string &taskName)
Set the task's internal name.
boost::weak_ptr< Stream > getStream () const
Obtain the stream to which this task belongs.
void setStream (const boost::shared_ptr< Stream > &stream)
Set the Stream object in which this Task object resides.
bool putInChannel (const Messages::Header::Ref &msg, size_t channel)
Place a given message into this Tasks's input processing queue.
int put (ACE_Message_Block *data, ACE_Time_Value *timeout=0) override
Override of ACE_Task method.
void setError (const std::string &text, bool force=false)
Record an error message.
const std::string & getError () const
Fetch the current error text.
void clearError ()
Clear the held error text.
bool hasError () const
Determine if the task has an error posted.
bool registerParameter (const Parameter::Ref &property)
Register a configurable parameter with the controller.
bool unregisterParameter (const Parameter::Ref &property)
Unregister a configurable parameter with the controller.
bool hasChangedParameters () const
Determine if this task has any parameter objects that have values that differ from their startup configuration.
ProcessingState::Value getProcessingState () const
Obtain the current processing state indicator.
bool isActive () const
Determine if the task is in a message processing state.
bool isInCalibrationState () const
Determine if the task is in the calibration state.
bool isInRunState () const
Determine if the task is in the run state.
bool isInStopState () const
Determine if the task is in the stop state.
const Stats & getInputStats (size_t channelIndex) const
Obtain a read-only reference to the message Stats object for this Task object.
void updateInputStats (size_t channelIndex, size_t byteCount, uint32_t sequenceCounter)
Update internal processing statistics using values from the latest message received by the task.
void setTaskIndex (size_t taskIndex)
Set the unique ID for this task.
size_t getTaskIndex () const
Obtain the unique ID for this task.
void addInputChannel (const Channel &channel)
Add an input channel to the task.
void addOutputChannel (const Channel &channel)
Add an input channel to the task.
const ChannelVector & getInputChannels () const
Obtain an existing input channel.
size_t getNumInputChannels () const
Obtain the number of input channels defined for this task.
const Channel & getInputChannel (size_t index)
Obtain a specific input channel defined for this task.
size_t getInputChannelIndex (const std::string &name)
Obtain the index of an input channel with a given name.
const ChannelVector & getOutputChannels () const
Obtain an existing output channel.
size_t getNumOutputChannels () const
Obtain the number of output channels defined for this task.
const Channel & getOutputChannel (size_t index)
Obtain a specific output channel defined for this task.
size_t getOutputChannelIndex (const std::string &name)
Obtain the index of an output channel with a given name.
void getCurrentParameters (XmlRpc::XmlRpcValue &value) const
Obtain an XML-RPC definition of the current runtime parameter values.
void getChangedParameters (XmlRpc::XmlRpcValue &value) const
Obtain an XML-RPC definition of all changed runtime parameter values, those with values different from that found in the configuration file or at initialization time.
virtual const char * getStatusClassName () const
Obtain the status class name for this class.
virtual size_t getStatusSize () const
Obtain the number of slots in the TaskStatus XML status object.
virtual void fillStatus (StatusBase &status)
Obtain status information from the task.
bool isUsingData () const
Obtain the current usingData_ setting.
void updateUsingDataValue ()
Update this object's usingData_ value.
virtual void setUsingData (bool value)
Set a new usingData_ value.
void setThreadParams (const ThreadParams &threadParams)
Set the thread parameters that the task will use in its activateThreads() call.
const ThreadParams & getThreadParams () const
Obtain the current thread parameter settings.
bool activateThreads (int count)
Spawn count threads that will each run in the task's svc() method, which derived classes must define (see ACE_Task::svc()).
Static Public Member Functions
static Logger::Log & Log ()
Log device for objects of this type.
static Ref Make ()
Factory method for creating new TCPDataPublisher objects.
Static Public Member Functions inherited from SideCar::IO::DataPublisher
static Logger::Log & Log ()
Log device for objects of this type.
Static Public Member Functions inherited from SideCar::IO::IOTask
static Logger::Log & Log ()
Static Public Member Functions inherited from SideCar::IO::Task
static Logger::Log & Log ()
Obtain the log device for objects of this class.
Static Public Member Functions inherited from SideCar::IO::ZeroconfTypes::TZCType< id >
static const char * GetZeroconfType ()
Obtain the configured Zeroconf type for objects derived from this class.
static const char * GetTwinZeroconfType ()
Obtain the "twin" Zeroconf type for objects derived from this class.
static std::string MakeZeroconfType (const std::string &subType)
Construct a valid SideCar Zeroconf type string for a given subtype.
static std::string MakeTwinZeroconfType (const std::string &subType)
Construct the twin SideCar Zeroconf type string for a given subtype.
Static Public Member Functions inherited from SideCar::IO::ZeroconfRegistry
static const char * GetType (ID id)
Obtain the Zeroconf type string for a given ID.
static ID GetTwin (ID id)
Locate the twin of this ID.
static std::string MakeZeroconfType (const char *type, const std::string &subType)
Construct a valid SideCar Zeroconf type string for a type and a subtype.
Protected Member Functions
TCPDataPublisher ()
Constructor.
bool deliverDataMessage (ACE_Message_Block *data, ACE_Time_Value *timeout=0)
Give a message to the task to do with as it pleases.
void setServiceName (const std::string &serviceName)
Protected Member Functions inherited from SideCar::IO::DataPublisher
DataPublisher ()
Constructor.
virtual void publishCallback (bool state)
virtual void publishSucceeded ()
virtual void publishFailed ()
int handle_timeout (const ACE_Time_Value &duration, const void *arg) override
Callback invoked when internal timer fires.
Protected Member Functions inherited from SideCar::IO::IOTask
IOTask (const Messages::MetaTypeInfo *metaType=0)
Constructor for derived classes.
void setMetaTypeInfoKeyName (const std::string &keyName)
Install the MetaTypeInfo object to use.
Protected Member Functions inherited from SideCar::IO::Task
bool enterProcessingState (ProcessingState::Value state)
Change the tasks processing state indicator.
bool enterLastProcessingState ()
Change to the last non-failure processing state.
virtual bool enterInitializeState ()
Processor for the transition into the initialize state.
virtual bool enterAutoDiagnosticsState ()
Processor for the transition into the auto-diagnostic state.
virtual bool enterCalibrateState ()
Processor for the transition into the calibrate state.
virtual bool enterRunState ()
Processor for the transition into the run state.
virtual bool enterStopState ()
Processor for the transition into the stop state.
virtual bool enterFailureState ()
Processor for the transition into the failure state.
void resetProcessedStats ()
Reset the processed counters.
virtual bool deliverControlMessage (ACE_Message_Block *data, ACE_Time_Value *timeout)
Give a control message to the task.
bool processMessage (ACE_Message_Block *data)
Process a message, data or control.
virtual bool processDataMessage (ACE_Message_Block *data)
Process a data message.
virtual bool doTimeout ()
Process a timeout expired control message.
virtual bool processControlMessage (ACE_Message_Block *data)
Process a control message.
virtual bool doParametersChange (const ParametersChangeRequest &request)
Process runtime parameter changes from an XML-RPC request.
virtual bool doProcessingStateChange (const ProcessingStateChangeRequest &request)
Respond to a processing state change meessage.
virtual bool doRecordingStateChange (const RecordingStateChangeRequest &request)
Respond to a recording state change meessage.
virtual bool doShutdownRequest ()
Respond to a SHUTDOOWN control meessage.
virtual bool doClearStatsRequest ()
Respond to a ClearStatsRequest control messsage.
void setConnectionInfo (const std::string &connectionInfo)
Set the status text that represents the connection information for the task.
virtual bool send (const Messages::Header::Ref &msg, size_t channelIndex)
bool sendManaged (MessageManager &mgr, size_t channelIndex)
Detailed Description
Publisher of data using TCP transport.
Relies on a ServerSocketWriterTask to do the heady lifing.
Definition at line 18 of file TCPDataPublisher.h.
Member Function Documentation
int TCPDataPublisher::close (u_long flags = 0)
Override of DataPublisher method.
The service is being shutdown.
Parameters
flags if 1 module is shutting down
Returns
0 if successful, -1 otherwise.
Definition at line 85 of file TCPDataPublisher.cc.
References SideCar::IO::DataPublisher::close(), Log(), LOGINFO, and SideCar::IO::Task::setConnectionInfo().
bool TCPDataPublisher::deliverDataMessage (ACE_Message_Block * data, ACE_Time_Value * timeout = 0) protected virtual
Give a message to the task to do with as it pleases.
Derived classes must define.
Parameters
data message to deliver
timeout amount of time to spend trying to deliver message
Returns
true if successful
Implements SideCar::IO::Task.
Definition at line 96 of file TCPDataPublisher.cc.
References SideCar::IO::Task::calculateUsingDataValue(), Log(), LOGINFO, and SideCar::IO::Task::updateUsingDataValue().
Logger::Log & TCPDataPublisher::Log () static
Log device for objects of this type.
Returns
log device
Definition at line 10 of file TCPDataPublisher.cc.
References Logger::Log::Find().
Referenced by close(), deliverDataMessage(), and openAndInit().
TCPDataPublisher::Ref TCPDataPublisher::Make () static
Factory method for creating new TCPDataPublisher objects.
Returns
reference to new DataPublisher object
Definition at line 18 of file TCPDataPublisher.cc.
bool TCPDataPublisher::openAndInit (const std::string & key, const std::string & serviceName, uint16_t port = 0, int bufferSize = 0, long threadFlags = kDefaultThreadFlags, long threadPriority = ACE_DEFAULT_THREAD_PRIORITY)
Open a server connection on a particular port.
Parameters
key message type key of published data
serviceName Zeroconf name of service publishing the data
\return true if successful, false otherwise
Definition at line 42 of file TCPDataPublisher.cc.
References Log(), LOGDEBUG, LOGERROR, LOGINFO, SideCar::IO::ZeroconfTypes::TZCType< id >::MakeZeroconfType(), SideCar::IO::DataPublisher::publish(), SideCar::IO::Task::setConnectionInfo(), SideCar::IO::Task::setError(), SideCar::IO::IOTask::setMetaTypeInfoKeyName(), and SideCar::IO::DataPublisher::setType().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/TCPDataPublisher.h
/Users/howes/src/sidecar/IO/TCPDataPublisher.cc