SideCar: SideCar::IO::MulticastDataSubscriber::ReaderThread Class Reference
SideCar::IO::MulticastDataSubscriber::ReaderThread Class Reference
Internal class used by MulticastDataSubscriber to perform reading from a multicast UDP socket in a separate thread.
Public Member Functions
ReaderThread (MulticastDataSubscriber *owner)
Constructor.
bool openAndInit (const ACE_INET_Addr &remoteAddress, int bufferSize, long threadFlags, long threadPriority)
Initialize the ReaderThread.
int close (u_long flags=0)
Close the connection to a multicast socket.
Static Public Member Functions
static Logger::Log & Log ()
Detailed Description
Internal class used by MulticastDataSubscriber to perform reading from a multicast UDP socket in a separate thread.
Definition at line 27 of file MulticastDataSubscriber.cc.
Constructor & Destructor Documentation
SideCar::IO::MulticastDataSubscriber::ReaderThread::ReaderThread (MulticastDataSubscriber * owner) inline
Constructor.
Parameters
owner
Definition at line 38 of file MulticastDataSubscriber.cc.
Member Function Documentation
int SideCar::IO::MulticastDataSubscriber::ReaderThread::close (u_long flags = 0) inline
Close the connection to a multicast socket.
Also called when the service thread exits the svc() method.
Parameters
flags if non-zero, called by an external entity to shut down the connection; otherwise, called due to service thread exiting
Returns
-1 if error
Definition at line 111 of file MulticastDataSubscriber.cc.
References SideCar::IO::IOTask::acquireExternalMessage(), SideCar::IO::DataSubscriber::close(), SideCar::IO::DatagramReader::fetchInput(), Logger::Log::Find(), SideCar::IO::Reader::getMessage(), SideCar::IO::Task::getTaskName(), SideCar::IO::Reader::isMessageAvailable(), LOGERROR, LOGINFO, and SideCar::IO::ReaderDevices::MulticastSocket::setFetchTimeout().
bool SideCar::IO::MulticastDataSubscriber::ReaderThread::openAndInit (const ACE_INET_Addr & remoteAddress, int bufferSize, long threadFlags, long threadPriority) inline
Initialize the ReaderThread.
Attempt to join a multicast broadcast, and if successful, start a new thread to read data from the socket.
Parameters
remoteAddress multicast address to join
bufferSize value to give to SO_RCVBUF socket setting
Returns
true if successful, false otherwise
Definition at line 50 of file MulticastDataSubscriber.cc.
References SideCar::IO::ReaderDevices::MulticastSocket::getDevice(), SideCar::IO::Task::getTaskName(), SideCar::IO::ReaderDevices::MulticastSocket::join(), LOGDEBUG, LOGERROR, LOGINFO, and SideCar::IO::Task::setError().
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/IO/MulticastDataSubscriber.cc