SideCar: SideCar::GUI::AScope::HistoryPosition Class Reference
SideCar::GUI::AScope::HistoryPosition Class Reference
History position for a given Visualizer object.
#include </Users/howes/src/sidecar/GUI/AScope/HistoryPosition.h>
Public Slots
void setPosition (int position)
Change the viewing position.
void viewingPast (bool state)
void setSynchronized (bool state)
void setInfoReporter (bool state)
Signals
void viewChanged ()
Notification sent out when the position changes in such a way that the view has changed.
void viewingPastChanged (bool state)
void infoUpdate (const Messages::PRIMessage::Ref &msg)
Public Member Functions
HistoryPosition (Visualizer *parent, AzimuthLatch *azimuthLatch)
Constructor.
void restoreFromSettings (QSettings &settings)
void saveToSettings (QSettings &settings)
bool isViewingPast () const
bool isSynchronized () const
bool isInfoReporter () const
int getPastPosition () const
Obtain the current view position.
Messages::PRIMessage::Ref getMessage (int slot) const
Static Public Member Functions
static Logger::Log & Log ()
Detailed Description
History position for a given Visualizer object.
All Visualizer plot widgets share the same History object, but have their own HistoryPosition object so that they may show different views of the historical data. Each view may show historical or live data independent of the other views; the viewingPast() method controls which data is shown.
Definition at line 28 of file HistoryPosition.h.
Constructor & Destructor Documentation
HistoryPosition::HistoryPosition (Visualizer * parent, AzimuthLatch * azimuthLatch)
Constructor.
The initial position is always set to show current data.
Definition at line 27 of file HistoryPosition.cc.
References SideCar::GUI::AScope::History::freezePast(), SideCar::GUI::AScope::History::getLiveFrame(), SideCar::GUI::AScope::HistoryFrame::getSomeMessage(), LOGDEBUG, LOGINFO, and viewChanged().
Member Function Documentation
int SideCar::GUI::AScope::HistoryPosition::getPastPosition () const inline
Obtain the current view position.
Returns
current view position
Definition at line 53 of file HistoryPosition.h.
Referenced by SideCar::GUI::AScope::HistoryControlWidget::HistoryControlWidget().
void HistoryPosition::setPosition (int position) slot
Change the viewing position.
Parameters
position new viewing position
Definition at line 130 of file HistoryPosition.cc.
References SideCar::GUI::AScope::History::freezePast(), SideCar::GUI::AScope::History::getLiveMessage(), SideCar::GUI::AScope::HistoryFrame::getMessage(), SideCar::GUI::AScope::History::getPastFrame(), SideCar::GUI::AScope::History::getSlotIndex(), SideCar::GUI::AScope::HistoryFrame::getSomeMessage(), LOGDEBUG, LOGINFO, and viewChanged().
Referenced by SideCar::GUI::AScope::HistoryControlWindow::activeMainWindowChanged(), and SideCar::GUI::AScope::HistoryControlWidget::HistoryControlWidget().
void SideCar::GUI::AScope::HistoryPosition::viewChanged () signal
Notification sent out when the position changes in such a way that the view has changed.
This is primarily to cause display views to repaint.
Referenced by HistoryPosition(), and setPosition().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/AScope/HistoryPosition.h
/Users/howes/src/sidecar/GUI/AScope/HistoryPosition.cc