SideCar: SideCar::GUI::AppBase Class Reference
SideCar::GUI::AppBase Class Reference abstract
Base application class used by all GUI applications.
#include </Users/howes/src/sidecar/GUI/AppBase.h>
Public Types
enum AngularFormatType { kDegreesMinutesSeconds = 0, kDecimal, kNumFormattingTypes }
Enumeration for the various angular formatting available from the application.
Public Slots
void updateToggleAction (bool state)
virtual void setPhantomCursor (const QPointF &pos)
Set the held phantom cursor value.
void showMessage (const QString &msg, int duration)
Show a message in the active main window.
void setAngleFormatting (AngularFormatType type)
Change the formatting used by getFormattedAngleDegrees() and getFormattedAngleRadians() methods.
void setDistanceUnits (const QString &units)
Change the distance units used by getFormattedDistance() method.
virtual void applicationQuit ()
Action event handler for the "Quit" menu item.
virtual void loggingLoadConfigurationFile ()
Present to the user an open file dialog in order to select a Logger configuration file.
virtual void loadStyleSheet ()
virtual void showAbout ()
virtual void windowNew ()
Signals
void activeMainWindowChanged (MainWindowBase *window)
Notification sent out when the application's active main window changes.
void shutdown ()
Notification sent out when the application is shutting down.
void restoreToolWindows ()
Notification sent out to all ToolWindowBase objects that they should show themselves if they were visible when the application last quit.
void angleFormattingChanged (int type)
Notification sent out when the angular formatting setting has been changed by the user.
void distanceUnitsChanged (const QString &suffix)
Notification sent out when the distance units have been changed by the user.
void phantomCursorChanged (const QPointF &pos)
Notification sent out when the phantom cursor value has been changed.
Public Member Functions
AppBase (const QString &name, int &argc, char **argv)
Constructor.
~AppBase ()
Destructor.
const QString & getApplicationName () const
QString getDocumentationPath () const
WindowManager * getWindowManager () const
QMenu * makeApplicationMenu (QWidget *parent)
QMenu * makeToolsMenu (QWidget *parent)
QMenu * makeWindowMenu (QWidget *parent)
QMenu * makeLoggingMenu (QWidget *parent)
QMenu * makeHelpMenu (QWidget *parent)
QAction * getToolsMenuAction (int index)
Obtain a specific QAction object found in the Tools menu.
void addWindowMenuActionTo (ToolBar *toolBar, int index) const
void setVisibleWindowMenuNew (bool visible)
Set the visibility state of the "New" action in the "Window" menu.
void setVisibleWindowMenuClose (bool visible)
Set the visibility state of the "Close" action in the "Window" menu.
void setVisibleWindowMenuMinimize (bool visible)
Set the visibility state of the "Minimize" action in the "Window" menu.
void setVisibleWindowMenuMaximize (bool visible)
Set the visibility state of the "Maximize" action in the "Window" menu.
void setVisibleWindowMenuFullScreen (bool visible)
Set the visibility state of the full-screen action in the "Window" menu.
void setLogConfigurationFile (const QString &path)
Use a configuration file for the Logger classes.
int getNumManagedWindows () const
Obtain the number of open MainWindowBase objects.
MainWindowBase * getActiveMainWindow () const
Obtain the active MainWindowBase object.
void manageWindow (QWidget *window, QMenu *windowMenu)
Manage a top-level window.
void unmanageWindow (QWidget *window)
Unmanage a top-level window.
bool isManagedWindow (QWidget *window) const
Determine if a given widget is managed by the application.
QWidget * getManagedWindow (const QString &title) const
bool isQuitting () const
Determine if the application is in the process of shutting down.
const QString & getDistanceUnits () const
Obtain the current distance units suffix.
QString getFormattedDistance (double value) const
Obtain a formatted representation of a distance value.
QString getFormattedAngleRadians (double value) const
Obtain a formatted representation of an angular value in radians.
QString getFormattedAngleDegrees (double value) const
Obtain a formatted representation of an angular value in degrees.
QPointF getPhantomCursor () const
Obtain the current phantom cursor value.
virtual void restoreWindows ()
Restore the windows that were open at the time the application last quit.
Static Public Member Functions
static Logger::Log & Log ()
Log device for instances of this class.
static AppBase * GetApp ()
Obtain the AppBase singleton.
static QString GetRootDocumentationPath ()
Protected Member Functions
virtual void addToolWindow (int index, ToolWindowBase *toolWindow)
Register a tool window with the application.
virtual MainWindowBase * makeNewMainWindow (const QString &objectName)=0
Create a new main window and show it.
MainWindowBase * makeAndInitializeNewMainWindow (const QString &type)
Detailed Description
Base application class used by all GUI applications.
Provides window management actions, and logging menu actions. Also provides saving/restoring facilities so that restarted applications have windows and settings from a previous run.
Definition at line 30 of file AppBase.h.
Constructor & Destructor Documentation
AppBase::AppBase (const QString & name, int & argc, char ** argv)
Constructor.
Parameters
name the name of the application
argc argument count from the command line
argv argument values from the command line
Definition at line 58 of file AppBase.cc.
References activeMainWindowChanged(), Log(), LOGINFO, Logger::Log::Root(), and Logger::Log::setPriorityLimit().
Member Function Documentation
void SideCar::GUI::AppBase::activeMainWindowChanged (MainWindowBase * window) signal
Notification sent out when the application's active main window changes.
Parameters
window the new active window (may be NULL).
Referenced by AppBase().
void AppBase::addToolWindow (int index, ToolWindowBase * toolWindow) protected virtual
Register a tool window with the application.
Adds the tool window's show/hide QAction object to the end of the Application menu.
Parameters
toolWindow the tool window to add
Definition at line 328 of file AppBase.cc.
References SideCar::GUI::WindowManager::getActiveMainWindow(), SideCar::GUI::ToolWindowBase::getShowHideAction(), SideCar::GUI::MainWindowBase::initialize(), Log(), LOGDEBUG, loggingLoadConfigurationFile(), LOGINFO, SideCar::GUI::MakeMenuAction(), makeNewMainWindow(), restoreToolWindows(), and SideCar::GUI::MainWindowBase::showAndRaise().
Referenced by SideCar::GUI::Playback::App::App(), SideCar::GUI::HealthAndStatus::App::App(), SideCar::GUI::ESScope::App::App(), SideCar::GUI::BScope::App::App(), SideCar::GUI::Spectrum::App::App(), SideCar::GUI::PPIDisplay::App::App(), and SideCar::GUI::AScope::App::~App().
void SideCar::GUI::AppBase::angleFormattingChanged (int type) signal
Notification sent out when the angular formatting setting has been changed by the user.
Parameters
type the new formatting type in use
Referenced by setAngleFormatting().
void AppBase::applicationQuit () virtual slot
Action event handler for the "Quit" menu item.
Saves open window settings, the current logging settings, emits the shutdown() signal, and then finally closes all open windows.
Reimplemented in SideCar::GUI::HealthAndStatus::App.
Definition at line 289 of file AppBase.cc.
References getNumManagedWindows(), Log(), LOGWARNING, and shutdown().
Referenced by SideCar::GUI::ESScope::App::App(), SideCar::GUI::Spectrum::App::App(), SideCar::GUI::HealthAndStatus::App::applicationQuit(), SideCar::GUI::PPIDisplay::App::makeNewMainWindow(), SideCar::GUI::Master::App::restoreWindows(), SideCar::GUI::BScope::App::restoreWindows(), setVisibleWindowMenuFullScreen(), and ~AppBase().
void SideCar::GUI::AppBase::distanceUnitsChanged (const QString & suffix) signal
Notification sent out when the distance units have been changed by the user.
Parameters
suffix new distance units
Referenced by setDistanceUnits().
MainWindowBase * AppBase::getActiveMainWindow () const
Obtain the active MainWindowBase object.
NOTE: this may be NULL.
Returns
active MainWindowBase object
Definition at line 492 of file AppBase.cc.
References SideCar::GUI::WindowManager::getActiveMainWindow().
Referenced by SideCar::GUI::AScope::App::addDisplayView().
AppBase * AppBase::GetApp () static
Obtain the AppBase singleton.
Returns
AppBase object
Definition at line 53 of file AppBase.cc.
Referenced by SideCar::GUI::Playback::App::GetApp(), SideCar::GUI::ToolWindowBase::getApp(), SideCar::GUI::MainWindowBase::getApp(), SideCar::GUI::Master::App::GetApp(), SideCar::GUI::ChannelSetting::Log(), SideCar::GUI::WindowManager::makeWindowMenu(), SideCar::GUI::RadarInfoWidget::RadarInfoWidget(), SideCar::GUI::ESScope::RadarInfoWidget::RadarInfoWidget(), and SideCar::GUI::WindowManager::unmanageWindow().
const QString& SideCar::GUI::AppBase::getDistanceUnits () const inline
Obtain the current distance units suffix.
Note that the suffix already has a space at the start.
Returns
current distance units.
Definition at line 181 of file AppBase.h.
QString AppBase::getFormattedAngleDegrees (double value) const
Obtain a formatted representation of an angular value in degrees.
Parameters
value the numerical value in degrees to format
Returns
textual angular value
Definition at line 438 of file AppBase.cc.
References SideCar::GUI::DegreesToString().
Referenced by SideCar::GUI::ESScope::RadarInfoWidget::RadarInfoWidget().
QString AppBase::getFormattedAngleRadians (double value) const
Obtain a formatted representation of an angular value in radians.
Parameters
value the numerical value in radians to format
Returns
textual angular value
Definition at line 432 of file AppBase.cc.
References SideCar::GUI::RadiansToString().
Referenced by SideCar::GUI::ESScope::CursorWidget::CursorWidget(), SideCar::GUI::BScope::CursorWidget::CursorWidget(), and SideCar::GUI::RadarInfoWidget::showMessageInfo().
QString AppBase::getFormattedDistance (double value) const
Obtain a formatted representation of a distance value.
Parameters
value the numerical value to format
Returns
textual distance value
Definition at line 419 of file AppBase.cc.
References SideCar::GUI::DistanceToString().
Referenced by SideCar::GUI::AScope::CursorWidget::CursorWidget(), SideCar::GUI::ESScope::CursorWidget::CursorWidget(), and SideCar::GUI::BScope::CursorWidget::CursorWidget().
int AppBase::getNumManagedWindows () const
Obtain the number of open MainWindowBase objects.
Returns
window count
Definition at line 486 of file AppBase.cc.
References SideCar::GUI::WindowManager::getNumManagedWindows().
Referenced by applicationQuit(), and SideCar::GUI::MainWindowBase::closeEvent().
QPointF SideCar::GUI::AppBase::getPhantomCursor () const inline
Obtain the current phantom cursor value.
The AppBase object only updates this value from the setPhantomCursor() slot.
Returns
QPointF value
Definition at line 212 of file AppBase.h.
QAction* SideCar::GUI::AppBase::getToolsMenuAction (int index) inline
Obtain a specific QAction object found in the Tools menu.
Parameters
index which QAction to fetch
Returns
QAction object
Definition at line 94 of file AppBase.h.
Referenced by SideCar::GUI::Playback::App::GetApp(), and SideCar::GUI::Master::App::GetApp().
bool AppBase::isManagedWindow (QWidget * window) const
Determine if a given widget is managed by the application.
Parameters
window the widget to test
Returns
true if so
Definition at line 510 of file AppBase.cc.
References SideCar::GUI::WindowManager::getManagedWindow(), and SideCar::GUI::WindowManager::isManagedWindow().
bool SideCar::GUI::AppBase::isQuitting () const inline
Determine if the application is in the process of shutting down.
This flag is only set from within the applicationQuit() slot.
Returns
true if so
Definition at line 175 of file AppBase.h.
Referenced by SideCar::GUI::MainWindowBase::closeEvent(), SideCar::GUI::BScope::MainWindow::initialize(), SideCar::GUI::PPIDisplay::MainWindow::MainWindow(), SideCar::GUI::HealthAndStatus::MainWindow::MainWindow(), SideCar::GUI::Spectrum::MainWindow::MainWindow(), SideCar::GUI::Master::MainWindow::MainWindow(), SideCar::GUI::ESScope::MainWindow::MainWindow(), and SideCar::GUI::SignalGenerator::MainWindow::saveToSettings().
Logger::Log & AppBase::Log () static
Log device for instances of this class.
Returns
log device
Definition at line 46 of file AppBase.cc.
References Logger::Log::Find().
Referenced by addToolWindow(), AppBase(), applicationQuit(), loggingLoadConfigurationFile(), restoreWindows(), setLogConfigurationFile(), setPhantomCursor(), setVisibleWindowMenuFullScreen(), and ~AppBase().
void AppBase::loggingLoadConfigurationFile () virtual slot
Present to the user an open file dialog in order to select a Logger configuration file.
If a file is choosen, create and install a Logger::ConfiguratorFile object.
Definition at line 253 of file AppBase.cc.
References Log(), LOGDEBUG, LOGINFO, and setLogConfigurationFile().
Referenced by addToolWindow().
virtual MainWindowBase* SideCar::GUI::AppBase::makeNewMainWindow (const QString & objectName) protected pure virtual
Create a new main window and show it.
Derived classes must define.
Parameters
objectName the type of main window to create.
Returns
new MainWindowBase object
Implemented in SideCar::GUI::PPIDisplay::App, SideCar::GUI::ZeroconfMonitor::App, SideCar::GUI::PRIEmitter::App, SideCar::GUI::ExtractionEmitter::App, SideCar::GUI::RangeTruthEmitter::App, and SideCar::GUI::SignalGenerator::App.
Referenced by addToolWindow().
void AppBase::manageWindow (QWidget * window, QMenu * windowMenu)
Manage a top-level window.
Managed windows have their own QAction object installed in the "Window" menu so that the user can make a window active from the menubar or keyboard.
\param window the window to manage
Definition at line 498 of file AppBase.cc.
References SideCar::GUI::WindowManager::manageWindow().
Referenced by SideCar::GUI::MainWindowBase::showEvent().
void SideCar::GUI::AppBase::phantomCursorChanged (const QPointF & pos) signal
Notification sent out when the phantom cursor value has been changed.
Parameters
pos new phantom cursor value
Referenced by setPhantomCursor().
void AppBase::restoreWindows () virtual
Restore the windows that were open at the time the application last quit.
Emits the restoreToolWindows() signal after all main windows have been restored.
Reimplemented in SideCar::GUI::BScope::App, and SideCar::GUI::Master::App.
Definition at line 180 of file AppBase.cc.
References Log(), LOGDEBUG, LOGINFO, restoreToolWindows(), and SideCar::GUI::MainWindowBase::showAndRaise().
Referenced by SideCar::GUI::Master::App::restoreWindows(), and SideCar::GUI::BScope::App::restoreWindows().
void AppBase::setAngleFormatting (AngularFormatType type) slot
Change the formatting used by getFormattedAngleDegrees() and getFormattedAngleRadians() methods.
Parameters
type new type to use
Definition at line 425 of file AppBase.cc.
References angleFormattingChanged().
Referenced by SideCar::GUI::AScope::ConfigurationWindow::ConfigurationWindow().
void AppBase::setDistanceUnits (const QString & units) slot
Change the distance units used by getFormattedDistance() method.
Parameters
units new units to use
Definition at line 410 of file AppBase.cc.
References distanceUnitsChanged().
Referenced by SideCar::GUI::AScope::ConfigurationWindow::ConfigurationWindow().
void AppBase::setLogConfigurationFile (const QString & path)
Use a configuration file for the Logger classes.
Parameters
path file path
Definition at line 221 of file AppBase.cc.
References Log(), LOGDEBUG, LOGINFO, LOGWARNING, Logger::ConfiguratorFile::startMonitor(), and Logger::ConfiguratorFile::stopMonitor().
Referenced by loggingLoadConfigurationFile().
void AppBase::setPhantomCursor (const QPointF & pos) virtual slot
Set the held phantom cursor value.
Emits the phantomCursorChanged() signal if the given value is different than the held one.
Parameters
pos new phantom cursor value
Definition at line 452 of file AppBase.cc.
References Log(), LOGINFO, phantomCursorChanged(), and SideCar::GUI::UpdateToggleAction().
Referenced by SideCar::GUI::BScope::PastImage::Log().
void AppBase::setVisibleWindowMenuClose (bool visible)
Set the visibility state of the "Close" action in the "Window" menu.
Parameters
visible true if visible
Definition at line 528 of file AppBase.cc.
References SideCar::GUI::WindowManager::setVisibleWindowMenuClose().
void AppBase::setVisibleWindowMenuFullScreen (bool visible)
Set the visibility state of the full-screen action in the "Window" menu.
Parameters
visible true if visible
Definition at line 546 of file AppBase.cc.
References SideCar::GUI::WindowManager::addWindowMenuActionTo(), applicationQuit(), Log(), LOGINFO, and SideCar::GUI::WindowManager::setVisibleWindowMenuFullScreen().
Referenced by SideCar::GUI::PRIEmitter::MainWindow::MainWindow().
void AppBase::setVisibleWindowMenuMaximize (bool visible)
Set the visibility state of the "Maximize" action in the "Window" menu.
Parameters
visible true if visible
Definition at line 540 of file AppBase.cc.
References SideCar::GUI::WindowManager::setVisibleWindowMenuMaximize().
Referenced by SideCar::GUI::PRIEmitter::MainWindow::MainWindow().
void AppBase::setVisibleWindowMenuMinimize (bool visible)
Set the visibility state of the "Minimize" action in the "Window" menu.
Parameters
visible true if visible
Definition at line 534 of file AppBase.cc.
References SideCar::GUI::WindowManager::setVisibleWindowMenuMinimize().
void AppBase::setVisibleWindowMenuNew (bool visible)
Set the visibility state of the "New" action in the "Window" menu.
Parameters
visible true if visible
Definition at line 522 of file AppBase.cc.
References SideCar::GUI::WindowManager::setVisibleWindowMenuNew().
Referenced by SideCar::GUI::Playback::App::App(), SideCar::GUI::HealthAndStatus::App::App(), SideCar::GUI::ESScope::App::App(), SideCar::GUI::BScope::App::App(), SideCar::GUI::Spectrum::App::App(), SideCar::GUI::PPIDisplay::App::App(), and SideCar::GUI::PRIEmitter::MainWindow::MainWindow().
void AppBase::showMessage (const QString & msg, int duration) slot
Show a message in the active main window.
Parameters
msg text of the message to show
duration amount of time in milliseconds to show the message; zero shows the message forever until cleared or replaced by another message.
Definition at line 444 of file AppBase.cc.
References SideCar::GUI::WindowManager::getActiveMainWindow().
void AppBase::unmanageWindow (QWidget * window)
Unmanage a top-level window.
Usually invoked when a window closes. Removes the associated QAction object from the "Window" menu.
Parameters
window the window to unmanage.
Definition at line 504 of file AppBase.cc.
References SideCar::GUI::WindowManager::unmanageWindow().
Referenced by SideCar::GUI::MainWindowBase::closeEvent().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/AppBase.h
/Users/howes/src/sidecar/GUI/AppBase.cc