SideCar: SideCar::GUI::TimeSetting Class Reference
SideCar::GUI::TimeSetting Class Reference
Derivation of the Setting class that manages QTime values (HH:MM:SS)
#include </Users/howes/src/sidecar/GUI/TimeSetting.h>
Public Slots
void setValue (const QTime &value)
Change the setting value.
Public Slots inherited from SideCar::GUI::Setting
void setEnabled (bool state)
Signals
void valueChanged (const QTime &value)
Notification sent out when the held value changes.
Signals inherited from SideCar::GUI::Setting
void save (int index, const QVariant &value)
Notification sent out by the Setting object when the held value changes due to the setValue() method.
void enabledChanged (bool state)
Notification sent out by the Setting object when its enabled state changes.
void valueChanged ()
Public Member Functions
TimeSetting (PresetManager *mgr, const QString &name, bool global=false)
Constructor.
TimeSetting (PresetManager *mgr, const QString &name, const QTime &value, bool global=false)
Constructor.
const QTime & getValue () const
Obtain the current setting value.
void connectWidget (QTimeEdit *widget)
Public Member Functions inherited from SideCar::GUI::Setting
Setting (PresetManager *mgr, const QString &name, bool global=false)
Constructor without a default setting value.
Setting (PresetManager *mgr, const QString &name, const QVariant &value, bool global=false)
Constructor with a default setting value.
const QString & getName () const
Obtain the name of the Setting object.
const QVariant & getOpaqueValue () const
Obtain the current value of the Setting object.
void setOpaqueValue (const QVariant &value)
Set the Setting's value and emit the opaqueValueChanged() signal followed by the save() signal.
bool isEnabled () const
Protected Member Functions
void valueUpdated ()
Override of Setting::valueUpdated() method.
Protected Member Functions inherited from SideCar::GUI::Setting
void resetOpaqueValue ()
void connectWidget (QWidget *widget)
void disconnectWidget (QWidget *widget)
Additional Inherited Members
Static Public Member Functions inherited from SideCar::GUI::Setting
static Logger::Log & Log ()
Log device for Setting objects.
Detailed Description
Derivation of the Setting class that manages QTime values (HH:MM:SS)
Definition at line 15 of file TimeSetting.h.
Constructor & Destructor Documentation
TimeSetting::TimeSetting (PresetManager * mgr, const QString & name, bool global = false)
Constructor.
Parameters
mgr
name
global
Definition at line 7 of file TimeSetting.cc.
References SideCar::GUI::Setting::getOpaqueValue().
TimeSetting::TimeSetting (PresetManager * mgr, const QString & name, const QTime & value, bool global = false)
Constructor.
Parameters
mgr
name
value
global
Definition at line 14 of file TimeSetting.cc.
References SideCar::GUI::Setting::getOpaqueValue().
Member Function Documentation
const QTime& SideCar::GUI::TimeSetting::getValue () const inline
Obtain the current setting value.
Returns
setting value
Definition at line 48 of file TimeSetting.h.
References setValue(), valueChanged(), and valueUpdated().
void TimeSetting::setValue (const QTime & value) slot
Change the setting value.
Emits the valueChanged() signal if the given value is different than the held one.
Parameters
value new value to use.
Definition at line 22 of file TimeSetting.cc.
References SideCar::GUI::Setting::setOpaqueValue().
Referenced by getValue(), and valueUpdated().
void SideCar::GUI::TimeSetting::valueChanged (const QTime & value) signal
Notification sent out when the held value changes.
Parameters
value new held value
Referenced by getValue(), and valueUpdated().
void TimeSetting::valueUpdated () protected virtual
Override of Setting::valueUpdated() method.
Records the new value and emits the valueChanged() signal.
Reimplemented from SideCar::GUI::Setting.
Definition at line 29 of file TimeSetting.cc.
References SideCar::GUI::Setting::getOpaqueValue(), setValue(), and valueChanged().
Referenced by getValue().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/TimeSetting.h
/Users/howes/src/sidecar/GUI/TimeSetting.cc