SideCar: SideCar::IO::ControlMessage Class Reference
SideCar::IO::ControlMessage Class Reference
Base class for all SideCar control messages.
#include </Users/howes/src/sidecar/IO/ControlMessage.h>
Public Types
enum Type {
kInvalid = -1, kParametersChange, kProcessingStateChange, kRecordingStateChange,
kShutdown, kClearStats, kTimeout, kNumTypes
}
Control message types.
Public Member Functions
ControlMessage (const ControlMessage &copy)
Copy constructor.
virtual ~ControlMessage ()
Destructor.
ACE_Message_Block * getWrapped () const
Obtain the control message wrapped inside an ACE_Message_Block object.
Protected Member Functions
ControlMessage (Type type, size_t size)
ControlMessage (ACE_Message_Block *data)
ACE_Message_Block * getData () const
Detailed Description
Base class for all SideCar control messages.
A control message affects the runtime behavior of one or more IO::Task objects. One cannot instantiate a ControlMessage directly.
Definition at line 12 of file ControlMessage.h.
Member Enumeration Documentation
enum SideCar::IO::ControlMessage::Type
Control message types.
When wrapped by an ACE_Message_Block, the block will have a message type equal to IO::MessageManager::kControl + one of the following values. When creating new control messages, add new values to the end of the enumeration.
Enumerator
kParametersChange
Remote parameter change message.
The contents of the buffer is an XmlRpc::XmlRpcValue value, containing one or more name/value pairs describing new parameter settings.
kProcessingStateChange
Remote state change message.
The contents of the buffer is an int value specifying the new state.
kRecordingStateChange
Recording mode change message.
The contents of the buffer is a boolean value indicating the recording state.
kShutdown
Shutdown a stream.
kClearStats
Clear statistics.
kTimeout
Process an alarm that an Algorithm has set for itself.
Definition at line 20 of file ControlMessage.h.
Constructor & Destructor Documentation
SideCar::IO::ControlMessage::ControlMessage (const ControlMessage & copy) inline
Copy constructor.
Parameters
copy object to copy
Definition at line 57 of file ControlMessage.h.
Referenced by getWrapped().
virtual SideCar::IO::ControlMessage::~ControlMessage () inline virtual
Destructor.
Decrease reference count on held data block.
Definition at line 61 of file ControlMessage.h.
Member Function Documentation
ACE_Message_Block* SideCar::IO::ControlMessage::getWrapped () const inline
Obtain the control message wrapped inside an ACE_Message_Block object.
Used to transport ControlMessage objects from one task to another.
Returns
ACE_Message_Block object
Definition at line 68 of file ControlMessage.h.
References ControlMessage().
Referenced by SideCar::Runner::App::App(), SideCar::Algorithms::Controller::injectControlMessage(), SideCar::Runner::App::setParameters(), and SideCar::IO::FileReaderTask::svc().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/ControlMessage.h
/Users/howes/src/sidecar/IO/ControlMessage.cc