SideCar: SideCar::IO::TimeIndex Class Reference
SideCar::IO::TimeIndex Class Reference
Data Structures
struct Entry
Public Types
using const_iterator = const Entry *
Public Member Functions
TimeIndex (const std::string &path)
Constructor.
off_t findOnOrBefore (uint32_t when) const
Find the record with the greatest time value that is equal to or less than the given value.
off_t getLastEntry () const
Obtain the offset for the last entry.
bool empty () const
size_t size () const
const_iterator begin () const
const_iterator end () const
Static Public Member Functions
static Logger::Log & Log ()
static std::string const & GetIndexFileSuffix ()
Detailed Description
Definition at line 13 of file TimeIndex.h.
Constructor & Destructor Documentation
TimeIndex::TimeIndex (const std::string & path)
Constructor.
Parameters
path location of index file to load
Definition at line 31 of file TimeIndex.cc.
References Utils::FilePath::c_str(), Utils::Exception::err(), Utils::FilePath::exists(), LOGDEBUG, LOGERROR, LOGINFO, and Logger::ProcLog::thrower().
Member Function Documentation
off_t TimeIndex::findOnOrBefore (uint32_t when) const
Find the record with the greatest time value that is equal to or less than the given value.
If the time is less than the first entry, the offset to the first entry is returned (0).
\param when time to look for
\return offset found
Definition at line 87 of file TimeIndex.cc.
References LOGDEBUG, and LOGINFO.
Referenced by Args::Args(), and SideCar::GUI::Playback::Emitter::setEmitting().
off_t SideCar::IO::TimeIndex::getLastEntry () const inline
Obtain the offset for the last entry.
Returns
offset found
Definition at line 53 of file TimeIndex.h.
Referenced by SideCar::GUI::Playback::Emitter::~Emitter().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/TimeIndex.h
/Users/howes/src/sidecar/IO/TimeIndex.cc