SideCar: SideCar::Zeroconf::ACEMonitor Class Reference
SideCar::Zeroconf::ACEMonitor Class Reference
Concrete implementation of the Monitor class that relies on the ACE infrastructure to determine when a Zeroconf object has data available for processing.
#include </Users/howes/src/sidecar/Zeroconf/ACEMonitor.h>
Public Member Functions
ACEMonitor ()
Constructor.
~ACEMonitor ()
Destructor.
Public Member Functions inherited from SideCar::Zeroconf::Monitor
virtual ~Monitor ()
Destructor.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for ACEMonitor objects.
Additional Inherited Members
Protected Member Functions inherited from SideCar::Zeroconf::Monitor
Monitor ()
Constructor.
Transaction * getMonitored () const
Obtain the monitored object.
Detailed Description
Concrete implementation of the Monitor class that relies on the ACE infrastructure to determine when a Zeroconf object has data available for processing.
When there is, it invokes Transaction::processConnection() to handle the incoming data.
The handle_input() method is the notification mechanism that ACE uses when there is data available from the file descriptor or socket managed by the ACEMonitor.
Definition at line 21 of file ACEMonitor.h.
Constructor & Destructor Documentation
ACEMonitor::ACEMonitor ()
Constructor.
Sets up the ACE_Event_Handler base class to use the global ACE_Reactor object.
Definition at line 17 of file ACEMonitor.cc.
References Log(), and LOGINFO.
Member Function Documentation
Logger::Log & ACEMonitor::Log () static
Obtain the log device for ACEMonitor objects.
Returns
log device
Definition at line 11 of file ACEMonitor.cc.
References Logger::Log::Find().
Referenced by ACEMonitor(), and ~ACEMonitor().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Zeroconf/ACEMonitor.h
/Users/howes/src/sidecar/Zeroconf/ACEMonitor.cc