SideCar: SideCar::IO::TaskStatus Class Reference
SideCar::IO::TaskStatus Class Reference
Extension of StatusBase to include Task-specific information, such as processing state, seen message count, and mesage and byte rates.
#include </Users/howes/src/sidecar/IO/TaskStatus.h>
Public Types
enum {
kProcessingState = StatusBase::kNumSlots, kError, kConnectionInfo, kMessageCount,
kByteRate, kMessageRate, kDropCount, kDupeCount,
kPendingQueueCount, kHasParameters, kUsingData, kNumSlots
}
Public Types inherited from SideCar::IO::StatusBase
enum Index { kVersion = 0, kClassName, kName, kNumSlots }
Indices for status elements managed by this class.
Public Member Functions
TaskStatus (const XmlRpc::XmlRpcValue &status)
ProcessingState::Value getProcessingState () const
Obtain the processing state value held in the status container.
std::string getError () const
std::string getConnectionInfo () const
int getMessageCount () const
Obtain the running message count held in the status container.
int getByteRate () const
int getMessageRate () const
int getDropCount () const
int getDupeCount () const
int getPendingQueueCount () const
bool hasParameters () const
bool isUsingData () const
Public Member Functions inherited from SideCar::IO::StatusBase
StatusBase (size_t numSlots, const std::string &className, const std::string &name)
StatusBase (const XmlRpc::XmlRpcValue &status)
Conversion constructor.
const XmlRpc::XmlRpcValue & getXMLData () const
Creates an XML value from the internal data.
bool isValid () const
Determine if the held value is valid.
const XmlRpc::XmlRpcValue & getSlot (size_t index) const
Obtain a status value at a particular index.
void setSlot (size_t index, const XmlRpc::XmlRpcValue &value)
Obtain a status value at a particular index.
std::string getVersion () const
bool isLatestVersion () const
std::string getClassName () const
Obtain the class name held in the status container.
std::string getName () const
Obtain the object name held in the status container.
const XmlRpc::XmlRpcValue & operator[] (size_t index) const
bool operator== (const StatusBase &rhs) const
Determine if the held status information is the same as that in another status container.
bool operator!= (const StatusBase &rhs) const
Determine if the held status information is not the same as that in another status container.
std::ostream & print (std::ostream &os) const
Print out an XML representation of the held status values.
Static Public Member Functions
static const char * GetClassName ()
Static Public Member Functions inherited from SideCar::IO::StatusBase
static std::string GetCompiledVersion ()
static void Make (XmlRpc::XmlRpcValue &status, size_t numSlots, const std::string &className, const std::string &name)
Detailed Description
Extension of StatusBase to include Task-specific information, such as processing state, seen message count, and mesage and byte rates.
Definition at line 14 of file TaskStatus.h.
Member Function Documentation
int SideCar::IO::TaskStatus::getMessageCount () const inline
Obtain the running message count held in the status container.
Returns
message count
Definition at line 52 of file TaskStatus.h.
References SideCar::IO::StatusBase::getSlot().
Referenced by SideCar::GUI::Master::TaskItem::beforeUpdate().
ProcessingState::Value SideCar::IO::TaskStatus::getProcessingState () const inline
Obtain the processing state value held in the status container.
Returns
ProcessingState::Value value
Definition at line 41 of file TaskStatus.h.
References SideCar::IO::StatusBase::getSlot().
Referenced by SideCar::GUI::Master::TaskItem::afterUpdate().
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/IO/TaskStatus.h