SideCar: SideCar::GUI::AScope::Visualizer Class Reference
SideCar::GUI::AScope::Visualizer Class Reference
Render widget for the AScope application.
#include </Users/howes/src/sidecar/GUI/AScope/Visualizer.h>
Public Slots
void centerAtCursor ()
void setBackground (const QImage &background)
void needUpdate ()
void setFrozen (bool state)
void setShowGrid (bool state)
void setShowPeakBars (bool state)
void raiseChannelConnection (int index)
void lowerChannelConnection (int index)
void swapViews ()
void popView ()
void popAllViews ()
void zoom (const QPoint &from, const QPoint &to)
void pan (const QPoint &from, const QPoint &to)
Signals
void transformChanged ()
void pointerMoved (const QPoint &local, const QPointF &world)
void channelConnectionsChanged (const QSet< QString > &names)
Public Member Functions
Visualizer (DisplayView *parent, AzimuthLatch *azimuthLatch)
Constructor.
bool isFrozen () const
bool isShowingGrid () const
bool isShowingPeakBars () const
HistoryPosition * getHistoryPosition () const
void saveToSettings (QSettings &settings)
void restoreFromSettings (QSettings &settings)
void duplicate (const Visualizer *other)
void addVideoChannel (VideoChannel &channel, bool visible, bool showPeakBars)
VideoChannel * removeChannelConnection (int index)
const QSet< QString > & getConnectionNames () const
ChannelConnection * getChannelConnection (const QString &name) const
ChannelConnection * getChannelConnection (int row) const
Obtain the ChannelConnection object at a particular index.
int findVideoChannel (VideoChannel *channel) const
bool isConnectedToChannel (VideoChannel *channel) const
int getNumChannelConnections () const
Obtain the number of held ChannelConnection objects.
const ViewSettings & getFullView () const
const ViewSettings & getCurrentView () const
void setShowingRanges (bool state)
void setShowingVoltages (bool state)
void setCurrentView (const ViewSettings &viewSettings)
void dupView ()
bool canPopView () const
const QMatrix & getTransform () const
const QMatrix & getInverseTransform () const
QPointF fromViewToWorld (const QPoint &point)
Static Public Member Functions
static Logger::Log & Log ()
Detailed Description
Render widget for the AScope application.
Draws data from one or more VideoChannel connections. Maintains a stack of ViewSettings settings which define the current view. Panning and zooming add to the stack, while menu actions exist to pop entries off, returning to a previous view.
Definition at line 38 of file Visualizer.h.
Constructor & Destructor Documentation
Visualizer::Visualizer (DisplayView * parent, AzimuthLatch * azimuthLatch)
Constructor.
Creates a new Visualizer from scratch.
Parameters
parent widget parent
Definition at line 38 of file Visualizer.cc.
References SideCar::GUI::AScope::ViewChanger::finished(), SideCar::GUI::AScope::App::GetApp(), SideCar::GUI::AScope::ChannelConnection::getChannel(), SideCar::GUI::AScope::App::getChannelConnectionWindow(), SideCar::GUI::AScope::VideoChannel::getName(), SideCar::GUI::AScope::ChannelConnectionWindow::getVideoChannel(), SideCar::GUI::AScope::App::getViewEditor(), SideCar::GUI::AScope::VideoChannel::isDisplayed(), SideCar::GUI::AScope::ChannelConnection::isShowingPeakBars(), SideCar::GUI::AScope::ChannelConnection::isVisible(), LOGDEBUG, LOGINFO, and SideCar::GUI::AScope::ViewChanger::mouseMoved().
Member Function Documentation
ChannelConnection* SideCar::GUI::AScope::Visualizer::getChannelConnection (int row) const inline
Obtain the ChannelConnection object at a particular index.
Returns
ChannelConnection object
Definition at line 82 of file Visualizer.h.
int SideCar::GUI::AScope::Visualizer::getNumChannelConnections () const inline
Obtain the number of held ChannelConnection objects.
Returns
ChannelConnection counnt
Definition at line 94 of file Visualizer.h.
Referenced by SideCar::GUI::AScope::ChannelConnectionModel::rowCount(), and SideCar::GUI::AScope::ChannelConnectionModel::setVisualizer().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/AScope/Visualizer.h
/Users/howes/src/sidecar/GUI/AScope/Visualizer.cc