SideCar: SideCar::GUI::Playback::Emitter Class Reference
SideCar::GUI::Playback::Emitter Class Reference
Message emitter for the Playback application.
#include </Users/howes/src/sidecar/GUI/Playback/Emitter.h>
Signals
void loadPercentageUpdate (int row)
void subscriberCountChanged (int row)
Public Member Functions
Emitter (MainWindow *mainWindow, const QFileInfo &fileInfo, int row, bool emitting)
Constructor.
~Emitter ()
Destructor.
bool isValid () const
void load (const QFileInfo &fileInfo)
const QString & getName () const
Obtain the name of the recording file being emitted.
int getPort () const
const Time::TimeStamp & getStartTime () const
Obtain the time of the first record in the file.
const Time::TimeStamp & getEndTime () const
Obtain the time of the last record in the file.
Time::TimeStamp getDuration () const
Obtain the duration of the recording file we represent.
bool getEmitting () const
Determine if the emitter is enabled to run.
double getLoadPercentage () const
size_t getSubscriberCount () const
void setEmitting (bool emitting)
Set whether the emitter should run when start() is invoked.
QString getFormattedStartTime () const
QString getFormattedEndTime () const
QString getFormattedDuration () const
int getRow () const
void makeWriter (bool restart=false)
Create a new publisher for the data stream.
Static Public Member Functions
static Logger::Log & Log ()
Log device for instances of this class.
Detailed Description
Message emitter for the Playback application.
Takes an existing recording file and a IO::TimeIndex file derived from it, and emits records from the file with time sequencing similar to the the original recording, only transposed to a current time frame.
The Emitter processing happens in a separate thread in the run() method. The main thread controls thread execution via the start() and stop() methods.
Definition at line 33 of file Emitter.h.
Constructor & Destructor Documentation
Emitter::Emitter (MainWindow * mainWindow, const QFileInfo & fileInfo, int row, bool emitting)
Constructor.
Initializes a new Emitter object.
Parameters
mainWindow the MainWindow parent of the Emitter
fileInfo QFileInfo object referring to the data file to emit
emitting true if the emitter will emit when start() is called
Definition at line 33 of file Emitter.cc.
References Log(), and LOGINFO.
Emitter::~Emitter ()
Destructor.
Makes sure thread is stopped.
Definition at line 44 of file Emitter.cc.
References SideCar::IO::StreamReader::fetchInput(), SideCar::Messages::MetaTypeInfo::Find(), SideCar::IO::ReaderDevices::File::getDevice(), SideCar::Messages::Header::getGloballyUniqueID(), SideCar::IO::TimeIndex::getLastEntry(), SideCar::IO::Reader::getMessage(), SideCar::IO::Reader::isMessageAvailable(), SideCar::Messages::MetaTypeInfo::kVideo, SideCar::Messages::Header::load(), and SideCar::GUI::MessageWriter::stop().
Member Function Documentation
Time::TimeStamp SideCar::GUI::Playback::Emitter::getDuration () const inline
Obtain the duration of the recording file we represent.
Returns
Time::TimeStamp value containing getEndTime() - getStartTime()
Definition at line 87 of file Emitter.h.
bool SideCar::GUI::Playback::Emitter::getEmitting () const inline
Determine if the emitter is enabled to run.
Returns
true if so
Definition at line 93 of file Emitter.h.
Referenced by SideCar::GUI::Playback::FileModel::data().
const Time::TimeStamp& SideCar::GUI::Playback::Emitter::getEndTime () const inline
Obtain the time of the last record in the file.
This is in the recording's frame of reference.
Returns
Time::TimeStamp value in clock time
Definition at line 81 of file Emitter.h.
Referenced by SideCar::GUI::Playback::FileModel::beginLoad().
const QString& SideCar::GUI::Playback::Emitter::getName () const inline
Obtain the name of the recording file being emitted.
Returns
file name
Definition at line 67 of file Emitter.h.
Referenced by SideCar::GUI::Playback::FileModel::beginLoad(), SideCar::GUI::Playback::FileModel::data(), SideCar::GUI::Playback::LoaderThread::Log(), and SideCar::GUI::Playback::FileModel::setData().
const Time::TimeStamp& SideCar::GUI::Playback::Emitter::getStartTime () const inline
Obtain the time of the first record in the file.
This is in the recording's frame of reference.
Returns
Time::TimeStamp value in clock time
Definition at line 75 of file Emitter.h.
Referenced by SideCar::GUI::Playback::FileModel::beginLoad().
Logger::Log & Emitter::Log () static
Log device for instances of this class.
Returns
log device
Definition at line 27 of file Emitter.cc.
References Logger::Log::Find().
Referenced by Emitter(), makeWriter(), and setEmitting().
void Emitter::setEmitting (bool emitting)
Set whether the emitter should run when start() is invoked.
Parameters
emitting new value
Definition at line 199 of file Emitter.cc.
References SideCar::IO::StreamReader::fetchInput(), SideCar::IO::TimeIndex::findOnOrBefore(), SideCar::GUI::Playback::Clock::formatDuration(), SideCar::GUI::Playback::Clock::formatTimeStamp(), SideCar::Messages::Header::getCreatedTimeStamp(), SideCar::IO::ReaderDevices::File::getDevice(), SideCar::IO::Reader::getMessage(), SideCar::IO::MessageManager::getMessage(), SideCar::Time::TimeStamp::getMicro(), SideCar::IO::MessageManager::getNative(), SideCar::GUI::Playback::Clock::getPlaybackClock(), SideCar::GUI::MessageWriter::getPort(), SideCar::Time::TimeStamp::getSeconds(), SideCar::GUI::Playback::Clock::getWallClockDurationUntil(), SideCar::IO::Reader::isMessageAvailable(), SideCar::GUI::Playback::Clock::isRunning(), SideCar::Messages::Header::load(), Log(), LOGDEBUG, LOGERROR, LOGINFO, makeWriter(), SideCar::Time::TimeStamp::Min(), SideCar::GUI::MessageWriter::stop(), and SideCar::GUI::MessageWriter::writeMessage().
Referenced by SideCar::GUI::Playback::FileModel::setData().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Playback/Emitter.h
/Users/howes/src/sidecar/GUI/Playback/Emitter.cc