SideCar: SideCar::Messages::RawVideo Class Reference
SideCar::Messages::RawVideo Class Reference
Public Types
using Super = Header
using Ref = boost::shared_ptr< RawVideo >
Public Types inherited from SideCar::Messages::Header
using Ref = boost::shared_ptr< Header >
Public Member Functions
~RawVideo ()
Destructor.
size_t getSize () const
Obtain the C++ structure size for this object.
TPRIMessageRef< Video > convert (const std::string &producer) const
Conversion from RawVideo to Video format.
ACE_InputCDR & load (ACE_InputCDR &cdr)
Read in raw VME data from an CDR input stream.
ACE_OutputCDR & write (ACE_OutputCDR &cdr) const
Write out raw VME data to a CDR output stream.
std::ostream & printData (std::ostream &os) const
Print out a textual representation of the raw VME data.
Public Member Functions inherited from SideCar::Messages::Header
Header (const MetaTypeInfo &metaTypeInfo)
Constructor for messages read in from an external device.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis, MetaTypeInfo::SequenceType sequenceNumber)
Constructor for new messages.
virtual ~Header ()
Destructor.
const MetaTypeInfo & getMetaTypeInfo () const
Obtain the type specification for the message.
const GUID & getGloballyUniqueID () const
Get the globally-unique ID of the message.
MetaTypeInfo::SequenceType getMessageSequenceNumber () const
Get the message sequence number for the message.
void setMessageSequenceNumber (MetaTypeInfo::SequenceType msn)
Set the sequence number for this message.
const Time::TimeStamp & getCreatedTimeStamp () const
Obtain when the message was created.
Time::TimeStamp setCreatedTimeStamp (const Time::TimeStamp &timeStamp)
Revise the creation message timestamp.
const Time::TimeStamp & getEmittedTimeStamp () const
Obtain when the message was written to an external device (file or network).
Time::TimeStamp setEmittedTimeStamp (const Time::TimeStamp &timeStamp)
Set the emitted time stamp with the given value.
HeaderPrinter headerPrinter () const
Convenience method that simply returns a new HeaderPrinter functor for this header object.
DataPrinter dataPrinter () const
Convenience method that simply returns a new DataPrinter functor for this header object.
XMLPrinter xmlPrinter () const
Convenience method that simply returns a new XMLPrinter functor for this header object.
virtual std::ostream & print (std::ostream &os) const
Write out the entire message to a C++ text output stream.
virtual std::ostream & printHeader (std::ostream &os) const
Write out the message header to a C++ text output stream.
virtual std::ostream & printXML (std::ostream &os) const
Write out the message to a C++ text output stream in XML format.
virtual std::ostream & printDataXML (std::ostream &os) const
Write out the message data to a C++ text output stream in XML format.
bool hasBasis () const
Determine if the message has a basis message attached to it.
Ref getBasis () const
Obtain a reference to the message that this one was based on.
template<typename T >
T::Ref getBasis () const
Templated version of the above method.
Static Public Member Functions
static Logger::Log & Log ()
static const MetaTypeInfo & GetMetaTypeInfo ()
Obtain the message type information for RawVideo objects.
static Ref Make (const std::string &producer, ACE_Message_Block *raw)
Class factory that creates new reference-counted RawVideo message objects.
static Ref Make (ACE_InputCDR &cdr)
Class factory that creates new reference-counted RawVideo message objects using data from an input CDR stream.
Static Public Member Functions inherited from SideCar::Messages::Header
static Logger::Log & Log ()
Obtain log device to use for objects of this class.
static const MetaTypeInfo * GetMessageMetaTypeInfo (ACE_InputCDR &cdr)
Additional Inherited Members
Protected Member Functions inherited from SideCar::Messages::Header
virtual void loadXML (XmlStreamReader &xsr)
Obtain new instance data from an XML input stream.
Detailed Description
Definition at line 14 of file RawVideo.h.
Member Function Documentation
Video::Ref RawVideo::convert (const std::string & producer) const
Conversion from RawVideo to Video format.
Performs byte-swapping from VME (PowerPC) system to Intel system.
Parameters
producer name of the entity doing the conversion
Returns
reference to new Video object
Definition at line 103 of file RawVideo.cc.
References LOGDEBUG, LOGERROR, LOGINFO, and SideCar::Messages::Video::Make().
const MetaTypeInfo & RawVideo::GetMetaTypeInfo () static
Obtain the message type information for RawVideo objects.
Returns
MetaTypeInfo reference
Definition at line 21 of file RawVideo.cc.
size_t SideCar::Messages::RawVideo::getSize () const inline virtual
Obtain the C++ structure size for this object.
Derived classes must override if they extend Header with additional members.
Returns
size of a Header object.
Reimplemented from SideCar::Messages::Header.
Definition at line 51 of file RawVideo.h.
ACE_InputCDR & RawVideo::load (ACE_InputCDR & cdr) virtual
Read in raw VME data from an CDR input stream.
Override of Header::load().
Parameters
cdr stream to read from
Returns
stream read from
Reimplemented from SideCar::Messages::Header.
Definition at line 66 of file RawVideo.cc.
References SideCar::Messages::Header::load(), and LOGINFO.
RawVideo::Ref RawVideo::Make (const std::string & producer, ACE_Message_Block * raw) static
Class factory that creates new reference-counted RawVideo message objects.
Parameters
producer name of the entity that is creating the new object
raw data block containing the raw data from a VME system
\return reference to new RawVideo object
Definition at line 27 of file RawVideo.cc.
References LOGINFO.
Referenced by SideCar::IO::VMEReaderTask::openAndInit(), and SideCar::IO::MulticastVMEReaderTask::openAndInit().
RawVideo::Ref RawVideo::Make (ACE_InputCDR & cdr) static
Class factory that creates new reference-counted RawVideo message objects using data from an input CDR stream.
Parameters
cdr input CDR stream to read from
\return reference to new RawVideo object
Definition at line 52 of file RawVideo.cc.
std::ostream & RawVideo::printData (std::ostream & os) const virtual
Print out a textual representation of the raw VME data.
Override of Header::print().
Parameters
os C++ text stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Definition at line 88 of file RawVideo.cc.
ACE_OutputCDR & RawVideo::write (ACE_OutputCDR & cdr) const virtual
Write out raw VME data to a CDR output stream.
Override of Header::write().
Parameters
cdr stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Definition at line 78 of file RawVideo.cc.
References LOGINFO, and SideCar::Messages::Header::write().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Messages/RawVideo.h
/Users/howes/src/sidecar/Messages/RawVideo.cc