SideCar: Utils::RunningMedian Class Reference
Utils::RunningMedian Class Reference
Container class the maintains a running median (and mean) value for a stream of values.
#include </Users/howes/src/sidecar/Utils/RunningMedian.h>
Data Structures
class OrderedIndex
Representation of an address to a specific ordered value in the RunningMedian container.
Public Member Functions
RunningMedian (size_t windowSize, double initialValue=0.0)
Constructor.
~RunningMedian ()
Destructor.
double addValue (double value)
Add a new sample to the container, and obtain an updated median value.
double getMedianValue () const
Obtain the current median value for the samples seen so far.
double getEstimatedMeanValue () const
Obtain an estimated mean (average) value of the samples seen so far.
double getTrueMeanValue ()
Obtain the true mean (average) value of the samples seen so far.
double getMinimumValue () const
Obtain the minimum value of all of the samples held by the container.
double getMaximumValue () const
Obtain the maximum value of all of the samples held by the container.
OrderedIndex generateOrderedIndex (size_t index) const
Obtain an OrderedIndex object that corresponds to a given offset in the sample window.
double getOrderedValue (const OrderedIndex &index) const
Obtain the value for the sample in the ordered window at the given location.
double getOrderedValue (size_t index) const
Convenience method for fetching ordered sample values without dealing with OrderedIndex objects.
void clear (double initialValue=0.0)
Reset the container so that all samples have a given initial value.
void setWindowSize (size_t windowSize, double initialValue=0.0)
Reset the container so that it has a new sample window size.
void dump () const
Write out a textual representation of the internal container to the RunningMedian log device.
Static Public Member Functions
static Logger::Log & Log ()
Obtain Logger::Log device to use for instances of this class.
Detailed Description
Container class the maintains a running median (and mean) value for a stream of values.
Instances have a fixed window size that determines how many samples to track for median calculations; after receiving this number of samples, the algorithm starts to forget the oldest sample.
The basics of the algorithm were taken from the paper "Efficient Algorithm for computing a Running Median" by Soumya D. Mohanty for the CalTech/MIT LIGO project. The key insight from the paper is the management of an array of equidistant 'checks' or 'fingers' that point to nodes of an ordered link-list. These nodes offer improved search speed over walking the linked list, with the increased complexity necessary to manage them as the elements in the linked-list move around.
Although the algorithm described is sound, the C implementation in the paper has some bugs that affected performance. In my implementation, I use the term 'fingers' to refer to the entity the paper calls a 'check'.
TODO: since the fingers are always ordered, an even faster implementation would be to use binary search on them to find the one to use to locate a given ordered link-list node.
Definition at line 27 of file RunningMedian.h.
Constructor & Destructor Documentation
RunningMedian::RunningMedian (size_t windowSize, double initialValue = 0.0)
Constructor.
Creates a new container for windowSize samples, initialized to initialValue values.
Parameters
windowSize number of samples to remember
initialValue initial value to give to window samples
Definition at line 19 of file RunningMedian.cc.
References setWindowSize().
Member Function Documentation
double RunningMedian::addValue (double value)
Add a new sample to the container, and obtain an updated median value.
Parameters
value sample value to add
Returns
updated median value
Definition at line 155 of file RunningMedian.cc.
References dump(), Log(), LOGDEBUG, LOGDEBUG3, LOGINFO, and Logger::ProcLog::showsDebug3().
Referenced by SideCar::Algorithms::ProcessingStat::beginProcessing().
void RunningMedian::clear (double initialValue = 0.0)
Reset the container so that all samples have a given initial value.
Parameters
initialValue the initial value to use
Definition at line 370 of file RunningMedian.cc.
Referenced by SideCar::Algorithms::ProcessingStat::reset(), and setWindowSize().
void RunningMedian::dump () const
Write out a textual representation of the internal container to the RunningMedian log device.
Only useful for debugging purposes.
Definition at line 324 of file RunningMedian.cc.
References Log(), LOGDEBUG, and LOGINFO.
Referenced by addValue().
RunningMedian::OrderedIndex RunningMedian::generateOrderedIndex (size_t index) const
Obtain an OrderedIndex object that corresponds to a given offset in the sample window.
For instance, an index value of zero (0) would return an OrderedIndex object that refers to the smallest element in the container, and a value of windowSize_ - 1 would return an OrderedIndex for the largest value.
Parameters
index ordered sample in the running window to refer to. Value must be < windowSize_.
Returns
OrderedIndex object
Definition at line 463 of file RunningMedian.cc.
References Log(), LOGDEBUG, and LOGINFO.
double Utils::RunningMedian::getEstimatedMeanValue () const inline
Obtain an estimated mean (average) value of the samples seen so far.
For speed, the RunningMedian class maintains a running sum of the sample values, and this method simply divides the running sum by the window size to obtain a mean value. However, note that after some amount of time, this calculation will most likely deviate from the true mean value due to rounding errors, especially when the magnitude between the largest and smallest values is very large. One can always obtain a true mean value via getTrueMeanValue() method, at some cost in performance.
Returns
current (estimated) mean value
Definition at line 82 of file RunningMedian.h.
Referenced by SideCar::Algorithms::ProcessingStat::getAverageProcessingTime(), and getTrueMeanValue().
double Utils::RunningMedian::getMaximumValue () const inline
Obtain the maximum value of all of the samples held by the container.
Returns
running maximum value
Definition at line 101 of file RunningMedian.h.
Referenced by SideCar::Algorithms::ProcessingStat::getAverageProcessingTime().
double Utils::RunningMedian::getMedianValue () const inline
Obtain the current median value for the samples seen so far.
Returns
current median value
Definition at line 71 of file RunningMedian.h.
Referenced by SideCar::Algorithms::ProcessingStat::getAverageProcessingTime().
double Utils::RunningMedian::getMinimumValue () const inline
Obtain the minimum value of all of the samples held by the container.
Returns
running minimum value
Definition at line 95 of file RunningMedian.h.
Referenced by SideCar::Algorithms::ProcessingStat::getAverageProcessingTime().
double RunningMedian::getOrderedValue (const OrderedIndex & index) const
Obtain the value for the sample in the ordered window at the given location.
Parameters
index location to fetch
Returns
current value at the given location
Definition at line 480 of file RunningMedian.cc.
References Log(), LOGDEBUG, and LOGINFO.
double Utils::RunningMedian::getOrderedValue (size_t index) const inline
Convenience method for fetching ordered sample values without dealing with OrderedIndex objects.
Parameters
index offset from the start of the running window to fetch
Returns
current value at the given location
Definition at line 127 of file RunningMedian.h.
References getOrderedValue().
Referenced by getOrderedValue().
double RunningMedian::getTrueMeanValue ()
Obtain the true mean (average) value of the samples seen so far.
Unlike, getMeanValue(), this method calculates the sum of the samples from scratch.
Returns
true mean value
Definition at line 454 of file RunningMedian.cc.
References getEstimatedMeanValue().
Logger::Log & RunningMedian::Log () static
Obtain Logger::Log device to use for instances of this class.
Returns
Logger::Log reference
Definition at line 13 of file RunningMedian.cc.
References Logger::Log::Find().
Referenced by addValue(), dump(), generateOrderedIndex(), getOrderedValue(), and setWindowSize().
void RunningMedian::setWindowSize (size_t windowSize, double initialValue = 0.0)
Reset the container so that it has a new sample window size.
If the given window size is the same as the current one, the effect will be the same as calling clear(initialValue).
Parameters
windowSize new size to use
initialValue the initial value to use for samples
Definition at line 31 of file RunningMedian.cc.
References clear(), Log(), LOGDEBUG, and LOGINFO.
Referenced by RunningMedian().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Utils/RunningMedian.h
/Users/howes/src/sidecar/Utils/RunningMedian.cc