SideCar: SideCar::IO::Writer Class Reference
SideCar::IO::Writer Class Reference abstract
Abstract base class for data writers.
#include </Users/howes/src/sidecar/IO/Writers.h>
Public Types
using Ref = boost::shared_ptr< Writer >
Public Member Functions
Writer ()
Constructor.
virtual ~Writer ()
Destructor.
void setClosingSignal ()
Set a flag to tell the writer that the device is being closed.
void resetClosingSignal ()
Reset the flag that tells the writer that the device is being closed.
bool isClosing () const
Determine if the writer has been commanded to shut down.
bool writeEncoded (size_t messageCount, ACE_Message_Block *data)
Write out an already-encoded data block.
bool write (const MessageManager &mm)
Write out the message managed by a MessageManager object.
int getLastError () const
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device to use for log messages.
Protected Member Functions
virtual ssize_t writeToDevice (const iovec *iov, int count)=0
Prototype of method that writes data to a device.
Detailed Description
Abstract base class for data writers.
A writer simply submits a block of data to a device object, such as a file or socket. The writer itself has no idea how data is transported; it only knows how to get the data to the device.
Definition at line 237 of file Writers.h.
Member Function Documentation
bool SideCar::IO::Writer::isClosing () const inline
Determine if the writer has been commanded to shut down.
Returns
true if so
Definition at line 269 of file Writers.h.
Logger::Log & Writer::Log () static
Obtain the log device to use for log messages.
Returns
Definition at line 93 of file Writers.cc.
References Logger::Log::Find().
void SideCar::IO::Writer::setClosingSignal () inline
Set a flag to tell the writer that the device is being closed.
This will break the writer out of the while loop in writeEncoded if it is encountering EAGAIN errors while writing data.
Definition at line 259 of file Writers.h.
bool Writer::write (const MessageManager & mm)
Write out the message managed by a MessageManager object.
Invokes MessageManager::getEncoded() to obtain the underlying ACE_Message_Block data block.
Parameters
mm container with the data to write
Returns
true if successful, false otherwise
Definition at line 100 of file Writers.cc.
References SideCar::IO::MessageManager::getEncoded().
Referenced by SideCar::IO::MulticastDataPublisher::deliverDataMessage(), SideCar::IO::UDPSocketWriterTask::openAndInit(), and SideCar::GUI::TCPMessageWriter::writeMessage().
bool Writer::writeEncoded (size_t messageCount, ACE_Message_Block * data)
Write out an already-encoded data block.
Parameters
data block to write
Returns
true if successful, false otherwise
Definition at line 106 of file Writers.cc.
References LOGDEBUG, LOGERROR, LOGTIN, LOGTOUT, SideCar::IO::IOVVector::push_back(), and SideCar::IO::WriterDevices::UDPSocket::writeToDevice().
Referenced by SideCar::IO::GatherWriter::flush(), and SideCar::GUI::TCPMessageWriter::writeMessage().
virtual ssize_t SideCar::IO::Writer::writeToDevice (const iovec * iov, int count) protected pure virtual
Prototype of method that writes data to a device.
The data to write exists as an array of pointer/length pairs.
Parameters
iov pointer to first iov to send
count number of iov entries to send
Returns
number of bytes sent if >= 0; error condition if < 0
Implemented in SideCar::IO::TWriter< _D >, SideCar::IO::TWriter< WriterDevices::MulticastSocket >, SideCar::IO::TWriter< WriterDevices::File >, SideCar::IO::TWriter< SocketWriterDevice >, SideCar::IO::TWriter< WriterDevices::TCPSocket >, and SideCar::IO::TWriter< WriterDevices::UDPSocket >.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/Writers.h
/Users/howes/src/sidecar/IO/Writers.cc