SideCar: SideCar::Time::TimeStamp Class Reference
SideCar::Time::TimeStamp Class Reference
Representation of a SideCar time value.
#include </Users/howes/src/sidecar/Time/TimeStamp.h>
Data Structures
struct IllegalTimeStamp
struct InvalidSpecification
Public Member Functions
TimeStamp ()
Default constructor.
TimeStamp (double value)
Conversion constructor for double values.
TimeStamp (time_t seconds, suseconds_t micro)
Constructor for integer seconds and microseconds.
TimeStamp (const ::timeval &value)
Conversion constructor for POSIX timeval members.
time_t getSeconds () const
Obtain the number of seconds in the time stamp.
time_t getSecondsRounded () const
Obtain the number of seconds in the time stamp, rounded by the value in the microseconds.
suseconds_t getMicro () const
Obtain the number of microseconds since T0 we represent.
double asDouble () const
Obtain internal value as a C++ double.
operator const ACE_Time_Value & () const
Allow object to appear where ACE_Time_Value objects may appear.
operator timeval () const
std::string hhmmss (int showMicroPlaces=0) const
bool operator== (const TimeStamp &rhs) const
bool operator< (const TimeStamp &rhs) const
operator bool () const
Determine if the held time is not the smallest time value.
bool operator! () const
Determine if the held time is the smallest time value.
std::ostream & print (std::ostream &os) const
Write out a textual representation of our time stamp.
TimeStamp & operator+= (const TimeStamp &rhs)
Add the seconds of another time value to this one.
TimeStamp & operator-= (const TimeStamp &rhs)
Subtract the seconds of another time value from this one.
TimeStamp & operator*= (double scale)
Multiply held time value by a scaling factor.
TimeStamp & operator/= (double scale)
Divide the held time value by a scaling factor.
ACE_InputCDR & load (ACE_InputCDR &cdr)
Acquire a new value from a input CDR stream.
ACE_OutputCDR & write (ACE_OutputCDR &cdr) const
Write out our value to an output CDR stream.
Static Public Member Functions
static const TimeStamp & Min ()
Obtain representation of minimum value that TimeStamp can represent.
static const TimeStamp & Max ()
Obtain representation of maximum value that TimeStamp can represent.
static TimeStamp Now ()
Obtain a TimeStamp the contains the current time from the system clock.
static TimeStamp ParseSpecification (const std::string &spec, const TimeStamp &zero)
Parse a time specification and return the TimeStamp value it represents.
static Logger::Log & Log ()
Get the log device for TimeStamp log messages.
Static Public Attributes
static double const kSecondsPerMicro = 1.E-6
static suseconds_t const kMicrosPerSecond = ACE_ONE_SECOND_IN_USECS
Protected Member Functions
TimeStamp (const ACE_Time_Value &when)
Detailed Description
Representation of a SideCar time value.
Internally, uses ACE_Time_Value to store a time value.
Definition at line 18 of file TimeStamp.h.
Constructor & Destructor Documentation
SideCar::Time::TimeStamp::TimeStamp () inline
Default constructor.
Initializes value to TimeStamp::Min().
Definition at line 76 of file TimeStamp.h.
Referenced by Now(), and ParseSpecification().
TimeStamp::TimeStamp (double value)
Conversion constructor for double values.
Parameters
value initial value to use
Definition at line 112 of file TimeStamp.cc.
References Log(), LOGDEBUG, and Logger::ProcLog::thrower().
SideCar::Time::TimeStamp::TimeStamp (time_t seconds, suseconds_t micro) inline
Constructor for integer seconds and microseconds.
Parameters
seconds number of seconds since T0
micro number of microseconds since T0
Definition at line 90 of file TimeStamp.h.
SideCar::Time::TimeStamp::TimeStamp (const ::timeval & value) inline
Conversion constructor for POSIX timeval members.
Parameters
value initial value
Definition at line 96 of file TimeStamp.h.
Member Function Documentation
double SideCar::Time::TimeStamp::asDouble () const inline
Obtain internal value as a C++ double.
Returns
double representation
Definition at line 120 of file TimeStamp.h.
Referenced by SideCar::Algorithms::ProcessingStat::beginProcessing(), SideCar::IO::Stats::calculateRates(), PRIInfoInputTask::deliverDataMessage(), getSecondsRounded(), SideCar::GUI::Playback::MainWindow::MainWindow(), SideCar::GUI::PRIEmitter::MainWindow::openFile(), SideCar::Algorithms::ComposeExtractions::processAlarm(), SideCar::Algorithms::TrackInitiator::reset(), SideCar::Algorithms::ABTracker::shutdown(), and SideCar::Algorithms::TrackMaintainer::shutdown().
suseconds_t SideCar::Time::TimeStamp::getMicro () const inline
Obtain the number of microseconds since T0 we represent.
Returns
microseconds
Definition at line 114 of file TimeStamp.h.
Referenced by SideCar::GUI::Playback::Emitter::setEmitting().
time_t SideCar::Time::TimeStamp::getSeconds () const inline
Obtain the number of seconds in the time stamp.
Returns
seconds
Definition at line 102 of file TimeStamp.h.
Referenced by SideCar::GUI::Playback::MainWindow::MainWindow(), and SideCar::GUI::Playback::Emitter::setEmitting().
time_t TimeStamp::getSecondsRounded () const
Obtain the number of seconds in the time stamp, rounded by the value in the microseconds.
Returns
seconds
Definition at line 174 of file TimeStamp.cc.
References asDouble().
ACE_InputCDR & TimeStamp::load (ACE_InputCDR & cdr)
Acquire a new value from a input CDR stream.
Parameters
cdr stream to read from
Returns
stream read from
Definition at line 127 of file TimeStamp.cc.
Logger::Log & TimeStamp::Log () static
Get the log device for TimeStamp log messages.
Returns
Log reference
Definition at line 106 of file TimeStamp.cc.
References Logger::Log::Find().
Referenced by ParseSpecification(), and TimeStamp().
const TimeStamp & TimeStamp::Max () static
Obtain representation of maximum value that TimeStamp can represent.
Returns
reference to maximum value
Definition at line 27 of file TimeStamp.cc.
Referenced by SideCar::GUI::Playback::FileModel::beginLoad(), InputTask::deliverDataMessage(), PRIInfoInputTask::deliverDataMessage(), SideCar::Algorithms::ProcessingStat::endProcessing(), SideCar::Time::TimeStampRange::Make(), and SideCar::Algorithms::ProcessingStat::reset().
const TimeStamp & TimeStamp::Min () static
Obtain representation of minimum value that TimeStamp can represent.
This is just 0 seconds.
Returns
reference to minimum value
Definition at line 20 of file TimeStamp.cc.
Referenced by SideCar::GUI::Playback::FileModel::beginLoad(), SideCar::IO::Stats::calculateRates(), InputTask::deliverDataMessage(), PRIInfoInputTask::deliverDataMessage(), SideCar::Messages::Extraction::Extraction(), SideCar::Messages::Header::loadXML(), SideCar::GUI::Playback::MainWindow::MainWindow(), SideCar::Time::TimeStampRange::Make(), SideCar::IO::Stats::resetAll(), SideCar::GUI::Playback::Emitter::setEmitting(), and SideCar::Messages::Header::write().
TimeStamp TimeStamp::Now () static
Obtain a TimeStamp the contains the current time from the system clock.
Returns
TimeStamp with current time
Definition at line 34 of file TimeStamp.cc.
References TimeStamp().
Referenced by SideCar::Algorithms::ProcessingStat::beginProcessing(), SideCar::IO::Stats::calculateRates(), SideCar::IO::MulticastDataPublisher::close(), SideCar::Algorithms::ProcessingStat::endProcessing(), SideCar::GUI::Playback::Clock::getPlaybackClock(), SideCar::IO::MulticastDataPublisher::handle_timeout(), SideCar::GUI::PRIEmitter::MainWindow::openFile(), SideCar::Algorithms::ComposeExtractions::processAlarm(), SideCar::GUI::Playback::Clock::setWallClockRate(), SideCar::Algorithms::CPIAlgorithm::shutdown(), SideCar::Algorithms::TrackMaintainer::shutdown(), SideCar::GUI::Playback::Clock::start(), SideCar::Algorithms::Segment2Extraction::startup(), and SideCar::Messages::Header::write().
SideCar::Time::TimeStamp::operator bool () const inline
Determine if the held time is not the smallest time value.
Returns
true if so.
Definition at line 141 of file TimeStamp.h.
SideCar::Time::TimeStamp::operator const ACE_Time_Value & () const inline
Allow object to appear where ACE_Time_Value objects may appear.
Returns
ACE_Time_Value value.
Definition at line 127 of file TimeStamp.h.
bool SideCar::Time::TimeStamp::operator! () const inline
Determine if the held time is the smallest time value.
Returns
true if so.
Definition at line 147 of file TimeStamp.h.
TimeStamp& SideCar::Time::TimeStamp::operator*= (double scale) inline
Multiply held time value by a scaling factor.
Parameters
scale value to multiply with
Returns
reference to self
Definition at line 179 of file TimeStamp.h.
TimeStamp& SideCar::Time::TimeStamp::operator+= (const TimeStamp & rhs) inline
Add the seconds of another time value to this one.
Parameters
rhs value to add
Returns
reference to self
Definition at line 163 of file TimeStamp.h.
TimeStamp& SideCar::Time::TimeStamp::operator-= (const TimeStamp & rhs) inline
Subtract the seconds of another time value from this one.
Parameters
rhs value to subtract
Returns
reference to self
Definition at line 171 of file TimeStamp.h.
TimeStamp& SideCar::Time::TimeStamp::operator/= (double scale) inline
Divide the held time value by a scaling factor.
Parameters
scale value to divide with
Returns
reference to self
Definition at line 187 of file TimeStamp.h.
TimeStamp TimeStamp::ParseSpecification (const std::string & spec, const TimeStamp & zero) static
Parse a time specification and return the TimeStamp value it represents.
Empty and invalid specifications throw InvalidSpecification errors. Supports relative and absolute specifications. Absolute times contains seconds and microseconds integer values, separated by a colon (':') character. Relative times start with a plus ('+') character followed by the number of seconds in the offset. This may be specified as a floating-point number, or as minutes ':' seconds. The resulting offset value is then added to the given 'zero' value and and returned.
Parameters
spec the time specification to parse
zero the reference to use for relative times
Returns
new TimeStamp value
Definition at line 42 of file TimeStamp.cc.
References Log(), LOGDEBUG, LOGINFO, and TimeStamp().
Referenced by InputTask::deliverDataMessage(), SideCar::Messages::Extraction::Extraction(), and SideCar::Messages::Header::loadXML().
std::ostream& SideCar::Time::TimeStamp::print (std::ostream & os) const inline
Write out a textual representation of our time stamp.
Parameters
os stream to write to
Returns
stream written to
Definition at line 155 of file TimeStamp.h.
ACE_OutputCDR & TimeStamp::write (ACE_OutputCDR & cdr) const
Write out our value to an output CDR stream.
Parameters
cdr stream to write to
Returns
stream written to
Definition at line 137 of file TimeStamp.cc.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Time/TimeStamp.h
/Users/howes/src/sidecar/Time/TimeStamp.cc