SideCar: Logger::Writers::RollingFile Class Reference
Logger::Writers::RollingFile Class Reference
Public Types
using Ref = boost::shared_ptr< RollingFile >
Public Types inherited from Logger::Writers::File
using Ref = boost::shared_ptr< File >
Public Types inherited from Logger::Writers::Writer
using Ref = boost::shared_ptr< Writer >
Public Member Functions
void open () override
Open connection to storage device.
void write (const Msg &msg) override
Write out a Msg instance to the storage device.
Public Member Functions inherited from Logger::Writers::File
void close () override
Close connection to storage device.
void flush () override
Flush any pending messages to the storage device.
const std::string & path () const
Public Member Functions inherited from Logger::Writers::Writer
virtual ~Writer ()
Destructor.
virtual void reopen ()
Close and then reopen connection to storage device.
bool operator< (const Writer &rhs) const
void setFlushAfterUse (bool enabled)
bool getFlushAfterUse () const
Static Public Member Functions
static Ref Make (const Formatters::Formatter::Ref &formatter, const std::string &path, ssize_t maxSize, int numVersions, bool append=true, mode_t mode=00644, bool flushAfterUse=false)
Static Public Member Functions inherited from Logger::Writers::File
static Ref Make (const Formatters::Formatter::Ref &formatter, const std::string &path, bool append=true, mode_t mode=00644, bool flushAfterUse=false)
Additional Inherited Members
Protected Member Functions inherited from Logger::Writers::File
File (const Formatters::Formatter::Ref &formatter, const std::string &path, bool append, mode_t mode, bool flushAfterUse)
size_t wrote () const
int fd () const
Protected Member Functions inherited from Logger::Writers::Writer
Writer (Formatters::Formatter::Ref formatter, bool flushAfterUse)
Constructor.
void format (std::ostream &os, const Msg &msg)
Detailed Description
Definition at line 127 of file Writers.h.
Member Function Documentation
void RollingFile::open () override virtual
Open connection to storage device.
Subclass must define.
Reimplemented from Logger::Writers::File.
Definition at line 10 of file RollingWriter.cc.
References Logger::Writers::File::open().
Referenced by write().
void RollingFile::write (const Msg & msg) override virtual
Write out a Msg instance to the storage device.
Parameters
msg Msg instance to format and write out
Reimplemented from Logger::Writers::File.
Definition at line 17 of file RollingWriter.cc.
References Logger::Writers::File::close(), open(), and Logger::Writers::File::write().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Logger/Writers.h
/Users/howes/src/sidecar/Logger/RollingWriter.cc