SideCar: SideCar::GUI::AScope::HistoryFrame Class Reference
SideCar::GUI::AScope::HistoryFrame Class Reference
Collection of Messages::PRIMessage objects that represent a viewable entity in the AScope.
#include </Users/howes/src/sidecar/GUI/AScope/HistoryFrame.h>
Public Member Functions
void clear ()
Erase the references to all held messages.
void expand ()
Add an empty reference to the end of the frame.
void shrink ()
Remove the last message slot from the frame, making it smaller.
void append (const Messages::PRIMessage::Ref &msg)
Append a message to the end of the frame.
void update (int index, const Messages::PRIMessage::Ref &msg)
Overwrite an existing entry with a new message reference.
void clearMessage (int index)
Overwrite and existing entry with a null message reference.
bool hasMessage (int index) const
Determine if there is a valid message at a given index.
Messages::PRIMessage::Ref getMessage (int index) const
Obtain a message at a given index.
Messages::PRIMessage::Ref getSomeMessage () const
Fetch the first non-NULL message in the collection.
bool empty () const
Determine if the frame has no messages.
double getTimeStamp () const
Obtain the timestamp of the last message added to the collection.
Static Public Member Functions
static Logger::Log & Log ()
Log device used by HistoryFrame objects.
Detailed Description
Collection of Messages::PRIMessage objects that represent a viewable entity in the AScope.
The order of the messages in an entry are based on the assignments done by a HistorySlotManager object.
Definition at line 18 of file HistoryFrame.h.
Member Function Documentation
void HistoryFrame::append (const Messages::PRIMessage::Ref & msg)
Append a message to the end of the frame.
Parameters
msg the message to add.
Definition at line 30 of file HistoryFrame.cc.
Referenced by SideCar::GUI::AScope::History::getPastFrame().
void HistoryFrame::clearMessage (int index)
Overwrite and existing entry with a null message reference.
The given index value must be valid, or else QList will throw an exception.
Parameters
index position to clear
Definition at line 50 of file HistoryFrame.cc.
bool SideCar::GUI::AScope::HistoryFrame::empty () const inline
Determine if the frame has no messages.
Returns
true if so
Definition at line 93 of file HistoryFrame.h.
Messages::PRIMessage::Ref SideCar::GUI::AScope::HistoryFrame::getMessage (int index) const inline
Obtain a message at a given index.
NOTE: the QList::value() method will always return a value, event if index is invalid, in which case the returned message reference may refer to no message.
Parameters
index which message to fetch
Returns
message reference
Definition at line 79 of file HistoryFrame.h.
Referenced by SideCar::GUI::AScope::History::getLiveMessage(), SideCar::GUI::AScope::History::getPastMessage(), and SideCar::GUI::AScope::HistoryPosition::setPosition().
Messages::PRIMessage::Ref SideCar::GUI::AScope::HistoryFrame::getSomeMessage () const inline
Fetch the first non-NULL message in the collection.
This is usually the first entry in the list, but that is not guaranteed.
Returns
Definition at line 86 of file HistoryFrame.h.
Referenced by SideCar::GUI::AScope::HistoryPosition::HistoryPosition(), and SideCar::GUI::AScope::HistoryPosition::setPosition().
double SideCar::GUI::AScope::HistoryFrame::getTimeStamp () const inline
Obtain the timestamp of the last message added to the collection.
Returns
Definition at line 99 of file HistoryFrame.h.
bool SideCar::GUI::AScope::HistoryFrame::hasMessage (int index) const inline
Determine if there is a valid message at a given index.
Safe to call with invalid index values.
Parameters
index value to check
Returns
true if so
Definition at line 70 of file HistoryFrame.h.
static Logger::Log& SideCar::GUI::AScope::HistoryFrame::Log () static
Log device used by HistoryFrame objects.
Returns
log device
void HistoryFrame::update (int index, const Messages::PRIMessage::Ref & msg)
Overwrite an existing entry with a new message reference.
NOTE: unlike getMessage(), the index value given to this method must be valid, or else QList will throw an exception.
Parameters
index position to update
message new value to hold (may be null)
Definition at line 40 of file HistoryFrame.cc.
Referenced by SideCar::GUI::AScope::History::update().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/AScope/HistoryFrame.h
/Users/howes/src/sidecar/GUI/AScope/HistoryFrame.cc