SideCar: SideCar::Parameter::ValueBase Class Reference
SideCar::Parameter::ValueBase Class Reference abstract
Abstract base class for named parameter values.
#include </Users/howes/src/sidecar/Parameter/Parameter.h>
Public Member Functions
ValueBase (const std::string &name, const std::string &label)
Constructor.
virtual ~ValueBase ()=default
Destructor.
const std::string & getName () const
Obtain the XML name of the parameter.
const std::string & getLabel () const
Obtain the GUI label of the parameter.
bool isAdvanced () const
Determine if the parameter is 'advanced', and not shown to the user by default.
void setAdvanced (bool state)
Change the parameter's advanced designation.
bool isEditable () const
Determine if the parameter is editable by the user.
void setEditable (bool state)
Change the parameter's editable designation.
virtual bool checkedLoad (ACE_InputCDR &cdr)=0
Acquire a new parameter value from an ACE CDR input stream.
virtual std::istream & load (std::istream &os)=0
Fetch the parameter value from a C++ input stream.
virtual std::ostream & save (std::ostream &os) const =0
Write the parameter value to a C++ output stream.
virtual ACE_InputCDR & load (ACE_InputCDR &cdr)=0
Load a new parameter value using data from a CDR input stream.
virtual ACE_OutputCDR & write (ACE_OutputCDR &cdr) const =0
Write the parameter value to a CDR input stream.
virtual void setXMLValue (XmlRpc::XmlRpcValue &xml)=0
Set the value using a value contained in an XML-RPC request.
virtual void setXMLOriginal (XmlRpc::XmlRpcValue &xml)=0
Set the original value using a value contained in an XML-RPC request.
virtual void describe (XmlRpc::XmlRpcValue &xml) const =0
Describe the parameter name attributes using an XML-RPC struct.
virtual bool isNotOriginal () const =0
Determine if the parameter value is different than the value used to initialize the parameter.
Detailed Description
Abstract base class for named parameter values.
Defines the interface all derived classes must provide. Parameter values may change at any time due to external messages or signals.
An object interested in knowning when the internal value of a Value instance changes may register for value-change notifications by calling connectChangedSignalTo().
Currently, there are two kinds of parameters, normal and advanced. They operate the same in all ways except when viewed from within the Master application. There, advanced parameters are normally hidden from view, and are only revealed when the 'Advanced' checkbox is checked.
Definition at line 46 of file Parameter.h.
Constructor & Destructor Documentation
SideCar::Parameter::ValueBase::ValueBase (const std::string & name, const std::string & label) inline
Constructor.
Sets the XML name and GUI label for the parameter.
Parameters
name XML name of the parameter
label GUI text label of the parameter
Definition at line 55 of file Parameter.h.
virtual SideCar::Parameter::ValueBase::~ValueBase () virtual default
Destructor.
Here to silence warnings about missing virtual destructors, though it is not needed.
Member Function Documentation
virtual bool SideCar::Parameter::ValueBase::checkedLoad (ACE_InputCDR & cdr) pure virtual
Acquire a new parameter value from an ACE CDR input stream.
Derived classes must define.
Parameters
cdr stream to read from
Returns
true if acquired value was valid and the parameter was set to it
Implemented in SideCar::Parameter::TValue< ParamDef >.
virtual void SideCar::Parameter::ValueBase::describe (XmlRpc::XmlRpcValue & xml) const pure virtual
Describe the parameter name attributes using an XML-RPC struct.
Derived classes must define.
Parameters
xml XML-RPC container to hold the attribute values.
Implemented in SideCar::Parameter::TValue< ParamDef >.
const std::string& SideCar::Parameter::ValueBase::getLabel () const inline
Obtain the GUI label of the parameter.
This is shown to the user when editing parameter values.
Returns
the GUI label
Definition at line 72 of file Parameter.h.
const std::string& SideCar::Parameter::ValueBase::getName () const inline
Obtain the XML name of the parameter.
Returns
the XML name
Definition at line 66 of file Parameter.h.
bool SideCar::Parameter::ValueBase::isAdvanced () const inline
Determine if the parameter is 'advanced', and not shown to the user by default.
Default value is false.
Returns
true if so
Definition at line 78 of file Parameter.h.
bool SideCar::Parameter::ValueBase::isEditable () const inline
Determine if the parameter is editable by the user.
Default value is true.
Returns
true if so
Definition at line 90 of file Parameter.h.
virtual bool SideCar::Parameter::ValueBase::isNotOriginal () const pure virtual
Determine if the parameter value is different than the value used to initialize the parameter.
Derived classes must define.
Returns
true if different
Implemented in SideCar::Parameter::TValue< ParamDef >.
Referenced by SideCar::IO::Task::hasChangedParameters().
virtual std::istream& SideCar::Parameter::ValueBase::load (std::istream & os) pure virtual
Fetch the parameter value from a C++ input stream.
Derived class must define.
Parameters
os stream to read
Returns
stream read
Implemented in SideCar::Parameter::TValue< ParamDef >.
Referenced by SideCar::Parameter::operator>>().
virtual ACE_InputCDR& SideCar::Parameter::ValueBase::load (ACE_InputCDR & cdr) pure virtual
Load a new parameter value using data from a CDR input stream.
Derived classes must define.
Parameters
cdr stream to read from
Returns
stream read from
Implemented in SideCar::Parameter::TValue< ParamDef >.
virtual std::ostream& SideCar::Parameter::ValueBase::save (std::ostream & os) const pure virtual
Write the parameter value to a C++ output stream.
Derived classes must define.
Parameters
os stream to write to
Returns
stream written to
Implemented in SideCar::Parameter::TValue< ParamDef >.
Referenced by SideCar::Parameter::operator<<().
void SideCar::Parameter::ValueBase::setAdvanced (bool state) inline
Change the parameter's advanced designation.
Parameters
state true if advanced
Definition at line 84 of file Parameter.h.
void SideCar::Parameter::ValueBase::setEditable (bool state) inline
Change the parameter's editable designation.
Parameters
state true if editable
Definition at line 96 of file Parameter.h.
virtual void SideCar::Parameter::ValueBase::setXMLOriginal (XmlRpc::XmlRpcValue & xml) pure virtual
Set the original value using a value contained in an XML-RPC request.
Derived classes must define.
Parameters
xml the XML-RPC value to use
Implemented in SideCar::Parameter::TValue< ParamDef >.
virtual void SideCar::Parameter::ValueBase::setXMLValue (XmlRpc::XmlRpcValue & xml) pure virtual
Set the value using a value contained in an XML-RPC request.
Derived classes must define.
Parameters
xml the XML-RPC value to use
Implemented in SideCar::Parameter::TValue< ParamDef >.
virtual ACE_OutputCDR& SideCar::Parameter::ValueBase::write (ACE_OutputCDR & cdr) const pure virtual
Write the parameter value to a CDR input stream.
Derived classes must define.
Parameters
cdr stream to write to
Returns
stream written to
Implemented in SideCar::Parameter::TValue< ParamDef >.
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/Parameter/Parameter.h