SideCar: SideCar::GUI::PlotSymbolWidget Class Reference
SideCar::GUI::PlotSymbolWidget Class Reference
Derivation of a QComboBox that works with a TargetPlotImaging instance to show the available target plot symbols and the current symbol setting in use by the TargetPlotImaging instance.
#include </Users/howes/src/sidecar/GUI/PlotSymbolWidget.h>
Public Slots
void colorChanged ()
Notification from the associated TargetPlotImaging that its plot color has changed.
Public Member Functions
PlotSymbolWidget (QWidget *parent=0)
Constructor.
void associateWith (TargetPlotImaging *settings)
Associate with a given TargetPlotImaging instance.
Detailed Description
Derivation of a QComboBox that works with a TargetPlotImaging instance to show the available target plot symbols and the current symbol setting in use by the TargetPlotImaging instance.
Definition at line 14 of file PlotSymbolWidget.h.
Constructor & Destructor Documentation
SideCar::GUI::PlotSymbolWidget::PlotSymbolWidget (QWidget * parent = 0) inline
Constructor.
Creates new widget that is not associated with any TargetPlotImaging instance.
Parameters
parent owner for auto-destruction
Definition at line 24 of file PlotSymbolWidget.h.
References associateWith(), and colorChanged().
Member Function Documentation
void PlotSymbolWidget::associateWith (TargetPlotImaging * settings)
Associate with a given TargetPlotImaging instance.
When the plot color of the TargetPlotImaging instance changes we recreate our symbol icons to use the new color.
Parameters
settings TargetPlotImaging instance to associate with
Definition at line 7 of file PlotSymbolWidget.cc.
References colorChanged().
Referenced by PlotSymbolWidget().
void PlotSymbolWidget::colorChanged () slot
Notification from the associated TargetPlotImaging that its plot color has changed.
We obtain a new set of symbol icons drawn in the new color.
Definition at line 15 of file PlotSymbolWidget.cc.
Referenced by associateWith(), and PlotSymbolWidget().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/PlotSymbolWidget.h
/Users/howes/src/sidecar/GUI/PlotSymbolWidget.cc