SideCar: SideCar::Messages::BugPlot Class Reference
SideCar::Messages::BugPlot Class Reference
Public Types
using Ref = boost::shared_ptr< BugPlot >
Public Types inherited from SideCar::Messages::Header
using Ref = boost::shared_ptr< Header >
Public Member Functions
~BugPlot ()
Destructor.
ACE_InputCDR & load (ACE_InputCDR &cdr)
Read in a BugPlot message from an CDR input stream.
ACE_OutputCDR & write (ACE_OutputCDR &cdr) const
Write out a BugPlot message to a CDR output stream.
std::ostream & printData (std::ostream &os) const
Print out a textual representation of the BugPlot message.
std::ostream & printDataXML (std::ostream &os) const
Print out a XML representation of the BugPlot message.
double getWhen () const
double getRange () const
double getAzimuth () const
double getElevation () const
const std::string & getTag () const
size_t getSize () const
Obtain the C++ structure size for this object.
Public Member Functions inherited from SideCar::Messages::Header
Header (const MetaTypeInfo &metaTypeInfo)
Constructor for messages read in from an external device.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis, MetaTypeInfo::SequenceType sequenceNumber)
Constructor for new messages.
virtual ~Header ()
Destructor.
const MetaTypeInfo & getMetaTypeInfo () const
Obtain the type specification for the message.
const GUID & getGloballyUniqueID () const
Get the globally-unique ID of the message.
MetaTypeInfo::SequenceType getMessageSequenceNumber () const
Get the message sequence number for the message.
void setMessageSequenceNumber (MetaTypeInfo::SequenceType msn)
Set the sequence number for this message.
const Time::TimeStamp & getCreatedTimeStamp () const
Obtain when the message was created.
Time::TimeStamp setCreatedTimeStamp (const Time::TimeStamp &timeStamp)
Revise the creation message timestamp.
const Time::TimeStamp & getEmittedTimeStamp () const
Obtain when the message was written to an external device (file or network).
Time::TimeStamp setEmittedTimeStamp (const Time::TimeStamp &timeStamp)
Set the emitted time stamp with the given value.
HeaderPrinter headerPrinter () const
Convenience method that simply returns a new HeaderPrinter functor for this header object.
DataPrinter dataPrinter () const
Convenience method that simply returns a new DataPrinter functor for this header object.
XMLPrinter xmlPrinter () const
Convenience method that simply returns a new XMLPrinter functor for this header object.
virtual std::ostream & print (std::ostream &os) const
Write out the entire message to a C++ text output stream.
virtual std::ostream & printHeader (std::ostream &os) const
Write out the message header to a C++ text output stream.
virtual std::ostream & printXML (std::ostream &os) const
Write out the message to a C++ text output stream in XML format.
bool hasBasis () const
Determine if the message has a basis message attached to it.
Ref getBasis () const
Obtain a reference to the message that this one was based on.
template<typename T >
T::Ref getBasis () const
Templated version of the above method.
Static Public Member Functions
static Logger::Log & Log ()
static const MetaTypeInfo & GetMetaTypeInfo ()
Obtain the message type information for RawVideo objects.
static Ref Make (const std::string &producer, double when, double range, double azimuth, double elevation, const std::string &tag)
static Ref Make (const QDomElement &header, const QDomElement &msg)
static Ref Make (ACE_InputCDR &cdr)
Class factory that creates new reference-counted BugPlot message objects using data from an input CDR stream.
Static Public Member Functions inherited from SideCar::Messages::Header
static Logger::Log & Log ()
Obtain log device to use for objects of this class.
static const MetaTypeInfo * GetMessageMetaTypeInfo (ACE_InputCDR &cdr)
Additional Inherited Members
Detailed Description
Definition at line 15 of file BugPlot.h.
Member Function Documentation
const MetaTypeInfo & BugPlot::GetMetaTypeInfo () static
Obtain the message type information for RawVideo objects.
Returns
MetaTypeInfo reference
Definition at line 22 of file BugPlot.cc.
Referenced by SideCar::Algorithms::BugCollectorUtils::BugPlotSubscriber::BugPlotSubscriber(), and Make().
size_t SideCar::Messages::BugPlot::getSize () const inline virtual
Obtain the C++ structure size for this object.
Derived classes must override if they extend Header with additional members.
Returns
size of a Header object.
Reimplemented from SideCar::Messages::Header.
Definition at line 90 of file BugPlot.h.
ACE_InputCDR & BugPlot::load (ACE_InputCDR & cdr) virtual
Read in a BugPlot message from an CDR input stream.
Override of Header::load().
Parameters
cdr stream to read from
Returns
stream read from
Reimplemented from SideCar::Messages::Header.
Definition at line 80 of file BugPlot.cc.
References SideCar::Messages::Header::load().
BugPlot::Ref BugPlot::Make (ACE_InputCDR & cdr) static
Class factory that creates new reference-counted BugPlot message objects using data from an input CDR stream.
Parameters
cdr input CDR stream to read from
\return reference to new RawVideo object
Definition at line 36 of file BugPlot.cc.
References GetMetaTypeInfo(), SideCar::Messages::Header::Header(), and LOGINFO.
std::ostream & BugPlot::printData (std::ostream & os) const virtual
Print out a textual representation of the BugPlot message.
Override of Header::print().
Parameters
os C++ text stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Definition at line 104 of file BugPlot.cc.
std::ostream & BugPlot::printDataXML (std::ostream & os) const virtual
Print out a XML representation of the BugPlot message.
Override of Header::printDataXML().
Parameters
os C++ text stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Definition at line 111 of file BugPlot.cc.
References SideCar::Messages::XmlStreamReader::getAttribute(), SideCar::Messages::Header::loadXML(), and SideCar::Messages::XmlStreamReader::readNextEntityAndValidate().
ACE_OutputCDR & BugPlot::write (ACE_OutputCDR & cdr) const virtual
Write out a BugPlot message to a CDR output stream.
Override of Header::write().
Parameters
cdr stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Definition at line 92 of file BugPlot.cc.
References SideCar::Messages::Header::write().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Messages/BugPlot.h
/Users/howes/src/sidecar/Messages/BugPlot.cc