SideCar: SideCar::IO::Growler Class Reference
SideCar::IO::Growler Class Reference
C++ interface to the Growl notification display service for Mac OS X (and other systemsw via various ports).
#include </Users/howes/src/sidecar/IO/Growl.h>
Data Structures
struct Destination
Utility class that holds information about a specific Growler destination.
Public Member Functions
Growler (const std::string &name, const std::string &password="")
Constructor for a new Growler object.
virtual ~Growler ()
Destructor.
void addHost (const std::string &host)
Add a new destination.
void removeHost (const std::string &host)
Remove an existing destination.
void useBroadcasting (bool value=true)
Enable (or disable) UDP broadcasting for Growl notifications.
void addNotification (const std::string &name, bool enabled=true)
Add a new notification name to support.
bool notify (const std::string &notification, const std::string &title, const std::string &description, int priority=0, bool sticky=false)
Emit a notification to registered hosts or broadcasted to the network.
Detailed Description
C++ interface to the Growl notification display service for Mac OS X (and other systemsw via various ports).
Growl is sort of like Twitter for applications: an application emits UDP messages to one or more Growl servers. This implementation also supports UDP broadcasting.
To use, create a new Growler instance, add one one or more notification names, and when desired invoked notify() to emit send out a Growl UDP message.
Definition at line 23 of file Growl.h.
Constructor & Destructor Documentation
Growler::Growler (const std::string & name, const std::string & password = "")
Constructor for a new Growler object.
Parameters
name the name to emit under
password the optional password to submit. If used, this must match the value set for the Growl application
Definition at line 131 of file Growl.cc.
References useBroadcasting().
Growler::~Growler () virtual
Destructor.
Releases any notification names and destinations.
Definition at line 138 of file Growl.cc.
Member Function Documentation
void Growler::addHost (const std::string & host)
Add a new destination.
Parameters
host the name or IP address of the host to contact
Definition at line 144 of file Growl.cc.
References useBroadcasting().
void Growler::addNotification (const std::string & name, bool enabled = true)
Add a new notification name to support.
Future notify() calls must use a notification name previously registered with addNotification().
Parameters
name the name to register
enabled whether the notification is currently enabled
Definition at line 209 of file Growl.cc.
bool Growler::notify (const std::string & notification, const std::string & title, const std::string & description, int priority = 0, bool sticky = false)
Emit a notification to registered hosts or broadcasted to the network.
Parameters
notification the registered notification to use
title the summary of the message
description the detailed contents of the message
priority optional priority for the message
sticky if true, the message will not fade away
Returns
true if successful
Definition at line 258 of file Growl.cc.
void SideCar::IO::Growler::removeHost (const std::string & host)
Remove an existing destination.
Parameters
host the name or IP address of the host to remove
void Growler::useBroadcasting (bool value = true)
Enable (or disable) UDP broadcasting for Growl notifications.
Note that calling addHost() will automatically disable broadcasting.
Parameters
value true if enabled.
Definition at line 170 of file Growl.cc.
Referenced by addHost(), and Growler().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/Growl.h
/Users/howes/src/sidecar/IO/Growl.cc