SideCar: SideCar::GUI::SettingsBlock Class Reference
SideCar::GUI::SettingsBlock Class Reference
Base class for a collection of Setting objects that conceptually belong together as a unit.
#include </Users/howes/src/sidecar/GUI/SettingsBlock.h>
Signals
void settingChanged ()
Notification sent out when a registered value has changed.
Public Member Functions
SettingsBlock (QObject *parent=0)
Constructor.
Protected Slots
virtual void postSettingChanged ()
Notification handler invoked when a Setting object that was registered with one of the add() methods emits its valueChanged() signal.
virtual void emitSettingChanged ()
Notification handler invoked when the QTimer object registered by the postSettingChanged() method fires.
Protected Member Functions
void add (Setting *setting)
Relate a Setting object to this SettingsBlock object.
Detailed Description
Base class for a collection of Setting objects that conceptually belong together as a unit.
The SettingsBlock::add() method allows one to add a Setting object to it. SettingsBlock objects do not keep around pointers to the added Setting objects, rather the SettingsBlock object will receive notification via its postSettingChanged() slot when a Setting object changes its held value. The postSettingChanged() method will register a one-shot QTimer object that will invoke the emitSettingChanged() slot as soon as the application's event loop is reentered. Only one QTime registration will take place, regardless of how many setting changes there are before the application's event loop is entered.
Definition at line 19 of file SettingsBlock.h.
Member Function Documentation
void SettingsBlock::add (Setting * setting) protected
Relate a Setting object to this SettingsBlock object.
Parameters
setting the object to connect
Definition at line 18 of file SettingsBlock.cc.
References postSettingChanged().
Referenced by SideCar::GUI::AScope::HistorySettings::HistorySettings(), SideCar::GUI::AScope::PeakBarSettings::PeakBarSettings(), SettingsBlock(), SideCar::GUI::VideoSampleCountTransform::VideoSampleCountTransform(), and SideCar::GUI::PPIDisplay::ViewSettings::ViewSettings().
void SettingsBlock::emitSettingChanged () protected virtual slot
Notification handler invoked when the QTimer object registered by the postSettingChanged() method fires.
Resets the pendingNotification_ attribute and emits the settingChanged() signal.
Definition at line 25 of file SettingsBlock.cc.
References settingChanged().
Referenced by postSettingChanged(), SettingsBlock(), and SideCar::GUI::VideoSampleCountTransform::VideoSampleCountTransform().
void SettingsBlock::postSettingChanged () protected virtual slot
Notification handler invoked when a Setting object that was registered with one of the add() methods emits its valueChanged() signal.
Sets up a QTimer to call emitSettingChanged() when the application event loop had nothing more to do. The emitSettingChanged() resets the one-shot boolean pendingNotification_ attribute and then emits the settingChanged() signal.
Definition at line 9 of file SettingsBlock.cc.
References emitSettingChanged().
Referenced by add(), SideCar::GUI::ChannelImaging::ChannelImaging(), SideCar::GUI::PPIDisplay::ViewSettings::moveTo(), and SettingsBlock().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/SettingsBlock.h
/Users/howes/src/sidecar/GUI/SettingsBlock.cc