SideCar: SideCar::GUI::OffscreenBuffer Class Reference
SideCar::GUI::OffscreenBuffer Class Reference
Manager of an OpenGL framebuffer object that allows for direct rendering into a texture object.
#include </Users/howes/src/sidecar/GUI/OffscreenBuffer.h>
Public Slots
void clearBuffer ()
Clear the render texture.
void remakeDisplayLists ()
Public Member Functions
OffscreenBuffer (const SampleImaging *imaging, double xMin, double xMax, double yMin, double yMax, int width, int height, int textureType=-1)
Constructor.
~OffscreenBuffer ()
Destructor.
bool isValid () const
Determine if the QGLFramebufferObject is valid and ready to use.
bool isInitialized () const
const Texture getTexture () const
Obtain the ID of the render texture.
const SampleImaging * getImaging () const
Obtain the imaging configuration for the rendering process.
void renderPoints (const VertexColorArray &points)
Prepare the OpenGL context to render the point data added by previous addPoint() calls.
void setBounds (double xMin, double xMax, double yMin, double yMax)
double getXMin () const
double getXMax () const
double getYMin () const
double getYMax () const
bool contains (double x, double y) const
bool intersects (double x0, double y0, double x1, double y1) const
Static Public Member Functions
static Logger::Log & Log ()
Obtain Log device to use for OffscreenBuffer messages.
Detailed Description
Manager of an OpenGL framebuffer object that allows for direct rendering into a texture object.
Uses an QGLFramebufferObject to do the OpenGL dirty work.
Definition at line 21 of file OffscreenBuffer.h.
Constructor & Destructor Documentation
OffscreenBuffer::OffscreenBuffer (const SampleImaging * imaging, double xMin, double xMax, double yMin, double yMax, int width, int height, int textureType = -1)
Constructor.
Creates a new OpenGL framebuffer object and initializes it to render into a new 2D texture object.
Parameters
imaging collection of settings that control how imaging is perfomed
Definition at line 26 of file OffscreenBuffer.cc.
References Log(), and LOGINFO.
OffscreenBuffer::~OffscreenBuffer ()
Destructor.
Destroys the created OpenGL framebuffer and 2D texture objects.
Definition at line 54 of file OffscreenBuffer.cc.
References Log(), and LOGINFO.
Member Function Documentation
const SampleImaging* SideCar::GUI::OffscreenBuffer::getImaging () const inline
Obtain the imaging configuration for the rendering process.
Returns
read-only reference
Definition at line 65 of file OffscreenBuffer.h.
Referenced by SideCar::GUI::PPIDisplay::BinaryOffscreenBuffer::addPoints(), SideCar::GUI::BScope::BinaryOffscreenBuffer::addPoints(), SideCar::GUI::BScope::VideoOffscreenBuffer::getImaging(), and SideCar::GUI::ESScope::VideoOffscreenBuffer::getImaging().
const Texture SideCar::GUI::OffscreenBuffer::getTexture () const inline
Obtain the ID of the render texture.
NOTE: use of this by another thread is not supported by OpenGL.
Returns
texture ID
Definition at line 59 of file OffscreenBuffer.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::initializeContext(), SideCar::GUI::BScope::PPIWidget::PPIWidget(), and SideCar::GUI::PPIDisplay::PPIWidget::~PPIWidget().
bool OffscreenBuffer::isValid () const
Determine if the QGLFramebufferObject is valid and ready to use.
Returns
true if valid, false if the texture size is too big or there is no framebuffer support.
Definition at line 132 of file OffscreenBuffer.cc.
Referenced by SideCar::GUI::BScope::PPIWidget::PPIWidget(), SideCar::GUI::PPIDisplay::OffscreenBuffer::rangeMaxChanged(), and SideCar::GUI::PPIDisplay::PPIWidget::~PPIWidget().
Logger::Log & OffscreenBuffer::Log () static
Obtain Log device to use for OffscreenBuffer messages.
Returns
Log device
Definition at line 19 of file OffscreenBuffer.cc.
References Logger::Log::Find().
Referenced by OffscreenBuffer(), renderPoints(), and ~OffscreenBuffer().
void OffscreenBuffer::renderPoints (const VertexColorArray & points)
Prepare the OpenGL context to render the point data added by previous addPoint() calls.
Invokes glDrawArrays() to perform the rendering.
Definition at line 118 of file OffscreenBuffer.cc.
References SideCar::GUI::VertexColorArray::draw(), SideCar::GUI::ChannelImaging::getSize(), and Log().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/OffscreenBuffer.h
/Users/howes/src/sidecar/GUI/OffscreenBuffer.cc