SideCar: SideCar::Messages::MetaTypeInfo Class Reference
SideCar::Messages::MetaTypeInfo Class Reference
Unique identification for message types/classes.
#include </Users/howes/src/sidecar/Messages/MetaTypeInfo.h>
Data Structures
struct Registrations
Internal class that mananges MetaTypeInfo registrations.
class SequenceGenerator
Internal class that provides monotonically increasing sequence numbers for messages.
Public Types
enum Value : uint16_t {
Value::kInvalid = 0, Value::kRawVideo, Value::kVideo, Value::kBinaryVideo,
Value::kExtractions, Value::kSegmentMessage, Value::kComplex, Value::kTSPI,
Value::kBugPlot, Value::kTrack, Value::kUnassigned
}
Active message types in the SideCar system.
using SequenceType = uint32_t
using HeaderRef = boost::shared_ptr< Header >
using TaskRef = boost::shared_ptr< IO::Task >
using CDRLoader = HeaderRef(*)(ACE_InputCDR &cdr)
using XMLLoader = HeaderRef(*)(const std::string &, XmlStreamReader &)
Public Member Functions
MetaTypeInfo (Value key, const std::string &name, CDRLoader cdrLoader, XMLLoader xmlLoader)
Constructor.
~MetaTypeInfo ()
Destructor.
void unregister ()
Value getKey () const
Obtain the Value value for the message class.
bool isa (Value key) const
Determine if the given MetaTypeInfo key is the same as ours.
const std::string & getName () const
Obtain the type name for the message class.
SequenceType getNextSequenceNumber () const
Obtain the next sequence number for a new message of this type.
CDRLoader getCDRLoader () const
Obtain the loader for the message class.
XMLLoader getXMLLoader () const
Obtain the loader for the message class.
bool operator< (const MetaTypeInfo &rhs) const
Less than comparison operator.
Static Public Member Functions
static auto GetValueValue (const Value &value) -> std::underlying_type_t< Value >
static Logger::Log & Log ()
Obtain the log device for MetaTypeInfo objects.
static const MetaTypeInfo * Find (Value key)
Obtain the MetaTypeInfo object registered under a given key.
static const MetaTypeInfo * Find (const std::string &keyName)
Obtain the MetaTypeInfo object registered under a given key name.
Detailed Description
Unique identification for message types/classes.
Each unique message class must have an entry in the MetaTypeInfo::Value enum. It is primarily used to locate message loading procedures that unmarshal data read in from an external data source.
Definition at line 25 of file MetaTypeInfo.h.
Member Enumeration Documentation
enum SideCar::Messages::MetaTypeInfo::Value : uint16_t strong
Active message types in the SideCar system.
The ordering is not important, though kInvalid should always be first, and kUnassigned should always be last.
NOTE: if you add to this, add to the END of the list, before kUnassigned. Otherwise, past recordings won't play correctly.
Enumerator
kInvalid
Keep first.
kRawVideo
Video data message emitted by the VME board.
kVideo
Video data message after conversion from VME format.
kBinaryVideo
Boolean data message.
kExtractions
Feature extraction message.
kSegmentMessage
Feature segmentation message.
kComplex
IQ (complex) message.
kTSPI
Message from external track (TSPI) provider.
kBugPlot
Message recording a user-initiated track.
kTrack
Message for an internally initiated track.
kUnassigned
Keep last.
Definition at line 43 of file MetaTypeInfo.h.
Constructor & Destructor Documentation
MetaTypeInfo::MetaTypeInfo (Value key, const std::string & name, CDRLoader cdrLoader, XMLLoader xmlLoader)
Constructor.
Registers the new MetaTypeInfo object under the given key.
Parameters
key the unique integral key for a message class
name the unique string key for a message class
loader the procedure to invoke to create a new message and load it from raw data buffer.
Definition at line 253 of file MetaTypeInfo.cc.
References Log(), and LOGINFO.
MetaTypeInfo::~MetaTypeInfo ()
Destructor.
Unregisters the MetaTypeInfo object from the internal registry.
Definition at line 264 of file MetaTypeInfo.cc.
References Log(), and LOGINFO.
Member Function Documentation
const MetaTypeInfo * MetaTypeInfo::Find (Value key) static
Obtain the MetaTypeInfo object registered under a given key.
NOTE: throws an exception if not found.
Parameters
key the key to look for
Returns
registered MetaTypeInfo object
Definition at line 315 of file MetaTypeInfo.cc.
Referenced by SideCar::Messages::CircularBuffer::add(), SideCar::Messages::Header::Log(), SideCar::GUI::ServiceBrowser::ServiceBrowser(), and SideCar::GUI::Playback::Emitter::~Emitter().
const MetaTypeInfo * MetaTypeInfo::Find (const std::string & keyName) static
Obtain the MetaTypeInfo object registered under a given key name.
NOTE: throws an exception if not found.
Parameters
keyName the key name to look for
Returns
registered MetaTypeInfo object
Definition at line 321 of file MetaTypeInfo.cc.
References kUnassigned, Log(), and Logger::ProcLog::thrower().
MetaTypeInfo::CDRLoader MetaTypeInfo::getCDRLoader () const
Obtain the loader for the message class.
Returns
Loader procedure
Definition at line 297 of file MetaTypeInfo.cc.
Referenced by SideCar::IO::MessageManager::MessageManager().
MetaTypeInfo::Value MetaTypeInfo::getKey () const
Obtain the Value value for the message class.
Returns
Value enum value
Definition at line 279 of file MetaTypeInfo.cc.
Referenced by SideCar::Algorithms::Algorithm::addProcessor(), SideCar::Messages::CircularBuffer::Get(), SideCar::Algorithms::CPISimpleOp::shutdown(), SideCar::Algorithms::FanOut::startup(), SideCar::Algorithms::Recorder::startup(), SideCar::Algorithms::FanIn::startup(), SideCar::Algorithms::Delay::startup(), SideCar::Algorithms::CPIAlgorithm::startup(), and SideCar::Algorithms::CPISimpleOp::startup().
const std::string & MetaTypeInfo::getName () const
Obtain the type name for the message class.
Returns
key name
Definition at line 285 of file MetaTypeInfo.cc.
Referenced by SideCar::Messages::CircularBuffer::add(), SideCar::Algorithms::Algorithm::addProcessor(), SideCar::GUI::PRIEmitter::MainWindow::MainWindow(), and SideCar::GUI::Playback::Emitter::makeWriter().
MetaTypeInfo::SequenceType MetaTypeInfo::getNextSequenceNumber () const
Obtain the next sequence number for a new message of this type.
Returns
next sequence number
Definition at line 291 of file MetaTypeInfo.cc.
References SideCar::Messages::MetaTypeInfo::SequenceGenerator::getNextSequenceNumber().
MetaTypeInfo::XMLLoader MetaTypeInfo::getXMLLoader () const
Obtain the loader for the message class.
Returns
Loader procedure
Definition at line 303 of file MetaTypeInfo.cc.
bool SideCar::Messages::MetaTypeInfo::isa (Value key) const inline
Determine if the given MetaTypeInfo key is the same as ours.
Parameters
key the value to compare
Returns
true if so
Definition at line 115 of file MetaTypeInfo.h.
References operator<<(), and operator>>().
Logger::Log & MetaTypeInfo::Log () static
Obtain the log device for MetaTypeInfo objects.
Returns
Log device
Definition at line 246 of file MetaTypeInfo.cc.
References Logger::Log::Find().
Referenced by Find(), MetaTypeInfo(), and ~MetaTypeInfo().
bool MetaTypeInfo::operator< (const MetaTypeInfo & rhs) const
Less than comparison operator.
Allows ordering of MetaTypeInfo objects by their type key.
Parameters
rhs object to compare against
Returns
true if our type key is less than the other object's type key
Definition at line 309 of file MetaTypeInfo.cc.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Messages/MetaTypeInfo.h
/Users/howes/src/sidecar/Messages/MetaTypeInfo.cc