SideCar: SideCar::GUI::ServiceBrowser Class Reference
SideCar::GUI::ServiceBrowser Class Reference
A refined Zeroconf browser for use by Qt widgets.
#include </Users/howes/src/sidecar/GUI/ServiceBrowser.h>
Public Types
using ZCBrowserRef = boost::shared_ptr< Zeroconf::Browser >
The following typedefs appear here so that we do not have to include Zeroconf/Browser.h, which also includes boost/signal.hpp, which has problems with QT includes.
using ZCServiceEntryRef = boost::shared_ptr< Zeroconf::ServiceEntry >
using ZCResolvedEntryRef = boost::shared_ptr< Zeroconf::ResolvedEntry >
using ZCServiceEntryVector = std::vector< ZCServiceEntryRef >
Signals
void availableServices (const ServiceEntryHash &found)
Notification sent out when the set of active services changes.
void foundServices (const ServiceEntryList &found)
Notification sent out when there are new services.
void lostServices (const ServiceEntryList &lost)
Notification sent out when services disappear.
Public Member Functions
ServiceBrowser (QObject *parent, const QString &type)
Constructor.
void start ()
Start the browser.
void stop ()
Stop the browser.
ServiceEntry * getServiceEntry (const QString &name) const
Obtain a ServiceEntry object under a given name.
const QString & getType () const
Static Public Member Functions
static Logger::Log & Log ()
Log device used by ServiceBrowser objects.
Detailed Description
A refined Zeroconf browser for use by Qt widgets.
Keeps track of the active services, represented by ServiceEntry objects. Users can obtain found ServiceEntry objects by name.
Definition at line 27 of file ServiceBrowser.h.
Constructor & Destructor Documentation
ServiceBrowser::ServiceBrowser (QObject * parent, const QString & type)
Constructor.
Parameters
parent owner relationship used for auto-destruction
serviceType a Zeroconf type designator that determines which services the browser sees.
Definition at line 21 of file ServiceBrowser.cc.
References SideCar::Messages::MetaTypeInfo::Find(), and Log().
Member Function Documentation
void SideCar::GUI::ServiceBrowser::availableServices (const ServiceEntryHash & found) signal
Notification sent out when the set of active services changes.
Parameters
found collection of active services
Referenced by stop().
void SideCar::GUI::ServiceBrowser::foundServices (const ServiceEntryList & found) signal
Notification sent out when there are new services.
Parameters
found collection of new services
Referenced by stop().
ServiceEntry * ServiceBrowser::getServiceEntry (const QString & name) const
Obtain a ServiceEntry object under a given name.
Parameters
name the name of the ServiceEntry to look for
Returns
object found, or NULL if none
Definition at line 112 of file ServiceBrowser.cc.
References Log(), and LOGDEBUG.
Referenced by SideCar::GUI::AScope::ChannelConnectionModel::getChannelConnection(), SideCar::GUI::HealthAndStatus::ChannelConnectionModel::Log(), SideCar::GUI::ChannelSetting::Log(), SideCar::GUI::AScope::ChannelConnectionModel::removeConnection(), and SideCar::GUI::ChannelGroup::shutdown().
Logger::Log & ServiceBrowser::Log () static
Log device used by ServiceBrowser objects.
Returns
log device
Definition at line 15 of file ServiceBrowser.cc.
References Logger::Log::Find().
Referenced by getServiceEntry(), ServiceBrowser(), start(), and stop().
void SideCar::GUI::ServiceBrowser::lostServices (const ServiceEntryList & lost) signal
Notification sent out when services disappear.
Parameters
lost collection of lost services
Referenced by stop().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/ServiceBrowser.h
/Users/howes/src/sidecar/GUI/ServiceBrowser.cc