SideCar: SideCar::Messages::Header Class Reference
SideCar::Messages::Header Class Reference
Definition of the header found at the beginning of all messages, regardless of content type.
#include </Users/howes/src/sidecar/Messages/Header.h>
Data Structures
struct DataPrinter
Utility functor that inserts a textual representation of message data into a std::ostream object.
struct HeaderPrinter
Utility functor that inserts a textual representation of a Header's header data into a std::ostream object.
struct XMLPrinter
Utility functor that inserts an XML representation of message data into a std::ostream object.
Public Types
using Ref = boost::shared_ptr< Header >
Public Member Functions
Header (const MetaTypeInfo &metaTypeInfo)
Constructor for messages read in from an external device.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis, MetaTypeInfo::SequenceType sequenceNumber)
Constructor for new messages.
virtual ~Header ()
Destructor.
const MetaTypeInfo & getMetaTypeInfo () const
Obtain the type specification for the message.
const GUID & getGloballyUniqueID () const
Get the globally-unique ID of the message.
MetaTypeInfo::SequenceType getMessageSequenceNumber () const
Get the message sequence number for the message.
void setMessageSequenceNumber (MetaTypeInfo::SequenceType msn)
Set the sequence number for this message.
const Time::TimeStamp & getCreatedTimeStamp () const
Obtain when the message was created.
Time::TimeStamp setCreatedTimeStamp (const Time::TimeStamp &timeStamp)
Revise the creation message timestamp.
const Time::TimeStamp & getEmittedTimeStamp () const
Obtain when the message was written to an external device (file or network).
Time::TimeStamp setEmittedTimeStamp (const Time::TimeStamp &timeStamp)
Set the emitted time stamp with the given value.
virtual size_t getSize () const
Obtain the C++ structure size for this object.
virtual ACE_InputCDR & load (ACE_InputCDR &cdr)
Obtain new instance data from a CDR input stream.
virtual ACE_OutputCDR & write (ACE_OutputCDR &cdr) const
Write out the header to a CDR output stream.
HeaderPrinter headerPrinter () const
Convenience method that simply returns a new HeaderPrinter functor for this header object.
DataPrinter dataPrinter () const
Convenience method that simply returns a new DataPrinter functor for this header object.
XMLPrinter xmlPrinter () const
Convenience method that simply returns a new XMLPrinter functor for this header object.
virtual std::ostream & print (std::ostream &os) const
Write out the entire message to a C++ text output stream.
virtual std::ostream & printHeader (std::ostream &os) const
Write out the message header to a C++ text output stream.
virtual std::ostream & printData (std::ostream &os) const
Write out the message data to a C++ text output stream.
virtual std::ostream & printXML (std::ostream &os) const
Write out the message to a C++ text output stream in XML format.
virtual std::ostream & printDataXML (std::ostream &os) const
Write out the message data to a C++ text output stream in XML format.
bool hasBasis () const
Determine if the message has a basis message attached to it.
Ref getBasis () const
Obtain a reference to the message that this one was based on.
template<typename T >
T::Ref getBasis () const
Templated version of the above method.
Static Public Member Functions
static Logger::Log & Log ()
Obtain log device to use for objects of this class.
static const MetaTypeInfo * GetMessageMetaTypeInfo (ACE_InputCDR &cdr)
Protected Member Functions
virtual void loadXML (XmlStreamReader &xsr)
Obtain new instance data from an XML input stream.
Detailed Description
Definition of the header found at the beginning of all messages, regardless of content type.
All messages contain a timestmp indicating when they were created, a timestamp when they were written out to a file or the network, and an unique sequence number.
Definition at line 25 of file Header.h.
Constructor & Destructor Documentation
Header::Header (const MetaTypeInfo & metaTypeInfo) explicit
Constructor for messages read in from an external device.
Parameters
metaTypeInfo type specification for the message
Definition at line 70 of file Header.cc.
References Log(), and LOGTIN.
Referenced by Log(), SideCar::Messages::BugPlot::Make(), SideCar::Messages::TSPI::MakeEFGCoordinateFromRawBytes(), and SideCar::Messages::TDecimator< _M >::print().
Header::Header (const std::string & producer, const MetaTypeInfo & metaTypeInfo)
Constructor for new messages.
Parameters
producer name of the entity that created the message
metaTypeInfo type specification for the message
Definition at line 45 of file Header.cc.
References Log(), and LOGTIN.
Header::Header (const std::string & producer, const MetaTypeInfo & metaTypeInfo, const Ref & basis)
Constructor for new messages.
Parameters
producer name of the entity that created the message
metaTypeInfo type specification for the message
Definition at line 53 of file Header.cc.
References Log(), and LOGTIN.
Header::Header (const std::string & producer, const MetaTypeInfo & metaTypeInfo, const Ref & basis, MetaTypeInfo::SequenceType sequenceNumber)
Constructor for new messages.
Parameters
producer name of the entity that created the message
metaTypeInfo type specification for the message
Definition at line 61 of file Header.cc.
References Log(), and LOGTIN.
Header::~Header () virtual
Destructor.
Made virtual so that derived classes will properly clean up our instance values (specifically guid_) destructed thru a Header pointer.
Definition at line 77 of file Header.cc.
Member Function Documentation
DataPrinter SideCar::Messages::Header::dataPrinter () const inline
Convenience method that simply returns a new DataPrinter functor for this header object.
Returns
DataPrinter object
Definition at line 194 of file Header.h.
Ref SideCar::Messages::Header::getBasis () const inline
Obtain a reference to the message that this one was based on.
NOTE: currently, this is only valid within a processing stream; in orther words, once a message is written to disk or the network, the message loses its basis value.
Returns
message reference
Definition at line 267 of file Header.h.
Referenced by SideCar::Messages::BinaryVideo::getVideoBasis().
template<typename T > T::Ref SideCar::Messages::Header::getBasis () const inline
Templated version of the above method.
Returns a typed reference to the basis message. Returns an invalid reference if the type-cast is invalid.
Returns
typed message reference
Definition at line 275 of file Header.h.
const Time::TimeStamp& SideCar::Messages::Header::getCreatedTimeStamp () const inline
Obtain when the message was created.
Returns
time stamp reference
Definition at line 109 of file Header.h.
Referenced by SideCar::GUI::Playback::Emitter::setEmitting().
const Time::TimeStamp& SideCar::Messages::Header::getEmittedTimeStamp () const inline
Obtain when the message was written to an external device (file or network).
Used by external utilities to calculate processing latencies within algorithms and processing chains.
Returns
time stamp reference
Definition at line 125 of file Header.h.
const GUID& SideCar::Messages::Header::getGloballyUniqueID () const inline
Get the globally-unique ID of the message.
A GUID contains a unique sequence number given to it by the metaTypeInfo_ attribute, accessed by the GUID.getMessageSequenceNumber().
Returns
unique ID
Definition at line 85 of file Header.h.
Referenced by SideCar::GUI::Playback::Emitter::~Emitter().
MetaTypeInfo::SequenceType SideCar::Messages::Header::getMessageSequenceNumber () const inline
Get the message sequence number for the message.
This is the sequence number from the GUID. Note that alone this is not unique among all SideCar messages; it is only unique within a message type.
Returns
sequence number
Definition at line 92 of file Header.h.
const MetaTypeInfo& SideCar::Messages::Header::getMetaTypeInfo () const inline
Obtain the type specification for the message.
Returns
Definition at line 78 of file Header.h.
virtual size_t SideCar::Messages::Header::getSize () const inline virtual
Obtain the C++ structure size for this object.
Derived classes must override if they extend Header with additional members.
Returns
size of a Header object.
Reimplemented in SideCar::Messages::TPRIMessage< _V >, SideCar::Messages::TPRIMessage< Traits::Bool >, SideCar::Messages::TPRIMessage< Traits::Int16 >, SideCar::Messages::TPRIMessage< Traits::ComplexInt16 >, SideCar::Messages::Extractions, SideCar::Messages::BugPlot, and SideCar::Messages::RawVideo.
Definition at line 140 of file Header.h.
bool SideCar::Messages::Header::hasBasis () const inline
Determine if the message has a basis message attached to it.
Returns
true if so
Definition at line 259 of file Header.h.
HeaderPrinter SideCar::Messages::Header::headerPrinter () const inline
Convenience method that simply returns a new HeaderPrinter functor for this header object.
Returns
HeaderPrinter object
Definition at line 176 of file Header.h.
ACE_InputCDR & Header::load (ACE_InputCDR & cdr) virtual
Obtain new instance data from a CDR input stream.
Parameters
cdr stream to read from
Returns
stream read from
Reimplemented in SideCar::Messages::TPRIMessage< _V >, SideCar::Messages::TPRIMessage< Traits::Bool >, SideCar::Messages::TPRIMessage< Traits::Int16 >, SideCar::Messages::TPRIMessage< Traits::ComplexInt16 >, SideCar::Messages::Extractions, SideCar::Messages::SegmentMessage, SideCar::Messages::TSPI, SideCar::Messages::TDecimator< _M >, SideCar::Messages::Track, SideCar::Messages::RawVideo, and SideCar::Messages::BugPlot.
Definition at line 99 of file Header.cc.
References Log(), LOGDEBUG, and LOGINFO.
Referenced by SideCar::Messages::BugPlot::load(), SideCar::Messages::RawVideo::load(), SideCar::Messages::TSPI::load(), SideCar::Messages::Extractions::load(), SideCar::Messages::PRIMessage::loadArray(), Log(), SideCar::GUI::Playback::Emitter::setEmitting(), and SideCar::GUI::Playback::Emitter::~Emitter().
void Header::loadXML (XmlStreamReader & xsr) protected virtual
Obtain new instance data from an XML input stream.
Parameters
xsr stream to read from
Reimplemented in SideCar::Messages::TPRIMessage< _V >, SideCar::Messages::TPRIMessage< Traits::Bool >, SideCar::Messages::TPRIMessage< Traits::Int16 >, SideCar::Messages::TPRIMessage< Traits::ComplexInt16 >, SideCar::Messages::TSPI, SideCar::Messages::Track, and SideCar::Messages::PRIMessage.
Definition at line 183 of file Header.cc.
References SideCar::Messages::XmlStreamReader::getAttribute(), Log(), SideCar::Time::TimeStamp::Min(), and SideCar::Time::TimeStamp::ParseSpecification().
Referenced by SideCar::Messages::PRIMessage::loadXML(), SideCar::Messages::Track::loadXML(), SideCar::Messages::TSPI::loadXML(), SideCar::Messages::BugPlot::printDataXML(), and SideCar::Messages::Extractions::printDataXML().
Logger::Log & Header::Log () static
Obtain log device to use for objects of this class.
Returns
log device
Definition at line 22 of file Header.cc.
References SideCar::Messages::MetaTypeInfo::Find(), Logger::Log::Find(), Header(), SideCar::Messages::MetaTypeInfo::kVideo, and load().
Referenced by Header(), SideCar::Messages::GUID::load(), load(), loadXML(), SideCar::Messages::GUID::write(), and write().
std::ostream & Header::print (std::ostream & os) const virtual
Write out the entire message to a C++ text output stream.
Parameters
os stream to write to
Returns
stream written to
Reimplemented in SideCar::Messages::TDecimator< _M >.
Definition at line 164 of file Header.cc.
References printData(), and printHeader().
std::ostream & Header::printData (std::ostream & os) const virtual
Write out the message data to a C++ text output stream.
Parameters
os stream to write to
Returns
stream written to
Reimplemented in SideCar::Messages::TPRIMessage< _V >, SideCar::Messages::TPRIMessage< Traits::Bool >, SideCar::Messages::TPRIMessage< Traits::Int16 >, SideCar::Messages::TPRIMessage< Traits::ComplexInt16 >, SideCar::Messages::Extractions, SideCar::Messages::SegmentMessage, SideCar::Messages::TSPI, SideCar::Messages::Track, SideCar::Messages::RawVideo, and SideCar::Messages::BugPlot.
Definition at line 152 of file Header.cc.
Referenced by print().
std::ostream & Header::printDataXML (std::ostream & os) const virtual
Write out the message data to a C++ text output stream in XML format.
Parameters
os stream to write to
Returns
stream written to
Reimplemented in SideCar::Messages::TPRIMessage< _V >, SideCar::Messages::TPRIMessage< Traits::Bool >, SideCar::Messages::TPRIMessage< Traits::Int16 >, SideCar::Messages::TPRIMessage< Traits::ComplexInt16 >, SideCar::Messages::Extractions, SideCar::Messages::TSPI, SideCar::Messages::Track, SideCar::Messages::PRIMessage, and SideCar::Messages::BugPlot.
Definition at line 158 of file Header.cc.
Referenced by printXML().
std::ostream & Header::printHeader (std::ostream & os) const virtual
Write out the message header to a C++ text output stream.
Parameters
os stream to write to
Returns
stream written to
Reimplemented in SideCar::Messages::PRIMessage.
Definition at line 144 of file Header.cc.
Referenced by print(), and SideCar::Messages::PRIMessage::printHeader().
std::ostream & Header::printXML (std::ostream & os) const virtual
Write out the message to a C++ text output stream in XML format.
Note: invokes printDataXML() to write the data elements of the message.
Parameters
os stream to write to
Returns
stream written to
Definition at line 172 of file Header.cc.
References printDataXML().
Time::TimeStamp Header::setCreatedTimeStamp (const Time::TimeStamp & timeStamp)
Revise the creation message timestamp.
Used by some SideCar utilities that wish to set/adjust the message frequency, which is determined by this time stamp.
Parameters
timeStamp new time stamp value
Returns
old value
Definition at line 83 of file Header.cc.
Time::TimeStamp Header::setEmittedTimeStamp (const Time::TimeStamp & timeStamp)
Set the emitted time stamp with the given value.
Parameters
timeStamp the time value to assign
Returns
previous emitted time stamp value
Definition at line 91 of file Header.cc.
void SideCar::Messages::Header::setMessageSequenceNumber (MetaTypeInfo::SequenceType msn) inline
Set the sequence number for this message.
Not to be used lightly. Particularly useful when an algorithm generates multiple output messages that should be synchronized by their sequence number.
NOTE: a better approach than this would be to have unique message sequence generators, which is available right now since there is a unique sequence generator associated with each unique producer name.
Parameters
msn new sequence number to use
Definition at line 103 of file Header.h.
ACE_OutputCDR & Header::write (ACE_OutputCDR & cdr) const virtual
Write out the header to a CDR output stream.
NOTE: by design we only write out our time stamp – the byte order and size are handled by one of the IO::Sink classes.
Parameters
cdr CDR stream to write to
Returns
CDR stream written to
Reimplemented in SideCar::Messages::TPRIMessage< _V >, SideCar::Messages::TPRIMessage< Traits::Bool >, SideCar::Messages::TPRIMessage< Traits::Int16 >, SideCar::Messages::TPRIMessage< Traits::ComplexInt16 >, SideCar::Messages::Extractions, SideCar::Messages::SegmentMessage, SideCar::Messages::TSPI, SideCar::Messages::TDecimator< _M >, SideCar::Messages::Track, SideCar::Messages::RawVideo, and SideCar::Messages::BugPlot.
Definition at line 131 of file Header.cc.
References Log(), LOGDEBUG, SideCar::Time::TimeStamp::Min(), and SideCar::Time::TimeStamp::Now().
Referenced by SideCar::Messages::BugPlot::write(), SideCar::Messages::RawVideo::write(), SideCar::Messages::Track::write(), SideCar::Messages::TSPI::write(), SideCar::Messages::Extractions::write(), and SideCar::Messages::PRIMessage::writeArray().
XMLPrinter SideCar::Messages::Header::xmlPrinter () const inline
Convenience method that simply returns a new XMLPrinter functor for this header object.
Returns
XMLPrinter object
Definition at line 212 of file Header.h.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Messages/Header.h
/Users/howes/src/sidecar/Messages/Header.cc