SideCar: SideCar::GUI::MessageReader Class Reference
SideCar::GUI::MessageReader Class Reference
Base class for SideCar message readers used by the GUI applications.
#include </Users/howes/src/sidecar/GUI/MessageReader.h>
Signals
void connected ()
Notification that the reader has connected to a publisher.
void received (const Messages::Header::Ref &msg)
Notification that a new message is available from a publisher.
void disconnected ()
Notification that the reader has disconnected from a publisher.
Public Member Functions
const Messages::MetaTypeInfo * getMetaTypeInfo () const
Obtain the meta type info for the messages being received.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for MessageReader objects.
static MessageReader * Make (const ServiceEntry *service)
Create a new MessageReader object using information from a publisher's ServiceEntry object.
static MessageReader * Make (const std::string &topic, const Messages::MetaTypeInfo *type)
Create a new MessageReader object using information from a publisher's ServiceEntry object.
Protected Member Functions
MessageReader (const Messages::MetaTypeInfo *metaTypeInfo)
Constructor.
void addRawData (ACE_Message_Block *raw)
Add raw incoming message data to the active message queue.
Detailed Description
Base class for SideCar message readers used by the GUI applications.
Contains no actual connection code; see derived classes TCPMessageReader and MulticastMessageReader.
Manages two MessageList objects, one that is active for incoming data, and one that was active but can safely be used by another thread to obtain received data.
Definition at line 23 of file MessageReader.h.
Constructor & Destructor Documentation
MessageReader::MessageReader (const Messages::MetaTypeInfo * metaTypeInfo) protected
Constructor.
Prohibits direct instantiation of this class. Use the class Make() methods instead.
Parameters
metaTypeInfo message type descriptor for data being read
Definition at line 50 of file MessageReader.cc.
Member Function Documentation
void MessageReader::addRawData (ACE_Message_Block * raw) protected
Add raw incoming message data to the active message queue.
First converts the raw data into a SideCar message type. Thread safe. Emits the dataAvailable() signal if this is the first message added he active message queue.
Parameters
raw pointer to raw message data
Definition at line 57 of file MessageReader.cc.
References SideCar::IO::MessageManager::getNative(), Log(), and received().
const Messages::MetaTypeInfo* SideCar::GUI::MessageReader::getMetaTypeInfo () const inline
Obtain the meta type info for the messages being received.
Returns
Messages::MetaTypeInfo object
Definition at line 55 of file MessageReader.h.
Logger::Log & MessageReader::Log () static
Obtain the log device for MessageReader objects.
Returns
Logger::Log reference
Definition at line 15 of file MessageReader.cc.
References Logger::Log::Find().
Referenced by addRawData(), and Make().
MessageReader * MessageReader::Make (const ServiceEntry * service) static
Create a new MessageReader object using information from a publisher's ServiceEntry object.
Parameters
service connection description for a publisher
Returns
new MessageReader object, or NULL if error
Definition at line 22 of file MessageReader.cc.
References SideCar::GUI::ServiceEntry::getHost(), SideCar::GUI::ServiceEntry::getName(), SideCar::GUI::ServiceEntry::getPort(), SideCar::GUI::ServiceEntry::getTransport(), Log(), LOGERROR, LOGINFO, and SideCar::GUI::MulticastMessageReader::Make().
Referenced by SideCar::GUI::ReaderThread::run().
static MessageReader* SideCar::GUI::MessageReader::Make (const std::string & topic, const Messages::MetaTypeInfo * type) static
Create a new MessageReader object using information from a publisher's ServiceEntry object.
Parameters
service connection description for a publisher
Returns
new MessageReader object, or NULL if error
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/MessageReader.h
/Users/howes/src/sidecar/GUI/MessageReader.cc