SideCar: SideCar::GUI::Master::RemoteClient Class Reference
SideCar::GUI::Master::RemoteClient Class Reference
TCP command interface that allows control of the recordings via command-line utility.
#include </Users/howes/src/sidecar/GUI/Master/RemoteClient.h>
Public Member Functions
RemoteClient (RecordingController &parent, QTcpSocket &socket)
Static Public Member Functions
static Logger::Log & Log ()
Log device to use for RemoteClient log messages.
Detailed Description
TCP command interface that allows control of the recordings via command-line utility.
Definition at line 19 of file RemoteClient.h.
Member Function Documentation
Logger::Log & RemoteClient::Log () static
Log device to use for RemoteClient log messages.
Returns
Log device
Definition at line 11 of file RemoteClient.cc.
References Logger::Log::Find(), Log(), LOGDEBUG, and LOGINFO.
Referenced by Log().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/RemoteClient.h
/Users/howes/src/sidecar/GUI/Master/RemoteClient.cc