SideCar: UnitTest::Suite Class Reference
UnitTest::Suite Class Reference
Represents a collection of TestObj objects.
#include </Users/howes/src/sidecar/UnitTest/Suite.h>
Public Types
using PairBoolTestObj = std::pair< bool, TestObj * >
Definition of type stored in std::vector collection.
Public Member Functions
Suite (const std::string &name) throw ()
Constructor.
virtual ~Suite () throw ()
Destructor.
virtual int numTests () const throw ()
Returns the number of unit tests this object represents.
virtual RunResults & run (RunResults &rr) throw ()
Execute the unit tests this object represents.
void add (TestObj *obj, bool own=true) throw ()
Add the given test object to our collection.
void add (TestObj &obj) throw ()
Add a reference to a test object, probably something allocated on the stack, and not the heap.
Public Member Functions inherited from UnitTest::TestObj
TestObj () throw ()
Default contructor.
TestObj (const std::string &name) throw ()
Contructor.
virtual ~TestObj ()
Destructor.
virtual int mainRun (std::ostream *os=&std::cerr) throw ()
Utility method useful in main() to run unit tests.
void setTestName (const std::string &name) throw ()
Set the test name to the given value.
const std::string & testName () const throw ()
Get the name of this test object.
void _assertTrue (bool value, const char *expr, const char *file, int line) const throw (UnitTestException)
Assertion for a true value.
void _assertTrue (std::istream &value, const char *expr, const char *file, int line) const throw (UnitTestException)
Assertion for a good std::istream value.
void _assertFalse (bool value, const char *expr, const char *file, int line) const throw (UnitTestException)
Assertion for a false value.
void _assertFalse (std::istream &value, const char *expr, const char *file, int line) const throw (UnitTestException)
Assertion for a good std::istream value.
template<typename T >
void _assertEqual (const T &expected, const T &actual, const char *file, int line) const throw (UnitTestException)
Assertion that two values of some type T are equal.
template<typename T >
void _assertEqual (const T *expected, const T *actual, const char *file, int line) const throw (UnitTestException)
Assertion that two values of some type pointer are equal.
void _assertEqual (std::string expected, std::string actual, const char *file, int line) const throw (UnitTestException)
Assertion that two strings are equal.
void _assertEqual (double expected, double actual, const char *file, int line) const throw (UnitTestException)
void _assertEqual (double expected, double actual, double epsilon, const char *file, int line) const throw (UnitTestException)
Assertion that two values are equal within some tolerance factor.
template<typename T >
void _assertNotEqual (const T &expected, const T &actual, const char *file, int line) const throw (UnitTestException)
Assertion that two values are NOT equal.
template<typename T >
void _assertNotEqual (const T *expected, const T *actual, const char *file, int line) const throw (UnitTestException)
void _assertNotEqual (std::string expected, std::string actual, const char *file, int line) const throw (UnitTestException)
Assertion that two strings are NOT equal.
void _assertNotEqual (double expected, double actual, const char *file, int line) const throw (UnitTestException)
void _assertNotEqual (double expected, double actual, double epsilon, const char *file, int line) const throw (UnitTestException)
Assertion that two values are NOT equal within some tolerance factor.
Additional Inherited Members
Protected Member Functions inherited from UnitTest::TestObj
virtual void test ()
Method to perform the unit test.
Detailed Description
Represents a collection of TestObj objects.
Extends TestObj interface to register one or more unit tests. Executing Suite::run() exercises all of them, in the order that they were registered. Because Suite only relies on the TestObj interface, nesting of Suite objects (and other container types) is possible. Here's a simple example:
struct Foobar : public UnitTest::TestObj
{
void test() { assertEqual(2, 2); }
};
int
main()
{
UnitTest::Suite s("Suite");
s.add(new Foobar);
return s.mainRun();
}
Definition at line 35 of file Suite.h.
Member Typedef Documentation
using UnitTest::Suite::PairBoolTestObj = std::pair<bool,TestObj*>
Definition of type stored in std::vector collection.
First element of std::pair holds a flag indicating if the second object is to be deleted upon destruction of the Suite object. The second element of the pair is a pointer to a TestObj object.
Definition at line 43 of file Suite.h.
Constructor & Destructor Documentation
UnitTest::Suite::Suite (const std::string & name) throw () inline
Constructor.
Parameters
name name of the test suite
Definition at line 49 of file Suite.h.
References numTests(), run(), and ~Suite().
Suite::~Suite () throw () virtual
Destructor.
Deletes all registered tests which we own.
Definition at line 23 of file Suite.cc.
Referenced by Suite().
Member Function Documentation
void UnitTest::Suite::add (TestObj * obj, bool own = true) throw () inline
Add the given test object to our collection.
Note that there is no way to remove tests once added.
Parameters
obj test object to add
own if true, assume ownership of the object and delete it when the Suite instance is destroyed.
Definition at line 78 of file Suite.h.
void UnitTest::Suite::add (TestObj & obj) throw () inline
Add a reference to a test object, probably something allocated on the stack, and not the heap.
Does not take ownership of the object.
Parameters
obj test object to add
Warning
Do not use a temporary (eg. add(TestObj());) since the object will be destroyed after the add method returns, and then your test case will run on a destructed object, which is bad.
Definition at line 89 of file Suite.h.
int Suite::numTests () const throw () virtual
Returns the number of unit tests this object represents.
The returned value represents the sum of numTests calls for each registered unit test. Note that this value may not be the same as what std::vector::size() would return, because one or more registered objects may itself be a Suite object.
Returns
number of registered tests
Reimplemented from UnitTest::TestObj.
Definition at line 51 of file Suite.cc.
Referenced by Suite().
RunResults & Suite::run (RunResults & rr) throw () virtual
Execute the unit tests this object represents.
Loops thru all of the registered unit test objects, and calls their run method.
Parameters
rr collector of run statistics
Returns
value of input parameter
Reimplemented from UnitTest::TestObj.
Definition at line 99 of file Suite.cc.
Referenced by Suite().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/UnitTest/Suite.h
/Users/howes/src/sidecar/UnitTest/Suite.cc