SideCar: SideCar::IO::Reader Class Reference
SideCar::IO::Reader Class Reference abstract
Abstract base class for readers.
#include </Users/howes/src/sidecar/IO/Readers.h>
Public Types
using Ref = boost::shared_ptr< Reader >
Public Member Functions
Reader ()
Constructor for new reader.
virtual ~Reader ()
Destructor.
virtual bool fetchInput ()=0
Read in data from the device and append to the existing ACE_Message_Block.
bool isMessageAvailable () const
Determine if a complete message is available for processing.
ACE_Message_Block * getMessage ()
Obtain the raw data block available from the reader.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device to use for log messages.
Protected Member Functions
void setAvailable (ACE_Message_Block *available)
Make a complete message available for consumption.
Detailed Description
Abstract base class for readers.
A reader accumulates data from a device until it has all of the data of a complete message. All SideCar messages have a header (see SideCar::Messages::Header class) which contains a size in bytes. A reader simply adds incoming bytes to an ACE_Message_Block until the ACE_Message_Block::length() == Header::getSize().
Definition at line 231 of file Readers.h.
Member Function Documentation
virtual bool SideCar::IO::Reader::fetchInput () pure virtual
Read in data from the device and append to the existing ACE_Message_Block.
Returns
true if device is still valid, false otherwise
Implemented in SideCar::IO::DatagramReader, and SideCar::IO::StreamReader.
ACE_Message_Block * Reader::getMessage ()
Obtain the raw data block available from the reader.
This is a one-shot call: future calls will return NULL until another message becomes available via the setAvailable() method. NOTE: caller is responsible for releasing the block when it is done with it by calling ACE_Message_Block::release() (and not by invoking delete on the returned object)
Returns
raw data block or NULL if isMessageAvailable() returns false.
Definition at line 33 of file Readers.cc.
Referenced by SideCar::IO::MulticastDataSubscriber::ReaderThread::close(), SideCar::IO::TCPInputHandler::handle_input(), SideCar::Algorithms::BugCollectorUtils::BugPlotReader::handle_input(), SideCar::IO::VMEReaderTask::openAndInit(), SideCar::IO::TSPIReaderTask::openAndInit(), SideCar::IO::UDPSocketReaderTask::openAndInit(), SideCar::IO::MulticastVMEReaderTask::openAndInit(), SideCar::GUI::Playback::Emitter::setEmitting(), SideCar::IO::FileReaderTask::svc(), and SideCar::GUI::Playback::Emitter::~Emitter().
bool SideCar::IO::Reader::isMessageAvailable () const inline
Determine if a complete message is available for processing.
Returns
true if so
Definition at line 260 of file Readers.h.
Referenced by SideCar::IO::MulticastDataSubscriber::ReaderThread::close(), SideCar::IO::DatagramReader::fetchInput(), SideCar::IO::TCPInputHandler::handle_input(), SideCar::Algorithms::BugCollectorUtils::BugPlotReader::handle_input(), SideCar::IO::VMEReaderTask::openAndInit(), SideCar::IO::TSPIReaderTask::openAndInit(), SideCar::IO::UDPSocketReaderTask::openAndInit(), SideCar::IO::MulticastVMEReaderTask::openAndInit(), SideCar::GUI::Playback::Emitter::setEmitting(), SideCar::IO::FileReaderTask::svc(), and SideCar::GUI::Playback::Emitter::~Emitter().
Logger::Log & Reader::Log () static
Obtain the log device to use for log messages.
Returns
Definition at line 18 of file Readers.cc.
References Logger::Log::Find().
void Reader::setAvailable (ACE_Message_Block * available) protected
Make a complete message available for consumption.
Parameters
available
Definition at line 41 of file Readers.cc.
Referenced by SideCar::IO::StreamReader::fetchInput(), and SideCar::IO::DatagramReader::fetchInput().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/Readers.h
/Users/howes/src/sidecar/IO/Readers.cc