SideCar: SideCar::IO::Channel Class Reference
SideCar::IO::Channel Class Reference
Representation of a named and typed data channel.
#include </Users/howes/src/sidecar/IO/Channel.h>
Public Types
using TaskRef = boost::shared_ptr< Task >
Public Member Functions
Channel (const std::string &name, const std::string &typeName)
Constructor.
Channel (const std::string &name, const std::string &typeName, const TaskRef &task, size_t channelIndex=0)
Constructor.
const std::string & getName () const
Obtain the name of the channel.
const Messages::MetaTypeInfo * getMetaTypeInfo () const
const std::string & getTypeName () const
Obtain the name of the data type configured for the channel.
Messages::MetaTypeInfo::Value getTypeKey () const
Obtain the unique key of the data type configured for the channel.
void addRecipient (const TaskRef &task, size_t channelIndex)
Add a message recipient to the list of recipients associated with the channel.
void setSender (const TaskRef &sender)
Set the Task object that sends data over this channel.
const TaskRef & getSender () const
Obtain the Task object that sends data over this channel.
bool deliver (ACE_Message_Block *data) const
Deliver a message over the channel to the registered recipients.
void updateSenderUsingData (bool value) const
Invoke Task::setUsingData() for the sender assigned to this channel.
bool areAnyRecipientsUsingData () const
Determine if there are any downstream recipients that demand data from the channel's sender.
Static Public Member Functions
static Logger::Log & Log ()
Detailed Description
Representation of a named and typed data channel.
Channels represent typed-connections between IO::Task objects. Channels are one-way, from sender to one or more receipients. Use addRecipient() to add a new connection to another IO::Task object.
All recipient connections have an index value associated with them, which is the index into the recipient's list of input channels. This value is conveyed to the receiving Task by storing it in the priority slot of the ACE_Message_Block of the containing the message. The code for RecipientList::deliver() describes this in detail.
Definition at line 25 of file Channel.h.
Constructor & Destructor Documentation
SideCar::IO::Channel::Channel (const std::string & name, const std::string & typeName) inline
Constructor.
Parameters
name assigned to the channel (for diagnostics and linking)
typeName name of the message type the channel supports
Definition at line 38 of file Channel.h.
SideCar::IO::Channel::Channel (const std::string & name, const std::string & typeName, const TaskRef & task, size_t channelIndex = 0) inline
Constructor.
Allow specification of the first recipient.
Parameters
name name of the channel
typeName name of the message type the channel supports
taskIndex the task index for the first recipient
channelIndex the channel index for the first recipient
Definition at line 51 of file Channel.h.
Member Function Documentation
void SideCar::IO::Channel::addRecipient (const TaskRef & task, size_t channelIndex) inline
Add a message recipient to the list of recipients associated with the channel.
Parameters
taskIndex unique task identifier of the recipient
channelIndex recipient's channel index for this output channel
Definition at line 83 of file Channel.h.
bool SideCar::IO::Channel::areAnyRecipientsUsingData () const inline
Determine if there are any downstream recipients that demand data from the channel's sender.
Returns
true if so
Definition at line 115 of file Channel.h.
Referenced by SideCar::IO::ChannelVector::areAnyRecipientsUsingData().
bool SideCar::IO::Channel::deliver (ACE_Message_Block * data) const inline
Deliver a message over the channel to the registered recipients.
Parameters
data the message to deliver
Returns
true if successful
Definition at line 103 of file Channel.h.
Referenced by SideCar::IO::Task::doClearStatsRequest().
const std::string& SideCar::IO::Channel::getName () const inline
Obtain the name of the channel.
A channel name is defined by the task that holds the Channel object.
Returns
channel name
Definition at line 61 of file Channel.h.
Referenced by SideCar::IO::ChannelVector::add(), SideCar::IO::ChannelVector::findName(), SideCar::Algorithms::Router::startup(), and SideCar::Algorithms::Printer::startup().
const TaskRef& SideCar::IO::Channel::getSender () const inline
Obtain the Task object that sends data over this channel.
Returns
Task reference (may be empty if never set)
Definition at line 95 of file Channel.h.
Messages::MetaTypeInfo::Value SideCar::IO::Channel::getTypeKey () const inline
Obtain the unique key of the data type configured for the channel.
Returns
type key
Definition at line 75 of file Channel.h.
Referenced by SideCar::Algorithms::CPISimpleOp::shutdown(), SideCar::Algorithms::FanOut::startup(), SideCar::Algorithms::FanIn::startup(), SideCar::Algorithms::Recorder::startup(), SideCar::Algorithms::ShiftBins::startup(), SideCar::Algorithms::Delay::startup(), SideCar::Algorithms::CPIAlgorithm::startup(), SideCar::Algorithms::CPISimpleOp::startup(), and SideCar::Algorithms::Printer::startup().
const std::string& SideCar::IO::Channel::getTypeName () const inline
Obtain the name of the data type configured for the channel.
Returns
data type name
Definition at line 69 of file Channel.h.
void SideCar::IO::Channel::setSender (const TaskRef & sender) inline
Set the Task object that sends data over this channel.
Parameters
sender Task that sends data over the channel
Definition at line 89 of file Channel.h.
Referenced by SideCar::Runner::StreamBuilder::Make().
void Channel::updateSenderUsingData (bool value) const
Invoke Task::setUsingData() for the sender assigned to this channel.
Parameters
value the new value to use
Definition at line 17 of file Channel.cc.
References Logger::Log::Find(), LOGINFO, and SideCar::IO::Task::setUsingData().
Referenced by SideCar::IO::Task::addInputChannel().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/Channel.h
/Users/howes/src/sidecar/IO/Channel.cc