SideCar: Logger::LogStreamBuf Class Reference
Logger::LogStreamBuf Class Reference
Enhanced std::stringbuf that forwards `finished' log messages to a Log device.
#include </Users/howes/src/sidecar/Logger/LogStreamBuf.h>
Public Member Functions
LogStreamBuf ()
Constructor.
virtual ~LogStreamBuf ()
Destuctor.
void setInfo (Log *log, Priority::Level level)
Assign a Log device and message priority level for the next message accumulated by the buffer.
Detailed Description
Enhanced std::stringbuf that forwards `finished' log messages to a Log device.
The sync() method handles this message forwarding. It overrides the std::stringbuf method, and is invoked when the owning stream wishes to flush the output.
Definition at line 15 of file LogStreamBuf.h.
Constructor & Destructor Documentation
LogStreamBuf::~LogStreamBuf () virtual
Destuctor.
Flush any unfinished message.
Definition at line 7 of file LogStreamBuf.cc.
References Logger::Log::post().
Referenced by LogStreamBuf().
Member Function Documentation
void LogStreamBuf::setInfo (Log * log, Priority::Level level)
Assign a Log device and message priority level for the next message accumulated by the buffer.
Parameters
log Log device that will receive the finished message text
level priority level for the message text
Definition at line 22 of file LogStreamBuf.cc.
Referenced by LogStreamBuf().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Logger/LogStreamBuf.h
/Users/howes/src/sidecar/Logger/LogStreamBuf.cc