SideCar: SideCar::GUI::Master::RootItem Class Reference
SideCar::GUI::Master::RootItem Class Reference
The root item of a QTreeView view.
#include </Users/howes/src/sidecar/GUI/Master/RootItem.h>
Public Member Functions
RootItem ()
Constructor.
ConfigurationItem * find (const QString &name) const
Locate a child item by its name.
ConfigurationItem * getChild (int index) const
Public Member Functions inherited from SideCar::GUI::Master::CollectionItem
void updateCollectionStats (CollectionStats &stats) const
Prototype for method to update a CollectionStats object with statistics provided by a TreeViewItem derivative.
bool canExpand () const
Determine if the TreeViewItem is expandable.
QVariant getNameDataValue (int role) const
Obtain the data value for the ServicesModel::kName column, which displays the name of the TreeViewItem.
QVariant getStateDataValue (int role) const
Obtain the data value for the ServicesModel::kState column, which displays the processing state of the TreeViewItem.
QVariant getRecordingDataValue (int role) const
Obtain the data value for the ServicesModel::kRecording column, which displays the recording state of the TreeViewItem.
QVariant getPendingCountValue (int role) const
Obtain the data value for the ServicesModel::kPending column, which displays the pending queue size of this item.
QVariant getRateDataValue (int role) const
Obtain the data value for the ServicesModel::kRate column, which displays the message processing rate of the TreeViewItem.
QVariant getErrorDataValue (int role) const
Obtain the data value for the ServicesModel::kError column, which displays any error text from the TreeViewItem.
IO::ProcessingState::Value getProcessingState () const
const CollectionStats & getCollectionStats () const
bool canRecord () const
bool willRecord () const
bool isRecording () const
void recalculateStats ()
Public Member Functions inherited from SideCar::GUI::Master::TreeViewItem
~TreeViewItem ()
Destructor.
virtual void initialize ()
Initialize this object's internal state.
const IO::StatusBase & getStatus () const
Obtain the latest IO::StatusBase object received for this object.
bool update (const IO::StatusBase &status)
Update the TreeViewItem held status.
bool isOK () const
bool isProcessing () const
Determine if the object is in a 'processing' state: auto-diagnostic, calibration, or run.
ActiveState getActiveState () const
Obtain the current ActiveState value for this object.
QVariant getData (int column, int role) const
Obtain the data point to use for a specific role in a given column.
virtual QVariant getHostDataValue (int role) const
Obtain the data value for the ServicesModel::kHost column, which displays the host name of the machine where the object is running.
virtual QVariant getInfoDataValue (int role) const
Obtain the data value for the ServicesModel::kInfo column, which displays miscellaneous informational data of the TreeViewItem.
virtual QColor getForegroundColor (int column) const
Obtain the foreground color to use for the contents of a given column.
virtual QFont getFont (int column) const
Obtain the font to use for the contents of a given column.
virtual int getAlignment (int columnt) const
Obtain the alignment (horizontal and vertical) to use for the contents of a given column.
virtual bool canEdit () const
Determine if the TreeViewItem supports editing of runtime parameter values.
const QString & getName () const
Obtain the object's name.
const QString & getFullName () const
Get the full name of the item.
void insertChild (int row, TreeViewItem *child)
Insert a child, renumbering the indices of all children after it.
void appendChild (TreeViewItem *child)
Add a child.
void removeChild (int index)
Remove the child at a given index.
TreeViewItem * getChild (int index) const
Obtain the child associated with a given index value.
int getNumChildren () const
Obtain the number of children.
int getIndex () const
Obtain the index of this object in the context of our parent's children array.
TreeViewItem * getParent () const
Obtain the parent of this TreeViewItem object.
int getParentIndex () const
Obtain the index value of the parent object (equivalent to getParent()->getIndex().
ChildrenIterator getChildrenIterator () const
Obtain a Java-style iterator for the children array.
bool isExpanded () const
Determine if the object is expanded.
void setExpanded (bool expanded)
Change the expansion attribute of the object.
int getInsertionPoint (const QString &name) const
Obtain the row where the given name could be inserted without disturbing the ordering of the existing rows.
virtual bool isFiltered (const QString &filter) const
Determine if this item contains the given filter string.
Additional Inherited Members
Public Types inherited from SideCar::GUI::Master::TreeViewItem
enum ActiveState { kIdle, kPartial, kActive, kNotUsingData }
using Children = QList< TreeViewItem * >
using ChildrenIterator = QListIterator< TreeViewItem * >
Static Public Member Functions inherited from SideCar::GUI::Master::TreeViewItem
static QVariant GetRecordingDataValue (bool canRecord, int role)
Utility class method that returns an appropriate value for the recording state depicted by the two arguments.
static QColor GetTextColor ()
Class method that returns the default (black) text color for all Qt::Foreground roles.
static QColor GetOKColor ()
Class method that returns the OK text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetWarningColor ()
Class method that returns the 'warning text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetFailureColor ()
Class method that returns the 'failure' text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetRecordingColor ()
Class method that returns the text color to use to show when a task is currently recording.
static QFont GetTextFont ()
Obtain the normal font to use for displayed text.
Protected Member Functions inherited from SideCar::GUI::Master::CollectionItem
CollectionItem (const IO::StatusBase &status, TreeViewItem *parent)
void beforeUpdate ()
Hook invoked before a status update.
void afterUpdate ()
Hook invoked after a status update.
void accumulateChildStats (TreeViewItem *child)
Protected Member Functions inherited from SideCar::GUI::Master::TreeViewItem
TreeViewItem ()
Constructor for the RootItem object (which has no parent).
TreeViewItem (const IO::StatusBase &status, TreeViewItem *parent)
Constructor for all derived classes except RootItem.
void setName (const QString &name)
void setOK (bool ok)
void setProcessing (bool processing)
void setProcessingState (IO::ProcessingState::Value state)
void setActiveState (ActiveState activeState)
template<typename T >
const T & getStatusT () const
Detailed Description
The root item of a QTreeView view.
A RootItem object has no parent, and all children are of class ConfigurationItem.
Definition at line 15 of file RootItem.h.
Member Function Documentation
ConfigurationItem * RootItem::find (const QString & name) const
Locate a child item by its name.
Parameters
name the name to look forward
Returns
found child or NULL if not found
Definition at line 8 of file RootItem.cc.
References SideCar::GUI::Master::TreeViewItem::getChild(), SideCar::GUI::Master::TreeViewItem::getName(), and SideCar::GUI::Master::TreeViewItem::getNumChildren().
Referenced by RootItem().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/RootItem.h
/Users/howes/src/sidecar/GUI/Master/RootItem.cc