SideCar: SideCar::GUI::WindowManager Class Reference
SideCar::GUI::WindowManager Class Reference
Manager of an application's 'Window' menu.
#include </Users/howes/src/sidecar/GUI/WindowManager.h>
Public Types
enum WindowMenuAction {
kNew = 0, kClose, kSeparator1, kMinimize,
kMaximize, kFullScreen, kSeparator2, kToolBarMenu,
kSeparator3, kNumWindowMenuActions
}
Enumeration for the various window actions found in the Window menu.
Public Slots
void showMessage (const QString &msg, int duration)
Show a message in the active main window.
Signals
void activeMainWindowChanged (MainWindowBase *window)
Public Member Functions
WindowManager (QObject *parent=0)
Constructor.
QMenu * makeWindowMenu (QWidget *parent)
Create the 'Window' menu for a given widget.
void addWindowMenuActionTo (ToolBar *toolBar, int index)
Obtain the QAction object found within the shared 'Window' menu.
void setVisibleWindowMenuNew (bool visible)
Set the visibility state of the "New" action in the "Window" menu.
void setVisibleWindowMenuClose (bool visible)
Set the visibility state of the "Close" action in the "Window" menu.
void setVisibleWindowMenuMinimize (bool visible)
Set the visibility state of the "Minimize" action in the "Window" menu.
void setVisibleWindowMenuMaximize (bool visible)
Set the visibility state of the "Maximize" action in the "Window" menu.
void setVisibleWindowMenuFullScreen (bool visible)
Set the visibility state of the full-screen action in the "Window" menu.
int getNumManagedWindows () const
Obtain the number of open MainWindowBase objects.
MainWindowBase * getActiveMainWindow () const
Obtain the active MainWindowBase object.
void manageWindow (QWidget *window, QMenu *windowMenu)
Manage a top-level window.
void unmanageWindow (QWidget *window)
Unmanage a top-level window.
bool isManagedWindow (QWidget *window) const
Determine if a given widget is managed by the application.
QWidget * getManagedWindow (const QString &title) const
Obtain the QWidget with a given name.
void saveWindows ()
Static Public Member Functions
static Logger::Log & Log ()
Log device for instances of this class.
Detailed Description
Manager of an application's 'Window' menu.
The 'Window' menu contains QAction objects that affect the size and visibility of MainWindowBase objects. It also contains a list of the active MainWindowBase objects, and automatically manages shortcut keys for them. Finally, the 'Window' menu contains a submenu that lists all of the active ToolBar objects.
Definition at line 23 of file WindowManager.h.
Constructor & Destructor Documentation
WindowManager::WindowManager (QObject * parent = 0)
Constructor.
There should be only one WindowManager object for an application, but this is not enforced.
Parameters
parent the application owner of this object
Definition at line 23 of file WindowManager.cc.
Member Function Documentation
void WindowManager::addWindowMenuActionTo (ToolBar * toolBar, int index)
Obtain the QAction object found within the shared 'Window' menu.
These are the WindowMenuAction commands listed above.
Parameters
index which action to obtain
Returns
QAction object
Definition at line 31 of file WindowManager.cc.
Referenced by SideCar::GUI::AppBase::setVisibleWindowMenuFullScreen().
MainWindowBase* SideCar::GUI::WindowManager::getActiveMainWindow () const inline
Obtain the active MainWindowBase object.
NOTE: this may be NULL.
Returns
active MainWindowBase object
Definition at line 120 of file WindowManager.h.
Referenced by SideCar::GUI::AppBase::addToolWindow(), SideCar::GUI::AppBase::getActiveMainWindow(), SideCar::GUI::AppBase::showMessage(), and unmanageWindow().
QWidget * WindowManager::getManagedWindow (const QString & title) const
Obtain the QWidget with a given name.
Parameters
title
Returns
Definition at line 103 of file WindowManager.cc.
References SideCar::GUI::MainWindowBase::isRestorable(), Log(), LOGDEBUG, and LOGINFO.
Referenced by SideCar::GUI::AppBase::isManagedWindow().
int SideCar::GUI::WindowManager::getNumManagedWindows () const inline
Obtain the number of open MainWindowBase objects.
Returns
window count
Definition at line 113 of file WindowManager.h.
Referenced by SideCar::GUI::AppBase::getNumManagedWindows().
bool SideCar::GUI::WindowManager::isManagedWindow (QWidget * window) const inline
Determine if a given widget is managed by the application.
Parameters
window the widget to test
Returns
true if so
Definition at line 142 of file WindowManager.h.
Referenced by SideCar::GUI::AppBase::isManagedWindow().
Logger::Log & WindowManager::Log () static
Log device for instances of this class.
Returns
log device
Definition at line 17 of file WindowManager.cc.
References Logger::Log::Find().
Referenced by getManagedWindow(), makeWindowMenu(), manageWindow(), and unmanageWindow().
QMenu * WindowManager::makeWindowMenu (QWidget * parent)
Create the 'Window' menu for a given widget.
The given widget is usually derived from MainWindowBase, but that is not actually necessary.
Parameters
parent the widget to use for ownership
Returns
new QMenu object for the widget
Definition at line 37 of file WindowManager.cc.
References SideCar::GUI::AppBase::GetApp(), Log(), LOGDEBUG, LOGINFO, and SideCar::GUI::MakeMenuAction().
Referenced by SideCar::GUI::AppBase::~AppBase().
void WindowManager::manageWindow (QWidget * window, QMenu * windowMenu)
Manage a top-level window.
Managed windows have their own QAction object installed in the "Window" menu so that the user can make a window active from the menubar or keyboard.
\param window the window to manage
Definition at line 190 of file WindowManager.cc.
References Log(), LOGDEBUG, and LOGINFO.
Referenced by SideCar::GUI::AppBase::manageWindow().
void SideCar::GUI::WindowManager::setVisibleWindowMenuClose (bool visible) inline
Set the visibility state of the "Close" action in the "Window" menu.
Parameters
visible true if visible
Definition at line 85 of file WindowManager.h.
Referenced by SideCar::GUI::AppBase::setVisibleWindowMenuClose().
void SideCar::GUI::WindowManager::setVisibleWindowMenuFullScreen (bool visible) inline
Set the visibility state of the full-screen action in the "Window" menu.
Parameters
visible true if visible
Definition at line 106 of file WindowManager.h.
Referenced by SideCar::GUI::AppBase::setVisibleWindowMenuFullScreen().
void SideCar::GUI::WindowManager::setVisibleWindowMenuMaximize (bool visible) inline
Set the visibility state of the "Maximize" action in the "Window" menu.
Parameters
visible true if visible
Definition at line 99 of file WindowManager.h.
Referenced by SideCar::GUI::AppBase::setVisibleWindowMenuMaximize().
void SideCar::GUI::WindowManager::setVisibleWindowMenuMinimize (bool visible) inline
Set the visibility state of the "Minimize" action in the "Window" menu.
Parameters
visible true if visible
Definition at line 92 of file WindowManager.h.
Referenced by SideCar::GUI::AppBase::setVisibleWindowMenuMinimize().
void SideCar::GUI::WindowManager::setVisibleWindowMenuNew (bool visible) inline
Set the visibility state of the "New" action in the "Window" menu.
Parameters
visible true if visible
Definition at line 78 of file WindowManager.h.
Referenced by SideCar::GUI::AppBase::setVisibleWindowMenuNew().
void WindowManager::showMessage (const QString & msg, int duration) slot
Show a message in the active main window.
Parameters
msg text of the message to show
duration amount of time in milliseconds to show the message; zero shows the message forever until cleared or replaced by another message.
Definition at line 484 of file WindowManager.cc.
void WindowManager::unmanageWindow (QWidget * window)
Unmanage a top-level window.
Usually invoked when a window closes. Removes the associated QAction object from the "Window" menu.
Parameters
window the window to unmanage.
Definition at line 267 of file WindowManager.cc.
References getActiveMainWindow(), SideCar::GUI::AppBase::GetApp(), SideCar::GUI::MainWindowBase::getToolBarMenu(), Log(), LOGDEBUG, LOGERROR, LOGINFO, SideCar::GUI::UpdateToggleAction(), and SideCar::GUI::MainWindowBase::windowMenuAboutToShow().
Referenced by SideCar::GUI::AppBase::unmanageWindow().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/WindowManager.h
/Users/howes/src/sidecar/GUI/WindowManager.cc