SideCar: SideCar::GUI::CLUT Class Reference
SideCar::GUI::CLUT Class Reference
General color lookup table class.
#include </Users/howes/src/sidecar/GUI/CLUT.h>
Public Types
enum Type {
kBlueSaturated, kBone, kCool, kCopper,
kGray, kGreenSaturated, kHot, kHSV,
kJet, kPink, kRedSaturated, kRGB655,
kRGB565, kRGB556, kNumTypes
}
Public Member Functions
CLUT (Type type, GLfloat alpha=1.0)
Constructor.
void setType (Type type)
Change the lookup table use by the CLUT object.
Type getType () const
Obtain the curent table index used by the CLUT objevt.
size_t getSize () const
Color getColor (double normalizedValue) const
Translate an intensity value in the range [0.0-1.0] into a Color objecct containing RGB + alpha values.
const RGBColor & getRGBColor (size_t index) const
Obtain the raw RGB color data from the table used by the CLUT objevt.
const RGBColor & getRGBColor (double normalizedIndex) const
Obtain the raw RGB color data from the table used by the CLUT objevt.
bool hasSaturation () const
void makeColorMapImage (QImage &image, bool showTicks=true)
void makeGradiantImage (QImage &image, const RGBColor &on, bool showTicks=true)
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for CLUT objects.
static const QString & GetTypeName (Type type)
Obtain the display name for a given CLUT::Type value.
static size_t GetSize (Type type)
Obtain the number of entries in each predefined table.
static bool HasSaturation (Type type)
Obtain the display name for a given CLUT::Type value.
static void AddTypeNames (QComboBox *widget)
Detailed Description
General color lookup table class.
Instances provide via getColor(double) a mapping from intensity values in the range [0.0-1.0] into RGB values stored in a Color object. There are kNumTypes predefined tables with different color ramps. The setType() method selects which table a CLUT object uses.
Definition at line 18 of file CLUT.h.
Constructor & Destructor Documentation
CLUT::CLUT (Type type, GLfloat alpha = 1.0)
Constructor.
Parameters
type initial lookup table to use
alpha initial alpha value to use
Definition at line 3014 of file CLUT.cc.
References Log(), and setType().
Member Function Documentation
Color CLUT::getColor (double normalizedValue) const
Translate an intensity value in the range [0.0-1.0] into a Color objecct containing RGB + alpha values.
Parameters
normalizedValue the value to translate
Returns
new Color object
Definition at line 3044 of file CLUT.cc.
References Log(), and LOGDEBUG.
const RGBColor& SideCar::GUI::CLUT::getRGBColor (size_t index) const inline
Obtain the raw RGB color data from the table used by the CLUT objevt.
Parameters
index table entry to fetch
Returns
read-only RGBColor reference
Definition at line 108 of file CLUT.h.
const RGBColor& SideCar::GUI::CLUT::getRGBColor (double normalizedIndex) const inline
Obtain the raw RGB color data from the table used by the CLUT objevt.
Parameters
index table entry to fetch
Returns
read-only RGBColor reference
Definition at line 116 of file CLUT.h.
size_t CLUT::GetSize (Type type) static
Obtain the number of entries in each predefined table.
Parameters
type predefined CLUT to work with
Returns
CLUT size
Definition at line 2989 of file CLUT.cc.
Type SideCar::GUI::CLUT::getType () const inline
Obtain the curent table index used by the CLUT objevt.
Returns
active table index
Definition at line 90 of file CLUT.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::initializeContext().
const QString & CLUT::GetTypeName (Type type) static
Obtain the display name for a given CLUT::Type value.
Parameters
type predefined CLUT to work with
Returns
type name
Definition at line 2983 of file CLUT.cc.
Referenced by SideCar::GUI::Spectrum::ColorMapWidget::ColorMapWidget(), and SideCar::GUI::ColorMapWidget::ColorMapWidget().
bool CLUT::HasSaturation (Type type) static
Obtain the display name for a given CLUT::Type value.
Parameters
type value to convert
Returns
type name
Definition at line 2995 of file CLUT.cc.
Logger::Log & CLUT::Log () static
Obtain the log device for CLUT objects.
Returns
Log device
Definition at line 2976 of file CLUT.cc.
References Logger::Log::Find().
Referenced by CLUT(), and getColor().
void CLUT::setType (Type type)
Change the lookup table use by the CLUT object.
Parameters
type new table index
Definition at line 3022 of file CLUT.cc.
Referenced by CLUT().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/CLUT.h
/Users/howes/src/sidecar/GUI/CLUT.cc