SideCar: SideCar::GUI::AScope::DisplayView Class Reference
SideCar::GUI::AScope::DisplayView Class Reference
Container that hosts a Visualizer widget.
#include </Users/howes/src/sidecar/GUI/AScope/DisplayView.h>
Public Slots
void setHorizontalScaleVisibility (bool value)
Action handler to adjust the visibility of the horizontal scale widget.
void setVerticalScaleVisibility (bool value)
Action handler to adjust the visibility of the vertical scale widget.
void setShowGrid (bool state)
Action handler to control whether grid lines are drawn in the Visualizer background.
void setFrozen (bool state)
void setShowPeakBars (bool state)
Action handler to control whether grid lines are drawn in the Visualizer background.
Signals
void activeDisplayViewChanged (DisplayView *displayView)
Notification sent out when the active DisplayView widget changes.
Public Member Functions
DisplayView (QWidget *parent, AzimuthLatch *azimuthLatch)
Create a new view with initial sprite visibility settings taken from a configuration file.
~DisplayView ()
Destructor.
void saveToSettings (QSettings &settings)
Save current view settings to a configuration settings file.
void restoreFromSettings (QSettings &settings)
Read view settings from a configuration settings file created by a previous run of the AScope program.
void duplicate (const DisplayView *displayView)
Duplicate the view settings of another DisplayView object.
Visualizer * getVisualizer () const
Obtain the held Visualizer object used to show data plots.
bool isHorizontalScaleVisible () const
Determine if the horizontal scale widget is visible.
bool isVerticalScaleVisible () const
Determine if the vertical scale widget is visible.
bool isShowingGrid () const
Determine if the gridlines of the plot are shown.
bool isFrozen () const
bool isShowingPeakBars () const
Determine if the gridlines of the plot are shown.
void setActiveDisplayView ()
Make this DisplayView the active DisplayView object, the one that has focus and whose channel connections are visible in the ChannelConnectionWindow.
Static Public Member Functions
static Logger::Log & Log ()
Detailed Description
Container that hosts a Visualizer widget.
Uses the QFrame base class to show an indicator (frame) when the held Visualizer object has focus. Contains two ScaleWidget objects that provide horizontal and vertical scales next to the Visualizer object. Provides the Visualizer with its background QImage that shows the grid lines created by the ScaleWidget objects.
Definition at line 23 of file DisplayView.h.
Constructor & Destructor Documentation
DisplayView::DisplayView (QWidget * parent, AzimuthLatch * azimuthLatch)
Create a new view with initial sprite visibility settings taken from a configuration file.
Parameters
parent QWidget containing this object
Definition at line 23 of file DisplayView.cc.
Member Function Documentation
void SideCar::GUI::AScope::DisplayView::activeDisplayViewChanged (DisplayView * displayView) signal
Notification sent out when the active DisplayView widget changes.
Parameters
displayView the new active widget
Referenced by setActiveDisplayView(), and ~DisplayView().
void DisplayView::duplicate (const DisplayView * displayView)
Duplicate the view settings of another DisplayView object.
Parameters
displayView the view to copy
Definition at line 65 of file DisplayView.cc.
References LOGINFO.
Referenced by SideCar::GUI::AScope::MainWindow::restoreFromSettings().
Visualizer* SideCar::GUI::AScope::DisplayView::getVisualizer () const inline
Obtain the held Visualizer object used to show data plots.
Returns
Visualizer object
Definition at line 63 of file DisplayView.h.
Referenced by SideCar::GUI::AScope::ChannelConnectionWindow::activeDisplayViewChanged(), SideCar::GUI::AScope::HistoryControlWidget::HistoryControlWidget(), and SideCar::GUI::AScope::MainWindow::restoreFromSettings().
bool DisplayView::isHorizontalScaleVisible () const
Determine if the horizontal scale widget is visible.
Returns
true if so
Definition at line 183 of file DisplayView.cc.
bool DisplayView::isShowingGrid () const
Determine if the gridlines of the plot are shown.
Returns
true if so
Definition at line 231 of file DisplayView.cc.
bool DisplayView::isShowingPeakBars () const
Determine if the gridlines of the plot are shown.
Returns
true if so
Definition at line 237 of file DisplayView.cc.
bool DisplayView::isVerticalScaleVisible () const
Determine if the vertical scale widget is visible.
Returns
true if so
Definition at line 189 of file DisplayView.cc.
void DisplayView::restoreFromSettings (QSettings & settings)
Read view settings from a configuration settings file created by a previous run of the AScope program.
Parameters
settings file to read from
Definition at line 53 of file DisplayView.cc.
References LOGINFO.
Referenced by SideCar::GUI::AScope::MainWindow::MainWindow().
void DisplayView::saveToSettings (QSettings & settings)
Save current view settings to a configuration settings file.
Parameters
settings the file to write to
Definition at line 42 of file DisplayView.cc.
References LOGINFO.
Referenced by SideCar::GUI::AScope::MainWindow::MainWindow().
void DisplayView::setHorizontalScaleVisibility (bool value) slot
Action handler to adjust the visibility of the horizontal scale widget.
Parameters
value visibility value
Definition at line 195 of file DisplayView.cc.
void DisplayView::setShowGrid (bool state) slot
Action handler to control whether grid lines are drawn in the Visualizer background.
Parameters
state true if so
Definition at line 213 of file DisplayView.cc.
void DisplayView::setShowPeakBars (bool state) slot
Action handler to control whether grid lines are drawn in the Visualizer background.
Parameters
state true if so
Definition at line 219 of file DisplayView.cc.
void DisplayView::setVerticalScaleVisibility (bool value) slot
Action handler to adjust the visibility of the vertical scale widget.
Parameters
value visibility value
Definition at line 201 of file DisplayView.cc.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/AScope/DisplayView.h
/Users/howes/src/sidecar/GUI/AScope/DisplayView.cc