SideCar: Logger::Log Class Reference
Logger::Log Class Reference
Master class for the Logger system.
#include </Users/howes/src/sidecar/Logger/Log.h>
Public Types
using ClockSourceRef = boost::shared_ptr< ClockSource >
Change the source of timestamps used in messages.
using NewLogNotifier = boost::function< void(Log &)>
Public Member Functions
~Log ()
Destructor.
const std::string & name () const
Obtain name of the log device.
const std::string & fullName () const
Obtain fully-qualified name of the log device.
void setPriorityLimit (Priority::Level priority)
Assign a new priority level to the Log instance.
void setPropagate (bool propagate)
Set whether message that are emitted by this device are also given to its parent for posting.
bool isHidden () const
Determine if the log is visible in the list of names from GetNames()
size_t getNumChildren () const
Obtain the number of children below this log level.
Log * getChild (size_t index) const
Obtain the child at the given index.
Priority::Level getPriorityLimit () const
Obtain current priority limit of log device.
Priority::Level getMaxPriorityLimit () const
Obtain max priority limit of the log device, which is defined as the max of getPriorityLimit() and getParent().getMaxPriorityLimit().
bool isAccepting (Priority::Level priority) const
Determine if this Log instance is accepting a given Priority level.
Log * getParent () const
Obtain the parent of this log device.
void addWriter (const Writers::Writer::Ref &writer)
Add a new Writer instance to the set of log message writers.
void removeWriter (const Writers::Writer::Ref &writer)
Remove a previously-added Writer instance from the set of log message writers.
void removeAllWriters ()
Remove all Writer objects associated with this Log instance.
int numWriters () const
void flushWriters ()
Ask all registered writers for the log device to write out any unwritten log messages.
void post (Priority::Level priority, const std::string &msg) const
Submit a log message to all of the assigned LogWriters.
bool showsFatal () const
Determine if a `fatal' log message would reach a log device.
bool showsError () const
Determine if a `error' log message would reach a log device.
bool showsWarning () const
Determine if a `warning' log message would reach a log device.
bool showsInfo () const
Determine if an 'info' log message would reach a log device.
bool showsTraceIn () const
Determine if an 'traceIn' log message would reach a log device.
bool showsTraceOut () const
Determine if an 'traceOut' log message would reach a log device.
bool showsDebug1 () const
Determine if a 'debug1' log message would reach a log device.
bool showsDebug2 () const
Determine if a 'debug2' log message would reach a log device.
bool showsDebug3 () const
Determine if a 'debug3' log message would reach a log device.
std::ostream & getStream (Priority::Level priority)
Obtain an output stream to use for a message of a certain priority level.
std::ostream & fatal ()
Obtain output stream for `fatal' log messages.
std::ostream & error ()
Obtain output stream for `error' log messages.
std::ostream & warning ()
Obtain output stream for `warning' log messages.
std::ostream & info ()
Obtain output stream for `info' log messages.
std::ostream & traceIn ()
Obtain output stream for `trace' log messages.
std::ostream & traceOut ()
Obtain output stream for `trace' log messages.
std::ostream & debug1 ()
Obtain output stream for `debug1' log messages.
std::ostream & debug2 ()
Obtain output stream for `debug2' log messages.
std::ostream & debug3 ()
Obtain output stream for `debug3' log messages.
template<typename T >
void thrower (const T &ex)
Generate a `fatal' log message from a exception object, and throw the exception object.
Static Public Member Functions
static ClockSourceRef SetClockSource (const ClockSourceRef &clock)
static ClockSourceRef GetClockSource ()
Get the source of timestamps used in messages.
static Log & Find (const std::string &name, bool hidden=false)
Class method that locates/creates a Log instance under a given name.
static Log & Root ()
Class method that locates/creates the top-level Log instance.
static std::vector< std::string > GetNames ()
Obtain a vector of all the currently known Log device names (these are the full, dot-separated values).
static std::vector< std::string > GetNames (NewLogNotifier observer)
Obtain a vector of all the currently known Log device names (these are the full, dot-separated values), and register a notifier to be called when new Log devices are encountered.
static std::string MakeFullName (const std::string &prefix, const std::string &tail)
Create a proper log path name.
Friends
class LogMap
Detailed Description
Master class for the Logger system.
A Log instance acts as a filter and destination for log messages created by the user. Each log message has an associated Priority value; if the message's priority is less than the Log instance's priority setting, the message is accepted for posting, and is then forwarded to the Writer objects registered for the Log instance. As a result, Log instances do not work directly with log messages, apart from filtering by priority level.
NOTE: most methods below are not thread-safe. The sole exception are Find() and Root(), which rely on a mutex in MakeObj to guarantee that there is a one-to-one correlation between a log device name, and a Log object.
Each Log instance has a parent, which is also a Log instance (the only exception to this is the top-level `root' Log instance.) A log message posted to a child will also propagate up the inheritance hierarchy to each parent.
Log messages are sent to Writer objects that manage a particular device or file. For instance, there is a Writer object that will write log messages to a file, and a Writer object that talks to a syslog daemon. Each Writer object has an associated Formatter object which takes each log message (represented by a Msg object) and generates a textual representation of it.
Log message streams are obtained by calling one of the Log stream-generating methods (fatal, error, warning, info, debug1). For instance, to send a debug-level message, one could do the following
Log::Root().debug1() << "this is a debug message" << std::endl;
There is only one output stream object for all Log objects of a given thread. The stream object accumulates message elements via the '<<' operator until it encounters an `endl' or `flush' manipulator.
When the output stream encounters an std::endl token it calls the LogStreamBuf::sync() method of the stream's LogStreamBuf instance. This method invokes the post() method of the assigned Log device, handing it the accumulated text and the priority level to post at. The post() method in turn creates a Msg object to represent the text string, priority level, and time of posting, which is then passed to the postMsg() method for all Log objects in the parent hierarchy that accept the message's priority level. Finally, postMsg() gives the message to registered writers that do the actual writing of the log message to a log device.
For the best performance, one should conditionalize log message generation with a call to one of the `shows*' methods (eg showsDebug() or showsError()).
if (log.showsDebug1()) log.debug1() << "hi mom!" << std::endl;
For convenience, there are macros that do just this:
LOGDEBUG3
LOGDEBUG2
LOGDEBUG1 (LOGDEBUG)
LOGENTER
LOGEXIT
LOGINFO
LOGWARNING
LOGERROR
LOGFATAL
Using these macros will result in the best performance regardless of log priority level settings. However, they do assume that there is a variable named `log' that refers to a Log instance, such as that returned by the Log::Find() method:
Logger::Log& log = Logger::Log::Find("a.b.c");
LOGDEBUG << "hi mom!" << std::endl;
Definition at line 92 of file Log.h.
Member Typedef Documentation
using Logger::Log::ClockSourceRef = boost::shared_ptr<ClockSource>
Change the source of timestamps used in messages.
NOTE: not thread-safe!
Parameters
clock ClockSource to install
Returns
previous clock source object
Definition at line 102 of file Log.h.
Member Function Documentation
void Log::addWriter (const Writers::Writer::Ref & writer)
Add a new Writer instance to the set of log message writers.
Parameters
writer instance to add
Definition at line 530 of file Log.cc.
Referenced by SideCar::Runner::App::App(), and Logger::Configurator::load().
std::ostream& Logger::Log::debug1 () inline
Obtain output stream for `debug1' log messages.
Returns
output stream
Definition at line 368 of file Log.h.
std::ostream& Logger::Log::debug2 () inline
Obtain output stream for `debug2' log messages.
Returns
output stream
Definition at line 374 of file Log.h.
std::ostream& Logger::Log::debug3 () inline
Obtain output stream for `debug3' log messages.
Returns
output stream
Definition at line 380 of file Log.h.
std::ostream& Logger::Log::error () inline
Obtain output stream for `error' log messages.
Returns
output stream
Definition at line 338 of file Log.h.
std::ostream& Logger::Log::fatal () inline
Obtain output stream for `fatal' log messages.
Returns
output stream
Definition at line 332 of file Log.h.
Log & Log::Find (const std::string & name, bool hidden = false) static
Class method that locates/creates a Log instance under a given name.
The name consists of zero or more parent names, separated by `.' characters. If there are no parent names, the Log instance is assigned as a child to the top-level `root' object.
Parameters
name the name to search for
hidden if true and a new log device is created, it will not appear in the output of GetNames()
Returns
Log instance found/created
Definition at line 353 of file Log.cc.
Referenced by SideCar::GUI::Master::ParamBase::addIfChanged(), SideCar::IO::MulticastDataSubscriber::ReaderThread::close(), SideCar::Algorithms::Controller::close(), SideCar::IO::DatagramReader::fetchInput(), Logger::Configurator::load(), Utils::FileWatcher::Log(), SideCar::IO::Stats::Log(), SideCar::IO::TCPConnector::Log(), SideCar::IO::UDPSocketWriterTask::Log(), SideCar::GUI::DoubleSetting::Log(), SideCar::IO::ClientSocketReaderTask::Log(), SideCar::IO::Decoder::Log(), SideCar::Algorithms::ShutdownMonitor::Log(), SideCar::IO::FileWriterTask::Log(), SideCar::IO::MulticastVMEReaderTask::Log(), SideCar::GUI::Playback::LoaderThread::Log(), SideCar::IO::StateEmitter::Log(), SideCar::IO::TCPInputHandler::Log(), SideCar::IO::TSPIReaderTask::Log(), SideCar::GUI::RTCLMessageReader::Log(), SideCar::Runner::RemoteController::Log(), SideCar::GUI::Spectrum::WorkerThread::Log(), SideCar::Configuration::RunnerConfig::Log(), SideCar::IO::FileReaderTask::Log(), SideCar::IO::TCPDataSubscriber::Log(), SideCar::IO::VMEReaderTask::Log(), SideCar::GUI::QComboBoxSetting::Log(), SideCar::Zeroconf::ASIOMonitor::Log(), SideCar::GUI::ToolWindowBase::Log(), SideCar::GUI::HealthAndStatus::ChannelConnectionModel::Log(), SideCar::IO::ClientSocketWriterTask::Log(), SideCar::IO::DataPublisher::Log(), SideCar::GUI::PPIDisplay::ViewSettings::Log(), SideCar::IO::GatherWriter::Log(), SideCar::GUI::Master::InfoFormatter::Log(), SideCar::GUI::Master::RemoteClient::Log(), SideCar::IO::UDPSocketReaderTask::Log(), SideCar::GUI::BScope::PastImage::Log(), SideCar::Zeroconf::ACEMonitor::Log(), SideCar::IO::DataSubscriber::Log(), SideCar::GUI::Master::LogViewWindow::Log(), SideCar::GUI::Master::LogViewWindowManager::Log(), SideCar::IO::MulticastDataSubscriber::Log(), SideCar::IO::Preamble::Log(), SideCar::Algorithms::MatchedFilterUtils::WorkerThreads::Log(), SideCar::IO::ServerSocketReaderTask::Log(), SideCar::IO::TCPDataPublisher::Log(), SideCar::GUI::PresetsWindow::Log(), Utils::SineCosineLUT::Log(), SideCar::GUI::OffscreenBuffer::Log(), SideCar::GUI::Spectrum::WorkRequest::Log(), SideCar::GUI::ChannelSetting::Log(), SideCar::Algorithms::RemoteControllerBase::Log(), PoolAllocator::Log(), SideCar::Algorithms::MatchedFilterUtils::WorkRequest::Log(), SideCar::GUI::Setting::Log(), SideCar::GUI::MainWindowBase::Log(), SideCar::GUI::AScope::ChannelConnection::Log(), SideCar::IO::ServerSocketWriterTask::Log(), SideCar::GUI::MessageReader::Log(), SideCar::GUI::Playback::MainWindow::Log(), SideCar::GUI::Preset::Log(), SideCar::GUI::ServiceEntry::Log(), SideCar::Zeroconf::Transaction::Log(), SideCar::Messages::Header::Log(), SideCar::Algorithms::ABTrackerUtils::Track::Log(), SideCar::GUI::Spectrum::WeightWindow::Log(), SideCar::IO::RecipientList::Log(), SideCar::GUI::ChannelGroup::Log(), SideCar::Algorithms::Recorder::Log(), SideCar::GUI::AScope::ChannelConnectionWindow::Log(), SideCar::GUI::Master::StatusCollector::Log(), SideCar::Messages::CircularBuffer::Log(), SideCar::GUI::AScope::VideoChannel::Log(), SideCar::GUI::Master::ConfigurationController::Log(), SideCar::IO::StatusEmitterBase::Log(), SideCar::GUI::VertexColorArray::Log(), SideCar::GUI::MulticastMessageReader::Log(), SideCar::Zeroconf::ServiceEntry::Log(), SideCar::Zeroconf::Publisher::Log(), SideCar::GUI::HealthAndStatus::App::Log(), SideCar::GUI::Playback::Emitter::Log(), SideCar::GUI::CLUT::Log(), SideCar::GUI::PPIDisplay::History::Log(), SideCar::GUI::ServiceBrowser::Log(), SideCar::GUI::Master::RecordingController::Log(), SideCar::Messages::RadarConfig::Log(), Utils::RunningMedian::Log(), SideCar::GUI::ZeroconfMonitor::App::Log(), SideCar::GUI::Master::ConfigurationInfo::Log(), SideCar::IO::MulticastDataPublisher::Log(), SideCar::GUI::PRIEmitter::MainWindow::Log(), SideCar::GUI::WindowManager::Log(), SideCar::GUI::AppBase::Log(), SideCar::Zeroconf::Browser::Log(), SideCar::GUI::ESScope::App::Log(), SideCar::GUI::BScope::App::Log(), SideCar::GUI::Spectrum::App::Log(), SideCar::GUI::Master::RunnerLog::Log(), SideCar::Messages::VoidLoaderRegistry::Log(), SideCar::GUI::AScope::ChannelConnectionModel::Log(), SideCar::GUI::PPIDisplay::App::Log(), SideCar::GUI::Playback::FileModel::Log(), SideCar::GUI::AScope::App::Log(), SideCar::Messages::MetaTypeInfo::Log(), SideCar::Algorithms::Controller::Log(), SideCar::Time::TimeStamp::Log(), SideCar::GUI::PPIDisplay::PPIWidget::Log(), SideCar::IO::MessageManager::Log(), SideCar::Messages::PRIMessage::Log(), SideCar::GUI::MessageWriter::Log(), SideCar::Runner::App::Log(), SideCar::IO::Task::Log(), SideCar::IO::Reader::Log(), SideCar::GUI::TCPMessageWriter::Log(), SideCar::IO::Writer::Log(), SideCar::IO::StreamReader::Log(), SideCar::GUI::UDPMessageWriter::Log(), SideCar::IO::DatagramReader::Log(), SideCar::Parameter::Defs::XMLMixin::Log(), SideCar::IO::ClientSocketWriterTask::Make(), SideCar::GUI::Master::PathParam::revertToOriginal(), SideCar::GUI::Master::NotificationParam::revertToOriginal(), SideCar::IO::Channel::updateSenderUsingData(), SideCar::IO::WriterDevices::MulticastSocket::writeToDevice(), and SideCar::GUI::PlotPositionFunctor::~PlotPositionFunctor().
const std::string& Logger::Log::fullName () const inline
Obtain fully-qualified name of the log device.
This includes the names of parents.
Returns
complete device name
Definition at line 169 of file Log.h.
Referenced by Logger::LogMap::add(), RuntimeData::getStream(), and MakeFullName().
Log* Logger::Log::getChild (size_t index) const inline
Obtain the child at the given index.
Parameters
index child to return
Returns
Log object
Definition at line 202 of file Log.h.
ClockSource::Ref Log::GetClockSource () static
Get the source of timestamps used in messages.
If there is not a clock source available, a SystemClockSource object will be created and returned. NOTE: not thread-safe!
\return active clock source
Definition at line 341 of file Log.cc.
References RuntimeData::clock(), and RuntimeData::Singleton().
Priority::Level Logger::Log::getMaxPriorityLimit () const inline
Obtain max priority limit of the log device, which is defined as the max of getPriorityLimit() and getParent().getMaxPriorityLimit().
Returns
priority level
Definition at line 215 of file Log.h.
Referenced by MakeFullName().
std::vector< std::string > Log::GetNames () static
Obtain a vector of all the currently known Log device names (these are the full, dot-separated values).
Returns
known Log names
Definition at line 359 of file Log.cc.
References RuntimeData::logMap(), and RuntimeData::Singleton().
std::vector< std::string > Log::GetNames (NewLogNotifier observer) static
Obtain a vector of all the currently known Log device names (these are the full, dot-separated values), and register a notifier to be called when new Log devices are encountered.
Returns
known Log names
Definition at line 365 of file Log.cc.
References Logger::LogMap::add(), Utils::Exception::err(), Logger::LogMap::find(), RuntimeData::logMap(), and RuntimeData::Singleton().
size_t Logger::Log::getNumChildren () const inline
Obtain the number of children below this log level.
Returns
number of children
Definition at line 194 of file Log.h.
Log* Logger::Log::getParent () const inline
Obtain the parent of this log device.
Returns
parent Log object, or NULL if this is the root Log device.
Definition at line 229 of file Log.h.
Priority::Level Logger::Log::getPriorityLimit () const inline
Obtain current priority limit of log device.
Returns
priority level
Definition at line 208 of file Log.h.
std::ostream & Log::getStream (Priority::Level priority)
Obtain an output stream to use for a message of a certain priority level.
All Log instances in the same thread share the same output stream. If no log device would write out a message at the given priority level, an `null' output stream is returned, one that is setup to not do any writing.
\param level priority level of the next log message written to the stream.
Returns
output stream
Definition at line 560 of file Log.cc.
References RuntimeData::getStream(), and RuntimeData::Singleton().
std::ostream& Logger::Log::info () inline
Obtain output stream for `info' log messages.
Returns
output stream
Definition at line 350 of file Log.h.
bool Logger::Log::isAccepting (Priority::Level priority) const inline
Determine if this Log instance is accepting a given Priority level.
Parameters
priority priority level to check for
Returns
true if accepted
Definition at line 223 of file Log.h.
Referenced by RuntimeData::getStream().
bool Logger::Log::isHidden () const inline
Determine if the log is visible in the list of names from GetNames()
Returns
current value
Definition at line 188 of file Log.h.
Referenced by Logger::LogMap::add().
std::string Log::MakeFullName (const std::string & prefix, const std::string & tail) static
Create a proper log path name.
Parameters
prefix the prefix of the full name
tail the tail of the full name
Returns
new name
Definition at line 408 of file Log.cc.
References fullName(), getMaxPriorityLimit(), and Threading::Mutex::Make().
const std::string& Logger::Log::name () const inline
Obtain name of the log device.
Does not contain names of parents.
Returns
short device name
Definition at line 163 of file Log.h.
Referenced by Logger::Configurator::ConfiguratorException< MissingNumVersions >::ConfiguratorException().
int Log::numWriters () const
Returns
the number of registered Writer objects
Definition at line 553 of file Log.cc.
void Log::post (Priority::Level priority, const std::string & msg) const
Submit a log message to all of the assigned LogWriters.
Does nothing if the given message level is greater than the priority setting of this instance or any parent priority settings.
Parameters
priority severity level of the log message
msg text of the log message
Definition at line 566 of file Log.cc.
References Logger::Msg::when_.
Referenced by Logger::LogStreamBuf::~LogStreamBuf().
void Log::removeWriter (const Writers::Writer::Ref & writer)
Remove a previously-added Writer instance from the set of log message writers.
Parameters
writer instance to remove
Definition at line 539 of file Log.cc.
Referenced by SideCar::Runner::App::~App().
Log & Log::Root () static
Class method that locates/creates the top-level Log instance.
Returns
top-level Log instance
Definition at line 347 of file Log.cc.
Referenced by SideCar::Runner::App::App(), SideCar::GUI::AppBase::AppBase(), ConverterInputTask::deliverDataMessage(), PRIInfoInputTask::deliverDataMessage(), InputTask::deliverDataMessage(), PRIChunkerOutputTask::deliverDataMessage(), and SideCar::Runner::App::~App().
void Log::setPriorityLimit (Priority::Level priority)
Assign a new priority level to the Log instance.
Parameters
priority new level to use
Definition at line 492 of file Log.cc.
Referenced by SideCar::Runner::App::App(), SideCar::GUI::AppBase::AppBase(), SideCar::Algorithms::Controller::close(), ConverterInputTask::deliverDataMessage(), PRIInfoInputTask::deliverDataMessage(), InputTask::deliverDataMessage(), PRIChunkerOutputTask::deliverDataMessage(), and Logger::Configurator::load().
void Logger::Log::setPropagate (bool propagate) inline
Set whether message that are emitted by this device are also given to its parent for posting.
The default for new Log devices is true.
Parameters
propagate true if propagating
Definition at line 182 of file Log.h.
Referenced by Logger::Configurator::load().
bool Logger::Log::showsDebug1 () const inline
Determine if a 'debug1' log message would reach a log device.
Returns
true if so
Definition at line 304 of file Log.h.
bool Logger::Log::showsDebug2 () const inline
Determine if a 'debug2' log message would reach a log device.
Returns
true if so
Definition at line 310 of file Log.h.
bool Logger::Log::showsDebug3 () const inline
Determine if a 'debug3' log message would reach a log device.
Returns
true if so
Definition at line 316 of file Log.h.
bool Logger::Log::showsError () const inline
Determine if a `error' log message would reach a log device.
Returns
true if so
Definition at line 274 of file Log.h.
bool Logger::Log::showsFatal () const inline
Determine if a `fatal' log message would reach a log device.
Returns
true if so
Definition at line 268 of file Log.h.
bool Logger::Log::showsInfo () const inline
Determine if an 'info' log message would reach a log device.
Returns
true if so
Definition at line 286 of file Log.h.
bool Logger::Log::showsTraceIn () const inline
Determine if an 'traceIn' log message would reach a log device.
Returns
true if so
Definition at line 292 of file Log.h.
bool Logger::Log::showsTraceOut () const inline
Determine if an 'traceOut' log message would reach a log device.
Returns
true if so
Definition at line 298 of file Log.h.
bool Logger::Log::showsWarning () const inline
Determine if a `warning' log message would reach a log device.
Returns
true if so
Definition at line 280 of file Log.h.
template<typename T > void Logger::Log::thrower (const T & ex) inline
Generate a `fatal' log message from a exception object, and throw the exception object.
As such, it will not return...
\param ex exception to log and throw
Definition at line 388 of file Log.h.
std::ostream& Logger::Log::traceIn () inline
Obtain output stream for `trace' log messages.
Returns
output stream
Definition at line 356 of file Log.h.
std::ostream& Logger::Log::traceOut () inline
Obtain output stream for `trace' log messages.
Returns
output stream
Definition at line 362 of file Log.h.
std::ostream& Logger::Log::warning () inline
Obtain output stream for `warning' log messages.
Returns
output stream
Definition at line 344 of file Log.h.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Logger/Log.h
/Users/howes/src/sidecar/Logger/Log.cc