SideCar: SideCar::Geometry::UnitVector Class Reference
SideCar::Geometry::UnitVector Class Reference
Tuple representing a unit vector in 3-D space.
#include </Users/howes/src/sidecar/Algorithms/ABTracker/UnitVector.h>
Public Member Functions
UnitVector ()
Default constructor.
UnitVector (double direction, double elevation)
Constructor using direction and elevation angles.
UnitVector (const Vector &vector)
Conversion constructor from a Vector.
double getDirection () const
Obtain the angle in radians of the vector in the X/Y plane and the Y axis (north)
double getElevation () const
Obtain the angle in radians of the vector in the Z/Y plane and the Y axis (0 elevation).
double getX () const
Obtain the X component.
double getY () const
Obtain the Y component.
double getZ () const
Obtain the Z component.
Detailed Description
Tuple representing a unit vector in 3-D space.
A unit vector always has a magnitude of 1. Borrowed from RWSL project. Calculates on demand component (X,Y,Z) values.
Definition at line 14 of file UnitVector.h.
Constructor & Destructor Documentation
UnitVector::UnitVector (double direction, double elevation)
Constructor using direction and elevation angles.
Parameters
direction angle in radians of the vector in the X/Y plane and the Y axis (north)
elevation angle in radians of the vector in the Z/Y plane and the Y axis
Definition at line 14 of file UnitVector.cc.
UnitVector::UnitVector (const Vector & vector)
Conversion constructor from a Vector.
Parameters
vector value to work with
Definition at line 21 of file UnitVector.cc.
Member Function Documentation
double SideCar::Geometry::UnitVector::getDirection () const inline
Obtain the angle in radians of the vector in the X/Y plane and the Y axis (north)
Returns
angle in radians
Definition at line 42 of file UnitVector.h.
double SideCar::Geometry::UnitVector::getElevation () const inline
Obtain the angle in radians of the vector in the Z/Y plane and the Y axis (0 elevation).
A well-formed unit vector would only have values in [0-PI/4].
Returns
angle in radians
Definition at line 49 of file UnitVector.h.
References getX(), getY(), and getZ().
double UnitVector::getX () const
Obtain the X component.
Value in [0-1]
Returns
length along X axis
Definition at line 28 of file UnitVector.cc.
Referenced by getElevation().
double UnitVector::getY () const
Obtain the Y component.
Value in [0-1]
Returns
length along Y axis
Definition at line 39 of file UnitVector.cc.
Referenced by getElevation().
double UnitVector::getZ () const
Obtain the Z component.
Value in [0-1]
Returns
length along Z axis
Definition at line 50 of file UnitVector.cc.
Referenced by getElevation().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/ABTracker/UnitVector.h
/Users/howes/src/sidecar/Algorithms/ABTracker/UnitVector.cc