SideCar: SideCar::GUI::TargetPlotImaging Class Reference
SideCar::GUI::TargetPlotImaging Class Reference
Extension of the ChannelImaging class that contains display settings for target plots.
#include </Users/howes/src/sidecar/GUI/TargetPlotImaging.h>
Data Structures
struct SymbolInfo
Public Types
enum SymbolType {
kCross, kCrossSquare, kDiamondFilled, kDiamondHollow,
kPlus, kPlusDiamond, kSquareFilled, kSquareHollow,
kTriangleFilled, kTriangleHollow, kDaggerFilled, kDaggerHollow,
kNumSymbolTypes
}
Enumeration of the various symbol types available to depict target plots.
Public Slots
void clearSymbolPoints ()
Signals
void lifeTimeChanged (int msecs)
Notification sent out when the lifetime setting changes.
Signals inherited from SideCar::GUI::ChannelImaging
void colorChanged ()
Notification sent out when the color setting changes.
void sizeChanged ()
Notification sent out when the size setting changes.
void alphaChanged ()
Notification sent out when the size setting changes.
Signals inherited from SideCar::GUI::OnOffSettingsBlock
void enabledChanged (bool state)
Notification sent out when the enabled state has changed.
Signals inherited from SideCar::GUI::SettingsBlock
void settingChanged ()
Notification sent out when a registered value has changed.
Public Member Functions
TargetPlotImaging (PlotPositionFunctor *plotPositionFunctor, BoolSetting *visible, ColorButtonSetting *color, DoubleSetting *extent, OpacitySetting *opacity, QComboBoxSetting *symbolType, DoubleSetting *lineWidth, IntSetting *lifeTime, BoolSetting *fadeEnabled, BoolSetting *showTrails=0, IntSetting *tagSize=0, BoolSetting *showTags=0)
void setPlotPositionFunctor (PlotPositionFunctor *plotPositionFunctor)
float getExtent () const
Obtain the extent size of the symbols.
float getExtent2 () const
Obtain half the extent size.
SymbolType getSymbolType () const
Obtain the current symbol type.
float getLineWidth () const
Obtain the current symbol line width.
int getLifeTime () const
Obtain the current plot lifetime, the number of milliseconds that a plot will display after its creation.
void fadeColor (Color &color, int age) const
Obtain the time-degraded opacity value for the target.
bool getFadeEnabled () const
Determine if plot fading is enabled.
void render (QWidget *widget, const TargetPlotList &targets)
Render plot symbols at the given locations.
void render (QWidget *widget, const TargetPlotListList &targets)
void connectPlotSymbolWidget (PlotSymbolWidget *widget)
void addSymbolIcons (QComboBox *widget) const
Public Member Functions inherited from SideCar::GUI::ChannelImaging
ChannelImaging (BoolSetting *enabled, ColorButtonSetting *color, DoubleSetting *size, OpacitySetting *opacity)
Constructor.
const QColor & getQColor () const
Obtain the current pen color setting as a Qt QColor value.
const Color & getColor () const
Obtain the current pen color setting as a SideCar::GUI::Color value.
float getSize () const
Obtain the current pen point/line size.
float getAlpha () const
Obtain the current alpha (opacity) value.
Public Member Functions inherited from SideCar::GUI::OnOffSettingsBlock
OnOffSettingsBlock (BoolSetting *enabled)
Constructor.
bool isEnabled () const
Determine if the settings block is enabled.
void toggleEnabled ()
Toggle the enabled state of this settings block.
void setToggleEnabledAction (QAction *action)
Install a QAction object to control the on/off state of the settings block.
void connectWidget (QCheckBox *widget)
Public Member Functions inherited from SideCar::GUI::SettingsBlock
SettingsBlock (QObject *parent=0)
Constructor.
Static Public Member Functions
static Logger::Log & Log ()
static const QString & GetSymbolName (SymbolType symbolType)
static const SymbolInfo & GetSymbolInfo (SymbolType symbolType)
Additional Inherited Members
Protected Slots inherited from SideCar::GUI::ChannelImaging
virtual void colorChanged (const QColor &color)
virtual void sizeChanged (double size)
virtual void opacityChanged (double opacity)
Protected Slots inherited from SideCar::GUI::SettingsBlock
virtual void postSettingChanged ()
Notification handler invoked when a Setting object that was registered with one of the add() methods emits its valueChanged() signal.
virtual void emitSettingChanged ()
Notification handler invoked when the QTimer object registered by the postSettingChanged() method fires.
Protected Member Functions inherited from SideCar::GUI::SettingsBlock
void add (Setting *setting)
Relate a Setting object to this SettingsBlock object.
Detailed Description
Extension of the ChannelImaging class that contains display settings for target plots.
Definition at line 58 of file TargetPlotImaging.h.
Member Function Documentation
void SideCar::GUI::TargetPlotImaging::fadeColor (Color & color, int age) const inline
Obtain the time-degraded opacity value for the target.
As time passes, the opacity decreases, thus fading the plot.
Parameters
alpha the initiali value to fade
age the plot age
Returns
Definition at line 147 of file TargetPlotImaging.h.
float SideCar::GUI::TargetPlotImaging::getExtent () const inline
Obtain the extent size of the symbols.
This is roughly equal to the diameter of a circle that circumscribes the plot symbol. Rename of the ChannelImaging::getSize() method to better reflect how the setting is used in the TargetPlotImaging class.
Returns
extent size
Definition at line 110 of file TargetPlotImaging.h.
float SideCar::GUI::TargetPlotImaging::getExtent2 () const inline
Obtain half the extent size.
This is roughly equal to the radius of a circle that circumscribes the plot symbol.
Returns
getExtent() / 2
Definition at line 117 of file TargetPlotImaging.h.
bool SideCar::GUI::TargetPlotImaging::getFadeEnabled () const inline
Determine if plot fading is enabled.
If it is, plot representations will have decreasing alpha values as they age.
Returns
true if enabled
Definition at line 154 of file TargetPlotImaging.h.
int SideCar::GUI::TargetPlotImaging::getLifeTime () const inline
Obtain the current plot lifetime, the number of milliseconds that a plot will display after its creation.
Returns
duration in milliseconds
Definition at line 136 of file TargetPlotImaging.h.
Referenced by SideCar::GUI::PPIDisplay::App::App().
float SideCar::GUI::TargetPlotImaging::getLineWidth () const inline
Obtain the current symbol line width.
Used by symbol types kCross and kPlus.
Returns
line width
Definition at line 129 of file TargetPlotImaging.h.
SymbolType SideCar::GUI::TargetPlotImaging::getSymbolType () const inline
Obtain the current symbol type.
Returns
symbol type
Definition at line 123 of file TargetPlotImaging.h.
void SideCar::GUI::TargetPlotImaging::lifeTimeChanged (int msecs) signal
Notification sent out when the lifetime setting changes.
Parameters
msecs
void TargetPlotImaging::render (QWidget * widget, const TargetPlotList & targets)
Render plot symbols at the given locations.
Parameters
targets list of plots to render
Definition at line 234 of file TargetPlotImaging.cc.
References SideCar::GUI::VertexColorArray::draw(), SideCar::GUI::TargetPlot::getAge(), SideCar::GUI::TargetPlot::getTag(), LOGDEBUG, SideCar::GUI::ProjectPoint(), SideCar::GUI::VertexColorTagArray::push_back(), SideCar::GUI::VertexColorArray::push_back(), and SideCar::GUI::VertexColorArray::size().
Referenced by SideCar::GUI::BScope::PPIWidget::PPIWidget(), SideCar::GUI::PPIDisplay::PPIWidget::processBugPlots(), and SideCar::GUI::ESScope::XYWidget::XYWidget().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/TargetPlotImaging.h
/Users/howes/src/sidecar/GUI/TargetPlotImaging.cc