SideCar: SideCar::GUI::PPIDisplay::History Class Reference
SideCar::GUI::PPIDisplay::History Class Reference
Container for collections of SideCar messages, grouped by revolution.
#include </Users/howes/src/sidecar/GUI/PPIDisplay/History.h>
Data Structures
class Entry
Collection of Video & Extraction objects for one revolution of the radar.
Public Types
using MessageVector = std::vector< Messages::PRIMessage::Ref >
Public Slots
void setEnabled (bool enabled)
Change whether retention is enabled.
void setRetentionSize (int retention)
Change the number of revolutions retained.
void showLiveEntry ()
Change the viewing state so that live data is visible.
void showEntry (int slot)
Change the viewing state so that the indicated past revolution is visible.
void setExtractionsLifeTime (int msecs)
void setRangeTruthsLifeTime (int msecs)
void setRangeTruthsMaxTrailLength (int length)
void setBugPlotsLifeTime (int msecs)
void clearAll ()
Erase all of the data in the live and pending views.
void clearVideo ()
void clearBinary ()
void clearExtractions ()
void clearRangeTruths ()
void clearBugPlots ()
Signals
void currentViewChanged (int age)
void currentViewAged (int age)
void retainedCountChanged (int retained)
Public Member Functions
History (QObject *parent, size_t retentionSize, bool enabled)
Constructor.
Messages::Video::DatumType getVideoValue (double azimuth, double range, bool &isValid) const
Messages::BinaryVideo::DatumType getBinaryValue (double azimuth, double range, bool &isValid) const
bool isEnabled () const
Determine if retention is enabled.
int getRetentionSize () const
Obtain the number of revolutions retained.
int getEntryAge () const
int getRetentionCount () const
bool showingLiveEntry () const
Determine if the user is viewing live data.
bool showingPastEntry () const
Determine if the user is viewing historical data.
const Entry & getViewedEntry () const
Obtain a reference to the Entry being viewed by the user.
void addVideo (const Messages::Video::Ref &msg)
Add a Video object to the live view, and possibly to a retained view if enabled.
void addBinary (const Messages::BinaryVideo::Ref &msg)
Add a BinaryVideo object the the live view.
void addExtractions (const Messages::Extractions::Ref &msg)
Add an Extractions object to the live view, and possibly to a retained view if enabled.
void addRangeTruth (const Messages::TSPI::Ref &msg)
Add a RangeTruth object to the live view, and possibly to a retained view if enabled.
void addBugPlot (const Messages::BugPlot::Ref &msg)
Add one TargetPlot object to the live view, and possibly to a retained view if enabled.
Static Public Member Functions
static Logger::Log & Log ()
Log device to use for History messages.
Detailed Description
Container for collections of SideCar messages, grouped by revolution.
As messages come in, they are added to live and pending Entry objects. When a complete revolution is detected, the pending Entry is placed at the front of the retained Entry queue, thus becoming the most-recent historical entry. The oldest Entry object is then popped off the back of the queue, keeping the queue a constant size, and the popped off Entry object becomes the new pending object.
Definition at line 32 of file History.h.
Constructor & Destructor Documentation
History::History (QObject * parent, size_t retentionSize, bool enabled)
Constructor.
Parameters
retentionSize number of revolutions to retain
enabled whether retention is enabled
Definition at line 387 of file History.cc.
Member Function Documentation
void History::addBinary (const Messages::BinaryVideo::Ref & msg)
Add a BinaryVideo object the the live view.
and possibly to a retained view if enabled.
Parameters
msg message to add
Definition at line 523 of file History.cc.
References SideCar::GUI::PPIDisplay::History::Entry::hasVideo().
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::processBinary().
void History::addBugPlot (const Messages::BugPlot::Ref & msg)
Add one TargetPlot object to the live view, and possibly to a retained view if enabled.
This is from a user clicking on the screen.
Parameters
msg message to add
Definition at line 551 of file History.cc.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::changeZoom(), SideCar::GUI::PPIDisplay::MagnifierView::MagnifierView(), and SideCar::GUI::PPIDisplay::PPIWidget::processBugPlots().
void History::addExtractions (const Messages::Extractions::Ref & msg)
Add an Extractions object to the live view, and possibly to a retained view if enabled.
Parameters
msg message to add
Definition at line 533 of file History.cc.
References SideCar::GUI::PPIDisplay::History::Entry::hasVideo().
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::processExtractions().
void History::addRangeTruth (const Messages::TSPI::Ref & msg)
Add a RangeTruth object to the live view, and possibly to a retained view if enabled.
Parameters
msg message to add
Definition at line 543 of file History.cc.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::processRangeTruths().
void History::addVideo (const Messages::Video::Ref & msg)
Add a Video object to the live view, and possibly to a retained view if enabled.
Parameters
msg message to add
Definition at line 436 of file History.cc.
References SideCar::GUI::PPIDisplay::History::Entry::clearAll(), SideCar::IO::MessageManager::GetAllocationStats(), SideCar::GUI::PPIDisplay::History::Entry::getBinary(), SideCar::GUI::PPIDisplay::History::Entry::getVideo(), Log(), LOGDEBUG, LOGINFO, and SideCar::IO::MessageManager::AllocationStats::messageBlocks.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::processVideo().
void History::clearAll () slot
Erase all of the data in the live and pending views.
Existing historical data is NOT erased.
Definition at line 615 of file History.cc.
References SideCar::GUI::PPIDisplay::History::Entry::clearAll().
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::clearAll().
int SideCar::GUI::PPIDisplay::History::getRetentionSize () const inline
Obtain the number of revolutions retained.
Returns
retention count
Definition at line 205 of file History.h.
const Entry& SideCar::GUI::PPIDisplay::History::getViewedEntry () const inline
Obtain a reference to the Entry being viewed by the user.
Returns
Entry reference
Definition at line 227 of file History.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::processBugPlots(), SideCar::GUI::PPIDisplay::PPIWidget::redisplayBinary(), SideCar::GUI::PPIDisplay::PPIWidget::redisplayVideo(), and SideCar::GUI::PPIDisplay::PPIWidget::renderScene().
bool SideCar::GUI::PPIDisplay::History::isEnabled () const inline
Determine if retention is enabled.
Returns
true if so
Definition at line 199 of file History.h.
Logger::Log & History::Log () static
Log device to use for History messages.
Returns
Logger::Log reference
Definition at line 381 of file History.cc.
References Logger::Log::Find().
Referenced by addVideo(), SideCar::GUI::PPIDisplay::History::Entry::clearAll(), showEntry(), and showLiveEntry().
void History::setEnabled (bool enabled) slot
Change whether retention is enabled.
Parameters
enabled new retention state
Definition at line 663 of file History.cc.
References showLiveEntry().
Referenced by SideCar::GUI::PPIDisplay::App::App().
void History::setRetentionSize (int retention) slot
Change the number of revolutions retained.
Parameters
retentionSize new value
Definition at line 397 of file History.cc.
Referenced by SideCar::GUI::PPIDisplay::App::App().
void History::showEntry (int slot) slot
Change the viewing state so that the indicated past revolution is visible.
Parameters
offset revolution in the past to view
Definition at line 574 of file History.cc.
References Log(), LOGDEBUG, LOGERROR, LOGINFO, and showLiveEntry().
bool SideCar::GUI::PPIDisplay::History::showingLiveEntry () const inline
Determine if the user is viewing live data.
Returns
true if so
Definition at line 215 of file History.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::processBinary(), SideCar::GUI::PPIDisplay::PPIWidget::processVideo(), and SideCar::GUI::PPIDisplay::PPIWidget::renderScene().
bool SideCar::GUI::PPIDisplay::History::showingPastEntry () const inline
Determine if the user is viewing historical data.
Returns
true if so
Definition at line 221 of file History.h.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/PPIDisplay/History.h
/Users/howes/src/sidecar/GUI/PPIDisplay/History.cc