SideCar: SideCar::Time::TimeStampRange Class Reference
SideCar::Time::TimeStampRange Class Reference
Representation of a span of time.
#include </Users/howes/src/sidecar/Time/TimeStampRange.h>
Data Structures
struct InvalidRange
Exception thrown if a range is invalid (start > end).
Public Member Functions
TimeStampRange (const TimeStamp &start, const TimeStamp &end)
Constructor.
bool operator< (const TimeStampRange &rhs) const
Less-than order operator.
const TimeStamp & getStart () const
Obtain the start time of the range.
const TimeStamp & getEnd () const
Obtain the end time of the range.
bool contains (const TimeStamp &when) const
Determine if a given TimeStamp value falls between the start end end times of a range, inclusive.
Static Public Member Functions
static TimeStampRange Make (const std::string &spec)
Factory method that converts a range specification in a string into a TimeStampRange object.
Detailed Description
Representation of a span of time.
Use the TimeStampRange::Make() class method to convert string range specifications into TimeStampRange objects. Use TimeStampRange::contains() to check if a TimeStamp is within a given range. Defines the less-than operator so TimeStampRange instances may be stored in ordered containers, such as std::set or std::map. The class TimeStampRangeSet is an enhanced std:set container for TimeStampRanges.
Definition at line 18 of file TimeStampRange.h.
Constructor & Destructor Documentation
TimeStampRange::TimeStampRange (const TimeStamp & start, const TimeStamp & end)
Constructor.
Parameters
start start of the time range
end end of the time range
Definition at line 39 of file TimeStampRange.cc.
Referenced by Make().
Member Function Documentation
bool SideCar::Time::TimeStampRange::contains (const TimeStamp & when) const inline
Determine if a given TimeStamp value falls between the start end end times of a range, inclusive.
Parameters
when value to check
Returns
true if contained
Definition at line 76 of file TimeStampRange.h.
const TimeStamp& SideCar::Time::TimeStampRange::getEnd () const inline
Obtain the end time of the range.
Returns
TimeStamp reference
Definition at line 68 of file TimeStampRange.h.
const TimeStamp& SideCar::Time::TimeStampRange::getStart () const inline
Obtain the start time of the range.
Returns
TimeStamp reference
Definition at line 62 of file TimeStampRange.h.
TimeStampRange TimeStampRange::Make (const std::string & spec) static
Factory method that converts a range specification in a string into a TimeStampRange object.
A specification may be in one of the following formats: - START-END - create a range of spanning START and END times - END - create a range from TimeStamp::Min() to END - START- - create a range from START to TimeStamp::Max() If the format is invalid, this routine throws a std::runtime_error exception.
Parameters
spec specification to parse
Returns
TimeStampRange instance
Definition at line 11 of file TimeStampRange.cc.
References SideCar::Time::TimeStamp::Max(), SideCar::Time::TimeStamp::Min(), and TimeStampRange().
bool SideCar::Time::TimeStampRange::operator< (const TimeStampRange & rhs) const inline
Less-than order operator.
A range is considered "smaller" than another one if its start time is less than the other, or the start times are the same, but the end time is less than the other.
Parameters
rhs instance to compare with
Returns
true if less than given value
Definition at line 55 of file TimeStampRange.h.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Time/TimeStampRange.h
/Users/howes/src/sidecar/Time/TimeStampRange.cc