SideCar: SideCar::Parameter::TValue< ParamDef > Class Template Reference
SideCar::Parameter::TValue< ParamDef > Class Template Reference
A template definition for a named parameter value.
#include </Users/howes/src/sidecar/Parameter/Parameter.h>
Public Types
using Self = TValue< ParamDef >
Our own type.
using ValueType = typename ParamDef::ValueType
The type of the value we hold.
using ReferenceType = typename ParamDef::ReferenceType
A read-write reference to a ValueType value.
using ConstReferenceType = typename ParamDef::ConstReferenceType
A read-only reference to a ValueType value.
using Ref = boost::shared_ptr< Self >
Type to use when sharing parameter objects.
using ChangedSignal = boost::signals2::signal< void(const Self &)>
Method/function specification for notifcations.
using ChangedSignalProc = typename ChangedSignal::slot_function_type
Value type for observer objects which get called when a Parameter object changes.
using SignalConnection = boost::signals2::connection
Value type for signal connections.
Public Member Functions
bool isValid (ConstReferenceType value) const
Determines if the given value is valid for the parameter.
ConstReferenceType getValue () const
Obtain the parameter's current value.
ConstReferenceType getOriginal () const
Obtain the parameter's original setting.
bool isNotOriginal () const override
Determine if the current value differs from the original setting.
void setValue (ConstReferenceType value)
Give the parameter a new value.
void setOriginal (ConstReferenceType value)
Give the parameter a new original (and current) value.
void setXMLValue (XmlRpc::XmlRpcValue &value) override
Give the parameter a new value taken from an XLM/RPC parameter.
void setXMLOriginal (XmlRpc::XmlRpcValue &value) override
Give the parameter a new original (and current) value taken from an XLM/RPC parameter.
void revert ()
Revert the parameter value to its original value.
Self & operator= (ConstReferenceType rhs)
Assignment operator.
Self & operator= (Self &rhs)
Assignment operator.
std::istream & load (std::istream &is) override
Obtain a new parameter value from a C++ input stream.
ACE_InputCDR & load (ACE_InputCDR &cdr) override
Obtain a new parameter value from an ACE CDR input stream.
bool checkedLoad (ACE_InputCDR &cdr) override
Same as the load() method, but an exception is never thrown.
std::ostream & save (std::ostream &os) const override
Write out to a C++ output stream the parameter name and value.
ACE_OutputCDR & write (ACE_OutputCDR &cdr) const override
Write out to an ACE CDR output stream the parameter name and value.
SignalConnection connectChangedSignalTo (ChangedSignalProc observer)
Add an observer to this property's value state.
void describe (XmlRpc::XmlRpcValue &xml) const override
Implementation of ValueBase interface.
Public Member Functions inherited from SideCar::Parameter::ValueBase
ValueBase (const std::string &name, const std::string &label)
Constructor.
virtual ~ValueBase ()=default
Destructor.
const std::string & getName () const
Obtain the XML name of the parameter.
const std::string & getLabel () const
Obtain the GUI label of the parameter.
bool isAdvanced () const
Determine if the parameter is 'advanced', and not shown to the user by default.
void setAdvanced (bool state)
Change the parameter's advanced designation.
bool isEditable () const
Determine if the parameter is editable by the user.
void setEditable (bool state)
Change the parameter's editable designation.
Static Public Member Functions
static Ref Make (const std::string &name, const std::string &label)
Factory method to create shareable parameter objects.
static Ref Make (const std::string &name, const std::string &label, ConstReferenceType value)
Factory method to create shareable parameter objects with an initial value.
Protected Member Functions
TValue (const std::string &name, const std::string &label)
Constructor.
TValue (const std::string &name, const std::string &label, ConstReferenceType value)
Constructor.
Detailed Description
template<typename ParamDef>
class SideCar::Parameter::TValue< ParamDef >
A template definition for a named parameter value.
The sole template parameter defines the capabilities available to the template class. The definition object must contain the following items:
ValueType: declaration of the type used to hold a parameter value.
ReferenceType: declaration for a non-const reference to the value.
ConstReferenceType: declaration for a const reference to the value.
IsValid: method that should return true if the value it is given is OK.
Load: read the parameter value from a C++ input stream.
Save: write out the parameter name and value to a C++ output stream.
Load: read the parameter value from an ACE CDR input stream.
Write: write out the parameter name and value to an ACE CDR output stream.
GetXMLTypeName: obtain the XML-RPC type designator
FromXML: convert an XML-RPC value into a native value
DescribeXML: fill in an XML-RPC struct with a description of the parameter (name, type, value)
Definition at line 212 of file Parameter.h.
Member Typedef Documentation
template<typename ParamDef > using SideCar::Parameter::TValue< ParamDef >::ChangedSignal = boost::signals2::signal<void (const Self&)>
Method/function specification for notifcations.
Each method receives a reference to ourselves.
Definition at line 238 of file Parameter.h.
Constructor & Destructor Documentation
template<typename ParamDef > SideCar::Parameter::TValue< ParamDef >::TValue (const std::string & name, const std::string & label) inline protected
Constructor.
Intialize with name and default value of ValueType().
Parameters
name name of the parameter
label the text string to use in a GUI showing this value
Definition at line 501 of file Parameter.h.
template<typename ParamDef > SideCar::Parameter::TValue< ParamDef >::TValue (const std::string & name, const std::string & label, ConstReferenceType value) inline protected
Constructor.
Intialize with name and initial value. NOTE: there is no validation of initial value.
Parameters
name name of the parameter
label the text string to use in a GUI showing this value
value initial parameter value
Definition at line 513 of file Parameter.h.
Member Function Documentation
template<typename ParamDef > bool SideCar::Parameter::TValue< ParamDef >::checkedLoad (ACE_InputCDR & cdr) inline override virtual
Same as the load() method, but an exception is never thrown.
The return value indicates whether the value taken from the input stream was OK
Parameters
cdr stream to read from
Returns
true if successful, false otherwise
Implements SideCar::Parameter::ValueBase.
Definition at line 446 of file Parameter.h.
template<typename ParamDef > SignalConnection SideCar::Parameter::TValue< ParamDef >::connectChangedSignalTo (ChangedSignalProc observer) inline
Add an observer to this property's value state.
When the value changes, the observer will receive notification. To disconnect a connection, invoke the disconnect() method of the returned value.
Parameters
observer object to register
Returns
connection identifier for the observer.
Definition at line 481 of file Parameter.h.
template<typename ParamDef > void SideCar::Parameter::TValue< ParamDef >::describe (XmlRpc::XmlRpcValue & xml) const inline override virtual
Implementation of ValueBase interface.
Write an XML description of the parameter into the given XML-RPC container.
Parameters
xml XML container to write into
Implements SideCar::Parameter::ValueBase.
Definition at line 489 of file Parameter.h.
template<typename ParamDef > ConstReferenceType SideCar::Parameter::TValue< ParamDef >::getOriginal () const inline
Obtain the parameter's original setting.
Returns
reference to currently-held value
Definition at line 303 of file Parameter.h.
template<typename ParamDef > ConstReferenceType SideCar::Parameter::TValue< ParamDef >::getValue () const inline
Obtain the parameter's current value.
Returns
reference to currently-held value
Definition at line 297 of file Parameter.h.
Referenced by SideCar::Algorithms::ChannelBuffer::enabledChanged(), SideCar::IO::Task::getChangedParameters(), SideCar::Algorithms::DownConverter::process(), SideCar::Algorithms::BugCollector::process(), SideCar::Algorithms::ManyInAlgorithm::processMessageReceived(), SideCar::Algorithms::Difference::reset(), SideCar::Algorithms::MatchedFilter::reset(), SideCar::Algorithms::ClutterMap::reset(), SideCar::Algorithms::ABTracker::shutdown(), SideCar::Algorithms::LowPassFilter::shutdown(), SideCar::Algorithms::CPISimpleOp::shutdown(), SideCar::Algorithms::MatchedFilter::shutdown(), SideCar::Algorithms::RangeDopplerMap::startup(), and SideCar::Algorithms::WindowedMinMax::startup().
template<typename ParamDef > bool SideCar::Parameter::TValue< ParamDef >::isNotOriginal () const inline override virtual
Determine if the current value differs from the original setting.
Returns
true if different
Implements SideCar::Parameter::ValueBase.
Definition at line 309 of file Parameter.h.
template<typename ParamDef > bool SideCar::Parameter::TValue< ParamDef >::isValid (ConstReferenceType value) const inline
Determines if the given value is valid for the parameter.
Parameters
value the value to check
Returns
true if valid
Definition at line 291 of file Parameter.h.
template<typename ParamDef > std::istream& SideCar::Parameter::TValue< ParamDef >::load (std::istream & is) inline override virtual
Obtain a new parameter value from a C++ input stream.
Relies on the template parameter's Load method to do the loading. Throws an InvalidValue exception if the loaded value is not valid for this parameter type.
Parameters
is stream to read from
Returns
stream read from
Implements SideCar::Parameter::ValueBase.
Definition at line 409 of file Parameter.h.
template<typename ParamDef > ACE_InputCDR& SideCar::Parameter::TValue< ParamDef >::load (ACE_InputCDR & cdr) inline override virtual
Obtain a new parameter value from an ACE CDR input stream.
Relies on the template parameter's Load() method to do the loading. Throws an InvalidValue exception if the loaded value is not valid for this parameter type.
Parameters
cdr stream to read from
Returns
stream read from
Implements SideCar::Parameter::ValueBase.
Definition at line 428 of file Parameter.h.
template<typename ParamDef > static Ref SideCar::Parameter::TValue< ParamDef >::Make (const std::string & name, const std::string & label) inline static
Factory method to create shareable parameter objects.
The parameter's initial value is the value of ValueType().
Parameters
name name of the parameter
label the text string to use in a GUI showing this value
Returns
shareable reference to new object
Definition at line 257 of file Parameter.h.
Referenced by SideCar::Algorithms::Controller::Make(), and SideCar::Algorithms::ChannelBuffer::makeEnabledParameter().
template<typename ParamDef > static Ref SideCar::Parameter::TValue< ParamDef >::Make (const std::string & name, const std::string & label, ConstReferenceType value) inline static
Factory method to create shareable parameter objects with an initial value.
NOTE: validates the given value before assigning it to the parameter, throwing an InvalidValue exception if it is invalid.
Parameters
name name of the parameter
label the text string to use in a GUI showing this value
value initial parameter value
Returns
shareable reference to new object
Definition at line 274 of file Parameter.h.
template<typename ParamDef > Self& SideCar::Parameter::TValue< ParamDef >::operator= (ConstReferenceType rhs) inline
Assignment operator.
See setValue().
Parameters
rhs new value to use
Returns
reference to self
Definition at line 379 of file Parameter.h.
template<typename ParamDef > Self& SideCar::Parameter::TValue< ParamDef >::operator= (Self & rhs) inline
Assignment operator.
Copies value from another parameter, but keeps the original name. Notifies registered change observers of the value change.
Parameters
rhs new value to use
Returns
reference to self
Definition at line 392 of file Parameter.h.
template<typename ParamDef > void SideCar::Parameter::TValue< ParamDef >::revert () inline
Revert the parameter value to its original value.
NOTE: currently, method emits a notification signal even when the values are the same. This may not hold in the future.
Definition at line 367 of file Parameter.h.
template<typename ParamDef > std::ostream& SideCar::Parameter::TValue< ParamDef >::save (std::ostream & os) const inline override virtual
Write out to a C++ output stream the parameter name and value.
Relies on the template parameter's Save() method to do the work.
Parameters
os stream to write to
Returns
stream written to
Implements SideCar::Parameter::ValueBase.
Definition at line 463 of file Parameter.h.
template<typename ParamDef > void SideCar::Parameter::TValue< ParamDef >::setOriginal (ConstReferenceType value) inline
Give the parameter a new original (and current) value.
If the value is not valid for this parameter type, throw an InvalidValue exception. After setting the new value, notifies registered change observers of the value change. NOTE: currently, method emits a notification signal even when the values are the same. This may not hold in the future.
Parameters
value new value to use
Definition at line 335 of file Parameter.h.
template<typename ParamDef > void SideCar::Parameter::TValue< ParamDef >::setValue (ConstReferenceType value) inline
Give the parameter a new value.
If the value is not valid for this parameter type, throw an InvalidValue exception. After setting the new value, notifies registered change observers of the value change. NOTE: currently, method emits a notification signal even when the values are the same. This may not hold in the future.
Parameters
value new value to use
Definition at line 318 of file Parameter.h.
template<typename ParamDef > void SideCar::Parameter::TValue< ParamDef >::setXMLOriginal (XmlRpc::XmlRpcValue & value) inline override virtual
Give the parameter a new original (and current) value taken from an XLM/RPC parameter.
Relies on the template definition's FromXML function to perform the translation from XML entity to ValueType. Throws an InvalidValue exception if the XML value is not valid for this parameter type. NOTE: currently, method emits a notification signal even when the values are the same. This may not hold in the future.
Parameters
value XML representation of value to use
Implements SideCar::Parameter::ValueBase.
Definition at line 362 of file Parameter.h.
template<typename ParamDef > void SideCar::Parameter::TValue< ParamDef >::setXMLValue (XmlRpc::XmlRpcValue & value) inline override virtual
Give the parameter a new value taken from an XLM/RPC parameter.
Relies on the template definition's FromXML function to perform the translation from XML entity to ValueType. Throws an InvalidValue exception if the XML value is not valid for this parameter type. NOTE: currently, method emits a notification signal even when the values are the same. This may not hold in the future.
Parameters
value XML representation of value to use
Implements SideCar::Parameter::ValueBase.
Definition at line 353 of file Parameter.h.
template<typename ParamDef > ACE_OutputCDR& SideCar::Parameter::TValue< ParamDef >::write (ACE_OutputCDR & cdr) const inline override virtual
Write out to an ACE CDR output stream the parameter name and value.
Relies on the template parameter's Write() method to do the work.
Parameters
cdr stream to write to
Returns
stream written to
Implements SideCar::Parameter::ValueBase.
Definition at line 472 of file Parameter.h.
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/Parameter/Parameter.h