SideCar: Logger::ProcLog Class Reference
Logger::ProcLog Class Reference
Utility class used to create log messages prefixed with a procedure name.
#include </Users/howes/src/sidecar/Logger/Log.h>
Public Member Functions
ProcLog (const char *name, Log &log)
Constructor.
ProcLog (const std::string &name, Log &log)
Constructor.
template<typename T >
void thrower (const T &ex)
Generate a `fatal' log message from an Utils::Exception object, and throw the exception object.
bool showsFatal () const
Determine if a 'fatal' log message would reach a log device.
bool showsError () const
Determine if an 'error' log message would reach a log device.
bool showsWarning () const
Determine if a 'warning' log message would reach a log device.
bool showsInfo () const
Determine if an 'info' log message would reach a log device.
bool showsTraceIn () const
Determine if a 'traceIn' log message would reach a log device.
bool showsTraceOut () const
Determine if a 'traceOut' log message would reach a log device.
bool showsDebug1 () const
Determine if a 'debug' log message would reach a log device.
bool showsDebug2 () const
Determine if a 'debug' log message would reach a log device.
bool showsDebug3 () const
Determine if a 'debug' log message would reach a log device.
std::ostream & fatal ()
Obtain output stream for `fatal' log messages.
std::ostream & error ()
Obtain output stream for `error' log messages.
std::ostream & warning ()
Obtain output stream for `warning' log messages.
std::ostream & info ()
Obtain output stream for `info' log messages.
std::ostream & traceIn ()
Obtain output stream for `trace' log messages.
std::ostream & traceOut ()
Obtain output stream for `trace' log messages.
std::ostream & debug1 ()
Obtain output stream for `debug1' log messages.
std::ostream & debug2 ()
Obtain output stream for `debug2' log messages.
std::ostream & debug3 ()
Obtain output stream for `debug3' log messages.
Protected Attributes
Log & log_
device to use for log messages
Detailed Description
Utility class used to create log messages prefixed with a procedure name.
To use, simply create an instance and use in place of a Log instance. To minimize routine entry times, one can create a static instance like so:
void Foo::bar() {
static Logger::ProcLog log("bar", Log());
log.debug() << "hi mom!" << std::endl;
The above assumes that the class Foo defined a (class) method called Log() which returned the general log device to use for all Foo-related log messages.
Definition at line 501 of file Log.h.
Constructor & Destructor Documentation
ProcLog::ProcLog (const char * name, Log & log)
Constructor.
Parameters
name routine name to prepend to log messages
log device to send log messages to
Definition at line 594 of file Log.cc.
ProcLog::ProcLog (const std::string & name, Log & log)
Constructor.
Parameters
name routine name to prepend to log messages
log device to send log messages to
Definition at line 600 of file Log.cc.
Member Function Documentation
std::ostream& Logger::ProcLog::debug1 () inline
Obtain output stream for `debug1' log messages.
Returns
output stream
Definition at line 623 of file Log.h.
std::ostream& Logger::ProcLog::debug2 () inline
Obtain output stream for `debug2' log messages.
Returns
output stream
Definition at line 629 of file Log.h.
std::ostream& Logger::ProcLog::debug3 () inline
Obtain output stream for `debug3' log messages.
Returns
output stream
Definition at line 635 of file Log.h.
std::ostream& Logger::ProcLog::error () inline
Obtain output stream for `error' log messages.
Returns
output stream
Definition at line 593 of file Log.h.
std::ostream& Logger::ProcLog::fatal () inline
Obtain output stream for `fatal' log messages.
Returns
output stream
Definition at line 587 of file Log.h.
std::ostream& Logger::ProcLog::info () inline
Obtain output stream for `info' log messages.
Returns
output stream
Definition at line 605 of file Log.h.
bool Logger::ProcLog::showsDebug1 () const inline
Determine if a 'debug' log message would reach a log device.
Returns
true if so
Definition at line 569 of file Log.h.
Referenced by SideCar::Messages::TSPI::MakeEFGCoordinateFromRawBytes().
bool Logger::ProcLog::showsDebug2 () const inline
Determine if a 'debug' log message would reach a log device.
Returns
true if so
Definition at line 575 of file Log.h.
bool Logger::ProcLog::showsDebug3 () const inline
Determine if a 'debug' log message would reach a log device.
Returns
true if so
Definition at line 581 of file Log.h.
Referenced by Utils::RunningMedian::addValue().
bool Logger::ProcLog::showsError () const inline
Determine if an 'error' log message would reach a log device.
Returns
true if so
Definition at line 539 of file Log.h.
bool Logger::ProcLog::showsFatal () const inline
Determine if a 'fatal' log message would reach a log device.
Returns
true if so
Definition at line 533 of file Log.h.
bool Logger::ProcLog::showsInfo () const inline
Determine if an 'info' log message would reach a log device.
Returns
true if so
Definition at line 551 of file Log.h.
bool Logger::ProcLog::showsTraceIn () const inline
Determine if a 'traceIn' log message would reach a log device.
Returns
true if so
Definition at line 557 of file Log.h.
bool Logger::ProcLog::showsTraceOut () const inline
Determine if a 'traceOut' log message would reach a log device.
Returns
true if so
Definition at line 563 of file Log.h.
bool Logger::ProcLog::showsWarning () const inline
Determine if a 'warning' log message would reach a log device.
Returns
true if so
Definition at line 545 of file Log.h.
template<typename T > void Logger::ProcLog::thrower (const T & ex) inline
Generate a `fatal' log message from an Utils::Exception object, and throw the exception object.
As such, it will not return...
\param ex exception to log and throw
Definition at line 527 of file Log.h.
Referenced by SideCar::Messages::CircularBuffer::add(), SideCar::IO::ChannelVector::add(), SideCar::Algorithms::Algorithm::addProcessor(), SideCar::Messages::VoidLoaderRegistry::addVoidLoader(), SideCar::Runner::App::App(), SideCar::IO::Task::doTimeout(), SideCar::Messages::MetaTypeInfo::Find(), SideCar::Messages::CircularBuffer::Get(), SideCar::Messages::VoidLoaderRegistry::getVoidLoader(), SideCar::GUI::PPIDisplay::PPIWidget::initializeContext(), SideCar::Messages::CircularBuffer::Install(), SideCar::Runner::StreamBuilder::Make(), SideCar::IO::MessageManager::MessageManager(), SideCar::GUI::BScope::PPIWidget::PPIWidget(), SideCar::IO::Task::processDataMessage(), SideCar::IO::RecordIndex::RecordIndex(), SideCar::Algorithms::Algorithm::removeProcessor(), SideCar::IO::TimeIndex::TimeIndex(), SideCar::Time::TimeStamp::TimeStamp(), SideCar::Messages::VoidLoaderRegistry::VoidLoaderRegistry(), and SideCar::GUI::ESScope::XYWidget::XYWidget().
std::ostream& Logger::ProcLog::traceIn () inline
Obtain output stream for `trace' log messages.
Returns
output stream
Definition at line 611 of file Log.h.
std::ostream& Logger::ProcLog::traceOut () inline
Obtain output stream for `trace' log messages.
Returns
output stream
Definition at line 617 of file Log.h.
std::ostream& Logger::ProcLog::warning () inline
Obtain output stream for `warning' log messages.
Returns
output stream
Definition at line 599 of file Log.h.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Logger/Log.h
/Users/howes/src/sidecar/Logger/Log.cc