SideCar: PoolAllocator Class Reference
PoolAllocator Class Reference
A wrapper for the Utils::Pool class which allows it to be used as an ACE memory allocator.
Public Member Functions
PoolAllocator (size_t objectSize, const char *name)
Constructor.
~PoolAllocator ()
Destructor.
Utils::Pool::AllocationStats getAllocationStats () const
Obtain allocation statistics for this allocator.
void * malloc (size_t size)
Override of ACE_New_Allocator::malloc() method.
void * calloc (size_t size, char init= '\0')
Override of ACE_New_Allocator::calloc() method.
void * calloc (size_t count, size_t elemSize, char init= '\0')
void free (void *ptr)
Return a previously-allocated object to the pool.
Static Public Member Functions
static Logger::Log & Log ()
Obtainn log device for PoolAllocator objects.
Detailed Description
A wrapper for the Utils::Pool class which allows it to be used as an ACE memory allocator.
The Utils::Pool class is a source of same-size memory objects with fast creation/destruction times. This class serves as the base class for the MessageBlockAllocatorImpl, DataBlockAllocatorImpl, and MetaDataAllocatorImpl classes below.
Definition at line 24 of file MessageManager.cc.
Constructor & Destructor Documentation
PoolAllocator::PoolAllocator (size_t objectSize, const char * name)
Constructor.
Parameters
objectSize the number of bytes take up by an object in the pool.
name name of the allocator (used only for log messages)
Definition at line 102 of file MessageManager.cc.
References Log(), and LOGDEBUG.
PoolAllocator::~PoolAllocator ()
Destructor.
Deallocates all pool chunks.
Definition at line 110 of file MessageManager.cc.
References Log(), and LOGDEBUG.
Member Function Documentation
void * PoolAllocator::calloc (size_t size, char init = '\0')
Override of ACE_New_Allocator::calloc() method.
Allocates a new object from the pool, and sets all of the bytes in the object to a given value. Uses malloc() method to do the allocation.
Parameters
size number of bytes to allocate. This should be the same value as given to the PoolAllocator constructor. If not, then the default C++ allocate will be used to process the request, and not the pool allocator.
init initial value to assign to all the allocated bytes
\return pointer to allocated space, or NULL if error
Definition at line 124 of file MessageManager.cc.
References malloc().
void PoolAllocator::free (void * ptr)
Return a previously-allocated object to the pool.
Normally, does not check to see if the given pointer originated from the pool. To do so, invoke Utils::Pool::SetValidateRelease(true) prior to deleting an object.
\param ptr pointer to release
Definition at line 132 of file MessageManager.cc.
References Utils::Pool::release().
Referenced by MetaDataAllocatorImpl::free().
Utils::Pool::AllocationStats PoolAllocator::getAllocationStats () const inline
Obtain allocation statistics for this allocator.
Returns
Utils::Pool::AllocationStats value
Definition at line 50 of file MessageManager.cc.
Logger::Log & PoolAllocator::Log () static
Obtainn log device for PoolAllocator objects.
Returns
log device
Definition at line 95 of file MessageManager.cc.
References Logger::Log::Find().
Referenced by SideCar::IO::MessageManager::MakeControlMessage(), PoolAllocator(), and ~PoolAllocator().
void * PoolAllocator::malloc (size_t size)
Override of ACE_New_Allocator::malloc() method.
Allocates a new object from the pool.
Parameters
size number of bytes to allocate. This should be the same value as given to the PoolAllocator constructor. If not, then the default C++ allocate will be used to process the request, and not the pool allocator.
Returns
pointer to allocated space, or NULL if error
Definition at line 117 of file MessageManager.cc.
References Utils::Pool::allocate().
Referenced by calloc().
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/IO/MessageManager.cc