SideCar: Utils::CmdLineArgs Class Reference
Utils::CmdLineArgs Class Reference
Command-line processor.
#include </Users/howes/src/sidecar/Utils/CmdLineArgs.h>
Data Structures
struct ArgumentDef
Collection of attributes used to define a command-line argument.
class Arguments
Collection arguments found on the command-line.
struct OptionDef
Collection of attributes used to define a command-line option.
class Options
Map of options found on the command line.
Public Types
using OptionDefVector = std::vector< OptionDef >
Define collection of OptionDef instances.
using ArgumentDefVector = std::vector< ArgumentDef >
Define collection of ArgumentDef instances.
Public Member Functions
CmdLineArgs (size_t argc, char *const *argv, const std::string &description, const OptionDefVector &optDefs, const ArgumentDefVector &argDefs, bool quitOnError=true)
Constructor.
CmdLineArgs (size_t argc, char *const *argv, const std::string &description, const OptionDef *optDefs, size_t sizeofOptDefs, const ArgumentDef *argDefs, size_t sizeofArgDefs, bool quitOnError=true)
Constructor.
const std::string & fullPath () const
const std::string & progName () const
void usage (const std::string &txt, bool quit=true) const
Write out an error message to std::cerr and exit the program with a non-zero value.
void help (bool quit=true) const
Show the usage text for the program, and exit with a zero value.
Options & opts ()
Obtain the options set on the command line.
Arguments & args ()
Obtain the arguments provided on the command line.
bool hasOpt (const std::string &key) const
Lookup an option to see if it was set by the user.
bool hasOpt (char key) const
Lookup an option to see if it was set by the user.
bool hasOpt (const std::string &key, std::string &value) const
Lookup an option to see if it was set by the user.
bool hasOpt (char key, std::string &value) const
Lookup an option to see if it was set by the user.
Options::ValueVector & opt (const std::string &key)
Fetch all of the values for an option key.
Options::ValueVector & opt (char key)
Fetch all of the values for an option key.
bool hasArg (size_t index) const
Check if a certain argument is available.
bool hasArg (size_t index, std::string &value) const
Check if a certain argument is available.
const std::string & arg (size_t index) const
Fetch a specific argument value.
int argc () const
Obtain the residual argc value after all option and argument processing.
char *const * argv () const
Obtain the residual argv value after all option and argument processing.
const std::string & cmdline () const
Obtain the arguments representing all of the command-line arguments processed up to this point.
Detailed Description
Command-line processor.
Visits data found in argc and argv (as given to main(), and creates entries in instances of Options and Arguments based on what was found on the command-line. Parsing of the command-line is governed by user-supplied arrays that define what options are supported, and what arguments are required.
OptionDef opts[] = { { 'd', "debug", "turn on debugging", "" },
                     { 'o', "output", "write output to FILE", "FILE" } };
ArgumentDef args[] = { { "FILE", "read input from FILE" } };
int main(int argc, const char* argv[])
{
  std::string inputFile(""), outputFile("");
  CmdLineArgs cla(argc, argv, opts, sizeof(opts), args, sizeof(args));
  if (cla.hasOpt("debug")) enableDebugging();
  if (cla.hasOpt("output", outputFile)) redirect(outputFile);
  inputFile = cla.arg(0);
  ...
  ...
}
Definition at line 36 of file CmdLineArgs.h.
Constructor & Destructor Documentation
CmdLineArgs::CmdLineArgs (size_t argc, char *const * argv, const std::string & description, const OptionDefVector & optDefs, const ArgumentDefVector & argDefs, bool quitOnError = true)
Constructor.
Processes the given command-line argument values, argc and argv. These should be the values given to the main() routine by the system. The first value in argv is taken as the running program's name. After processing, the remaining argc and argv values may be obtained via the CmdLineArgs::argc() and CmdLineArgs::argv() methods.
Parameters
argc number of values in argv
argv array of C strings representing the command line values
description short description of the program
optDefs vector of option definition values
argDefs vector of argument definition values
quitOnError control whether the program call ::exit or throws an exception on an error.
Definition at line 25 of file CmdLineArgs.cc.
CmdLineArgs::CmdLineArgs (size_t argc, char *const * argv, const std::string & description, const OptionDef * optDefs, size_t sizeofOptDefs, const ArgumentDef * argDefs, size_t sizeofArgDefs, bool quitOnError = true)
Constructor.
Processes the given command-line argument values, argc and argv. These should be the values given to the main() routine by the system. The first value in argv is taken as the running program's name. After processing, the remaining argc and argv values may be obtained via the CmdLineArgs::argc() and CmdLineArgs::argv() methods.
Parameters
argc number of values in argv
argv array of C strings representing the command line values
description short description of the program
optDefs array of option definitions
sizeofOptDefs value of the sizeof operator applied to the optDefs value. Note that this must be done against the array object itself, and not a pointer to it.
argDefs array of argument definitions
sizeofArgDefs value of the sizeof operator applied to the argDefs value. Note that this must be done against the array object itself, and not a pointer to it.
quitOnError control whether the program call ::exit or throws an exception on an error.
Definition at line 33 of file CmdLineArgs.cc.
Member Function Documentation
const std::string& Utils::CmdLineArgs::arg (size_t index) const inline
Fetch a specific argument value.
Parameters
index which argument to obtain (zero-based)
Returns
argument value
Definition at line 331 of file CmdLineArgs.h.
Referenced by SideCar::Runner::App::App(), ConverterInputTask::deliverDataMessage(), PRIInfoInputTask::deliverDataMessage(), PRIChunkerOutputTask::deliverDataMessage(), and hasArg().
int Utils::CmdLineArgs::argc () const inline
Obtain the residual argc value after all option and argument processing.
Returns
number of values remaining in argv array
Definition at line 337 of file CmdLineArgs.h.
Referenced by Args::Args().
Arguments& Utils::CmdLineArgs::args () inline
Obtain the arguments provided on the command line.
Returns
reference to Arguments instance
Definition at line 247 of file CmdLineArgs.h.
char* const* Utils::CmdLineArgs::argv () const inline
Obtain the residual argv value after all option and argument processing.
Returns
address of first unprocessed argument item
Definition at line 343 of file CmdLineArgs.h.
const std::string& Utils::CmdLineArgs::cmdline () const inline
Obtain the arguments representing all of the command-line arguments processed up to this point.
Returns
string of processed arguments
Definition at line 349 of file CmdLineArgs.h.
References opt().
const std::string& Utils::CmdLineArgs::fullPath () const inline
Returns
the full path of the executable
Definition at line 219 of file CmdLineArgs.h.
bool Utils::CmdLineArgs::hasArg (size_t index) const inline
Check if a certain argument is available.
Parameters
index which argument to look for
Returns
true if the argument is present; false otherwise
Definition at line 313 of file CmdLineArgs.h.
Referenced by Args::Args().
bool CmdLineArgs::hasArg (size_t index, std::string & value) const
Check if a certain argument is available.
If so, return its value.
Parameters
index which argument to look for
value reference to string that is updated with the argument value, if the argument exists
Returns
TRUE if the argument was found; false otherwise
Definition at line 80 of file CmdLineArgs.cc.
References arg().
bool Utils::CmdLineArgs::hasOpt (const std::string & key) const inline
Lookup an option to see if it was set by the user.
Parameters
key the name of the option to look for
Returns
true if the option was found; false otherwise.
Definition at line 255 of file CmdLineArgs.h.
Referenced by SideCar::Runner::App::App(), Args::Args(), ConverterInputTask::deliverDataMessage(), PRIInfoInputTask::deliverDataMessage(), and PRIChunkerOutputTask::deliverDataMessage().
bool Utils::CmdLineArgs::hasOpt (char key) const inline
Lookup an option to see if it was set by the user.
Parameters
key the name of the option to look for
Returns
true if the option was found; false otherwise.
Definition at line 263 of file CmdLineArgs.h.
bool Utils::CmdLineArgs::hasOpt (const std::string & key, std::string & value) const inline
Lookup an option to see if it was set by the user.
If so, return the first value found under the option name.
Parameters
key the name of the option to look for
value reference to string that is updated with the first option value found. If option was not set, then this value is left alone
Returns
true if the option was found; false otherwise.
Definition at line 275 of file CmdLineArgs.h.
bool Utils::CmdLineArgs::hasOpt (char key, std::string & value) const inline
Lookup an option to see if it was set by the user.
If so, return the first value found under the option name.
Parameters
key the name of the option to look for
value reference to string that is updated with the first option value found. If option was not set, then this value is left alone
Returns
true if the option was found; false otherwise
Definition at line 288 of file CmdLineArgs.h.
Options::ValueVector& Utils::CmdLineArgs::opt (const std::string & key) inline
Fetch all of the values for an option key.
Parameters
key the name of the option to look for.
Returns
vector of values set for the option. If option was never set, size of vector will be zero.
Definition at line 297 of file CmdLineArgs.h.
Referenced by cmdline(), PRIInfoInputTask::deliverDataMessage(), PrintDetailArg::operator()(), and FindLongName::operator()().
Options::ValueVector& Utils::CmdLineArgs::opt (char key) inline
Fetch all of the values for an option key.
Parameters
key the name of the option to look for.
Returns
vector of values set for the option. If option was never set, size of vector will be zero.
Definition at line 305 of file CmdLineArgs.h.
Options& Utils::CmdLineArgs::opts () inline
Obtain the options set on the command line.
Returns
reference to Options instance
Definition at line 241 of file CmdLineArgs.h.
const std::string& Utils::CmdLineArgs::progName () const inline
Returns
the program name as taken from the first value in argv, sans any path.
Definition at line 223 of file CmdLineArgs.h.
References usage().
Referenced by PRIInfoInputTask::deliverDataMessage(), and PRIChunkerOutputTask::deliverDataMessage().
void CmdLineArgs::usage (const std::string & txt, bool quit = true) const
Write out an error message to std::cerr and exit the program with a non-zero value.
Parameters
txt error message text
quit if true, call ::exit when done; otherwise throw std::runtime_error exception
Definition at line 72 of file CmdLineArgs.cc.
References help().
Referenced by Args::Args(), ConverterInputTask::deliverDataMessage(), FindLongName::operator()(), and progName().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Utils/CmdLineArgs.h
/Users/howes/src/sidecar/Utils/CmdLineArgs.cc