SideCar: SideCar::GUI::ChannelSetting Class Reference
SideCar::GUI::ChannelSetting Class Reference
Derivation of StringSetting that works with a QComboBox widget to display and change a subscription channel setting.
#include </Users/howes/src/sidecar/GUI/ChannelSetting.h>
Public Slots
void shutdown ()
Public Slots inherited from SideCar::GUI::StringSetting
void setValue (const QString &value)
Change the setting value.
Public Slots inherited from SideCar::GUI::Setting
void setEnabled (bool state)
Signals
void incoming (const MessageList &messages)
Notification sent out when the channel has data.
void availableChannels (const QList< QString > &names)
void valueChanged (int index)
void channelsAvailable (bool value)
Signals inherited from SideCar::GUI::StringSetting
void valueChanged (const QString &value)
Notification sent out when the held value changes.
Signals inherited from SideCar::GUI::Setting
void save (int index, const QVariant &value)
Notification sent out by the Setting object when the held value changes due to the setValue() method.
void enabledChanged (bool state)
Notification sent out by the Setting object when its enabled state changes.
void valueChanged ()
Public Member Functions
ChannelSetting (const std::string &typeName, PresetManager *mgr, QComboBox *widget=0, bool global=false)
void connectWidget (QComboBox *widget)
bool hasChannels () const
bool isConnected () const
Public Member Functions inherited from SideCar::GUI::StringSetting
StringSetting (PresetManager *mgr, const QString &name, bool global=false)
Constructor.
StringSetting (PresetManager *mgr, const QString &name, const QString &value, bool global=false)
Constructor.
const QString & getValue () const
Obtain the current setting value.
Public Member Functions inherited from SideCar::GUI::Setting
Setting (PresetManager *mgr, const QString &name, bool global=false)
Constructor without a default setting value.
Setting (PresetManager *mgr, const QString &name, const QVariant &value, bool global=false)
Constructor with a default setting value.
const QString & getName () const
Obtain the name of the Setting object.
const QVariant & getOpaqueValue () const
Obtain the current value of the Setting object.
void setOpaqueValue (const QVariant &value)
Set the Setting's value and emit the opaqueValueChanged() signal followed by the save() signal.
bool isEnabled () const
Static Public Member Functions
static Logger::Log & Log ()
Log device for objects of this class.
static QString GetChannelName (const std::string &typeName)
Static Public Member Functions inherited from SideCar::GUI::Setting
static Logger::Log & Log ()
Log device for Setting objects.
Static Public Member Functions inherited from SideCar::IO::ZeroconfTypes::TZCType< id >
static const char * GetZeroconfType ()
Obtain the configured Zeroconf type for objects derived from this class.
static const char * GetTwinZeroconfType ()
Obtain the "twin" Zeroconf type for objects derived from this class.
static std::string MakeZeroconfType (const std::string &subType)
Construct a valid SideCar Zeroconf type string for a given subtype.
static std::string MakeTwinZeroconfType (const std::string &subType)
Construct the twin SideCar Zeroconf type string for a given subtype.
Static Public Member Functions inherited from SideCar::IO::ZeroconfRegistry
static const char * GetType (ID id)
Obtain the Zeroconf type string for a given ID.
static ID GetTwin (ID id)
Locate the twin of this ID.
static std::string MakeZeroconfType (const char *type, const std::string &subType)
Construct a valid SideCar Zeroconf type string for a type and a subtype.
Additional Inherited Members
Public Types inherited from SideCar::IO::ZeroconfRegistry
enum ID {
kPublisher = 0, kSubscriber, kRunnerStatusCollector, kRunnerStatusEmitter,
kStateEmitter, kStateCollector, kRunnerRemoteController, kNumTypes
}
Defined Zeroconf types.
Protected Member Functions inherited from SideCar::GUI::StringSetting
void valueUpdated ()
Override of Setting::valueUpdated() method.
Protected Member Functions inherited from SideCar::GUI::Setting
void resetOpaqueValue ()
void connectWidget (QWidget *widget)
void disconnectWidget (QWidget *widget)
Detailed Description
Derivation of StringSetting that works with a QComboBox widget to display and change a subscription channel setting.
Uses the QComboBox::currentIndexChanged() signal to detect changes in the widget.
Definition at line 21 of file ChannelSetting.h.
Member Function Documentation
void SideCar::GUI::ChannelSetting::incoming (const MessageList & messages) signal
Notification sent out when the channel has data.
Parameters
messages list of Messages::Header::Ref objects
Referenced by Log().
Logger::Log & ChannelSetting::Log () static
Log device for objects of this class.
Returns
log device
Definition at line 17 of file ChannelSetting.cc.
References Logger::Log::Find(), SideCar::GUI::AppBase::GetApp(), SideCar::GUI::Subscriber::getMessages(), SideCar::GUI::Setting::getName(), SideCar::GUI::ServiceBrowser::getServiceEntry(), SideCar::GUI::StringSetting::getValue(), incoming(), LOGDEBUG, LOGINFO, SideCar::IO::ZeroconfTypes::TZCType< id >::MakeTwinZeroconfType(), SideCar::GUI::StringSetting::setValue(), SideCar::GUI::Subscriber::shutdown(), SideCar::GUI::ServiceBrowser::start(), SideCar::GUI::ServiceBrowser::stop(), SideCar::GUI::Subscriber::useServiceEntry(), and SideCar::GUI::StringSetting::valueUpdated().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/ChannelSetting.h
/Users/howes/src/sidecar/GUI/ChannelSetting.cc