SideCar: SideCar::GUI::AScope::VideoChannel Class Reference
SideCar::GUI::AScope::VideoChannel Class Reference
Manages a Subscriber connection to a remote data publisher for Messages::Video data.
#include </Users/howes/src/sidecar/GUI/AScope/VideoChannel.h>
Public Slots
void shutdown ()
Notification from the application that it is shutting down.
Signals
void connected ()
Notification sent out when the connection to a publisher has been established.
void disconnected ()
Notification sent out when the connection to a publisher has been broken.
void colorChanged (const QColor &color)
Notification sent out when the channel color has changed.
void sampleToVoltageScalingChanged ()
Notification sent out when the sample-to-voltage scaling has changed.
Public Member Functions
VideoChannel (History &history, const QString &name)
Constructor.
~VideoChannel ()
Destructor.
const QString & getName () const
Obtain the name of the subscription channel.
const QColor & getColor () const
Obtain the color used to draw data from the channel.
size_t getHistorySlot () const
Obtain the history slot assigned to the channel.
int getDisplayCount () const
Obtain the number of times the channel is shown in a Visualizer view.
const PeakBarCollection & getPeakBars () const
bool isDisplayed () const
Determine if there are active ChannelConnection objects containing this channel.
size_t displayAdded ()
Channel is associated with a new ChannelConnection object.
void displayDropped ()
Channel is no longer associated with a ChannelConnection object.
bool isConnected () const
Obtain the connection state of the channel.
void useServiceEntry (ServiceEntry *serviceEntry)
Provide the connection information to use to establish a connection to a data publisher.
void setColor (const QColor &color)
Change the color used when drawing the data from the channel.
void setSampleToVoltageScaling (int sampleMin, int sampleMax, double voltageMin, double voltageMax)
double getVoltageForSample (int sample) const
void restoreFromSettings (QSettings &settings)
void saveToSettings (QSettings &settings) const
int getSampleMin () const
int getSampleMax () const
double getVoltageMin () const
double getVoltageMax () const
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for instances of this class.
Protected Slots
void readerIncoming ()
Notification from the Subscriber object of incoming data.
Detailed Description
Manages a Subscriber connection to a remote data publisher for Messages::Video data.
Each instance has a unique History slot value which it uses to post incoming data to the application's History object. Instances also have a user-configurable color value which is used to distinguish its data from that of other channels.
Definition at line 29 of file VideoChannel.h.
Constructor & Destructor Documentation
VideoChannel::VideoChannel (History & history, const QString & name)
Constructor.
Used when creating a new channel
Parameters
history object that records incoming data
name name of the subscription channel
Definition at line 31 of file VideoChannel.cc.
References Log(), and LOGINFO.
VideoChannel::~VideoChannel ()
Destructor.
Releases any allocated history slot.
Definition at line 40 of file VideoChannel.cc.
References Log(), LOGINFO, and SideCar::GUI::AScope::History::releaseSlot().
Member Function Documentation
size_t VideoChannel::displayAdded ()
Channel is associated with a new ChannelConnection object.
Causes the channel to connect to the data publisher if not already connected.
Returns
history slot assigned to the channel
Definition at line 49 of file VideoChannel.cc.
References SideCar::GUI::AScope::History::allocateSlot(), Log(), and LOGINFO.
void VideoChannel::displayDropped ()
Channel is no longer associated with a ChannelConnection object.
If there are no more ChannelConnection objects, then drop the connection to the data publisher.
Definition at line 61 of file VideoChannel.cc.
References Log(), LOGINFO, SideCar::GUI::AScope::History::releaseSlot(), and shutdown().
Referenced by SideCar::GUI::AScope::ChannelConnection::~ChannelConnection().
const QColor& SideCar::GUI::AScope::VideoChannel::getColor () const inline
Obtain the color used to draw data from the channel.
Returns
QColor reference
Definition at line 62 of file VideoChannel.h.
int SideCar::GUI::AScope::VideoChannel::getDisplayCount () const inline
Obtain the number of times the channel is shown in a Visualizer view.
Returns
Definition at line 74 of file VideoChannel.h.
size_t SideCar::GUI::AScope::VideoChannel::getHistorySlot () const inline
Obtain the history slot assigned to the channel.
Returns
Definition at line 68 of file VideoChannel.h.
const QString& SideCar::GUI::AScope::VideoChannel::getName () const inline
Obtain the name of the subscription channel.
Returns
name
Definition at line 56 of file VideoChannel.h.
Referenced by SideCar::GUI::AScope::ChannelConnectionModel::getChannelConnection(), SideCar::GUI::AScope::ChannelConnectionModel::removeConnection(), SideCar::GUI::AScope::ChannelConnectionModel::setData(), and SideCar::GUI::AScope::Visualizer::Visualizer().
bool VideoChannel::isConnected () const
Obtain the connection state of the channel.
Returns
true if connected, false otherwise
Definition at line 73 of file VideoChannel.cc.
References SideCar::GUI::Subscriber::isConnected().
Referenced by SideCar::GUI::AScope::ChannelConnectionModel::data(), and SideCar::GUI::AScope::ChannelConnectionModel::setData().
bool SideCar::GUI::AScope::VideoChannel::isDisplayed () const inline
Determine if there are active ChannelConnection objects containing this channel.
Returns
true if so
Definition at line 82 of file VideoChannel.h.
Referenced by SideCar::GUI::AScope::ChannelConnectionModel::removeConnection(), and SideCar::GUI::AScope::Visualizer::Visualizer().
Logger::Log & VideoChannel::Log () static
Obtain the log device for instances of this class.
Returns
log device
Definition at line 25 of file VideoChannel.cc.
References Logger::Log::Find().
Referenced by displayAdded(), displayDropped(), readerIncoming(), setColor(), shutdown(), useServiceEntry(), VideoChannel(), and ~VideoChannel().
void VideoChannel::readerIncoming () protected slot
Notification from the Subscriber object of incoming data.
Parameters
data incoming message
Definition at line 102 of file VideoChannel.cc.
References SideCar::GUI::AScope::History::getLiveMessage(), SideCar::GUI::Subscriber::getMessages(), Log(), LOGINFO, and SideCar::GUI::AScope::History::update().
Referenced by useServiceEntry().
void VideoChannel::setColor (const QColor & color)
Change the color used when drawing the data from the channel.
Parameters
color new color to use
Definition at line 91 of file VideoChannel.cc.
References colorChanged(), Log(), and LOGDEBUG.
Referenced by SideCar::GUI::AScope::ChannelConnection::setFrozen().
void VideoChannel::shutdown () slot
Notification from the application that it is shutting down.
Stops the reader thread.
Definition at line 79 of file VideoChannel.cc.
References Log(), and LOGINFO.
Referenced by displayDropped().
void VideoChannel::useServiceEntry (ServiceEntry * serviceEntry)
Provide the connection information to use to establish a connection to a data publisher.
If a connection currently exists, drop it and start anew.
Parameters
serviceEntry connection information
Definition at line 114 of file VideoChannel.cc.
References connected(), disconnected(), SideCar::GUI::AScope::App::GetApp(), Log(), LOGERROR, readerIncoming(), sampleToVoltageScalingChanged(), and SideCar::GUI::Subscriber::useServiceEntry().
Referenced by SideCar::GUI::AScope::ChannelConnectionModel::getChannelConnection(), and SideCar::GUI::AScope::ChannelConnectionModel::setData().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/AScope/VideoChannel.h
/Users/howes/src/sidecar/GUI/AScope/VideoChannel.cc