SideCar: SideCar::GUI::AScope::History Class Reference
SideCar::GUI::AScope::History Class Reference
Manager of a collection of HistoryFrame objects that represent unique snapshots of data from one or more input channels.
#include </Users/howes/src/sidecar/GUI/AScope/History.h>
Public Slots
void setEnabled (bool enabled)
Change whether retention is enabled.
void freezePast (bool state)
Freeze the past buffer so that it may be viewed, or thaw it to accumulate new live data.
void setDuration (int duration)
Change the number of seconds retained.
Signals
void liveFrameChanged ()
Notification sent out when a new live frame is available.
void pastFrozen ()
void pastThawed ()
Public Member Functions
History (QObject *parent)
Constructor.
int allocateSlot ()
Obtain a unique slot to use for working with the history buffer.
int getSlotIndex (int slot) const
Obtain the internal mapping from a slot value to frame index.
void releaseSlot (int slot)
Remove an allocated slot from the history buffer.
void update (int slot, const MessageList &data)
Update the historical record with a one or more data messages.
bool isEnabled () const
Determine if retention is enabled.
int getDuration () const
Obtain the number of seconds retained.
int getFrameCount () const
Obtain the number of frames in the historical past.
const HistoryFrame & getLiveFrame () const
Obtain the current frame of data.
HistoryFrame getPastFrame (int position) const
Obtain a frame of data from sometime in the past if position is non-zero, or else the current frame.
Messages::PRIMessage::Ref getLiveMessage (int slot) const
Obtain the live data of a slot.
Messages::PRIMessage::Ref getPastMessage (int position, int slot) const
Obtain the frozen data of a slot.
Static Public Member Functions
static Logger::Log & Log ()
Detailed Description
Manager of a collection of HistoryFrame objects that represent unique snapshots of data from one or more input channels.
Definition at line 26 of file History.h.
Constructor & Destructor Documentation
History::History (QObject * parent)
Constructor.
Parameters
durations number of seconds to retain
enabled whether retention is enabled
Definition at line 25 of file History.cc.
Member Function Documentation
int History::allocateSlot ()
Obtain a unique slot to use for working with the history buffer.
Returns
slot value
Definition at line 33 of file History.cc.
References LOGDEBUG, and LOGINFO.
Referenced by SideCar::GUI::AScope::VideoChannel::displayAdded().
void History::freezePast (bool state) slot
Freeze the past buffer so that it may be viewed, or thaw it to accumulate new live data.
Emits the pastFrozen() or pastThawed() signal depending on which state the past buffer is in. signal.
Definition at line 194 of file History.cc.
Referenced by SideCar::GUI::AScope::HistoryPosition::HistoryPosition(), and SideCar::GUI::AScope::HistoryPosition::setPosition().
int SideCar::GUI::AScope::History::getDuration () const inline
Obtain the number of seconds retained.
Returns
retention count
Definition at line 85 of file History.h.
int SideCar::GUI::AScope::History::getFrameCount () const inline
Obtain the number of frames in the historical past.
Since pruning of the records is done by time, this value is not a constant.
Returns
past size
Definition at line 92 of file History.h.
Referenced by SideCar::GUI::AScope::HistoryControlWindow::activeMainWindowChanged(), and SideCar::GUI::AScope::HistoryControlWidget::HistoryControlWidget().
const HistoryFrame& SideCar::GUI::AScope::History::getLiveFrame () const inline
Obtain the current frame of data.
Returns
HistoryFrame pointer
Definition at line 98 of file History.h.
Referenced by SideCar::GUI::AScope::HistoryPosition::HistoryPosition().
Messages::PRIMessage::Ref History::getLiveMessage (int slot) const
Obtain the live data of a slot.
Parameters
position which entry to obtain
slot which message of an entry to obtain
Returns
a PRIMessage reference (may be a NULL reference)
Definition at line 235 of file History.cc.
References SideCar::GUI::AScope::HistoryFrame::getMessage(), and LOGINFO.
Referenced by SideCar::GUI::AScope::VideoChannel::readerIncoming(), and SideCar::GUI::AScope::HistoryPosition::setPosition().
HistoryFrame History::getPastFrame (int position) const
Obtain a frame of data from sometime in the past if position is non-zero, or else the current frame.
Parameters
position position in a HistoryBuffer of the data to fetch
Returns
HistoryFrame pointer
Definition at line 216 of file History.cc.
References SideCar::GUI::AScope::HistoryFrame::append(), and LOGINFO.
Referenced by getPastMessage(), and SideCar::GUI::AScope::HistoryPosition::setPosition().
Messages::PRIMessage::Ref History::getPastMessage (int position, int slot) const
Obtain the frozen data of a slot.
Parameters
position which entry to obtain
slot which message of an entry to obtain
Returns
a PRIMessage reference (may be a NULL reference)
Definition at line 246 of file History.cc.
References SideCar::GUI::AScope::HistoryFrame::getMessage(), and getPastFrame().
int SideCar::GUI::AScope::History::getSlotIndex (int slot) const inline
Obtain the internal mapping from a slot value to frame index.
NOTE: this value may change after future calls to releaseSlot(), so it should not be saved. Also, the returned value may be -1 if the data channel assigned to the slot has not yet placed any data into its history buffer.
Parameters
slot value from a prior allocateSlot() call to fetch
Returns
assigned index value for the slot
Definition at line 55 of file History.h.
Referenced by SideCar::GUI::AScope::HistoryPosition::setPosition().
bool SideCar::GUI::AScope::History::isEnabled () const inline
Determine if retention is enabled.
Returns
true if so
Definition at line 79 of file History.h.
Referenced by SideCar::GUI::AScope::HistoryControlWindow::activeMainWindowChanged().
void SideCar::GUI::AScope::History::liveFrameChanged () signal
Notification sent out when a new live frame is available.
Parameters
frame
Referenced by update().
void History::releaseSlot (int slot)
Remove an allocated slot from the history buffer.
Future calls to update() or getMessage() with the given slot value will return a NULL reference.
Parameters
slot index to remove
Definition at line 57 of file History.cc.
References LOGINFO, and SideCar::GUI::AScope::HistoryFrame::shrink().
Referenced by SideCar::GUI::AScope::VideoChannel::displayDropped(), and SideCar::GUI::AScope::VideoChannel::~VideoChannel().
void History::setDuration (int duration) slot
Change the number of seconds retained.
Parameters
duration seconds retained
Definition at line 206 of file History.cc.
References LOGINFO.
Referenced by SideCar::GUI::AScope::App::App().
void History::setEnabled (bool enabled) slot
Change whether retention is enabled.
Parameters
enabled new retention state
Definition at line 181 of file History.cc.
References LOGINFO.
Referenced by SideCar::GUI::AScope::App::App().
void History::update (int slot, const MessageList & data)
Update the historical record with a one or more data messages.
Parameters
slot unique ID of the data provider, obtained by an earlier call to allocateSlot().
data collection of raw incoming messages to record
metaType description of the incoming data
Definition at line 106 of file History.cc.
References SideCar::GUI::AScope::HistoryFrame::expand(), liveFrameChanged(), LOGDEBUG, LOGINFO, and SideCar::GUI::AScope::HistoryFrame::update().
Referenced by SideCar::GUI::AScope::VideoChannel::readerIncoming().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/AScope/History.h
/Users/howes/src/sidecar/GUI/AScope/History.cc