SideCar: SideCar::Zeroconf::Browser Class Reference
SideCar::Zeroconf::Browser Class Reference
Zeroconf browser for information regarding available SideCar services.
#include </Users/howes/src/sidecar/Zeroconf/Browser.h>
Public Types
using Ref = boost::shared_ptr< Browser >
using ServiceEntryVector = std::vector< ServiceEntry::Ref >
using ServiceEntryMap = std::map< std::string, ServiceEntry::Ref >
using Signal = boost::signals2::signal< void(const ServiceEntryVector &)>
using SignalProc = Signal::slot_function_type
using SignalConnection = boost::signals2::connection
Public Types inherited from SideCar::Zeroconf::Transaction
using Ref = boost::shared_ptr< Transaction >
Public Member Functions
~Browser ()
Destructor.
const std::string & getType () const
Obtain the name of the publisher data type to browse for.
const std::string & getDomain () const
Obtain the name of the domain to search in.
uint32_t getInterface () const
Obtain the index of the interface to browse on.
void setType (const std::string &type)
Change the type of the service being browsed for.
void setDomain (const std::string &domain)
Change the domain of the service being browsed for.
void setInterface (uint32_t interface)
Change the interface to browse on.
SignalConnection connectToFoundSignal (SignalProc observer)
Connect an observer to the FoundSignal signal to receive a notification when a new service has been found by the browser.
SignalConnection connectToLostSignal (SignalProc observer)
Connect an observer to the LostSignal signal to receive a notification when a service has been dropped.
bool start ()
Start the browser.
Public Member Functions inherited from SideCar::Zeroconf::Transaction
virtual ~Transaction ()
Destructor.
bool stop ()
Stop a Zeroconf service.
bool isRunning () const
Determine if a Zeroconf service is running.
int getConnection () const
Obtain the underlying IPC descriptor used to communicate with the Zeroconf daemon.
bool processConnection ()
Data is available from the Zeroconf daemon.
Static Public Member Functions
static Logger::Log & Log ()
Log device for all Publisher objects.
static Ref Make (const MonitorFactory::Ref &monitorFactory, const std::string &type)
Factory method used to create a new Browser instance.
Static Public Member Functions inherited from SideCar::Zeroconf::Transaction
static Logger::Log & Log ()
Obtain the log device for all Transaction objects.
Additional Inherited Members
Protected Member Functions inherited from SideCar::Zeroconf::Transaction
Transaction (Monitor *monitor)
Constructor.
virtual void serviceStarted ()
Hook for derived classes for notification that a service has started.
virtual void serviceStopping ()
Hook for derived classes for notification that a sservice is being stopped.
void setSelf (const Ref &self)
Set a weak reference to ourselves so that we can give out shared_ptr refences to ourselves.
void finished ()
void finish ()
template<typename T >
boost::shared_ptr< T > getSelf () const
Obtain a shared_ptr reference to ourselves.
DNSServiceRef & getDNSServiceRef ()
const DNSServiceRef & getDNSServiceRef () const
Detailed Description
Zeroconf browser for information regarding available SideCar services.
Each Browser instance maintains a connection to the multicast DNS (mdsn) server running locally. The mdns server notifies the browser when new services become available or die via the BrowseCallback() class method. The browser in turn notifies clients that registered themselves with the connectToFoundSignal() and connectToLostSignal() methods.
Each found service is represented by a ServiceEntry object. The life-time of the ServiceEntry object is the time between found and lost notifications; after the lost notification signal, clients must no longer access in any way the ServiceEntry object revealed in the lost notification.
Publishing information to a mdns server is performed by the Publisher class.
Definition at line 31 of file Browser.h.
Constructor & Destructor Documentation
Browser::~Browser ()
Destructor.
Stops the browser if not already stopped.
Definition at line 33 of file Browser.cc.
References SideCar::Zeroconf::Transaction::stop().
Member Function Documentation
SignalConnection SideCar::Zeroconf::Browser::connectToFoundSignal (SignalProc observer) inline
Connect an observer to the FoundSignal signal to receive a notification when a new service has been found by the browser.
The observer must be a function object that takes three parameters:
Browser::Ref - the browser that found the service
ServiceEntry::Ref - the service that waS found
bool - true if there are more notifications on the way
To disconnect, simply invoke the disconnect() method of the returned object.
\param observer object to receive notifications
\return object identifying the signal connection
Definition at line 119 of file Browser.h.
SignalConnection SideCar::Zeroconf::Browser::connectToLostSignal (SignalProc observer) inline
Connect an observer to the LostSignal signal to receive a notification when a service has been dropped.
The observer must be a function object that takes three parameters:
Browser::Ref - the browser that sent the notification
ServiceEntry::Ref - the service that was lost
bool - true if there are more notifications on the way
To disconnect, simply invoke the disconnect() method of the returned object.
\param observer object to receive notifications
\return object identifying the signal connection
Definition at line 135 of file Browser.h.
const std::string& SideCar::Zeroconf::Browser::getDomain () const inline
Obtain the name of the domain to search in.
The default value is "local."
Returns
domain name
Definition at line 75 of file Browser.h.
uint32_t SideCar::Zeroconf::Browser::getInterface () const inline
Obtain the index of the interface to browse on.
The default value is zero, which browses on all active interfaces. Use if_indextoname() to convert non-zero index value into a name value.
Returns
interface index
Definition at line 82 of file Browser.h.
const std::string& SideCar::Zeroconf::Browser::getType () const inline
Obtain the name of the publisher data type to browse for.
Returns
publisher data type
Definition at line 69 of file Browser.h.
Logger::Log & Browser::Log () static
Log device for all Publisher objects.
Returns
log device
Definition at line 10 of file Browser.cc.
References Logger::Log::Find().
Referenced by Make(), and start().
Browser::Ref Browser::Make (const MonitorFactory::Ref & monitorFactory, const std::string & type) static
Factory method used to create a new Browser instance.
Browses in the default domain ('.'), and on all network interfaces.
Parameters
monitorFactory creator of Monitor objects for ServiceEntry objects
type what to browse for
\return reference to new Browser
Definition at line 17 of file Browser.cc.
References Log(), and LOGINFO.
Referenced by SideCar::Algorithms::BugCollectorUtils::BugPlotSubscriber::BugPlotSubscriber(), SideCar::IO::StateEmitter::Log(), SideCar::IO::StatusEmitterBase::Log(), and SideCar::IO::DataSubscriber::openAndInit().
void SideCar::Zeroconf::Browser::setDomain (const std::string & domain) inline
Change the domain of the service being browsed for.
Note that the change does not affect any publishing that is in effect; one must stop() and then start() to have the change take effect.
Parameters
domain the new service domain
Definition at line 96 of file Browser.h.
void SideCar::Zeroconf::Browser::setInterface (uint32_t interface) inline
Change the interface to browse on.
Hosts may have more than one network interface active. The default behavior of mdns is to publish connection information on all active interfaces. Use this method to restrict publishing to a specific network interface.
Parameters
interface network interface to use
Definition at line 104 of file Browser.h.
void SideCar::Zeroconf::Browser::setType (const std::string & type) inline
Change the type of the service being browsed for.
Note that the change does not affect an active browser; one must stop() and then start() to have the change toke affect.
Parameters
type the new service type
Definition at line 89 of file Browser.h.
bool Browser::start ()
Start the browser.
To stop, invoke stop().
Returns
true if successful, false otherwise
Definition at line 39 of file Browser.cc.
References SideCar::Zeroconf::Transaction::isRunning(), Log(), LOGERROR, LOGINFO, SideCar::Zeroconf::Transaction::serviceStarted(), and SideCar::Zeroconf::Transaction::stop().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Zeroconf/Browser.h
/Users/howes/src/sidecar/Zeroconf/Browser.cc