SideCar: SideCar::GUI::QColorSetting Class Reference
SideCar::GUI::QColorSetting Class Reference
Derivation of the Setting class that works with QColor values.
#include </Users/howes/src/sidecar/GUI/QColorSetting.h>
Public Slots
void setValue (const QColor &color)
Change the setting value.
Public Slots inherited from SideCar::GUI::Setting
void setEnabled (bool state)
Signals
void valueChanged (const QColor &color)
Notification sent out when the held value changes.
Signals inherited from SideCar::GUI::Setting
void save (int index, const QVariant &value)
Notification sent out by the Setting object when the held value changes due to the setValue() method.
void enabledChanged (bool state)
Notification sent out by the Setting object when its enabled state changes.
void valueChanged ()
Public Member Functions
QColorSetting (PresetManager *mgr, const QString &name, const QColor &color, bool global=false)
Constructor with initial default value.
const QColor & getValue () const
Obtain the current setting value.
void connectWidget (ColorButtonWidget *widget)
Public Member Functions inherited from SideCar::GUI::Setting
Setting (PresetManager *mgr, const QString &name, bool global=false)
Constructor without a default setting value.
Setting (PresetManager *mgr, const QString &name, const QVariant &value, bool global=false)
Constructor with a default setting value.
const QString & getName () const
Obtain the name of the Setting object.
const QVariant & getOpaqueValue () const
Obtain the current value of the Setting object.
void setOpaqueValue (const QVariant &value)
Set the Setting's value and emit the opaqueValueChanged() signal followed by the save() signal.
bool isEnabled () const
Protected Member Functions
void valueUpdated ()
Override of Setting method.
Protected Member Functions inherited from SideCar::GUI::Setting
void resetOpaqueValue ()
void connectWidget (QWidget *widget)
void disconnectWidget (QWidget *widget)
Additional Inherited Members
Static Public Member Functions inherited from SideCar::GUI::Setting
static Logger::Log & Log ()
Log device for Setting objects.
Detailed Description
Derivation of the Setting class that works with QColor values.
Definition at line 15 of file QColorSetting.h.
Constructor & Destructor Documentation
QColorSetting::QColorSetting (PresetManager * mgr, const QString & name, const QColor & color, bool global = false)
Constructor with initial default value.
Parameters
mgr PresetManager object that records this setting
name the name of the setting
color initial value to use for the setting if one is not recorded
global if true, this is a global setting, not associated with a specific Preset.
Definition at line 7 of file QColorSetting.cc.
Member Function Documentation
const QColor& SideCar::GUI::QColorSetting::getValue () const inline
Obtain the current setting value.
Returns
setting value
Definition at line 39 of file QColorSetting.h.
References setValue(), valueChanged(), and valueUpdated().
Referenced by SideCar::GUI::ChannelImaging::ChannelImaging(), and valueUpdated().
void QColorSetting::setValue (const QColor & color) slot
Change the setting value.
Emits the valueChanged() signal if the given value is different from the held one.
Parameters
color new value to use
Definition at line 15 of file QColorSetting.cc.
References SideCar::GUI::Setting::setOpaqueValue().
Referenced by getValue(), and valueUpdated().
void SideCar::GUI::QColorSetting::valueChanged (const QColor & color) signal
Notification sent out when the held value changes.
Parameters
color new held value
Referenced by getValue(), and valueUpdated().
void QColorSetting::valueUpdated () protected virtual
Override of Setting method.
Updates value_ attribute with new value and emits valueChanged() signal.
Reimplemented from SideCar::GUI::Setting.
Definition at line 24 of file QColorSetting.cc.
References SideCar::GUI::Setting::getOpaqueValue(), getValue(), setValue(), and valueChanged().
Referenced by getValue().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/QColorSetting.h
/Users/howes/src/sidecar/GUI/QColorSetting.cc