SideCar: Threading::Thread Class Reference
Threading::Thread Class Reference abstract
Abstract base class representation of a thread.
#include </Users/howes/src/sidecar/Threading/Threading.h>
Data Structures
struct Exception
Top-level exception class for all Thread-related exceptions.
struct FailedCancel
Exception thrown if there is a problem with pthread_create.
struct FailedCreate
Exception thrown if there is a problem with pthread_create.
struct FailedJoin
Exception thrown if there is a problem with pthread_create.
Public Member Functions
Thread () throw (Condition::FailedInit, Mutex::FailedInit)
Constructor.
virtual ~Thread ()
Destructor.
pthread_t getThreadId () const throw ()
Fetch the thread ID.
bool isRunning () throw (Mutex::FailedLock)
void waitToFinish () throw (Mutex::FailedLock)
Pause the current thread until the thread represented by this instance has finished running.
bool detach () throw ()
Detach the running thread so that a join() call is unnecessary to clean up thread-specific memory when the thread run() method finishes.
bool join () throw (Thread::FailedJoin)
Another thread wishes to consume the one we represent.
void cancel () throw (Thread::FailedCancel)
Request that a our thread be canceled.
bool operator== (const Thread &rhs) const throw ()
See if two Thread objects represent the same thread.
bool operator!= (const Thread &rhs) const throw ()
See if two Thread objects do not represent the same thread.
bool isActive () const throw ()
void start () throw (FailedCreate, Mutex::FailedLock, Condition::FailedInit)
Start a new thread.
Static Public Member Functions
static void Sleep (double duration) throw (std::out_of_range)
Utility to pause a thread for some amount of time.
static pthread_t Self ()
Protected Member Functions
virtual void run ()=0
Thread-specific code to run when Thread::start is called.
Detailed Description
Abstract base class representation of a thread.
When a new Thread instance is created, it is running in the thread that created it. To actually start a new thread, call the instance method Thread::start. New threads invoke the Thread::run method which must be defined by derived classes.
Definition at line 305 of file Threading.h.
Constructor & Destructor Documentation
Thread::~Thread () virtual
Destructor.
Release system-dependent resources.
Definition at line 358 of file Threading.cc.
Member Function Documentation
void Thread::cancel () throw (Thread::FailedCancel)
Request that a our thread be canceled.
A thread cancellation is deferred until the thread reaches a cancellation point. Note that usually a call to join() should follow a cancel request, but is not mandatory.
Definition at line 397 of file Threading.cc.
bool Thread::detach () throw ()
Detach the running thread so that a join() call is unnecessary to clean up thread-specific memory when the thread run() method finishes.
Returns
true if successful
Definition at line 381 of file Threading.cc.
pthread_t Threading::Thread::getThreadId () const throw () inline
Fetch the thread ID.
Returns
thread ID
Definition at line 350 of file Threading.h.
bool Threading::Thread::isActive () const throw () inline
Returns
true if this instance represents the thread currently executing
Definition at line 400 of file Threading.h.
References Utils::Exception::operator=().
bool Thread::isRunning () throw (Mutex::FailedLock)
Returns
true if the thread is still running. Not necessarily thread-safe, but for the resolution required vs. the cost of locking this attribute, its OK.
Definition at line 371 of file Threading.cc.
bool Thread::join () throw (Thread::FailedJoin)
Another thread wishes to consume the one we represent.
This method will block the calling thread until our thread exits.
Returns
true if pthread_join was successful; false if our thread has already terminated and has joined with another thread.
Definition at line 388 of file Threading.cc.
Referenced by Utils::FileWatcher::Monitor::run().
bool Threading::Thread::operator!= (const Thread & rhs) const throw () inline
See if two Thread objects do not represent the same thread.
Parameters
rhs Thread object to compare with
Returns
true if not the same
Definition at line 396 of file Threading.h.
bool Thread::operator== (const Thread & rhs) const throw ()
See if two Thread objects represent the same thread.
Parameters
rhs Thread object to compare with
Returns
true if same
Definition at line 405 of file Threading.cc.
virtual void Threading::Thread::run () protected pure virtual
Thread-specific code to run when Thread::start is called.
Derived classes must define.
Implemented in Utils::FileWatcher::Monitor.
void Thread::Sleep (double duration) throw (std::out_of_range) static
Utility to pause a thread for some amount of time.
Other threads can run while this one is sleeping.
Parameters
duration amount of time to pause, in seconds/microseconds
Definition at line 221 of file Threading.cc.
void Thread::start () throw (FailedCreate, Mutex::FailedLock, Condition::FailedInit)
Start a new thread.
The new thread will invoke Thread::run, which must be defined by derived classes. Creates a new Starter object to do the actually starting. Call will not return until the new thread is up and running.
Definition at line 332 of file Threading.cc.
Referenced by Utils::FileWatcher::getModificationTime().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Threading/Threading.h
/Users/howes/src/sidecar/Threading/Threading.cc