SideCar: UnitTest::RunResults Class Reference
UnitTest::RunResults Class Reference
Records statistics for all unit tests run.
#include </Users/howes/src/sidecar/UnitTest/RunResults.h>
Public Member Functions
RunResults () throw ()
Default constructor.
void addOK (const std::string &s) throw ()
Add a test name that passed.
void addError (const UnitTestException &e) throw ()
Add an exception to the list of errors.
void addFailure (const UnitTestException &e) throw ()
Add an exception to the list of failures.
int numGood () const throw ()
int numErrors () const throw ()
int numFailures () const throw ()
int numBad () const throw ()
bool passed () const throw ()
operator bool () const throw ()
Test if any errors or failures (! passed()).
bool isStopped () const throw ()
void stopRun () throw ()
Stop running.
std::ostream & printText (std::ostream &os) const throw ()
Write formatted text statistics to the given stream.
std::ostream & printXML (std::ostream &os) const throw ()
Write XML statistics to the given stream.
Detailed Description
Records statistics for all unit tests run.
If any unit test throws an exception, we keep a copy of it. There are two types of exceptions covered: failures (represented by TestException exceptions) and errors (caused by anything else). The former represents a unit test that failed to pass, whereas the latter represents a problem running the test.
Definition at line 18 of file RunResults.h.
Member Function Documentation
void UnitTest::RunResults::addError (const UnitTestException & e) throw () inline
Add an exception to the list of errors.
Parameters
e exception to record.
Definition at line 37 of file RunResults.h.
void UnitTest::RunResults::addFailure (const UnitTestException & e) throw () inline
Add an exception to the list of failures.
Parameters
e exception to record.
Definition at line 43 of file RunResults.h.
void UnitTest::RunResults::addOK (const std::string & s) throw () inline
Add a test name that passed.
Parameters
s the test name that passed
Definition at line 31 of file RunResults.h.
bool UnitTest::RunResults::isStopped () const throw () inline
Returns
true if asked to stop running.
Definition at line 73 of file RunResults.h.
int UnitTest::RunResults::numBad () const throw () inline
Returns
count of unit tests that did not pass. This is the sum of numErrors and numFailures.
Definition at line 59 of file RunResults.h.
References numErrors(), and numFailures().
Referenced by passed().
int UnitTest::RunResults::numErrors () const throw () inline
Returns
the number of unit tests with errors.
Definition at line 51 of file RunResults.h.
Referenced by numBad().
int UnitTest::RunResults::numFailures () const throw () inline
Returns
the number of unit tests that failed to pass.
Definition at line 55 of file RunResults.h.
Referenced by numBad().
int UnitTest::RunResults::numGood () const throw () inline
Returns
the number of good tests so far
Definition at line 47 of file RunResults.h.
UnitTest::RunResults::operator bool () const throw () inline
Test if any errors or failures (! passed()).
Returns
true if any errors or failures
Definition at line 69 of file RunResults.h.
References passed().
bool UnitTest::RunResults::passed () const throw () inline
Returns
true if all unit tests passed (numBad() == 0)
Definition at line 63 of file RunResults.h.
References numBad().
Referenced by operator bool().
std::ostream & RunResults::printText (std::ostream & os) const throw ()
Write formatted text statistics to the given stream.
Parameters
os stream to write to
Definition at line 50 of file RunResults.cc.
Referenced by stopRun().
std::ostream & RunResults::printXML (std::ostream & os) const throw ()
Write XML statistics to the given stream.
Parameters
os stream to write to
Definition at line 121 of file RunResults.cc.
Referenced by stopRun().
void UnitTest::RunResults::stopRun () throw () inline
Stop running.
Do not start any future tests.
Definition at line 77 of file RunResults.h.
References printText(), and printXML().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/UnitTest/RunResults.h
/Users/howes/src/sidecar/UnitTest/RunResults.cc