SideCar: Utils::FileWatcher Class Reference
Utils::FileWatcher Class Reference abstract
Abstract base class that monitors a file for changes to its modification timestamp.
#include </Users/howes/src/sidecar/Utils/FileWatcher.h>
Data Structures
struct Monitor
Public Member Functions
FileWatcher (double period=10.0)
Constructor.
virtual ~FileWatcher ()
Destructor.
bool setFilePath (const std::string &path)
Set the path to a file to watch.
time_t getModificationTime () const
Obtain the modification time of the active file.
bool isStale () const
Determine if the file has been modified since the last load.
bool check ()
Check to see if the watched file has changed since the last load.
bool reload ()
Reload a file and update the load timestamp.
Static Public Member Functions
static Logger::Log & Log ()
Log device for RadarConfig messages.
Protected Member Functions
virtual bool loadFile (const std::string &path)=0
Notification that the file has new contents.
virtual void start ()
virtual void stop ()
Detailed Description
Abstract base class that monitors a file for changes to its modification timestamp.
Derived clases must define a loadFile() method to do the actual loading.
Definition at line 11 of file FileWatcher.h.
Constructor & Destructor Documentation
FileWatcher::FileWatcher (double period = 10.0)
Constructor.
Parameters
period number of seconds to wait between checks for file changes
Definition at line 62 of file FileWatcher.cc.
FileWatcher::~FileWatcher () virtual
Destructor.
Shuts down and disposes of any active monitor object.
Definition at line 70 of file FileWatcher.cc.
Member Function Documentation
bool Utils::FileWatcher::check () inline
Check to see if the watched file has changed since the last load.
If file is not stale, nothing is done, but routine still returns true.
Returns
true if successful or file is not stale
Definition at line 58 of file FileWatcher.h.
time_t FileWatcher::getModificationTime () const
Obtain the modification time of the active file.
Only valid after setFilePath().
Returns
modification time of the file or time_t(-1) if file no longer exists.
Definition at line 76 of file FileWatcher.cc.
References Log(), LOGDEBUG, LOGINFO, LOGWARNING, and Threading::Thread::start().
Referenced by reload().
bool Utils::FileWatcher::isStale () const inline
Determine if the file has been modified since the last load.
Returns
true if so
Definition at line 51 of file FileWatcher.h.
virtual bool Utils::FileWatcher::loadFile (const std::string & path) protected pure virtual
Notification that the file has new contents.
Derived classes must define.
Parameters
path configured file path
Returns
true if successful
Referenced by reload().
Logger::Log & FileWatcher::Log () static
Log device for RadarConfig messages.
Returns
Log device
Definition at line 56 of file FileWatcher.cc.
References Logger::Log::Find().
Referenced by getModificationTime(), reload(), Utils::FileWatcher::Monitor::run(), and setFilePath().
bool FileWatcher::reload ()
Reload a file and update the load timestamp.
Invokes loadFile to do the actual work.
Returns
true if successful
Definition at line 128 of file FileWatcher.cc.
References getModificationTime(), loadFile(), Log(), LOGDEBUG, and LOGERROR.
Referenced by setFilePath().
bool FileWatcher::setFilePath (const std::string & path)
Set the path to a file to watch.
Invokes the virtual function loadFile() to signal derived classes to work with the file.
Parameters
path file path
Returns
true if successful
Definition at line 109 of file FileWatcher.cc.
References Log(), LOGERROR, LOGINFO, and reload().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Utils/FileWatcher.h
/Users/howes/src/sidecar/Utils/FileWatcher.cc