SideCar: SideCar::Geometry::Vector Class Reference
SideCar::Geometry::Vector Class Reference
Tuple representing a vector in 3-D space.
#include </Users/howes/src/sidecar/Algorithms/ABTracker/Vector.h>
Public Member Functions
Vector ()
Default constructor.
Vector (double x, double y, double z)
Constructor using component values.
Vector (const UnitVector &direction, double length)
Constructor using direction and magnitude values.
Vector (const Vector &from, const Vector &to)
Constructor from two Vector objects.
double getX () const
Obtain the X component.
double getY () const
Obtain the Y component.
double getZ () const
Obtain the Z component.
double getMagnitude () const
Obtain the magnitude of the vector.
double getMagnitudeSquared () const
Obtain the squared magnitude of the vector.
double getDirection () const
Obtain the angle in radians of the vector in the X/Y plane and the Y axis (north)
double getElevation () const
Obtain the angle in radians of the vector in the Z/Y plane and the Y axis (0 elevation).
Vector & operator+= (const Vector &rhs)
Add component values from another vector to this one.
Vector & operator-= (const Vector &rhs)
Subtract component values of another vector from this one.
Vector & operator*= (double scale)
Multiply component vales by a given value.
Vector & operator/= (double scale)
Divide component vales by a given value.
std::ostream & print (std::ostream &os) const
Write out a textual representation of the Vector to the given C++ output stream.
Detailed Description
Tuple representing a vector in 3-D space.
Supports basic vector/vector and vector/scalar operations. Borrowed from RWSL project. Calculates on demand magnitude and direction values.
NOTE: not sure if elevation and Z axis are handled properly. Need to be vetted.
Definition at line 17 of file Vector.h.
Constructor & Destructor Documentation
Vector::Vector (double x, double y, double z)
Constructor using component values.
Parameters
x length of vector along X axis
y length of vector along Y axis
z length of vector along Z axis
Definition at line 17 of file Vector.cc.
Vector::Vector (const UnitVector & direction, double length)
Constructor using direction and magnitude values.
Parameters
direction UnitVector representing the direction of the vector
length the magnitude of the vector
Definition at line 29 of file Vector.cc.
Vector::Vector (const Vector & from, const Vector & to)
Constructor from two Vector objects.
Calculates the difference between the two.
Parameters
from starting vector
to ending vector
Definition at line 23 of file Vector.cc.
Member Function Documentation
double Vector::getDirection () const
Obtain the angle in radians of the vector in the X/Y plane and the Y axis (north)
Returns
angle in radians
Definition at line 65 of file Vector.cc.
Referenced by getZ().
double Vector::getElevation () const
Obtain the angle in radians of the vector in the Z/Y plane and the Y axis (0 elevation).
A well-formed vector would only have values in [0-PI/4].
Returns
angle in radians
Definition at line 81 of file Vector.cc.
References getMagnitude().
Referenced by getZ().
double Vector::getMagnitude () const
Obtain the magnitude of the vector.
Returns
SQRT(X*X + Y*Y + Z*Z)
Definition at line 54 of file Vector.cc.
References getMagnitudeSquared().
Referenced by getElevation(), and getZ().
double Vector::getMagnitudeSquared () const
Obtain the squared magnitude of the vector.
Returns
X*X + Y*Y + Z*Z
Definition at line 38 of file Vector.cc.
Referenced by getMagnitude(), SideCar::Algorithms::ABTrackerUtils::Track::getProximityTo(), and getZ().
double SideCar::Geometry::Vector::getX () const inline
Obtain the X component.
Returns
length along X axis
Definition at line 55 of file Vector.h.
double SideCar::Geometry::Vector::getY () const inline
Obtain the Y component.
Returns
length along Y axis
Definition at line 61 of file Vector.h.
double SideCar::Geometry::Vector::getZ () const inline
Obtain the Z component.
Returns
length along Z axis
Definition at line 67 of file Vector.h.
References getDirection(), getElevation(), getMagnitude(), getMagnitudeSquared(), operator*=(), operator+=(), operator-=(), operator/=(), and print().
Vector & Vector::operator*= (double scale)
Multiply component vales by a given value.
Parameters
scale value to multiply with
Returns
reference to self
Definition at line 118 of file Vector.cc.
Referenced by getZ(), and operator/=().
Vector & Vector::operator+= (const Vector & rhs)
Add component values from another vector to this one.
Parameters
rhs vector to add
Returns
reference to self
Definition at line 98 of file Vector.cc.
Referenced by getZ().
Vector & Vector::operator-= (const Vector & rhs)
Subtract component values of another vector from this one.
Parameters
rhs vector to subtract
Returns
reference to self
Definition at line 108 of file Vector.cc.
Referenced by getZ().
Vector & Vector::operator/= (double scale)
Divide component vales by a given value.
Parameters
scale value to divide with
Returns
reference to self
Definition at line 128 of file Vector.cc.
References operator*=().
Referenced by getZ().
std::ostream& SideCar::Geometry::Vector::print (std::ostream & os) const
Write out a textual representation of the Vector to the given C++ output stream.
Parameters
os stream to write to
Returns
stream written to
Referenced by getZ().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/ABTracker/Vector.h
/Users/howes/src/sidecar/Algorithms/ABTracker/Vector.cc