SideCar: SideCar::GUI::ColorMapWidget Class Reference
SideCar::GUI::ColorMapWidget Class Reference
Floating tool window that shows the message time for the data shown in a PPIWidget, and the range/azimuth values for the cursor.
#include </Users/howes/src/sidecar/GUI/ColorMapWidget.h>
Public Slots
void setColorMap (const QImage &colorMap)
Signals
void changeColorMapType (int index)
Public Member Functions
ColorMapWidget (VideoSampleCountTransform *transform, QWidget *parent=0)
Constructor.
Detailed Description
Floating tool window that shows the message time for the data shown in a PPIWidget, and the range/azimuth values for the cursor.
The message values may be current or historical.
Definition at line 17 of file ColorMapWidget.h.
Constructor & Destructor Documentation
ColorMapWidget::ColorMapWidget (VideoSampleCountTransform * transform, QWidget * parent = 0)
Constructor.
Creates and initializes window widgets.
Definition at line 14 of file ColorMapWidget.cc.
References SideCar::GUI::VideoSampleCountTransform::getSampleMax(), SideCar::GUI::VideoSampleCountTransform::getSampleMin(), SideCar::GUI::VideoSampleCountTransform::getShowDecibels(), SideCar::GUI::VideoSampleCountTransform::getThresholdMax(), SideCar::GUI::VideoSampleCountTransform::getThresholdMin(), and SideCar::GUI::CLUT::GetTypeName().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/ColorMapWidget.h
/Users/howes/src/sidecar/GUI/ColorMapWidget.cc