SideCar: SideCar::IO::ChannelVector Class Reference
SideCar::IO::ChannelVector Class Reference
Collection of Channel objects.
#include </Users/howes/src/sidecar/IO/Channel.h>
Public Types
using Container = std::vector< Channel >
Public Member Functions
ChannelVector ()
Default constructor.
size_t size () const
Obtain the number of channels in the container.
bool empty () const
Determine if the container is empty.
void add (const Channel &channel)
Add a new Channel object to the end of the collection.
const Channel & getChannel (size_t index) const
Obtain the Channel object at a given index of the container.
size_t findName (const std::string &name) const
Obtain the index of the first Channel object that has a given name.
const Channel & getChannel (const std::string &name) const
Obtain the Channel object at a given index of the container.
bool containsChannel (const std::string &name) const
Determine if a given name exists in the container.
void updateSendersUsingData (bool value)
Invoke Channel::updateSenderUsingData() for each Channel in this container.
bool areAnyRecipientsUsingData () const
Determine if there are any downstream recipients that demand data from the channel's sender.
Static Public Member Functions
static Logger::Log & Log ()
Detailed Description
Collection of Channel objects.
Note that the collection holds actual Channel objects, not their pointers. Currently, the SideCar software only supports adding Channel objects, and most Tasks only have one input or one output, so most ChannelVector objects are very small. If these operating characteristics change, we should reconsider the types held in a ChannelVector, possibly holding a boost::shared_ptr<Channel> instead.
Definition at line 129 of file Channel.h.
Member Function Documentation
void ChannelVector::add (const Channel & channel)
Add a new Channel object to the end of the collection.
Parameters
channel object to append
Definition at line 36 of file Channel.cc.
References SideCar::IO::Channel::getName(), LOGINFO, and Logger::ProcLog::thrower().
bool ChannelVector::areAnyRecipientsUsingData () const
Determine if there are any downstream recipients that demand data from the channel's sender.
Note
Stops checking after any Channel returns true.
Returns
true if so
Definition at line 77 of file Channel.cc.
References SideCar::IO::Channel::areAnyRecipientsUsingData().
bool SideCar::IO::ChannelVector::containsChannel (const std::string & name) const inline
Determine if a given name exists in the container.
Parameters
name the channel name to look for
Returns
true if so
Definition at line 188 of file Channel.h.
bool SideCar::IO::ChannelVector::empty () const inline
Determine if the container is empty.
Returns
true if so
Definition at line 150 of file Channel.h.
size_t ChannelVector::findName (const std::string & name) const
Obtain the index of the first Channel object that has a given name.
Parameters
name the Channel name to look for
Returns
the index of the Channel, or size() if none found.
Definition at line 51 of file Channel.cc.
References SideCar::IO::Channel::getName(), and LOGINFO.
const Channel& SideCar::IO::ChannelVector::getChannel (size_t index) const inline
Obtain the Channel object at a given index of the container.
Parameters
index location to fetch
Returns
Channel reference
Definition at line 164 of file Channel.h.
Referenced by SideCar::IO::Task::doClearStatsRequest().
const Channel& SideCar::IO::ChannelVector::getChannel (const std::string & name) const inline
Obtain the Channel object at a given index of the container.
Parameters
index location to fetch
Returns
Channel reference
Definition at line 180 of file Channel.h.
size_t SideCar::IO::ChannelVector::size () const inline
Obtain the number of channels in the container.
Returns
channel count
Definition at line 144 of file Channel.h.
Referenced by SideCar::IO::Task::doClearStatsRequest().
void ChannelVector::updateSendersUsingData (bool value)
Invoke Channel::updateSenderUsingData() for each Channel in this container.
Parameters
value the new value to use
Definition at line 64 of file Channel.cc.
References LOGINFO.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/Channel.h
/Users/howes/src/sidecar/IO/Channel.cc