SideCar: SideCar::Messages::Track Class Reference
SideCar::Messages::Track Class Reference
Data Structures
struct Coord
Public Types
enum Flags {
kDropping = 1, kNew, kPromoted, kNeedsPrediction,
kNeedsCorrection, kPredicted, kCorrected
}
enum Type { kTentative = 1, kConfirmed }
using Ref = boost::shared_ptr< Track >
Public Types inherited from SideCar::Messages::Header
using Ref = boost::shared_ptr< Header >
Public Member Functions
~Track ()
Destructor.
ACE_InputCDR & load (ACE_InputCDR &cdr)
Read in a Track message from an CDR input stream.
ACE_OutputCDR & write (ACE_OutputCDR &cdr) const
Write out a Track message to a CDR output stream.
double getStartTime () const
Get and Set methods for class variables not inherited from TSPI.
void setStartTime (double time)
double getConfirmedTime () const
void setConfirmedTime (double time)
int getType () const
void setType (int t)
double getPredictionTime () const
void setPredictionTime (double time)
double getExtractionTime () const
void setExtractionTime (double time)
int getTrackNumber () const
void setTrackNumber (int n)
const Coord & getPrediction () const
void setPrediction (const Coord &llh)
const Coord & getVelocity () const
void setVelocity (const Coord &llh)
const Coord & getExtraction () const
void setExtraction (const Coord &aer)
int getExtractionNum () const
void setExtractionNum (int num)
int getBatchNum () const
void setBatchNum (int n)
int getTotalInBatch () const
void setTotalInBatch (int n)
uint16_t getFlags () const
void setFlags (uint16_t f)
const Coord & getEstimate () const
double getLatitude () const
double getLongitude () const
double getHeight () const
void setEstimate (const Coord &llh)
double getWhen () const
void setWhen (double when)
std::ostream & printData (std::ostream &os) const
Print out a textual representation of the Track message.
std::ostream & printDataXML (std::ostream &os) const
Write out the message data to a C++ text output stream in XML format.
void loadXML (XmlStreamReader &xsr)
Obtain new instance data from an XML input stream.
void dump () const
Public Member Functions inherited from SideCar::Messages::Header
Header (const MetaTypeInfo &metaTypeInfo)
Constructor for messages read in from an external device.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis, MetaTypeInfo::SequenceType sequenceNumber)
Constructor for new messages.
virtual ~Header ()
Destructor.
const MetaTypeInfo & getMetaTypeInfo () const
Obtain the type specification for the message.
const GUID & getGloballyUniqueID () const
Get the globally-unique ID of the message.
MetaTypeInfo::SequenceType getMessageSequenceNumber () const
Get the message sequence number for the message.
void setMessageSequenceNumber (MetaTypeInfo::SequenceType msn)
Set the sequence number for this message.
const Time::TimeStamp & getCreatedTimeStamp () const
Obtain when the message was created.
Time::TimeStamp setCreatedTimeStamp (const Time::TimeStamp &timeStamp)
Revise the creation message timestamp.
const Time::TimeStamp & getEmittedTimeStamp () const
Obtain when the message was written to an external device (file or network).
Time::TimeStamp setEmittedTimeStamp (const Time::TimeStamp &timeStamp)
Set the emitted time stamp with the given value.
virtual size_t getSize () const
Obtain the C++ structure size for this object.
HeaderPrinter headerPrinter () const
Convenience method that simply returns a new HeaderPrinter functor for this header object.
DataPrinter dataPrinter () const
Convenience method that simply returns a new DataPrinter functor for this header object.
XMLPrinter xmlPrinter () const
Convenience method that simply returns a new XMLPrinter functor for this header object.
virtual std::ostream & print (std::ostream &os) const
Write out the entire message to a C++ text output stream.
virtual std::ostream & printHeader (std::ostream &os) const
Write out the message header to a C++ text output stream.
virtual std::ostream & printXML (std::ostream &os) const
Write out the message to a C++ text output stream in XML format.
bool hasBasis () const
Determine if the message has a basis message attached to it.
Ref getBasis () const
Obtain a reference to the message that this one was based on.
template<typename T >
T::Ref getBasis () const
Templated version of the above method.
Static Public Member Functions
static Logger::Log & Log ()
static const MetaTypeInfo & GetMetaTypeInfo ()
static Ref Make (const std::string &producer)
static Ref Make (ACE_InputCDR &cdr)
static Ref Make (const std::string &producer, const Messages::Track::Ref &report)
Copy constructor copies the contents of report to the new Track message.
Static Public Member Functions inherited from SideCar::Messages::Header
static Logger::Log & Log ()
Obtain log device to use for objects of this class.
static const MetaTypeInfo * GetMessageMetaTypeInfo (ACE_InputCDR &cdr)
Additional Inherited Members
Detailed Description
Definition at line 20 of file Track.h.
Member Function Documentation
ACE_InputCDR & Track::load (ACE_InputCDR & cdr) virtual
Read in a Track message from an CDR input stream.
Override of Header::load().
Parameters
cdr stream to read from
Returns
stream read from
Reimplemented from SideCar::Messages::Header.
Definition at line 110 of file Track.cc.
References SideCar::Messages::TLoaderRegistry< T >::load(), and LOGINFO.
void Track::loadXML (XmlStreamReader & xsr) virtual
Obtain new instance data from an XML input stream.
Parameters
xsr stream to read from
Reimplemented from SideCar::Messages::Header.
Definition at line 248 of file Track.cc.
References SideCar::Messages::XmlStreamReader::getAttribute(), SideCar::Messages::Header::loadXML(), LOGERROR, and SideCar::Messages::XmlStreamReader::readNextEntityAndValidate().
Track::Ref Track::Make (const std::string & producer, const Messages::Track::Ref & report) static
Copy constructor copies the contents of report to the new Track message.
Copy constructor.
Definition at line 57 of file Track.cc.
std::ostream & Track::printData (std::ostream & os) const virtual
Print out a textual representation of the Track message.
Override of Header::print().
Parameters
os C++ text stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Definition at line 207 of file Track.cc.
std::ostream & Track::printDataXML (std::ostream & os) const virtual
Write out the message data to a C++ text output stream in XML format.
Parameters
os stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Definition at line 236 of file Track.cc.
ACE_OutputCDR & Track::write (ACE_OutputCDR & cdr) const virtual
Write out a Track message to a CDR output stream.
Override of Header::write().
Parameters
cdr stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Definition at line 164 of file Track.cc.
References SideCar::Messages::VoidLoaderRegistry::getCurrentVersion(), and SideCar::Messages::Header::write().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Messages/Track.h
/Users/howes/src/sidecar/Messages/Track.cc