SideCar: SideCar::Algorithms::IQFilter Class Reference
SideCar::Algorithms::IQFilter Class Reference
Conversion filter from I/Q (complex) messages into Video message format.
#include </Users/howes/src/sidecar/Algorithms/iqfilter/IQFilter.h>
Public Types
enum InfoSlot { kFilterType = ControllerStatus::kNumSlots, kEnabled, kNumSlots }
enum FilterType {
kMinValue = 0, kLogSqrtSumIQSquared = kMinValue, kSqrtSumIQSquared, kSumIQSquared,
kISamples, kQSamples, kPhaseAngle, kMaxValue = kPhaseAngle,
kNumFilterTypes
}
Filtering options available via the Master GUI application.
Public Member Functions
IQFilter (Controller &controller, Logger::Log &log)
Constructor.
void setFilterType (int filterType)
bool startup ()
Implementation of the Algorithm::startup interface.
size_t getNumInfoSlots () const
Obtain the number of data slots found in the ControllerStatus XML array.
void setInfoSlots (IO::StatusBase &status)
Obtain custom status information from an algorithm.
Public Member Functions inherited from SideCar::Algorithms::Algorithm
Algorithm (Controller &controller, Logger::Log &log)
Constructor.
virtual ~Algorithm ()
Destructor.
Controller & getController () const
Obtain the Controller object managing the algorithm.
Logger::Log & getLog () const
Obtain the log device to use for by the algorithm for log messages.
const std::string & getName () const
Obtain the name of the algorithm.
bool registerParameter (const Parameter::Ref &parameter)
Add a configuration parameter to the runtime system.
bool unregisterParameter (const Parameter::Ref &parameter)
Remove a configuration parameter from the runtime system.
template<typename A , typename M >
void registerProcessor (boost::function< bool(A *, typename M::Ref)> proc)
Install a method to process a particular message type.
template<typename A , typename M >
void registerProcessor (const std::string &channelName, boost::function< bool(A *, typename M::Ref)> proc)
Same as above method, but allows user to pick the channel by name.
template<typename A , typename M >
void registerProcessor (size_t channelIndex, boost::function< bool(A *, typename M::Ref)> proc)
Same as above method, but allows user to pick the channel by index.
template<typename A >
void registerProcessor (const std::string &channelName, const Messages::MetaTypeInfo &metaTypeInfo, boost::function< bool(A *, typename Messages::Header::Ref)> proc)
template<typename A >
void registerProcessor (size_t channelIndex, const Messages::MetaTypeInfo &metaTypeInfo, boost::function< bool(A *, typename Messages::Header::Ref)> proc)
size_t addProcessor (const std::string &channelName, const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
size_t addProcessor (const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
size_t addProcessor (size_t index, const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
void removeProcessor (size_t index)
Remove a processor from a given channel.
size_t getOutputChannelIndex (const std::string &name) const
Obtain an output channel index with a given name.
bool send (const Messages::Header::Ref &msg, size_t channelIndex=0)
Submit a message object to the controller for sending out on a given data channel.
bool sendAsIs (const Messages::Header::Ref &msg, size_t channelIndex=0)
Hand a message to the controller for sending out on a given data channel.
size_t getActiveChannelIndex () const
Obtain the index of the input channel that last received a message for the algorithm to process.
Additional Inherited Members
Static Public Member Functions inherited from SideCar::Algorithms::Algorithm
static void * FormatInfoValue (const QString &value)
Obtain a C-safe value for the given QString string.
static void * FormatInfoValue (const char *value)
Obtain a C-safe value for the given character string.
Protected Member Functions inherited from SideCar::Algorithms::Algorithm
void setAlarm (int secs)
This method can be used by an Algorithm to schedule a periodic alarm to go off for itself.
virtual bool reset ()
Hook called when the algorithm is transitioning from a stopped to a running state (one of Task::kAutoDiagnostic, Task::kCalibrate, or Task::kRun).
virtual bool clearStats ()
Hook called when the algorithm is commaned to clear any statistics.
virtual bool beginAutoDiag ()
Hook called when the algorithm is entering the Task::kAutoDiagnostic state.
virtual bool beginCalibration ()
Hook called when the algorithm is entering the Task::kCalibrate state.
virtual bool beginRun ()
Hook called when the algorithm is entering the Task::kRun state.
virtual bool stop ()
Hook called when the algorithm is entering the Task::kStop state.
virtual bool shutdown ()
Hook called when the processing system shuts down.
virtual void recordingStarted ()
Hook called when a recording has started.
virtual void recordingStopped ()
Hook called when a recording has stopped.
virtual void beginParameterChanges ()
Hook called just before algorithm runtime parameters are changed.
virtual void endParameterChanges ()
Hook called just after algorithm runtime parameters have been changed.
virtual void processAlarm ()
This method will get called whenever an alarm expires for this Algorithm.
Detailed Description
Conversion filter from I/Q (complex) messages into Video message format.
Output messages can be in one of 5 formats:
results of 10 * log10(sqrt(I * I + Q * Q))
results of sqrt(I * I + Q * Q)
results of I * I + Q * Q
actual I samples
actual Q samples
phase angle atan2(Q, I)
The IQFilter can accept data in either Video or the new Complex format. Which format is used depends on the XML configuration used to start the IQFilter. To accept Video messages, use
<input type="Video">
Likewise, to accept Complex messages, add
<input type="Complex">
Note that for either input, there must be a message provider in the XML file that has a matching output type, or else the algorithm will fail to start up.
Definition at line 40 of file IQFilter.h.
Constructor & Destructor Documentation
IQFilter::IQFilter (Controller & controller, Logger::Log & log)
Constructor.
Parameters
controller object that controls us
log device used for log messages
Definition at line 27 of file IQFilter.cc.
Referenced by setInfoSlots().
Member Function Documentation
size_t SideCar::Algorithms::IQFilter::getNumInfoSlots () const inline virtual
Obtain the number of data slots found in the ControllerStatus XML array.
Any custom Algorithm slots will appear after the last defined ControllerStatus slot. NOTE: implementations must be thread-safe, since this routine will execute in the alorithm's StatusEmitter thread.
Returns
ControllerStats::kNumSlots
Reimplemented from SideCar::Algorithms::Algorithm.
Definition at line 82 of file IQFilter.h.
References setInfoSlots().
void IQFilter::setInfoSlots (IO::StatusBase & status) virtual
Obtain custom status information from an algorithm.
All algorithms report generic status information to external entities via the ControllerStatus object. However, an algorithm with special reporting needs can provide custom data by appending to array whatever values it wants. NOTE: implementations must be thread-safe, since this routine will execute in the algorithm's StatusEmitter thread.
\param array container to hold the custom status information
Reimplemented from SideCar::Algorithms::Algorithm.
Definition at line 119 of file IQFilter.cc.
References SideCar::Algorithms::Algorithm::FormatInfoValue(), IQFilter(), and SideCar::IO::StatusBase::setSlot().
Referenced by getNumInfoSlots().
bool IQFilter::startup () virtual
Implementation of the Algorithm::startup interface.
Register run-time parameters with the controller.
Returns
true if successful, false otherwise
Reimplemented from SideCar::Algorithms::Algorithm.
Definition at line 36 of file IQFilter.cc.
References SideCar::Algorithms::Algorithm::getLog(), SideCar::Algorithms::Algorithm::getName(), LOGDEBUG, LOGERROR, SideCar::Messages::Video::Make(), SideCar::Algorithms::Algorithm::registerParameter(), SideCar::Algorithms::Algorithm::send(), and SideCar::Algorithms::Algorithm::startup().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/iqfilter/IQFilter.h
/Users/howes/src/sidecar/Algorithms/iqfilter/IQFilter.cc