SideCar: SideCar::GUI::BScope::App Class Reference
SideCar::GUI::BScope::App Class Reference
Application class for the Master application.
#include </Users/howes/src/sidecar/GUI/BScope/App.h>
Public Types
enum ToolsMenuAction {
kShowChannelSelectorWindow, kShowConfigurationWindow, kShowControlsWindow, kShowPresetsWindow,
kNumToolsMenuActions
}
Public Types inherited from SideCar::GUI::AppBase
enum AngularFormatType { kDegreesMinutesSeconds = 0, kDecimal, kNumFormattingTypes }
Enumeration for the various angular formatting available from the application.
Signals
void newFrameCount (int frameCount)
void imageSizeChanged (const QSize &size)
void frameAdded (int activeFrames)
Signals inherited from SideCar::GUI::AppBase
void activeMainWindowChanged (MainWindowBase *window)
Notification sent out when the application's active main window changes.
void shutdown ()
Notification sent out when the application is shutting down.
void restoreToolWindows ()
Notification sent out to all ToolWindowBase objects that they should show themselves if they were visible when the application last quit.
void angleFormattingChanged (int type)
Notification sent out when the angular formatting setting has been changed by the user.
void distanceUnitsChanged (const QString &suffix)
Notification sent out when the distance units have been changed by the user.
void phantomCursorChanged (const QPointF &pos)
Notification sent out when the phantom cursor value has been changed.
Public Member Functions
App (int &argc, char **argv)
Constructor.
QAction * getToolsMenuAction (ToolsMenuAction index)
ChannelSelectorWindow * getChannelSelectorWindow () const
Obtain the ChannelSelectorWindow tool window.
ConfigurationWindow * getConfigurationWindow () const
Obtain the ConfigurationWindow tool window.
ControlsWindow * getControlsWindow () const
Obtain the ControlsWindow tool window.
PresetsWindow * getPresetsWindow () const
Obtain the InfoWindow tool window.
MainWindow * getMainWindow () const
PlayerWindow * getPlayerWindow () const
FramesWindow * getFramesWindow () const
Configuration * getConfiguration () const
History * getHistory () const
void restoreWindows ()
Restore the windows that were open at the time the application last quit.
void addFrame (const QImage &image)
void setImageSize (const QSize &size)
Public Member Functions inherited from SideCar::GUI::AppBase
AppBase (const QString &name, int &argc, char **argv)
Constructor.
~AppBase ()
Destructor.
const QString & getApplicationName () const
QString getDocumentationPath () const
WindowManager * getWindowManager () const
QMenu * makeApplicationMenu (QWidget *parent)
QMenu * makeToolsMenu (QWidget *parent)
QMenu * makeWindowMenu (QWidget *parent)
QMenu * makeLoggingMenu (QWidget *parent)
QMenu * makeHelpMenu (QWidget *parent)
QAction * getToolsMenuAction (int index)
Obtain a specific QAction object found in the Tools menu.
void addWindowMenuActionTo (ToolBar *toolBar, int index) const
void setVisibleWindowMenuNew (bool visible)
Set the visibility state of the "New" action in the "Window" menu.
void setVisibleWindowMenuClose (bool visible)
Set the visibility state of the "Close" action in the "Window" menu.
void setVisibleWindowMenuMinimize (bool visible)
Set the visibility state of the "Minimize" action in the "Window" menu.
void setVisibleWindowMenuMaximize (bool visible)
Set the visibility state of the "Maximize" action in the "Window" menu.
void setVisibleWindowMenuFullScreen (bool visible)
Set the visibility state of the full-screen action in the "Window" menu.
void setLogConfigurationFile (const QString &path)
Use a configuration file for the Logger classes.
int getNumManagedWindows () const
Obtain the number of open MainWindowBase objects.
MainWindowBase * getActiveMainWindow () const
Obtain the active MainWindowBase object.
void manageWindow (QWidget *window, QMenu *windowMenu)
Manage a top-level window.
void unmanageWindow (QWidget *window)
Unmanage a top-level window.
bool isManagedWindow (QWidget *window) const
Determine if a given widget is managed by the application.
QWidget * getManagedWindow (const QString &title) const
bool isQuitting () const
Determine if the application is in the process of shutting down.
const QString & getDistanceUnits () const
Obtain the current distance units suffix.
QString getFormattedDistance (double value) const
Obtain a formatted representation of a distance value.
QString getFormattedAngleRadians (double value) const
Obtain a formatted representation of an angular value in radians.
QString getFormattedAngleDegrees (double value) const
Obtain a formatted representation of an angular value in degrees.
QPointF getPhantomCursor () const
Obtain the current phantom cursor value.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the Log device for App instances.
static App * GetApp ()
Obtain the singleton App object.
Static Public Member Functions inherited from SideCar::GUI::AppBase
static Logger::Log & Log ()
Log device for instances of this class.
static AppBase * GetApp ()
Obtain the AppBase singleton.
static QString GetRootDocumentationPath ()
Additional Inherited Members
Public Slots inherited from SideCar::GUI::AppBase
void updateToggleAction (bool state)
virtual void setPhantomCursor (const QPointF &pos)
Set the held phantom cursor value.
void showMessage (const QString &msg, int duration)
Show a message in the active main window.
void setAngleFormatting (AngularFormatType type)
Change the formatting used by getFormattedAngleDegrees() and getFormattedAngleRadians() methods.
void setDistanceUnits (const QString &units)
Change the distance units used by getFormattedDistance() method.
virtual void applicationQuit ()
Action event handler for the "Quit" menu item.
virtual void loggingLoadConfigurationFile ()
Present to the user an open file dialog in order to select a Logger configuration file.
virtual void loadStyleSheet ()
virtual void showAbout ()
virtual void windowNew ()
Protected Member Functions inherited from SideCar::GUI::AppBase
virtual void addToolWindow (int index, ToolWindowBase *toolWindow)
Register a tool window with the application.
MainWindowBase * makeAndInitializeNewMainWindow (const QString &type)
Detailed Description
Application class for the Master application.
Creates and manages the floating tool windows. There is only one instance of this class created (in main.cc) for the life of the application.
Definition at line 34 of file App.h.
Constructor & Destructor Documentation
App::App (int & argc, char ** argv)
Constructor.
Creates floating tool windows.
Parameters
argc command-line argument count
argv vector of command-line argument values
Definition at line 30 of file App.cc.
References SideCar::GUI::AppBase::addToolWindow(), and SideCar::GUI::AppBase::setVisibleWindowMenuNew().
Member Function Documentation
static App* SideCar::GUI::BScope::App::GetApp () inline static
Obtain the singleton App object.
Returns
App instance
Definition at line 58 of file App.h.
Referenced by SideCar::GUI::BScope::CursorWidget::CursorWidget(), SideCar::GUI::BScope::PastImage::Log(), SideCar::GUI::BScope::MagnifierView::MagnifierView(), SideCar::GUI::BScope::PPIWidget::PPIWidget(), and SideCar::GUI::BScope::VideoOffscreenBuffer::VideoOffscreenBuffer().
ChannelSelectorWindow* SideCar::GUI::BScope::App::getChannelSelectorWindow () const inline
Obtain the ChannelSelectorWindow tool window.
Returns
ChannelSelectorWindow object
Definition at line 75 of file App.h.
ConfigurationWindow* SideCar::GUI::BScope::App::getConfigurationWindow () const inline
Obtain the ConfigurationWindow tool window.
Returns
ConfigurationWindow object
Definition at line 82 of file App.h.
ControlsWindow* SideCar::GUI::BScope::App::getControlsWindow () const inline
Obtain the ControlsWindow tool window.
Returns
ControlsWindow object
Definition at line 89 of file App.h.
PresetsWindow* SideCar::GUI::BScope::App::getPresetsWindow () const inline
Obtain the InfoWindow tool window.
Returns
InfoWindow object
Definition at line 96 of file App.h.
Referenced by restoreWindows().
Logger::Log & App::Log () static
Obtain the Log device for App instances.
Returns
Log device
Definition at line 24 of file App.cc.
References Logger::Log::Find().
Referenced by restoreWindows().
void App::restoreWindows () virtual
Restore the windows that were open at the time the application last quit.
Emits the restoreToolWindows() signal after all main windows have been restored.
Reimplemented from SideCar::GUI::AppBase.
Definition at line 69 of file App.cc.
References SideCar::GUI::AppBase::applicationQuit(), getPresetsWindow(), Log(), LOGINFO, SideCar::GUI::AppBase::restoreWindows(), SideCar::GUI::PresetManager::saveAllPresets(), and SideCar::GUI::MainWindowBase::setVisibleAfterRestore().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/BScope/App.h
/Users/howes/src/sidecar/GUI/BScope/App.cc