SideCar: SideCar::Zeroconf::Monitor Class Reference
SideCar::Zeroconf::Monitor Class Reference abstract
Abstract base class that monitors the running status of a Zerconf object such as Publisher or Browser.
#include </Users/howes/src/sidecar/Zeroconf/Monitor.h>
Public Member Functions
virtual ~Monitor ()
Destructor.
Protected Member Functions
Monitor ()
Constructor.
virtual void serviceStarted ()=0
Notification from the monitored object that a service has started.
virtual void serviceStopping ()=0
Notification from the monitored object that a service is about to stop.
Transaction * getMonitored () const
Obtain the monitored object.
Friends
class Transaction
Detailed Description
Abstract base class that monitors the running status of a Zerconf object such as Publisher or Browser.
The monitor receives notifications when a Zeroconf service starts or stops. Derived classes must define the serviceStarted() and serviceStopping() routines.
Definition at line 15 of file Monitor.h.
Constructor & Destructor Documentation
virtual SideCar::Zeroconf::Monitor::~Monitor () inline virtual
Destructor.
Here to silence obnoxious GCC warnings about virtual methods without a virtual destructor.
Definition at line 21 of file Monitor.h.
SideCar::Zeroconf::Monitor::Monitor () inline protected
Constructor.
Begin by not monitoring anything.
Definition at line 27 of file Monitor.h.
References serviceStarted(), and serviceStopping().
Member Function Documentation
Transaction* SideCar::Zeroconf::Monitor::getMonitored () const inline protected
Obtain the monitored object.
NOTE: this value must NOT be held by others since Transaction objects are reference-counted, and may be destroyed at any time.
Returns
monitored object.
Definition at line 44 of file Monitor.h.
Referenced by SideCar::Zeroconf::ASIOMonitor::ASIOMonitor(), SideCar::Zeroconf::ACEMonitor::~ACEMonitor(), and SideCar::GUI::QtMonitor::~QtMonitor().
virtual void SideCar::Zeroconf::Monitor::serviceStarted () protected pure virtual
Notification from the monitored object that a service has started.
At this point, calls to getMonitored() shall return valid values.
Referenced by Monitor().
virtual void SideCar::Zeroconf::Monitor::serviceStopping () protected pure virtual
Notification from the monitored object that a service is about to stop.
At this point, calls to getMonitored() shall still return valid values, but after this routine exits, they will not.
Referenced by Monitor().
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/Zeroconf/Monitor.h