SideCar: Utils::CmdLineArgs::Options Class Reference
Utils::CmdLineArgs::Options Class Reference
Map of options found on the command line.
#include </Users/howes/src/sidecar/Utils/CmdLineArgs.h>
Public Types
using ValueVector = std::vector< std::string >
using OptionMap = std::map< std::string, ValueVector >
Public Member Functions
Options ()
Constructor.
void add (const std::string &name, const std::string &alt, const std::string &value)
Add a new option under one or two names.
bool has (const std::string &key) const
Lookup an option to see if it was set by the user.
bool has (char key) const
Lookup an option to see if it was set by the user.
bool has (const std::string &key, std::string &value) const
Lookup an option to see if it was set by the user.
bool has (char key, std::string &value) const
Lookup an option to see if it was set by the user.
ValueVector & operator[] (const std::string &key)
Fetch all of the values for a long option key.
ValueVector & operator[] (char key)
Fetch all of the values for a short option key.
Detailed Description
Map of options found on the command line.
If an option was given a value, then its value is stored; otherwise, an empty string is stored for the value.
Definition at line 85 of file CmdLineArgs.h.
Member Function Documentation
void CmdLineArgs::Options::add (const std::string & name, const std::string & alt, const std::string & value)
Add a new option under one or two names.
Parameters
name name of the option (long or short name)
alt an alternative name for the option. If `name' is a long name, then this would be a short name.
value the value to store under the given name and alt.
Definition at line 10 of file CmdLineArgs.cc.
bool Utils::CmdLineArgs::Options::has (const std::string & key) const inline
Lookup an option to see if it was set by the user.
Parameters
key the name of the option to look for
Returns
TRUE if the option was found
Definition at line 112 of file CmdLineArgs.h.
bool Utils::CmdLineArgs::Options::has (char key) const inline
Lookup an option to see if it was set by the user.
Parameters
key the name of the option to look for
Returns
TRUE if the option was found
Definition at line 120 of file CmdLineArgs.h.
References has().
Referenced by has().
bool CmdLineArgs::Options::has (const std::string & key, std::string & value) const
Lookup an option to see if it was set by the user.
If so, return the first value found under the option name.
Parameters
key the name of the option to look for
value reference to string that is updated with the first option value found. If option was not set, then this value is left alone
Returns
TRUE if the option was found
Definition at line 17 of file CmdLineArgs.cc.
bool Utils::CmdLineArgs::Options::has (char key, std::string & value) const inline
Lookup an option to see if it was set by the user.
If so, return the first value found under the option name.
Parameters
key the name of the option to look for
value reference to string that is updated with the first option value found. If option was not set, then this value is left alone
Returns
TRUE if the option was found
Definition at line 144 of file CmdLineArgs.h.
References has().
Referenced by has().
ValueVector& Utils::CmdLineArgs::Options::operator[] (const std::string & key) inline
Fetch all of the values for a long option key.
Parameters
key the name of the option to look for.
Returns
vector of values set for the option. If option was never set, size of vector will be zero.
Definition at line 152 of file CmdLineArgs.h.
ValueVector& Utils::CmdLineArgs::Options::operator[] (char key) inline
Fetch all of the values for a short option key.
Parameters
key the name of the option to look for.
Returns
vector of values set for the option. If option was never set, size of vector will be zero.
Definition at line 160 of file CmdLineArgs.h.
References operator[]().
Referenced by operator[]().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Utils/CmdLineArgs.h
/Users/howes/src/sidecar/Utils/CmdLineArgs.cc