SideCar: SideCar::GUI::ChannelGroup Class Reference
SideCar::GUI::ChannelGroup Class Reference
A manager of a collection of subscription channels for a particular message type (eg.
#include </Users/howes/src/sidecar/GUI/ChannelGroup.h>
Public Slots
void shutdown ()
Shutdown the reader thread and its connection to a publisher.
Signals
void incoming (const MessageList &messages)
Notification sent out when the channel has data.
void channelChanged ()
Notification that the user requested a new channel to connect to.
Public Member Functions
ChannelGroup (QObject *parent, const std::string &typeName, QComboBox *found)
Constructor.
Static Public Member Functions
static Logger::Log & Log ()
Log device for objects of this class.
Static Public Member Functions inherited from SideCar::IO::ZeroconfTypes::TZCType< id >
static const char * GetZeroconfType ()
Obtain the configured Zeroconf type for objects derived from this class.
static const char * GetTwinZeroconfType ()
Obtain the "twin" Zeroconf type for objects derived from this class.
static std::string MakeZeroconfType (const std::string &subType)
Construct a valid SideCar Zeroconf type string for a given subtype.
static std::string MakeTwinZeroconfType (const std::string &subType)
Construct the twin SideCar Zeroconf type string for a given subtype.
Static Public Member Functions inherited from SideCar::IO::ZeroconfRegistry
static const char * GetType (ID id)
Obtain the Zeroconf type string for a given ID.
static ID GetTwin (ID id)
Locate the twin of this ID.
static std::string MakeZeroconfType (const char *type, const std::string &subType)
Construct a valid SideCar Zeroconf type string for a type and a subtype.
Additional Inherited Members
Public Types inherited from SideCar::IO::ZeroconfRegistry
enum ID {
kPublisher = 0, kSubscriber, kRunnerStatusCollector, kRunnerStatusEmitter,
kStateEmitter, kStateCollector, kRunnerRemoteController, kNumTypes
}
Defined Zeroconf types.
Detailed Description
A manager of a collection of subscription channels for a particular message type (eg.
Video or BinaryVideo messages). Contains a ServiceBrowser which monitors Zeroconfig announcements from publishers, and a QComboBox widget that contains the names of the publishers available for selection. Finally, it also contains a ReaderThread that will subscribe to a chosen publisher and read in the published data.
Originally, this was a part of the PPIDisplay program, but was hoisted to the GUI directory with hopes that it would be useful in other programs. That has not proved the case; it should go back to PPIDisplay.
Definition at line 27 of file ChannelGroup.h.
Constructor & Destructor Documentation
ChannelGroup::ChannelGroup (QObject * parent, const std::string & typeName, QComboBox * found)
Constructor.
Parameters
parent owner of this object (for destruction)
typeName message type of the publishers to watch for
found the widget to update with publisher changes
Definition at line 23 of file ChannelGroup.cc.
References Log(), LOGINFO, and SideCar::GUI::ServiceBrowser::start().
Member Function Documentation
void SideCar::GUI::ChannelGroup::incoming (const MessageList & messages) signal
Notification sent out when the channel has data.
Parameters
messages list of Messages::Header::Ref objects
Referenced by shutdown().
Logger::Log & ChannelGroup::Log () static
Log device for objects of this class.
Returns
log device
Definition at line 17 of file ChannelGroup.cc.
References Logger::Log::Find().
Referenced by ChannelGroup(), and shutdown().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/ChannelGroup.h
/Users/howes/src/sidecar/GUI/ChannelGroup.cc