SideCar: SideCar::Messages::PRIMessage Class Reference
SideCar::Messages::PRIMessage Class Reference abstract
Base class for all PRI-type messages created in the SideCar.
#include </Users/howes/src/sidecar/Messages/PRIMessage.h>
Data Structures
struct RIUInfo
Internal collection of VME/RIU header attributes.
Public Types
using Super = Header
using Ref = boost::shared_ptr< PRIMessage >
Public Types inherited from SideCar::Messages::Header
using Ref = boost::shared_ptr< Header >
Public Member Functions
RIUInfo & getRIUInfo ()
Obtain a reference to the VME header attributes.
uint32_t getSequenceCounter () const
uint32_t getShaftEncoding () const
Obtain the shaft encoding value for the message.
bool hasIRIGTime () const
double getIRIGTime () const
double getRangeMin () const
double getRangeMax () const
double getRangeFactor () const
double getRangeAt (double gate) const
double getAzimuthStart () const
Obtain an azimuth value in radians for the PRI message, based on the shaft encoder and the north mark values from the VME syatem.
double getAzimuthEnd () const
Obtain the value of getAzimuthStart() + RadarConfig::GetBeamWidth().
virtual size_t size () const =0
std::ostream & printHeader (std::ostream &os) const
Write out the message values to a C++ text output stream.
std::ostream & printDataXML (std::ostream &os) const
Write out the message data to a C++ text output stream in XML format.
void loadXML (XmlStreamReader &xsr)
Obtain new instance data from an XML input stream.
Public Member Functions inherited from SideCar::Messages::Header
Header (const MetaTypeInfo &metaTypeInfo)
Constructor for messages read in from an external device.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis, MetaTypeInfo::SequenceType sequenceNumber)
Constructor for new messages.
virtual ~Header ()
Destructor.
const MetaTypeInfo & getMetaTypeInfo () const
Obtain the type specification for the message.
const GUID & getGloballyUniqueID () const
Get the globally-unique ID of the message.
MetaTypeInfo::SequenceType getMessageSequenceNumber () const
Get the message sequence number for the message.
void setMessageSequenceNumber (MetaTypeInfo::SequenceType msn)
Set the sequence number for this message.
const Time::TimeStamp & getCreatedTimeStamp () const
Obtain when the message was created.
Time::TimeStamp setCreatedTimeStamp (const Time::TimeStamp &timeStamp)
Revise the creation message timestamp.
const Time::TimeStamp & getEmittedTimeStamp () const
Obtain when the message was written to an external device (file or network).
Time::TimeStamp setEmittedTimeStamp (const Time::TimeStamp &timeStamp)
Set the emitted time stamp with the given value.
virtual size_t getSize () const
Obtain the C++ structure size for this object.
virtual ACE_InputCDR & load (ACE_InputCDR &cdr)
Obtain new instance data from a CDR input stream.
virtual ACE_OutputCDR & write (ACE_OutputCDR &cdr) const
Write out the header to a CDR output stream.
HeaderPrinter headerPrinter () const
Convenience method that simply returns a new HeaderPrinter functor for this header object.
DataPrinter dataPrinter () const
Convenience method that simply returns a new DataPrinter functor for this header object.
XMLPrinter xmlPrinter () const
Convenience method that simply returns a new XMLPrinter functor for this header object.
virtual std::ostream & print (std::ostream &os) const
Write out the entire message to a C++ text output stream.
virtual std::ostream & printData (std::ostream &os) const
Write out the message data to a C++ text output stream.
virtual std::ostream & printXML (std::ostream &os) const
Write out the message to a C++ text output stream in XML format.
bool hasBasis () const
Determine if the message has a basis message attached to it.
Ref getBasis () const
Obtain a reference to the message that this one was based on.
template<typename T >
T::Ref getBasis () const
Templated version of the above method.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for PRIMessage objects.
Static Public Member Functions inherited from SideCar::Messages::Header
static Logger::Log & Log ()
Obtain log device to use for objects of this class.
static const MetaTypeInfo * GetMessageMetaTypeInfo (ACE_InputCDR &cdr)
Protected Member Functions
PRIMessage (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const PRIMessage::Ref &copy)
Constructor used to create a new message that is derived from another one.
PRIMessage (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const VMEDataMessage &vme)
Constructor used to create a new message.
PRIMessage (const MetaTypeInfo &metaTypeInfo)
Constructor used to create a new message populated with data from a raw buffer.
PRIMessage (const std::string &producer, const MetaTypeInfo &metaTypeInfo)
Constructor used to create a new message populated with data from a raw buffer.
ACE_InputCDR & loadArray (ACE_InputCDR &cdr, uint32_t &count)
Read in binary data from a CDR stream.
ACE_OutputCDR & writeArray (ACE_OutputCDR &cdr, uint32_t size) const
Write out our binary data to a CDR stream.
Detailed Description
Base class for all PRI-type messages created in the SideCar.
Each message contains header information from the VME system, followed by the data samples.
Previously, PRIMessage held a shared reference to a PRIMessageInfo object, which detailed radar configuration parameters. This is no longer the case. Radar settings are now contained in the RadarConfig class.
Definition at line 29 of file PRIMessage.h.
Constructor & Destructor Documentation
PRIMessage::PRIMessage (const std::string & producer, const MetaTypeInfo & metaTypeInfo, const PRIMessage::Ref & copy) protected
Constructor used to create a new message that is derived from another one.
Shares the PRIMessageInfo object with the copy, but everything else s unique to the new object.
Parameters
producer name of the task that is creating the new object
metaTypeInfo message type description
copy message to derive from
Definition at line 129 of file PRIMessage.cc.
PRIMessage::PRIMessage (const std::string & producer, const MetaTypeInfo & metaTypeInfo, const VMEDataMessage & vme) protected
Constructor used to create a new message.
Parameters
producer name of the task that is creating the new object
metaTypeInfo message type description
\param vme header info from the VME RIU message
Definition at line 123 of file PRIMessage.cc.
PRIMessage::PRIMessage (const MetaTypeInfo & metaTypeInfo) protected
Constructor used to create a new message populated with data from a raw buffer.
Parameters
metaTypeInfo message type description
Definition at line 141 of file PRIMessage.cc.
PRIMessage::PRIMessage (const std::string & producer, const MetaTypeInfo & metaTypeInfo) protected
Constructor used to create a new message populated with data from a raw buffer.
Parameters
metaTypeInfo message type description
Definition at line 135 of file PRIMessage.cc.
Member Function Documentation
double PRIMessage::getAzimuthEnd () const
Obtain the value of getAzimuthStart() + RadarConfig::GetBeamWidth().
Returns
azimuth in radians
Definition at line 165 of file PRIMessage.cc.
References SideCar::Messages::RadarConfig::GetAzimuth(), SideCar::Messages::RadarConfig::GetBeamWidth(), SideCar::Messages::RadarConfig::GetShaftEncodingMax(), SideCar::Messages::PRIMessage::RIUInfo::irigTime, SideCar::Messages::PRIMessage::RIUInfo::load(), Log(), LOGDEBUG, LOGTIN, SideCar::Messages::PRIMessage::RIUInfo::msgDesc, SideCar::Messages::PRIMessage::RIUInfo::prfEncoding, SideCar::Messages::PRIMessage::RIUInfo::rangeFactor, SideCar::Messages::PRIMessage::RIUInfo::rangeMin, SideCar::Messages::PRIMessage::RIUInfo::sequenceCounter, SideCar::Messages::PRIMessage::RIUInfo::shaftEncoding, and SideCar::Messages::PRIMessage::RIUInfo::timeStamp.
double PRIMessage::getAzimuthStart () const
Obtain an azimuth value in radians for the PRI message, based on the shaft encoder and the north mark values from the VME syatem.
Returns
azimuth in radians
Definition at line 159 of file PRIMessage.cc.
References SideCar::Messages::RadarConfig::GetAzimuth(), and SideCar::Messages::PRIMessage::RIUInfo::shaftEncoding.
RIUInfo& SideCar::Messages::PRIMessage::getRIUInfo () inline
Obtain a reference to the VME header attributes.
Returns
RIUInfo reference
Definition at line 99 of file PRIMessage.h.
References SideCar::Messages::PRIMessage::RIUInfo::sequenceCounter.
uint32_t SideCar::Messages::PRIMessage::getShaftEncoding () const inline
Obtain the shaft encoding value for the message.
To get an azimuth value in radians, use getAzimuthStart(). This value should fall between 0 and RadarConfig::GetShaftEncodingMax().
Returns
encoder value
Definition at line 108 of file PRIMessage.h.
ACE_InputCDR & PRIMessage::loadArray (ACE_InputCDR & cdr, uint32_t & count) protected
Read in binary data from a CDR stream.
Parameters
cdr stream to read from
Returns
stream read from
Definition at line 148 of file PRIMessage.cc.
References SideCar::Messages::Header::load(), SideCar::Messages::TLoaderRegistry< T >::load(), Log(), and LOGDEBUG.
void PRIMessage::loadXML (XmlStreamReader & xsr) virtual
Obtain new instance data from an XML input stream.
Parameters
xsr stream to read from
Reimplemented from SideCar::Messages::Header.
Reimplemented in SideCar::Messages::TPRIMessage< _V >, SideCar::Messages::TPRIMessage< Traits::Bool >, SideCar::Messages::TPRIMessage< Traits::Int16 >, and SideCar::Messages::TPRIMessage< Traits::ComplexInt16 >.
Definition at line 273 of file PRIMessage.cc.
References SideCar::Messages::XmlStreamReader::getSamples(), SideCar::Messages::Header::loadXML(), and SideCar::Messages::XmlStreamReader::readNextEntityAndValidate().
Logger::Log & PRIMessage::Log () static
Obtain the log device for PRIMessage objects.
The device name is "SideCar.Messages.PRIMEssage"
Returns
log device
Definition at line 20 of file PRIMessage.cc.
References Logger::Log::Find().
Referenced by getAzimuthEnd(), SideCar::Messages::BinaryVideo::getVideoBasis(), loadArray(), and SideCar::Messages::PRIMessage::RIUInfo::write().
std::ostream & PRIMessage::printDataXML (std::ostream & os) const virtual
Write out the message data to a C++ text output stream in XML format.
Parameters
os stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Reimplemented in SideCar::Messages::TPRIMessage< _V >, SideCar::Messages::TPRIMessage< Traits::Bool >, SideCar::Messages::TPRIMessage< Traits::Int16 >, and SideCar::Messages::TPRIMessage< Traits::ComplexInt16 >.
Definition at line 266 of file PRIMessage.cc.
std::ostream & PRIMessage::printHeader (std::ostream & os) const virtual
Write out the message values to a C++ text output stream.
Parameters
os stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Definition at line 260 of file PRIMessage.cc.
References SideCar::Messages::PRIMessage::RIUInfo::print(), and SideCar::Messages::Header::printHeader().
ACE_OutputCDR & PRIMessage::writeArray (ACE_OutputCDR & cdr, uint32_t size) const protected
Write out our binary data to a CDR stream.
Parameters
cdr stream to write to
Returns
stream written to
Definition at line 250 of file PRIMessage.cc.
References SideCar::Messages::VoidLoaderRegistry::getCurrentVersion(), and SideCar::Messages::Header::write().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Messages/PRIMessage.h
/Users/howes/src/sidecar/Messages/PRIMessage.cc