SideCar: SideCar::IO::DatagramReader Class Reference
SideCar::IO::DatagramReader Class Reference abstract
Abstract base class for readers.
#include </Users/howes/src/sidecar/IO/Readers.h>
Public Types
using Ref = boost::shared_ptr< DatagramReader >
Public Types inherited from SideCar::IO::Reader
using Ref = boost::shared_ptr< Reader >
Public Member Functions
DatagramReader (size_t maxSize)
Constructor for new reader.
~DatagramReader ()
Destructor.
bool fetchInput ()
Read in data from the device and append to the existing ACE_Message_Block.
void reset ()
Reset the stream by discarding any partially-read messages.
Public Member Functions inherited from SideCar::IO::Reader
Reader ()
Constructor for new reader.
virtual ~Reader ()
Destructor.
bool isMessageAvailable () const
Determine if a complete message is available for processing.
ACE_Message_Block * getMessage ()
Obtain the raw data block available from the reader.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device to use for log messages.
Static Public Member Functions inherited from SideCar::IO::Reader
static Logger::Log & Log ()
Obtain the log device to use for log messages.
Protected Member Functions
virtual ssize_t fetchFromDevice (void *addr, size_t size)=0
Prototype of method that fetches data from a device and places it into a specific location.
void makeIncomingBuffer (size_t size)
Create a new buffer to hold the next message begin built.
Protected Member Functions inherited from SideCar::IO::Reader
void setAvailable (ACE_Message_Block *available)
Make a complete message available for consumption.
Protected Attributes
ACE_Message_Block * building_
Message being built.
Detailed Description
Abstract base class for readers.
A reader accumulates data from a device until it has all of the data of a complete message. All SideCar messages have a header (see SideCar::Messages::Header class) which contains a size in bytes. A reader simply adds incoming bytes to an ACE_Message_Block until the ACE_Message_Block::length() == Header::getSize().
Definition at line 349 of file Readers.h.
Constructor & Destructor Documentation
DatagramReader::DatagramReader (size_t maxSize)
Constructor for new reader.
Parameters
bufferSize starting size for read buffer
Definition at line 218 of file Readers.cc.
References makeIncomingBuffer().
Member Function Documentation
virtual ssize_t SideCar::IO::DatagramReader::fetchFromDevice (void * addr, size_t size) protected pure virtual
Prototype of method that fetches data from a device and places it into a specific location.
Parameters
addr where to place fetched data
size how much data to fetch
Returns
number of bytes fetched if > 0; EOF if == 0; and error condition if < 0
Implemented in SideCar::IO::TReader< DatagramReader, ReaderDevices::MulticastSocket >, and SideCar::IO::TReader< DatagramReader, ReaderDevices::UDPSocket >.
Referenced by fetchInput().
bool DatagramReader::fetchInput () virtual
Read in data from the device and append to the existing ACE_Message_Block.
Returns
true if device is still valid, false otherwise
Implements SideCar::IO::Reader.
Definition at line 245 of file Readers.cc.
References building_, fetchFromDevice(), Logger::Log::Find(), SideCar::IO::Reader::isMessageAvailable(), Log(), LOGDEBUG, LOGERROR, LOGINFO, makeIncomingBuffer(), and SideCar::IO::Reader::setAvailable().
Referenced by SideCar::IO::MulticastDataSubscriber::ReaderThread::close(), SideCar::Algorithms::BugCollectorUtils::BugPlotReader::handle_input(), SideCar::IO::VMEReaderTask::openAndInit(), SideCar::IO::TSPIReaderTask::openAndInit(), SideCar::IO::UDPSocketReaderTask::openAndInit(), and SideCar::IO::MulticastVMEReaderTask::openAndInit().
Logger::Log & DatagramReader::Log () static
Obtain the log device to use for log messages.
Returns
Definition at line 212 of file Readers.cc.
References Logger::Log::Find().
Referenced by fetchInput(), SideCar::IO::ReaderDevices::MulticastSocket::join(), makeIncomingBuffer(), and ~DatagramReader().
void DatagramReader::makeIncomingBuffer (size_t size) protected
Create a new buffer to hold the next message begin built.
Parameters
bufferSize the initial size of the new buffer
Definition at line 235 of file Readers.cc.
References building_, Log(), LOGDEBUG, and SideCar::IO::MessageManager::MakeMessageBlock().
Referenced by DatagramReader(), and fetchInput().
void SideCar::IO::DatagramReader::reset () inline
Reset the stream by discarding any partially-read messages.
This is a NOP for this class since datagrams are always read whole.
Definition at line 379 of file Readers.h.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/Readers.h
/Users/howes/src/sidecar/IO/Readers.cc