SideCar: SideCar::IO::TCPConnector Class Reference
SideCar::IO::TCPConnector Class Reference
Public Member Functions
TCPConnector (IOTask *task, int maxSocketBufferSize=0)
Constructor.
bool openAndInit (const ACE_INET_Addr &remoteAddress, ACE_Reactor *reactor)
Atttempt to connect to a remote host using the given address.
int getMaxSocketBufferSize () const
int close ()
Shut down the output handler.
int handle_timeout (const ACE_Time_Value &timeout, const void *arg)
Notification that our attempt to connect to a remote server has timed out.
bool attemptConnection ()
Attempt to (re)connect to a remote host using the cached connection address.
bool scheduleConnectionAttempt ()
Static Public Member Functions
static Logger::Log & Log ()
Log device for objects of this type.
Detailed Description
Definition at line 15 of file TCPConnector.h.
Constructor & Destructor Documentation
SideCar::IO::TCPConnector::TCPConnector (IOTask * task, int maxSocketBufferSize = 0) inline
Constructor.
Parameters
task task from which to pull messages to emit.
Definition at line 30 of file TCPConnector.h.
Member Function Documentation
bool TCPConnector::attemptConnection ()
Attempt to (re)connect to a remote host using the cached connection address.
Creates a new InputHandler object if the connection succeeds.
Returns
true if successful, false otherwise
Definition at line 50 of file TCPConnector.cc.
References SideCar::IO::IOTask::establishedConnection(), SideCar::IO::Task::isUsingData(), Log(), LOGDEBUG, LOGERROR, LOGINFO, SideCar::IO::Task::setError(), and SideCar::IO::Task::setUsingData().
Referenced by handle_timeout(), and openAndInit().
int TCPConnector::close ()
Shut down the output handler.
Override of ACE_Connector method.
Returns
0 if successful, -1 otherwise
Definition at line 40 of file TCPConnector.cc.
References SideCar::IO::TCPInputHandler::close(), Log(), and LOGINFO.
Referenced by SideCar::IO::ClientSocketReaderTask::close(), openAndInit(), SideCar::IO::TCPDataSubscriber::openAndInit(), and SideCar::IO::TCPDataSubscriber::setServiceName().
int TCPConnector::handle_timeout (const ACE_Time_Value & timeout, const void * arg)
Notification that our attempt to connect to a remote server has timed out.
Try again.
Parameters
timeout
arg
Returns
Definition at line 104 of file TCPConnector.cc.
References attemptConnection(), Log(), and LOGINFO.
Logger::Log & TCPConnector::Log () static
Log device for objects of this type.
Returns
log device
Definition at line 8 of file TCPConnector.cc.
References Logger::Log::Find().
Referenced by attemptConnection(), close(), handle_timeout(), and openAndInit().
bool TCPConnector::openAndInit (const ACE_INET_Addr & remoteAddress, ACE_Reactor * reactor)
Atttempt to connect to a remote host using the given address.
Parameters
remoteAddress address of remote host to connect to
reactor the ACE_Reactor to register with
Returns
true if successful, false otherwise
Definition at line 15 of file TCPConnector.cc.
References attemptConnection(), close(), Log(), LOGDEBUG, LOGERROR, and LOGINFO.
Referenced by SideCar::IO::ClientSocketReaderTask::openAndInit(), and SideCar::IO::TCPDataSubscriber::setServiceName().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/TCPConnector.h
/Users/howes/src/sidecar/IO/TCPConnector.cc