SideCar: Utils::Pool Class Reference
Utils::Pool Class Reference
An allocator for same-size memory chunks.
#include </Users/howes/src/sidecar/Utils/Pool.h>
Data Structures
struct AllocationStats
Public Member Functions
Pool (std::size_t objectSize, std::size_t objectsPerBlock) throw (std::invalid_argument)
Constructor.
~Pool () throw ()
Destructor.
AllocationStats getAllocationStats () const
void * allocate (std::size_t size) throw (std::bad_alloc)
Allocate chunk for object.
void release (void *ptr, std::size_t size) throw ()
Reclaim chunk allocated for an object.
size_t numBlocks () const throw ()
size_t numAllocated () const throw ()
size_t numInUse () const throw ()
size_t numFree () const throw ()
Static Public Member Functions
static bool SetValidateRelease (bool flag=true)
Control whether release() calls have their address argument validated before being used.
static bool SetObjectSizeWarning (bool flag=true)
Control whether allocate and release calls issue a warning message when invoked with an object size not equal to the pool size.
Detailed Description
An allocator for same-size memory chunks.
Basic idea is to acquire a large block of memory using C++ new operator, and then handle chunk requests from the large block. Available chunks are kept on a linked-list, which makes chunk allocation and deallocation very fast.
To use as a class allocator, one needs to override the C++ new and delete operators for the class, and create a class attribute for the pool allocator. Here is an example:
class Foo
{
public:
  static void* operator new(size_t) { return allocator_.allocate(); }
  static void operator delete(void* ptr, size_t) { allocator_.release(ptr); }
private:
  static Utils::Pool allocator_;
};
// Create allocator for all Foo objects. Allocate 1000 at a time.
Utils::Pool Foo::allocator_(sizeof(Foo), 1000);
Definition at line 33 of file Pool.h.
Constructor & Destructor Documentation
Pool::Pool (std::size_t objectSize, std::size_t objectsPerBlock) throw (std::invalid_argument)
Constructor.
Parameters
objectSize size of pooled object
objectsPerBlock number of objects to allocate per block of raw memory allocated.
Definition at line 29 of file Pool.cc.
Pool::~Pool () throw ()
Destructor.
Frees allocated memory block.
Definition at line 37 of file Pool.cc.
Member Function Documentation
void * Pool::allocate (std::size_t size) throw (std::bad_alloc)
Allocate chunk for object.
Returns
address of memory allocated
Definition at line 43 of file Pool.cc.
Referenced by PoolAllocator::malloc().
size_t Utils::Pool::numAllocated () const throw () inline
Returns
number of created chunks
Definition at line 93 of file Pool.h.
Referenced by release().
size_t Utils::Pool::numBlocks () const throw () inline
Returns
number of memory blocks currently in use.
Definition at line 89 of file Pool.h.
Referenced by release().
size_t Utils::Pool::numFree () const throw () inline
Returns
number of available chunks
Definition at line 101 of file Pool.h.
Referenced by release().
size_t Utils::Pool::numInUse () const throw () inline
Returns
number of chunks in use
Definition at line 97 of file Pool.h.
Referenced by release().
void Pool::release (void * ptr, std::size_t size) throw ()
Reclaim chunk allocated for an object.
Parameters
ptr address of memory to add back
Definition at line 64 of file Pool.cc.
References numAllocated(), numBlocks(), numFree(), and numInUse().
Referenced by PoolAllocator::free().
bool Pool::SetObjectSizeWarning (bool flag = true) static
Control whether allocate and release calls issue a warning message when invoked with an object size not equal to the pool size.
Parameters
flag if true, issue warnings
Returns
previous setting
Definition at line 22 of file Pool.cc.
bool Pool::SetValidateRelease (bool flag = true) static
Control whether release() calls have their address argument validated before being used.
Parameters
flag if true, validate release parameter
Returns
previous setting
Definition at line 14 of file Pool.cc.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Utils/Pool.h
/Users/howes/src/sidecar/Utils/Pool.cc