SideCar: SideCar::GUI::PPIDisplay::BackgroundImageSettings Class Reference
SideCar::GUI::PPIDisplay::BackgroundImageSettings Class Reference
Collection of Setting objects that control the display of a background image in a PPIWidget widget.
#include </Users/howes/src/sidecar/GUI/PPIDisplay/BackgroundImageSettings.h>
Signals
void imageChanged (const QImage &image)
Notification emitted when the background image changes.
Signals inherited from SideCar::GUI::OnOffSettingsBlock
void enabledChanged (bool state)
Notification sent out when the enabled state has changed.
Signals inherited from SideCar::GUI::SettingsBlock
void settingChanged ()
Notification sent out when a registered value has changed.
Public Member Functions
BackgroundImageSettings (BoolSetting *enabled, PathSetting *path, OpacitySetting *opacity)
Constructor.
QString getPath () const
Obtain the current image file path.
double getOpacity () const
Obtain the current image opacity value.
const QImage & getFiltered () const
Obtain the filtered background image.
Public Member Functions inherited from SideCar::GUI::OnOffSettingsBlock
OnOffSettingsBlock (BoolSetting *enabled)
Constructor.
bool isEnabled () const
Determine if the settings block is enabled.
void toggleEnabled ()
Toggle the enabled state of this settings block.
void setToggleEnabledAction (QAction *action)
Install a QAction object to control the on/off state of the settings block.
void connectWidget (QCheckBox *widget)
Public Member Functions inherited from SideCar::GUI::SettingsBlock
SettingsBlock (QObject *parent=0)
Constructor.
Static Public Member Functions
static Logger::Log & Log ()
Additional Inherited Members
Protected Slots inherited from SideCar::GUI::SettingsBlock
virtual void postSettingChanged ()
Notification handler invoked when a Setting object that was registered with one of the add() methods emits its valueChanged() signal.
virtual void emitSettingChanged ()
Notification handler invoked when the QTimer object registered by the postSettingChanged() method fires.
Protected Member Functions inherited from SideCar::GUI::SettingsBlock
void add (Setting *setting)
Relate a Setting object to this SettingsBlock object.
Detailed Description
Collection of Setting objects that control the display of a background image in a PPIWidget widget.
Relies on the Qt QImage class to do most of the work. The QImage class supports a variety of image formats, including JPEG, PNG, and XPM.
Definition at line 20 of file BackgroundImageSettings.h.
Constructor & Destructor Documentation
BackgroundImageSettings::BackgroundImageSettings (BoolSetting * enabled, PathSetting * path, OpacitySetting * opacity)
Constructor.
Parameters
enabled
path
opacity
Definition at line 17 of file BackgroundImageSettings.cc.
References SideCar::GUI::StringSetting::getValue(), SideCar::GUI::DoubleSetting::getValue(), imageChanged(), and LOGERROR.
Member Function Documentation
const QImage& SideCar::GUI::PPIDisplay::BackgroundImageSettings::getFiltered () const inline
Obtain the filtered background image.
This is the last image emitted in in the imageChanged signal.
Returns
QImage reference
Definition at line 55 of file BackgroundImageSettings.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::initializeContext().
double SideCar::GUI::PPIDisplay::BackgroundImageSettings::getOpacity () const inline
Obtain the current image opacity value.
Returns
opacity value in range [0.0-1.0].
Definition at line 49 of file BackgroundImageSettings.h.
QString SideCar::GUI::PPIDisplay::BackgroundImageSettings::getPath () const inline
Obtain the current image file path.
May be empty if not set.
Returns
path
Definition at line 43 of file BackgroundImageSettings.h.
void SideCar::GUI::PPIDisplay::BackgroundImageSettings::imageChanged (const QImage & image) signal
Notification emitted when the background image changes.
Parameters
image new background image
Referenced by BackgroundImageSettings().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/PPIDisplay/BackgroundImageSettings.h
/Users/howes/src/sidecar/GUI/PPIDisplay/BackgroundImageSettings.cc