SideCar: SideCar::IO::Stats Class Reference
SideCar::IO::Stats Class Reference
General processing statistics of an IO::Task.
#include </Users/howes/src/sidecar/IO/Stats.h>
Public Member Functions
Stats ()
Constructor.
void resetAll ()
Reset the counters and rates to zero.
void resetDropDupeCounts ()
void updateInputCounters (size_t byteCount)
Update the held counters.
void updateInputCounters (size_t byteCount, uint32_t sequenceNumber)
Update the held counters.
size_t getByteRate () const
Obtain the last-calculated byte rate.
size_t getMessageRate () const
Obtain the last-calculated message rate.
size_t getMessageCount () const
Obtain the running message count.
size_t getDropCount () const
Obtain the total number of dropped messages found so far.
size_t getDupeCount () const
Obtain the total number of duplicate message IDs found so far.
void calculateRates ()
Update the message and byte rates based on the elapsed time since the last update.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device to use for Stats objects.
Detailed Description
General processing statistics of an IO::Task.
Records object and byte counts, and provides for calculating throughput rates in terms of messages and bytes.
Definition at line 15 of file Stats.h.
Member Function Documentation
size_t SideCar::IO::Stats::getByteRate () const inline
Obtain the last-calculated byte rate.
Returns
byte rate
Definition at line 53 of file Stats.h.
Referenced by SideCar::IO::Task::fillStatus().
size_t SideCar::IO::Stats::getDropCount () const inline
Obtain the total number of dropped messages found so far.
Returns
dropped count
Definition at line 71 of file Stats.h.
Referenced by SideCar::IO::Task::fillStatus().
size_t SideCar::IO::Stats::getDupeCount () const inline
Obtain the total number of duplicate message IDs found so far.
Returns
duplicate count
Definition at line 77 of file Stats.h.
Referenced by SideCar::IO::Task::fillStatus().
size_t SideCar::IO::Stats::getMessageCount () const inline
Obtain the running message count.
Returns
message count
Definition at line 65 of file Stats.h.
Referenced by SideCar::IO::Task::fillStatus().
size_t SideCar::IO::Stats::getMessageRate () const inline
Obtain the last-calculated message rate.
Returns
message rate
Definition at line 59 of file Stats.h.
Referenced by SideCar::IO::Task::fillStatus().
Logger::Log & Stats::Log () static
Obtain the log device to use for Stats objects.
Returns
Log device
Definition at line 11 of file Stats.cc.
References Logger::Log::Find().
Referenced by calculateRates(), and updateInputCounters().
void Stats::updateInputCounters (size_t byteCount)
Update the held counters.
Parameters
byteCount number of bytes processed
Definition at line 70 of file Stats.cc.
Referenced by updateInputCounters().
void Stats::updateInputCounters (size_t byteCount, uint32_t sequenceNumber)
Update the held counters.
Parameters
byteCount number of bytes processed
sequenceNumber
Definition at line 39 of file Stats.cc.
References Log(), LOGERROR, LOGTIN, and updateInputCounters().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/Stats.h
/Users/howes/src/sidecar/IO/Stats.cc