SideCar: SideCar::GUI::BScope::History Class Reference
SideCar::GUI::BScope::History Class Reference
Container for collections of SideCar messages, grouped by revolution.
#include </Users/howes/src/sidecar/GUI/BScope/History.h>
Public Types
using MessageVector = std::vector< Messages::PRIMessage::Ref >
Public Slots
void setExtractionsLifeTime (int msecs)
void setRangeTruthsLifeTime (int msecs)
void setRangeTruthsMaxTrailLength (int length)
void setBugPlotsLifeTime (int msecs)
Public Member Functions
History (QObject *parent)
Constructor.
Messages::Video::DatumType getVideoValue (double azimuth, double range, bool &isValid) const
Messages::BinaryVideo::DatumType getBinaryValue (double azimuth, double range, bool &isValid) const
const MessageVector & getVideo () const
Obtain a read-only reference to the Video collection.
const MessageVector & getBinary () const
Obtain a read-only reference to the BinaryVideo collection.
const TargetPlotList & getExtractions () const
Obtain a read-only reference to the Extraction message collection.
const TargetPlotListList & getRangeTruths () const
Obtain a read-only reference to the TSPI message collection.
const TargetPlotList & getBugPlots () const
Obtain a read-only reference to the user bug plot entries.
void addVideo (const Messages::Video::Ref &msg)
Add a Video object to the live view, and possibly to a retained view if enabled.
void addBinary (const Messages::BinaryVideo::Ref &msg)
Add a BinaryVideo object the the live view.
void addExtractions (const Messages::Extractions::Ref &msg)
Add an Extractions object to the live view, and possibly to a retained view if enabled.
void addRangeTruth (const Messages::TSPI::Ref &msg)
Add a TSPI object to the live view, and possibly to a retained view if enabled.
void addBugPlot (const Messages::BugPlot::Ref &msg)
Add one TargetPlot object to the live view, and possibly to a retained view if enabled.
void wrap ()
void clear ()
Erase all cached data.
void clearVideo ()
void clearBinary ()
void clearExtractions ()
void clearRangeTruths ()
void clearBugPlots ()
Static Public Member Functions
static Logger::Log & Log ()
Detailed Description
Container for collections of SideCar messages, grouped by revolution.
As messages come in, they are added to live and pending Entry objects. When a complete revolution is detected, the pending Entry is placed at the front of the retained Entry queue, thus becoming the most-recent historical entry. The oldest Entry object is then popped off the back of the queue, keeping the queue a constant size, and the popped off Entry object becomes the new pending object.
Definition at line 29 of file History.h.
Constructor & Destructor Documentation
History::History (QObject * parent)
Constructor.
Parameters
retentionSize number of revolutions to retain
enabled whether retention is enabled
Definition at line 22 of file History.cc.
References clear().
Member Function Documentation
void History::addBinary (const Messages::BinaryVideo::Ref & msg)
Add a BinaryVideo object the the live view.
and possibly to a retained view if enabled.
Parameters
msg message to add
Definition at line 213 of file History.cc.
Referenced by SideCar::GUI::BScope::PPIWidget::PPIWidget().
void History::addBugPlot (const Messages::BugPlot::Ref & msg)
Add one TargetPlot object to the live view, and possibly to a retained view if enabled.
This is from a user clicking on the screen.
Parameters
msg bug plot to add
Definition at line 284 of file History.cc.
Referenced by SideCar::GUI::BScope::MagnifierView::MagnifierView(), and SideCar::GUI::BScope::PPIWidget::PPIWidget().
void History::addExtractions (const Messages::Extractions::Ref & msg)
Add an Extractions object to the live view, and possibly to a retained view if enabled.
Parameters
msg message to add
Definition at line 242 of file History.cc.
Referenced by SideCar::GUI::BScope::PPIWidget::PPIWidget().
void History::addRangeTruth (const Messages::TSPI::Ref & msg)
Add a TSPI object to the live view, and possibly to a retained view if enabled.
Parameters
msg message to add
Definition at line 251 of file History.cc.
Referenced by SideCar::GUI::BScope::PPIWidget::PPIWidget().
void History::addVideo (const Messages::Video::Ref & msg)
Add a Video object to the live view, and possibly to a retained view if enabled.
Parameters
msg message to add
Definition at line 147 of file History.cc.
Referenced by SideCar::GUI::BScope::PPIWidget::PPIWidget().
const MessageVector& SideCar::GUI::BScope::History::getBinary () const inline
Obtain a read-only reference to the BinaryVideo collection.
Returns
MessageVector reference
Definition at line 62 of file History.h.
Referenced by SideCar::GUI::BScope::PPIWidget::PPIWidget().
const TargetPlotList& SideCar::GUI::BScope::History::getBugPlots () const inline
Obtain a read-only reference to the user bug plot entries.
Returns
TargetPlotList reference
Definition at line 80 of file History.h.
References Utils::wrap().
Referenced by SideCar::GUI::BScope::PPIWidget::PPIWidget().
const TargetPlotList& SideCar::GUI::BScope::History::getExtractions () const inline
Obtain a read-only reference to the Extraction message collection.
Returns
TargetPlotList reference
Definition at line 68 of file History.h.
Referenced by SideCar::GUI::BScope::PPIWidget::PPIWidget().
const TargetPlotListList& SideCar::GUI::BScope::History::getRangeTruths () const inline
Obtain a read-only reference to the TSPI message collection.
Returns
TargetPlotListList reference
Definition at line 74 of file History.h.
Referenced by SideCar::GUI::BScope::PPIWidget::PPIWidget().
const MessageVector& SideCar::GUI::BScope::History::getVideo () const inline
Obtain a read-only reference to the Video collection.
Returns
MessageVector reference
Definition at line 56 of file History.h.
Referenced by SideCar::GUI::BScope::PPIWidget::PPIWidget().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/BScope/History.h
/Users/howes/src/sidecar/GUI/BScope/History.cc