SideCar: SideCar::GUI::Spectrum::SpectrumWidget Class Reference
SideCar::GUI::Spectrum::SpectrumWidget Class Reference
Public Slots
void setFFTSize (int size)
void centerAtCursor ()
void needUpdate ()
void swapViews ()
void popView ()
void popAllViews ()
void zoom (const QPoint &from, const QPoint &to)
void pan (const QPoint &from, const QPoint &to)
Signals
void binsUpdated (const QVector< QPointF > &bins)
void transformChanged ()
void currentCursorPosition (const QPointF &pos)
void showMessageInfo (const Messages::PRIMessage::Ref &msg)
Public Member Functions
SpectrumWidget (QWidget *parent)
Constructor.
void setData (const Messages::PRIMessage::Ref &, const fftw_complex *data)
void setBackground (const QImage &iamge)
void setFrozen (bool state)
void setAzimuthLatch (AzimuthLatch *trigger)
void saveToSettings (QSettings &settings)
void restoreFromSettings (QSettings &settings)
const ViewSettings & getFullView () const
const ViewSettings & getCurrentView () const
void dupView ()
bool canPopView () const
void setCurrentView (const ViewSettings &viewSettings)
const QVector< QPointF > & getBins () const
double getPowerFromMagnitude (const fftw_complex &c) const
Static Public Member Functions
static Logger::Log & Log ()
Detailed Description
Definition at line 29 of file SpectrumWidget.h.
Constructor & Destructor Documentation
SpectrumWidget::SpectrumWidget (QWidget * parent)
Constructor.
Creates a new Visualizer from scratch.
Parameters
parent widget parent
Definition at line 36 of file SpectrumWidget.cc.
References SideCar::GUI::Spectrum::ViewChanger::finished(), SideCar::GUI::Spectrum::App::GetApp(), SideCar::GUI::Spectrum::App::getViewEditor(), LOGDEBUG, LOGINFO, and SideCar::GUI::Spectrum::ViewChanger::mouseMoved().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Spectrum/SpectrumWidget.h
/Users/howes/src/sidecar/GUI/Spectrum/SpectrumWidget.cc