SideCar: Logger::Formatters::Pattern Class Reference
Logger::Formatters::Pattern Class Reference
Concrete Formatter class that uses a formatting pattern (ala printf and friends) to determine what components to put in the formatted output.
#include </Users/howes/src/sidecar/Logger/Formatters.h>
Public Types
using Ref = boost::shared_ptr< Pattern >
Public Types inherited from Logger::Formatters::Formatter
using Ref = boost::shared_ptr< Formatter >
Public Member Functions
void setPattern (const std::string &pattern)
Use a different formatting pattern.
void format (std::ostream &os, const Msg &msg) throw (std::out_of_range)
Build a std::string representation of a Msg object.
Public Member Functions inherited from Logger::Formatters::Formatter
virtual ~Formatter ()
Destructor.
Static Public Member Functions
static Ref Make ()
static Ref Make (const std::string &pattern)
Additional Inherited Members
Protected Member Functions inherited from Logger::Formatters::Formatter
Formatter ()
Constructor.
Detailed Description
Concrete Formatter class that uses a formatting pattern (ala printf and friends) to determine what components to put in the formatted output.
A pattern consists of a text string, with one or more formatting flags. A formatting flag starts with a % character The following formatting flags may be used in a formatting pattern:
% insert a `' character
c insert the log message category value
m insert the log message text
M insert the timestamp's microseconds value
p insert the log message priority name
P insert the log message priority value
S insert the timestamp's seconds value
w insert the timestamp of the log message. This uses the formatting defined by the TimeVal::operator<<() method for std::ostream streams.
W generate a text representation of the timestamp using a format similar to that of the Unix date utility
' take the formatting text between two single quotes and use as the format string for the strftime C library call. See the man page for strftime(3C).
z insert a '
' character
Definition at line 113 of file Formatters.h.
Member Function Documentation
void Pattern::format (std::ostream & os, const Msg & msg) throw (std::out_of_range) virtual
Build a std::string representation of a Msg object.
Parameters
msg object to format
os stream to write to
Implements Logger::Formatters::Formatter.
Definition at line 41 of file Formatters.cc.
References Logger::Priority::GetLongName(), and Logger::Priority::GetShortName().
void Logger::Formatters::Pattern::setPattern (const std::string & pattern) inline
Use a different formatting pattern.
Parameters
pattern formatting pattern to use for log messages.
Definition at line 125 of file Formatters.h.
References Logger::Formatters::Formatter::format(), and Logger::Formatters::Formatter::Formatter().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Logger/Formatters.h
/Users/howes/src/sidecar/Logger/Formatters.cc