SideCar: SideCar::GUI::Preset Class Reference
SideCar::GUI::Preset Class Reference
Collection of Setting values that represent a defined preset for an application.
#include </Users/howes/src/sidecar/GUI/Preset.h>
Public Member Functions
Preset (const QString &name, PresetManager *parent)
Constructor.
Preset * duplicate (const QString &name)
Create a duplicate of this preset.
const QString & getName () const
Obtain the name of the preset.
bool isDirty () const
void setName (const QString &name)
Change the setting's name.
void setValue (int index, const QVariant &value)
Change the held preset value for a given Setting.
void expand (int index, const QVariant &value)
void save (QSettings &file, const QStringList &names)
Save all held preset values to a QSettings object.
void restore (QSettings &file, const QList< Setting * > &settings, bool isActive)
Restore all held preset values from a QSettings object.
void restoreOne (QSettings &file, Setting *setting)
Restore one preset value from a QSettings object.
void apply (const QList< Setting * > &settings)
Apply held preset values to active Setting objects.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the Log device to use for Preset objects.
Friends
class PresetManager
Detailed Description
Collection of Setting values that represent a defined preset for an application.
A Preset object only records the values that make up the preset. It relies on a PresetCollection object to do the actual manipulation of Setting object values when a Preset becomes active.
Definition at line 23 of file Preset.h.
Constructor & Destructor Documentation
Preset::Preset (const QString & name, PresetManager * parent)
Constructor.
Creates a new preset with a given name.
Parameters
name the name of the preset
parent PresetManager owner of the preset
Definition at line 18 of file Preset.cc.
References Log(), and LOGINFO.
Referenced by duplicate().
Member Function Documentation
void Preset::apply (const QList< Setting * > & settings)
Apply held preset values to active Setting objects.
Parameters
settings list of Setting objects to update
Definition at line 147 of file Preset.cc.
References Log(), and LOGINFO.
Referenced by restore().
Preset * Preset::duplicate (const QString & name)
Create a duplicate of this preset.
Parameters
name the name for the new Preset object
Returns
new Preset object containing the same Setting values as this one
Definition at line 27 of file Preset.cc.
References Preset().
const QString& SideCar::GUI::Preset::getName () const inline
Obtain the name of the preset.
Returns
QString reference
Definition at line 55 of file Preset.h.
Logger::Log & Preset::Log () static
Obtain the Log device to use for Preset objects.
Returns
Log reference
Definition at line 12 of file Preset.cc.
References Logger::Log::Find().
Referenced by apply(), Preset(), restore(), restoreOne(), save(), and setValue().
void Preset::restore (QSettings & file, const QList< Setting * > & settings, bool isActive)
Restore all held preset values from a QSettings object.
Parameters
file the QSettings object to read from
settings list of Setting objects to update
isActive if true, apply restored values to Setting objects
Definition at line 83 of file Preset.cc.
References apply(), Log(), LOGDEBUG, and LOGINFO.
void Preset::restoreOne (QSettings & file, Setting * setting)
Restore one preset value from a QSettings object.
Parameters
file the QSettings object to read from
setting the value to restore
Definition at line 123 of file Preset.cc.
References SideCar::GUI::Setting::getName(), SideCar::GUI::Setting::getOpaqueValue(), Log(), LOGDEBUG, and LOGINFO.
void Preset::save (QSettings & file, const QStringList & names)
Save all held preset values to a QSettings object.
Parameters
file the QSettings object to write into
names list of Setting names to write
Definition at line 64 of file Preset.cc.
References Log(), and LOGINFO.
void SideCar::GUI::Preset::setName (const QString & name) inline
Change the setting's name.
Parameters
name new name to use
Definition at line 63 of file Preset.h.
void Preset::setValue (int index, const QVariant & value)
Change the held preset value for a given Setting.
Parameters
index which Setting value to change
value new Setting value
Definition at line 35 of file Preset.cc.
References SideCar::GUI::Setting::getName(), SideCar::GUI::PresetManager::getSetting(), Log(), LOGDEBUG, and LOGINFO.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Preset.h
/Users/howes/src/sidecar/GUI/Preset.cc