SideCar: BufferMat< T > Class Template Reference
BufferMat< T > Class Template Reference
View a submatrix within a Buffer.
#include </Users/howes/src/sidecar/Utils/Buffer/BufferMat.h>
Public Types
using SubMat = vsip::Matrix< T, vsip::impl::Subset_block< vsip::Dense< 2, T > > >
Public Member Functions
BufferMat (Buffer< T > &b, size_t rows=0, size_t cols=0, size_t row=0, int col=0, bool flush=true)
View a subset of the Buffer as a vsip::Matrix.
void setStart (size_t row=0, int col=0)
Sets the location of the first row and column in the parent Buffer.
void setRow (size_t row=0)
Sets the location of the first row in the parent Buffer.
void setCol (int col=0)
Sets the location of the first column in the parent Buffer.
size_t getRow () const
int getCol () const
void flush ()
Force the view to be flushed (written to the buffer)
Data Fields
SubMat m
The vsip::Matrix which is mapped to this subview.
Detailed Description
template<class T>
class BufferMat< T >
View a submatrix within a Buffer.
Bind a vsip::Matrix to a (sub)set of the buffer Copies changes to the wrapped area if the location changes or BufferMat is destroyed. Cannot simply subclass vsip::Matrix since
Matrix(rows,cols) allocates a new block – not good for user-allocated memory
Matrix(Dense&) needs the Dense to be constructed before the Matrix, but the Dense should be created and destroyed by the BufferMat.
the overloaded operator= causes problems
As illustrated in Figure 1, the BufferMat provides a subview of a parent Buffer object. Unlike the strict alignment of BufferRow and BufferCol within the parent Buffer, BufferMat is somewhat free to move around. The only requirements are:
the maximum size of (rows, cols) be able to fit within the parent Buffer's data dimensions of (Buffer::getDataRows(), Buffer::getDataCols())
the first column of the BufferMat must not start before the allocated window column width (-b.wc)
the first column of the BufferMat must not start past the last column of the data area
Acceptable locations for the BufferMat are indicated by shading in Figure 1.
As with the BufferRow, the row indices of BufferMat are taken modulo b.dr to allow for a rolling window into the data.
Placement of a BufferMat within a Buffer
Only matrices up to size (Buffer::getWindowRows(), Buffer::getWindowRows()) are guaranteed to be within the Buffer; lager matrices may fall outside the allocated space depending on their initial row and column within the parent Buffer.
Definition at line 16 of file Buffer.h.
Constructor & Destructor Documentation
template<class T > BufferMat< T >::BufferMat (Buffer< T > & b, size_t rows = 0, size_t cols = 0, size_t row = 0, int col = 0, bool flush = true)
View a subset of the Buffer as a vsip::Matrix.
Creates a Matrix of size (rows, cols) with the top-left corner located at (row, col) in the parent Buffer.
If rows=0, then use all b.dr rows. Similarly, cols=0 selects all b.dc columns.
Parameters
b Buffer to view
rows Number of rows to view. Limited to rows <= Buffer::getDataRows()
cols Number of columns to view. Limited to cols <= Buffer::getDataCols()
row Index of the first row in the parent Buffer
col Index of the first column in the parent Buffer. Limited to the range - Buffer::getWindowCols() < col < Buffer::getDataCols()
flush Whether this view should change the underlying buffer
Definition at line 141 of file BufferMat.h.
Member Function Documentation
template<class T > void BufferMat< T >::flush () inline
Force the view to be flushed (written to the buffer)
This function ignores the flush flag set at object creation. It is useful if you need to ensure consistency of the underlying Buffer without changing the row or column.
Definition at line 94 of file BufferMat.h.
template<class T > int BufferMat< T >::getCol () const inline
Returns
Index of the column which is being viewed
Definition at line 87 of file BufferMat.h.
template<class T > size_t BufferMat< T >::getRow () const inline
Returns
Index of the row which is being viewed
Definition at line 82 of file BufferMat.h.
template<class T > void BufferMat< T >::setCol (int col = 0) inline
Sets the location of the first column in the parent Buffer.
Parameters
col Index of the first column in the parent Buffer. Limited to the range - Buffer::getWindowCols() < col < Buffer::getDataCols()
Definition at line 77 of file BufferMat.h.
References BufferMat< T >::setStart().
template<class T > void BufferMat< T >::setRow (size_t row = 0) inline
Sets the location of the first row in the parent Buffer.
Parameters
row Index of the first row in the parent Buffer
Definition at line 71 of file BufferMat.h.
References BufferMat< T >::setStart().
template<class T > void BufferMat< T >::setStart (size_t row = 0, int col = 0)
Sets the location of the first row and column in the parent Buffer.
Parameters
row Index of the first row in the parent Buffer
col Index of the first column in the parent Buffer. Limited to the range - Buffer::getWindowCols() < col < Buffer::getDataCols()
Definition at line 162 of file BufferMat.h.
References BufferMat< T >::m.
Referenced by BufferMat< T >::setCol(), and BufferMat< T >::setRow().
Field Documentation
template<class T > SubMat BufferMat< T >::m
The vsip::Matrix which is mapped to this subview.
This member is made public for ease of use; any operations on it will use the vsip::Matrix operator overloads.
Definition at line 109 of file BufferMat.h.
Referenced by BufferMat< T >::setStart().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Utils/Buffer/Buffer.h
/Users/howes/src/sidecar/Utils/Buffer/BufferMat.h