SideCar: SideCar::Algorithms::MatchedFilterUtils::WorkerThreads Class Reference
SideCar::Algorithms::MatchedFilterUtils::WorkerThreads Class Reference
Thread pool that generates threads that perform the following in the overridden svc() method:
#include </Users/howes/src/sidecar/Algorithms/MatchedFilter/WorkerThreads.h>
Public Member Functions
WorkerThreads (Algorithm &algorithm, WorkRequestQueue &pendingQueue, WorkRequestQueue &finishedQueue)
Constructor for the thread pool.
~WorkerThreads ()
Destructor.
int svc ()
Override of ACE_Task method.
Static Public Member Functions
static Logger::Log & Log ()
Log device for WorkerThreads objects.
Detailed Description
Thread pool that generates threads that perform the following in the overridden svc() method:
fetch the next WorkRequest object from the pending WorkRequest queue
call the WorkRequest::process() method to process a slice of the data
post the finished WorkRequest object onto the finished WorkRequest queue
Definition at line 21 of file WorkerThreads.h.
Constructor & Destructor Documentation
WorkerThreads::WorkerThreads (Algorithm & algorithm, WorkRequestQueue & pendingQueue, WorkRequestQueue & finishedQueue)
Constructor for the thread pool.
Installs the pending and finished WorkRequest object queues. NOTE: does not create any threads; one must still invoke the ACE_Task::activate() method.
Parameters
algorithm the thread will post output messages to the Algorithm::send() method of this object
\param pendingQueue thread-safe FIFO queue for pending WorkRequest
objects
\param finishedQueue thread-safe FIFO queue for completed WorkRequest
objects
Definition at line 18 of file WorkerThreads.cc.
References Log(), and LOGINFO.
WorkerThreads::~WorkerThreads ()
Destructor.
Here only to emit a log message for debugging.
Definition at line 28 of file WorkerThreads.cc.
References Log(), and LOGINFO.
Member Function Documentation
Logger::Log & WorkerThreads::Log () static
Log device for WorkerThreads objects.
Returns
Logger::Log device reference
Definition at line 11 of file WorkerThreads.cc.
References Logger::Log::Find().
Referenced by svc(), WorkerThreads(), and ~WorkerThreads().
int WorkerThreads::svc ()
Override of ACE_Task method.
Contains the code that runs in a separate thread. When the routine returns, the thread stops.
Returns
always 0.
Definition at line 35 of file WorkerThreads.cc.
References SideCar::Algorithms::MatchedFilterUtils::WorkRequest::FromMessageBlock(), Log(), LOGINFO, LOGWARNING, and SideCar::Algorithms::MatchedFilterUtils::WorkRequest::process().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/MatchedFilter/WorkerThreads.h
/Users/howes/src/sidecar/Algorithms/MatchedFilter/WorkerThreads.cc