SideCar: SideCar::Runner::StreamBuilder Class Reference
SideCar::Runner::StreamBuilder Class Reference
Utility class that creates and populates a new IO::Stream object.
#include </Users/howes/src/sidecar/Runner/StreamBuilder.h>
Static Public Member Functions
static Logger::Log & Log ()
static IO::Stream::Ref Make (const QDomElement &config, const StatusEmitter::Ref &emitter, const std::string &mcastAddress)
Factory method that creates a new IO::Stream object.
Detailed Description
Utility class that creates and populates a new IO::Stream object.
Definition at line 20 of file StreamBuilder.h.
Member Function Documentation
IO::Stream::Ref StreamBuilder::Make (const QDomElement & config, const StatusEmitter::Ref & emitter, const std::string & mcastAddress) static
Factory method that creates a new IO::Stream object.
Parameters
config XML configuration for the stream
Returns
new stream object
Definition at line 53 of file StreamBuilder.cc.
References SideCar::IO::Module::getTask(), LOGDEBUG, LOGINFO, LOGWARNING, SideCar::IO::Channel::setSender(), and Logger::ProcLog::thrower().
Referenced by SideCar::Runner::App::App().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Runner/StreamBuilder.h
/Users/howes/src/sidecar/Runner/StreamBuilder.cc