SideCar: SideCar::IO::ZeroconfTypes::TZCType< id > Class Template Reference
SideCar::IO::ZeroconfTypes::TZCType< id > Class Template Reference
Template class that adds class methods that return character types for the template parameter type ID as well as for its twin ID value.
#include </Users/howes/src/sidecar/IO/ZeroconfRegistry.h>
Static Public Member Functions
static const char * GetZeroconfType ()
Obtain the configured Zeroconf type for objects derived from this class.
static const char * GetTwinZeroconfType ()
Obtain the "twin" Zeroconf type for objects derived from this class.
static std::string MakeZeroconfType (const std::string &subType)
Construct a valid SideCar Zeroconf type string for a given subtype.
static std::string MakeTwinZeroconfType (const std::string &subType)
Construct the twin SideCar Zeroconf type string for a given subtype.
Static Public Member Functions inherited from SideCar::IO::ZeroconfRegistry
static const char * GetType (ID id)
Obtain the Zeroconf type string for a given ID.
static ID GetTwin (ID id)
Locate the twin of this ID.
static std::string MakeZeroconfType (const char *type, const std::string &subType)
Construct a valid SideCar Zeroconf type string for a type and a subtype.
Additional Inherited Members
Public Types inherited from SideCar::IO::ZeroconfRegistry
enum ID {
kPublisher = 0, kSubscriber, kRunnerStatusCollector, kRunnerStatusEmitter,
kStateEmitter, kStateCollector, kRunnerRemoteController, kNumTypes
}
Defined Zeroconf types.
Detailed Description
template<ZeroconfRegistry::ID id>
class SideCar::IO::ZeroconfTypes::TZCType< id >
Template class that adds class methods that return character types for the template parameter type ID as well as for its twin ID value.
Other classes may derive from this template in order to assign a Zeroconf type, and to get methods to access the types.
Definition at line 76 of file ZeroconfRegistry.h.
Member Function Documentation
template<ZeroconfRegistry::ID id> static const char* SideCar::IO::ZeroconfTypes::TZCType< id >::GetTwinZeroconfType () inline static
Obtain the "twin" Zeroconf type for objects derived from this class.
A "twin" is the counterpart of a publisher/subscriber pair. If the template class was defined to be a publisher, then this class method should return the appropriate subscriber type.
Returns
NULL-terminated C string
Definition at line 93 of file ZeroconfRegistry.h.
References SideCar::IO::ZeroconfRegistry::GetTwin(), and SideCar::IO::ZeroconfRegistry::GetType().
template<ZeroconfRegistry::ID id> static const char* SideCar::IO::ZeroconfTypes::TZCType< id >::GetZeroconfType () inline static
Obtain the configured Zeroconf type for objects derived from this class.
Returns
NULL-terminated C string
Definition at line 84 of file ZeroconfRegistry.h.
References SideCar::IO::ZeroconfRegistry::GetType().
Referenced by SideCar::IO::StateEmitter::Log(), and SideCar::Runner::RemoteController::RemoteController().
template<ZeroconfRegistry::ID id> static std::string SideCar::IO::ZeroconfTypes::TZCType< id >::MakeTwinZeroconfType (const std::string & subType) inline static
Construct the twin SideCar Zeroconf type string for a given subtype.
Parameters
subType the data type restriction to apply (eg. Video)
Returns
type string
Definition at line 112 of file ZeroconfRegistry.h.
References SideCar::IO::ZeroconfRegistry::MakeZeroconfType().
Referenced by SideCar::GUI::ChannelSetting::Log(), and SideCar::IO::TCPDataSubscriber::openAndInit().
template<ZeroconfRegistry::ID id> static std::string SideCar::IO::ZeroconfTypes::TZCType< id >::MakeZeroconfType (const std::string & subType) inline static
Construct a valid SideCar Zeroconf type string for a given subtype.
Parameters
subType the data type restriction to apply (eg. Video)
Returns
type string
Definition at line 102 of file ZeroconfRegistry.h.
References SideCar::IO::ZeroconfRegistry::MakeZeroconfType().
Referenced by SideCar::GUI::AScope::ChannelConnectionModel::ChannelConnectionModel(), SideCar::GUI::HealthAndStatus::ChannelConnectionModel::Log(), SideCar::IO::TCPDataPublisher::openAndInit(), and SideCar::IO::MulticastDataPublisher::openAndInit().
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/IO/ZeroconfRegistry.h