SideCar: SideCar::GUI::Spectrum::WorkRequest Class Reference
SideCar::GUI::Spectrum::WorkRequest Class Reference
Representation of an FFT processing step.
#include </Users/howes/src/sidecar/GUI/Spectrum/WorkRequest.h>
Public Slots
void setGateStart (int value)
void setInputSmoothing (int value)
void setZeroPad (bool value)
Public Member Functions
WorkRequest (const WeightWindow &weightWindow)
Constructor for the first or 'master' WorkRequest object.
WorkRequest (const WorkRequest &master)
Constructor for 'slave' WorkRequest objects (all but the first).
~WorkRequest ()
Destructor.
void clear ()
Reset the counter of accumulated input messages.
int getAccumulated () const
bool addData (const Messages::Video::Ref &msg)
size_t getFFTSize () const
void execute ()
const fftw_complex * getOutput () const
const Messages::Video::Ref & getLastMessage () const
Static Public Member Functions
static Logger::Log & Log ()
Log device to use for WorkRequest log messages.
Detailed Description
Representation of an FFT processing step.
Accumulates input data that will be used for an FFT, as well as the results of an FFT calculation.
Definition at line 21 of file WorkRequest.h.
Constructor & Destructor Documentation
WorkRequest::WorkRequest (const WeightWindow & weightWindow)
Constructor for the first or 'master' WorkRequest object.
This object will create a FFTW3 plan for use by all other WorkRequest objects to efficiently perform their FFT calculations.
Parameters
weightWindow the WeightWindow object to use for input sample shaping. Also defines the FFT size.
gateStart the first sample in the input data to use for the FFT
smoothing number of input messages to accumulate and average before submitting to an FFT.
Definition at line 18 of file WorkRequest.cc.
References SideCar::GUI::Spectrum::App::GetApp().
WorkRequest::WorkRequest (const WorkRequest & master)
Constructor for 'slave' WorkRequest objects (all but the first).
Parameters
master defintion to copy
Definition at line 41 of file WorkRequest.cc.
References SideCar::GUI::Spectrum::App::GetApp().
WorkRequest::~WorkRequest ()
Destructor.
If the master WorkRequest, destroys the FFTW3 plan object.
Definition at line 61 of file WorkRequest.cc.
References Log(), LOGDEBUG, and LOGINFO.
Member Function Documentation
Logger::Log & WorkRequest::Log () static
Log device to use for WorkRequest log messages.
Returns
Log device
Definition at line 12 of file WorkRequest.cc.
References Logger::Log::Find().
Referenced by ~WorkRequest().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Spectrum/WorkRequest.h
/Users/howes/src/sidecar/GUI/Spectrum/WorkRequest.cc