SideCar: UnitTest::ProcSuite< T > Class Template Reference
UnitTest::ProcSuite< T > Class Template Reference
Template class that represents a collection of unit test methods within one class.
#include </Users/howes/src/sidecar/UnitTest/ProcSuite.h>
Public Types
using Proc) = void(T::*)(
Definition of type that represents a method pointer for class T.
using NamedProc = std::pair< std::string, Proc >
Definition of type stored in std::vector collection.
Public Member Functions
ProcSuite (T *obj, const std::string &name) throw ()
Constructor with existing T object that will be used to call the all of the registered methods.
ProcSuite (const std::string &name) throw ()
Constructor which creates a new T object to be used to call the all of the registered methods.
~ProcSuite ()
Destructor.
virtual int numTests () const throw ()
virtual RunResults & run (RunResults &rr) throw ()
Execute the unit tests this object represents.
void add (const char *name, Proc p) throw ()
Add the given class T method to our set of unit test methods.
Public Member Functions inherited from UnitTest::TestObj
TestObj () throw ()
Default contructor.
TestObj (const std::string &name) throw ()
Contructor.
virtual ~TestObj ()
Destructor.
virtual int mainRun (std::ostream *os=&std::cerr) throw ()
Utility method useful in main() to run unit tests.
void setTestName (const std::string &name) throw ()
Set the test name to the given value.
const std::string & testName () const throw ()
Get the name of this test object.
void _assertTrue (bool value, const char *expr, const char *file, int line) const throw (UnitTestException)
Assertion for a true value.
void _assertTrue (std::istream &value, const char *expr, const char *file, int line) const throw (UnitTestException)
Assertion for a good std::istream value.
void _assertFalse (bool value, const char *expr, const char *file, int line) const throw (UnitTestException)
Assertion for a false value.
void _assertFalse (std::istream &value, const char *expr, const char *file, int line) const throw (UnitTestException)
Assertion for a good std::istream value.
template<typename T >
void _assertEqual (const T &expected, const T &actual, const char *file, int line) const throw (UnitTestException)
Assertion that two values of some type T are equal.
template<typename T >
void _assertEqual (const T *expected, const T *actual, const char *file, int line) const throw (UnitTestException)
Assertion that two values of some type pointer are equal.
void _assertEqual (std::string expected, std::string actual, const char *file, int line) const throw (UnitTestException)
Assertion that two strings are equal.
void _assertEqual (double expected, double actual, const char *file, int line) const throw (UnitTestException)
void _assertEqual (double expected, double actual, double epsilon, const char *file, int line) const throw (UnitTestException)
Assertion that two values are equal within some tolerance factor.
template<typename T >
void _assertNotEqual (const T &expected, const T &actual, const char *file, int line) const throw (UnitTestException)
Assertion that two values are NOT equal.
template<typename T >
void _assertNotEqual (const T *expected, const T *actual, const char *file, int line) const throw (UnitTestException)
void _assertNotEqual (std::string expected, std::string actual, const char *file, int line) const throw (UnitTestException)
Assertion that two strings are NOT equal.
void _assertNotEqual (double expected, double actual, const char *file, int line) const throw (UnitTestException)
void _assertNotEqual (double expected, double actual, double epsilon, const char *file, int line) const throw (UnitTestException)
Assertion that two values are NOT equal within some tolerance factor.
Protected Member Functions
virtual void test ()
Method to perform the unit test.
Detailed Description
template<typename T>
class UnitTest::ProcSuite< T >
Template class that represents a collection of unit test methods within one class.
Extends the TestObj interface to register one or more methods of a class that perform the actual unit tests. Executing ProcSuite::run() calls them all in the order in which they were registered. Here's a quick example of how to set up a ProcSuite:
struct Foobar : public UnitTest::TestObj
{
void testFoobar() { assertEqual(2, 2); }
static void Install(UnitTest::ProcSuite<Foobar>& ps)
{
// Register the method testFoobar with the given ProcSuite object.
ps.add("testFoobar", &Foobar::testFoobar);
}
};
int
main()
{
UnitTest::ProcSuite<Foobar> ps("ProcSuite");
Foobar::Install(ps);
return ps.mainRun();
}
Definition at line 41 of file ProcSuite.h.
Member Typedef Documentation
template<typename T> using UnitTest::ProcSuite< T >::NamedProc = std::pair<std::string,Proc>
Definition of type stored in std::vector collection.
First element of std::pair is the name of the unit test, and the second is the pointer to the class method to call to perform the test.
Definition at line 52 of file ProcSuite.h.
Constructor & Destructor Documentation
template<typename T> UnitTest::ProcSuite< T >::ProcSuite (T * obj, const std::string & name) throw () inline
Constructor with existing T object that will be used to call the all of the registered methods.
Adds a '.' to the name as a separator – in the ProcSuite::run method, test names are prepended with this name so that any logged failures have a full inheritance path name.
Parameters
obj object to use for registered method calls
name name of this test collection
Definition at line 62 of file ProcSuite.h.
template<typename T> UnitTest::ProcSuite< T >::ProcSuite (const std::string & name) throw () inline
Constructor which creates a new T object to be used to call the all of the registered methods.
Adds a '.' to the name as a separator – in the ProcSuite::run method, test names are prepended with this name so that any logged failures have a full inheritance path name.
Parameters
name name of this test collection
Definition at line 70 of file ProcSuite.h.
template<typename T> UnitTest::ProcSuite< T >::~ProcSuite () inline
Destructor.
Cleans up any previously-allocated test object.
Definition at line 74 of file ProcSuite.h.
Member Function Documentation
template<typename T> void UnitTest::ProcSuite< T >::add (const char * name, Proc p) throw () inline
Add the given class T method to our set of unit test methods.
Associate the name with the method for logging purposes.
Parameters
name name for the unit test
p pointer to the class method to call to run a unit test
Definition at line 119 of file ProcSuite.h.
template<typename T> virtual int UnitTest::ProcSuite< T >::numTests () const throw () inline virtual
Returns
the number of unit tests this object represents. Unlike Suite::numTests, this is simply the value of std::vector::size().
Reimplemented from UnitTest::TestObj.
Definition at line 79 of file ProcSuite.h.
template<typename T> virtual RunResults& UnitTest::ProcSuite< T >::run (RunResults & rr) throw () inline virtual
Execute the unit tests this object represents.
Loops thru all of the registered unit test methods, and invokes each one, recording their pass/fail value. See also ProcSuite::test() below.
Parameters
rr RunResults object to record the test results
Returns
RunResults object that was used
Reimplemented from UnitTest::TestObj.
Definition at line 89 of file ProcSuite.h.
References UnitTest::TestObj::run(), UnitTest::TestObj::setTestName(), and UnitTest::TestObj::testName().
template<typename T> virtual void UnitTest::ProcSuite< T >::test () inline protected virtual
Method to perform the unit test.
Here, we call the registered object method to perform the unit test. Any exceptions encountered here will be caught in the TestObj::run() method.
Reimplemented from UnitTest::TestObj.
Definition at line 132 of file ProcSuite.h.
References UnitTest::TestObj::testName().
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/UnitTest/ProcSuite.h