SideCar: SideCar::GUI::AScope::HistoryControlWidget Class Reference
SideCar::GUI::AScope::HistoryControlWidget Class Reference
Tool window that allows the user to move back in time to a previous frame of data.
#include </Users/howes/src/sidecar/GUI/AScope/HistoryControlWidget.h>
Public Slots
void activeDisplayViewChanged (DisplayView *displayView)
Signals
void positionChange (int)
Public Member Functions
HistoryControlWidget (ToolBar *parent)
Constructor.
void manage (HistoryPosition *historyPosition)
Static Public Member Functions
static Logger::Log & Log ()
Detailed Description
Tool window that allows the user to move back in time to a previous frame of data.
Shows information about the previous frame as well as the size of the history buffer. It does not manipulate the application's History object, only reports information about it. It will change the active MainWindow's HistoryPosition when the user adjusts the history position slider.
Definition at line 26 of file HistoryControlWidget.h.
Constructor & Destructor Documentation
HistoryControlWidget::HistoryControlWidget (ToolBar * parent)
Constructor.
Creates and initializes window widgets.
Parameters
shortcut key sequence to change window visibility
history application History object to work with
Definition at line 23 of file HistoryControlWidget.cc.
References SideCar::GUI::AScope::App::GetApp(), SideCar::GUI::AScope::History::getFrameCount(), SideCar::GUI::AScope::HistoryPosition::getPastPosition(), SideCar::GUI::AScope::DisplayView::getVisualizer(), SideCar::GUI::OnOffSettingsBlock::isEnabled(), and SideCar::GUI::AScope::HistoryPosition::setPosition().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/AScope/HistoryControlWidget.h
/Users/howes/src/sidecar/GUI/AScope/HistoryControlWidget.cc