SideCar: SideCar::Algorithms::DownConverterUtils::Channel Class Reference
SideCar::Algorithms::DownConverterUtils::Channel Class Reference
Utility class for DownConverter that manages data from one input channel.
#include </Users/howes/src/sidecar/Algorithms/DownConverter/Channel.h>
Public Member Functions
Channel (DownConverter &master, size_t maxBufferSize)
Constructor for a DownConverter data channel.
size_t getBufferSize () const
void setMaxBufferSize (size_t maxBufferSize)
Change the max buffer size.
void reset ()
Reset to a know state.
bool isEmpty () const
Determine if there are any messages in the internal buffer.
uint32_t getNextSequence () const
Obtain the sequence counter of the oldest message in the buffer.
bool addData (const Messages::Video::Ref &msg)
Add a new message to the channel's buffer.
bool prune (uint32_t sequenceCounter)
Remove entries that have VME sequence counter 'older' than a given one.
void getSlice (int offset, int span, VsipComplexVector &slice)
Messages::Video::Ref getData () const
Messages::Video::Ref popData ()
Public Member Functions inherited from SideCar::Algorithms::TProcessor< Channel, Messages::Video >
TProcessor (Channel *obj, Proc proc)
Constructor.
bool process (const Messages::Header::Ref &msg)
Implementation of the Processor base class method.
Public Member Functions inherited from SideCar::Algorithms::Processor
virtual ~Processor ()
Destructor.
Static Public Member Functions
static Logger::Log & Log ()
Additional Inherited Members
Public Types inherited from SideCar::Algorithms::TProcessor< Channel, Messages::Video >
using Proc = boost::function< bool(Channel *, typename Messages::Video::Ref)>
Type definition for a method of class P that can process messages of class M.
Detailed Description
Utility class for DownConverter that manages data from one input channel.
Contains an internal deque (FIFO) that allows the channel to synchronize with other Channel objects based on VME sequence counter value.
Definition at line 19 of file Channel.h.
Constructor & Destructor Documentation
Channel::Channel (DownConverter & master, size_t maxBufferSize)
Constructor for a DownConverter data channel.
Parameters
master
maxBufferSize
auxIndex
Definition at line 17 of file Channel.cc.
Member Function Documentation
bool Channel::addData (const Messages::Video::Ref & msg)
Add a new message to the channel's buffer.
Parameters
msg message to add
Returns
true if
Definition at line 39 of file Channel.cc.
References LOGDEBUG, LOGERROR, LOGINFO, and SideCar::Algorithms::DownConverter::process().
Referenced by getNextSequence().
uint32_t SideCar::Algorithms::DownConverterUtils::Channel::getNextSequence () const inline
Obtain the sequence counter of the oldest message in the buffer.
NOTE: not safe to call when buffer is empty.
Returns
sequence counter of oldest message in the buffer.
Definition at line 60 of file Channel.h.
References addData(), and prune().
Referenced by SideCar::Algorithms::DownConverter::process().
bool SideCar::Algorithms::DownConverterUtils::Channel::isEmpty () const inline
Determine if there are any messages in the internal buffer.
Returns
true if so
Definition at line 53 of file Channel.h.
Referenced by SideCar::Algorithms::DownConverter::process().
bool Channel::prune (uint32_t sequenceCounter)
Remove entries that have VME sequence counter 'older' than a given one.
Since sequence counter values should be monotonically increasing, except when wrapping around to zero, 'older' means a value that is less than the given value, or if the given value is zero, greater than the value + maxBufferSize.
Parameters
sequenceCounter the VME sequence counter to use for testing
Returns
true if the channel is empty
Definition at line 96 of file Channel.cc.
References LOGDEBUG, and LOGINFO.
Referenced by getNextSequence(), and SideCar::Algorithms::DownConverter::process().
void Channel::setMaxBufferSize (size_t maxBufferSize)
Change the max buffer size.
Parameters
maxBufferSize new max buffer size
Definition at line 25 of file Channel.cc.
References LOGDEBUG, and LOGINFO.
Referenced by SideCar::Algorithms::DownConverter::process().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/DownConverter/Channel.h
/Users/howes/src/sidecar/Algorithms/DownConverter/Channel.cc