SideCar: Logger::Priority Class Reference
Logger::Priority Class Reference
Representation of a log message priority.
#include </Users/howes/src/sidecar/Logger/Priority.h>
Data Structures
struct InvalidLevel
Invalid priority level given to the Find class method.
struct InvalidName
Invalid priority name given to the Find class method.
struct PriorityException
Base class for all Priority class exceptions.
Public Types
enum Level {
kNone = 0, kFatal, kError, kWarning,
kInfo, kTraceIn, kTraceOut, kDebug,
kDebug1 = kDebug, kDebug2, kDebug3, kNumLevels
}
Level values.
Static Public Member Functions
static Priority::Level Find (std::string name) throw (InvalidName)
Locate a Priority instance under a given name.
static const char * GetShortName (Level level) throw (InvalidLevel)
Locate a Priority instance with a given level.
static const char * GetLongName (Level level) throw (InvalidLevel)
Locate a Priority instance with a given level.
static const char *const * GetShortNames ()
Obtain a pointer to all of the priority names.
static const char *const * GetLongNames ()
Obtain a pointer to all of the priority names.
Detailed Description
Representation of a log message priority.
All messages are issued at a certain priority level, and Log instances have a level setting, below which no messages are emitted.
Definition at line 12 of file Priority.h.
Member Function Documentation
Priority::Level Priority::Find (std::string name) throw (InvalidName) static
Locate a Priority instance under a given name.
Parameters
name key to use for the search
Returns
Priority instance found
Definition at line 48 of file Priority.cc.
Referenced by Logger::Configurator::load().
const char * Priority::GetLongName (Level level) throw (InvalidLevel) static
Locate a Priority instance with a given level.
Parameters
level to look for
Returns
Priority instance found
Definition at line 76 of file Priority.cc.
Referenced by Logger::Formatters::Verbose::format(), Logger::Formatters::Pattern::format(), and SideCar::GUI::Master::RunnerLog::showWindow().
const char *const * Priority::GetLongNames () static
Obtain a pointer to all of the priority names.
Returns
read-only C string array
Definition at line 89 of file Priority.cc.
Referenced by SideCar::Algorithms::Controller::getTimerSecs().
const char * Priority::GetShortName (Level level) throw (InvalidLevel) static
Locate a Priority instance with a given level.
Parameters
level to look for
Returns
Priority instance found
Definition at line 69 of file Priority.cc.
Referenced by Logger::Formatters::Terse::format(), and Logger::Formatters::Pattern::format().
const char *const * Priority::GetShortNames () static
Obtain a pointer to all of the priority names.
Returns
read-only C string array
Definition at line 83 of file Priority.cc.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Logger/Priority.h
/Users/howes/src/sidecar/Logger/Priority.cc