SideCar: SideCar::GUI::MainWindowBase Class Reference
SideCar::GUI::MainWindowBase Class Reference
Common base class for all SideCar GUI projects.
#include </Users/howes/src/sidecar/GUI/MainWindowBase.h>
Public Slots
virtual void showAndRaise ()
Convenience slot method that shows our window, raises it to the top of the window layer, and then activates it.
Public Member Functions
MainWindowBase ()
Constructor.
~MainWindowBase ()
Destructor.
virtual void initialize ()
Complete widget initialization.
QAction * getShowAction ()
Obtain the QAction object that toggles the tool window's visibility.
void setFixedSize ()
Configure the window so that the user may not resize it.
virtual void saveToSettings (QSettings &settings)
Save window settings in a QSettings object.
virtual void restoreFromSettings (QSettings &settings)
Restore a window configuration using settings from a QSettings object.
void setWindowTitle (const QString &windowTitle)
Shadow of QWidget::setWindowTitle() method.
QMenu * getWindowMenu () const
Obtain the 'Window' menu for this window.
QMenu * getToolBarMenu () const
Obtain the menu item that holds QAction items that control the visibility of toolbars registered with makeToolBar().
virtual void windowMenuAboutToShow (QList< QAction * > &actions)
Notification from the application's WindowManager that the 'Window' menu is about to show itself.
void setRestorable (bool state)
If a window is restorable, then the active WindowManager object will call its saveToSettings() method when the application quits.
bool isRestorable () const
Determine of the window is restorable.
void setVisibleAfterRestore (bool state)
If a window is restorable, this flag controls whether is it also initially visible to the user when it is restored.
bool isVisibleAfterRestore () const
Determine if the window should be visible when the application relaunches.
Static Public Member Functions
static Logger::Log & Log ()
Log device for instances of this class.
static AppBase * getApp ()
Obtain the application object.
Protected Member Functions
void setWindowMenu (QMenu *menu)
Install a QMenu object to use for the window's 'Window' menu.
void setContextMenu (QMenu *menu)
Install a QMenu object to use for the window's context menu (the menu that pops up when the user right-clicks (or CTRL+click on Mac) inside the window.
virtual void makeMenuBar ()
Create the window's QMenuBar object.
virtual void fillContextMenu (QMenu *menu)
Add QAction objects to the QMenu object used as a context menu.
virtual QAction * makeShowAction (int shortcut=0)
Create a new QAction that controls our visibility.
QAction * makeMenuAction (const QString &title, const char *slot=0, int shortcut=0)
Create a new QAction object, with this as the parent of the new object and the receiver of the action's triggered() signal.
virtual ToolBar * makeToolBar (const QString &title, Qt::ToolBarArea area=Qt::TopToolBarArea)
Create a new QToolBar object with a given title and initial position.
bool event (QEvent *event)
void contextMenuEvent (QContextMenuEvent *event)
Called in response to a user request to show a context menu.
void showEvent (QShowEvent *event)
Called just before the window is shown to the user.
void closeEvent (QCloseEvent *event)
Called when the widget has been closed, either programmatically or due to user action.
void changeEvent (QEvent *event)
Looks for QEvent::WindowStateChange events to detect when entering/exiting full-screen mode in order to hide/show the menu and status bars.
Detailed Description
Common base class for all SideCar GUI projects.
Holds features and functionality shared among all of the GUI applications. Saves and restores the window position and size between application runs. Manages window minimization, mazimization, and full-screen mode using a common window menu, managed by the application's WindowManager object.
Definition at line 23 of file MainWindowBase.h.
Member Function Documentation
void MainWindowBase::changeEvent (QEvent * event) protected
Looks for QEvent::WindowStateChange events to detect when entering/exiting full-screen mode in order to hide/show the menu and status bars.
Override of QWidget method.
Parameters
event event descriptor
Definition at line 147 of file MainWindowBase.cc.
References Log(), LOGDEBUG, and LOGINFO.
void MainWindowBase::closeEvent (QCloseEvent * event) protected
Called when the widget has been closed, either programmatically or due to user action.
Removes the window from management by AppBase. Overrides of QWidget method.
Parameters
event event descriptor
Definition at line 207 of file MainWindowBase.cc.
References getApp(), SideCar::GUI::AppBase::getNumManagedWindows(), SideCar::GUI::AppBase::isQuitting(), Log(), saveToSettings(), and SideCar::GUI::AppBase::unmanageWindow().
Referenced by SideCar::GUI::Master::ConfigurationEditor::ConfigurationEditor(), SideCar::GUI::BScope::MainWindow::initialize(), SideCar::GUI::PPIDisplay::MainWindow::MainWindow(), SideCar::GUI::Playback::MainWindow::MainWindow(), SideCar::GUI::HealthAndStatus::MainWindow::MainWindow(), SideCar::GUI::Spectrum::MainWindow::MainWindow(), SideCar::GUI::Master::MainWindow::MainWindow(), SideCar::GUI::ESScope::MainWindow::MainWindow(), SideCar::GUI::Master::NotesWindow::NotesWindow(), and SideCar::GUI::SignalGenerator::MainWindow::saveToSettings().
void MainWindowBase::contextMenuEvent (QContextMenuEvent * event) protected
Called in response to a user request to show a context menu.
Displays one if a derived class overrides getContextMenu() to return a non-NULL value. Override of QWidget method.
Parameters
event event descriptor
Definition at line 140 of file MainWindowBase.cc.
void MainWindowBase::fillContextMenu (QMenu * menu) protected virtual
Add QAction objects to the QMenu object used as a context menu.
Invoked from within the initialize() method.
Parameters
menu the QMenu object to work with
Definition at line 100 of file MainWindowBase.cc.
Referenced by initialize().
AppBase * MainWindowBase::getApp () static
Obtain the application object.
Returns
AppBase object
Definition at line 49 of file MainWindowBase.cc.
References SideCar::GUI::AppBase::GetApp().
Referenced by closeEvent(), SideCar::GUI::Master::ConfigurationEditor::ConfigurationEditor(), SideCar::GUI::Master::LogViewWindow::LogViewWindow(), SideCar::GUI::PRIEmitter::MainWindow::MainWindow(), makeMenuBar(), SideCar::GUI::Master::NotesWindow::NotesWindow(), and showEvent().
QAction * MainWindowBase::getShowAction ()
Obtain the QAction object that toggles the tool window's visibility.
If one does not yet exist, it will invoke makeShowAction() to create one.
Returns
QAction object
Definition at line 106 of file MainWindowBase.cc.
References makeShowAction().
QMenu* SideCar::GUI::MainWindowBase::getToolBarMenu () const inline
Obtain the menu item that holds QAction items that control the visibility of toolbars registered with makeToolBar().
Returns
QMenu object
Definition at line 97 of file MainWindowBase.h.
Referenced by SideCar::GUI::WindowManager::unmanageWindow().
QMenu* SideCar::GUI::MainWindowBase::getWindowMenu () const inline
Obtain the 'Window' menu for this window.
The 'Window' menu contains window-specific actions such as 'Maximize' and 'Minimize', and it also maintains a list of open windows for easy selection by the user.
Returns
QMenu object
Definition at line 90 of file MainWindowBase.h.
Referenced by SideCar::GUI::Master::ConfigurationEditor::ConfigurationEditor(), SideCar::GUI::Master::NotesWindow::NotesWindow(), and showEvent().
void MainWindowBase::initialize () virtual
Complete widget initialization.
As this is a virtual method, derived classes should override this to implement their custom initialization. The constructor is not a good place for some initialization because virtual methods are not honored there.
Reimplemented in SideCar::GUI::BScope::MainWindow.
Definition at line 55 of file MainWindowBase.cc.
References fillContextMenu(), and makeMenuBar().
Referenced by SideCar::GUI::AppBase::addToolWindow(), SideCar::GUI::PPIDisplay::PPIWidget::changeZoom(), SideCar::GUI::Master::ConfigurationInfo::getEditor(), SideCar::GUI::BScope::MainWindow::initialize(), SideCar::GUI::PPIDisplay::PPIWidget::initializeContext(), SideCar::GUI::BScope::PPIWidget::PPIWidget(), SideCar::GUI::Master::RecordingInfo::RecordingInfo(), and showEvent().
bool SideCar::GUI::MainWindowBase::isRestorable () const inline
Determine of the window is restorable.
Returns
true if so
Definition at line 120 of file MainWindowBase.h.
Referenced by SideCar::GUI::WindowManager::getManagedWindow().
bool SideCar::GUI::MainWindowBase::isVisibleAfterRestore () const inline
Determine if the window should be visible when the application relaunches.
Returns
true if so
Definition at line 134 of file MainWindowBase.h.
Logger::Log & MainWindowBase::Log () static
Log device for instances of this class.
Returns
log device
Definition at line 23 of file MainWindowBase.cc.
References Logger::Log::Find().
Referenced by changeEvent(), closeEvent(), MainWindowBase(), restoreFromSettings(), saveToSettings(), showEvent(), and ~MainWindowBase().
QAction * MainWindowBase::makeMenuAction (const QString & title, const char * slot = 0, int shortcut = 0) protected
Create a new QAction object, with this as the parent of the new object and the receiver of the action's triggered() signal.
Parameters
title name of the new action
slot the slot to connect to the action's triggered() signal.
shortcut key sequence associated with the action
Returns
new QAction object
Definition at line 230 of file MainWindowBase.cc.
References SideCar::GUI::MakeMenuAction().
Referenced by makeShowAction().
void MainWindowBase::makeMenuBar () protected virtual
Create the window's QMenuBar object.
Populates it with QMenu objects. This implementation creates or uses the following menus:
Tools
Window
Logging
Definition at line 70 of file MainWindowBase.cc.
References getApp().
Referenced by initialize().
QAction * MainWindowBase::makeShowAction (int shortcut = 0) protected virtual
Create a new QAction that controls our visibility.
Invoked from getShowAction(). The default behavior is to create a new QAction with no key shortcut. Derived classes can override this, and provide a different shortcut value.
Parameters
shortcut key shortcut to use for the QAction
Returns
new QAction object
Definition at line 237 of file MainWindowBase.cc.
References makeMenuAction(), and showAndRaise().
Referenced by getShowAction().
ToolBar * MainWindowBase::makeToolBar (const QString & title, Qt::ToolBarArea area = Qt::TopToolBarArea) protected virtual
Create a new QToolBar object with a given title and initial position.
Add a visibility QAction object to the internal toolbar menu to control toolbar visibility.
Parameters
title name of the new toolbar, as shown in the toolbar menu
area default location for the toolbar
Returns
new QToolBar object
Definition at line 251 of file MainWindowBase.cc.
Referenced by SideCar::GUI::PPIDisplay::MainWindow::MainWindow(), SideCar::GUI::Spectrum::MainWindow::MainWindow(), SideCar::GUI::BScope::MainWindow::MainWindow(), SideCar::GUI::Master::MainWindow::MainWindow(), SideCar::GUI::ESScope::MainWindow::MainWindow(), and SideCar::GUI::AScope::MainWindow::MainWindow().
void MainWindowBase::restoreFromSettings (QSettings & settings) virtual
Restore a window configuration using settings from a QSettings object.
Parameters
settings container with the window settings to use
Reimplemented in SideCar::GUI::AScope::MainWindow, SideCar::GUI::HealthAndStatus::MainWindow, SideCar::GUI::Spectrum::MainWindow, SideCar::GUI::SignalGenerator::MainWindow, SideCar::GUI::BScope::PlayerWindow, and SideCar::GUI::BScope::FramesWindow.
Definition at line 123 of file MainWindowBase.cc.
References Log(), and LOGINFO.
Referenced by SideCar::GUI::BScope::MainWindow::initialize(), SideCar::GUI::PPIDisplay::MainWindow::MainWindow(), SideCar::GUI::Master::MainWindow::MainWindow(), SideCar::GUI::SignalGenerator::MainWindow::restoreFromSettings(), SideCar::GUI::Spectrum::MainWindow::restoreFromSettings(), SideCar::GUI::HealthAndStatus::MainWindow::restoreFromSettings(), SideCar::GUI::AScope::MainWindow::restoreFromSettings(), and showEvent().
void MainWindowBase::saveToSettings (QSettings & settings) virtual
Save window settings in a QSettings object.
Parameters
settings container to hold the window settings
Reimplemented in SideCar::GUI::AScope::MainWindow, SideCar::GUI::HealthAndStatus::MainWindow, SideCar::GUI::SignalGenerator::MainWindow, SideCar::GUI::Spectrum::MainWindow, SideCar::GUI::BScope::PlayerWindow, and SideCar::GUI::BScope::FramesWindow.
Definition at line 114 of file MainWindowBase.cc.
References Log(), and LOGINFO.
Referenced by closeEvent(), SideCar::GUI::BScope::MainWindow::initialize(), SideCar::GUI::PPIDisplay::MainWindow::MainWindow(), SideCar::GUI::Master::MainWindow::MainWindow(), SideCar::GUI::Spectrum::MainWindow::saveToSettings(), SideCar::GUI::HealthAndStatus::MainWindow::saveToSettings(), and SideCar::GUI::AScope::MainWindow::saveToSettings().
void SideCar::GUI::MainWindowBase::setContextMenu (QMenu * menu) inline protected
Install a QMenu object to use for the window's context menu (the menu that pops up when the user right-clicks (or CTRL+click on Mac) inside the window.
Parameters
menu the QMenu to use
Definition at line 156 of file MainWindowBase.h.
void SideCar::GUI::MainWindowBase::setRestorable (bool state) inline
If a window is restorable, then the active WindowManager object will call its saveToSettings() method when the application quits.
When the application launches again, it will recreate the saved MainWindowBase objects, restoring them to their original size and location.
Parameters
state new state to use
Definition at line 113 of file MainWindowBase.h.
void SideCar::GUI::MainWindowBase::setVisibleAfterRestore (bool state) inline
If a window is restorable, this flag controls whether is it also initially visible to the user when it is restored.
Parameters
state new state to use
Definition at line 127 of file MainWindowBase.h.
Referenced by SideCar::GUI::Master::NotesWindow::NotesWindow(), and SideCar::GUI::BScope::App::restoreWindows().
void SideCar::GUI::MainWindowBase::setWindowMenu (QMenu * menu) inline protected
Install a QMenu object to use for the window's 'Window' menu.
Should be invoked prior to initialize().
Parameters
menu the QMenu to use
Definition at line 149 of file MainWindowBase.h.
Referenced by SideCar::GUI::Master::ConfigurationEditor::ConfigurationEditor(), and SideCar::GUI::Master::NotesWindow::NotesWindow().
void MainWindowBase::setWindowTitle (const QString & windowTitle)
Shadow of QWidget::setWindowTitle() method.
Informs the AppBase object managing the window of the title change.
Parameters
windowTitle
Definition at line 243 of file MainWindowBase.cc.
Referenced by SideCar::GUI::Master::ConfigurationEditor::ConfigurationEditor(), SideCar::GUI::Master::LogViewWindow::LogViewWindow(), SideCar::GUI::PPIDisplay::MainWindow::MainWindow(), SideCar::GUI::ZeroconfMonitor::MainWindow::MainWindow(), SideCar::GUI::HealthAndStatus::MainWindow::MainWindow(), SideCar::GUI::Playback::MainWindow::MainWindow(), SideCar::GUI::Spectrum::MainWindow::MainWindow(), SideCar::GUI::BScope::MainWindow::MainWindow(), SideCar::GUI::Master::MainWindow::MainWindow(), SideCar::GUI::ESScope::MainWindow::MainWindow(), SideCar::GUI::AScope::MainWindow::MainWindow(), SideCar::GUI::PRIEmitter::MainWindow::MainWindow(), SideCar::GUI::Master::NotesWindow::NotesWindow(), and SideCar::GUI::PRIEmitter::MainWindow::openFile().
void MainWindowBase::showEvent (QShowEvent * event) protected
Called just before the window is shown to the user.
Calls AppBase::manageWindow() to tell the application manage our window with its Window menu. Override of QWidget method.
Parameters
event event descriptor
Definition at line 179 of file MainWindowBase.cc.
References getApp(), getWindowMenu(), initialize(), Log(), LOGINFO, SideCar::GUI::AppBase::manageWindow(), restoreFromSettings(), and showAndRaise().
Referenced by SideCar::GUI::BScope::MainWindow::initialize(), SideCar::GUI::PPIDisplay::MainWindow::MainWindow(), SideCar::GUI::Master::MainWindow::MainWindow(), and SideCar::GUI::ESScope::MainWindow::MainWindow().
virtual void SideCar::GUI::MainWindowBase::windowMenuAboutToShow (QList< QAction * > & actions) inline virtual
Notification from the application's WindowManager that the 'Window' menu is about to show itself.
Derived classes should override this method if they need to update one or more QAction objects before the menu is displayed.
Parameters
actions list of QAction objects that make up the 'Window' menu.
Reimplemented in SideCar::GUI::AScope::MainWindow.
Definition at line 105 of file MainWindowBase.h.
Referenced by SideCar::GUI::WindowManager::unmanageWindow(), and SideCar::GUI::AScope::MainWindow::windowMenuAboutToShow().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/MainWindowBase.h
/Users/howes/src/sidecar/GUI/MainWindowBase.cc