SideCar: SideCar::GUI::StencilBufferState Class Reference
SideCar::GUI::StencilBufferState Class Reference
Utility class that turns on Open/GL stencil buffer tesing only if it is used, and disables it when destructed.
#include </Users/howes/src/sidecar/GUI/StencilBufferState.h>
Public Member Functions
StencilBufferState ()
Constructor.
~StencilBufferState ()
Destructor.
void use ()
Enable the stencil test if necessary, and clear the stencil buffer.
Detailed Description
Utility class that turns on Open/GL stencil buffer tesing only if it is used, and disables it when destructed.
Definition at line 10 of file StencilBufferState.h.
Constructor & Destructor Documentation
SideCar::GUI::StencilBufferState::StencilBufferState () inline
Constructor.
Assumes that GL_STENCIL_TEST is not enabled.
Definition at line 16 of file StencilBufferState.h.
References use(), and ~StencilBufferState().
StencilBufferState::~StencilBufferState ()
Destructor.
Disables GL_STENCIL_TEST if it had been enabled by an earlier use() call.
Definition at line 7 of file StencilBufferState.cc.
Referenced by StencilBufferState().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/StencilBufferState.h
/Users/howes/src/sidecar/GUI/StencilBufferState.cc