SideCar: SideCar::GUI::AScope::ChannelConnectionView Class Reference
SideCar::GUI::AScope::ChannelConnectionView Class Reference
View class for channel connections:
#include </Users/howes/src/sidecar/GUI/AScope/ChannelConnectionView.h>
Public Member Functions
ChannelConnectionView (QWidget *parent=0)
Constructor.
Static Public Member Functions
static Logger::Log & Log ()
Detailed Description
View class for channel connections:
QCheckBox indicating whether the channel data is visible
Text showing the name of the channel, italicized if the channel is not connected to a publisher.
Color swatch showing the display color of the channel. If the user double-clicks on the swatch, the view shows a QColorDialog box so that the user may change the color value.
Definition at line 21 of file ChannelConnectionView.h.
Constructor & Destructor Documentation
ChannelConnectionView::ChannelConnectionView (QWidget * parent = 0)
Constructor.
Sets up the view to respond to user clicks. Sets up the header.
Parameters
parent
Definition at line 47 of file ChannelConnectionView.cc.
References SideCar::GUI::AScope::ChannelConnection::getChannel(), SideCar::GUI::AScope::ChannelConnectionModel::getChannelConnection(), SideCar::GUI::AScope::ChannelConnection::isShowingPeakBars(), SideCar::GUI::AScope::ChannelConnection::isVisible(), LOGINFO, SideCar::GUI::AScope::ChannelConnectionModel::rowCount(), SideCar::GUI::AScope::ChannelConnectionModel::saveVideoChannelSettings(), SideCar::GUI::AScope::ChannelConnectionModel::setData(), and SideCar::GUI::AScope::ChannelConnection::setVisible().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/AScope/ChannelConnectionView.h
/Users/howes/src/sidecar/GUI/AScope/ChannelConnectionView.cc