SideCar: SideCar::IO::LineBufferStream Class Reference
SideCar::IO::LineBufferStream Class Reference
Derivation of std::istream that uses a LineBuffer for input buffering.
#include </Users/howes/src/sidecar/IO/LineBuffer.h>
Public Types
using traits_type = std::istream::traits_type
Public Member Functions
LineBufferStream (std::streambuf *buf)
Constructor.
virtual ~LineBufferStream ()
Destructor.
int getLineNumber () const
Obtain the current line number of the input buffer.
const LineBuffer::BufferType & getBuffer () const
Obtain the contents of the input line buffer.
void printContext (std::ostream &os) const
Write out the line number and buffer contents to the given stream in the format "Line: <LINE> '<BUFFER>'".
std::ostream & print (std::ostream &os) const
Write out line information to a C++ output stream.
Detailed Description
Derivation of std::istream that uses a LineBuffer for input buffering.
Provides simple error-reporting mechanism that throws a LineBufferStream::InputFailure exception, showing an error message and the line in the input buffer present when the error was raised.
Definition at line 96 of file LineBuffer.h.
Constructor & Destructor Documentation
SideCar::IO::LineBufferStream::LineBufferStream (std::streambuf * buf) inline
Constructor.
Creates a LineBuffer object wrapper for the given streambuf object.
Definition at line 103 of file LineBuffer.h.
virtual SideCar::IO::LineBufferStream::~LineBufferStream () inline virtual
Destructor.
Disposes of LineBuffer object.
Definition at line 107 of file LineBuffer.h.
Member Function Documentation
const LineBuffer::BufferType& SideCar::IO::LineBufferStream::getBuffer () const inline
Obtain the contents of the input line buffer.
Returns
copy of buffer
Definition at line 119 of file LineBuffer.h.
int SideCar::IO::LineBufferStream::getLineNumber () const inline
Obtain the current line number of the input buffer.
Returns
line number
Definition at line 113 of file LineBuffer.h.
std::ostream& SideCar::IO::LineBufferStream::print (std::ostream & os) const inline
Write out line information to a C++ output stream.
Parameters
os stream to write to
Returns
stream written to
Definition at line 134 of file LineBuffer.h.
References SideCar::IO::LineBuffer::getLineNumber().
Referenced by SideCar::IO::operator<<(), and SideCar::IO::LineBufferFile::print().
void LineBufferStream::printContext (std::ostream & os) const
Write out the line number and buffer contents to the given stream in the format "Line: <LINE> '<BUFFER>'".
Parameters
os stream to write to
Definition at line 83 of file LineBuffer.cc.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/LineBuffer.h
/Users/howes/src/sidecar/IO/LineBuffer.cc