SideCar: SideCar::IO::LineBuffer Class Reference
SideCar::IO::LineBuffer Class Reference
Specialization of std::streambuf that reads whole lines of text, counting the number of lines read in.
#include </Users/howes/src/sidecar/IO/LineBuffer.h>
Public Types
using BufferType = std::vector< char >
Public Member Functions
LineBuffer (std::streambuf *src)
Constructor.
~LineBuffer ()
Destructor.
int getLineNumber () const
Obtain the current line number.
const BufferType & getBuffer () const
Obtain the contents of the input line buffer.
Protected Member Functions
virtual std::streambuf * setbuf (char *ptr, std::streamsize len)
Override of streambuf method.
int overflow (int)
Override of streambuf method.
int underflow ()
Override of streambuf method.
Detailed Description
Specialization of std::streambuf that reads whole lines of text, counting the number of lines read in.
Useful to use as the buffer for an input stream so that when an error is encountered during processing, some reference where the error occured can be given in an exception.
Overrides setbuf(), overflow(), and underflow() to maintain the line count.
Definition at line 24 of file LineBuffer.h.
Constructor & Destructor Documentation
LineBuffer::LineBuffer (std::streambuf * src) explicit
Constructor.
Parameters
src streambuf instance to use for raw data
own indicates whether this instance owns the src pointer
Definition at line 11 of file LineBuffer.cc.
Referenced by overflow().
LineBuffer::~LineBuffer ()
Destructor.
Zaps the parent buffer pointers to help catch any misuse of a destructed LineBufffer object.
Definition at line 17 of file LineBuffer.cc.
Member Function Documentation
const BufferType& SideCar::IO::LineBuffer::getBuffer () const inline
Obtain the contents of the input line buffer.
Returns
reference to buffer
Definition at line 51 of file LineBuffer.h.
int SideCar::IO::LineBuffer::getLineNumber () const inline
Obtain the current line number.
Returns
line number
Definition at line 45 of file LineBuffer.h.
Referenced by SideCar::IO::LineBufferStream::print().
int SideCar::IO::LineBuffer::overflow (int) inline protected
Override of streambuf method.
We don't support `put' operations, so we simply return EOF.
Returns
EOF
Definition at line 69 of file LineBuffer.h.
References LineBuffer(), and underflow().
virtual std::streambuf* SideCar::IO::LineBuffer::setbuf (char * ptr, std::streamsize len) inline protected virtual
Override of streambuf method.
Forward call to the active streambuf object.
Parameters
ptr character buffer to use
len size of buffer
Returns
reference to self as a std::streambuf
Definition at line 63 of file LineBuffer.h.
int LineBuffer::underflow () protected
Override of streambuf method.
Keep track of line numbers as characters are added to the internal buffer.
Returns
next character found in buffer, or EOF if end-of-file
Definition at line 23 of file LineBuffer.cc.
Referenced by overflow().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/LineBuffer.h
/Users/howes/src/sidecar/IO/LineBuffer.cc