SideCar: SideCar::IO::StatusEmitterBase Class Reference
SideCar::IO::StatusEmitterBase Class Reference abstract
Abstract base class for status emitters.
#include </Users/howes/src/sidecar/IO/StatusEmitterBase.h>
Data Structures
struct Emitter
Internal class used by StatusEmitterBase to do most of the work.
Public Types
using Ref = boost::shared_ptr< StatusEmitterBase >
Public Member Functions
StatusEmitterBase (const char *emitterType, const char *collectorType, double updateRate)
Constructor.
virtual ~StatusEmitterBase ()
Destructor.
bool open (long threadFlags=THR_NEW_LWP|THR_JOINABLE|THR_INHERIT_SCHED, long priority=ACE_DEFAULT_THREAD_PRIORITY)
Open a datagram socket and publish connection information.
void close ()
Close the datagram socket and shutdown Zeroconf publisher.
void setUpdateRate (double updateRate)
Change the update rate for the emitter.
double getUpdateRate () const
Obtain the current update rate of the emitter.
void emitStatus ()
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device used by StatusEmitter objects.
Protected Member Functions
virtual void fillStatus (XmlRpc::XmlRpcValue &status)=0
Fill in an XML-RPC struct value with name/value pairs that describe the current status of the Algorithm we represent.
Detailed Description
Abstract base class for status emitters.
Periodically emits an XML status message to one or more "status watcher" objects (see GUI::StatusCollector for an example). Derived classes must define a fillStatus() method.
At first, a StatusEmitter does not emit any status information. Rather, it waits for the appearance of one or more status collector services with a particular Zeroconfig service type, at which point the emitter starts a timer that will cause it to emit periodic status updates. Whenever there are no active status collectors, the emitter will stop its update time and thus stop broadcasting status information.
Status is contained in an XML-RPC struct structure, which consists of a set of name/value pairs. The fillStatus() method adds the name/value pairs to an existing XML-RPC struct value. This result is what the Emitter helper class uses when it emits status information to registered listeners.
Definition at line 28 of file StatusEmitterBase.h.
Constructor & Destructor Documentation
StatusEmitterBase::StatusEmitterBase (const char * emitterType, const char * collectorType, double updateRate)
Constructor.
Parameters
name of the Zeroconf service to publish
\param updateRate the number of seconds between status emissions.
Definition at line 475 of file StatusEmitterBase.cc.
StatusEmitterBase::~StatusEmitterBase () virtual
Destructor.
Shutdown any active Emitter object
Definition at line 482 of file StatusEmitterBase.cc.
References close().
Member Function Documentation
virtual void SideCar::IO::StatusEmitterBase::fillStatus (XmlRpc::XmlRpcValue & status) protected pure virtual
Fill in an XML-RPC struct value with name/value pairs that describe the current status of the Algorithm we represent.
Derived classes should override this method to provide their own status.
Parameters
status the XML-RPC value to update
double SideCar::IO::StatusEmitterBase::getUpdateRate () const inline
Obtain the current update rate of the emitter.
Returns
update rate
Definition at line 73 of file StatusEmitterBase.h.
Logger::Log & StatusEmitterBase::Log () static
Obtain the log device used by StatusEmitter objects.
Returns
log device
Definition at line 91 of file StatusEmitterBase.cc.
References Logger::Log::Find(), SideCar::Zeroconf::ResolvedEntry::getFullName(), SideCar::Zeroconf::ResolvedEntry::getHost(), SideCar::Zeroconf::ResolvedEntry::getPort(), LOGDEBUG, LOGERROR, LOGFATAL, LOGINFO, LOGWARNING, SideCar::Zeroconf::Browser::Make(), SideCar::Zeroconf::ACEMonitorFactory::Make(), and XmlRpc::XmlRpcValue::toXml().
bool StatusEmitterBase::open (long threadFlags = THR_NEW_LWP | THR_JOINABLE | THR_INHERIT_SCHED, long priority = ACE_DEFAULT_THREAD_PRIORITY)
Open a datagram socket and publish connection information.
Returns
true if successful
Definition at line 488 of file StatusEmitterBase.cc.
void StatusEmitterBase::setUpdateRate (double updateRate)
Change the update rate for the emitter.
Parameters
updateRate new update rate in seconds
Definition at line 504 of file StatusEmitterBase.cc.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/StatusEmitterBase.h
/Users/howes/src/sidecar/IO/StatusEmitterBase.cc