SideCar: SideCar::Messages::XmlStreamReader Class Reference
SideCar::Messages::XmlStreamReader Class Reference
Variant of Qt QXmlStreamReader class that encapsulates some common SideCar uses.
#include </Users/howes/src/sidecar/Messages/XmlStreamReader.h>
Public Member Functions
XmlStreamReader (QIODevice *device)
Constructor.
QString getAttribute (const QString &name) const
Obtain the attribute value for the current entity with a given name.
bool readNextEntityAndValidate (const QString &expected)
Read the stream until the next entity start.
QStringList getSamples ()
Obtain a list of sample values from the current entity.
Detailed Description
Variant of Qt QXmlStreamReader class that encapsulates some common SideCar uses.
Also solves a linking problem on MacOS X due to some crufty symbol renaming going on by Trolltech/Nokia (I don't think they'll be doing THAT again, given all of the complaints this caused...)
Definition at line 18 of file XmlStreamReader.h.
Constructor & Destructor Documentation
XmlStreamReader::XmlStreamReader (QIODevice * device)
Constructor.
Initializes instance, taking data from the given QIODevice object.
Parameters
file the source of the data
Definition at line 7 of file XmlStreamReader.cc.
Member Function Documentation
QString XmlStreamReader::getAttribute (const QString & name) const
Obtain the attribute value for the current entity with a given name.
Parameters
name the name of the attribute to look for
Returns
value found. NOTE: QString::isNull() will return true if the attribute did not exist, while QString::isEmpty() will return true if the attribute was set with an empty value ("").
Definition at line 14 of file XmlStreamReader.cc.
Referenced by SideCar::Messages::Extraction::Extraction(), SideCar::Messages::Track::loadXML(), SideCar::Messages::Header::loadXML(), SideCar::Messages::TSPI::loadXML(), SideCar::Messages::PRIMessage::RIUInfo::print(), and SideCar::Messages::BugPlot::printDataXML().
QStringList XmlStreamReader::getSamples ()
Obtain a list of sample values from the current entity.
Returns
QStringList
Definition at line 29 of file XmlStreamReader.cc.
Referenced by SideCar::Messages::PRIMessage::loadXML().
bool XmlStreamReader::readNextEntityAndValidate (const QString & expected)
Read the stream until the next entity start.
Parameters
expected the name of the entity to expect
Returns
true if the expected entity was found; false otherwise
Definition at line 20 of file XmlStreamReader.cc.
Referenced by SideCar::Messages::PRIMessage::loadXML(), SideCar::Messages::Track::loadXML(), SideCar::Messages::TSPI::loadXML(), SideCar::Messages::BugPlot::printDataXML(), and SideCar::Messages::Extractions::printDataXML().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Messages/XmlStreamReader.h
/Users/howes/src/sidecar/Messages/XmlStreamReader.cc