SideCar: SideCar::Messages::TDecimator< _M > Class Template Reference
SideCar::Messages::TDecimator< _M > Class Template Reference
Template class that can generate iterators for a TPRIMessage class that return every N item.
#include </Users/howes/src/sidecar/Messages/Decimator.h>
Data Structures
class const_iterator
Internal class that defines a constant iterator for the decimated sequence.
Public Types
using Self = TDecimator< _M >
using Ref = boost::shared_ptr< Self >
using DatumType = typename _M::DatumType
using SourceConstIterator = typename _M::const_iterator
using SourceRef = typename _M::Ref
Public Types inherited from SideCar::Messages::Header
using Ref = boost::shared_ptr< Header >
Public Member Functions
size_t getMessageSize () const
size_t size () const
Obtain the number of elements in the decimated sequence.
bool empty () const
Determine if the decimated sequence is empty.
const_iterator begin () const
Obtain a read-only iterator to the first element in the decimated sequence.
const_iterator end () const
Obtain a read-only iterator to the termination point of the decimated sequence.
ACE_InputCDR & load (ACE_InputCDR &cdr)
Implementation of the Base abstact method.
ACE_OutputCDR & write (ACE_OutputCDR &cdr) const
Implementation of the Base abstact method.
std::ostream & print (std::ostream &os) const
Write out the entire message to a C++ text output stream.
Public Member Functions inherited from SideCar::Messages::Header
Header (const MetaTypeInfo &metaTypeInfo)
Constructor for messages read in from an external device.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis, MetaTypeInfo::SequenceType sequenceNumber)
Constructor for new messages.
virtual ~Header ()
Destructor.
const MetaTypeInfo & getMetaTypeInfo () const
Obtain the type specification for the message.
const GUID & getGloballyUniqueID () const
Get the globally-unique ID of the message.
MetaTypeInfo::SequenceType getMessageSequenceNumber () const
Get the message sequence number for the message.
void setMessageSequenceNumber (MetaTypeInfo::SequenceType msn)
Set the sequence number for this message.
const Time::TimeStamp & getCreatedTimeStamp () const
Obtain when the message was created.
Time::TimeStamp setCreatedTimeStamp (const Time::TimeStamp &timeStamp)
Revise the creation message timestamp.
const Time::TimeStamp & getEmittedTimeStamp () const
Obtain when the message was written to an external device (file or network).
Time::TimeStamp setEmittedTimeStamp (const Time::TimeStamp &timeStamp)
Set the emitted time stamp with the given value.
virtual size_t getSize () const
Obtain the C++ structure size for this object.
HeaderPrinter headerPrinter () const
Convenience method that simply returns a new HeaderPrinter functor for this header object.
DataPrinter dataPrinter () const
Convenience method that simply returns a new DataPrinter functor for this header object.
XMLPrinter xmlPrinter () const
Convenience method that simply returns a new XMLPrinter functor for this header object.
virtual std::ostream & printHeader (std::ostream &os) const
Write out the message header to a C++ text output stream.
virtual std::ostream & printData (std::ostream &os) const
Write out the message data to a C++ text output stream.
virtual std::ostream & printXML (std::ostream &os) const
Write out the message to a C++ text output stream in XML format.
virtual std::ostream & printDataXML (std::ostream &os) const
Write out the message data to a C++ text output stream in XML format.
bool hasBasis () const
Determine if the message has a basis message attached to it.
Ref getBasis () const
Obtain a reference to the message that this one was based on.
template<typename T >
T::Ref getBasis () const
Templated version of the above method.
Static Public Member Functions
static Ref Make (const SourceRef &source, int factor)
Create a new decimator.
Static Public Member Functions inherited from SideCar::Messages::Header
static Logger::Log & Log ()
Obtain log device to use for objects of this class.
static const MetaTypeInfo * GetMessageMetaTypeInfo (ACE_InputCDR &cdr)
Additional Inherited Members
Protected Member Functions inherited from SideCar::Messages::Header
virtual void loadXML (XmlStreamReader &xsr)
Obtain new instance data from an XML input stream.
Detailed Description
template<typename _M>
class SideCar::Messages::TDecimator< _M >
Template class that can generate iterators for a TPRIMessage class that return every N item.
The template parameter _M should be a class derived or instantiate from TPRIMessage.
Definition at line 17 of file Decimator.h.
Member Function Documentation
template<typename _M > const_iterator SideCar::Messages::TDecimator< _M >::begin () const inline
Obtain a read-only iterator to the first element in the decimated sequence.
Returns
read-only iterator
Definition at line 90 of file Decimator.h.
Referenced by SideCar::Messages::TDecimator< _M >::write().
template<typename _M > bool SideCar::Messages::TDecimator< _M >::empty () const inline
Determine if the decimated sequence is empty.
Returns
Definition at line 53 of file Decimator.h.
template<typename _M > const_iterator SideCar::Messages::TDecimator< _M >::end () const inline
Obtain a read-only iterator to the termination point of the decimated sequence.
NOTE: I think this violates the C++ standard...
Returns
Definition at line 97 of file Decimator.h.
References SideCar::Messages::TDecimator< _M >::size().
Referenced by SideCar::Messages::TDecimator< _M >::write().
template<typename _M > ACE_InputCDR& SideCar::Messages::TDecimator< _M >::load (ACE_InputCDR & cdr) inline virtual
Implementation of the Base abstact method.
Forwards the load to the underlying container. NOTE: this should normally NOT be used.
Parameters
cdr
Returns
Reimplemented from SideCar::Messages::Header.
Definition at line 107 of file Decimator.h.
template<typename _M > static Ref SideCar::Messages::TDecimator< _M >::Make (const SourceRef & source, int factor) inline static
Create a new decimator.
Parameters
source
factor
Returns
Definition at line 34 of file Decimator.h.
References SideCar::Messages::TDecimator< _M >::size().
template<typename _M > std::ostream& SideCar::Messages::TDecimator< _M >::print (std::ostream & os) const inline virtual
Write out the entire message to a C++ text output stream.
Parameters
os stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Definition at line 124 of file Decimator.h.
References SideCar::Messages::Header::Header().
template<typename _M > size_t SideCar::Messages::TDecimator< _M >::size () const inline
Obtain the number of elements in the decimated sequence.
Returns
size
Definition at line 47 of file Decimator.h.
Referenced by SideCar::Messages::TDecimator< _M >::end(), SideCar::Messages::TDecimator< _M >::Make(), and SideCar::Messages::TDecimator< _M >::write().
template<typename _M > ACE_OutputCDR& SideCar::Messages::TDecimator< _M >::write (ACE_OutputCDR & cdr) const inline virtual
Implementation of the Base abstact method.
Write out the decimated sequence to a CDR output stream.
Parameters
cdr stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Definition at line 115 of file Decimator.h.
References SideCar::Messages::TDecimator< _M >::begin(), SideCar::Messages::TDecimator< _M >::end(), and SideCar::Messages::TDecimator< _M >::size().
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/Messages/Decimator.h