SideCar: SideCar::GUI::Master::ServicesView Class Reference
SideCar::GUI::Master::ServicesView Class Reference
Visual representation of the status information received by Runner objects.
#include </Users/howes/src/sidecar/GUI/Master/ServicesView.h>
Public Member Functions
ServicesView (QWidget *parent=0)
Constructor.
void setModel (QAbstractItemModel *model)
Override of QTreeView method.
void setConfigurationVisibleFilter (const QStringList &known, const QStringList &visible, const QString &filter)
void setExpanded (const QModelIndex &index, bool expanded)
Static Public Member Functions
static Logger::Log & Log ()
Protected Slots
void rowsInserted (const QModelIndex &parent, int start, int end)
Override of QTreeView method.
Detailed Description
Visual representation of the status information received by Runner objects.
A Runner object hosts one or more processing streams (IO::Stream class) which contain IO::Task-based objects that do the actual data processing. Some of the IO::Task objects are Algorithms::Controller objects that manage an Algorithms::Algorithm object performs some work on the data. At present, there is at most one runner process per host.
The Runner object contains an XML-RPC server (wrapped in a RemoteController object) and a StatusEmitter object that periodically sends out status information to active processes running a GUI::StatusCollector. The status sent out contains entries for all of the Runner's IO::Stream objects, and their IO::Task/Algorithms::Controller objects. This information is held by the GUI::ServicesModel object that provides data to this view.
The tree view shows information in a nested fashion, with contained entries indented under their parents. Entries with children may be expanded or collapsed by the user – a collapsed entry hides its children and children's children.
Entries in the view that correspond to Algorithms::Controller objects have a QPushButton widget in the name column, which when pushed, allows the user to change runtime parameter settings of the algorithm.
Definition at line 42 of file ServicesView.h.
Constructor & Destructor Documentation
ServicesView::ServicesView (QWidget * parent = 0)
Constructor.
Creates a context menu that allows for expansion / collapsing of all nodes, and the showing / hiding of specific columns.
Parameters
parent owner of this view (for automatic destruction)
Definition at line 60 of file ServicesView.cc.
Member Function Documentation
void ServicesView::rowsInserted (const QModelIndex & parent, int start, int end) protected slot
Override of QTreeView method.
Notification from the model that one or more rows have been inserted into the model. Expands all expandable entries, and adds a QPushButton widget to entries that correspond to Algorithms::Controller objects.
Parameters
parent index of the containing node
start row within the parent of the first inserted value
end row within the parent of the last inserted value
Definition at line 250 of file ServicesView.cc.
References SideCar::GUI::Master::RunnerItem::executeRequest(), SideCar::GUI::Master::RunnerLog::Find(), SideCar::GUI::Master::RunnerItem::getConfigName(), SideCar::GUI::Master::TreeViewItem::getFullName(), SideCar::GUI::Master::TreeViewItem::getName(), SideCar::GUI::Master::RunnerItem::getServiceName(), SideCar::GUI::Master::TreeViewItem::isFiltered(), LOGDEBUG, LOGINFO, SideCar::GUI::Master::TreeViewItem::setExpanded(), and SideCar::GUI::Master::RunnerLog::showWindow().
void ServicesView::setModel (QAbstractItemModel * model)
Override of QTreeView method.
Install the data model for the view to use. NOTE: most actions on a view do nothing or are ignored by the Qt library until a model has been installed. Thus, some view setup happens in this method where it will have an effect.
Parameters
model
Definition at line 109 of file ServicesView.cc.
References SideCar::GUI::Master::TreeViewItem::canEdit(), SideCar::GUI::Master::TreeViewItem::canExpand(), SideCar::GUI::Master::TreeViewItem::getFullName(), SideCar::GUI::Master::TreeViewItem::getName(), LOGDEBUG, and LOGINFO.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/ServicesView.h
/Users/howes/src/sidecar/GUI/Master/ServicesView.cc