SideCar: SideCar::Configuration::RunnerConfig Class Reference
SideCar::Configuration::RunnerConfig Class Reference
Simple container class that holds attributes relating to a particular runner in a configuration file.
#include </Users/howes/src/sidecar/Configuration/RunnerConfig.h>
Data Structures
struct Init
Public Member Functions
RunnerConfig (const Loader &loader, const Init &init)
Constructor for a new RunnerConfig object.
const QString & getConfigurationName () const
Obtain the name of the configuration.
const QString & getRunnerName () const
Obtain the name of the runner in the configuration.
const QString & getHostName () const
Obtain the name of the host on which the runner will run.
const QString & getMulticastAddress () const
Obtain the multicast address to use for multicast emissions.
const QString & getServiceName () const
Obtain the service name for the runner.
const QString & getScheduler () const
Obtain the requested scheduler for the runner.
const QString & getPriority () const
Obtain the requested priority for the runner.
const QString & getCpuAffinity () const
Obtain the requested cpu affinity for the runner.
const QString & getInitialProcessingState () const
const QString & getLogPath () const
Obtain the location of the log file for the runner process.
const QString & getRemoteCommand () const
Obtain the command to execute that will run the runner process on the configured remote host.
const QList< QDomElement > & getStreamNodes () const
Obtain a list of XML nodes that define the streams in the runner process.
void setServiceName (const QString &serviceName)
Update the service name due to a name conflict with something else running in the local LAN.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for RunnerConfig objects.
Detailed Description
Simple container class that holds attributes relating to a particular runner in a configuration file.
Definition at line 18 of file RunnerConfig.h.
Constructor & Destructor Documentation
RunnerConfig::RunnerConfig (const Loader & loader, const Init & init)
Constructor for a new RunnerConfig object.
Parameters
configurationName name of the configuration we belong to
configurationPath path of the configuration file we belong to
runnerName the name of the runner process being configured
hostName name of the host that is running the runner process
multicastAddress address to use for all multicast emissions
logsDirectory location where log files will be deposited
streams
Definition at line 19 of file RunnerConfig.cc.
References SideCar::Configuration::Loader::getConfigurationPath(), SideCar::Configuration::Loader::getLogsDirectory(), Log(), LOGDEBUG, and LOGINFO.
Member Function Documentation
const QString& SideCar::Configuration::RunnerConfig::getConfigurationName () const inline
Obtain the name of the configuration.
Returns
configuration name
Definition at line 67 of file RunnerConfig.h.
Referenced by SideCar::GUI::Master::LogViewWindowManager::addLogInfo().
const QString& SideCar::Configuration::RunnerConfig::getCpuAffinity () const inline
Obtain the requested cpu affinity for the runner.
Returns
cpuaffinity
Definition at line 111 of file RunnerConfig.h.
const QString& SideCar::Configuration::RunnerConfig::getHostName () const inline
Obtain the name of the host on which the runner will run.
Returns
host name
Definition at line 79 of file RunnerConfig.h.
Referenced by SideCar::GUI::Master::ConfigurationInfo::lostRunner(), SideCar::GUI::Master::Launcher::start(), and SideCar::GUI::Master::ConfigurationInfo::startup().
const QString& SideCar::Configuration::RunnerConfig::getLogPath () const inline
Obtain the location of the log file for the runner process.
Returns
log file path
Definition at line 119 of file RunnerConfig.h.
const QString& SideCar::Configuration::RunnerConfig::getMulticastAddress () const inline
Obtain the multicast address to use for multicast emissions.
Returns
multicast address in dot notation
Definition at line 85 of file RunnerConfig.h.
const QString& SideCar::Configuration::RunnerConfig::getPriority () const inline
Obtain the requested priority for the runner.
Returns
priority
Definition at line 105 of file RunnerConfig.h.
const QString& SideCar::Configuration::RunnerConfig::getRemoteCommand () const inline
Obtain the command to execute that will run the runner process on the configured remote host.
Returns
command line string
Definition at line 125 of file RunnerConfig.h.
Referenced by SideCar::GUI::Master::Launcher::start().
const QString& SideCar::Configuration::RunnerConfig::getRunnerName () const inline
Obtain the name of the runner in the configuration.
Returns
runner name
Definition at line 73 of file RunnerConfig.h.
Referenced by SideCar::GUI::Master::LogViewWindowManager::addLogInfo(), SideCar::GUI::Master::ConfigurationInfo::lostRunner(), SideCar::GUI::Master::Launcher::start(), and SideCar::GUI::Master::ConfigurationInfo::startup().
const QString& SideCar::Configuration::RunnerConfig::getScheduler () const inline
Obtain the requested scheduler for the runner.
This can be one of : SCHED_INHERIT, SCHED_OTHER, SCHED_FIFO, SCHED_RR
\return thread flags
Definition at line 99 of file RunnerConfig.h.
const QString& SideCar::Configuration::RunnerConfig::getServiceName () const inline
Obtain the service name for the runner.
This is a combination of the configuration name, host name, and runner name, separated by a ':' character.
Returns
service name
Definition at line 92 of file RunnerConfig.h.
Referenced by SideCar::GUI::Master::LogViewWindowManager::addLogInfo(), SideCar::GUI::Master::ConfigurationInfo::foundRunner(), and SideCar::GUI::Master::ConfigurationInfo::lostRunner().
const QList<QDomElement>& SideCar::Configuration::RunnerConfig::getStreamNodes () const inline
Obtain a list of XML nodes that define the streams in the runner process.
Returns
QList of XML nodes
Definition at line 131 of file RunnerConfig.h.
Logger::Log & RunnerConfig::Log () static
Obtain the log device for RunnerConfig objects.
Returns
Logger::Log reference
Definition at line 13 of file RunnerConfig.cc.
References Logger::Log::Find().
Referenced by RunnerConfig(), and setServiceName().
void RunnerConfig::setServiceName (const QString & serviceName)
Update the service name due to a name conflict with something else running in the local LAN.
Parameters
serviceName new name to use for the service
Definition at line 54 of file RunnerConfig.cc.
References Log(), LOGDEBUG, and LOGWARNING.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Configuration/RunnerConfig.h
/Users/howes/src/sidecar/Configuration/RunnerConfig.cc