SideCar: SideCar::GUI::PPIDisplay::ViewSettings Class Reference
SideCar::GUI::PPIDisplay::ViewSettings Class Reference
Collection of settings that relate the the view shown in a PPIWidget.
#include </Users/howes/src/sidecar/GUI/PPIDisplay/ViewSettings.h>
Public Slots
void setRangeFactorAndMax (double rangeFactor, double rangeMaxMax)
Register new range factor/max values.
void shift (double x, double y)
Shift the horizontal and/or vertical offsets of the radar center.
void moveTo (double x, double y)
Set the horizontal and vertical offset of the radar center.
void reset ()
Signals
void rangeMaxMaxChanged (double value)
Notificationn sent out when the maximum range value changes.
void rangeMaxChanged (double value)
Notification sent out when the maximum visible range setting changs.
Signals inherited from SideCar::GUI::SettingsBlock
void settingChanged ()
Notification sent out when a registered value has changed.
Public Member Functions
ViewSettings (DoubleSetting *rangeMaxMax, DoubleSetting *rangeMax, DoubleSetting *x, DoubleSetting *y, IntSetting *zoomPower, DoubleSetting *zoomFactor)
Constructor.
double getRangeFactor () const
Obtain the last rangeFactor value given in a setRangeFactorAndMax() call.
double getRangeMaxMax () const
Obtain the last max range value given in a setRangeFactorAndMax() call.
double getRangeMax () const
Obtain the current maximum visible range value.
float getX () const
Obtain the current horizontal offset for the radar's center.
float getY () const
Obtain the current vertical offset for the radar's center.
int getZoomPower () const
Obtain the current view zoom power setting.
void setZoomPower (int value)
Change the current view zoom power setting.
double getZoom () const
Obtain the current magnification for the view.
double getZoom (int power) const
Public Member Functions inherited from SideCar::GUI::SettingsBlock
SettingsBlock (QObject *parent=0)
Constructor.
Static Public Member Functions
static Logger::Log & Log ()
Obtain Log device for ViewSetting objects.
Additional Inherited Members
Protected Slots inherited from SideCar::GUI::SettingsBlock
virtual void postSettingChanged ()
Notification handler invoked when a Setting object that was registered with one of the add() methods emits its valueChanged() signal.
virtual void emitSettingChanged ()
Notification handler invoked when the QTimer object registered by the postSettingChanged() method fires.
Protected Member Functions inherited from SideCar::GUI::SettingsBlock
void add (Setting *setting)
Relate a Setting object to this SettingsBlock object.
Detailed Description
Collection of settings that relate the the view shown in a PPIWidget.
Specifically, a view has horizontal and vertical offset for the radar's center, where zero offsets place the radar in the center of the screen; a zoom factor that magnifies the data; and a maximum visible range value that limits the samples used for the display.
Definition at line 18 of file ViewSettings.h.
Constructor & Destructor Documentation
ViewSettings::ViewSettings (DoubleSetting * rangeMaxMax, DoubleSetting * rangeMax, DoubleSetting * x, DoubleSetting * y, IntSetting * zoomPower, DoubleSetting * zoomFactor)
Constructor.
Parameters
rangeMaxMax
rangeMax
x
y
zoomPower
zoomFactor
Definition at line 16 of file ViewSettings.cc.
References SideCar::GUI::SettingsBlock::add(), rangeMaxChanged(), and rangeMaxMaxChanged().
Member Function Documentation
double SideCar::GUI::PPIDisplay::ViewSettings::getRangeFactor () const inline
Obtain the last rangeFactor value given in a setRangeFactorAndMax() call.
Returns
range factor
Definition at line 52 of file ViewSettings.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::processVideo().
double SideCar::GUI::PPIDisplay::ViewSettings::getRangeMax () const inline
Obtain the current maximum visible range value.
This value should always be less than or equal to getRangeMax().
Returns
maximum visible range
Definition at line 65 of file ViewSettings.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::initializeContext(), SideCar::GUI::PPIDisplay::PPIWidget::renderScene(), and SideCar::GUI::PPIDisplay::PPIWidget::~PPIWidget().
double SideCar::GUI::PPIDisplay::ViewSettings::getRangeMaxMax () const inline
Obtain the last max range value given in a setRangeFactorAndMax() call.
Returns
range max
Definition at line 58 of file ViewSettings.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::initializeContext().
float SideCar::GUI::PPIDisplay::ViewSettings::getX () const inline
Obtain the current horizontal offset for the radar's center.
Returns
horizontal offset value
Definition at line 71 of file ViewSettings.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::renderScene().
float SideCar::GUI::PPIDisplay::ViewSettings::getY () const inline
Obtain the current vertical offset for the radar's center.
Returns
vertical offset value
Definition at line 77 of file ViewSettings.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::renderScene().
double SideCar::GUI::PPIDisplay::ViewSettings::getZoom () const inline
Obtain the current magnification for the view.
Returns
magnification factor.
Definition at line 95 of file ViewSettings.h.
Referenced by moveTo(), and SideCar::GUI::PPIDisplay::PPIWidget::renderScene().
double ViewSettings::getZoom (int power) const
Parameters
power
Returns
Definition at line 89 of file ViewSettings.cc.
References SideCar::GUI::DoubleSetting::getValue().
int SideCar::GUI::PPIDisplay::ViewSettings::getZoomPower () const inline
Obtain the current view zoom power setting.
Returns
zoom power
Definition at line 83 of file ViewSettings.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::changeZoom().
Logger::Log & ViewSettings::Log () static
Obtain Log device for ViewSetting objects.
Returns
Log device
Definition at line 10 of file ViewSettings.cc.
References Logger::Log::Find().
Referenced by moveTo(), and setZoomPower().
void ViewSettings::moveTo (double x, double y) slot
Set the horizontal and vertical offset of the radar center.
Parameters
x horizontal offset to use
y vertical offset to use
Definition at line 41 of file ViewSettings.cc.
References SideCar::GUI::IntSetting::getValue(), SideCar::GUI::DoubleSetting::getValue(), getZoom(), Log(), LOGINFO, SideCar::GUI::SettingsBlock::postSettingChanged(), and SideCar::GUI::DoubleSetting::setValue().
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::centerAtCursor().
void SideCar::GUI::PPIDisplay::ViewSettings::rangeMaxChanged (double value) signal
Notification sent out when the maximum visible range setting changs.
Parameters
value new value
Referenced by ViewSettings().
void SideCar::GUI::PPIDisplay::ViewSettings::rangeMaxMaxChanged (double value) signal
Notificationn sent out when the maximum range value changes.
Parameters
value new value
Referenced by ViewSettings().
void ViewSettings::setRangeFactorAndMax (double rangeFactor, double rangeMaxMax) slot
Register new range factor/max values.
This should only be done when there is an appreciable difference between the given rangeFactor and the value of getRangeFactor(), since the rangeMax values may vary by one or more gate values due to timing accuracy. NOTE: this routine will change the internal rangeMax_ value if it is larger than then new max range value.
Parameters
rangeFactor new gate-to-gate range factor to record
rangeMaxMax new maximum range value to record
Definition at line 71 of file ViewSettings.cc.
References SideCar::GUI::IntSetting::setValue(), and SideCar::GUI::DoubleSetting::setValue().
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::processVideo().
void ViewSettings::setZoomPower (int value)
Change the current view zoom power setting.
Parameters
value new value
Definition at line 59 of file ViewSettings.cc.
References Log(), LOGINFO, and SideCar::GUI::IntSetting::setValue().
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::changeZoom().
void SideCar::GUI::PPIDisplay::ViewSettings::shift (double x, double y) inline slot
Shift the horizontal and/or vertical offsets of the radar center.
Parameters
x horizontal offset to add
y vertical offset to add
Definition at line 124 of file ViewSettings.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::changeZoom(), and SideCar::GUI::PPIDisplay::PPIWidget::pan().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/PPIDisplay/ViewSettings.h
/Users/howes/src/sidecar/GUI/PPIDisplay/ViewSettings.cc