SideCar: SideCar::GUI::MulticastMessageReader Class Reference
SideCar::GUI::MulticastMessageReader Class Reference
Derivation of MessageReader that obtains messages over a UDP multicast socket.
#include </Users/howes/src/sidecar/GUI/MulticastMessageReader.h>
Public Types
using ZeroconfPublisherRef = boost::shared_ptr< Zeroconf::Publisher >
Public Types inherited from SideCar::IO::ZeroconfRegistry
enum ID {
kPublisher = 0, kSubscriber, kRunnerStatusCollector, kRunnerStatusEmitter,
kStateEmitter, kStateCollector, kRunnerRemoteController, kNumTypes
}
Defined Zeroconf types.
Public Member Functions
~MulticastMessageReader ()
Destructor.
Public Member Functions inherited from SideCar::GUI::MessageReader
const Messages::MetaTypeInfo * getMetaTypeInfo () const
Obtain the meta type info for the messages being received.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for MulticastMessageReader objects.
static MulticastMessageReader * Make (const ServiceEntry *service)
Factory class method that creates new MulticastMessageReader objects.
Static Public Member Functions inherited from SideCar::GUI::MessageReader
static Logger::Log & Log ()
Obtain the log device for MessageReader objects.
static MessageReader * Make (const ServiceEntry *service)
Create a new MessageReader object using information from a publisher's ServiceEntry object.
static MessageReader * Make (const std::string &topic, const Messages::MetaTypeInfo *type)
Create a new MessageReader object using information from a publisher's ServiceEntry object.
Static Public Member Functions inherited from SideCar::IO::ZeroconfTypes::TZCType< id >
static const char * GetZeroconfType ()
Obtain the configured Zeroconf type for objects derived from this class.
static const char * GetTwinZeroconfType ()
Obtain the "twin" Zeroconf type for objects derived from this class.
static std::string MakeZeroconfType (const std::string &subType)
Construct a valid SideCar Zeroconf type string for a given subtype.
static std::string MakeTwinZeroconfType (const std::string &subType)
Construct the twin SideCar Zeroconf type string for a given subtype.
Static Public Member Functions inherited from SideCar::IO::ZeroconfRegistry
static const char * GetType (ID id)
Obtain the Zeroconf type string for a given ID.
static ID GetTwin (ID id)
Locate the twin of this ID.
static std::string MakeZeroconfType (const char *type, const std::string &subType)
Construct a valid SideCar Zeroconf type string for a type and a subtype.
Additional Inherited Members
Signals inherited from SideCar::GUI::MessageReader
void connected ()
Notification that the reader has connected to a publisher.
void received (const Messages::Header::Ref &msg)
Notification that a new message is available from a publisher.
void disconnected ()
Notification that the reader has disconnected from a publisher.
Protected Member Functions inherited from SideCar::GUI::MessageReader
MessageReader (const Messages::MetaTypeInfo *metaTypeInfo)
Constructor.
void addRawData (ACE_Message_Block *raw)
Add raw incoming message data to the active message queue.
Detailed Description
Derivation of MessageReader that obtains messages over a UDP multicast socket.
Use the Make() class method to create new instances, or even better use the MessageReader::Make() methods.
Creates a QUdpSocket to serve as a proxy for the real socket that was created, and set up by the IO::MulticastSocketReader class. When data is available to read from the socket, the socketReadyRead() method runs and puts complete datagrams into new ACE_Message_Block objects, which the method hands off to the MessageReader::addRawData() method to add to the active message list.
Definition at line 27 of file MulticastMessageReader.h.
Member Function Documentation
Logger::Log & MulticastMessageReader::Log () static
Obtain the log device for MulticastMessageReader objects.
Returns
log device
Definition at line 19 of file MulticastMessageReader.cc.
References Logger::Log::Find().
MulticastMessageReader * MulticastMessageReader::Make (const ServiceEntry * service) static
Factory class method that creates new MulticastMessageReader objects.
Parameters
type the message type for data coming in from the publisher
publisherName the name of the publisher sending the data
publisherHost the host where the publisher resides
publisherPort the port over which the publisher sends the data
Returns
new MulticastMessageReader object, or NULL if error
Definition at line 27 of file MulticastMessageReader.cc.
References SideCar::GUI::ServiceEntry::getMetaTypeInfo(), LOGERROR, and LOGINFO.
Referenced by SideCar::GUI::MessageReader::Make().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/MulticastMessageReader.h
/Users/howes/src/sidecar/GUI/MulticastMessageReader.cc