SideCar: SideCar::GUI::Master::RecordingInfo Class Reference
SideCar::GUI::Master::RecordingInfo Class Reference
Class that holds information about a particular recording.
#include </Users/howes/src/sidecar/GUI/Master/RecordingInfo.h>
Public Slots
void infoChanged ()
Signals
void configChanged ()
void statsChanged ()
Public Member Functions
RecordingInfo (RecordingController &controller, const QString &name, const QTime &duration)
Constructor.
RecordingInfo (RecordingController &controller, const QDir &recordingDir)
~RecordingInfo ()
Destructor.
void addConfiguration (const QString &configName)
void addRecordingDirectory (const QDir &recordingDir)
const QStringList & getConfigurationNames () const
Obtain the configuration names that make up the recording.
const QStringList & getRecordingDirectories () const
const QString & getName () const
QString getStartTime () const
QString getFormattedStartTime () const
const QString & getElapsedTime () const
QString getFormattedElapsedTime () const
const QString & getRemainingTime () const
bool isDone () const
Determine if this recording is finished.
void showNotesWindow ()
Show the NotesWindow window associated with this recording.
void closeNotesWindow ()
void start (const QStringList &changes)
void addChangedParameters (const QStringList &changes)
void addAlerts (const QStringList &alerts)
bool hasDurationPassed (const QString &now)
Determine if the set duration has passed for this recording.
void recordingStopped ()
bool wasRadarTransmitting () const
QString getRadarFreqency () const
bool wasRadarRotating () const
QString getRadarRotationRate () const
bool wasDRFMOn () const
QString getDRFMConfig () const
QString getBoolAsString (bool value) const
int getDropCount () const
int getDupeCount () const
void updateStats (int dropCount, int dupeCount)
Detailed Description
Class that holds information about a particular recording.
Each recording started by the RecordingController gets its own RecordingInfo object, which is shown in the RecordingsView table.
Definition at line 20 of file RecordingInfo.h.
Constructor & Destructor Documentation
RecordingInfo::RecordingInfo (RecordingController & controller, const QString & name, const QTime & duration)
Constructor.
Parameters
parent container hosting the widget
filter
duration
dir
Definition at line 16 of file RecordingInfo.cc.
References SideCar::GUI::MainWindowBase::initialize().
RecordingInfo::~RecordingInfo ()
Destructor.
Deletes the NotesWindow.
Definition at line 49 of file RecordingInfo.cc.
Member Function Documentation
const QStringList& SideCar::GUI::Master::RecordingInfo::getConfigurationNames () const inline
Obtain the configuration names that make up the recording.
Returns
QStringList reference
Definition at line 52 of file RecordingInfo.h.
Referenced by SideCar::GUI::Master::RecordingController::Log(), SideCar::GUI::Master::MainWindow::MainWindow(), and SideCar::GUI::Master::NotesWindow::NotesWindow().
bool RecordingInfo::hasDurationPassed (const QString & now)
Determine if the set duration has passed for this recording.
Returns
Definition at line 142 of file RecordingInfo.cc.
Referenced by isDone(), and SideCar::GUI::Master::RecordingController::Log().
bool SideCar::GUI::Master::RecordingInfo::isDone () const inline
Determine if this recording is finished.
Returns
true if so
Definition at line 78 of file RecordingInfo.h.
References hasDurationPassed(), and showNotesWindow().
Referenced by SideCar::GUI::Master::RecordingController::Log().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/RecordingInfo.h
/Users/howes/src/sidecar/GUI/Master/RecordingInfo.cc