SideCar: Utils::MD5 Class Reference
Utils::MD5 Class Reference
MD5 hash generator.
#include </Users/howes/src/sidecar/Utils/MD5.h>
Data Structures
struct Private
Private utility class that implements the RSA MD5 algorithm.
Public Types
enum { kDigestSize = 16, kBufferSize = 4 * kDigestSize }
using DigestType = uint8_t[kDigestSize]
Container type for all MD5 hashes: 16 byte array.
Public Member Functions
MD5 ()
Constructor.
~MD5 ()
Destructor.
void add (const std::string &buffer)
Add bytes from an STL string to the hash function.
void add (const std::vector< uint8_t > &buffer)
Add bytes from an STL vector to the hash function.
void add (const uint8_t *buffer, size_t count)
Add bytes from user-defined structure.
const DigestType & getDigest ()
Obtain the hash digest for the accumulated data.
Detailed Description
MD5 hash generator.
Accumulates data using its add() methods, and returns the hash of the accumulated data via its getDigest() method. NOTE: not to be used for cryptographic purposes.
Definition at line 13 of file MD5.h.
Constructor & Destructor Documentation
MD5::MD5 ()
Constructor.
Initialize generator constants
Definition at line 273 of file MD5.cc.
MD5::~MD5 ()
Destructor.
Releases private memory.
Definition at line 281 of file MD5.cc.
Member Function Documentation
void Utils::MD5::add (const std::string & buffer) inline
Add bytes from an STL string to the hash function.
Parameters
buffer the data to add
Definition at line 38 of file MD5.h.
References add().
Referenced by add().
void Utils::MD5::add (const std::vector< uint8_t > & buffer) inline
Add bytes from an STL vector to the hash function.
Parameters
buffer the data to add
Definition at line 44 of file MD5.h.
References add(), and getDigest().
Referenced by add().
void MD5::add (const uint8_t * buffer, size_t count)
Add bytes from user-defined structure.
Parameters
buffer pointer to the first byte to add
count the number of bytes to add
Definition at line 287 of file MD5.cc.
const MD5::DigestType & MD5::getDigest ()
Obtain the hash digest for the accumulated data.
Returns
read-only reference to a 16-byte array holding the digest values.
Definition at line 293 of file MD5.cc.
Referenced by add().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Utils/MD5.h
/Users/howes/src/sidecar/Utils/MD5.cc