SideCar: SideCar::IO::StreamReader Class Reference
SideCar::IO::StreamReader Class Reference abstract
Abstract base class for readers.
#include </Users/howes/src/sidecar/IO/Readers.h>
Public Member Functions
StreamReader (size_t bufferSize)
Constructor for new reader.
~StreamReader ()
Destructor.
bool fetchInput ()
Read in data from the device and append to the existing ACE_Message_Block.
void reset ()
Reset the stream by discarding any partially-read messages.
Public Member Functions inherited from SideCar::IO::Reader
Reader ()
Constructor for new reader.
virtual ~Reader ()
Destructor.
bool isMessageAvailable () const
Determine if a complete message is available for processing.
ACE_Message_Block * getMessage ()
Obtain the raw data block available from the reader.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device to use for log messages.
Static Public Member Functions inherited from SideCar::IO::Reader
static Logger::Log & Log ()
Obtain the log device to use for log messages.
Protected Member Functions
virtual ssize_t fetchFromDevice (void *addr, size_t size)=0
Prototype of method that fetches data from a device and places it into a specific location.
Protected Member Functions inherited from SideCar::IO::Reader
void setAvailable (ACE_Message_Block *available)
Make a complete message available for consumption.
Additional Inherited Members
Public Types inherited from SideCar::IO::Reader
using Ref = boost::shared_ptr< Reader >
Detailed Description
Abstract base class for readers.
A reader accumulates data from a device until it has all of the data of a complete message. All SideCar messages have a header (see SideCar::Messages::Header class) which contains a size in bytes. A reader simply adds incoming bytes to an ACE_Message_Block until the ACE_Message_Block::length() == Header::getSize().
Definition at line 288 of file Readers.h.
Constructor & Destructor Documentation
StreamReader::StreamReader (size_t bufferSize)
Constructor for new reader.
Parameters
bufferSize starting size for read buffer
Definition at line 54 of file Readers.cc.
References Log(), and LOGINFO.
Member Function Documentation
virtual ssize_t SideCar::IO::StreamReader::fetchFromDevice (void * addr, size_t size) protected pure virtual
Prototype of method that fetches data from a device and places it into a specific location.
Parameters
addr where to place fetched data
size how much data to fetch
Returns
number of bytes fetched if > 0; EOF if == 0; and error condition if < 0
Implemented in SideCar::IO::TReader< StreamReader, ReaderDevices::File >, SideCar::IO::TReader< IO::StreamReader, TCPSocketReaderDevice >, and SideCar::IO::TReader< StreamReader, ReaderDevices::TCPSocket >.
Referenced by fetchInput().
bool StreamReader::fetchInput () virtual
Read in data from the device and append to the existing ACE_Message_Block.
Returns
true if device is still valid, false otherwise
Implements SideCar::IO::Reader.
Definition at line 96 of file Readers.cc.
References fetchFromDevice(), SideCar::IO::Decoder::getMessageSize(), SideCar::IO::Preamble::kCDRStreamSize, SideCar::IO::Preamble::kMagicTag, Log(), LOGDEBUG, LOGERROR, SideCar::IO::MessageManager::MakeMessageBlock(), and SideCar::IO::Reader::setAvailable().
Referenced by SideCar::IO::TCPInputHandler::handle_input(), SideCar::GUI::Playback::Emitter::setEmitting(), SideCar::IO::FileReaderTask::svc(), and SideCar::GUI::Playback::Emitter::~Emitter().
Logger::Log & StreamReader::Log () static
Obtain the log device to use for log messages.
Returns
Definition at line 48 of file Readers.cc.
References Logger::Log::Find().
Referenced by fetchInput(), reset(), and StreamReader().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/Readers.h
/Users/howes/src/sidecar/IO/Readers.cc