SideCar: SideCar::GUI::AScope::HistoryBuffer Class Reference
SideCar::GUI::AScope::HistoryBuffer Class Reference
Container of HistoryFrame objects that represent snapshots of past data.
#include </Users/howes/src/sidecar/GUI/AScope/HistoryBuffer.h>
Public Member Functions
HistoryBuffer (int duration)
Constructor.
void setDuration (int duration)
Change the duration value.
void record (int bufferIndex, const Messages::PRIMessage::Ref &msg)
Add a new HistoryFrame to the buffer, and prune any old entries.
int size () const
Obtain the number of frames held in the buffer.
const HistoryFrame & getFrame (int index) const
Fetch the frame from the buffer at a given position.
void addMessageBuffer ()
void removeMessageBuffer (int index)
void clear ()
Static Public Member Functions
static Logger::Log & Log ()
Detailed Description
Container of HistoryFrame objects that represent snapshots of past data.
The size of the container is bounded by a duration parameter, which limits how old the oldest record in the buffer may be. Does not delete old frames, but rather places them on a free list. For near-constant data rates, this should allow the HistoryBuffer to reach a stable point where it no longer allocates new frames.
Definition at line 19 of file HistoryBuffer.h.
Constructor & Destructor Documentation
HistoryBuffer::HistoryBuffer (int duration)
Constructor.
Parameters
duration how old in seconds the oldest record may be before it is removed.
Definition at line 8 of file HistoryBuffer.cc.
References setDuration().
Member Function Documentation
const HistoryFrame & HistoryBuffer::getFrame (int index) const
Fetch the frame from the buffer at a given position.
Parameters
index position to fetch from
Returns
found frame
Definition at line 52 of file HistoryBuffer.cc.
References SideCar::GUI::AScope::HistoryFrame::clear(), and size().
void HistoryBuffer::record (int bufferIndex, const Messages::PRIMessage::Ref & msg)
Add a new HistoryFrame to the buffer, and prune any old entries.
Note: makes a copy of the given frame.
Parameters
current reference to new frame to add
Definition at line 21 of file HistoryBuffer.cc.
References size().
void HistoryBuffer::setDuration (int duration)
Change the duration value.
Parameters
duration new duration value in seconds
Definition at line 15 of file HistoryBuffer.cc.
Referenced by HistoryBuffer().
int SideCar::GUI::AScope::HistoryBuffer::size () const inline
Obtain the number of frames held in the buffer.
Note that since buffer size is determined by time, this value might not the same from call to call.
Returns
buffer size
Definition at line 49 of file HistoryBuffer.h.
Referenced by getFrame(), and record().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/AScope/HistoryBuffer.h
/Users/howes/src/sidecar/GUI/AScope/HistoryBuffer.cc