SideCar: SideCar::GUI::KeySeq Class Reference
SideCar::GUI::KeySeq Class Reference
A wrapper around QKeySequence that better handles conversions to a QString than that found in QKeySequence when run on OS X.
#include </Users/howes/src/sidecar/GUI/KeySeq.h>
Public Member Functions
KeySeq ()
Default constructor.
KeySeq (const QString &key)
Construct a key sequence from a string.
KeySeq (const QKeySequence &key)
Construct a key sequence from a defined QKeySequence.
KeySeq (const QKeyEvent *event)
Construct a key sequence from a key code found in a key event.
const QKeySequence & getKeySequence () const
Obtain the wrapped QKeySequence object.
bool matches (const KeySeq &event) const
Determine if the given key sequence from an event is the same as the key sequence we represent.
QString asString () const
Obtain a textual representation of the key sequence.
Detailed Description
A wrapper around QKeySequence that better handles conversions to a QString than that found in QKeySequence when run on OS X.
Definition at line 15 of file KeySeq.h.
Constructor & Destructor Documentation
KeySeq::KeySeq ()
Default constructor.
No defined key sequence.
Definition at line 9 of file KeySeq.cc.
KeySeq::KeySeq (const QString & key)
Construct a key sequence from a string.
Parameters
key textual representation of the key
Definition at line 15 of file KeySeq.cc.
KeySeq::KeySeq (const QKeySequence & key)
Construct a key sequence from a defined QKeySequence.
Parameters
key key sequence to copy
Definition at line 21 of file KeySeq.cc.
KeySeq::KeySeq (const QKeyEvent * event)
Construct a key sequence from a key code found in a key event.
Parameters
event event with the key code
Definition at line 27 of file KeySeq.cc.
Member Function Documentation
QString KeySeq::asString () const
Obtain a textual representation of the key sequence.
Returns
QString object
Definition at line 40 of file KeySeq.cc.
Referenced by getKeySequence().
const QKeySequence& SideCar::GUI::KeySeq::getKeySequence () const inline
Obtain the wrapped QKeySequence object.
Returns
QKeySequence reference
Definition at line 45 of file KeySeq.h.
References asString(), and matches().
bool KeySeq::matches (const KeySeq & event) const
Determine if the given key sequence from an event is the same as the key sequence we represent.
Parameters
event key sequence from an event
Returns
true if matched
Definition at line 59 of file KeySeq.cc.
Referenced by getKeySequence().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/KeySeq.h
/Users/howes/src/sidecar/GUI/KeySeq.cc