SideCar: SideCar::GUI::ChannelImaging Class Reference
SideCar::GUI::ChannelImaging Class Reference
Collection of display attributes for a data channel or artifact.
#include </Users/howes/src/sidecar/GUI/ChannelImaging.h>
Signals
void colorChanged ()
Notification sent out when the color setting changes.
void sizeChanged ()
Notification sent out when the size setting changes.
void alphaChanged ()
Notification sent out when the size setting changes.
Signals inherited from SideCar::GUI::OnOffSettingsBlock
void enabledChanged (bool state)
Notification sent out when the enabled state has changed.
Signals inherited from SideCar::GUI::SettingsBlock
void settingChanged ()
Notification sent out when a registered value has changed.
Public Member Functions
ChannelImaging (BoolSetting *enabled, ColorButtonSetting *color, DoubleSetting *size, OpacitySetting *opacity)
Constructor.
const QColor & getQColor () const
Obtain the current pen color setting as a Qt QColor value.
const Color & getColor () const
Obtain the current pen color setting as a SideCar::GUI::Color value.
float getSize () const
Obtain the current pen point/line size.
float getAlpha () const
Obtain the current alpha (opacity) value.
Public Member Functions inherited from SideCar::GUI::OnOffSettingsBlock
OnOffSettingsBlock (BoolSetting *enabled)
Constructor.
bool isEnabled () const
Determine if the settings block is enabled.
void toggleEnabled ()
Toggle the enabled state of this settings block.
void setToggleEnabledAction (QAction *action)
Install a QAction object to control the on/off state of the settings block.
void connectWidget (QCheckBox *widget)
Public Member Functions inherited from SideCar::GUI::SettingsBlock
SettingsBlock (QObject *parent=0)
Constructor.
Protected Slots
virtual void colorChanged (const QColor &color)
virtual void sizeChanged (double size)
virtual void opacityChanged (double opacity)
Protected Slots inherited from SideCar::GUI::SettingsBlock
virtual void postSettingChanged ()
Notification handler invoked when a Setting object that was registered with one of the add() methods emits its valueChanged() signal.
virtual void emitSettingChanged ()
Notification handler invoked when the QTimer object registered by the postSettingChanged() method fires.
Additional Inherited Members
Protected Member Functions inherited from SideCar::GUI::SettingsBlock
void add (Setting *setting)
Relate a Setting object to this SettingsBlock object.
Detailed Description
Collection of display attributes for a data channel or artifact.
Thise base class holds separate RGB components, a GL point size value, and a visibility boolean. The ConfigurationWindow class contains a GUI analog that provides a way to change these values from the ConfigurationWindow GUI. This is the model component of the MVC triad.
Definition at line 22 of file ChannelImaging.h.
Constructor & Destructor Documentation
ChannelImaging::ChannelImaging (BoolSetting * enabled, ColorButtonSetting * color, DoubleSetting * size, OpacitySetting * opacity)
Constructor.
Create a new model for a particular imaging part of the PPIWidget.
Parameters
enabled setting that controls whether the channel is rendered
color setting that contains the color to render with
size setting that controls the point or line size used during rendering
opacity setting that controls the alpha value of the color used during rendering
Definition at line 5 of file ChannelImaging.cc.
References alphaChanged(), colorChanged(), SideCar::GUI::QColorSetting::getValue(), SideCar::GUI::DoubleSetting::getValue(), SideCar::GUI::SettingsBlock::postSettingChanged(), and sizeChanged().
Member Function Documentation
float SideCar::GUI::ChannelImaging::getAlpha () const inline
Obtain the current alpha (opacity) value.
Larger values increase opacity, while smaller values increase transparency.
Returns
value in the range [0.0 - 1.0]
Definition at line 64 of file ChannelImaging.h.
const Color& SideCar::GUI::ChannelImaging::getColor () const inline
Obtain the current pen color setting as a SideCar::GUI::Color value.
Returns
SideCar::GUI::Color value
Definition at line 51 of file ChannelImaging.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::initializeContext(), SideCar::GUI::BScope::PPIWidget::PPIWidget(), and SideCar::GUI::ESScope::XYWidget::XYWidget().
const QColor& SideCar::GUI::ChannelImaging::getQColor () const inline
Obtain the current pen color setting as a Qt QColor value.
Returns
QColor value
Definition at line 45 of file ChannelImaging.h.
float SideCar::GUI::ChannelImaging::getSize () const inline
Obtain the current pen point/line size.
Returns
point/line size value
Definition at line 57 of file ChannelImaging.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::initializeContext(), SideCar::GUI::BScope::PPIWidget::PPIWidget(), SideCar::GUI::OffscreenBuffer::renderPoints(), SideCar::GUI::Spectrum::SpectrographWidget::SpectrographWidget(), and SideCar::GUI::ESScope::XYWidget::XYWidget().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/ChannelImaging.h
/Users/howes/src/sidecar/GUI/ChannelImaging.cc