SideCar: SideCar::Messages::TLoaderRegistry< T > Class Template Reference
SideCar::Messages::TLoaderRegistry< T > Class Template Reference
Template version of the LoaderRegistry class.
#include </Users/howes/src/sidecar/Messages/LoaderRegistry.h>
Data Structures
struct VersionedLoader
Type-specific definition of the LoaderRegistry::VersionedLoader class.
Public Types
using Super = VoidLoaderRegistry
using TLoader = ACE_InputCDR &(*)(T *object, ACE_InputCDR &cdr)
Type-specific definition of the LoaderRegistry::Loader procedure specification .
using VersionedLoaderVector = std::vector< VersionedLoader >
Public Types inherited from SideCar::Messages::VoidLoaderRegistry
using VoidLoader = ACE_InputCDR &(*)(void *object, ACE_InputCDR &cdr)
Type specification for loader procedures.
using VersionType = uint16_t
Type specification for version indicators.
Public Member Functions
TLoaderRegistry (VersionType version, TLoader loader)
Constructor.
TLoaderRegistry (const VersionedLoader *first, size_t numVersions)
Constructor.
TLoaderRegistry (const VersionedLoaderVector &vector)
void addLoader (VersionType version, TLoader loader) throw (Utils::Exception)
Register a new version/loader combination.
ACE_InputCDR & load (T *obj, ACE_InputCDR &cdr) const
Find and invoke the appropriate loader procedure depending on the version indicator read in from an ACE CDR stream.
ACE_InputCDR & load (T *obj, ACE_InputCDR &cdr, VersionType version) const
Public Member Functions inherited from SideCar::Messages::VoidLoaderRegistry
VersionType getCurrentVersion () const
Obtain the latest version registered.
Additional Inherited Members
Static Public Member Functions inherited from SideCar::Messages::VoidLoaderRegistry
static Logger::Log & Log ()
Obtain log device for instances of this class.
Protected Member Functions inherited from SideCar::Messages::VoidLoaderRegistry
VoidLoaderRegistry (VersionType version, VoidLoader loader)
Constructor.
VoidLoaderRegistry (const VersionedVoidLoader *first, size_t numVersions) throw (Utils::Exception)
Constructor.
void addVoidLoader (VersionType version, VoidLoader loader) throw (Utils::Exception)
Register a new version/loader combination.
VoidLoader getVoidLoader (VersionType version) const throw (Utils::Exception)
Obtain the appropriate loader for a given version.
Detailed Description
template<typename T>
class SideCar::Messages::TLoaderRegistry< T >
Template version of the LoaderRegistry class.
Provides type-safe registration and retrieval of loader procedures. The template parameter is a commonly the name of a class that contains methods that read from and write to an ACE CDR stream. For example, class definition for Foo
struct Foo { ACE_InputCDR& load(ACE_InputCDR& cdr) { return loaderRegistry_.load(this, cdr); } ACE_OutputCDR& write(ACE_OutputCDR& cdr) const { cdr << loaderRegistry_.getCurrentVersion(); return cdr; } private: static ACE_InputCDR& LoadV1(Foo* obj, ACE_InputCDR& cdr); static TLoaderRegistry<Foo>::VersionedLoader* DefineLoaders(); static TLoaderRegistry<Foo> loaderRegistry_; };
defines a load() and a write() method to read/write instance data (here, Foo has no instance data). The write() method first deposits the latest version number to the CDR stream. Instance attributes would then follow. In the load() method, the responsibility is immediately transfered to the TLoaderRegistry::load() method, which expects a version indicator as the next data element in the ACE CDR input stream. The method then looks for an appropriate loader to call and invokes it. The definition of the loaders occurs in the source file (as is the case for most class members) like so:
TLoaderRegistry<Foo>::VersionedLoader* Foo::DefineLoaders() { static TLoaderRegistry<Foo>::VersionedLoader loaders_[] = { TLoaderRegistry<Foo>::VersionedLoader(1, &Foo::LoadV1) }; return loaders_; }
TLoaderRegistry<Foo> PRIMessageInfo::loaderRegistry_(PRIMessageInfo::DefineLoaders(), 1);
The DefineLoaders() class method creates an array of VersionedLoader objects, which are just pairings of version indicators with method pointers. Next, the loaderRegistry_ class attribute is defined, using the result from the DefineLoaders() class method.
NOTE: playing with C++ class attributes may lead to fire. In particular, there are some narly initialization issues/rules that may cause problems. A good rule-of-thumb is to never refer to a class attribute from an inline method. Furthermore, in order for the LoaderRegistry to have a registration installed before the someone calls getLoader(), for all code paths that lead to a getLoader() call, there must be a call to a method defined and invoked in the source file where the class attribute is defined. An easy way to meet this requirement is to have no inlined constructor definitions, since an object must be constructed and available before a loader is requested in the TLoaderRegistry::load() method.
Definition at line 177 of file LoaderRegistry.h.
Constructor & Destructor Documentation
template<typename T> SideCar::Messages::TLoaderRegistry< T >::TLoaderRegistry (VersionType version, TLoader loader) inline
Constructor.
Registers a single loader.
Parameters
version version indicator to register
loader procedure to register
Definition at line 201 of file LoaderRegistry.h.
template<typename T> SideCar::Messages::TLoaderRegistry< T >::TLoaderRegistry (const VersionedLoader * first, size_t numVersions) inline
Constructor.
Registers an array of loaders and their versions.
Parameters
first pointer to the first entry to register
numVersions number of entries to register
Definition at line 209 of file LoaderRegistry.h.
Member Function Documentation
template<typename T> void SideCar::Messages::TLoaderRegistry< T >::addLoader (VersionType version, TLoader loader) throw (Utils::Exception) inline
Register a new version/loader combination.
NOTE: if the version is already registered, the routine thruws an exception.
Parameters
version version indicator to register
loader procedure to register
Definition at line 220 of file LoaderRegistry.h.
template<typename T> ACE_InputCDR& SideCar::Messages::TLoaderRegistry< T >::load (T * obj, ACE_InputCDR & cdr) const inline
Find and invoke the appropriate loader procedure depending on the version indicator read in from an ACE CDR stream.
Parameters
obj the class instance to load
cdr the input CDR stream containing the raw data
Returns
input CDR stream reference
Definition at line 232 of file LoaderRegistry.h.
Referenced by SideCar::Messages::Track::load(), SideCar::Messages::TSPI::load(), and SideCar::Messages::PRIMessage::loadArray().
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/Messages/LoaderRegistry.h