SideCar: SideCar::Messages::Extractions Class Reference
SideCar::Messages::Extractions Class Reference
Container of Extraction objects.
#include </Users/howes/src/sidecar/Messages/Extraction.h>
Data Structures
class Ref
Reference-counting reference to message object.
Public Types
using Container = std::vector< Extraction >
using iterator = Container::iterator
using const_iterator = Container::const_iterator
Public Types inherited from SideCar::Messages::Header
using Ref = boost::shared_ptr< Header >
Public Member Functions
Container & getData ()
Obtain a writeable reference to the underlying sample data container.
void reserve (size_t size)
Allocate enough space in the sample container to hold a certain number of samples.
size_t size () const
Obtain the number of data elements in the message.
bool empty () const
Determine if the message has any data at all.
void push_back (const Extraction &value)
Append a sample value to the end of the message.
Extraction & operator[] (size_t index)
Index operator to access samples using array notation.
const Extraction & operator[] (size_t index) const
Read-only index operator to access samples using array notation.
const_iterator begin () const
Obtain read-only iterator to the first sample value in the message.
const_iterator end () const
Obtain read-only iterator to the last + 1 sample value in the message.
iterator begin ()
Obtain writable iterator to the first sample value in the message.
iterator end ()
Obtain writable iterator to the last + 1 sample value in the message.
size_t getSize () const
Obtain the C++ structure size for this object.
ACE_InputCDR & load (ACE_InputCDR &cdr)
Read in binary data from a CDR stream.
ACE_OutputCDR & write (ACE_OutputCDR &cdr) const
Write out our binary data to a CDR stream.
std::ostream & printData (std::ostream &os) const
Write out the message data to a C++ text output stream.
std::ostream & printDataXML (std::ostream &os) const
Write out the message data to a C++ text output stream in XML format.
Public Member Functions inherited from SideCar::Messages::Header
Header (const MetaTypeInfo &metaTypeInfo)
Constructor for messages read in from an external device.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis, MetaTypeInfo::SequenceType sequenceNumber)
Constructor for new messages.
virtual ~Header ()
Destructor.
const MetaTypeInfo & getMetaTypeInfo () const
Obtain the type specification for the message.
const GUID & getGloballyUniqueID () const
Get the globally-unique ID of the message.
MetaTypeInfo::SequenceType getMessageSequenceNumber () const
Get the message sequence number for the message.
void setMessageSequenceNumber (MetaTypeInfo::SequenceType msn)
Set the sequence number for this message.
const Time::TimeStamp & getCreatedTimeStamp () const
Obtain when the message was created.
Time::TimeStamp setCreatedTimeStamp (const Time::TimeStamp &timeStamp)
Revise the creation message timestamp.
const Time::TimeStamp & getEmittedTimeStamp () const
Obtain when the message was written to an external device (file or network).
Time::TimeStamp setEmittedTimeStamp (const Time::TimeStamp &timeStamp)
Set the emitted time stamp with the given value.
HeaderPrinter headerPrinter () const
Convenience method that simply returns a new HeaderPrinter functor for this header object.
DataPrinter dataPrinter () const
Convenience method that simply returns a new DataPrinter functor for this header object.
XMLPrinter xmlPrinter () const
Convenience method that simply returns a new XMLPrinter functor for this header object.
virtual std::ostream & print (std::ostream &os) const
Write out the entire message to a C++ text output stream.
virtual std::ostream & printHeader (std::ostream &os) const
Write out the message header to a C++ text output stream.
virtual std::ostream & printXML (std::ostream &os) const
Write out the message to a C++ text output stream in XML format.
bool hasBasis () const
Determine if the message has a basis message attached to it.
Ref getBasis () const
Obtain a reference to the message that this one was based on.
template<typename T >
T::Ref getBasis () const
Templated version of the above method.
Static Public Member Functions
static const MetaTypeInfo & GetMetaTypeInfo ()
static Ref Make (const std::string &producer, const Header::Ref &basis)
static Ref Make (ACE_InputCDR &cdr)
Static Public Member Functions inherited from SideCar::Messages::Header
static Logger::Log & Log ()
Obtain log device to use for objects of this class.
static const MetaTypeInfo * GetMessageMetaTypeInfo (ACE_InputCDR &cdr)
Protected Member Functions
Extractions (const std::string &producer)
Extractions (const std::string &producer, const Header::Ref &basis)
Detailed Description
Container of Extraction objects.
The interface is similar to that for TPRIMessage objects, but it does not derive from PRIMessageBase since the elements may not have the same azimuth value.
Definition at line 135 of file Extraction.h.
Member Function Documentation
const_iterator SideCar::Messages::Extractions::begin () const inline
Obtain read-only iterator to the first sample value in the message.
Returns
read-only iterator
Definition at line 248 of file Extraction.h.
iterator SideCar::Messages::Extractions::begin () inline
Obtain writable iterator to the first sample value in the message.
Returns
writable iterator
Definition at line 260 of file Extraction.h.
bool SideCar::Messages::Extractions::empty () const inline
Determine if the message has any data at all.
Returns
true if empty
Definition at line 220 of file Extraction.h.
const_iterator SideCar::Messages::Extractions::end () const inline
Obtain read-only iterator to the last + 1 sample value in the message.
Returns
read-only iterator
Definition at line 254 of file Extraction.h.
iterator SideCar::Messages::Extractions::end () inline
Obtain writable iterator to the last + 1 sample value in the message.
Returns
writable iterator
Definition at line 266 of file Extraction.h.
Container& SideCar::Messages::Extractions::getData () inline
Obtain a writeable reference to the underlying sample data container.
Returns
Container reference
Definition at line 201 of file Extraction.h.
size_t SideCar::Messages::Extractions::getSize () const inline virtual
Obtain the C++ structure size for this object.
Derived classes must override if they extend Header with additional members.
Returns
size of a Header object.
Reimplemented from SideCar::Messages::Header.
Definition at line 268 of file Extraction.h.
ACE_InputCDR & Extractions::load (ACE_InputCDR & cdr) virtual
Read in binary data from a CDR stream.
Parameters
cdr stream to read from
Returns
stream read from
Reimplemented from SideCar::Messages::Header.
Definition at line 96 of file Extraction.cc.
References SideCar::Messages::Header::load().
Extraction& SideCar::Messages::Extractions::operator[] (size_t index) inline
Index operator to access samples using array notation.
Parameters
index sample to obtain
Returns
reference to indexed sample
Definition at line 234 of file Extraction.h.
const Extraction& SideCar::Messages::Extractions::operator[] (size_t index) const inline
Read-only index operator to access samples using array notation.
Parameters
index sample to obtain
Returns
read-only reference to indexed sample
Definition at line 242 of file Extraction.h.
std::ostream & Extractions::printData (std::ostream & os) const virtual
Write out the message data to a C++ text output stream.
Parameters
os stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Definition at line 125 of file Extraction.cc.
std::ostream & Extractions::printDataXML (std::ostream & os) const virtual
Write out the message data to a C++ text output stream in XML format.
Parameters
os stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Definition at line 134 of file Extraction.cc.
References SideCar::Messages::Extraction::Extraction(), SideCar::Messages::Header::loadXML(), and SideCar::Messages::XmlStreamReader::readNextEntityAndValidate().
void SideCar::Messages::Extractions::push_back (const Extraction & value) inline
Append a sample value to the end of the message.
Parameters
datum value to append
Definition at line 226 of file Extraction.h.
void SideCar::Messages::Extractions::reserve (size_t size) inline
Allocate enough space in the sample container to hold a certain number of samples.
Simply forwards to the container's reserve() method.
Parameters
size space to reserve
Definition at line 208 of file Extraction.h.
size_t SideCar::Messages::Extractions::size () const inline
Obtain the number of data elements in the message.
Returns
count
Definition at line 214 of file Extraction.h.
ACE_OutputCDR & Extractions::write (ACE_OutputCDR & cdr) const virtual
Write out our binary data to a CDR stream.
Parameters
cdr stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Definition at line 111 of file Extraction.cc.
References SideCar::Messages::Header::write().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Messages/Extraction.h
/Users/howes/src/sidecar/Messages/Extraction.cc