SideCar: SideCar::GUI::ToolWindowBase Class Reference
SideCar::GUI::ToolWindowBase Class Reference
Common base class for all SideCar GUI tool windows.
#include </Users/howes/src/sidecar/GUI/ToolWindowBase.h>
Public Slots
virtual void activeMainWindowChanged (MainWindowBase *window)
virtual void applyInitialVisibility ()
virtual void toggleVisibility ()
virtual void showAndRaise ()
Public Member Functions
ToolWindowBase (const QString &name, const QString &actionTitle, int shortcut=0)
Constructor.
QAction * getShowHideAction () const
Obtain the QAction object that toggles the tool window's visibility.
void setFixedSize ()
Configure the window so that the user may not resize it.
bool getInitialVisibility () const
Determine if the application should show the window at startup.
Static Public Member Functions
static Logger::Log & Log ()
Log device for instances of this class.
static AppBase * getApp ()
Convenience method that obtains the AppBase singleton.
Protected Member Functions
void showEvent (QShowEvent *event)
Event handler for show events.
void closeEvent (QCloseEvent *event)
Event handler for close events.
void hideEvent (QHideEvent *event)
Event handler for hide events.
Detailed Description
Common base class for all SideCar GUI tool windows.
A tool window is a QDialog window that is not modal. The application saves and restores tool window position, size, and visibility state information.
Definition at line 17 of file ToolWindowBase.h.
Constructor & Destructor Documentation
ToolWindowBase::ToolWindowBase (const QString & name, const QString & actionTitle, int shortcut = 0)
Constructor.
Parameters
name the name of the tool window to use when loading and saving settings
actionTitle text for the QAction object used to control window visibility
shortcut optional key sequence used to toggle window visibility reflects the state of the tool window
Definition at line 42 of file ToolWindowBase.cc.
References getApp(), Log(), and LOGINFO.
Member Function Documentation
void ToolWindowBase::closeEvent (QCloseEvent * event) protected
Event handler for close events.
Update any managed QAction object.
Parameters
event event descriptor
Definition at line 104 of file ToolWindowBase.cc.
References getApp(), Log(), and LOGINFO.
Referenced by SideCar::GUI::AScope::ChannelConnectionWindow::activeDisplayViewChanged().
AppBase * ToolWindowBase::getApp () static
Convenience method that obtains the AppBase singleton.
Returns
AppBase object
Definition at line 74 of file ToolWindowBase.cc.
References SideCar::GUI::AppBase::GetApp().
Referenced by SideCar::GUI::AScope::ChannelConnectionWindow::activeDisplayViewChanged(), closeEvent(), SideCar::GUI::AScope::ConfigurationWindow::ConfigurationWindow(), hideEvent(), and ToolWindowBase().
bool ToolWindowBase::getInitialVisibility () const
Determine if the application should show the window at startup.
Returns
true if so
Definition at line 140 of file ToolWindowBase.cc.
References Log(), LOGINFO, and SideCar::GUI::UpdateToggleAction().
QAction* SideCar::GUI::ToolWindowBase::getShowHideAction () const inline
Obtain the QAction object that toggles the tool window's visibility.
Returns
QAction object
Definition at line 47 of file ToolWindowBase.h.
Referenced by SideCar::GUI::AppBase::addToolWindow(), SideCar::GUI::Playback::MainWindow::MainWindow(), and SideCar::GUI::HealthAndStatus::MainWindow::MainWindow().
void ToolWindowBase::hideEvent (QHideEvent * event) protected
Event handler for hide events.
Update any managed QAction object.
Parameters
event event descriptor
Definition at line 121 of file ToolWindowBase.cc.
References getApp(), Log(), and LOGINFO.
Logger::Log & ToolWindowBase::Log () static
Log device for instances of this class.
Returns
log device
Definition at line 35 of file ToolWindowBase.cc.
References Logger::Log::Find().
Referenced by closeEvent(), getInitialVisibility(), hideEvent(), setFixedSize(), showEvent(), and ToolWindowBase().
void ToolWindowBase::showEvent (QShowEvent * event) protected
Event handler for show events.
Use any saved settings for the window's size and position values. Updates any managed QAction object.
Parameters
event event descriptor
Definition at line 89 of file ToolWindowBase.cc.
References Log(), and LOGINFO.
Referenced by SideCar::GUI::ManualWindow::ManualWindow(), and SideCar::GUI::PresetsWindow::PresetsWindow().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/ToolWindowBase.h
/Users/howes/src/sidecar/GUI/ToolWindowBase.cc