SideCar: SideCar::GUI::AScope::ChannelConnectionModel Class Reference
SideCar::GUI::AScope::ChannelConnectionModel Class Reference
A model of channel connection objects for a specific Visualizer (only one Visualizer is the active one at any time).
#include </Users/howes/src/sidecar/GUI/AScope/ChannelConnectionModel.h>
Public Types
enum Columns {
kName = 0, kColor, kSampleMin, kSampleMax,
kVoltageMin, kVoltageMax, kVisible, kFrozen,
kShowPeakBars, kDisplayCount, kNumColumns
}
Indices of the data columns provided by the model.
using VideoChannelHash = QHash< QString, VideoChannel * >
Mapping of VideoChannel objects to their name.
Public Member Functions
ChannelConnectionModel (ChannelConnectionWindow *parent)
Constructor.
~ChannelConnectionModel ()
Destructor.
VideoChannel * getVideoChannel (const QString &channelName)
Obtain the VideoChannel object with a given name.
ChannelConnection * getChannelConnection (int row) const
Obtain the ChannelConnection object associated with row.
void setVisualizer (Visualizer *visualizer)
Set the active Visualizer object.
bool makeConnection (const QString &name)
Create a new ChannelConnection object to link the active Plotter object with the VideoChannel object having a given name.
ServiceEntry * removeConnection (int index)
Remove an existing connections.
int columnCount (const QModelIndex &parent=QModelIndex()) const
Implementation of QAbstractItemModel method.
int rowCount (const QModelIndex &parent=QModelIndex()) const
Implementation of QAbstractItemModel method.
QVariant data (const QModelIndex &pos, int role=Qt::DisplayRole) const
Implementation of QAbstractItemModel method.
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Implementation of QAbstractItemModel method.
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Implementation of QAbstractItemModel method.
Qt::ItemFlags flags (const QModelIndex &index) const
Implementation of QAbstractItemModel method.
void moveUp (int row)
Move a row up in the list of channel connections.
void moveDown (int row)
Move a row down in the list of channel connections.
void saveVideoChannelSettings ()
Write current VideoChannel settings the to application's settings file.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for instances of this class.
Detailed Description
A model of channel connection objects for a specific Visualizer (only one Visualizer is the active one at any time).
The model supplies the data for display by a ChannelConnectionView view, and it implements most of the controller aspects of the MVC paradigm.
Definition at line 27 of file ChannelConnectionModel.h.
Constructor & Destructor Documentation
ChannelConnectionModel::ChannelConnectionModel (ChannelConnectionWindow * parent)
Constructor.
Parameters
parent owner of the object
Definition at line 42 of file ChannelConnectionModel.cc.
References SideCar::Messages::Video::GetMetaTypeInfo(), Log(), LOGINFO, SideCar::IO::ZeroconfTypes::TZCType< id >::MakeZeroconfType(), and SideCar::GUI::ServiceBrowser::start().
ChannelConnectionModel::~ChannelConnectionModel ()
Destructor.
Shuts down held VideoChannel objects.
Definition at line 66 of file ChannelConnectionModel.cc.
Member Function Documentation
int ChannelConnectionModel::columnCount (const QModelIndex & parent = QModelIndex()) const
Implementation of QAbstractItemModel method.
Obtain the number of columns in the model data.
Parameters
parent model index of containing parent model (not used)
Returns
number of columns (kNumColumns)
Definition at line 229 of file ChannelConnectionModel.cc.
QVariant ChannelConnectionModel::data (const QModelIndex & pos, int role = Qt::DisplayRole) const
Implementation of QAbstractItemModel method.
Obtain a piece of data from the model for a particular location (row,column) and purpose.
Parameters
index location of the datum to get
role how the data will be used
Returns
value to use for the given purpose
Definition at line 242 of file ChannelConnectionModel.cc.
References SideCar::GUI::AScope::ChannelConnection::getChannel(), getChannelConnection(), SideCar::GUI::AScope::VideoChannel::isConnected(), SideCar::GUI::AScope::ChannelConnection::isFrozen(), SideCar::GUI::AScope::ChannelConnection::isShowingPeakBars(), SideCar::GUI::AScope::ChannelConnection::isVisible(), Log(), and rowCount().
Qt::ItemFlags ChannelConnectionModel::flags (const QModelIndex & index) const
Implementation of QAbstractItemModel method.
Obtain the display flags for a particular location. All elements have Qt::ItemIsEnabled set, and the kVisible column has Qt::ItemIsUserCheckable set.
Parameters
index location of the flags to get
Returns
display flags
Definition at line 389 of file ChannelConnectionModel.cc.
References SideCar::GUI::OnOffSettingsBlock::isEnabled().
ChannelConnection * ChannelConnectionModel::getChannelConnection (int row) const
Obtain the ChannelConnection object associated with row.
Parameters
row the row to fetch
Returns
ChannelConnection object or NULL if row is invalid
Definition at line 131 of file ChannelConnectionModel.cc.
References SideCar::GUI::AScope::VideoChannel::getName(), SideCar::GUI::ServiceBrowser::getServiceEntry(), Log(), LOGINFO, and SideCar::GUI::AScope::VideoChannel::useServiceEntry().
Referenced by SideCar::GUI::AScope::ChannelConnectionView::ChannelConnectionView(), data(), and SideCar::GUI::AScope::ChannelConnectionWindow::getSelectedChannelConnection().
VideoChannel * ChannelConnectionModel::getVideoChannel (const QString & channelName)
Obtain the VideoChannel object with a given name.
Parameters
channelName name to look for
Returns
found object or NULL
Definition at line 176 of file ChannelConnectionModel.cc.
References Log(), and LOGINFO.
Referenced by SideCar::GUI::AScope::ChannelConnectionWindow::getVideoChannel(), and makeConnection().
QVariant ChannelConnectionModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
Implementation of QAbstractItemModel method.
Obtain a piece of data from the model to display in the horizontal or vertical header. The horizontal header contains column names, while the vertical header contains row numbers (one-based).
Parameters
section which row or column to fetch
orientation which header, horizontal or vertical, to fetch for
role how the data will be used
Returns
value to use for the given purpose
Definition at line 366 of file ChannelConnectionModel.cc.
Logger::Log & ChannelConnectionModel::Log () static
Obtain the log device for instances of this class.
Returns
log device
Definition at line 35 of file ChannelConnectionModel.cc.
References Logger::Log::Find().
Referenced by ChannelConnectionModel(), data(), getChannelConnection(), getVideoChannel(), makeConnection(), removeConnection(), saveVideoChannelSettings(), setData(), and setVisualizer().
bool ChannelConnectionModel::makeConnection (const QString & name)
Create a new ChannelConnection object to link the active Plotter object with the VideoChannel object having a given name.
If there is no VideoChannel object found with the given name, create one.
Parameters
name data channel name
Returns
true if successful, false otherwise
Definition at line 192 of file ChannelConnectionModel.cc.
References SideCar::GUI::AScope::App::GetApp(), getVideoChannel(), Log(), LOGERROR, LOGINFO, and rowCount().
Referenced by SideCar::GUI::AScope::ChannelConnectionWindow::getSelectedChannelConnection().
void ChannelConnectionModel::moveDown (int row)
Move a row down in the list of channel connections.
Rows higher are drawn before those below them.
Parameters
row index of the ChannelConnection object to move
Definition at line 519 of file ChannelConnectionModel.cc.
Referenced by SideCar::GUI::AScope::ChannelConnectionWindow::getSelectedChannelConnection().
void ChannelConnectionModel::moveUp (int row)
Move a row up in the list of channel connections.
Rows higher are drawn before those below them.
Parameters
row index of the ChannelConnection object to move
Definition at line 510 of file ChannelConnectionModel.cc.
Referenced by SideCar::GUI::AScope::ChannelConnectionWindow::getSelectedChannelConnection().
ServiceEntry * ChannelConnectionModel::removeConnection (int index)
Remove an existing connections.
Parameters
index index of the ChannelConnection object to remove
Returns
ServiceEntry of the connection that was removed if still available, or NULL if service is no longer present
Definition at line 212 of file ChannelConnectionModel.cc.
References SideCar::GUI::AScope::VideoChannel::getName(), SideCar::GUI::ServiceBrowser::getServiceEntry(), SideCar::GUI::AScope::VideoChannel::isDisplayed(), Log(), and LOGINFO.
Referenced by SideCar::GUI::AScope::ChannelConnectionWindow::getSelectedChannelConnection().
int ChannelConnectionModel::rowCount (const QModelIndex & parent = QModelIndex()) const
Implementation of QAbstractItemModel method.
Obtain the number of rows in the model data.
Parameters
parent model index of containing parent model (not used)
Returns
number of rows
Definition at line 235 of file ChannelConnectionModel.cc.
References SideCar::GUI::AScope::Visualizer::getNumChannelConnections().
Referenced by SideCar::GUI::AScope::ChannelConnectionView::ChannelConnectionView(), SideCar::GUI::AScope::ChannelConnectionWindow::ChannelConnectionWindow(), data(), SideCar::GUI::AScope::ChannelConnectionWindow::getSelectedChannelConnection(), makeConnection(), saveVideoChannelSettings(), and setVisualizer().
bool ChannelConnectionModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole)
Implementation of QAbstractItemModel method.
Change the data in the model at a particular location and display purpose.
Parameters
index location of the datum to set
value new value to use
role how the data will be used
Returns
true if the value was successfully set, false otherwise.
Definition at line 422 of file ChannelConnectionModel.cc.
References SideCar::GUI::AScope::VideoChannel::getName(), SideCar::GUI::AScope::VideoChannel::isConnected(), Log(), LOGDEBUG, LOGINFO, SideCar::GUI::AScope::ChannelConnection::setFrozen(), SideCar::GUI::AScope::ChannelConnection::setVisible(), setVisualizer(), and SideCar::GUI::AScope::VideoChannel::useServiceEntry().
Referenced by SideCar::GUI::AScope::ChannelConnectionView::ChannelConnectionView().
void ChannelConnectionModel::setVisualizer (Visualizer * visualizer)
Set the active Visualizer object.
May be NULL.
Parameters
visualizer Visualizer object to use
Definition at line 75 of file ChannelConnectionModel.cc.
References SideCar::GUI::AScope::Visualizer::getNumChannelConnections(), Log(), LOGDEBUG, LOGINFO, rowCount(), and SideCar::GUI::AScope::ChannelConnectionWindow::setUnconnected().
Referenced by SideCar::GUI::AScope::ChannelConnectionWindow::activeDisplayViewChanged(), and setData().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/AScope/ChannelConnectionModel.h
/Users/howes/src/sidecar/GUI/AScope/ChannelConnectionModel.cc