SideCar: SideCar::GUI::PRIEmitter::App Class Reference
SideCar::GUI::PRIEmitter::App Class Reference
Application class for the PRIEmitter application.
#include </Users/howes/src/sidecar/GUI/PRIEmitter/App.h>
Public Member Functions
App (int &argc, char **argv)
Constructor.
Public Member Functions inherited from SideCar::GUI::AppBase
AppBase (const QString &name, int &argc, char **argv)
Constructor.
~AppBase ()
Destructor.
const QString & getApplicationName () const
QString getDocumentationPath () const
WindowManager * getWindowManager () const
QMenu * makeApplicationMenu (QWidget *parent)
QMenu * makeToolsMenu (QWidget *parent)
QMenu * makeWindowMenu (QWidget *parent)
QMenu * makeLoggingMenu (QWidget *parent)
QMenu * makeHelpMenu (QWidget *parent)
QAction * getToolsMenuAction (int index)
Obtain a specific QAction object found in the Tools menu.
void addWindowMenuActionTo (ToolBar *toolBar, int index) const
void setVisibleWindowMenuNew (bool visible)
Set the visibility state of the "New" action in the "Window" menu.
void setVisibleWindowMenuClose (bool visible)
Set the visibility state of the "Close" action in the "Window" menu.
void setVisibleWindowMenuMinimize (bool visible)
Set the visibility state of the "Minimize" action in the "Window" menu.
void setVisibleWindowMenuMaximize (bool visible)
Set the visibility state of the "Maximize" action in the "Window" menu.
void setVisibleWindowMenuFullScreen (bool visible)
Set the visibility state of the full-screen action in the "Window" menu.
void setLogConfigurationFile (const QString &path)
Use a configuration file for the Logger classes.
int getNumManagedWindows () const
Obtain the number of open MainWindowBase objects.
MainWindowBase * getActiveMainWindow () const
Obtain the active MainWindowBase object.
void manageWindow (QWidget *window, QMenu *windowMenu)
Manage a top-level window.
void unmanageWindow (QWidget *window)
Unmanage a top-level window.
bool isManagedWindow (QWidget *window) const
Determine if a given widget is managed by the application.
QWidget * getManagedWindow (const QString &title) const
bool isQuitting () const
Determine if the application is in the process of shutting down.
const QString & getDistanceUnits () const
Obtain the current distance units suffix.
QString getFormattedDistance (double value) const
Obtain a formatted representation of a distance value.
QString getFormattedAngleRadians (double value) const
Obtain a formatted representation of an angular value in radians.
QString getFormattedAngleDegrees (double value) const
Obtain a formatted representation of an angular value in degrees.
QPointF getPhantomCursor () const
Obtain the current phantom cursor value.
virtual void restoreWindows ()
Restore the windows that were open at the time the application last quit.
Static Public Member Functions
static App * GetApp ()
Obtain the singleton App object.
Static Public Member Functions inherited from SideCar::GUI::AppBase
static Logger::Log & Log ()
Log device for instances of this class.
static AppBase * GetApp ()
Obtain the AppBase singleton.
static QString GetRootDocumentationPath ()
Protected Member Functions
MainWindowBase * makeNewMainWindow (const QString &objectName)
Create a new MainWindow object and show to the user.
Protected Member Functions inherited from SideCar::GUI::AppBase
virtual void addToolWindow (int index, ToolWindowBase *toolWindow)
Register a tool window with the application.
MainWindowBase * makeAndInitializeNewMainWindow (const QString &type)
Additional Inherited Members
Public Types inherited from SideCar::GUI::AppBase
enum AngularFormatType { kDegreesMinutesSeconds = 0, kDecimal, kNumFormattingTypes }
Enumeration for the various angular formatting available from the application.
Public Slots inherited from SideCar::GUI::AppBase
void updateToggleAction (bool state)
virtual void setPhantomCursor (const QPointF &pos)
Set the held phantom cursor value.
void showMessage (const QString &msg, int duration)
Show a message in the active main window.
void setAngleFormatting (AngularFormatType type)
Change the formatting used by getFormattedAngleDegrees() and getFormattedAngleRadians() methods.
void setDistanceUnits (const QString &units)
Change the distance units used by getFormattedDistance() method.
virtual void applicationQuit ()
Action event handler for the "Quit" menu item.
virtual void loggingLoadConfigurationFile ()
Present to the user an open file dialog in order to select a Logger configuration file.
virtual void loadStyleSheet ()
virtual void showAbout ()
virtual void windowNew ()
Signals inherited from SideCar::GUI::AppBase
void activeMainWindowChanged (MainWindowBase *window)
Notification sent out when the application's active main window changes.
void shutdown ()
Notification sent out when the application is shutting down.
void restoreToolWindows ()
Notification sent out to all ToolWindowBase objects that they should show themselves if they were visible when the application last quit.
void angleFormattingChanged (int type)
Notification sent out when the angular formatting setting has been changed by the user.
void distanceUnitsChanged (const QString &suffix)
Notification sent out when the distance units have been changed by the user.
void phantomCursorChanged (const QPointF &pos)
Notification sent out when the phantom cursor value has been changed.
Detailed Description
Application class for the PRIEmitter application.
Definition at line 25 of file App.h.
Constructor & Destructor Documentation
SideCar::GUI::PRIEmitter::App::App (int & argc, char ** argv) inline
Constructor.
Parameters
argc command-line argument count
argv command-line argument values
Definition at line 43 of file App.h.
References makeNewMainWindow().
Member Function Documentation
static App* SideCar::GUI::PRIEmitter::App::GetApp () inline static
Obtain the singleton App object.
Returns
App instance
Definition at line 35 of file App.h.
MainWindowBase * App::makeNewMainWindow (const QString & objectName) protected virtual
Create a new MainWindow object and show to the user.
Implements AppBase::makeNewMainWindow() interface.
Returns
new MainWindow object
Implements SideCar::GUI::AppBase.
Definition at line 8 of file App.cc.
References SideCar::GUI::PRIEmitter::MainWindow::openFile().
Referenced by App().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/PRIEmitter/App.h
/Users/howes/src/sidecar/GUI/PRIEmitter/App.cc