SideCar: SideCar::GUI::ESScope::XYWidget Class Reference
SideCar::GUI::ESScope::XYWidget Class Reference abstract
Public Slots
void setSlaveAlpha (double value)
void redraw ()
void clear ()
Signals
void cursorMoved (double x, double y)
void bugged ()
Public Member Functions
XYWidget (XYView *parent, ViewSettings *viewSettings, PlotPositionFunctor *plotPositionFunctor)
Constructor.
void localToRealWorld (int x, int y, GLdouble &alpha, GLdouble &beta) const
void setGridPositions (const std::vector< float > &alpha, const std::vector< float > &beta)
double getXScaling () const
double getYScaling () const
double getXYScaling () const
virtual int getXScans () const =0
virtual int getYScans () const =0
virtual double getXMinMin () const =0
virtual double getXMaxMax () const =0
virtual double getYMinMin () const =0
virtual double getYMaxMax () const =0
QPointF getPendingBugPlot () const
void clearPendingBugPlot ()
Static Public Member Functions
static Logger::Log & Log ()
static QGLFormat GetGLFormat ()
Obtain the OpenGL configuration we want to use.
Protected Types
enum ListIndex { kGridLines = 0, kNumLists }
enum VBOIndex { kVertices = 0, kColors, kNumVBOs }
Protected Slots
virtual void alphasChanged (const AlphaIndices &indices)=0
void generateVertices ()
Protected Member Functions
GLuint getDisplayList (int index) const
void initializeGL ()
void makeBuffers ()
void paintGL ()
void updateColors (int offset)
void resizeGL (int width, int height)
void setViewTransform ()
void mousePressEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void keyPressEvent (QKeyEvent *event)
void wheelEvent (QWheelEvent *event)
void enterEvent (QEvent *event)
void leaveEvent (QEvent *event)
virtual void fillColors ()=0
void centerAtCursor ()
void changeZoom (int factor)
Protected Attributes
GLuint vbos_ [kNumVBOs]
XYView * parent_
ViewSettings * viewSettings_
PlotPositionFunctor * plotPositionFunctor_
VideoSampleCountTransform * videoSampleCountTransform_
VideoImaging * videoImaging_
RadarSettings * radarSettings_
TargetPlotImaging * extractionsImaging_
TargetPlotImaging * rangeTruthsImaging_
TargetPlotImaging * bugPlotsImaging_
BugPlotEmitterSettings * bugPlotEmitterSettings_
GridImaging * gridImaging_
PhantomCursorImaging * phantomCursorImaging_
History * history_
int xScans_
int yScans_
int gridSize_
double xScaling_
double yScaling_
double xyScaling_
GLuint displayLists_
QPoint lastMouse_
QPoint pendingBugPlot_
GLdouble lastMouseX_
GLdouble lastMouseY_
std::vector< float > hGridPositions_
std::vector< float > vGridPositions_
QuadColorVector colors_
Color clearColor_
QPoint magStartPos_
double magStartX_
double magStartY_
double magEndX_
double magEndY_
double slaveAlpha_
bool rubberBanding_
bool underMouse_
Detailed Description
Definition at line 34 of file XYWidget.h.
Constructor & Destructor Documentation
XYWidget::XYWidget (XYView * parent, ViewSettings * viewSettings, PlotPositionFunctor * plotPositionFunctor)
Constructor.
Parameters
parent parent object
Definition at line 53 of file XYWidget.cc.
References SideCar::GUI::ESScope::App::GetApp(), SideCar::GUI::ESScope::History::getBugPlots(), SideCar::GUI::ChannelImaging::getColor(), SideCar::GUI::ESScope::History::getExtractions(), SideCar::GUI::ESScope::History::getRangeTruths(), SideCar::GUI::ChannelImaging::getSize(), SideCar::GUI::OnOffSettingsBlock::isEnabled(), LOGERROR, LOGINFO, SideCar::GUI::TargetPlotImaging::render(), Logger::ProcLog::thrower(), SideCar::GUI::VideoSampleCountTransform::transform(), SideCar::GUI::StencilBufferState::use(), and SideCar::GUI::Color::use().
Member Function Documentation
QGLFormat XYWidget::GetGLFormat () static
Obtain the OpenGL configuration we want to use.
Returns
OpenGL format
Definition at line 41 of file XYWidget.cc.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/ESScope/XYWidget.h
/Users/howes/src/sidecar/GUI/ESScope/XYWidget.cc