SideCar: SideCar::GUI::VideoSampleCountTransform Class Reference
SideCar::GUI::VideoSampleCountTransform Class Reference
Converts sample count information contained in Messages::Video messages into values between 0 and 1, inclusive.
#include </Users/howes/src/sidecar/GUI/VideoSampleCountTransform.h>
Public Slots
void setShowDecibels (bool value)
Signals
void showingDecibels (bool state)
Notification sent out when the decibel setting changes.
Signals inherited from SideCar::GUI::SettingsBlock
void settingChanged ()
Notification sent out when a registered value has changed.
Public Member Functions
VideoSampleCountTransform (IntSetting *sampleMin, IntSetting *sampleMax, IntSetting *gain, IntSetting *cutoffMin, IntSetting *cutoffMax, BoolSetting *showDecibels)
Constructor.
double transform (int sampleCount) const
Transform a sample count value into a value in range [0-1].
int inverseTransform (double value) const
double operator() (int sampleCount) const
Call operator to allow transform function in STL constructs.
int getSampleMin () const
Obtain the current min sample value.
int getSampleMax () const
Obtain the current max sample value.
double getThresholdMin () const
Obtain the current low-end cutoff value.
double getThresholdMax () const
Obtain the current high-end cutoff percentage.
bool getShowDecibels () const
Determine if values from transform() are in decibels.
void setThresholdMin (int value)
void setThresholdMax (int value)
Public Member Functions inherited from SideCar::GUI::SettingsBlock
SettingsBlock (QObject *parent=0)
Constructor.
Static Public Member Functions
static Logger::Log & Log ()
Additional Inherited Members
Protected Slots inherited from SideCar::GUI::SettingsBlock
virtual void postSettingChanged ()
Notification handler invoked when a Setting object that was registered with one of the add() methods emits its valueChanged() signal.
virtual void emitSettingChanged ()
Notification handler invoked when the QTimer object registered by the postSettingChanged() method fires.
Protected Member Functions inherited from SideCar::GUI::SettingsBlock
void add (Setting *setting)
Relate a Setting object to this SettingsBlock object.
Detailed Description
Converts sample count information contained in Messages::Video messages into values between 0 and 1, inclusive.
The mapping takes into account user controls that provide gain and lower-bounds thresholding. Can also return values in decibels.
The gain_ setting is simply a multiplier that is applied to incoming sample counts before anything else is done. The ControlsWindow contains a GUI widget that manipulates this value.
The cutoff_ affects how much of the sample range (defined by sampleMin_ and sampleMax_) is mapped to the output range 0-1. Its value ranges from [0-1.0) and reflects a percentage of the available sample range, starting at the low end. A cutoff_value of 0 provides a full mapping, while values > 0.0 create a threshold greater than sampleMin_, thus reducing the input bandwidth:
threshold_ = cutoff_ * (sampleMax_ - sampleMin_) + sampleMin_;
The transform() routine clamps input values to the range [threshold_, sampleMax_].
Definition at line 37 of file VideoSampleCountTransform.h.
Constructor & Destructor Documentation
VideoSampleCountTransform::VideoSampleCountTransform (IntSetting * sampleMin, IntSetting * sampleMax, IntSetting * gain, IntSetting * cutoffMin, IntSetting * cutoffMax, BoolSetting * showDecibels)
Constructor.
Parameters
sampleMin smallest sample value in message data
sampleMax largest sample value in message data
gain initial gain value multiplied with samples
cutoffMin initial low-end cutoff value
cutoffMax initial high-end cutoff value
showDecibels initial setting for returning decibel values
Definition at line 17 of file VideoSampleCountTransform.cc.
References SideCar::GUI::SettingsBlock::add(), SideCar::GUI::SettingsBlock::emitSettingChanged(), SideCar::GUI::BoolSetting::getValue(), SideCar::GUI::IntSetting::getValue(), LOGINFO, SideCar::GUI::IntSetting::setValue(), and showingDecibels().
Member Function Documentation
int SideCar::GUI::VideoSampleCountTransform::getSampleMax () const inline
Obtain the current max sample value.
Returns
max sample
Definition at line 93 of file VideoSampleCountTransform.h.
Referenced by SideCar::GUI::ColorMapWidget::ColorMapWidget().
int SideCar::GUI::VideoSampleCountTransform::getSampleMin () const inline
Obtain the current min sample value.
Returns
min sample
Definition at line 87 of file VideoSampleCountTransform.h.
Referenced by SideCar::GUI::ColorMapWidget::ColorMapWidget().
bool SideCar::GUI::VideoSampleCountTransform::getShowDecibels () const inline
Determine if values from transform() are in decibels.
Returns
true if so
Definition at line 111 of file VideoSampleCountTransform.h.
Referenced by SideCar::GUI::ColorMapWidget::ColorMapWidget().
double SideCar::GUI::VideoSampleCountTransform::getThresholdMax () const inline
Obtain the current high-end cutoff percentage.
Returns
cutoff value
Definition at line 105 of file VideoSampleCountTransform.h.
Referenced by SideCar::GUI::ColorMapWidget::ColorMapWidget().
double SideCar::GUI::VideoSampleCountTransform::getThresholdMin () const inline
Obtain the current low-end cutoff value.
Returns
cutoff value
Definition at line 99 of file VideoSampleCountTransform.h.
Referenced by SideCar::GUI::ColorMapWidget::ColorMapWidget().
double SideCar::GUI::VideoSampleCountTransform::operator() (int sampleCount) const inline
Call operator to allow transform function in STL constructs.
Parameters
sampleCount the value to transform
Returns
value in range [0-1]
Definition at line 80 of file VideoSampleCountTransform.h.
void SideCar::GUI::VideoSampleCountTransform::showingDecibels (bool state) signal
Notification sent out when the decibel setting changes.
Parameters
state new state
Referenced by VideoSampleCountTransform().
double VideoSampleCountTransform::transform (int sampleCount) const
Transform a sample count value into a value in range [0-1].
Parameters
sampleCount the value to transform
Returns
value in range [0-1]
Definition at line 104 of file VideoSampleCountTransform.cc.
References SideCar::GUI::BoolSetting::getValue().
Referenced by SideCar::GUI::ESScope::XYWidget::XYWidget().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/VideoSampleCountTransform.h
/Users/howes/src/sidecar/GUI/VideoSampleCountTransform.cc