SideCar: SideCar::IO::TCPInputHandler Class Reference
SideCar::IO::TCPInputHandler Class Reference
Public Member Functions
TCPInputHandler (IOTask *task=0)
int open (void *arg=0)
Sets up the SocketReader instance to use the socket connection to the client.
int close (u_long flags=0)
Close the connection.
int handle_input (ACE_HANDLE device=ACE_INVALID_HANDLE)
Gives its SocketReader object a chance to fetch data from the socket, and if there is a finished message available, it will pass it in a call to ServerSocketReaderTask::put().
int handle_close (ACE_HANDLE device=ACE_INVALID_HANDLE, ACE_Reactor_Mask mask=0)
Notification that the remote side closed the connection.
Static Public Member Functions
static Logger::Log & Log ()
Log device for objects of this type.
Detailed Description
Definition at line 16 of file TCPInputHandler.h.
Member Function Documentation
int TCPInputHandler::close (u_long flags = 0)
Close the connection.
Override of ACE_Task method.
Parameters
flags ignored
Returns
-1 if failed
Definition at line 52 of file TCPInputHandler.cc.
References Log(), LOGDEBUG, LOGERROR, and LOGINFO.
Referenced by SideCar::IO::TCPConnector::close().
int TCPInputHandler::handle_close (ACE_HANDLE device = ACE_INVALID_HANDLE, ACE_Reactor_Mask mask = 0)
Notification that the remote side closed the connection.
Override of ACE_Event_Handler method.
Parameters
device device descriptor of the connection that closed
mask registration mask of the device in the ACE_Reactor
Returns
-1 if failed
Definition at line 118 of file TCPInputHandler.cc.
References Log(), and LOGINFO.
int TCPInputHandler::handle_input (ACE_HANDLE device = ACE_INVALID_HANDLE)
Gives its SocketReader object a chance to fetch data from the socket, and if there is a finished message available, it will pass it in a call to ServerSocketReaderTask::put().
NOTE: the return of 1 when successful tells the ACE_Reactor object to revisit this handler before doing another ::select call. Override of ACE_Event_Handler method.
Parameters
device socket connection (ignored)
Returns
0 or 1 if successful, -1 otherwise
Definition at line 80 of file TCPInputHandler.cc.
References SideCar::IO::IOTask::acquireExternalMessage(), SideCar::IO::StreamReader::fetchInput(), SideCar::IO::Reader::getMessage(), SideCar::IO::Reader::isMessageAvailable(), Log(), LOGDEBUG, LOGERROR, LOGINFO, and SideCar::IO::Task::setError().
Logger::Log & TCPInputHandler::Log () static
Log device for objects of this type.
Returns
log device
Definition at line 12 of file TCPInputHandler.cc.
References Logger::Log::Find().
Referenced by close(), handle_close(), handle_input(), and open().
int TCPInputHandler::open (void * arg = 0)
Sets up the SocketReader instance to use the socket connection to the client.
Override of ACE_Task method.
Parameters
arg ACE_Connector object that did the connecting
Returns
-f if failed
Definition at line 20 of file TCPInputHandler.cc.
References SideCar::IO::ReaderDevices::TCPSocket::getDevice(), Log(), LOGDEBUG, LOGERROR, and LOGINFO.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/TCPInputHandler.h
/Users/howes/src/sidecar/IO/TCPInputHandler.cc