SideCar: SideCar::GUI::TCPMessageWriter Class Reference
SideCar::GUI::TCPMessageWriter Class Reference
Qt message writer that uses QTcpServer/QTcpSocket to write data over a TCP connection.
#include </Users/howes/src/sidecar/GUI/Writers.h>
Public Member Functions
bool start ()
Start the QTcpServer and publish connection information.
bool writeMessage (const IO::MessageManager &mgr)
Implementation of the MessageWriter API.
bool writeEncoded (ACE_Message_Block *data)
bool stop ()
Stop the publisher and QTcpServer.
Public Member Functions inherited from SideCar::GUI::MessageWriter
void setServiceName (const QString &serviceName)
Set the service name to publish under.
const QString & getServiceName () const
Obtain the service name being published.
const QString & getServiceAddress () const
Obtain the multicast address to use for sending out data.
uint16_t getPort () const
Obtain the socket port number used by the publisher.
bool isPublished () const
Determine if the MessageWriter is currently publishing its connection info.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device to use for TCPMessageWriter objects.
static TCPMessageWriter * Make (const QString &serviceName, const std::string &subType)
Factory method used to creates a new, initialized TCPMessageWriter.
Static Public Member Functions inherited from SideCar::GUI::MessageWriter
static Logger::Log & Log ()
Obtain the Log device to use for MessageWriter objects.
Static Public Member Functions inherited from SideCar::IO::ZeroconfTypes::TZCType< id >
static const char * GetZeroconfType ()
Obtain the configured Zeroconf type for objects derived from this class.
static const char * GetTwinZeroconfType ()
Obtain the "twin" Zeroconf type for objects derived from this class.
static std::string MakeZeroconfType (const std::string &subType)
Construct a valid SideCar Zeroconf type string for a given subtype.
static std::string MakeTwinZeroconfType (const std::string &subType)
Construct the twin SideCar Zeroconf type string for a given subtype.
Static Public Member Functions inherited from SideCar::IO::ZeroconfRegistry
static const char * GetType (ID id)
Obtain the Zeroconf type string for a given ID.
static ID GetTwin (ID id)
Locate the twin of this ID.
static std::string MakeZeroconfType (const char *type, const std::string &subType)
Construct a valid SideCar Zeroconf type string for a type and a subtype.
Additional Inherited Members
Public Types inherited from SideCar::IO::ZeroconfRegistry
enum ID {
kPublisher = 0, kSubscriber, kRunnerStatusCollector, kRunnerStatusEmitter,
kStateEmitter, kStateCollector, kRunnerRemoteController, kNumTypes
}
Defined Zeroconf types.
Signals inherited from SideCar::GUI::MessageWriter
void published (const QString &serviceName, const QString &serviceAddress, uint16_t port)
Notification sent out when the MessageWriter successfully publishes its connection information.
void failure ()
Notification sent out when the MessageWriter encounters a failure.
void subscriberCountChanged (size_t count)
Notification sent out when the number of subscribers to the publisher changes.
Protected Member Functions inherited from SideCar::GUI::MessageWriter
MessageWriter (const QString &serviceName, const std::string &type, const std::string &transport, const QString &serviceAddress)
Constructor.
void setPort (uint16_t port)
Set the socket port assigned to the publisher by the OS.
virtual void setPublishedServiceName (const QString &serviceName)
Update the service name to the one created by Zeroconf due to a name collision.
boost::shared_ptr< Zeroconf::Publisher > getPublisher () const
Obtain the Zeroconf::Publisher object used to broadcast publisher connection information.
Detailed Description
Qt message writer that uses QTcpServer/QTcpSocket to write data over a TCP connection.
Acts as a garden-variety TCP server, accepting socket connections, and sending data over each connection.
NOTE: this is a simplistic implementation that does not scale very well. For publishers serving a large number of connections, one should use UDPMessageWriter, which uses multicasting to emit messages.
Uses QTcpServer to manage socket connections. Each connection to a subscriber has its own QTcpSocket instance.
Definition at line 231 of file Writers.h.
Member Function Documentation
Logger::Log & TCPMessageWriter::Log () static
Obtain the log device to use for TCPMessageWriter objects.
Returns
Log device
Definition at line 148 of file Writers.cc.
References Logger::Log::Find().
TCPMessageWriter * TCPMessageWriter::Make (const QString & serviceName, const std::string & subType) static
Factory method used to creates a new, initialized TCPMessageWriter.
Parameters
serviceName name to publish under
subType message type of the messages to write
Returns
new TCPMessageWriter if successful, NULL otherwise
Definition at line 155 of file Writers.cc.
References SideCar::GUI::MessageWriter::Log(), LOGERROR, LOGINFO, and start().
Referenced by SideCar::GUI::PRIEmitter::MainWindow::MainWindow().
bool TCPMessageWriter::start () virtual
Start the QTcpServer and publish connection information.
Returns
true if successful
Reimplemented from SideCar::GUI::MessageWriter.
Definition at line 176 of file Writers.cc.
References SideCar::GUI::MessageWriter::Log(), LOGERROR, LOGINFO, and SideCar::GUI::MessageWriter::setPort().
Referenced by Make().
bool TCPMessageWriter::stop () virtual
Stop the publisher and QTcpServer.
Closes all active client QTcpSocket connections.
Returns
true if successful
Reimplemented from SideCar::GUI::MessageWriter.
Definition at line 197 of file Writers.cc.
References SideCar::GUI::MessageWriter::Log(), LOGDEBUG, LOGINFO, and SideCar::GUI::MessageWriter::subscriberCountChanged().
bool TCPMessageWriter::writeMessage (const IO::MessageManager & mgr) virtual
Implementation of the MessageWriter API.
Sends the message held by the given IO::MessageManager to each TCP connection.
Parameters
mgr container holding the message to write
Returns
true if successful
Implements SideCar::GUI::MessageWriter.
Definition at line 252 of file Writers.cc.
References SideCar::GUI::MessageWriter::Log(), LOGINFO, LOGWARNING, SideCar::IO::Writer::write(), and SideCar::IO::Writer::writeEncoded().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Writers.h
/Users/howes/src/sidecar/GUI/Writers.cc