SideCar: SideCar::GUI::Master::TaskItem Class Reference
SideCar::GUI::Master::TaskItem Class Reference
TreeViewItem that represents an IO::Task object of an IO::Stream.
#include </Users/howes/src/sidecar/GUI/Master/TaskItem.h>
Public Member Functions
TaskItem (const IO::TaskStatus &status, StreamItem *parent)
Constructor.
void updateCollectionStats (CollectionStats &stats) const
Prototype for method to update a CollectionStats object with statistics provided by a TreeViewItem derivative.
QVariant getNameDataValue (int role) const
Obtain the data value for the ServicesModel::kName column, which displays the name of the TreeViewItem.
QVariant getStateDataValue (int role) const
Obtain the data value for the ServicesModel::kState column, which displays the processing state of the TreeViewItem.
QVariant getPendingCountValue (int role) const
Obtain the data value for the ServicesModel::kPending column, which displays the pending queue size of this item.
QVariant getRateDataValue (int role) const
Obtain the data value for the fourth column, which displays the message processing rate of the TaskItem.
QVariant getErrorDataValue (int role) const
Obtain the data value for the ServicesModel::kError column, which displays any error text from the TreeViewItem.
QVariant getInfoDataValue (int role) const
Obtain the data value for the ServicesModel::kInfo column, which displays miscellaneous informational data of the TreeViewItem.
IO::ProcessingState::Value getProcessingState () const
const QString & getError () const
const QString & getConnectionInfo () const
int getMessageCount () const
Obtain the message count from the last status entry.
int getByteRate () const
Obtain the byte rate from the last status container.
int getMessageRate () const
Obtain the message rate from the last status container.
virtual int getDropCount () const
virtual int getDupeCount () const
int getPendingQueueCount () const
bool isUsingData () const
StreamItem * getParent () const
void formatChangedParameters (const XmlRpc::XmlRpcValue &definitions, QStringList &changes) const
QString getParameterChangedHeading () const
Public Member Functions inherited from SideCar::GUI::Master::TreeViewItem
~TreeViewItem ()
Destructor.
virtual void initialize ()
Initialize this object's internal state.
const IO::StatusBase & getStatus () const
Obtain the latest IO::StatusBase object received for this object.
bool update (const IO::StatusBase &status)
Update the TreeViewItem held status.
bool isOK () const
bool isProcessing () const
Determine if the object is in a 'processing' state: auto-diagnostic, calibration, or run.
ActiveState getActiveState () const
Obtain the current ActiveState value for this object.
QVariant getData (int column, int role) const
Obtain the data point to use for a specific role in a given column.
virtual QVariant getHostDataValue (int role) const
Obtain the data value for the ServicesModel::kHost column, which displays the host name of the machine where the object is running.
virtual QVariant getRecordingDataValue (int role) const
Obtain the data value for the ServicesModel::kRecording column, which displays the recording state of the TreeViewItem.
virtual QColor getForegroundColor (int column) const
Obtain the foreground color to use for the contents of a given column.
virtual QFont getFont (int column) const
Obtain the font to use for the contents of a given column.
virtual int getAlignment (int columnt) const
Obtain the alignment (horizontal and vertical) to use for the contents of a given column.
virtual bool canEdit () const
Determine if the TreeViewItem supports editing of runtime parameter values.
virtual bool canExpand () const
Determine if the TreeViewItem is expandable.
const QString & getName () const
Obtain the object's name.
const QString & getFullName () const
Get the full name of the item.
void insertChild (int row, TreeViewItem *child)
Insert a child, renumbering the indices of all children after it.
void appendChild (TreeViewItem *child)
Add a child.
void removeChild (int index)
Remove the child at a given index.
TreeViewItem * getChild (int index) const
Obtain the child associated with a given index value.
int getNumChildren () const
Obtain the number of children.
int getIndex () const
Obtain the index of this object in the context of our parent's children array.
TreeViewItem * getParent () const
Obtain the parent of this TreeViewItem object.
int getParentIndex () const
Obtain the index value of the parent object (equivalent to getParent()->getIndex().
ChildrenIterator getChildrenIterator () const
Obtain a Java-style iterator for the children array.
bool isExpanded () const
Determine if the object is expanded.
void setExpanded (bool expanded)
Change the expansion attribute of the object.
int getInsertionPoint (const QString &name) const
Obtain the row where the given name could be inserted without disturbing the ordering of the existing rows.
virtual bool isFiltered (const QString &filter) const
Determine if this item contains the given filter string.
Static Public Member Functions
static Logger::Log & Log ()
Static Public Member Functions inherited from SideCar::GUI::Master::TreeViewItem
static QVariant GetRecordingDataValue (bool canRecord, int role)
Utility class method that returns an appropriate value for the recording state depicted by the two arguments.
static QColor GetTextColor ()
Class method that returns the default (black) text color for all Qt::Foreground roles.
static QColor GetOKColor ()
Class method that returns the OK text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetWarningColor ()
Class method that returns the 'warning text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetFailureColor ()
Class method that returns the 'failure' text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetRecordingColor ()
Class method that returns the text color to use to show when a task is currently recording.
static QFont GetTextFont ()
Obtain the normal font to use for displayed text.
Protected Member Functions
void beforeUpdate ()
Hook invoked before a status update.
void afterUpdate ()
Hook invoked after a status update.
virtual void fillCollectionStats (CollectionStats &stats) const
Protected Member Functions inherited from SideCar::GUI::Master::TreeViewItem
TreeViewItem ()
Constructor for the RootItem object (which has no parent).
TreeViewItem (const IO::StatusBase &status, TreeViewItem *parent)
Constructor for all derived classes except RootItem.
void setName (const QString &name)
void setOK (bool ok)
void setProcessing (bool processing)
void setProcessingState (IO::ProcessingState::Value state)
void setActiveState (ActiveState activeState)
template<typename T >
const T & getStatusT () const
virtual void childAdded (TreeViewItem *child)
virtual void childRemoved (TreeViewItem *child)
Additional Inherited Members
Public Types inherited from SideCar::GUI::Master::TreeViewItem
enum ActiveState { kIdle, kPartial, kActive, kNotUsingData }
using Children = QList< TreeViewItem * >
using ChildrenIterator = QListIterator< TreeViewItem * >
Detailed Description
TreeViewItem that represents an IO::Task object of an IO::Stream.
Definition at line 17 of file TaskItem.h.
Constructor & Destructor Documentation
TaskItem::TaskItem (const IO::TaskStatus & status, StreamItem * parent)
Constructor.
Parameters
status initial status value of the item
parent parent node for this item
Definition at line 22 of file TaskItem.cc.
Member Function Documentation
void TaskItem::afterUpdate () protected virtual
Hook invoked after a status update.
This implementation does nothing.
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Definition at line 123 of file TaskItem.cc.
References SideCar::GUI::Master::TreeViewItem::afterUpdate(), getMessageCount(), SideCar::IO::TaskStatus::getProcessingState(), SideCar::GUI::Master::TreeViewItem::kActive, SideCar::GUI::Master::TreeViewItem::kIdle, and SideCar::GUI::Master::TreeViewItem::kNotUsingData.
Referenced by SideCar::GUI::Master::ControllerItem::afterUpdate().
void TaskItem::beforeUpdate () protected virtual
Hook invoked before a status update.
This implementation does nothing.
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Definition at line 117 of file TaskItem.cc.
References SideCar::IO::TaskStatus::getMessageCount().
int SideCar::GUI::Master::TaskItem::getByteRate () const inline
Obtain the byte rate from the last status container.
Returns
byte rate
Definition at line 71 of file TaskItem.h.
Referenced by getRateDataValue().
QVariant TaskItem::getErrorDataValue (int role) const virtual
Obtain the data value for the ServicesModel::kError column, which displays any error text from the TreeViewItem.
Parameters
role the display role that determines the type of data to return
Returns
null QVariant
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Definition at line 97 of file TaskItem.cc.
References SideCar::GUI::Master::TreeViewItem::getErrorDataValue().
QVariant TaskItem::getInfoDataValue (int role) const virtual
Obtain the data value for the ServicesModel::kInfo column, which displays miscellaneous informational data of the TreeViewItem.
Parameters
role the display role that determines the type of data to return
Returns
null QVariant
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Definition at line 104 of file TaskItem.cc.
References SideCar::GUI::Master::TreeViewItem::getInfoDataValue(), and SideCar::GUI::Master::TreeViewItem::getParent().
Referenced by SideCar::GUI::Master::ControllerItem::getInfoDataValue().
int SideCar::GUI::Master::TaskItem::getMessageCount () const inline
Obtain the message count from the last status entry.
Returns
message count
Definition at line 65 of file TaskItem.h.
Referenced by afterUpdate(), and getRateDataValue().
int SideCar::GUI::Master::TaskItem::getMessageRate () const inline
Obtain the message rate from the last status container.
Returns
message rate
Definition at line 77 of file TaskItem.h.
Referenced by getRateDataValue(), and SideCar::GUI::Master::ControllerItem::getRateDataValue().
QVariant TaskItem::getNameDataValue (int role) const virtual
Obtain the data value for the ServicesModel::kName column, which displays the name of the TreeViewItem.
Parameters
role the display role that determines the type of data to return
Returns
object name if role is Qt::DisplayRole
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Definition at line 32 of file TaskItem.cc.
References SideCar::GUI::Master::TreeViewItem::getNameDataValue().
QVariant TaskItem::getPendingCountValue (int role) const virtual
Obtain the data value for the ServicesModel::kPending column, which displays the pending queue size of this item.
Parameters
role the display role that determines the type of data to return
Returns
null QVariant
null QVariant
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Definition at line 47 of file TaskItem.cc.
References SideCar::GUI::Master::TreeViewItem::getPendingCountValue().
Referenced by SideCar::GUI::Master::ControllerItem::getPendingCountValue().
QVariant TaskItem::getRateDataValue (int role) const virtual
Obtain the data value for the fourth column, which displays the message processing rate of the TaskItem.
Shows the current message count, message rate, and byte rate.
Parameters
role the display role that determines the type of data to return
Returns
returns count + rate information
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Definition at line 56 of file TaskItem.cc.
References getByteRate(), SideCar::GUI::Master::TreeViewItem::GetFailureColor(), getMessageCount(), getMessageRate(), and SideCar::GUI::Master::TreeViewItem::getRateDataValue().
Referenced by SideCar::GUI::Master::ControllerItem::getRateDataValue().
QVariant TaskItem::getStateDataValue (int role) const virtual
Obtain the data value for the ServicesModel::kState column, which displays the processing state of the TreeViewItem.
Parameters
role the display role that determines the type of data to return
Returns
processing state name if role is Qt::DisplayRole
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Definition at line 40 of file TaskItem.cc.
References SideCar::IO::ProcessingState::GetName().
void TaskItem::updateCollectionStats (CollectionStats & stats) const virtual
Prototype for method to update a CollectionStats object with statistics provided by a TreeViewItem derivative.
Derived classes must define.
Parameters
stats object to update
Implements SideCar::GUI::Master::TreeViewItem.
Definition at line 142 of file TaskItem.cc.
References SideCar::GUI::Master::TreeViewItem::getActiveState(), SideCar::GUI::Master::TreeViewItem::getName(), SideCar::GUI::Master::TreeViewItem::getParent(), SideCar::GUI::Master::TreeViewItem::kActive, SideCar::GUI::Master::CollectionStats::kActiveCount, SideCar::GUI::Master::CollectionStats::kDropCount, SideCar::GUI::Master::CollectionStats::kDupeCount, SideCar::GUI::Master::TreeViewItem::kIdle, SideCar::GUI::Master::CollectionStats::kIdleCount, SideCar::GUI::Master::CollectionStats::kLeafCount, SideCar::GUI::Master::TreeViewItem::kNotUsingData, SideCar::GUI::Master::CollectionStats::kNotUsingDataCount, SideCar::GUI::Master::CollectionStats::kOKCount, SideCar::GUI::Master::CollectionStats::kPendingQueueCount, and XmlRpc::XmlRpcValue::size().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/TaskItem.h
/Users/howes/src/sidecar/GUI/Master/TaskItem.cc