SideCar: SideCar::Algorithms::Algorithm Class Reference
SideCar::Algorithms::Algorithm Class Reference
Base class for all algorithm classes.
#include </Users/howes/src/sidecar/Algorithms/Algorithm.h>
Inherited by SideCar::Algorithms::ABTracker, SideCar::Algorithms::Alarmer, SideCar::Algorithms::BugCollector, SideCar::Algorithms::CFAR, SideCar::Algorithms::CIntegrate, SideCar::Algorithms::Clamp, SideCar::Algorithms::ClutterMap, SideCar::Algorithms::ComposeExtractions, SideCar::Algorithms::ComposeTracks, SideCar::Algorithms::CPIAlgorithm, SideCar::Algorithms::CPIMarker, SideCar::Algorithms::Decimator, SideCar::Algorithms::Delay, SideCar::Algorithms::Despeckle, SideCar::Algorithms::Difference, SideCar::Algorithms::DownConverter, SideCar::Algorithms::EdgeDetector, SideCar::Algorithms::Extract, SideCar::Algorithms::ExtractWithCentroiding, SideCar::Algorithms::FanIn, SideCar::Algorithms::FanOut, SideCar::Algorithms::Filter, SideCar::Algorithms::GeoFilter, SideCar::Algorithms::Inverter, SideCar::Algorithms::IQ2AmplitudePhase, SideCar::Algorithms::IQFilter, SideCar::Algorithms::LowPassFilter, SideCar::Algorithms::ManyInAlgorithm, SideCar::Algorithms::MofN, SideCar::Algorithms::MTI2, SideCar::Algorithms::NCIntegrate, SideCar::Algorithms::NOOP, SideCar::Algorithms::Offset, SideCar::Algorithms::OSCFAR, SideCar::Algorithms::PRISegmentation, SideCar::Algorithms::ProcessTracks, SideCar::Algorithms::RawPRI, SideCar::Algorithms::Recorder, SideCar::Algorithms::Router, SideCar::Algorithms::SandBox, SideCar::Algorithms::Scale, SideCar::Algorithms::ScanCorrelator, SideCar::Algorithms::SectorMask, SideCar::Algorithms::Segment2Extraction, SideCar::Algorithms::SegmentConnector, SideCar::Algorithms::SegmentSplitter, SideCar::Algorithms::SegmentStats, SideCar::Algorithms::ShiftBins, SideCar::Algorithms::SimpleNOOP, SideCar::Algorithms::SlidingOp, SideCar::Algorithms::Sum, SideCar::Algorithms::SumNDiff, SideCar::Algorithms::Threshold, SideCar::Algorithms::TrackerReceive, SideCar::Algorithms::TrackerSend, SideCar::Algorithms::TrackInitiator, SideCar::Algorithms::TrackMaintainer, SideCar::Algorithms::Trimmer, SideCar::Algorithms::TSPI, SideCar::Algorithms::VideoInterpolation, SideCar::Algorithms::Volts2Power, and SideCar::Algorithms::WindowedMinMax.
Public Member Functions
Algorithm (Controller &controller, Logger::Log &log)
Constructor.
virtual ~Algorithm ()
Destructor.
Controller & getController () const
Obtain the Controller object managing the algorithm.
Logger::Log & getLog () const
Obtain the log device to use for by the algorithm for log messages.
const std::string & getName () const
Obtain the name of the algorithm.
bool registerParameter (const Parameter::Ref &parameter)
Add a configuration parameter to the runtime system.
bool unregisterParameter (const Parameter::Ref &parameter)
Remove a configuration parameter from the runtime system.
template<typename A , typename M >
void registerProcessor (boost::function< bool(A *, typename M::Ref)> proc)
Install a method to process a particular message type.
template<typename A , typename M >
void registerProcessor (const std::string &channelName, boost::function< bool(A *, typename M::Ref)> proc)
Same as above method, but allows user to pick the channel by name.
template<typename A , typename M >
void registerProcessor (size_t channelIndex, boost::function< bool(A *, typename M::Ref)> proc)
Same as above method, but allows user to pick the channel by index.
template<typename A >
void registerProcessor (const std::string &channelName, const Messages::MetaTypeInfo &metaTypeInfo, boost::function< bool(A *, typename Messages::Header::Ref)> proc)
template<typename A >
void registerProcessor (size_t channelIndex, const Messages::MetaTypeInfo &metaTypeInfo, boost::function< bool(A *, typename Messages::Header::Ref)> proc)
size_t addProcessor (const std::string &channelName, const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
size_t addProcessor (const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
size_t addProcessor (size_t index, const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
void removeProcessor (size_t index)
Remove a processor from a given channel.
size_t getOutputChannelIndex (const std::string &name) const
Obtain an output channel index with a given name.
bool send (const Messages::Header::Ref &msg, size_t channelIndex=0)
Submit a message object to the controller for sending out on a given data channel.
bool sendAsIs (const Messages::Header::Ref &msg, size_t channelIndex=0)
Hand a message to the controller for sending out on a given data channel.
virtual size_t getNumInfoSlots () const
Obtain the number of data slots found in the ControllerStatus XML array.
virtual void setInfoSlots (IO::StatusBase &status)
Obtain custom status information from an algorithm.
size_t getActiveChannelIndex () const
Obtain the index of the input channel that last received a message for the algorithm to process.
Static Public Member Functions
static void * FormatInfoValue (const QString &value)
Obtain a C-safe value for the given QString string.
static void * FormatInfoValue (const char *value)
Obtain a C-safe value for the given character string.
Protected Member Functions
void setAlarm (int secs)
This method can be used by an Algorithm to schedule a periodic alarm to go off for itself.
virtual bool startup ()
Hook called once after the DLL is loaded and before processing begins.
virtual bool reset ()
Hook called when the algorithm is transitioning from a stopped to a running state (one of Task::kAutoDiagnostic, Task::kCalibrate, or Task::kRun).
virtual bool clearStats ()
Hook called when the algorithm is commaned to clear any statistics.
virtual bool beginAutoDiag ()
Hook called when the algorithm is entering the Task::kAutoDiagnostic state.
virtual bool beginCalibration ()
Hook called when the algorithm is entering the Task::kCalibrate state.
virtual bool beginRun ()
Hook called when the algorithm is entering the Task::kRun state.
virtual bool stop ()
Hook called when the algorithm is entering the Task::kStop state.
virtual bool shutdown ()
Hook called when the processing system shuts down.
virtual void recordingStarted ()
Hook called when a recording has started.
virtual void recordingStopped ()
Hook called when a recording has stopped.
virtual void beginParameterChanges ()
Hook called just before algorithm runtime parameters are changed.
virtual void endParameterChanges ()
Hook called just after algorithm runtime parameters have been changed.
virtual void processAlarm ()
This method will get called whenever an alarm expires for this Algorithm.
Friends
class Controller
Detailed Description
Base class for all algorithm classes.
An algorithm exists on the system as a dynamically-loaded library (DLL). This abstraction allows the algorithms to run in a variety of different contexts, without the algorithm knowing or caring which one is in use.
Initialization
At a minimum, derived classes must define one or more process methods that accept a shared reference to a message object to perform the work defined by the algorithm. These process methods return a boolean value that indicates success (true) or failure (false). An algorithm may have more than one processor depending on the work it is doing and its data dependencies. Registration of the processors (using the registerProcessor() methods) should occur in the startup() method:
bool
Foo::startup()
{
registerProcessor<Foo,Messages::Video>("main", &NOOP::processMain);
registerProcessor<Foo,Messages::Video>("aux", &NOOP::processAux);
return true;
}
Algorithms that provide runtime parameters (see SideCar::Parameter) must also register them with the SideCar infrastructure so that they may respond to change requests via external XML-RPC messages. Again, this registration should be done in the startup() method:
bool
Foo::startup()
{
registerProcessor<Foo,Messages::Video>("main", &NOOP::processMain);
registerProcessor<Foo,Messages::Video>("aux", &NOOP::processAux);
return registerParameter(param1_) && registerParameter(param2_);
}
NOTE: the processor registration methods throw an exception whenever an error occurs, but the registerParameter() method only returns false on failure. Sorry about that.
For more registration examples, check out the documentation and source code for specific algorithms (eg. SideCar::Algorithms::NOOP).
Status Reporting
Algorithms can report status to external entities such as the Monitor program. Status information is contained in an XML-RPC container, which is filled in by the call Algorithm::getInfoData() method. The return value from this method should be a string value that identifies the source of the XML-RPC data. Usually, this should be the same name as the algorithm.
Definition at line 68 of file Algorithm.h.
Constructor & Destructor Documentation
Algorithm::Algorithm (Controller & controller, Logger::Log & log)
Constructor.
Parameters
controller the processor controller in use
log device to use for log messages for this processor
Definition at line 8 of file Algorithm.cc.
Member Function Documentation
size_t Algorithm::addProcessor (const std::string & channelName, const Messages::MetaTypeInfo & metaTypeInfo, Processor * processor)
Add a message processor for a channel.
Locates the channel with a given name.
Parameters
channelName name of the channel to locate
metaTypeInfo message type to process
processor method to install
Definition at line 56 of file Algorithm.cc.
References SideCar::IO::Task::getInputChannelIndex(), SideCar::Messages::MetaTypeInfo::getName(), and LOGINFO.
Referenced by addProcessor(), SideCar::Algorithms::DownConverter::startup(), and SideCar::Algorithms::TChannelBuffer< T >::TChannelBuffer().
size_t Algorithm::addProcessor (const Messages::MetaTypeInfo & metaTypeInfo, Processor * processor)
Add a message processor for a channel.
Locates the first channel with a given message type.
Parameters
metaTypeInfo message type to process
processor method to install
Definition at line 65 of file Algorithm.cc.
References addProcessor(), SideCar::Algorithms::Controller::getAlgorithmName(), SideCar::IO::Task::getInputChannel(), SideCar::Messages::MetaTypeInfo::getKey(), SideCar::Messages::MetaTypeInfo::getName(), SideCar::IO::Task::getNumInputChannels(), LOGINFO, and Logger::ProcLog::thrower().
size_t Algorithm::addProcessor (size_t index, const Messages::MetaTypeInfo & metaTypeInfo, Processor * processor)
Add a message processor for a channel.
Uses a specific channel obtained from Task::getInputChannel().
Parameters
index position of the channel to use
\param metaTypeInfo message type to process
\param processor method to install
Definition at line 20 of file Algorithm.cc.
References SideCar::IO::Task::getInputChannel(), SideCar::Messages::MetaTypeInfo::getKey(), SideCar::Messages::MetaTypeInfo::getName(), LOGDEBUG, LOGINFO, and Logger::ProcLog::thrower().
virtual bool SideCar::Algorithms::Algorithm::beginAutoDiag () inline protected virtual
Hook called when the algorithm is entering the Task::kAutoDiagnostic state.
Returns
true if successful
Definition at line 337 of file Algorithm.h.
virtual bool SideCar::Algorithms::Algorithm::beginCalibration () inline protected virtual
Hook called when the algorithm is entering the Task::kCalibrate state.
Returns
true if successful
Definition at line 343 of file Algorithm.h.
virtual bool SideCar::Algorithms::Algorithm::beginRun () inline protected virtual
Hook called when the algorithm is entering the Task::kRun state.
Returns
true if successful
Definition at line 349 of file Algorithm.h.
virtual bool SideCar::Algorithms::Algorithm::clearStats () inline protected virtual
Hook called when the algorithm is commaned to clear any statistics.
Returns
true if successful
Definition at line 331 of file Algorithm.h.
void * Algorithm::FormatInfoValue (const QString & value) static
Obtain a C-safe value for the given QString string.
If string is empty, returns NULL. Otherwise, allocates a char buffer and fills it with UTF8-encoded contents of the string.
Parameters
value string to encode
Returns
NULL or pointer to heap array holding UTF8-encoded string
Definition at line 169 of file Algorithm.cc.
Referenced by SideCar::Algorithms::BinaryOp::BinaryOp(), SideCar::Algorithms::GeoFilter::GeoFilter(), SideCar::Algorithms::BugCollector::process(), SideCar::Algorithms::CPIIntegrate::processCPI(), SideCar::Algorithms::EdgeDetector::reset(), SideCar::Algorithms::CIntegrate::reset(), SideCar::Algorithms::ClutterMap::saveMap(), SideCar::Algorithms::IQFilter::setInfoSlots(), SideCar::Algorithms::Clamp::setMaxValue(), SideCar::Algorithms::SpreadMofN::shutdown(), SideCar::Algorithms::RGBConverter::shutdown(), SideCar::Algorithms::Decimator::shutdown(), SideCar::Algorithms::CPIMarker::shutdown(), SideCar::Algorithms::ComposeTracks::shutdown(), SideCar::Algorithms::ProcessTracks::shutdown(), SideCar::Algorithms::ComposeExtractions::shutdown(), SideCar::Algorithms::Sum::shutdown(), SideCar::Algorithms::SumNDiff::shutdown(), SideCar::Algorithms::ABTracker::shutdown(), SideCar::Algorithms::Router::shutdown(), SideCar::Algorithms::Delay::shutdown(), SideCar::Algorithms::LowPassFilter::shutdown(), SideCar::Algorithms::CPISimpleOp::shutdown(), SideCar::Algorithms::MatchedFilter::shutdown(), SideCar::Algorithms::SimpleOp::SimpleOp(), SideCar::Algorithms::Trimmer::startup(), SideCar::Algorithms::ShiftBins::startup(), SideCar::Algorithms::OSCFAR::startup(), SideCar::Algorithms::DynamicThreshold::startup(), SideCar::Algorithms::WindowedMinMax::startup(), SideCar::Algorithms::SlidingOp::startup(), and SideCar::Algorithms::Summer::Summer().
void * Algorithm::FormatInfoValue (const char * value) static
Obtain a C-safe value for the given character string.
If string is empty, returns NULL. Otherwise, allocates a char buffer and fills it with contents of the string.
Parameters
value string to encode
Returns
NULL or pointer to heap array holding UTF8-encoded string
Definition at line 179 of file Algorithm.cc.
size_t SideCar::Algorithms::Algorithm::getActiveChannelIndex () const inline
Obtain the index of the input channel that last received a message for the algorithm to process.
This value is valid until the process() method returns.
Returns
channel index
Definition at line 303 of file Algorithm.h.
Referenced by SideCar::Algorithms::Router::shutdown().
Controller& SideCar::Algorithms::Algorithm::getController () const inline
Obtain the Controller object managing the algorithm.
Returns
Controller reference
Definition at line 106 of file Algorithm.h.
Referenced by SideCar::Algorithms::GeoFilter::GeoFilter(), SideCar::Algorithms::BugCollector::process(), SideCar::Algorithms::ManyInAlgorithm::processMessageReceived(), SideCar::Algorithms::MatchedFilter::reset(), SideCar::Algorithms::FanOut::shutdown(), SideCar::Algorithms::CPIAlgorithm::shutdown(), SideCar::Algorithms::CPISimpleOp::shutdown(), SideCar::Algorithms::MatchedFilter::shutdown(), SideCar::Algorithms::FanOut::startup(), SideCar::Algorithms::Recorder::startup(), SideCar::Algorithms::FanIn::startup(), SideCar::Algorithms::ShiftBins::startup(), SideCar::Algorithms::OSCFAR::startup(), SideCar::Algorithms::Delay::startup(), SideCar::Algorithms::Router::startup(), SideCar::Algorithms::CPIAlgorithm::startup(), SideCar::Algorithms::ManyInAlgorithm::startup(), SideCar::Algorithms::CPISimpleOp::startup(), and SideCar::Algorithms::Printer::startup().
Logger::Log& SideCar::Algorithms::Algorithm::getLog () const inline
Obtain the log device to use for by the algorithm for log messages.
Returns
reference to Log device
Definition at line 112 of file Algorithm.h.
Referenced by SideCar::Algorithms::BinaryOp::BinaryOp(), SideCar::Algorithms::BugCollectorUtils::BugPlotReader::close(), SideCar::Algorithms::DynamicThreshold::DynamicThreshold(), SideCar::Algorithms::GeoFilter::GeoFilter(), SideCar::Algorithms::BugCollectorUtils::BugPlotReader::handle_input(), SideCar::Algorithms::ClutterMap::loadMap(), SideCar::Algorithms::BugCollectorUtils::BugPlotReader::openAndInit(), SideCar::Algorithms::DownConverter::process(), SideCar::Algorithms::BugCollector::process(), SideCar::Algorithms::ComposeExtractions::processAlarm(), SideCar::Algorithms::ComposeTracks::processAlarm(), SideCar::Algorithms::TrackMaintainer::processAlarm(), SideCar::Algorithms::CPIIntegrate::processCPI(), SideCar::Algorithms::TrackInitiator::reset(), SideCar::Algorithms::Despeckle::reset(), SideCar::Algorithms::ScanCorrelator::reset(), SideCar::Algorithms::Extract::reset(), SideCar::Algorithms::EdgeDetector::reset(), SideCar::Algorithms::Filter::reset(), SideCar::Algorithms::MatchedFilter::reset(), SideCar::Algorithms::CIntegrate::reset(), SideCar::Algorithms::ClutterMap::reset(), SideCar::Algorithms::ClutterMap::saveMap(), SideCar::Algorithms::Clamp::setMaxValue(), SideCar::Algorithms::SpreadMofN::shutdown(), SideCar::Algorithms::Decimator::shutdown(), SideCar::Algorithms::RGBConverter::shutdown(), SideCar::Algorithms::CPIMarker::shutdown(), SideCar::Algorithms::ProcessTracks::shutdown(), SideCar::Algorithms::SectorMask::shutdown(), SideCar::Algorithms::Sum::shutdown(), SideCar::Algorithms::SumNDiff::shutdown(), SideCar::Algorithms::ABTracker::shutdown(), SideCar::Algorithms::Delay::shutdown(), SideCar::Algorithms::CPIAlgorithm::shutdown(), SideCar::Algorithms::TrackMaintainer::shutdown(), SideCar::Algorithms::LowPassFilter::shutdown(), SideCar::Algorithms::Filter::shutdown(), SideCar::Algorithms::CPISimpleOp::shutdown(), SideCar::Algorithms::MatchedFilter::shutdown(), SideCar::Algorithms::SimpleOp::SimpleOp(), SideCar::Algorithms::NOOP::startup(), SideCar::Algorithms::Offset::startup(), SideCar::Algorithms::Scale::startup(), SideCar::Algorithms::SimpleNOOP::startup(), SideCar::Algorithms::Volts2Power::startup(), SideCar::Algorithms::SandBox::startup(), SideCar::Algorithms::DownConverter::startup(), SideCar::Algorithms::OSCFAR::startup(), SideCar::Algorithms::Router::startup(), SideCar::Algorithms::RangeDopplerMap::startup(), SideCar::Algorithms::LowPassFilter::startup(), SideCar::Algorithms::WindowedMinMax::startup(), SideCar::Algorithms::DynamicThreshold::startup(), SideCar::Algorithms::SlidingOp::startup(), SideCar::Algorithms::Inverter::startup(), SideCar::Algorithms::ManyInAlgorithm::startup(), SideCar::Algorithms::CPISimpleOp::startup(), SideCar::Algorithms::Printer::startup(), SideCar::Algorithms::CIntegrate::startup(), SideCar::Algorithms::IQFilter::startup(), SideCar::Algorithms::ClutterMap::startup(), and SideCar::Algorithms::Summer::Summer().
const std::string& SideCar::Algorithms::Algorithm::getName () const inline
Obtain the name of the algorithm.
This is the name assigned in the XML configuration file, and may be different than the DLL name.
Returns
Definition at line 119 of file Algorithm.h.
Referenced by SideCar::Algorithms::BinaryOp::BinaryOp(), SideCar::Algorithms::ABTrackerUtils::Track::emitPosition(), SideCar::Algorithms::ClutterMap::loadMap(), SideCar::Algorithms::DownConverter::process(), SideCar::Algorithms::CPIIntegrate::processCPI(), SideCar::Algorithms::Despeckle::reset(), SideCar::Algorithms::Difference::reset(), SideCar::Algorithms::Filter::reset(), SideCar::Algorithms::MatchedFilter::reset(), SideCar::Algorithms::ClutterMap::reset(), SideCar::Algorithms::SpreadMofN::shutdown(), SideCar::Algorithms::RGBConverter::shutdown(), SideCar::Algorithms::Delay::shutdown(), SideCar::Algorithms::CPISimpleOp::shutdown(), SideCar::Algorithms::MatchedFilter::shutdown(), SideCar::Algorithms::SimpleOp::SimpleOp(), SideCar::Algorithms::NOOP::startup(), SideCar::Algorithms::Offset::startup(), SideCar::Algorithms::Scale::startup(), SideCar::Algorithms::SimpleNOOP::startup(), SideCar::Algorithms::SandBox::startup(), SideCar::Algorithms::Volts2Power::startup(), SideCar::Algorithms::Trimmer::startup(), SideCar::Algorithms::OSCFAR::startup(), SideCar::Algorithms::RangeDopplerMap::startup(), SideCar::Algorithms::ManyInAlgorithm::startup(), SideCar::Algorithms::IQFilter::startup(), and SideCar::Algorithms::Summer::Summer().
virtual size_t SideCar::Algorithms::Algorithm::getNumInfoSlots () const inline virtual
Obtain the number of data slots found in the ControllerStatus XML array.
Any custom Algorithm slots will appear after the last defined ControllerStatus slot. NOTE: implementations must be thread-safe, since this routine will execute in the alorithm's StatusEmitter thread.
Returns
ControllerStats::kNumSlots
Reimplemented in SideCar::Algorithms::ManyInAlgorithm, SideCar::Algorithms::ClutterMap, SideCar::Algorithms::IQFilter, and SideCar::Algorithms::CPIAlgorithm.
Definition at line 287 of file Algorithm.h.
size_t SideCar::Algorithms::Algorithm::getOutputChannelIndex (const std::string & name) const inline
Obtain an output channel index with a given name.
NOTE: throws an exception if the name is not found.
Parameters
name the name to look for
Returns
the index found
Definition at line 248 of file Algorithm.h.
Referenced by SideCar::Algorithms::SandBox::startup().
virtual void SideCar::Algorithms::Algorithm::processAlarm () inline protected virtual
This method will get called whenever an alarm expires for this Algorithm.
Derived classes can override this method. If not, it's a no-op.
Reimplemented in SideCar::Algorithms::TrackMaintainer, SideCar::Algorithms::ComposeTracks, SideCar::Algorithms::ComposeExtractions, and SideCar::Algorithms::Alarmer.
Definition at line 381 of file Algorithm.h.
virtual void SideCar::Algorithms::Algorithm::recordingStarted () inline protected virtual
Hook called when a recording has started.
Default method does nothing.
Definition at line 364 of file Algorithm.h.
virtual void SideCar::Algorithms::Algorithm::recordingStopped () inline protected virtual
Hook called when a recording has stopped.
Default method does nothing.
Definition at line 368 of file Algorithm.h.
bool SideCar::Algorithms::Algorithm::registerParameter (const Parameter::Ref & parameter) inline
Add a configuration parameter to the runtime system.
A parameter value may change during runtime via external messages to the processing module.
Parameters
parameter object to add
Returns
true if successful
Definition at line 128 of file Algorithm.h.
Referenced by SideCar::Algorithms::BinaryOp::BinaryOp(), SideCar::Algorithms::GeoFilter::GeoFilter(), SideCar::Algorithms::ChannelBuffer::makeEnabledParameter(), SideCar::Algorithms::SimpleOp::SimpleOp(), SideCar::Algorithms::Offset::startup(), SideCar::Algorithms::Scale::startup(), SideCar::Algorithms::SandBox::startup(), SideCar::Algorithms::MTI2::startup(), SideCar::Algorithms::PRISegmentation::startup(), SideCar::Algorithms::CPIIntegrate::startup(), SideCar::Algorithms::SpreadMofN::startup(), SideCar::Algorithms::Alarmer::startup(), SideCar::Algorithms::RGBConverter::startup(), SideCar::Algorithms::IQ2AmplitudePhase::startup(), SideCar::Algorithms::TrackInitiator::startup(), SideCar::Algorithms::Decimator::startup(), SideCar::Algorithms::Despeckle::startup(), SideCar::Algorithms::Difference::startup(), SideCar::Algorithms::ScanCorrelator::startup(), SideCar::Algorithms::Threshold::startup(), SideCar::Algorithms::CPIMarker::startup(), SideCar::Algorithms::ComposeExtractions::startup(), SideCar::Algorithms::ProcessTracks::startup(), SideCar::Algorithms::ComposeTracks::startup(), SideCar::Algorithms::ShiftBins::startup(), SideCar::Algorithms::Trimmer::startup(), SideCar::Algorithms::Clamp::startup(), SideCar::Algorithms::DownConverter::startup(), SideCar::Algorithms::SectorMask::startup(), SideCar::Algorithms::Sum::startup(), SideCar::Algorithms::OSCFAR::startup(), SideCar::Algorithms::SumNDiff::startup(), SideCar::Algorithms::ManyInCPIAlgorithm::startup(), SideCar::Algorithms::Delay::startup(), SideCar::Algorithms::ABTracker::startup(), SideCar::Algorithms::Router::startup(), SideCar::Algorithms::CPIAlgorithm::startup(), SideCar::Algorithms::Segment2Extraction::startup(), SideCar::Algorithms::TrackMaintainer::startup(), SideCar::Algorithms::BugCollector::startup(), SideCar::Algorithms::EdgeDetector::startup(), SideCar::Algorithms::LowPassFilter::startup(), SideCar::Algorithms::DynamicThreshold::startup(), SideCar::Algorithms::WindowedMinMax::startup(), SideCar::Algorithms::SlidingOp::startup(), SideCar::Algorithms::MofN::startup(), SideCar::Algorithms::Filter::startup(), SideCar::Algorithms::Inverter::startup(), SideCar::Algorithms::NCIntegrate::startup(), SideCar::Algorithms::ManyInAlgorithm::startup(), SideCar::Algorithms::CPISimpleOp::startup(), SideCar::Algorithms::MatchedFilter::startup(), SideCar::Algorithms::SegmentStats::startup(), SideCar::Algorithms::Printer::startup(), SideCar::Algorithms::CIntegrate::startup(), SideCar::Algorithms::IQFilter::startup(), and SideCar::Algorithms::ClutterMap::startup().
template<typename A , typename M > void SideCar::Algorithms::Algorithm::registerProcessor (boost::function< bool(A *, typename M::Ref)> proc) inline
Install a method to process a particular message type.
Used by derived classes to install message processing methods. The two template parameters are
A – name of the class derived from Algorithm that is registering
M – name of the message class to register
Accepts as its sole argument a pointer to a method which will be invoked by the registered processor. The method must take as its only parameter a boost::shared_ptr<T> object and return a boolean value to indicate success (true) or failure (false).
All registrations shall appear in the startup() method. For example, to register a Video message processor in a class called Foo, the following would suffice:
bool
Foo::startup() {
registerProcessor<Foo,Messages::Video>(&Foo::process);
return true;
}
bool
Foo::process(const Messages::Video::Ref& msg)
{
...
}
Parameters
proc pointer to a method to invoke to process a message
Definition at line 169 of file Algorithm.h.
template<typename A , typename M > void SideCar::Algorithms::Algorithm::registerProcessor (const std::string & channelName, boost::function< bool(A *, typename M::Ref)> proc) inline
Same as above method, but allows user to pick the channel by name.
Useful when there are multiple inputs with the same message type.
Parameters
channelName name of the input channel to use
proc pointer to a method to invoke to process a message
Definition at line 180 of file Algorithm.h.
template<typename A , typename M > void SideCar::Algorithms::Algorithm::registerProcessor (size_t channelIndex, boost::function< bool(A *, typename M::Ref)> proc) inline
Same as above method, but allows user to pick the channel by index.
Useful when there are multiple inputs with the same message type.
Parameters
channelIndex index of the input channel to use
proc pointer to a method to invoke to process a message
Definition at line 191 of file Algorithm.h.
void Algorithm::removeProcessor (size_t index)
Remove a processor from a given channel.
NOTE: any future messages received on a channel with no registered processor will cause the Controller hosting to algorithm to abort.
Parameters
index position of the channel to use (not verified)
Definition at line 104 of file Algorithm.cc.
References LOGTIN, LOGTOUT, and Logger::ProcLog::thrower().
virtual bool SideCar::Algorithms::Algorithm::reset () inline protected virtual
Hook called when the algorithm is transitioning from a stopped to a running state (one of Task::kAutoDiagnostic, Task::kCalibrate, or Task::kRun).
Derived classes should override this method and perform whatever actions necessary to return the algorithm to a known state.
Returns
true if successful
Reimplemented in SideCar::Algorithms::ManyInAlgorithm, SideCar::Algorithms::ClutterMap, SideCar::Algorithms::CIntegrate, SideCar::Algorithms::MatchedFilter, SideCar::Algorithms::MofN, SideCar::Algorithms::Filter, SideCar::Algorithms::NCIntegrate, SideCar::Algorithms::SegmentSplitter, SideCar::Algorithms::VideoInterpolation, SideCar::Algorithms::TrackMaintainer, SideCar::Algorithms::CPIIntegrate, SideCar::Algorithms::EdgeDetector, SideCar::Algorithms::Extract, SideCar::Algorithms::Despeckle, SideCar::Algorithms::Difference, SideCar::Algorithms::ScanCorrelator, SideCar::Algorithms::TrackInitiator, SideCar::Algorithms::MTI2, SideCar::Algorithms::PRISegmentation, SideCar::Algorithms::CFAR, and SideCar::Algorithms::SegmentConnector.
Definition at line 325 of file Algorithm.h.
Referenced by SideCar::Algorithms::OSCFAR::OSCFAR(), SideCar::Algorithms::SegmentConnector::reset(), SideCar::Algorithms::TrackInitiator::reset(), SideCar::Algorithms::EdgeDetector::reset(), SideCar::Algorithms::TrackMaintainer::reset(), and SideCar::Algorithms::ManyInAlgorithm::reset().
bool Algorithm::send (const Messages::Header::Ref & msg, size_t channelIndex = 0)
Submit a message object to the controller for sending out on a given data channel.
Assigns a unique sequence number to the message.
NOTE: once passed to the send() method, the algorithm must not change the message since other threads will have access to it.
WARNING: this is not thread-safe; a multi-threaded algorithm must not call send() simultaneously from multiple threads.
Parameters
msg object to send
Returns
true if successful, false otherwise
Definition at line 129 of file Algorithm.cc.
References SideCar::IO::Task::getNumOutputChannels(), LOGDEBUG, LOGTIN, and LOGTOUT.
Referenced by SideCar::Algorithms::BinaryOp::BinaryOp(), SideCar::Algorithms::ABTrackerUtils::Track::emitPosition(), SideCar::Algorithms::GeoFilter::GeoFilter(), SideCar::Algorithms::DownConverter::process(), SideCar::Algorithms::BugCollector::process(), SideCar::Algorithms::ComposeExtractions::processAlarm(), SideCar::Algorithms::ComposeTracks::processAlarm(), SideCar::Algorithms::CPIIntegrate::processCPI(), SideCar::Algorithms::SegmentConnector::reset(), SideCar::Algorithms::PRISegmentation::reset(), SideCar::Algorithms::TrackInitiator::reset(), SideCar::Algorithms::Difference::reset(), SideCar::Algorithms::ScanCorrelator::reset(), SideCar::Algorithms::Despeckle::reset(), SideCar::Algorithms::Extract::reset(), SideCar::Algorithms::EdgeDetector::reset(), SideCar::Algorithms::Filter::reset(), SideCar::Algorithms::MatchedFilter::reset(), SideCar::Algorithms::ClutterMap::reset(), SideCar::Algorithms::Clamp::setMaxValue(), SideCar::Algorithms::FanOut::shutdown(), SideCar::Algorithms::Recorder::shutdown(), SideCar::Algorithms::FanIn::shutdown(), SideCar::Algorithms::SpreadMofN::shutdown(), SideCar::Algorithms::Alarmer::shutdown(), SideCar::Algorithms::RGBConverter::shutdown(), SideCar::Algorithms::Decimator::shutdown(), SideCar::Algorithms::CPIMarker::shutdown(), SideCar::Algorithms::ProcessTracks::shutdown(), SideCar::Algorithms::SectorMask::shutdown(), SideCar::Algorithms::Sum::shutdown(), SideCar::Algorithms::SumNDiff::shutdown(), SideCar::Algorithms::Router::shutdown(), SideCar::Algorithms::Delay::shutdown(), SideCar::Algorithms::TrackMaintainer::shutdown(), SideCar::Algorithms::LowPassFilter::shutdown(), SideCar::Algorithms::CPISimpleOp::shutdown(), SideCar::Algorithms::MatchedFilter::shutdown(), SideCar::Algorithms::SimpleOp::SimpleOp(), SideCar::Algorithms::TSPI::startup(), SideCar::Algorithms::RawPRI::startup(), SideCar::Algorithms::Offset::startup(), SideCar::Algorithms::Scale::startup(), SideCar::Algorithms::NOOP::startup(), SideCar::Algorithms::SimpleNOOP::startup(), SideCar::Algorithms::Volts2Power::startup(), SideCar::Algorithms::SandBox::startup(), SideCar::Algorithms::IQ2AmplitudePhase::startup(), SideCar::Algorithms::Trimmer::startup(), SideCar::Algorithms::OSCFAR::startup(), SideCar::Algorithms::Segment2Extraction::startup(), SideCar::Algorithms::TrackerReceive::startup(), SideCar::Algorithms::RangeDopplerMap::startup(), SideCar::Algorithms::WindowedMinMax::startup(), SideCar::Algorithms::DynamicThreshold::startup(), SideCar::Algorithms::SlidingOp::startup(), SideCar::Algorithms::Inverter::startup(), SideCar::Algorithms::SegmentStats::startup(), SideCar::Algorithms::CIntegrate::startup(), SideCar::Algorithms::IQFilter::startup(), and SideCar::Algorithms::Summer::Summer().
bool SideCar::Algorithms::Algorithm::sendAsIs (const Messages::Header::Ref & msg, size_t channelIndex = 0) inline
Hand a message to the controller for sending out on a given data channel.
Unlike send() above, this does not update the message sequence counter.
NOTE: once passed to the send() method, the algorithm must not change the message since other threads will have access to it.
NOTE: unlike send() above, this method is thread-safe.
\param msg object to send
\return true if successful, false otherwise
Definition at line 278 of file Algorithm.h.
virtual void SideCar::Algorithms::Algorithm::setInfoSlots (IO::StatusBase & status) inline virtual
Obtain custom status information from an algorithm.
All algorithms report generic status information to external entities via the ControllerStatus object. However, an algorithm with special reporting needs can provide custom data by appending to array whatever values it wants. NOTE: implementations must be thread-safe, since this routine will execute in the algorithm's StatusEmitter thread.
\param array container to hold the custom status information
Reimplemented in SideCar::Algorithms::ManyInAlgorithm, SideCar::Algorithms::ClutterMap, SideCar::Algorithms::IQFilter, and SideCar::Algorithms::CPIAlgorithm.
Definition at line 296 of file Algorithm.h.
Referenced by SideCar::Algorithms::CIntegrate::reset().
virtual bool SideCar::Algorithms::Algorithm::shutdown () inline protected virtual
Hook called when the processing system shuts down.
Derived classes should perform any necessary cleanup not automatically handled by object destruction.
Reimplemented in SideCar::Algorithms::MatchedFilter, SideCar::Algorithms::MatchedFilter, SideCar::Algorithms::CPISimpleOp, SideCar::Algorithms::ManyInAlgorithm, SideCar::Algorithms::Filter, SideCar::Algorithms::LowPassFilter, SideCar::Algorithms::TrackMaintainer, SideCar::Algorithms::CPIAlgorithm, SideCar::Algorithms::ABTracker, SideCar::Algorithms::Delay, SideCar::Algorithms::Router, SideCar::Algorithms::SumNDiff, SideCar::Algorithms::SectorMask, SideCar::Algorithms::Sum, SideCar::Algorithms::ComposeExtractions, SideCar::Algorithms::ComposeTracks, SideCar::Algorithms::ProcessTracks, SideCar::Algorithms::CPIMarker, SideCar::Algorithms::Decimator, SideCar::Algorithms::RGBConverter, SideCar::Algorithms::Alarmer, SideCar::Algorithms::CPIIntegrate, SideCar::Algorithms::SpreadMofN, SideCar::Algorithms::FanIn, SideCar::Algorithms::Recorder, and SideCar::Algorithms::FanOut.
Definition at line 360 of file Algorithm.h.
Referenced by SideCar::Algorithms::FanOut::shutdown(), SideCar::Algorithms::FanIn::shutdown(), SideCar::Algorithms::Recorder::shutdown(), SideCar::Algorithms::Alarmer::shutdown(), SideCar::Algorithms::Decimator::shutdown(), SideCar::Algorithms::CPIMarker::shutdown(), SideCar::Algorithms::ComposeTracks::shutdown(), SideCar::Algorithms::ComposeExtractions::shutdown(), SideCar::Algorithms::ProcessTracks::shutdown(), SideCar::Algorithms::Sum::shutdown(), SideCar::Algorithms::SectorMask::shutdown(), SideCar::Algorithms::SumNDiff::shutdown(), SideCar::Algorithms::ABTracker::shutdown(), SideCar::Algorithms::Delay::shutdown(), SideCar::Algorithms::Router::shutdown(), SideCar::Algorithms::CPIAlgorithm::shutdown(), SideCar::Algorithms::TrackMaintainer::shutdown(), SideCar::Algorithms::LowPassFilter::shutdown(), and SideCar::Algorithms::ManyInAlgorithm::shutdown().
virtual bool SideCar::Algorithms::Algorithm::startup () inline protected virtual
Hook called once after the DLL is loaded and before processing begins.
If a service fails to start up for any reason, it should return false. Any configurable parameters must be registered here. The processor's config file will be loaded after this routine returns.
Returns
true if successful.
Reimplemented in SideCar::Algorithms::ClutterMap, SideCar::Algorithms::IQFilter, SideCar::Algorithms::CIntegrate, SideCar::Algorithms::Printer, SideCar::Algorithms::SegmentStats, SideCar::Algorithms::MatchedFilter, SideCar::Algorithms::MatchedFilter, SideCar::Algorithms::CPISimpleOp, SideCar::Algorithms::Inverter, SideCar::Algorithms::ManyInAlgorithm, SideCar::Algorithms::NCIntegrate, SideCar::Algorithms::SegmentSplitter, SideCar::Algorithms::Filter, SideCar::Algorithms::MofN, SideCar::Algorithms::SlidingOp, SideCar::Algorithms::VideoInterpolation, SideCar::Algorithms::DynamicThreshold, SideCar::Algorithms::WindowedMinMax, SideCar::Algorithms::LowPassFilter, SideCar::Algorithms::RangeDopplerMap, SideCar::Algorithms::EdgeDetector, SideCar::Algorithms::BugCollector, SideCar::Algorithms::TrackerReceive, SideCar::Algorithms::TrackerSend, SideCar::Algorithms::TrackMaintainer, SideCar::Algorithms::CPIAlgorithm, SideCar::Algorithms::Segment2Extraction, SideCar::Algorithms::ABTracker, SideCar::Algorithms::Delay, SideCar::Algorithms::Router, SideCar::Algorithms::Extract, SideCar::Algorithms::ManyInCPIAlgorithm, SideCar::Algorithms::OSCFAR, SideCar::Algorithms::SumNDiff, SideCar::Algorithms::DownConverter, SideCar::Algorithms::SectorMask, SideCar::Algorithms::Sum, SideCar::Algorithms::Clamp, SideCar::Algorithms::ComposeExtractions, SideCar::Algorithms::ComposeTracks, SideCar::Algorithms::ProcessTracks, SideCar::Algorithms::ShiftBins, SideCar::Algorithms::Trimmer, SideCar::Algorithms::CPIMarker, SideCar::Algorithms::Despeckle, SideCar::Algorithms::Difference, SideCar::Algorithms::ScanCorrelator, SideCar::Algorithms::Threshold, SideCar::Algorithms::Decimator, SideCar::Algorithms::IQ2AmplitudePhase, SideCar::Algorithms::RGBConverter, SideCar::Algorithms::TrackInitiator, SideCar::Algorithms::Alarmer, SideCar::Algorithms::CPIIntegrate, SideCar::Algorithms::PRISegmentation, SideCar::Algorithms::SpreadMofN, SideCar::Algorithms::MTI2, SideCar::Algorithms::FanIn, SideCar::Algorithms::Recorder, SideCar::Algorithms::FanOut, SideCar::Algorithms::SandBox, SideCar::Algorithms::Volts2Power, SideCar::Algorithms::SimpleNOOP, SideCar::Algorithms::NOOP, SideCar::Algorithms::Offset, SideCar::Algorithms::Scale, SideCar::Algorithms::RawPRI, SideCar::Algorithms::TSPI, SideCar::Algorithms::ExtractWithCentroiding, SideCar::Algorithms::CFAR, and SideCar::Algorithms::SegmentConnector.
Definition at line 317 of file Algorithm.h.
Referenced by SideCar::Algorithms::GeoFilter::GeoFilter(), SideCar::Algorithms::CFAR::startup(), SideCar::Algorithms::SegmentConnector::startup(), SideCar::Algorithms::TSPI::startup(), SideCar::Algorithms::RawPRI::startup(), SideCar::Algorithms::Scale::startup(), SideCar::Algorithms::NOOP::startup(), SideCar::Algorithms::Offset::startup(), SideCar::Algorithms::SimpleNOOP::startup(), SideCar::Algorithms::SandBox::startup(), SideCar::Algorithms::FanOut::startup(), SideCar::Algorithms::FanIn::startup(), SideCar::Algorithms::Recorder::startup(), SideCar::Algorithms::MTI2::startup(), SideCar::Algorithms::PRISegmentation::startup(), SideCar::Algorithms::Alarmer::startup(), SideCar::Algorithms::TrackInitiator::startup(), SideCar::Algorithms::Decimator::startup(), SideCar::Algorithms::ScanCorrelator::startup(), SideCar::Algorithms::CPIMarker::startup(), SideCar::Algorithms::Threshold::startup(), SideCar::Algorithms::Despeckle::startup(), SideCar::Algorithms::ComposeExtractions::startup(), SideCar::Algorithms::ProcessTracks::startup(), SideCar::Algorithms::ComposeTracks::startup(), SideCar::Algorithms::ShiftBins::startup(), SideCar::Algorithms::Trimmer::startup(), SideCar::Algorithms::Clamp::startup(), SideCar::Algorithms::SectorMask::startup(), SideCar::Algorithms::Sum::startup(), SideCar::Algorithms::DownConverter::startup(), SideCar::Algorithms::SumNDiff::startup(), SideCar::Algorithms::OSCFAR::startup(), SideCar::Algorithms::Router::startup(), SideCar::Algorithms::ABTracker::startup(), SideCar::Algorithms::Delay::startup(), SideCar::Algorithms::Segment2Extraction::startup(), SideCar::Algorithms::CPIAlgorithm::startup(), SideCar::Algorithms::TrackMaintainer::startup(), SideCar::Algorithms::BugCollector::startup(), SideCar::Algorithms::EdgeDetector::startup(), SideCar::Algorithms::LowPassFilter::startup(), SideCar::Algorithms::WindowedMinMax::startup(), SideCar::Algorithms::SlidingOp::startup(), SideCar::Algorithms::MofN::startup(), SideCar::Algorithms::Filter::startup(), SideCar::Algorithms::Inverter::startup(), SideCar::Algorithms::ManyInAlgorithm::startup(), SideCar::Algorithms::NCIntegrate::startup(), SideCar::Algorithms::SegmentStats::startup(), SideCar::Algorithms::CIntegrate::startup(), SideCar::Algorithms::IQFilter::startup(), and SideCar::Algorithms::ClutterMap::startup().
virtual bool SideCar::Algorithms::Algorithm::stop () inline protected virtual
Hook called when the algorithm is entering the Task::kStop state.
Returns
true if successful
Reimplemented in SideCar::Algorithms::Recorder.
Definition at line 355 of file Algorithm.h.
Referenced by SideCar::Algorithms::TrackerSend::process(), SideCar::Algorithms::SegmentConnector::reset(), SideCar::Algorithms::ScanCorrelator::reset(), and SideCar::Algorithms::SegmentStats::startup().
bool SideCar::Algorithms::Algorithm::unregisterParameter (const Parameter::Ref & parameter) inline
Remove a configuration parameter from the runtime system.
Parameters
parameter object to remove
Returns
true if successful
Definition at line 136 of file Algorithm.h.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/Algorithm.h
/Users/howes/src/sidecar/Algorithms/Algorithm.cc