SideCar: SideCar::GUI::AScope::MainWindow Class Reference
SideCar::GUI::AScope::MainWindow Class Reference
Main window for the AScope application.
#include </Users/howes/src/sidecar/GUI/AScope/MainWindow.h>
Public Member Functions
MainWindow (History &history, int windowIndex, DisplayView *basis=0)
Constructor.
DisplayView * getActiveDisplayView () const
Obtain the active DisplayView for the window.
bool isDisplayViewSplit () const
Determine if the active display view is contained in a split view.
App * getApp () const
Obtain the App object singleton.
void saveToSettings (QSettings &settings)
Write out settings of the window and its contents to a given QSettings object.
void restoreFromSettings (QSettings &settings)
Restore settings for the window and its contents from a QSettings object.
void windowMenuAboutToShow (QList< QAction * > &actions)
Notification from the application's WindowManager that the 'Window' menu is about to show itself.
Public Member Functions inherited from SideCar::GUI::MainWindowBase
MainWindowBase ()
Constructor.
~MainWindowBase ()
Destructor.
virtual void initialize ()
Complete widget initialization.
QAction * getShowAction ()
Obtain the QAction object that toggles the tool window's visibility.
void setFixedSize ()
Configure the window so that the user may not resize it.
void setWindowTitle (const QString &windowTitle)
Shadow of QWidget::setWindowTitle() method.
QMenu * getWindowMenu () const
Obtain the 'Window' menu for this window.
QMenu * getToolBarMenu () const
Obtain the menu item that holds QAction items that control the visibility of toolbars registered with makeToolBar().
void setRestorable (bool state)
If a window is restorable, then the active WindowManager object will call its saveToSettings() method when the application quits.
bool isRestorable () const
Determine of the window is restorable.
void setVisibleAfterRestore (bool state)
If a window is restorable, this flag controls whether is it also initially visible to the user when it is restored.
bool isVisibleAfterRestore () const
Determine if the window should be visible when the application relaunches.
Static Public Member Functions
static Logger::Log & Log ()
Static Public Member Functions inherited from SideCar::GUI::MainWindowBase
static Logger::Log & Log ()
Log device for instances of this class.
static AppBase * getApp ()
Obtain the application object.
Additional Inherited Members
Public Slots inherited from SideCar::GUI::MainWindowBase
virtual void showAndRaise ()
Convenience slot method that shows our window, raises it to the top of the window layer, and then activates it.
Protected Member Functions inherited from SideCar::GUI::MainWindowBase
void setWindowMenu (QMenu *menu)
Install a QMenu object to use for the window's 'Window' menu.
void setContextMenu (QMenu *menu)
Install a QMenu object to use for the window's context menu (the menu that pops up when the user right-clicks (or CTRL+click on Mac) inside the window.
virtual void makeMenuBar ()
Create the window's QMenuBar object.
virtual void fillContextMenu (QMenu *menu)
Add QAction objects to the QMenu object used as a context menu.
virtual QAction * makeShowAction (int shortcut=0)
Create a new QAction that controls our visibility.
QAction * makeMenuAction (const QString &title, const char *slot=0, int shortcut=0)
Create a new QAction object, with this as the parent of the new object and the receiver of the action's triggered() signal.
virtual ToolBar * makeToolBar (const QString &title, Qt::ToolBarArea area=Qt::TopToolBarArea)
Create a new QToolBar object with a given title and initial position.
bool event (QEvent *event)
void contextMenuEvent (QContextMenuEvent *event)
Called in response to a user request to show a context menu.
void showEvent (QShowEvent *event)
Called just before the window is shown to the user.
void closeEvent (QCloseEvent *event)
Called when the widget has been closed, either programmatically or due to user action.
void changeEvent (QEvent *event)
Looks for QEvent::WindowStateChange events to detect when entering/exiting full-screen mode in order to hide/show the menu and status bars.
Detailed Description
Main window for the AScope application.
A main window hosts one or more DisplayView objects, and each DisplayView object has a Visualizer widget which does the plotting of the incoming data.
Definition at line 34 of file MainWindow.h.
Constructor & Destructor Documentation
MainWindow::MainWindow (History & history, int windowIndex, DisplayView * basis = 0)
Constructor.
Parameters
history application history buffer for all Video messages.
basis DisplayView to duplicate
Definition at line 38 of file MainWindow.cc.
References SideCar::GUI::Splittable::bottomRight(), getApp(), SideCar::GUI::Splittable::getSplitter(), SideCar::GUI::AScope::App::getViewEditor(), SideCar::GUI::OnOffSettingsBlock::isEnabled(), LOGINFO, SideCar::GUI::MainWindowBase::makeToolBar(), SideCar::GUI::AScope::DisplayView::restoreFromSettings(), SideCar::GUI::AScope::DisplayView::saveToSettings(), SideCar::GUI::Splittable::setContents(), SideCar::GUI::MainWindowBase::setWindowTitle(), SideCar::GUI::Splittable::split(), SideCar::GUI::Splittable::topLeft(), and SideCar::GUI::UpdateToggleAction().
Member Function Documentation
DisplayView* SideCar::GUI::AScope::MainWindow::getActiveDisplayView () const inline
Obtain the active DisplayView for the window.
When a window is raised to become the active window, it installs its active DisplayView to be the application's active DisplayView object.NOTE: this value should never be NULL.
Returns
DisplayView object
Definition at line 56 of file MainWindow.h.
Referenced by SideCar::GUI::AScope::App::addDisplayView().
App* SideCar::GUI::AScope::MainWindow::getApp () const inline
Obtain the App object singleton.
Returns
App object
Definition at line 68 of file MainWindow.h.
Referenced by MainWindow(), and restoreFromSettings().
bool MainWindow::isDisplayViewSplit () const
Determine if the active display view is contained in a split view.
Returns
true if so
Definition at line 464 of file MainWindow.cc.
References SideCar::GUI::Splittable::closeOtherView(), LOGINFO, and SideCar::GUI::UpdateToggleAction().
Referenced by restoreFromSettings().
void MainWindow::restoreFromSettings (QSettings & settings) virtual
Restore settings for the window and its contents from a QSettings object.
Parameters
settings container to use for setting values
Reimplemented from SideCar::GUI::MainWindowBase.
Definition at line 275 of file MainWindow.cc.
References SideCar::GUI::AScope::App::addDisplayView(), SideCar::GUI::AScope::DisplayView::duplicate(), getApp(), SideCar::GUI::AScope::DisplayView::getVisualizer(), isDisplayViewSplit(), LOGDEBUG, LOGINFO, SideCar::GUI::MainWindowBase::restoreFromSettings(), SideCar::GUI::AScope::DisplayView::setActiveDisplayView(), SideCar::GUI::Splittable::split(), and SideCar::GUI::UpdateToggleAction().
void MainWindow::saveToSettings (QSettings & settings) virtual
Write out settings of the window and its contents to a given QSettings object.
Parameters
settings container to store the setting values
Reimplemented from SideCar::GUI::MainWindowBase.
Definition at line 258 of file MainWindow.cc.
References LOGINFO, and SideCar::GUI::MainWindowBase::saveToSettings().
void MainWindow::windowMenuAboutToShow (QList< QAction * > & actions) virtual
Notification from the application's WindowManager that the 'Window' menu is about to show itself.
Derived classes should override this method if they need to update one or more QAction objects before the menu is displayed.
Parameters
actions list of QAction objects that make up the 'Window' menu.
Reimplemented from SideCar::GUI::MainWindowBase.
Definition at line 625 of file MainWindow.cc.
References SideCar::GUI::MainWindowBase::windowMenuAboutToShow().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/AScope/MainWindow.h
/Users/howes/src/sidecar/GUI/AScope/MainWindow.cc