SideCar: SideCar::Algorithms::Controller Class Reference
SideCar::Algorithms::Controller Class Reference
Controller for an Algorithm object found in a separate DLL.
#include </Users/howes/src/sidecar/Algorithms/Controller.h>
Data Structures
struct IncomingNotifier
Helper class for Controller objects that do not spawn a thread for algorithm message processing (see Controller::openAndInit()).
Public Types
using Ref = boost::shared_ptr< Controller >
Reference to self.
Public Types inherited from SideCar::IO::Task
enum { kDefaultThreadFlags = THR_NEW_LWP | THR_JOINABLE | THR_SCHED_DEFAULT | THR_INHERIT_SCHED }
Default flags to use for processing threads.
using Ref = boost::shared_ptr< Task >
Shared reference counter for Task objects.
using ParameterMap = std::map< std::string, size_t >
Container of Parameter object references.
using ParameterVector = std::vector< Parameter::Ref >
Public Member Functions
~Controller ()
Destructor.
bool openAndInit (const std::string &algorithmName, const std::string &serviceName="", Algorithm *algorithm=0, long threadFlags=kDefaultThreadFlags, long threadPriority=ACE_DEFAULT_THREAD_PRIORITY, bool threaded=true)
Open the controller.
int close (u_long flags=0) override
Shutdown the task.
const std::string & getAlgorithmName () const
Obtain the name of the algorithm DLL the controller will load and manage.
Algorithm * getAlgorithm () const
Fetch the loaded algorithm.
bool injectControlMessage (const IO::ControlMessage &msg)
Post a control message to the internal processing queue.
bool injectProcessingStateChange (IO::ProcessingState::Value state)
Post a control message to change the run state.
const char * getStatusClassName () const override
Override of IO::Task method.
size_t getStatusSize () const override
Obtain the number of slots in a ControllerStatus XML array filled in by the algorithm.
void fillStatus (IO::StatusBase &status) override
Override of IO::Task method.
void addProcessingStatSample (const Time::TimeStamp &delta)
Manually update the held ProcessingStats attribute with the given sample value.
void beginStatsProcessing ()
Start a timer for tracking algorithm processing time.
bool calculateUsingDataValue () const override
Override of IO::Task method.
void setStatsManaged (bool state)
Set whether the controller manages the ProcessingStats attribute.
void setXMLDefinition (const QDomNode &node)
Install the QDomNode of the XML parsed configuration file for the algorithm.
const QDomNode & getXMLDefinition () const
void setTimerSecs (int timerSecs)
Algorithms can use this method to set a periodic alarm every N seconds.
int getTimerSecs ()
Obtain the current alarm period.
Public Member Functions inherited from SideCar::IO::Task
Task (bool usingData=false)
Constructor.
~Task ()
Destructor.
const std::string & getTaskName () const
Obtain the name of the task.
void setTaskName (const std::string &taskName)
Set the task's internal name.
boost::weak_ptr< Stream > getStream () const
Obtain the stream to which this task belongs.
void setStream (const boost::shared_ptr< Stream > &stream)
Set the Stream object in which this Task object resides.
bool putInChannel (const Messages::Header::Ref &msg, size_t channel)
Place a given message into this Tasks's input processing queue.
int put (ACE_Message_Block *data, ACE_Time_Value *timeout=0) override
Override of ACE_Task method.
void setError (const std::string &text, bool force=false)
Record an error message.
const std::string & getError () const
Fetch the current error text.
void clearError ()
Clear the held error text.
bool hasError () const
Determine if the task has an error posted.
bool registerParameter (const Parameter::Ref &property)
Register a configurable parameter with the controller.
bool unregisterParameter (const Parameter::Ref &property)
Unregister a configurable parameter with the controller.
bool hasChangedParameters () const
Determine if this task has any parameter objects that have values that differ from their startup configuration.
ProcessingState::Value getProcessingState () const
Obtain the current processing state indicator.
bool isActive () const
Determine if the task is in a message processing state.
bool isInCalibrationState () const
Determine if the task is in the calibration state.
bool isInRunState () const
Determine if the task is in the run state.
bool isInStopState () const
Determine if the task is in the stop state.
const Stats & getInputStats (size_t channelIndex) const
Obtain a read-only reference to the message Stats object for this Task object.
void updateInputStats (size_t channelIndex, size_t byteCount, uint32_t sequenceCounter)
Update internal processing statistics using values from the latest message received by the task.
void setTaskIndex (size_t taskIndex)
Set the unique ID for this task.
size_t getTaskIndex () const
Obtain the unique ID for this task.
void addInputChannel (const Channel &channel)
Add an input channel to the task.
void addOutputChannel (const Channel &channel)
Add an input channel to the task.
const ChannelVector & getInputChannels () const
Obtain an existing input channel.
size_t getNumInputChannels () const
Obtain the number of input channels defined for this task.
const Channel & getInputChannel (size_t index)
Obtain a specific input channel defined for this task.
size_t getInputChannelIndex (const std::string &name)
Obtain the index of an input channel with a given name.
const ChannelVector & getOutputChannels () const
Obtain an existing output channel.
size_t getNumOutputChannels () const
Obtain the number of output channels defined for this task.
const Channel & getOutputChannel (size_t index)
Obtain a specific output channel defined for this task.
size_t getOutputChannelIndex (const std::string &name)
Obtain the index of an output channel with a given name.
void getCurrentParameters (XmlRpc::XmlRpcValue &value) const
Obtain an XML-RPC definition of the current runtime parameter values.
void getChangedParameters (XmlRpc::XmlRpcValue &value) const
Obtain an XML-RPC definition of all changed runtime parameter values, those with values different from that found in the configuration file or at initialization time.
bool isUsingData () const
Obtain the current usingData_ setting.
void updateUsingDataValue ()
Update this object's usingData_ value.
virtual void setUsingData (bool value)
Set a new usingData_ value.
void setThreadParams (const ThreadParams &threadParams)
Set the thread parameters that the task will use in its activateThreads() call.
const ThreadParams & getThreadParams () const
Obtain the current thread parameter settings.
bool activateThreads (int count)
Spawn count threads that will each run in the task's svc() method, which derived classes must define (see ACE_Task::svc()).
Static Public Member Functions
static Logger::Log & Log ()
Obtain log device for Controller objects to use.
static Ref Make ()
Factory method that creates a new Controller object.
Static Public Member Functions inherited from SideCar::IO::Task
static Logger::Log & Log ()
Obtain the log device for objects of this class.
Friends
class IncomingNotifier
class Algorithm
Additional Inherited Members
Protected Member Functions inherited from SideCar::IO::Task
bool enterProcessingState (ProcessingState::Value state)
Change the tasks processing state indicator.
bool enterLastProcessingState ()
Change to the last non-failure processing state.
virtual bool enterFailureState ()
Processor for the transition into the failure state.
void resetProcessedStats ()
Reset the processed counters.
bool processMessage (ACE_Message_Block *data)
Process a message, data or control.
virtual bool processControlMessage (ACE_Message_Block *data)
Process a control message.
virtual bool doProcessingStateChange (const ProcessingStateChangeRequest &request)
Respond to a processing state change meessage.
virtual bool doShutdownRequest ()
Respond to a SHUTDOOWN control meessage.
void setConnectionInfo (const std::string &connectionInfo)
Set the status text that represents the connection information for the task.
bool sendManaged (MessageManager &mgr, size_t channelIndex)
Detailed Description
Controller for an Algorithm object found in a separate DLL.
Isolates the algorithm from specifics regarding data source and destination. Since the Controller class derives from IO::Task, it can exist as part of an IO::Stream, which is usually how they appear in the SideCar system.
The openAndInit() method provides a Controller with the name of the algorithm to load. This routine invokes loadAlgorithm() to handle the DLL loading in a platform-neutral way. If the load was successful, the Controller initializes the Algorithm object by invoking Algorithm::startup(). If that step succeeds, the Controller starts a separate thread (which runs the svc() method) to handle message passing to the algorithm's registered message processors.
Algorithm Output Recording
Each controller has its own Recorder object that manages the recording state for the Controller. Recordings contain values from the output channels defined for the Controller. Current, there is no way to isolate recording to just a subset of the output channels.
Recording must be enabled for an Controller/Algorithm before it will allow its Recorder object to respond to Recorder::start() and Recorder::stop() messages. The Controller has a runtime parameter named "recordingEnabled" which contains the enabled state for recording. When set to true, the Controller will respond to IO::RecordingStateChangeRequest messages. The user can change this value through the SideCar::GUI::Master application's parameter editor interface.
Definition at line 53 of file Controller.h.
Constructor & Destructor Documentation
Controller::~Controller ()
Destructor.
Only present to emit log messages.
Definition at line 128 of file Controller.cc.
References LOGINFO.
Member Function Documentation
void Controller::addProcessingStatSample (const Time::TimeStamp & delta)
Manually update the held ProcessingStats attribute with the given sample value.
Parameters
delta processing duration to record
Definition at line 664 of file Controller.cc.
Referenced by SideCar::Algorithms::CPIAlgorithm::shutdown().
void SideCar::Algorithms::Controller::beginStatsProcessing () inline
Start a timer for tracking algorithm processing time.
The timer stops when the managed algorithm emits a message by calling send().
Definition at line 175 of file Controller.h.
bool Controller::calculateUsingDataValue () const override virtual
Override of IO::Task method.
Determines whether the algorithm is currently using data.
Returns
true if recording is enabled
Reimplemented from SideCar::IO::Task.
Definition at line 670 of file Controller.cc.
References SideCar::IO::Task::calculateUsingDataValue(), SideCar::IO::Task::getTaskName(), getTimerSecs(), SideCar::IO::ControlMessage::kTimeout, LOGINFO, SideCar::IO::MessageManager::MakeControlMessage(), and SideCar::IO::Task::put().
int Controller::close (u_long flags = 0) override
Shutdown the task.
Override of ACE_Task method. This is the canonical way to stop an ACE task. The close method gets called in two distinct situations, indicated by the value of the the given flags argument:
non-zero the controller is being closed by an external entity such as an IO::Module that is hosting the controller.
zero a thread spawned by the controller in the openAndInit() method has returned from the svc() method.
If flags is non-zero, the method deactivates the internal message queue to signal the service thread to stop processing. The method then waits for the thread to exit before it then invokes Algorithm::shutdown() to notify the algorithm that it is no longer running.
Parameters
flags indication of the situation in which the method is being called (see above)
Returns
0 if successful, -1 otherwise
Definition at line 193 of file Controller.cc.
References Logger::Log::Find(), SideCar::IO::MessageManager::getMessage(), LOGDEBUG, LOGERROR, LOGINFO, LOGWARNING, SideCar::IO::Task::put(), SideCar::IO::Task::setError(), and Logger::Log::setPriorityLimit().
void Controller::fillStatus (IO::StatusBase & status) override virtual
Override of IO::Task method.
Obtain status information from the controller. Fills recording state, and info data from the Algorithm (if any)
Parameters
status status object to fill in
Reimplemented from SideCar::IO::Task.
Definition at line 599 of file Controller.cc.
References SideCar::IO::Task::fillStatus(), getStatusSize(), LOGINFO, and SideCar::IO::StatusBase::setSlot().
Algorithm* SideCar::Algorithms::Controller::getAlgorithm () const inline
Fetch the loaded algorithm.
NOTE: do not save this pointer since the algorithm object may be unloaded at any time, making the pointer invalid.
Returns
pointer to loaded algorithm
Definition at line 127 of file Controller.h.
const std::string& SideCar::Algorithms::Controller::getAlgorithmName () const inline
Obtain the name of the algorithm DLL the controller will load and manage.
Returns
algorithm name
Definition at line 120 of file Controller.h.
Referenced by SideCar::Algorithms::Algorithm::addProcessor().
const char* SideCar::Algorithms::Controller::getStatusClassName () const inline override virtual
Override of IO::Task method.
Obtain the status class name for algorithm controller tasks.
Returns
NULL-terminated C string
Reimplemented from SideCar::IO::Task.
Definition at line 149 of file Controller.h.
size_t Controller::getStatusSize () const override virtual
Obtain the number of slots in a ControllerStatus XML array filled in by the algorithm.
By default, this is ControllerStatus::kNumSlots. However, if an algorithm adds its own custom slots, the returned value will be greater.
Returns
Reimplemented from SideCar::IO::Task.
Definition at line 634 of file Controller.cc.
References LOGERROR, LOGINFO, and SideCar::IO::Task::setError().
Referenced by fillStatus().
int SideCar::Algorithms::Controller::getTimerSecs () inline
Obtain the current alarm period.
If zero, alarms are disabled.
Returns
alarm period in seconds
Definition at line 210 of file Controller.h.
References Logger::Priority::GetLongNames().
Referenced by calculateUsingDataValue().
bool Controller::injectControlMessage (const IO::ControlMessage & msg)
Post a control message to the internal processing queue.
Parameters
msg control message to post
Returns
true if successful
Definition at line 357 of file Controller.cc.
References SideCar::IO::ControlMessage::getWrapped(), and SideCar::IO::Task::setError().
Referenced by injectProcessingStateChange().
bool Controller::injectProcessingStateChange (IO::ProcessingState::Value state)
Post a control message to change the run state.
Parameters
msg control message to post
Returns
true if successful
Definition at line 373 of file Controller.cc.
References SideCar::IO::Task::doClearStatsRequest(), SideCar::IO::Task::doParametersChange(), SideCar::IO::Task::enterAutoDiagnosticsState(), SideCar::IO::Task::enterCalibrateState(), SideCar::IO::Task::enterInitializeState(), SideCar::IO::Task::enterRunState(), SideCar::IO::Task::enterStopState(), SideCar::IO::MessageManager::getNative(), SideCar::IO::MessageManager::getNativeMessageType(), SideCar::IO::Task::getNumOutputChannels(), SideCar::IO::Task::getTaskName(), SideCar::IO::RecordingStateChangeRequest::getValue(), SideCar::IO::Task::hasError(), injectControlMessage(), SideCar::IO::Task::isActive(), SideCar::IO::RecordingStateChangeRequest::isOn(), LOGDEBUG, LOGERROR, LOGINFO, LOGTIN, LOGTOUT, SideCar::IO::Task::processMessage(), and SideCar::IO::Task::setError().
Logger::Log & Controller::Log () static
Obtain log device for Controller objects to use.
Returns
log device
Definition at line 88 of file Controller.cc.
References Logger::Log::Find().
Controller::Ref Controller::Make () static
Factory method that creates a new Controller object.
This is the only way to create a new Controller object. Returned objects have been initialized, but they do not have an Algorithm under their control; that occurs in the openAndInit() method.
Returns
reference to new Controller object
Definition at line 95 of file Controller.cc.
References LOGINFO, SideCar::Parameter::TValue< ParamDef >::Make(), and SideCar::IO::Task::registerParameter().
bool Controller::openAndInit (const std::string & algorithmName, const std::string & serviceName = "", Algorithm * algorithm = 0, long threadFlags = kDefaultThreadFlags, long threadPriority = ACE_DEFAULT_THREAD_PRIORITY, bool threaded = true)
Open the controller.
Attempts to load the DLL that contains the Algorithm class to instantiate. If loading was successful, invokes the Algorithm::startup() method to let the algorithm finish initializing itself. Finally, the controller spawns a new thread which will handle all message processing of the controller, including data writes/read writes to/from the Algorithm object.
Parameters
algorithmName name of the algorithm to load
algorithm if not NULL, use as the Algorithm object to manage. Used by the unit test to supply a test algorithm. NOTE: if used, the controller does not attempt to load in the DLL with the name algorithmName. If you need the DLL loaded, you must do so yourself.
Returns
true if successful
Definition at line 135 of file Controller.cc.
References SideCar::IO::Task::getTaskName(), LOGERROR, LOGINFO, LOGWARNING, SideCar::IO::Task::setError(), and SideCar::IO::Task::setTaskName().
void SideCar::Algorithms::Controller::setStatsManaged (bool state) inline
Set whether the controller manages the ProcessingStats attribute.
If false, the algorithm is responsible for posting processing duration values via addProcessingStatSample().
Parameters
state new state
Definition at line 188 of file Controller.h.
Referenced by SideCar::Algorithms::CPIAlgorithm::startup().
void Controller::setTimerSecs (int timerSecs)
Algorithms can use this method to set a periodic alarm every N seconds.
When the alarm goes off, the controller will invoke the algorithm's processAlarm() method.
Parameters
timerSecs the number of seconds between processAlarm() calls. If set to zero, disable alarms.
Definition at line 709 of file Controller.cc.
References SideCar::IO::Task::getTaskName(), SideCar::IO::Task::isActive(), LOGERROR, LOGINFO, and LOGWARNING.
Referenced by SideCar::Algorithms::Algorithm::setAlarm().
void SideCar::Algorithms::Controller::setXMLDefinition (const QDomNode & node) inline
Install the QDomNode of the XML parsed configuration file for the algorithm.
Parameters
node the QDomNode that refers to an <algorithm> entity.
Definition at line 194 of file Controller.h.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/Controller.h
/Users/howes/src/sidecar/Algorithms/Controller.cc