SideCar: SideCar::GUI::Spectrum::ViewChanger Class Reference
SideCar::GUI::Spectrum::ViewChanger Class Reference abstract
Abstract base class that manages user events associated with changing a SpectrumWidget view transformation matrix using the mouse.
#include </Users/howes/src/sidecar/GUI/Spectrum/ViewChanger.h>
Public Member Functions
ViewChanger (SpectrumWidget *spectrumWidget, const QPoint &start)
Constructor.
virtual ~ViewChanger ()
Destructor.
virtual void mouseMoved (const QPoint &pos)=0
Notification of a mouse change.
virtual void finished (const QPoint &pos)=0
Notification that the change is done.
Protected Attributes
SpectrumWidget * spectrumWidget_
QPoint start_
Detailed Description
Abstract base class that manages user events associated with changing a SpectrumWidget view transformation matrix using the mouse.
Derived classes exist for panning and zooming changes.
Definition at line 15 of file ViewChanger.h.
Constructor & Destructor Documentation
ViewChanger::ViewChanger (SpectrumWidget * spectrumWidget, const QPoint & start)
Constructor.
Parameters
spectrumWidget the SpectrumWidget to manipulate
start mouse position at the start of the change in local coordinates
Definition at line 6 of file ViewChanger.cc.
Member Function Documentation
virtual void SideCar::GUI::Spectrum::ViewChanger::finished (const QPoint & pos) pure virtual
Notification that the change is done.
Derived classes must define.
Parameters
pos last mouse position in local coordinates
Implemented in SideCar::GUI::Spectrum::ZoomingViewChanger, and SideCar::GUI::Spectrum::PanningViewChanger.
Referenced by SideCar::GUI::Spectrum::SpectrumWidget::SpectrumWidget(), and ~ViewChanger().
virtual void SideCar::GUI::Spectrum::ViewChanger::mouseMoved (const QPoint & pos) pure virtual
Notification of a mouse change.
Derived classes must define.
Parameters
pos new mouse position in local coordinates
Implemented in SideCar::GUI::Spectrum::ZoomingViewChanger, and SideCar::GUI::Spectrum::PanningViewChanger.
Referenced by SideCar::GUI::Spectrum::SpectrumWidget::SpectrumWidget(), and ~ViewChanger().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Spectrum/ViewChanger.h
/Users/howes/src/sidecar/GUI/Spectrum/ViewChanger.cc