SideCar: SideCar::GUI::QtMonitor Class Reference
SideCar::GUI::QtMonitor Class Reference
Concrete implementation of the Monitor class that relies on QSocketNotifier object to determine when a Transaction object has data available for processing.
#include </Users/howes/src/sidecar/GUI/QtMonitor.h>
Public Member Functions
QtMonitor ()
Constructor.
~QtMonitor ()
Destructor.
Public Member Functions inherited from SideCar::Zeroconf::Monitor
virtual ~Monitor ()
Destructor.
Static Public Member Functions
static Logger::Log & Log ()
Additional Inherited Members
Protected Member Functions inherited from SideCar::Zeroconf::Monitor
Monitor ()
Constructor.
Transaction * getMonitored () const
Obtain the monitored object.
Detailed Description
Concrete implementation of the Monitor class that relies on QSocketNotifier object to determine when a Transaction object has data available for processing.
When there is, it invokes Transaction::processConnection() to handle the incoming data.
Definition at line 18 of file QtMonitor.h.
Constructor & Destructor Documentation
SideCar::GUI::QtMonitor::QtMonitor () inline
Constructor.
Just initialize. Wait and create a new QSocketNotifier when there is a socket to monitor.
Definition at line 27 of file QtMonitor.h.
QtMonitor::~QtMonitor ()
Destructor.
Dispose of any active QSocketNotifier
Definition at line 16 of file QtMonitor.cc.
References SideCar::Zeroconf::Transaction::getConnection(), SideCar::Zeroconf::Monitor::getMonitored(), LOGDEBUG, LOGINFO, and SideCar::Zeroconf::Transaction::processConnection().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/QtMonitor.h
/Users/howes/src/sidecar/GUI/QtMonitor.cc