SideCar: SideCar::GUI::MessageWriter Class Reference
SideCar::GUI::MessageWriter Class Reference abstract
Abstract base class for Qt data publishers.
#include </Users/howes/src/sidecar/GUI/Writers.h>
Signals
void published (const QString &serviceName, const QString &serviceAddress, uint16_t port)
Notification sent out when the MessageWriter successfully publishes its connection information.
void failure ()
Notification sent out when the MessageWriter encounters a failure.
void subscriberCountChanged (size_t count)
Notification sent out when the number of subscribers to the publisher changes.
Public Member Functions
void setServiceName (const QString &serviceName)
Set the service name to publish under.
const QString & getServiceName () const
Obtain the service name being published.
const QString & getServiceAddress () const
Obtain the multicast address to use for sending out data.
uint16_t getPort () const
Obtain the socket port number used by the publisher.
virtual bool start ()
Start the publisher.
virtual bool writeMessage (const IO::MessageManager &mgr)=0
Publish a SideCar data message.
virtual bool stop ()
Stop the publisher.
bool isPublished () const
Determine if the MessageWriter is currently publishing its connection info.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the Log device to use for MessageWriter objects.
Protected Member Functions
MessageWriter (const QString &serviceName, const std::string &type, const std::string &transport, const QString &serviceAddress)
Constructor.
void setPort (uint16_t port)
Set the socket port assigned to the publisher by the OS.
virtual void setPublishedServiceName (const QString &serviceName)
Update the service name to the one created by Zeroconf due to a name collision.
boost::shared_ptr< Zeroconf::Publisher > getPublisher () const
Obtain the Zeroconf::Publisher object used to broadcast publisher connection information.
Detailed Description
Abstract base class for Qt data publishers.
Manages a Zeroconf::Publisher to broadcast publishing information. Derived classes must implement the writeMessage() method.
Definition at line 85 of file Writers.h.
Constructor & Destructor Documentation
MessageWriter::MessageWriter (const QString & serviceName, const std::string & type, const std::string & transport, const QString & serviceAddress) protected
Constructor.
Restricted to derived classes.
Parameters
serviceName name of the service to publish
type name of the message type to publish
transport the IP transport to use ('tcp' or 'multicast').
serviceAddress the address to publish for the server. Normally this would be the host IP address or name, but for multicasting, this must be the multicast address to use.
Definition at line 54 of file Writers.cc.
References Log(), and LOGINFO.
Member Function Documentation
void SideCar::GUI::MessageWriter::failure () signal
Notification sent out when the MessageWriter encounters a failure.
Currently this is only sent out if publishing fails.
Referenced by stop().
uint16_t SideCar::GUI::MessageWriter::getPort () const inline
Obtain the socket port number used by the publisher.
Returns
socket port number
Definition at line 121 of file Writers.h.
Referenced by SideCar::GUI::Playback::Emitter::setEmitting().
boost::shared_ptr<Zeroconf::Publisher> SideCar::GUI::MessageWriter::getPublisher () const inline protected
Obtain the Zeroconf::Publisher object used to broadcast publisher connection information.
Returns
Zeroconf::Publisher reference
Definition at line 205 of file Writers.h.
Referenced by SideCar::GUI::UDPMessageWriter::Make().
const QString& SideCar::GUI::MessageWriter::getServiceAddress () const inline
Obtain the multicast address to use for sending out data.
Returns
IPV4 multicast address
Definition at line 115 of file Writers.h.
Referenced by SideCar::GUI::UDPMessageWriter::Make().
const QString& SideCar::GUI::MessageWriter::getServiceName () const inline
Obtain the service name being published.
Returns
service name
Definition at line 109 of file Writers.h.
bool MessageWriter::isPublished () const
Determine if the MessageWriter is currently publishing its connection info.
Returns
true if publishing
Definition at line 73 of file Writers.cc.
Referenced by setServiceName().
Logger::Log & MessageWriter::Log () static
Obtain the Log device to use for MessageWriter objects.
Returns
Log device
Definition at line 48 of file Writers.cc.
References Logger::Log::Find().
Referenced by SideCar::GUI::TCPMessageWriter::Make(), SideCar::GUI::UDPMessageWriter::Make(), MessageWriter(), setServiceName(), start(), SideCar::GUI::TCPMessageWriter::start(), stop(), SideCar::GUI::TCPMessageWriter::stop(), SideCar::GUI::TCPMessageWriter::writeMessage(), and SideCar::GUI::UDPMessageWriter::writeMessage().
void SideCar::GUI::MessageWriter::published (const QString & serviceName, const QString & serviceAddress, uint16_t port) signal
Notification sent out when the MessageWriter successfully publishes its connection information.
Parameters
serviceName name that was published
serviceAddress host address that was published
port socket port that was published
Referenced by stop().
void SideCar::GUI::MessageWriter::setPort (uint16_t port) inline protected
Set the socket port assigned to the publisher by the OS.
Parameters
port socket port to use for writing
Definition at line 193 of file Writers.h.
Referenced by SideCar::GUI::UDPMessageWriter::Make(), and SideCar::GUI::TCPMessageWriter::start().
void MessageWriter::setPublishedServiceName (const QString & serviceName) protected virtual
Update the service name to the one created by Zeroconf due to a name collision.
Parameters
serviceName new service name
Definition at line 97 of file Writers.cc.
Referenced by stop().
void MessageWriter::setServiceName (const QString & serviceName)
Set the service name to publish under.
Parameters
serviceName the name to publish
Definition at line 79 of file Writers.cc.
References isPublished(), Log(), LOGINFO, start(), and stop().
bool MessageWriter::start () virtual
Start the publisher.
Returns
true if successful
Reimplemented in SideCar::GUI::TCPMessageWriter.
Definition at line 103 of file Writers.cc.
References Log(), LOGERROR, and LOGINFO.
Referenced by SideCar::GUI::UDPMessageWriter::Make(), and setServiceName().
bool MessageWriter::stop () virtual
Stop the publisher.
Returns
true if successful
Reimplemented in SideCar::GUI::TCPMessageWriter.
Definition at line 120 of file Writers.cc.
References failure(), Log(), LOGINFO, LOGWARNING, published(), and setPublishedServiceName().
Referenced by SideCar::GUI::Playback::Emitter::makeWriter(), SideCar::GUI::Playback::Emitter::setEmitting(), setServiceName(), and SideCar::GUI::Playback::Emitter::~Emitter().
void SideCar::GUI::MessageWriter::subscriberCountChanged (size_t count) signal
Notification sent out when the number of subscribers to the publisher changes.
Note that this class does not emit this signal; derived classes are expected to when they determine that the count has changed.
Parameters
count new subscriber count
Referenced by SideCar::GUI::UDPMessageWriter::Make(), and SideCar::GUI::TCPMessageWriter::stop().
virtual bool SideCar::GUI::MessageWriter::writeMessage (const IO::MessageManager & mgr) pure virtual
Publish a SideCar data message.
Derived classes must define.
Parameters
mgr container holding the message to write
Returns
true if successful
Implemented in SideCar::GUI::UDPMessageWriter, and SideCar::GUI::TCPMessageWriter.
Referenced by SideCar::GUI::PRIEmitter::MainWindow::openFile(), and SideCar::GUI::Playback::Emitter::setEmitting().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Writers.h
/Users/howes/src/sidecar/GUI/Writers.cc