SideCar: SideCar::Runner::App Class Reference
SideCar::Runner::App Class Reference
Manager for one or more ACE stream objects, each of which contain one or more SideCar IO::Task objects.
#include </Users/howes/src/sidecar/Runner/App.h>
Public Member Functions
App (int argc, char *const *argv)
Constructor for all App objects.
~App ()
Destructor.
void initialize ()
const std::string & getServiceName ()
Obtain the service name the runner has published.
void getChangedParameters (XmlRpc::XmlRpcValue &value) const
Obtain the set of all of the changed parameters for the runner.
bool getParameters (int streamIndex, int taskIndex, XmlRpc::XmlRpcValue &result) const
Fill an XML-RPC variable with a description of the runtime parameter settings of an IO::Task object.
bool setParameters (int streamIndex, int taskIndex, const XmlRpc::XmlRpcValue &params) const
Change one or more runtime parameter settings of an IO::Task object.
void fillStatus (XmlRpc::XmlRpcValue &status)
Fill in a RunnerStatus object with the current status of all managed IO::Stream objects.
void run ()
Start the RemoteController and StatusEmitter objects, and enter the ACE Reactor run loop, allowing data to flow.
void shutdown ()
Stop the StatusEmitter object and the ACE Reactor run loop.
void clearStats ()
Command all of the tasks to reset their input statistics.
void postControlMessage (ACE_Message_Block *data)
Post a control message to all managed streams.
void recordingStateChange (const std::string &path)
Command all of the tasks to change their recording state if they are enabled for recording.
size_t getStreamCount () const
Obtain the number of processing streams allocated in the runner.
void setServiceName (const std::string &name)
Change the runner's service name.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for App instances.
static App * GetApp ()
Get sole App instace.
Detailed Description
Manager for one or more ACE stream objects, each of which contain one or more SideCar IO::Task objects.
A runner application receives remote commands via XML-RPC requests, handled by its RemoteController object. Periodically, the runner emits status about all of its streams and stream tasks. This emission is managed by its StatusEmitter object.
The runner application accepts the following options on the command-line:
runner [-?|--help] [-d|--debug] [-H|--hostname HOST] [-i|--invalid] [-L|--logger LOG] [-M|--mcast ADDR] [-t|--tag TAG] [CONFIG]
d | debug enable verbose (debug level) log messages for ALL Logger::Log devices in the SideCar framework.
H | hostname set the host name to use when processing the XML configuration file, overriding the host name of the machine.
i | invalid start up the runner and all of its IO::Task objects in the IO::ProcessingState::kInvalid state. Without this option, the tasks will start up in the IO::ProcessingState::kRun state.
L | logger set a Logger configuration file to load and configure the all Logger::Log devices.
M | mcast assign a default IP address to use for multicast services. Note that if the XML configuration file defines a multicast address in the <host> tag used by the runner, then that value will be used instead of this one.
t | tag use the <host> stanza in the XML configuration file that has the corresponding tag value. This allows multiple runner processes to exist on the same host using the same XML configuration file.
If the runner command has no CONFIG argument, it will read from standard input for the configuration data. This would be useful when the XML configuration is dynamically generated, and not in a file on the system.
The App objects respond to the following XML-RCP requests:
getParameters – obtain the runtime parameters of a particular IO::Task object of a specific stream. Requires two parameters in the request: stream index, and task index. Returns an XML-RPC array with status for each stream.
recordingChange – start/stop data recording for all Algorithm::Controller objects enabled to record. Takes one parameter, a string that is the path of the directory into which Algorithm::Controller objects create their recordings. If the string is empty, recording stops.
setParameters – change one or more runtime parameter values of a specific IO::Task. Takes one parameter, an XML-RPC array with two items for each parameter being changed: the parameter name, and the new parameter value.
shutdown – command the runner to shutdown its streams. Takes no parameters.
stateChange – command all IO::Task objects to enter a new processing state. Takes one parameter, an integer value that corresponds to one of the enumeration values in IO::ProcessingState::Value.
NOTE: all of the above messages will run in a separate thread. The main thread of the App object, is essentially blocked at an ACE_Reactor::run_reactor_event_loop() call, and does not call back into any other App methods while the ACE Reactor is running.
Definition at line 94 of file App.h.
Constructor & Destructor Documentation
App::App (int argc, char *const * argv)
Constructor for all App objects.
Parameters
argc number of values in argv
argv command line arguments (including executable name)
Definition at line 86 of file App.cc.
References Logger::Log::addWriter(), Utils::CmdLineArgs::arg(), SideCar::Configuration::Loader::getLastLoadResult(), SideCar::Configuration::Loader::getRunnerConfig(), SideCar::IO::ProcessingState::GetValue(), SideCar::IO::ControlMessage::getWrapped(), Utils::CmdLineArgs::hasOpt(), SideCar::Configuration::Loader::load(), Log(), LOGERROR, LOGINFO, LOGWARNING, SideCar::Runner::StreamBuilder::Make(), postControlMessage(), Logger::Log::Root(), Logger::Log::setPriorityLimit(), and Logger::ProcLog::thrower().
App::~App ()
Destructor.
Removes the custom LogCollector from the Log service.
Definition at line 262 of file App.cc.
References Logger::Log::removeWriter(), and Logger::Log::Root().
Member Function Documentation
void App::fillStatus (XmlRpc::XmlRpcValue & status)
Fill in a RunnerStatus object with the current status of all managed IO::Stream objects.
Parameters
status object to update
Definition at line 338 of file App.cc.
References Log(), and LOGINFO.
App * App::GetApp () static
Get sole App instace.
Returns
App pointer
Definition at line 66 of file App.cc.
void App::getChangedParameters (XmlRpc::XmlRpcValue & value) const
Obtain the set of all of the changed parameters for the runner.
Parameters
value container to hold the results
Definition at line 379 of file App.cc.
References Log(), LOGDEBUG, LOGINFO, XmlRpc::XmlRpcValue::setSize(), and XmlRpc::XmlRpcValue::toXml().
bool App::getParameters (int streamIndex, int taskIndex, XmlRpc::XmlRpcValue & result) const
Fill an XML-RPC variable with a description of the runtime parameter settings of an IO::Task object.
Parameters
streamIndex index of the stream containing the task
taskIndex index of the task within the stream
result storage for the result
Returns
true if successful, false otherwise
Definition at line 395 of file App.cc.
References Log(), LOGDEBUG, and LOGINFO.
const std::string& SideCar::Runner::App::getServiceName ()
Obtain the service name the runner has published.
Returns
size_t SideCar::Runner::App::getStreamCount () const inline
Obtain the number of processing streams allocated in the runner.
Returns
stream count
Definition at line 199 of file App.h.
Logger::Log & App::Log () static
Obtain the log device for App instances.
Returns
Log device
Definition at line 72 of file App.cc.
References Logger::Log::Find(), and LOGERROR.
Referenced by App(), clearStats(), fillStatus(), getChangedParameters(), getParameters(), postControlMessage(), recordingStateChange(), run(), setParameters(), setServiceName(), and shutdown().
void App::postControlMessage (ACE_Message_Block * data)
Post a control message to all managed streams.
Parameters
data raw representation of an IO::ControlMessage object
Definition at line 319 of file App.cc.
References Log(), LOGERROR, and LOGINFO.
Referenced by App(), clearStats(), and recordingStateChange().
void App::recordingStateChange (const std::string & path)
Command all of the tasks to change their recording state if they are enabled for recording.
If the given path is not empty, then it is a valid directory into which tasks shall write their recordings. If it is empty, then any previous recording activity stops.
Parameters
path full path of directory to use for the recording
Definition at line 302 of file App.cc.
References Log(), LOGINFO, and postControlMessage().
bool App::setParameters (int streamIndex, int taskIndex, const XmlRpc::XmlRpcValue & params) const
Change one or more runtime parameter settings of an IO::Task object.
Parameters
streamIndex index of the stream containing the task
taskIndex index of the task within the stream
params XML-RPC array containing parameter names and new values.
Returns
true if successful, false otherwise
Definition at line 409 of file App.cc.
References SideCar::IO::ControlMessage::getWrapped(), Log(), and LOGINFO.
void App::setServiceName (const std::string & name)
Change the runner's service name.
Called when there is a naming conflict with another runner.
Parameters
name new name to use
Definition at line 432 of file App.cc.
References Log(), and LOGWARNING.
void App::shutdown ()
Stop the StatusEmitter object and the ACE Reactor run loop.
Note that this method runs in a separate thread. Invokes ACE_Reactor::end_event_loop() which will cause the run() method to return from ACE_Reactor::run_reactor_event_loop().
Definition at line 287 of file App.cc.
References Log(), and LOGWARNING.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Runner/App.h
/Users/howes/src/sidecar/Runner/App.cc