SideCar: Utils::PtrRingBuffer< T > Class Template Reference
Utils::PtrRingBuffer< T > Class Template Reference
Template class for ring buffers that contain pointers to user-defined types.
#include </Users/howes/src/sidecar/Utils/RingBuffer.h>
Public Member Functions
PtrRingBuffer (int capacity)
Constructor.
~PtrRingBuffer ()
Destructor.
bool pushOn (T *obj)
Add an object to the buffer.
T * popOff ()
Fetch the next object from the buffer.
Public Member Functions inherited from Utils::VoidRingBuffer
VoidRingBuffer (int capacity)
Constructor.
Public Member Functions inherited from Utils::TRingBuffer< void * >
TRingBuffer (int capacity)
Constructor.
bool pushOn (const void * &value)
Add an object to the buffer.
bool popOff (void * &value)
Fetch the next object from the buffer.
Public Member Functions inherited from Utils::RingBufferBase
RingBufferBase (int capacity)
Constructor.
int getCapacity () const
Obtain the capacity of the buffer.
int getSize () const
Obtain the number of objects held by the buffer.
bool isEmpty () const
Determine if the buffer is empty.
bool isFull () const
Determine if the buffer is full.
Additional Inherited Members
Protected Member Functions inherited from Utils::VoidRingBuffer
void * popOff ()
Fetch the next object from the buffer.
Protected Member Functions inherited from Utils::RingBufferBase
int getReadOffset ()
Obtain the current read offset, then increment the offset before returning.
int getWriteOffset ()
Obtain the current write offset, then increment the offset before returning.
void added ()
Increment the number of objects in the buffer.
void removed ()
Decrement the number of objects in the buffer.
Detailed Description
template<typename T>
class Utils::PtrRingBuffer< T >
Template class for ring buffers that contain pointers to user-defined types.
Only contains overrides of base class methods with necessary type-casting to keep the classes very light-weight.
Definition at line 152 of file RingBuffer.h.
Constructor & Destructor Documentation
template<typename T > Utils::PtrRingBuffer< T >::PtrRingBuffer (int capacity) inline
Constructor.
Parameters
capacity maximum number of objects in the buffer can hold
Definition at line 160 of file RingBuffer.h.
template<typename T > Utils::PtrRingBuffer< T >::~PtrRingBuffer () inline
Destructor.
Deletes any items in the buffer.
Definition at line 164 of file RingBuffer.h.
References Utils::RingBufferBase::isEmpty().
Member Function Documentation
template<typename T > T* Utils::PtrRingBuffer< T >::popOff () inline
Fetch the next object from the buffer.
Hands off ownership of the object to the caller.
Returns
next value or NULL if buffer was empty
Definition at line 179 of file RingBuffer.h.
References Utils::VoidRingBuffer::popOff().
template<typename T > bool Utils::PtrRingBuffer< T >::pushOn (T * obj) inline
Add an object to the buffer.
Note that the buffer takes ownership of the object while it is held in the buffer.
Parameters
obj the value to add
Returns
true if added, false if buffer was full
Definition at line 173 of file RingBuffer.h.
References Utils::TRingBuffer< void * >::pushOn().
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/Utils/RingBuffer.h