SideCar: SideCar::IO::WriterDevices::UDPSocket Class Reference
SideCar::IO::WriterDevices::UDPSocket Class Reference
Device that writes to a unicast socket.
#include </Users/howes/src/sidecar/IO/Writers.h>
Public Member Functions
UDPSocket ()
Constructor for new reader.
ACE_SOCK_Dgram & getDevice ()
Obtain reference to socket device.
const ACE_SOCK_Dgram & getDevice () const
Obtain read-only reference to socket device.
void setRemoteAddress (const ACE_INET_Addr &remoteAddress)
Set the address of the remote host to write to.
Static Public Member Functions
static Logger::Log & Log ()
Protected Member Functions
ssize_t writeToDevice (const iovec *iov, int count)
Send data to the device.
Detailed Description
Device that writes to a unicast socket.
Definition at line 152 of file Writers.h.
Member Function Documentation
ACE_SOCK_Dgram& SideCar::IO::WriterDevices::UDPSocket::getDevice () inline
Obtain reference to socket device.
Returns
socket device
Definition at line 166 of file Writers.h.
Referenced by SideCar::IO::MulticastDataPublisher::close(), SideCar::IO::UDPSocketWriterTask::openAndInit(), and SideCar::IO::MulticastDataPublisher::openAndInit().
const ACE_SOCK_Dgram& SideCar::IO::WriterDevices::UDPSocket::getDevice () const inline
Obtain read-only reference to socket device.
Returns
socket device
Definition at line 172 of file Writers.h.
void SideCar::IO::WriterDevices::UDPSocket::setRemoteAddress (const ACE_INET_Addr & remoteAddress) inline
Set the address of the remote host to write to.
Parameters
remoteAddress IP address of remote host
Definition at line 178 of file Writers.h.
Referenced by SideCar::IO::UDPSocketWriterTask::openAndInit(), and SideCar::IO::MulticastDataPublisher::openAndInit().
ssize_t WriterDevices::UDPSocket::writeToDevice (const iovec * iov, int count) protected
Send data to the device.
Parameters
iov address of first iovec structure to use
count number of iovec structures to process
Returns
number of bytes successfully written to device, or -1 if error
Definition at line 60 of file Writers.cc.
References LOGERROR.
Referenced by SideCar::IO::Writer::writeEncoded().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/Writers.h
/Users/howes/src/sidecar/IO/Writers.cc