SideCar: Logger::Writers::Writer Class Reference
Logger::Writers::Writer Class Reference abstract
Abstract class that defines the interface for all objects that write log messages.
#include </Users/howes/src/sidecar/Logger/Writers.h>
Public Types
using Ref = boost::shared_ptr< Writer >
Public Member Functions
virtual ~Writer ()
Destructor.
virtual void open ()
Open connection to storage device.
virtual void close ()
Close connection to storage device.
virtual void reopen ()
Close and then reopen connection to storage device.
virtual void flush ()
Flush any pending messages to the storage device.
virtual void write (const Msg &msg)=0
Write out a Msg instance to the storage device.
bool operator< (const Writer &rhs) const
void setFlushAfterUse (bool enabled)
bool getFlushAfterUse () const
Protected Member Functions
Writer (Formatters::Formatter::Ref formatter, bool flushAfterUse)
Constructor.
void format (std::ostream &os, const Msg &msg)
Detailed Description
Abstract class that defines the interface for all objects that write log messages.
Definition at line 40 of file Writers.h.
Constructor & Destructor Documentation
virtual Logger::Writers::Writer::~Writer () inline virtual
Destructor.
Delete registered Formatter object and remove from set of created writers.
Definition at line 48 of file Writers.h.
Logger::Writers::Writer::Writer (Formatters::Formatter::Ref formatter, bool flushAfterUse) inline protected
Constructor.
Only derived classes can see.
Parameters
formatter Formatter instances used to generate a std::string value from a Msg instance. Acquires ownership of the Formatter instace, and will dispose of it in the destructor.
Definition at line 85 of file Writers.h.
Member Function Documentation
virtual void Logger::Writers::Writer::close () inline virtual
Close connection to storage device.
Subclass must define.
Reimplemented in Logger::Writers::RemoteSyslog, Logger::Writers::Syslog, and Logger::Writers::File.
Definition at line 56 of file Writers.h.
Referenced by reopen().
virtual void Logger::Writers::Writer::open () inline virtual
Open connection to storage device.
Subclass must define.
Reimplemented in Logger::Writers::RemoteSyslog, Logger::Writers::Syslog, Logger::Writers::RollingFile, and Logger::Writers::File.
Definition at line 52 of file Writers.h.
Referenced by reopen().
virtual void Logger::Writers::Writer::write (const Msg & msg) pure virtual
Write out a Msg instance to the storage device.
Parameters
msg Msg instance to format and write out
Implemented in Logger::Writers::RemoteSyslog, Logger::Writers::Syslog, Logger::Writers::Stream, Logger::Writers::RollingFile, Logger::Writers::File, and SideCar::Runner::LogCollector.
Referenced by flush().
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/Logger/Writers.h