SideCar: SideCar::Parameter::Monitor< Parameter > Class Template Reference
SideCar::Parameter::Monitor< Parameter > Class Template Reference abstract
Monitor and apply changes to a Value instance.
#include </Users/howes/src/sidecar/Parameter/Monitor.h>
Public Types
using Self = Monitor< Parameter >
using Ref = boost::shared_ptr< Self >
Type to use for shared references to Monitor objects.
Public Member Functions
Monitor (typename Parameter::Ref &parameter)
Constructor.
virtual ~Monitor ()
Destructor.
Protected Member Functions
virtual void valueChanged (const Parameter &value)=0
Event handler called after our associated value has changed.
Detailed Description
template<typename Parameter>
class SideCar::Parameter::Monitor< Parameter >
Monitor and apply changes to a Value instance.
The setValue() method will apply a change to the associated Value instance, and will invoke the valueChanged() notification method, which derived classes must define.
Definition at line 14 of file Monitor.h.
Constructor & Destructor Documentation
template<typename Parameter > SideCar::Parameter::Monitor< Parameter >::Monitor (typename Parameter::Ref & parameter) inline
Constructor.
Associate with a specific Value instance.
Parameters
value Value istance to monitor
Definition at line 27 of file Monitor.h.
References SideCar::Parameter::Monitor< Parameter >::valueChanged().
template<typename Parameter > virtual SideCar::Parameter::Monitor< Parameter >::~Monitor () inline virtual
Destructor.
Disconnect monitor from the parameter's change signal.
Definition at line 33 of file Monitor.h.
References SideCar::Parameter::Monitor< Parameter >::valueChanged().
Member Function Documentation
template<typename Parameter > virtual void SideCar::Parameter::Monitor< Parameter >::valueChanged (const Parameter & value) protected pure virtual
Event handler called after our associated value has changed.
Derived classes must define.
Parameters
value parameter that has changed. NOTE: do not save a copy of this value; it is only valid for the duration of the valueChanged() call.
Referenced by SideCar::Parameter::Monitor< Parameter >::Monitor(), SideCar::Parameter::MonitorProxy< Parameter, Destination >::MonitorProxy(), and SideCar::Parameter::Monitor< Parameter >::~Monitor().
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/Parameter/Monitor.h