SideCar: SideCar::IO::ReaderDevices::MulticastSocket Class Reference
SideCar::IO::ReaderDevices::MulticastSocket Class Reference
Device that gets data from a network socket set up for multicast UDP messages.
#include </Users/howes/src/sidecar/IO/Readers.h>
Public Member Functions
MulticastSocket ()
Constructor for new reader.
ACE_SOCK_Dgram_Mcast & getDevice ()
Obtain reference to socket device.
const ACE_SOCK_Dgram_Mcast & getDevice () const
Obtain read-only reference to socket device.
const ACE_INET_Addr & getRemoteAddress () const
Obtain the address/port of the host that sent the last UDP message we received in fetchFromDevice().
void setFetchTimeout (const ACE_Time_Value *timeout)
Set a timeout value for fetches from a UDP socket.
bool join (const ACE_INET_Addr &address)
Establish a connection to a remote host at a given address.
Static Public Member Functions
static Logger::Log & Log ()
Protected Member Functions
ssize_t fetchFromDevice (void *addr, size_t size)
Obtain data from the device.
Detailed Description
Device that gets data from a network socket set up for multicast UDP messages.
Definition at line 162 of file Readers.h.
Member Function Documentation
ssize_t SideCar::IO::ReaderDevices::MulticastSocket::fetchFromDevice (void * addr, size_t size) inline protected
Obtain data from the device.
Parameters
addr where to place fetched data
size how much data to fetch
Returns
number of bytes fetched if > 0; EOF if == 0; and error condition if < 0
Definition at line 215 of file Readers.h.
ACE_SOCK_Dgram_Mcast& SideCar::IO::ReaderDevices::MulticastSocket::getDevice () inline
Obtain reference to socket device.
Returns
socket device
Definition at line 176 of file Readers.h.
Referenced by SideCar::IO::MulticastVMEReaderTask::close(), SideCar::Algorithms::BugCollectorUtils::BugPlotReader::get_handle(), SideCar::IO::VMEReaderTask::openAndInit(), SideCar::IO::TSPIReaderTask::openAndInit(), and SideCar::IO::MulticastDataSubscriber::ReaderThread::openAndInit().
const ACE_SOCK_Dgram_Mcast& SideCar::IO::ReaderDevices::MulticastSocket::getDevice () const inline
Obtain read-only reference to socket device.
Returns
socket device
Definition at line 182 of file Readers.h.
const ACE_INET_Addr& SideCar::IO::ReaderDevices::MulticastSocket::getRemoteAddress () const inline
Obtain the address/port of the host that sent the last UDP message we received in fetchFromDevice().
Returns
ACE_INET_Addr reference
Definition at line 188 of file Readers.h.
bool MulticastSocket::join (const ACE_INET_Addr & address)
Establish a connection to a remote host at a given address.
Parameters
address remote host to communicate with
Returns
true if successful
Definition at line 289 of file Readers.cc.
References SideCar::IO::DatagramReader::Log(), and LOGINFO.
Referenced by SideCar::IO::TSPIReaderTask::close(), SideCar::IO::MulticastVMEReaderTask::close(), SideCar::IO::VMEReaderTask::openAndInit(), SideCar::Algorithms::BugCollectorUtils::BugPlotReader::openAndInit(), and SideCar::IO::MulticastDataSubscriber::ReaderThread::openAndInit().
void SideCar::IO::ReaderDevices::MulticastSocket::setFetchTimeout (const ACE_Time_Value * timeout) inline
Set a timeout value for fetches from a UDP socket.
Useful when fetchFromDevice() runs a loop in a thread, causing recv() to block for a set amount of time before returning with a -1.
Parameters
timeout the amount of time to wait for data
Definition at line 195 of file Readers.h.
Referenced by SideCar::IO::MulticastDataSubscriber::ReaderThread::close(), SideCar::IO::TSPIReaderTask::openAndInit(), and SideCar::IO::MulticastVMEReaderTask::openAndInit().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/Readers.h
/Users/howes/src/sidecar/IO/Readers.cc