SideCar: SideCar::GUI::Master::ServicesModel Class Reference
SideCar::GUI::Master::ServicesModel Class Reference
Model class for SideCar services discovered via Zeroconfig.
#include </Users/howes/src/sidecar/GUI/Master/ServicesModel.h>
Public Types
enum Columns {
kName = 0, kHost, kState, kRecording,
kPending, kRate, kError, kInfo,
kNumColumns
}
Signals
void statusUpdated ()
Notification that the.
void runnerAdded (const RunnerItem *added)
void runnerRemoved (const RunnerItem *removed)
Public Member Functions
ServicesModel (QObject *parent)
bool start ()
int columnCount (const QModelIndex &parent=QModelIndex()) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
QModelIndex parent (const QModelIndex &index) const
bool postProcessingStateChange (const QStringList &configNames, IO::ProcessingState::Value) const
bool postClearStats (const QStringList &configNames) const
bool postRecordingStart (const QStringList &configNames, const QStringList &recordingPaths) const
bool postRecordingStop (const QStringList &configNames) const
bool postShutdownRequest (const QString &configName) const
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Qt::ItemFlags flags (const QModelIndex &index) const
int getConfigurationCount () const
void getServiceStats (int &runnerCount, int &streamCount, int &pendingCount, int &failureCount) const
void getDropsAndDupes (const QStringList &filter, int &drops, int &dupes) const
bool isRecording (const QStringList &filter) const
bool isCalibrating (const QStringList &filter) const
ConfigurationItem * getConfigurationItem (const QString &name) const
QStringList getServiceNames (const QString &configName) const
RunnerItem * getRunnerItem (const QString &configName, const QString &runnerName) const
bool getChangedParameters (const QStringList &configNames, QStringList &changes) const
Obtain a list of parameter settings that differ from their original settings as defined in the XML configuration files used to start Runner objects.
Static Public Member Functions
static Logger::Log & Log ()
static QString GetColumnName (int index)
static TreeViewItem * GetModelData (const QModelIndex &index)
Detailed Description
Model class for SideCar services discovered via Zeroconfig.
Contains the concrete data that describes each service.
Definition at line 31 of file ServicesModel.h.
Member Function Documentation
bool ServicesModel::getChangedParameters (const QStringList & configNames, QStringList & changes) const
Obtain a list of parameter settings that differ from their original settings as defined in the XML configuration files used to start Runner objects.
Parameters
definition XML container that will contain the changes
Returns
true if successful
Definition at line 230 of file ServicesModel.cc.
References SideCar::GUI::Master::ConfigurationItem::getChild(), SideCar::GUI::Master::TreeViewItem::getIndex(), SideCar::GUI::Master::TreeViewItem::getInsertionPoint(), SideCar::GUI::ServiceEntry::getName(), SideCar::GUI::Master::TreeViewItem::getName(), SideCar::GUI::Master::TreeViewItem::getNumChildren(), SideCar::GUI::Master::RunnerItem::getServiceEntry(), SideCar::GUI::Master::RunnerItem::getServiceName(), SideCar::GUI::Master::TreeViewItem::insertChild(), SideCar::GUI::ServiceEntry::isResolved(), SideCar::IO::ProcessingState::kCalibrate, SideCar::GUI::Master::RunnerLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, LOGWARNING, SideCar::GUI::Master::TreeViewItem::removeChild(), and SideCar::GUI::ServiceEntry::resolve().
Referenced by SideCar::GUI::Master::MainWindow::MainWindow().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/ServicesModel.h
/Users/howes/src/sidecar/GUI/Master/ServicesModel.cc