SideCar: SideCar::GUI::IntSetting Class Reference
SideCar::GUI::IntSetting Class Reference
Derivation of the Setting class that manages integer values.
#include </Users/howes/src/sidecar/GUI/IntSetting.h>
Public Slots
virtual void setValue (int value)
Change the setting value.
Public Slots inherited from SideCar::GUI::Setting
void setEnabled (bool state)
Signals
void valueChanged (int value)
Notification sent out when the held value changes.
Signals inherited from SideCar::GUI::Setting
void save (int index, const QVariant &value)
Notification sent out by the Setting object when the held value changes due to the setValue() method.
void enabledChanged (bool state)
Notification sent out by the Setting object when its enabled state changes.
void valueChanged ()
Public Member Functions
IntSetting (PresetManager *mgr, const QString &name, bool global=false)
Constructor with no default value.
IntSetting (PresetManager *mgr, const QString &name, int value, bool global=false)
Constructor with initial default value.
int getValue () const
Obtain the current setting value.
void connectWidget (QSpinBox *widget)
void connectWidget (QComboBox *widget)
Public Member Functions inherited from SideCar::GUI::Setting
Setting (PresetManager *mgr, const QString &name, bool global=false)
Constructor without a default setting value.
Setting (PresetManager *mgr, const QString &name, const QVariant &value, bool global=false)
Constructor with a default setting value.
const QString & getName () const
Obtain the name of the Setting object.
const QVariant & getOpaqueValue () const
Obtain the current value of the Setting object.
void setOpaqueValue (const QVariant &value)
Set the Setting's value and emit the opaqueValueChanged() signal followed by the save() signal.
bool isEnabled () const
Protected Member Functions
void valueUpdated ()
Override of Setting::valueUpdated() method.
Protected Member Functions inherited from SideCar::GUI::Setting
void resetOpaqueValue ()
void connectWidget (QWidget *widget)
void disconnectWidget (QWidget *widget)
Additional Inherited Members
Static Public Member Functions inherited from SideCar::GUI::Setting
static Logger::Log & Log ()
Log device for Setting objects.
Detailed Description
Derivation of the Setting class that manages integer values.
Definition at line 14 of file IntSetting.h.
Constructor & Destructor Documentation
IntSetting::IntSetting (PresetManager * mgr, const QString & name, bool global = false)
Constructor with no default value.
Parameters
mgr PresetManager object that records this setting
name the name of the setting
global if true, this is a global setting, not associated with a specific Preset.
Definition at line 8 of file IntSetting.cc.
IntSetting::IntSetting (PresetManager * mgr, const QString & name, int value, bool global = false)
Constructor with initial default value.
Parameters
mgr PresetManager object that records this setting
name the name of the setting
value initial value to use for the setting if one is not recorded
\param global if true, this is a global setting, not associated with a
specific Preset.
Definition at line 15 of file IntSetting.cc.
Member Function Documentation
int SideCar::GUI::IntSetting::getValue () const inline
Obtain the current setting value.
Returns
setting value
Definition at line 49 of file IntSetting.h.
References setValue(), valueChanged(), and valueUpdated().
Referenced by SideCar::GUI::SampleImaging::getDecimation(), SideCar::GUI::CLUTSetting::getType(), SideCar::GUI::PPIDisplay::ViewSettings::moveTo(), valueUpdated(), and SideCar::GUI::VideoSampleCountTransform::VideoSampleCountTransform().
void IntSetting::setValue (int value) virtual slot
Change the setting value.
Emits the valueChanged() signal if the given value is different than the held one.
Parameters
value new value to use.
Definition at line 23 of file IntSetting.cc.
References SideCar::GUI::Setting::setOpaqueValue().
Referenced by getValue(), SideCar::GUI::PPIDisplay::ViewSettings::setRangeFactorAndMax(), SideCar::GUI::PPIDisplay::ViewSettings::setZoomPower(), valueUpdated(), and SideCar::GUI::VideoSampleCountTransform::VideoSampleCountTransform().
void SideCar::GUI::IntSetting::valueChanged (int value) signal
Notification sent out when the held value changes.
Parameters
value new held value
Referenced by getValue(), and valueUpdated().
void IntSetting::valueUpdated () protected virtual
Override of Setting::valueUpdated() method.
Records the new value and emits the valueChanged() signal.
Reimplemented from SideCar::GUI::Setting.
Definition at line 32 of file IntSetting.cc.
References SideCar::GUI::Setting::getOpaqueValue(), getValue(), setValue(), and valueChanged().
Referenced by getValue().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/IntSetting.h
/Users/howes/src/sidecar/GUI/IntSetting.cc