SideCar: SideCar::GUI::Master::RunnerItem Class Reference
SideCar::GUI::Master::RunnerItem Class Reference
TreeViewItem that represents a runner process, which contains a collection of processing streams.
#include </Users/howes/src/sidecar/GUI/Master/RunnerItem.h>
Public Member Functions
RunnerItem (const Runner::RunnerStatus &status, ConfigurationItem *parent)
Constructor for a new runner process.
QVariant getHostDataValue (int role) const
Obtain the data value for the Host column, which displays host names where runner programs are executing.
QVariant getInfoDataValue (int role) const
Obtain the data value for the Info column, which displays task-specific information.
void setServiceEntry (ServiceEntry *serviceEntry)
ServiceEntry * getServiceEntry () const
Obtain the service entry found for this runner.
QString getServiceName () const
Obtain the unique name for the runner.
QString getHostName () const
Obtain the name of the host where the runner is executing.
QString getConfigName () const
Obtain the name of the configuration in use by the remote runner process.
QString getLogPath () const
Obtain the name of the configuration in use by the remote runner process.
StreamItem * getChild (int index) const
Shadow of TreeViewItem method that returns a type-casted value.
bool getParameters (int streamIndex, int taskIndex, XmlRpc::XmlRpcValue &definition) const
Obtain the current runtime parameter values from the XML-RPC server of the runner process hosting the Controller.
bool setParameters (int streamIndex, int taskIndex, const XmlRpc::XmlRpcValue &changes) const
Submit new runtime parameter values to the XML-RPC server of the runner process hosting the Controller.
bool getChangedParameters (QStringList &changes) const
Obtain a list of parameter settings that differ from their original settings as defined in the XML configuration file used to start the Runner.
bool executeRequest (const char *cmd, const XmlRpc::XmlRpcValue &args, XmlRpc::XmlRpcValue &result) const
Issue an XML-RPC request to the runner application.
bool isFiltered (const QString &filter) const
Override of TreeViewItem method.
Public Member Functions inherited from SideCar::GUI::Master::CollectionItem
void updateCollectionStats (CollectionStats &stats) const
Prototype for method to update a CollectionStats object with statistics provided by a TreeViewItem derivative.
bool canExpand () const
Determine if the TreeViewItem is expandable.
QVariant getNameDataValue (int role) const
Obtain the data value for the ServicesModel::kName column, which displays the name of the TreeViewItem.
QVariant getStateDataValue (int role) const
Obtain the data value for the ServicesModel::kState column, which displays the processing state of the TreeViewItem.
QVariant getRecordingDataValue (int role) const
Obtain the data value for the ServicesModel::kRecording column, which displays the recording state of the TreeViewItem.
QVariant getPendingCountValue (int role) const
Obtain the data value for the ServicesModel::kPending column, which displays the pending queue size of this item.
QVariant getRateDataValue (int role) const
Obtain the data value for the ServicesModel::kRate column, which displays the message processing rate of the TreeViewItem.
QVariant getErrorDataValue (int role) const
Obtain the data value for the ServicesModel::kError column, which displays any error text from the TreeViewItem.
IO::ProcessingState::Value getProcessingState () const
const CollectionStats & getCollectionStats () const
bool canRecord () const
bool willRecord () const
bool isRecording () const
void recalculateStats ()
Public Member Functions inherited from SideCar::GUI::Master::TreeViewItem
~TreeViewItem ()
Destructor.
virtual void initialize ()
Initialize this object's internal state.
const IO::StatusBase & getStatus () const
Obtain the latest IO::StatusBase object received for this object.
bool update (const IO::StatusBase &status)
Update the TreeViewItem held status.
bool isOK () const
bool isProcessing () const
Determine if the object is in a 'processing' state: auto-diagnostic, calibration, or run.
ActiveState getActiveState () const
Obtain the current ActiveState value for this object.
QVariant getData (int column, int role) const
Obtain the data point to use for a specific role in a given column.
virtual QColor getForegroundColor (int column) const
Obtain the foreground color to use for the contents of a given column.
virtual QFont getFont (int column) const
Obtain the font to use for the contents of a given column.
virtual int getAlignment (int columnt) const
Obtain the alignment (horizontal and vertical) to use for the contents of a given column.
virtual bool canEdit () const
Determine if the TreeViewItem supports editing of runtime parameter values.
const QString & getName () const
Obtain the object's name.
const QString & getFullName () const
Get the full name of the item.
void insertChild (int row, TreeViewItem *child)
Insert a child, renumbering the indices of all children after it.
void appendChild (TreeViewItem *child)
Add a child.
void removeChild (int index)
Remove the child at a given index.
TreeViewItem * getChild (int index) const
Obtain the child associated with a given index value.
int getNumChildren () const
Obtain the number of children.
int getIndex () const
Obtain the index of this object in the context of our parent's children array.
TreeViewItem * getParent () const
Obtain the parent of this TreeViewItem object.
int getParentIndex () const
Obtain the index value of the parent object (equivalent to getParent()->getIndex().
ChildrenIterator getChildrenIterator () const
Obtain a Java-style iterator for the children array.
bool isExpanded () const
Determine if the object is expanded.
void setExpanded (bool expanded)
Change the expansion attribute of the object.
int getInsertionPoint (const QString &name) const
Obtain the row where the given name could be inserted without disturbing the ordering of the existing rows.
Static Public Member Functions
static Logger::Log & Log ()
Static Public Member Functions inherited from SideCar::GUI::Master::TreeViewItem
static QVariant GetRecordingDataValue (bool canRecord, int role)
Utility class method that returns an appropriate value for the recording state depicted by the two arguments.
static QColor GetTextColor ()
Class method that returns the default (black) text color for all Qt::Foreground roles.
static QColor GetOKColor ()
Class method that returns the OK text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetWarningColor ()
Class method that returns the 'warning text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetFailureColor ()
Class method that returns the 'failure' text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetRecordingColor ()
Class method that returns the text color to use to show when a task is currently recording.
static QFont GetTextFont ()
Obtain the normal font to use for displayed text.
Protected Member Functions
void afterUpdate ()
Override of CollectionItem::afterUpdate().
Protected Member Functions inherited from SideCar::GUI::Master::CollectionItem
CollectionItem (const IO::StatusBase &status, TreeViewItem *parent)
void beforeUpdate ()
Hook invoked before a status update.
void accumulateChildStats (TreeViewItem *child)
Protected Member Functions inherited from SideCar::GUI::Master::TreeViewItem
TreeViewItem ()
Constructor for the RootItem object (which has no parent).
TreeViewItem (const IO::StatusBase &status, TreeViewItem *parent)
Constructor for all derived classes except RootItem.
void setName (const QString &name)
void setOK (bool ok)
void setProcessing (bool processing)
void setProcessingState (IO::ProcessingState::Value state)
void setActiveState (ActiveState activeState)
template<typename T >
const T & getStatusT () const
Additional Inherited Members
Public Types inherited from SideCar::GUI::Master::TreeViewItem
enum ActiveState { kIdle, kPartial, kActive, kNotUsingData }
using Children = QList< TreeViewItem * >
using ChildrenIterator = QListIterator< TreeViewItem * >
Detailed Description
TreeViewItem that represents a runner process, which contains a collection of processing streams.
When a ServicesModel receives a status container, it creates new RunnerItem objects when it fails to find the status container name. The RunnerItem holds a pointer to a GUI::ServiceEntry, which contains information about a Zeroconf-discovered service. When a RunnerItem has a valid ServiceEntry, the ServicesModel can talk to it via XML-RPC requests.
Definition at line 30 of file RunnerItem.h.
Constructor & Destructor Documentation
RunnerItem::RunnerItem (const Runner::RunnerStatus & status, ConfigurationItem * parent)
Constructor for a new runner process.
Parameters
status initial status value of the item
serviceEntry connection information for the XML-RPC server of the runner process. May be NULL if the ServiceEntry is not yet available.
parent parent node for this item
Definition at line 24 of file RunnerItem.cc.
References getChild(), SideCar::GUI::Master::TreeViewItem::getIndex(), SideCar::GUI::Master::TreeViewItem::getInsertionPoint(), SideCar::GUI::Master::TreeViewItem::getName(), SideCar::GUI::Master::TreeViewItem::getNumChildren(), SideCar::GUI::Master::TreeViewItem::insertChild(), LOGDEBUG, LOGINFO, and SideCar::GUI::Master::TreeViewItem::update().
Member Function Documentation
void RunnerItem::afterUpdate () protected virtual
Override of CollectionItem::afterUpdate().
Assigns RunnerLog objects if necessary, and then posts log messages from the last status update to the assigned RunnerLog object.
Reimplemented from SideCar::GUI::Master::CollectionItem.
Definition at line 178 of file RunnerItem.cc.
References SideCar::GUI::Master::CollectionItem::afterUpdate(), SideCar::GUI::Master::RunnerLog::Find(), SideCar::GUI::Master::TreeViewItem::getName(), getServiceName(), LOGDEBUG, and LOGWARNING.
bool RunnerItem::executeRequest (const char * cmd, const XmlRpc::XmlRpcValue & args, XmlRpc::XmlRpcValue & result) const
Issue an XML-RPC request to the runner application.
Parameters
cmd remote command to execute
args command arguments
result command result
Returns
true if successfully executed
Definition at line 89 of file RunnerItem.cc.
References XmlRpc::XmlRpcClient::execute(), getHostName(), SideCar::GUI::ServiceEntry::getPort(), getServiceName(), LOGDEBUG, LOGERROR, and LOGINFO.
Referenced by getChangedParameters(), getParameters(), SideCar::GUI::Master::ServicesView::rowsInserted(), and setParameters().
bool RunnerItem::getChangedParameters (QStringList & changes) const
Obtain a list of parameter settings that differ from their original settings as defined in the XML configuration file used to start the Runner.
Parameters
definition XML container that will contain the changes
Returns
true if successful
Definition at line 130 of file RunnerItem.cc.
References executeRequest(), getChild(), SideCar::GUI::Master::TreeViewItem::getNumChildren(), LOGDEBUG, LOGERROR, LOGINFO, XmlRpc::XmlRpcValue::setSize(), and XmlRpc::XmlRpcValue::toXml().
Referenced by SideCar::GUI::Master::ConfigurationItem::executeRequest().
StreamItem * RunnerItem::getChild (int index) const
Shadow of TreeViewItem method that returns a type-casted value.
Parameters
index chld to obtain
Returns
StreamItem object
Definition at line 158 of file RunnerItem.cc.
References SideCar::GUI::Master::RunnerLog::Find(), SideCar::GUI::Master::TreeViewItem::getChild(), SideCar::GUI::ServiceEntry::getName(), getServiceName(), and LOGINFO.
Referenced by getChangedParameters(), and RunnerItem().
QString SideCar::GUI::Master::RunnerItem::getConfigName () const inline
Obtain the name of the configuration in use by the remote runner process.
Returns
configuration name
Definition at line 95 of file RunnerItem.h.
Referenced by SideCar::GUI::Master::LogViewWindowManager::addLogInfo(), SideCar::GUI::Master::ConfigurationController::ConfigurationController(), and SideCar::GUI::Master::ServicesView::rowsInserted().
QVariant RunnerItem::getHostDataValue (int role) const virtual
Obtain the data value for the Host column, which displays host names where runner programs are executing.
Parameters
role the display role that determines the type of data to return
Returns
display value
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Definition at line 59 of file RunnerItem.cc.
References SideCar::GUI::Master::TreeViewItem::getHostDataValue(), getHostName(), and SideCar::GUI::ServiceEntry::getPort().
QString SideCar::GUI::Master::RunnerItem::getHostName () const inline
Obtain the name of the host where the runner is executing.
Returns
host name
Definition at line 88 of file RunnerItem.h.
Referenced by executeRequest(), and getHostDataValue().
QVariant RunnerItem::getInfoDataValue (int role) const virtual
Obtain the data value for the Info column, which displays task-specific information.
Parameters
role the display role that determines the type of data to return
Returns
display value
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Definition at line 71 of file RunnerItem.cc.
References SideCar::GUI::ByteAmountToString(), SideCar::GUI::Master::TreeViewItem::GetFailureColor(), SideCar::GUI::Master::TreeViewItem::getInfoDataValue(), SideCar::GUI::Master::TreeViewItem::GetOKColor(), and SideCar::GUI::Master::TreeViewItem::GetWarningColor().
QString SideCar::GUI::Master::RunnerItem::getLogPath () const inline
Obtain the name of the configuration in use by the remote runner process.
Returns
configuration name
Definition at line 102 of file RunnerItem.h.
bool RunnerItem::getParameters (int streamIndex, int taskIndex, XmlRpc::XmlRpcValue & definition) const
Obtain the current runtime parameter values from the XML-RPC server of the runner process hosting the Controller.
Parameters
definition container to hold the returned value
Returns
true if successful
Definition at line 108 of file RunnerItem.cc.
References executeRequest(), and XmlRpc::XmlRpcValue::setSize().
Referenced by SideCar::GUI::Master::StreamItem::getParameters().
ServiceEntry* SideCar::GUI::Master::RunnerItem::getServiceEntry () const inline
Obtain the service entry found for this runner.
NOTE: this value may be NULL if we have not yet received a resolved ServiceEntry object.
Returns
ServiceEntry object or NULL if none assigned
Definition at line 74 of file RunnerItem.h.
Referenced by SideCar::GUI::Master::ConfigurationItem::executeRequest(), and SideCar::GUI::Master::ServicesModel::getChangedParameters().
QString SideCar::GUI::Master::RunnerItem::getServiceName () const inline
Obtain the unique name for the runner.
This is a composite of the configuration name, host name, and runner name, separated by ':' charadcters.
Returns
unique service name
Definition at line 81 of file RunnerItem.h.
Referenced by SideCar::GUI::Master::LogViewWindowManager::addLogInfo(), afterUpdate(), SideCar::GUI::Master::ConfigurationController::ConfigurationController(), SideCar::GUI::Master::ConfigurationItem::ConfigurationItem(), executeRequest(), SideCar::GUI::Master::ConfigurationInfo::foundRunner(), SideCar::GUI::Master::ServicesModel::getChangedParameters(), getChild(), and SideCar::GUI::Master::ServicesView::rowsInserted().
bool SideCar::GUI::Master::RunnerItem::isFiltered (const QString & filter) const inline virtual
Override of TreeViewItem method.
Allow filter matching on the host name where the Runner is executing.
Parameters
filter the text used as a filter
Returns
true if this item matches the filter
Reimplemented from SideCar::GUI::Master::TreeViewItem.
Definition at line 161 of file RunnerItem.h.
bool RunnerItem::setParameters (int streamIndex, int taskIndex, const XmlRpc::XmlRpcValue & changes) const
Submit new runtime parameter values to the XML-RPC server of the runner process hosting the Controller.
Parameters
changes container holding the new settings
Returns
true if successful
Definition at line 118 of file RunnerItem.cc.
References executeRequest(), and XmlRpc::XmlRpcValue::setSize().
Referenced by SideCar::GUI::Master::StreamItem::setParameters().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/RunnerItem.h
/Users/howes/src/sidecar/GUI/Master/RunnerItem.cc