SideCar: Logger::Writers::File Class Reference
Logger::Writers::File Class Reference
Public Types
using Ref = boost::shared_ptr< File >
Public Types inherited from Logger::Writers::Writer
using Ref = boost::shared_ptr< Writer >
Public Member Functions
void open () override
Open connection to storage device.
void close () override
Close connection to storage device.
void flush () override
Flush any pending messages to the storage device.
void write (const Msg &msg) override
Write out a Msg instance to the storage device.
const std::string & path () const
Public Member Functions inherited from Logger::Writers::Writer
virtual ~Writer ()
Destructor.
virtual void reopen ()
Close and then reopen connection to storage device.
bool operator< (const Writer &rhs) const
void setFlushAfterUse (bool enabled)
bool getFlushAfterUse () const
Static Public Member Functions
static Ref Make (const Formatters::Formatter::Ref &formatter, const std::string &path, bool append=true, mode_t mode=00644, bool flushAfterUse=false)
Protected Member Functions
File (const Formatters::Formatter::Ref &formatter, const std::string &path, bool append, mode_t mode, bool flushAfterUse)
size_t wrote () const
int fd () const
Protected Member Functions inherited from Logger::Writers::Writer
Writer (Formatters::Formatter::Ref formatter, bool flushAfterUse)
Constructor.
void format (std::ostream &os, const Msg &msg)
Detailed Description
Definition at line 95 of file Writers.h.
Member Function Documentation
void File::close () override virtual
Close connection to storage device.
Subclass must define.
Reimplemented from Logger::Writers::Writer.
Definition at line 37 of file FileWriter.cc.
Referenced by Logger::Writers::RollingFile::write().
void File::open () override virtual
Open connection to storage device.
Subclass must define.
Reimplemented from Logger::Writers::Writer.
Reimplemented in Logger::Writers::RollingFile.
Definition at line 27 of file FileWriter.cc.
Referenced by Logger::Writers::RollingFile::open().
void File::write (const Msg & msg) override virtual
Write out a Msg instance to the storage device.
Parameters
msg Msg instance to format and write out
Implements Logger::Writers::Writer.
Reimplemented in Logger::Writers::RollingFile.
Definition at line 54 of file FileWriter.cc.
Referenced by Logger::Writers::RollingFile::write().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Logger/Writers.h
/Users/howes/src/sidecar/Logger/FileWriter.cc