SideCar: UnitTest::UnitTestException Class Reference
UnitTest::UnitTestException Class Reference
Exception class thrown by a failed assertion in a unit test.
#include </Users/howes/src/sidecar/UnitTest/TestObj.h>
Public Member Functions
UnitTestException (const char *msg, const std::string &testName) throw ()
Constructor.
UnitTestException (const std::string &msg, const std::string &testName) throw ()
UnitTestException (const char *msg, const char *file, int line, const std::string &testName) throw ()
UnitTestException (const std::string &msg, const char *file, int line, const std::string &testName) throw ()
virtual ~UnitTestException () throw ()
Destructor.
const std::string & err () const throw ()
Return the description of the failure or error.
const std::string & testName () const throw ()
Return the name of the unit test that was running.
const std::string & file () const throw ()
Return the name of the file in which the exception occured.
long line () const throw ()
Return the line number of the file.
std::ostream & printText (std::ostream &os) const
Write out exception text to given output stream.
std::ostream & printXML (std::ostream &os) const
Write out XML representation of exception to given output stream.
Detailed Description
Exception class thrown by a failed assertion in a unit test.
Records the failure message, the file it was found in, the line of the file, and the name of the test that failed the assertion. For the UnitTest framework, there are two classifications of exceptions: those thrown by a failed assertion (assertTrue() or assertEQ()), and all others. The first are classified as test failures, while the latter are run-time errors (eg. file not found). Both classifications are represented by UnitTestException (perhaps mistakenly so). However, only test failures report file and line information.
Definition at line 119 of file TestObj.h.
Constructor & Destructor Documentation
UnitTest::UnitTestException::UnitTestException (const char * msg, const std::string & testName) throw () inline
Constructor.
Remembers details of an exceptional situation.
Parameters
msg description of the failure or error
file name of the file that raised the exception. May be NULL.
line line number of the file
testName name of the test that was running at the time of the exception.
Definition at line 132 of file TestObj.h.
Referenced by UnitTest::TestObj::_assertNotEqual(), and UnitTest::TestObj::run().
Member Function Documentation
const std::string& UnitTest::UnitTestException::file () const throw () inline
Return the name of the file in which the exception occured.
May be NULL.
Definition at line 158 of file TestObj.h.
Referenced by UnitTest::TestObj::_assertEqual(), and UnitTest::TestObj::_assertNotEqual().
long UnitTest::UnitTestException::line () const throw () inline
Return the line number of the file.
If file() returns NULL, this is undefined.
Definition at line 162 of file TestObj.h.
Referenced by UnitTest::TestObj::_assertEqual(), and UnitTest::TestObj::_assertNotEqual().
std::ostream & UnitTestException::printText (std::ostream & os) const
Write out exception text to given output stream.
Parameters
os stream to write to
Returns
stream written to
Definition at line 17 of file TestObj.cc.
Referenced by PrintText::operator()().
std::ostream & UnitTestException::printXML (std::ostream & os) const
Write out XML representation of exception to given output stream.
Parameters
os stream to write to
Returns
stream written to
Definition at line 24 of file TestObj.cc.
Referenced by PrintXML::operator()().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/UnitTest/TestObj.h
/Users/howes/src/sidecar/UnitTest/TestObj.cc