SideCar: SideCar::GUI::BoolSetting Class Reference
SideCar::GUI::BoolSetting Class Reference
Derivation of the Setting class that manages boolean values.
#include </Users/howes/src/sidecar/GUI/BoolSetting.h>
Public Slots
void setValue (bool value)
Change the setting value.
void toggle ()
Toggle the setting value.
Public Slots inherited from SideCar::GUI::Setting
void setEnabled (bool state)
Signals
void valueChanged (bool value)
Notification sent out when the held value changes.
Signals inherited from SideCar::GUI::Setting
void save (int index, const QVariant &value)
Notification sent out by the Setting object when the held value changes due to the setValue() method.
void enabledChanged (bool state)
Notification sent out by the Setting object when its enabled state changes.
void valueChanged ()
Public Member Functions
BoolSetting (PresetManager *mgr, const QString &name, bool global=false)
Constructor.
BoolSetting (PresetManager *mgr, const QString &name, bool value, bool global=false)
Constructor.
bool getValue () const
Obtain the current setting value.
void connectWidget (QCheckBox *widget)
void connectWidget (QRadioButton *widget)
void connectAction (QAction *action)
Public Member Functions inherited from SideCar::GUI::Setting
Setting (PresetManager *mgr, const QString &name, bool global=false)
Constructor without a default setting value.
Setting (PresetManager *mgr, const QString &name, const QVariant &value, bool global=false)
Constructor with a default setting value.
const QString & getName () const
Obtain the name of the Setting object.
const QVariant & getOpaqueValue () const
Obtain the current value of the Setting object.
void setOpaqueValue (const QVariant &value)
Set the Setting's value and emit the opaqueValueChanged() signal followed by the save() signal.
bool isEnabled () const
Additional Inherited Members
Static Public Member Functions inherited from SideCar::GUI::Setting
static Logger::Log & Log ()
Log device for Setting objects.
Protected Member Functions inherited from SideCar::GUI::Setting
void resetOpaqueValue ()
void connectWidget (QWidget *widget)
void disconnectWidget (QWidget *widget)
Detailed Description
Derivation of the Setting class that manages boolean values.
Definition at line 15 of file BoolSetting.h.
Constructor & Destructor Documentation
BoolSetting::BoolSetting (PresetManager * mgr, const QString & name, bool global = false)
Constructor.
Parameters
mgr
name
global
Definition at line 10 of file BoolSetting.cc.
BoolSetting::BoolSetting (PresetManager * mgr, const QString & name, bool value, bool global = false)
Constructor.
Parameters
mgr
name
value
global
Definition at line 16 of file BoolSetting.cc.
Member Function Documentation
bool SideCar::GUI::BoolSetting::getValue () const inline
Obtain the current setting value.
Returns
setting value
Definition at line 47 of file BoolSetting.h.
References setValue(), and valueChanged().
Referenced by SideCar::GUI::ESScope::History::History(), SideCar::GUI::OnOffSettingsBlock::isEnabled(), SideCar::GUI::QCheckBoxSetting::QCheckBoxSetting(), setValue(), toggle(), SideCar::GUI::VideoSampleCountTransform::transform(), and SideCar::GUI::VideoSampleCountTransform::VideoSampleCountTransform().
void BoolSetting::setValue (bool value) slot
Change the setting value.
Emits the valueChanged() signal if the given value is diferent than the held one.
Parameters
value new value to use
Definition at line 23 of file BoolSetting.cc.
References SideCar::GUI::Setting::getOpaqueValue(), getValue(), SideCar::GUI::Setting::setOpaqueValue(), SideCar::GUI::UpdateToggleAction(), and valueChanged().
Referenced by getValue(), SideCar::GUI::QCheckBoxSetting::QCheckBoxSetting(), and toggle().
void SideCar::GUI::BoolSetting::valueChanged (bool value) signal
Notification sent out when the held value changes.
Parameters
value new held value
Referenced by getValue(), SideCar::GUI::QCheckBoxSetting::QCheckBoxSetting(), and setValue().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/BoolSetting.h
/Users/howes/src/sidecar/GUI/BoolSetting.cc