SideCar: SideCar::Algorithms::ChannelBuffer Class Reference
SideCar::Algorithms::ChannelBuffer Class Reference abstract
Abstract base class of an input message buffer that will hold a maximum number of messages in FIFO order.
#include </Users/howes/src/sidecar/Algorithms/ChannelBuffer.h>
Public Types
using Container = std::deque< Messages::PRIMessage::Ref >
using const_iterator = Container::const_iterator
Public Member Functions
ChannelBuffer (ManyInAlgorithm &processor, size_t channelIndex, size_t maxBufferSize)
Constructor.
virtual ~ChannelBuffer ()
Destructor.
size_t getChannelIndex () const
Obtain the channel index for this object.
size_t getMaxBufferSize () const
Obtain the maximum number of messages to hold.
size_t size () const
Obtain the number of messages in the buffer.
bool isEmpty () const
Determine if the buffer is empty.
bool isEnabled () const
Determine if the buffer is enabled.
uint32_t getNextSequenceCounter () const
Obtain the sequence counter of the first message in the queue.
bool pruneToSequenceCounter (uint32_t sequenceCounter)
Remove messages from the front of the queue whose sequence counter values are less than the given value.
virtual void setMaxBufferSize (size_t maxBufferSize)
Change the maximum number of messages to hold.
virtual void setEnabled (bool value)
Change the enabled state.
virtual void reset ()
Reset the buffer by forgetting any held messagess.
virtual void getSlice (int offset, int span, VsipComplexVector &slice, bool doPop)=0
Obtain a slide of the data, copying it into a VSIPL vector.
bool addData (const Messages::PRIMessage::Ref &msg)
Add a message to the queue.
virtual bool makeEnabledParameter ()
Create a runtime parameter to control the channel enabled state.
virtual bool makeEnabledParameter (const std::string &shortName, const std::string &longName)
Create a runtime parameter to control the channel enabled state.
const_iterator begin () const
Obtain read-only iterator to the first sample value in the message.
const_iterator end () const
Obtain read-only iterator to the last + 1 sample value in the message.
Messages::PRIMessage::Ref getFront () const
Obtain the oldest message in the queue.
Messages::PRIMessage::Ref popFront ()
Remove the oldest message in the queue.
Static Public Member Functions
static std::string MakeGenericShortName (int index)
Create generic short name for the input channel.
static std::string MakeGenericLongName (int index)
Create generic long name for the input channel.
Protected Member Functions
void popFrontInternal ()
Remove the oldest message from the queue.
void pruneToMaxBufferSize ()
Remove messages until the size of the buffer is less than or equal to maxBufferSize_.
virtual void enabledChanged (const Parameter::BoolValue &parameter)
Callback invoked when the 'enabled' parameter state changes.
Detailed Description
Abstract base class of an input message buffer that will hold a maximum number of messages in FIFO order.
Held messages are of type PRIMessage; a derived template class, TChannelBuffer, works with concrete SideCar messages types.
Note that this class works with a ManyInAlgorithm instance, requiring one in its constructor. After a ChannelBuffer places a new message in its queue, it calls the ManyInAlgorithm::processMessageReceived() method to notify the ManyInAlgorithm object of new data.
Definition at line 29 of file ChannelBuffer.h.
Constructor & Destructor Documentation
ChannelBuffer::ChannelBuffer (ManyInAlgorithm & processor, size_t channelIndex, size_t maxBufferSize)
Constructor.
Parameters
processor object to notify when new data arrives in the buffer
channelIndex the channel index unique to this object
maxBufferSize the maximum number of messages to hold
Definition at line 24 of file ChannelBuffer.cc.
ChannelBuffer::~ChannelBuffer () virtual
Destructor.
Properly dispose of any held messages.
Definition at line 31 of file ChannelBuffer.cc.
Member Function Documentation
bool ChannelBuffer::addData (const Messages::PRIMessage::Ref & msg)
Add a message to the queue.
Parameters
msg the message to process
Returns
true if successful
Definition at line 96 of file ChannelBuffer.cc.
References isEnabled(), SideCar::Algorithms::ManyInAlgorithm::processMessageReceived(), and pruneToMaxBufferSize().
Referenced by getNextSequenceCounter().
const_iterator SideCar::Algorithms::ChannelBuffer::begin () const inline
Obtain read-only iterator to the first sample value in the message.
Returns
read-only iterator
Definition at line 172 of file ChannelBuffer.h.
void ChannelBuffer::enabledChanged (const Parameter::BoolValue & parameter) protected virtual
Callback invoked when the 'enabled' parameter state changes.
Parameters
parameter the parameter that changed
Definition at line 51 of file ChannelBuffer.cc.
References SideCar::Parameter::TValue< ParamDef >::getValue(), and setEnabled().
Referenced by makeEnabledParameter(), and popFront().
const_iterator SideCar::Algorithms::ChannelBuffer::end () const inline
Obtain read-only iterator to the last + 1 sample value in the message.
Returns
read-only iterator
Definition at line 178 of file ChannelBuffer.h.
size_t SideCar::Algorithms::ChannelBuffer::getChannelIndex () const inline
Obtain the channel index for this object.
Returns
channel index
Definition at line 72 of file ChannelBuffer.h.
Referenced by SideCar::Algorithms::SimpleOp::SimpleOp(), and SideCar::Algorithms::Summer::Summer().
Messages::PRIMessage::Ref SideCar::Algorithms::ChannelBuffer::getFront () const inline
Obtain the oldest message in the queue.
NOTE: only call if the queue is not empty.
Returns
Messages::PRIMessage reference
Definition at line 184 of file ChannelBuffer.h.
Referenced by SideCar::Algorithms::TChannelBuffer< Messages::Video >::getFront(), SideCar::Algorithms::TChannelBuffer< Messages::Video >::getSlice(), popFront(), and SideCar::Algorithms::TChannelBuffer< Messages::Video >::popFront().
size_t SideCar::Algorithms::ChannelBuffer::getMaxBufferSize () const inline
Obtain the maximum number of messages to hold.
Returns
buffer limit
Definition at line 78 of file ChannelBuffer.h.
uint32_t SideCar::Algorithms::ChannelBuffer::getNextSequenceCounter () const inline
Obtain the sequence counter of the first message in the queue.
NOTE: if the queue is empty, this returns 0.
Returns
sequence counter
Definition at line 103 of file ChannelBuffer.h.
References addData(), getSlice(), makeEnabledParameter(), pruneToSequenceCounter(), reset(), setEnabled(), and setMaxBufferSize().
virtual void SideCar::Algorithms::ChannelBuffer::getSlice (int offset, int span, VsipComplexVector & slice, bool doPop) pure virtual
Obtain a slide of the data, copying it into a VSIPL vector.
NOTE: only valid if isEmpty() is false. Always works on the first message in the FIFO queue.
Parameters
offset index of the first sample value to use
span count of sample values to gather
slice container to hold the resulting complex values
doPop if true, remove the first message from the queue after working with it
Implemented in SideCar::Algorithms::TChannelBuffer< T >, and SideCar::Algorithms::TChannelBuffer< Messages::Video >.
Referenced by getNextSequenceCounter().
bool SideCar::Algorithms::ChannelBuffer::isEmpty () const inline
Determine if the buffer is empty.
Returns
true if so
Definition at line 90 of file ChannelBuffer.h.
Referenced by SideCar::Algorithms::TChannelBuffer< Messages::Video >::getFront(), SideCar::Algorithms::TChannelBuffer< Messages::Video >::getSlice(), popFront(), SideCar::Algorithms::TChannelBuffer< Messages::Video >::popFront(), popFrontInternal(), and pruneToSequenceCounter().
bool SideCar::Algorithms::ChannelBuffer::isEnabled () const inline
Determine if the buffer is enabled.
A disabled buffer ignores all addData() calls.
Returns
true if so
Definition at line 96 of file ChannelBuffer.h.
Referenced by addData(), SideCar::Algorithms::ManyInAlgorithm::getNumInfoSlots(), SideCar::Algorithms::SimpleOp::SimpleOp(), and SideCar::Algorithms::Summer::Summer().
bool ChannelBuffer::makeEnabledParameter () virtual
Create a runtime parameter to control the channel enabled state.
The created Parameter::BoolValue object will have names created from MakeGenericShortName() and MakeGenericLongName().
Returns
true if successful
Definition at line 37 of file ChannelBuffer.cc.
References MakeGenericLongName(), and MakeGenericShortName().
Referenced by SideCar::Algorithms::BinaryOp::BinaryOp(), getNextSequenceCounter(), SideCar::Algorithms::SimpleOp::SimpleOp(), and SideCar::Algorithms::Summer::Summer().
bool ChannelBuffer::makeEnabledParameter (const std::string & shortName, const std::string & longName) virtual
Create a runtime parameter to control the channel enabled state.
Parameters
shortName
longName
Returns
true if successful
Definition at line 43 of file ChannelBuffer.cc.
References enabledChanged(), SideCar::Parameter::TValue< ParamDef >::Make(), and SideCar::Algorithms::Algorithm::registerParameter().
std::string ChannelBuffer::MakeGenericLongName (int index) static
Create generic long name for the input channel.
Given an index value of N, this will return a string with the format "Input # Enabled", with # replaced by the value N+1.
Parameters
index the channel index to use
Returns
generic short name
Definition at line 17 of file ChannelBuffer.cc.
Referenced by makeEnabledParameter().
std::string ChannelBuffer::MakeGenericShortName (int index) static
Create generic short name for the input channel.
Given an index value of N, this will return a string with the format "input#Enabled", with # replaced by the value N+1.
Parameters
index the channel index to use
Returns
generic short name
Definition at line 9 of file ChannelBuffer.cc.
Referenced by makeEnabledParameter().
Messages::PRIMessage::Ref SideCar::Algorithms::ChannelBuffer::popFront () inline
Remove the oldest message in the queue.
NOTE: only call if the queue is not empty.
Definition at line 188 of file ChannelBuffer.h.
References enabledChanged(), getFront(), isEmpty(), popFrontInternal(), and pruneToMaxBufferSize().
Referenced by SideCar::Algorithms::TChannelBuffer< Messages::Video >::getSlice(), and SideCar::Algorithms::Printer::startup().
void ChannelBuffer::popFrontInternal () protected
Remove the oldest message from the queue.
Updates the nextSequenceCounter_ value. NOTE: only call if the queue is not empty.
Definition at line 108 of file ChannelBuffer.cc.
References isEmpty().
Referenced by popFront(), SideCar::Algorithms::TChannelBuffer< Messages::Video >::popFront(), pruneToMaxBufferSize(), and pruneToSequenceCounter().
bool ChannelBuffer::pruneToSequenceCounter (uint32_t sequenceCounter)
Remove messages from the front of the queue whose sequence counter values are less than the given value.
Parameters
sequenceCounter the value to compare against
Returns
true if the buffer has a message with the given sequence counter
Definition at line 59 of file ChannelBuffer.cc.
References isEmpty(), and popFrontInternal().
Referenced by getNextSequenceCounter().
void ChannelBuffer::setEnabled (bool value) virtual
Change the enabled state.
Parameters
value new value
Definition at line 81 of file ChannelBuffer.cc.
References SideCar::Algorithms::ManyInAlgorithm::channelEnabledChanged(), and reset().
Referenced by enabledChanged(), and getNextSequenceCounter().
void ChannelBuffer::setMaxBufferSize (size_t maxBufferSize) virtual
Change the maximum number of messages to hold.
Parameters
maxBufferSize new value
Definition at line 74 of file ChannelBuffer.cc.
References pruneToMaxBufferSize().
Referenced by getNextSequenceCounter().
size_t SideCar::Algorithms::ChannelBuffer::size () const inline
Obtain the number of messages in the buffer.
Returns
buffer size
Definition at line 84 of file ChannelBuffer.h.
Referenced by pruneToMaxBufferSize().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/ChannelBuffer.h
/Users/howes/src/sidecar/Algorithms/ChannelBuffer.cc