SideCar: SideCar::Algorithms::ComposeExtractions Class Reference
SideCar::Algorithms::ComposeExtractions Class Reference
Documentation for the algorithm ProcessTracks This task simply receives track messages and passes them along.
#include </Users/howes/src/sidecar/Algorithms/ComposeExtractions/ComposeExtractions.h>
Public Types
enum InfoSlots { kEnabled = ControllerStatus::kNumSlots, kNumSlots }
Public Member Functions
ComposeExtractions (Controller &controller, Logger::Log &log)
Constructor.
bool startup ()
Implementation of the Algorithm::startup interface.
bool shutdown ()
Implementation of the Algorithm::shutdown interface.
void processAlarm ()
This method will get called whenever an alarm expires for this Algorithm.
Public Member Functions inherited from SideCar::Algorithms::Algorithm
Algorithm (Controller &controller, Logger::Log &log)
Constructor.
virtual ~Algorithm ()
Destructor.
Controller & getController () const
Obtain the Controller object managing the algorithm.
Logger::Log & getLog () const
Obtain the log device to use for by the algorithm for log messages.
const std::string & getName () const
Obtain the name of the algorithm.
bool registerParameter (const Parameter::Ref &parameter)
Add a configuration parameter to the runtime system.
bool unregisterParameter (const Parameter::Ref &parameter)
Remove a configuration parameter from the runtime system.
template<typename A , typename M >
void registerProcessor (boost::function< bool(A *, typename M::Ref)> proc)
Install a method to process a particular message type.
template<typename A , typename M >
void registerProcessor (const std::string &channelName, boost::function< bool(A *, typename M::Ref)> proc)
Same as above method, but allows user to pick the channel by name.
template<typename A , typename M >
void registerProcessor (size_t channelIndex, boost::function< bool(A *, typename M::Ref)> proc)
Same as above method, but allows user to pick the channel by index.
template<typename A >
void registerProcessor (const std::string &channelName, const Messages::MetaTypeInfo &metaTypeInfo, boost::function< bool(A *, typename Messages::Header::Ref)> proc)
template<typename A >
void registerProcessor (size_t channelIndex, const Messages::MetaTypeInfo &metaTypeInfo, boost::function< bool(A *, typename Messages::Header::Ref)> proc)
size_t addProcessor (const std::string &channelName, const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
size_t addProcessor (const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
size_t addProcessor (size_t index, const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
void removeProcessor (size_t index)
Remove a processor from a given channel.
size_t getOutputChannelIndex (const std::string &name) const
Obtain an output channel index with a given name.
bool send (const Messages::Header::Ref &msg, size_t channelIndex=0)
Submit a message object to the controller for sending out on a given data channel.
bool sendAsIs (const Messages::Header::Ref &msg, size_t channelIndex=0)
Hand a message to the controller for sending out on a given data channel.
size_t getActiveChannelIndex () const
Obtain the index of the input channel that last received a message for the algorithm to process.
Data Fields
int timerCount_
Additional Inherited Members
Static Public Member Functions inherited from SideCar::Algorithms::Algorithm
static void * FormatInfoValue (const QString &value)
Obtain a C-safe value for the given QString string.
static void * FormatInfoValue (const char *value)
Obtain a C-safe value for the given character string.
Protected Member Functions inherited from SideCar::Algorithms::Algorithm
void setAlarm (int secs)
This method can be used by an Algorithm to schedule a periodic alarm to go off for itself.
virtual bool reset ()
Hook called when the algorithm is transitioning from a stopped to a running state (one of Task::kAutoDiagnostic, Task::kCalibrate, or Task::kRun).
virtual bool clearStats ()
Hook called when the algorithm is commaned to clear any statistics.
virtual bool beginAutoDiag ()
Hook called when the algorithm is entering the Task::kAutoDiagnostic state.
virtual bool beginCalibration ()
Hook called when the algorithm is entering the Task::kCalibrate state.
virtual bool beginRun ()
Hook called when the algorithm is entering the Task::kRun state.
virtual bool stop ()
Hook called when the algorithm is entering the Task::kStop state.
virtual void recordingStarted ()
Hook called when a recording has started.
virtual void recordingStopped ()
Hook called when a recording has stopped.
virtual void beginParameterChanges ()
Hook called just before algorithm runtime parameters are changed.
virtual void endParameterChanges ()
Hook called just after algorithm runtime parameters have been changed.
Detailed Description
Documentation for the algorithm ProcessTracks This task simply receives track messages and passes them along.
Definition at line 16 of file ComposeExtractions.h.
Constructor & Destructor Documentation
ComposeExtractions::ComposeExtractions (Controller & controller, Logger::Log & log)
Constructor.
Parameters
controller object that controls us
log device used for log messages
Definition at line 17 of file ComposeExtractions.cc.
Referenced by shutdown().
Member Function Documentation
void ComposeExtractions::processAlarm () virtual
This method will get called whenever an alarm expires for this Algorithm.
Derived classes can override this method. If not, it's a no-op.
Reimplemented from SideCar::Algorithms::Algorithm.
Definition at line 38 of file ComposeExtractions.cc.
References SideCar::Time::TimeStamp::asDouble(), SideCar::Algorithms::Algorithm::getLog(), LOGERROR, SideCar::Time::TimeStamp::Now(), and SideCar::Algorithms::Algorithm::send().
bool ComposeExtractions::shutdown () virtual
Implementation of the Algorithm::shutdown interface.
Dispose of any resources (such as memory) allocated from within the startup() method.
Returns
true if successful, false otherwise
Reimplemented from SideCar::Algorithms::Algorithm.
Definition at line 87 of file ComposeExtractions.cc.
References ComposeExtractions(), SideCar::Algorithms::Algorithm::FormatInfoValue(), SideCar::IO::StatusBase::setSlot(), and SideCar::Algorithms::Algorithm::shutdown().
bool ComposeExtractions::startup () virtual
Implementation of the Algorithm::startup interface.
Register runtime parameters and data processors.
Returns
true if successful, false otherwise
Reimplemented from SideCar::Algorithms::Algorithm.
Definition at line 26 of file ComposeExtractions.cc.
References SideCar::Algorithms::Algorithm::registerParameter(), SideCar::Algorithms::Algorithm::setAlarm(), and SideCar::Algorithms::Algorithm::startup().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/ComposeExtractions/ComposeExtractions.h
/Users/howes/src/sidecar/Algorithms/ComposeExtractions/ComposeExtractions.cc