SideCar: SideCar::Zeroconf::ACEMonitorFactory Class Reference
SideCar::Zeroconf::ACEMonitorFactory Class Reference
Factory of ACEMonitor objects.
#include </Users/howes/src/sidecar/Zeroconf/ACEMonitor.h>
Public Types
using Ref = boost::shared_ptr< MonitorFactory >
Public Types inherited from SideCar::Zeroconf::MonitorFactory
using Ref = boost::shared_ptr< MonitorFactory >
Public Member Functions
Monitor * make ()
Obtain a new ACEMonitor object.
Public Member Functions inherited from SideCar::Zeroconf::MonitorFactory
virtual ~MonitorFactory ()
Destructor.
Static Public Member Functions
static Ref Make ()
Factory method used to create a reference-counted ACEMonitorFactory object.
Additional Inherited Members
Protected Member Functions inherited from SideCar::Zeroconf::MonitorFactory
MonitorFactory ()
Constructor.
Detailed Description
Factory of ACEMonitor objects.
The Browser object requires a monitor factory so that the browser can give an ACEMonitor to each ServiceEntry objects the it creates.
Definition at line 72 of file ACEMonitor.h.
Member Function Documentation
ACEMonitorFactory::Ref ACEMonitorFactory::Make () static
Factory method used to create a reference-counted ACEMonitorFactory object.
Returns
new ACEMonitorFactory object
Definition at line 65 of file ACEMonitor.cc.
Referenced by SideCar::Algorithms::BugCollectorUtils::BugPlotSubscriber::BugPlotSubscriber(), SideCar::IO::StateEmitter::Log(), SideCar::IO::StatusEmitterBase::Log(), and SideCar::IO::DataSubscriber::openAndInit().
Monitor* SideCar::Zeroconf::ACEMonitorFactory::make () inline virtual
Obtain a new ACEMonitor object.
Returns
ACEMonitor object
Implements SideCar::Zeroconf::MonitorFactory.
Definition at line 87 of file ACEMonitor.h.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Zeroconf/ACEMonitor.h
/Users/howes/src/sidecar/Zeroconf/ACEMonitor.cc