SideCar: SideCar::GUI::AScope::ChannelConnectionWindow Class Reference
SideCar::GUI::AScope::ChannelConnectionWindow Class Reference
Tool window that shows the list of configured channel connections for the active Visuazlier.
#include </Users/howes/src/sidecar/GUI/AScope/ChannelConnectionWindow.h>
Public Slots
void activeDisplayViewChanged (DisplayView *displayView)
Notification that the active DisplayView has changed.
Public Slots inherited from SideCar::GUI::ToolWindowBase
virtual void activeMainWindowChanged (MainWindowBase *window)
virtual void applyInitialVisibility ()
virtual void toggleVisibility ()
virtual void showAndRaise ()
Public Member Functions
ChannelConnectionWindow (int shortcut)
Constructor.
VideoChannel * getVideoChannel (const QString &channelName)
Obtain the VideoChannel object with a given name.
ChannelConnection * getSelectedChannelConnection () const
Obtain the ChannelConnection represented by the current selection.
void setUnconnected (const QStringList &values)
Use the given list of service names as the contents of the QComboBox widget that shows the services that are unconnected.
QStringList getUnconnected () const
Obtain the list of unconnected channels.
Public Member Functions inherited from SideCar::GUI::ToolWindowBase
ToolWindowBase (const QString &name, const QString &actionTitle, int shortcut=0)
Constructor.
QAction * getShowHideAction () const
Obtain the QAction object that toggles the tool window's visibility.
void setFixedSize ()
Configure the window so that the user may not resize it.
bool getInitialVisibility () const
Determine if the application should show the window at startup.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the Log device to use for log messages from this class.
Static Public Member Functions inherited from SideCar::GUI::ToolWindowBase
static Logger::Log & Log ()
Log device for instances of this class.
static AppBase * getApp ()
Convenience method that obtains the AppBase singleton.
Additional Inherited Members
Protected Member Functions inherited from SideCar::GUI::ToolWindowBase
void showEvent (QShowEvent *event)
Event handler for show events.
void closeEvent (QCloseEvent *event)
Event handler for close events.
void hideEvent (QHideEvent *event)
Event handler for hide events.
Detailed Description
Tool window that shows the list of configured channel connections for the active Visuazlier.
Hosts buttons that allow the user to add/remove channel connections, and to change the ordering of the existing connections.
Definition at line 25 of file ChannelConnectionWindow.h.
Constructor & Destructor Documentation
ChannelConnectionWindow::ChannelConnectionWindow (int shortcut)
Constructor.
Creates and initializes the GUI objects in the window.
Parameters
shortcut key sequence to change window's visibility
\param history application's data history buffer
Definition at line 25 of file ChannelConnectionWindow.cc.
References SideCar::GUI::AScope::ChannelConnectionModel::rowCount().
Member Function Documentation
void ChannelConnectionWindow::activeDisplayViewChanged (DisplayView * displayView) slot
Notification that the active DisplayView has changed.
Notify the model object of the change by giving it the new DisplayView's Plotter.
Parameters
displayView the active DisplayView (may be NULL)
Definition at line 183 of file ChannelConnectionWindow.cc.
References SideCar::GUI::ToolWindowBase::closeEvent(), SideCar::GUI::ToolWindowBase::getApp(), SideCar::GUI::AScope::DisplayView::getVisualizer(), Log(), LOGINFO, SideCar::GUI::AScope::ChannelConnectionModel::saveVideoChannelSettings(), and SideCar::GUI::AScope::ChannelConnectionModel::setVisualizer().
ChannelConnection * ChannelConnectionWindow::getSelectedChannelConnection () const
Obtain the ChannelConnection represented by the current selection.
Note that there may not be a selection, in which case this will return NULL.
Returns
ChannelConnection object or NULL
Definition at line 96 of file ChannelConnectionWindow.cc.
References SideCar::GUI::AScope::ChannelConnectionModel::getChannelConnection(), SideCar::GUI::ServiceEntry::getName(), getUnconnected(), Log(), LOGERROR, LOGINFO, SideCar::GUI::AScope::ChannelConnectionModel::makeConnection(), SideCar::GUI::AScope::ChannelConnectionModel::moveDown(), SideCar::GUI::AScope::ChannelConnectionModel::moveUp(), SideCar::GUI::AScope::ChannelConnectionModel::removeConnection(), SideCar::GUI::AScope::ChannelConnectionModel::rowCount(), and setUnconnected().
QStringList ChannelConnectionWindow::getUnconnected () const
Obtain the list of unconnected channels.
Returns
QString list
Definition at line 81 of file ChannelConnectionWindow.cc.
Referenced by getSelectedChannelConnection().
VideoChannel * ChannelConnectionWindow::getVideoChannel (const QString & channelName)
Obtain the VideoChannel object with a given name.
Parameters
channelName the name to look for
Returns
found VideoChannel object, or NULL
Definition at line 90 of file ChannelConnectionWindow.cc.
References SideCar::GUI::AScope::ChannelConnectionModel::getVideoChannel().
Referenced by SideCar::GUI::AScope::Visualizer::Visualizer().
Logger::Log & ChannelConnectionWindow::Log () static
Obtain the Log device to use for log messages from this class.
Returns
Log reference
Definition at line 18 of file ChannelConnectionWindow.cc.
References Logger::Log::Find().
Referenced by activeDisplayViewChanged(), and getSelectedChannelConnection().
void ChannelConnectionWindow::setUnconnected (const QStringList & values)
Use the given list of service names as the contents of the QComboBox widget that shows the services that are unconnected.
Parameters
values service names
Definition at line 68 of file ChannelConnectionWindow.cc.
Referenced by getSelectedChannelConnection(), and SideCar::GUI::AScope::ChannelConnectionModel::setVisualizer().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/AScope/ChannelConnectionWindow.h
/Users/howes/src/sidecar/GUI/AScope/ChannelConnectionWindow.cc