SideCar: Buffer< T > Class Template Reference
Buffer< T > Class Template Reference
A matrix class that supports VSIPL++ subviews.
#include </Users/howes/src/sidecar/Utils/Buffer/Buffer.h>
Public Types
using Row = BufferRow< T >
Class for viewing rows in this Buffer.
using const_Row = const_BufferRow< T >
Class for viewing rows in this Buffer.
using Col = BufferCol< T >
Class for viewing columns in this Buffer.
using Column = BufferCol< T >
Long form of Col.
using Mat = BufferMat< T >
Class for viewing submatrices in this Buffer.
using Matrix = BufferMat< T >
Long form of Mat.
Public Member Functions
Buffer (size_t dr, size_t dc, size_t wr=0, size_t wc=0, T *mem=0)
Constructs the Buffer object.
~Buffer ()
Deletes the memory buffer if it was created internally.
void print (std::ostream &os) const
void clearData (T mean=0, T stddev=0)
Clear the data area.
size_t getDataRows () const
size_t getDataCols () const
T get (size_t row, size_t col) const
T sget (size_t row, size_t col) const
A "safe" get.
void clearWindow (T mean=0, T stddev=0)
Clear the window buffer area.
size_t getWindowRows () const
size_t getWindowCols () const
void resizeWindow (size_t wr=0, size_t wc=0)
Resizes the Buffer to support a larger window.
template<>
void print (std::ostream &os) const
Friends
class BufferRowBase< T, vsip::Vector< T >, true >
class BufferRowBase< T, vsip::const_Vector< T >, false >
class BufferRow< T >
class BufferCol< T >
class BufferMat< T >
Additional Inherited Members
Protected Types inherited from BufferModel
using ViewList = std::list< const BufferView * >
Protected Attributes inherited from BufferModel
ViewList views
Detailed Description
template<class T>
class Buffer< T >
A matrix class that supports VSIPL++ subviews.
The Buffer class and its friend classes BufferRow, BufferCol, and BufferMat together provide a convenient framework for creating a 2-dimensional array of data that is accessible using VSIPL++.
As shown in Figure 1, the Buffer is defined by two matrix sizes; the data matrix is padded such that it may be convolved with a smaller matrix up to a maximum specified size. Given this maximum window size, the padding allows convolving arbitrary subwindows of the Buffer without fear of accessing undefined memory. Also, the data rows are "wrapped" so that the Buffer may be used as a rolling window.
Figure 1: Conceptual layout
Figure 2 shows the underlying memory layout which supports the conceptual model. The end user should understand two important decisions which were made. First, a single space is used to buffer both ends of the data; this conserves memory, but it could also cause strange side effects if the user writes to this area (only possible with the BufferMat view). Second, wrapping of the rows is achieved by copying the first few rows to the end of the matrix; in either location, updates to the first few rows are only copied to the other location when the view is flushed; this copy-on-flush policy allows the use of unmodified VSIPL++ view classes.
Figure 2: Physical layout
Definition at line 34 of file Buffer.h.
Constructor & Destructor Documentation
template<class T> Buffer< T >::Buffer (size_t dr, size_t dc, size_t wr = 0, size_t wc = 0, T * mem = 0)
Constructs the Buffer object.
Does not initialize the Buffer memory. Allocates internal buffer memory if an external memory location is not passed.
Parameters
dr Number of data rows
dc Number of data columns
wr Maximum number of window rows
wc Maximum number of window columns
mem Externally-allocated memory, of minimum size (dr+wr)*(dc+wc)
Definition at line 197 of file Buffer.h.
Member Function Documentation
template<class T> void Buffer< T >::clearData (T mean = 0, T stddev = 0)
Clear the data area.
Fills the data area with normally distributed random numbers.
Parameters
mean Mean of the distribution
stddev Standard deviation
Definition at line 219 of file Buffer.h.
template<class T> void Buffer< T >::clearWindow (T mean = 0, T stddev = 0)
Clear the window buffer area.
Fills the window buffer area with normally distributed random numbers.
Parameters
mean Mean of the distribution
stddev Standard deviation
Definition at line 288 of file Buffer.h.
Referenced by Buffer< VideoT >::sget().
template<class T> T Buffer< T >::get (size_t row, size_t col) const inline
Parameters
row Not bounds checked
col Not bounds checked
Returns
the value at (row, col)
Definition at line 109 of file Buffer.h.
Referenced by SideCar::Algorithms::SegmentStats::startup().
template<class T> size_t Buffer< T >::getDataCols () const inline
Returns
Number of columns allocated for data
Definition at line 100 of file Buffer.h.
Referenced by SideCar::Algorithms::SegmentStats::startup().
template<class T> size_t Buffer< T >::getDataRows () const inline
Returns
Number of rows allocated for data
Definition at line 95 of file Buffer.h.
template<class T> size_t Buffer< T >::getWindowCols () const inline
Returns
Number of columns allocated for windowing
Definition at line 147 of file Buffer.h.
template<class T> size_t Buffer< T >::getWindowRows () const inline
Returns
Number of rows allocated for windowing
Definition at line 142 of file Buffer.h.
template<class T > void Buffer< T >::resizeWindow (size_t wr = 0, size_t wc = 0)
Resizes the Buffer to support a larger window.
Preserves the data section, but does not initialize the window buffer area.
Definition at line 356 of file Buffer.h.
Referenced by Buffer< VideoT >::getWindowCols().
template<class T> T Buffer< T >::sget (size_t row, size_t col) const inline
A "safe" get.
Parameters
row Bounds checked
col Bounds checked
Returns
the value at (row, col)
Definition at line 119 of file Buffer.h.
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/Utils/Buffer/Buffer.h