SideCar: SideCar::VsipVector< T, DatumType > Class Template Reference
SideCar::VsipVector< T, DatumType > Class Template Reference
Provides a simple wrapper around std::vector-like data structures.
#include </Users/howes/src/sidecar/Utils/VsipVector.h>
Public Member Functions
VsipVector (T &base)
Constructor.
VsipVector (T &base, size_t size)
Wraps size entries, starting with T[0].
VsipVector (T &base, size_t start, size_t stop)
Wraps T[start] to T[stop].
void admit (bool read)
Set whether VSIPL will use existing data found in the external array given in the constructor.
void release (bool flush)
Set whether VSIPL will flush any data from internal storage to the external array given in the constructor.
Data Fields
vsip::Vector< DatumType > v
Detailed Description
template<class T, class DatumType = typename T::value_type>
class SideCar::VsipVector< T, DatumType >
Provides a simple wrapper around std::vector-like data structures.
T needs to have T.size() and T[0] operators. DatumType needs to match the size of entries in T.
Definition at line 13 of file VsipVector.h.
Constructor & Destructor Documentation
template<class T, class DatumType = typename T::value_type> SideCar::VsipVector< T, DatumType >::VsipVector (T & base) inline
Constructor.
Wraps T.size() entries, starting with T[0].
Definition at line 19 of file VsipVector.h.
template<class T, class DatumType = typename T::value_type> SideCar::VsipVector< T, DatumType >::VsipVector (T & base, size_t start, size_t stop) inline
Wraps T[start] to T[stop].
Parameters
start initial index
stop final index
Definition at line 33 of file VsipVector.h.
Member Function Documentation
template<class T, class DatumType = typename T::value_type> void SideCar::VsipVector< T, DatumType >::admit (bool read) inline
Set whether VSIPL will use existing data found in the external array given in the constructor.
Parameters
read if true VSIPL will use existing data
Definition at line 40 of file VsipVector.h.
Referenced by SideCar::Algorithms::Difference::reset(), SideCar::Algorithms::VideoInterpolation::reset(), SideCar::Algorithms::Scale::startup(), SideCar::Algorithms::Offset::startup(), and SideCar::Algorithms::IQ2AmplitudePhase::startup().
template<class T, class DatumType = typename T::value_type> void SideCar::VsipVector< T, DatumType >::release (bool flush) inline
Set whether VSIPL will flush any data from internal storage to the external array given in the constructor.
Parameters
read if true VSIPL will flush data to the external array
Definition at line 47 of file VsipVector.h.
Referenced by SideCar::Algorithms::Difference::reset(), SideCar::Algorithms::VideoInterpolation::reset(), SideCar::Algorithms::Scale::startup(), SideCar::Algorithms::Offset::startup(), and SideCar::Algorithms::IQ2AmplitudePhase::startup().
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/Utils/VsipVector.h