SideCar: Logger::Configurator Class Reference
Logger::Configurator Class Reference
Logger configuration manager class.
#include </Users/howes/src/sidecar/Logger/Configurator.h>
Data Structures
struct ConfiguratorException
Top-level exception class used by all Configurator exceptions.
struct InvalidCommand
Exception thrown if command is not writer or priority.
struct InvalidFileFlag
Exception thrown if FileWriter definition has an invalid option name.
struct InvalidFormatterType
Exception thrown if formatter command does not have a valid type value.
struct InvalidRemoteSyslogFlag
Exception thrown if RemoteSyslogWriter definition has an invalid option name.
struct InvalidStreamFlag
Exception thrown if StreamWriter definition has an invalid option name.
struct InvalidSyslogFlag
Exception thrown if SyslogWriter definition has an invalid option name.
struct InvalidWriterType
Exception thrown if writer command does not have a valid type value.
struct MissingFacility
Exception thrown if SyslogWriter definition has the facility option, but no facility value.
struct MissingFileMode
Exception thrown if FileWriter definition has the mode option, but does not have a mode value.
struct MissingFilePath
Exception thrown if FileWriter definition does not have a file path value.
struct MissingFormatterPattern
Exception thrown if formatter pattern does not have a format specifier string.
struct MissingFormatterType
Exception thrown if formatter command does not have a type value.
struct MissingIdent
Exception thrown if SyslogWriter definition does not have an ident value.
struct MissingLoggerName
Exception thrown if no name found for Log instance.
struct MissingMaxSize
Exception thrown if RollingWriter definition has the size option, but no size value.
struct MissingNumVersions
Exception thrown if RollingWriter definition has the versions option, but no versions value.
struct MissingPriorityName
Exception thrown if priority command does not have a value.
struct MissingRemoteHost
Exception thrown if RemoteSyslogWriter does not have a host name value.
struct MissingRemotePort
Exception thrown if RemoteSyslogWriter definition has the port option, but no port value.
struct MissingWriterType
Exception thrown if no writer type found.
struct UnterminatedString
Exception thrown if a closing single- or double-quote is not found in a configuration line.
Public Member Functions
Configurator ()
Default constructor.
Configurator (std::istream &is)
Constructor.
void load (std::istream &is)
Read configuration settings from a stream.
Protected Member Functions
const std::set< Log * > & managed () const
Accessor for the set of Log objects created by Configurator::load.
Detailed Description
Logger configuration manager class.
A configuration is defined by the contents of a config file (or stream), where each line specifies a Log object and its setup. The format of a config line is:
NAME [priority P] [[writer W [W_ARGS] formatter F [F_ARGS]] ...]
where NAME is the name of the Log object (including lineage); P is the priority level the Log object will accept messages; W is the name of a Writer object to assign to the Log object; W_ARGS are any optional settings for the Writer constructor; F is the name of the Formatter object to use for the Writer; and F_ARGS are any optional settings for the Formatter constructor.
The priority and writer constructs are optional; there may be either or both on the same line, or they may appear on separate config lines. There may even be more than one writer specification on the same line, or each one may appear on a separate config line. In short, all settings are additive and all config lines are processed in the order in which they appear in a file or stream.
The following are valid W values for the writer keyword:
cout
Creates a new StreamWriter object, writing to the std::cout stream. The only option available to this (and all other) StreamWriter object is
[flush]
which controls whether the stream's flush method is called after each log message write.
clog
Same as above except the StreamWriter object uses std::clog for its output stream
cerr
Same as above except the StreamWriter object uses std::cerr for its output stream
file
Creates a new FileWriter object. The arguments to a FileWriter are:
PATH [nappend | mode M]
where PATH specifies a file used to hold log messages (required), and M is an optional mode specification used for newly-created files (see open(2))
If nappend is found, then FileWriter will overwrite any existing log file; the default behavior is to append to the end of an existing file.
rolling
Create a new RollingWriter object. The arguments to a RollingWriter are:
PATH [nappend | mode M | versions V | size S]
where PATH, M, and nappend are the same as for FileWriter; V is the number of versions of the log file to keep around; S is the maximum size of the log file – if the log file reaches this size, then the file is versioned, and then a new log file is created.
syslog
Create a new SyslogWriter object which sends all log messages to a syslog daemon (see syslog(3C)). The arguments to a SyslogWriter are:
IDENT [facility F]
where IDENT is the required identification string given to openlog and found in all log messages generated by syslog. F is an optional facility specification as defined by the syslog implementation.
remote
Create a new RemoteSyslogWriter object which will send all log messages over the network as datagrams to a remote syslog server. The arguments to a RemoteSyslogWriter are:
HOST [port P]
where HOST is the required host name or IP address of the remote host to connect to, and P is an optional port number (default is 514).
The following are valid F values for the formatter keyword:
terse
Use a TerseFormatter object for log message formatting.
verbose
Use a VerboseFormatter object for log message formatting.
pattern
Use a PatternFormatter object for log message formatting. The sole argument to a PatternFormatter is a string that specifies how to format a log message.
Test Cases:
see ConfiguratorTests.cc
Definition at line 101 of file Configurator.h.
Constructor & Destructor Documentation
Logger::Configurator::Configurator () inline
Default constructor.
No configuration is loaded.
Definition at line 238 of file Configurator.h.
References load().
Configurator::Configurator (std::istream & is)
Constructor.
Load configuration from a stream
Parameters
is C++ standard input stream to read from
Definition at line 142 of file Configurator.cc.
References load().
Member Function Documentation
void Configurator::load (std::istream & is)
Read configuration settings from a stream.
Parameters
is C++ standard input stream to read from
Definition at line 148 of file Configurator.cc.
References Logger::Log::addWriter(), Logger::Priority::Find(), Logger::Log::Find(), Logger::Log::setPriorityLimit(), and Logger::Log::setPropagate().
Referenced by Configurator(), and Logger::ConfiguratorFile::reload().
const std::set<Log*>& Logger::Configurator::managed () const inline protected
Accessor for the set of Log objects created by Configurator::load.
Returns
set of managed Log objects
Definition at line 258 of file Configurator.h.
Referenced by Logger::ConfiguratorFile::reload().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Logger/Configurator.h
/Users/howes/src/sidecar/Logger/Configurator.cc