SideCar: SideCar::Algorithms::BugCollectorUtils::BugPlotReader Class Reference
SideCar::Algorithms::BugCollectorUtils::BugPlotReader Class Reference
Multicast data reader of BugPlot messages.
#include </Users/howes/src/sidecar/Algorithms/BugCollector/BugPlotSubscriber.h>
Public Member Functions
BugPlotReader (BugCollector &bugCollector)
Constructor.
bool openAndInit (const Zeroconf::ServiceEntry::Ref &service)
Attempt to establish a multicast connection to the BugPlot publisher described by the given ServiceEntry object.
int close (u_long flags)
Unsubscribe from the BugPlot publisher.
int handle_input (ACE_HANDLE handle)
Event handler invoked when data is available on the subscription socket.
ACE_HANDLE get_handle () const
Obtain the socket descriptor for the connection.
const std::string & getServiceName () const
Obtain the name of the publisher we are subscribed to.
void sendHeartBeat (const char *msg="HI") const
Send a heartbeat message to the remote bug emitter to keep it sending data to us.
Detailed Description
Multicast data reader of BugPlot messages.
Created by a BugPlotSubscriber instance whenever it detects a new BugPlot publisher. Forwards each incoming BugPlot message to the BugCollector algorithm it knows about via its BugCollector::process() method.
Definition at line 25 of file BugPlotSubscriber.h.
Constructor & Destructor Documentation
BugPlotReader::BugPlotReader (BugCollector & bugCollector)
Constructor.
Only performs simple initialization.
Parameters
bugCollector the Bugcollector algorithm to forward BugPlot messages to
Definition at line 21 of file BugPlotSubscriber.cc.
Member Function Documentation
int BugPlotReader::close (u_long flags)
Unsubscribe from the BugPlot publisher.
Parameters
flags ignored
Returns
Definition at line 94 of file BugPlotSubscriber.cc.
References SideCar::Algorithms::Algorithm::getLog(), and sendHeartBeat().
ACE_HANDLE BugPlotReader::get_handle () const
Obtain the socket descriptor for the connection.
Returns
Definition at line 111 of file BugPlotSubscriber.cc.
References SideCar::IO::ReaderDevices::MulticastSocket::getDevice().
const std::string& SideCar::Algorithms::BugCollectorUtils::BugPlotReader::getServiceName () const inline
Obtain the name of the publisher we are subscribed to.
Returns
publisher name
Definition at line 71 of file BugPlotSubscriber.h.
References sendHeartBeat().
int BugPlotReader::handle_input (ACE_HANDLE handle)
Event handler invoked when data is available on the subscription socket.
Parameters
handle socket identifier
Returns
0 if no error, 1 if more data is available, -1 if an error
Definition at line 67 of file BugPlotSubscriber.cc.
References SideCar::IO::DatagramReader::fetchInput(), SideCar::Algorithms::Algorithm::getLog(), SideCar::IO::Reader::getMessage(), SideCar::IO::Reader::isMessageAvailable(), LOGDEBUG, and SideCar::Algorithms::BugCollector::process().
bool BugPlotReader::openAndInit (const Zeroconf::ServiceEntry::Ref & service)
Attempt to establish a multicast connection to the BugPlot publisher described by the given ServiceEntry object.
Parameters
service description of the BugPlot publisher to subscribe to
Returns
true if successful
Definition at line 30 of file BugPlotSubscriber.cc.
References SideCar::Zeroconf::ResolvedEntry::getHost(), SideCar::Algorithms::Algorithm::getLog(), SideCar::Zeroconf::ResolvedEntry::getPort(), SideCar::Zeroconf::ResolvedEntry::getTextEntry(), SideCar::IO::ReaderDevices::MulticastSocket::join(), LOGERROR, and sendHeartBeat().
Referenced by SideCar::Algorithms::BugCollectorUtils::BugPlotSubscriber::setPrefix().
void BugPlotReader::sendHeartBeat (const char * msg = "HI") const
Send a heartbeat message to the remote bug emitter to keep it sending data to us.
Parameters
msg the message to send (either "HI" or "BYE")
Definition at line 104 of file BugPlotSubscriber.cc.
Referenced by close(), getServiceName(), and openAndInit().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/BugCollector/BugPlotSubscriber.h
/Users/howes/src/sidecar/Algorithms/BugCollector/BugPlotSubscriber.cc