SideCar: SideCar::GUI::BScope::PastImage Class Reference
SideCar::GUI::BScope::PastImage Class Reference
Public Slots
void setPhantomCursor (const QPointF &pos)
void showPhantomCursor (bool state)
void clearPhantomCursor ()
void setLabel (const QString &label)
Public Member Functions
PastImage (QWidget *parent, const QImage &image, const QSize &size=QSize())
void setImage (const QImage &image)
void setImageSize (const QSize &size)
const QImage & getImage () const
QSize sizeHint () const
QSize minimumSizeHint () const
QSize maximumSizeHint () const
bool getShowPhantomCursor () const
Static Public Member Functions
static Logger::Log & Log ()
Obtain the Log device for PastImage instances.
Detailed Description
Definition at line 19 of file PastImage.h.
Member Function Documentation
Logger::Log & PastImage::Log () static
Obtain the Log device for PastImage instances.
Returns
Log device
Definition at line 23 of file PastImage.cc.
References Logger::Log::Find(), SideCar::GUI::BScope::App::GetApp(), LOGINFO, and SideCar::GUI::AppBase::setPhantomCursor().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/BScope/PastImage.h
/Users/howes/src/sidecar/GUI/BScope/PastImage.cc