SideCar: SideCar::IO::MessageManager Class Reference
SideCar::IO::MessageManager Class Reference
Manager class for all message objects in the SideCar system.
#include </Users/howes/src/sidecar/IO/MessageManager.h>
Data Structures
struct AllocationStats
Collection of statistics that describe how much memory is allocated by the Utils::Pool objects used internally by MessageManager instances.
struct MetaData
Internal class that contains the channel ID the message belongs to and a reference to a SideCar message object if one was set.
Public Types
enum MessageTypes { kRawData = ACE_Message_Block::MB_DATA, kMetaData, kControl = ACE_Message_Block::MB_USER }
Definition of the various message types supported by the MessageManager.
using Ref = boost::shared_ptr< MessageManager >
Public Member Functions
MessageManager (ACE_Message_Block *data, const Messages::MetaTypeInfo *metaTypeInfo=0)
Constructor that takes raw data from an ACE_Message_Block object.
MessageManager (const Messages::Header::Ref &native)
Constructor for SideCar messages.
~MessageManager ()
Destructor.
bool isValid () const
Determine if there is a message held by this MessageManager object.
ACE_Message_Block::ACE_Message_Type getMessageType () const
Obtain the raw message type of the held data block.
bool hasRawData () const
Determine if the held data block is non-native.
bool hasMetaData () const
Determine if the held data block contains a native SideCar message, in either raw or encoded form.
bool hasControlMessage () const
Determine if the held data block contains a control message.
ControlMessage::Type getControlMessageType () const
Obtain the ControlMessage::Type value for the held data block.
bool isParametersChangeRequest () const
Determine if held data message is a ParametersChangeRequest control message.
bool isProcessingStateChangeRequest () const
Determine if held data message is a ProcessingStateChangeRequest control message.
bool isRecordingStateChangeRequest () const
Determine if held data message is a RecordingStateChangeRequest control message.
bool isShutdownRequest () const
Determine if held data message is a ShutdownRequest control message.
bool hasNative () const
Determine if there is a native SideCar message associated with the data block.
bool hasEncoded () const
Determine if there is encoded (marshalled) data available.
Messages::MetaTypeInfo::Value getNativeMessageType () const
Obtain the message type key for the held message.
bool hasNativeMessageType (Messages::MetaTypeInfo::Value key) const
Determine if the held message has a given message type key.
size_t getMessageSize () const
Obtain the number of bytes of managed data.
ACE_Message_Block * getMessage ()
Obtain a shallow copy of the held ACE_Message_Block.
ACE_Message_Block * getEncoded () const
Obtain encoded message data.
template<typename T >
boost::shared_ptr< T > getNative (bool checked=true) const
Obtain a shared reference to a held native message.
Messages::Header::Ref getNative () const
Obtain a reference to the native SideCar message.
template<typename T >
T getControlMessage () const
Obtain a control message constructed from the held ACE_Message_Block object.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for MessageManager objects.
static AllocationStats GetAllocationStats ()
Class method that returns information about memory allocation performed by internal MesageManager memory pools.
static ACE_Message_Block * MakeMessageBlock (size_t size, int type=kRawData)
Create a new ACE_Message_Block with a given capacity.
static ACE_Message_Block * MakeControlMessage (ControlMessage::Type type, size_t size)
Create a new ACE_Message_Block with the type kStateChangeType.
static int GetMessageType (ACE_Message_Block *data)
Obtain the message type found in a data block.
static bool IsRawMessage (ACE_Message_Block *data)
Determine if the given data block is a raw, non-native message.
static bool IsDataMessage (ACE_Message_Block *data)
Determine if the given data block contains a native message.
static bool IsControlMessage (ACE_Message_Block *data)
Determine if the given data block contains a control message.
static ControlMessage::Type GetControlMessageType (ACE_Message_Block *data)
Obtain the ControlMessage::Type value from a given data block.
Detailed Description
Manager class for all message objects in the SideCar system.
The ACE framework uses ACE_Message_Block objects to pass data from one ACE_Task to another. For native SideCar C++ objects, one would like to not have to create an ACE_Message_Block from them in order to use this infrastructure. The approach with the MessageManager is to properly record when an ACE_Message_Block contains encoded (marshalled) data, and when it contains a reference to a native SideCar object.
When the manager receives an IO reader in its constructor, the manager creates a new ACE_Message_Block of type kMetaDataType and then links the readers' encoded data block to it. The new block contains a MetaData structure which holds the channel ID and an unset reference pointer for Messages::Header objects. If in the future, the manager receives a native SideCar message object derived from Messages::Header, it releases the encoded data block.
The manager provides marshalling facilities that take a stored native SideCar mesasge object and encodes it into the common data representation (CDR) format. The call getEncoded() returns the result of this process. The results of the encoding are cached so that subsequent getEncoded() calls just return the result of the original encoding.
The MessageManager uses three custom allocators to provide fast allocation and deallocation of ACE_Message_Block, ACE_Data_Block, and MessageManager::MetaData objects. These custom allocators are based on the Utils::Pool class. The MessageManager class method GetAllocationStats() returns a snapshot of the allocation statistics for all of the custom allocators.
Definition at line 41 of file MessageManager.h.
Member Enumeration Documentation
enum SideCar::IO::MessageManager::MessageTypes
Definition of the various message types supported by the MessageManager.
Enumerator
kRawData
Raw, non-native data, such as messages from VME or TSPI servers.
kMetaData
Native message data (eg PRIMessage)
kControl
Control message.
NOTE: must be the last message type, since MessageManager adds the ControlMessage::Type value of the message to this value (see IsControlMessage() and GetControlMessageType())
Definition at line 48 of file MessageManager.h.
Constructor & Destructor Documentation
MessageManager::MessageManager (ACE_Message_Block * data, const Messages::MetaTypeInfo * metaTypeInfo = 0)
Constructor that takes raw data from an ACE_Message_Block object.
Takes ownership of the data block.
Parameters
encoded object containing the raw message data
metaTypeInfo message type of the encoded data. If NULL, then the type will be obtained directly from the message data.
Definition at line 273 of file MessageManager.cc.
References SideCar::Messages::MetaTypeInfo::getCDRLoader(), IsControlMessage(), kMetaData, kRawData, Log(), LOGDEBUG, LOGTIN, LOGTOUT, SideCar::IO::MessageManager::MetaData::native, SideCar::IO::MessageManager::MetaData::size, and Logger::ProcLog::thrower().
MessageManager::MessageManager (const Messages::Header::Ref & native)
Constructor for SideCar messages.
Increases the reference count of the given message by one.
Parameters
native reference to a SideCar message to manage
cid channel ID to assign
Definition at line 263 of file MessageManager.cc.
References Log(), LOGINFO, SideCar::IO::MessageManager::MetaData::native, and SideCar::IO::MessageManager::MetaData::size.
MessageManager::~MessageManager ()
Destructor.
Releases the underlying ACE_Message_Block object.
Definition at line 336 of file MessageManager.cc.
References kMetaData, Log(), and LOGINFO.
Member Function Documentation
MessageManager::AllocationStats MessageManager::GetAllocationStats () static
Class method that returns information about memory allocation performed by internal MesageManager memory pools.
Returns
AllocationStats object
Definition at line 436 of file MessageManager.cc.
References SideCar::IO::MessageManager::AllocationStats::dataBlocks, SideCar::IO::MessageManager::AllocationStats::messageBlocks, and SideCar::IO::MessageManager::AllocationStats::metaData.
Referenced by SideCar::GUI::PPIDisplay::History::addVideo().
template<typename T > T SideCar::IO::MessageManager::getControlMessage () const inline
Obtain a control message constructed from the held ACE_Message_Block object.
NOTE: this is not valid unless hasControlMessage() is true.
Returns
ControlMessage instance
Definition at line 345 of file MessageManager.h.
static ControlMessage::Type SideCar::IO::MessageManager::GetControlMessageType (ACE_Message_Block * data) inline static
Obtain the ControlMessage::Type value from a given data block.
Only valid if IsControlMessage(data) is true.
Parameters
data message block to query
Returns
ControlMessage::Type value
Definition at line 173 of file MessageManager.h.
Referenced by SideCar::IO::Task::put().
ControlMessage::Type SideCar::IO::MessageManager::getControlMessageType () const inline
Obtain the ControlMessage::Type value for the held data block.
Only valid if hasControlMessage() returns true.
Returns
ControlMessage::Type value
Definition at line 236 of file MessageManager.h.
ACE_Message_Block * MessageManager::getEncoded () const
Obtain encoded message data.
Only valid if the instance holds a native SideCar mesage object.
Returns
ACE_Message_Block pointer (may be NULL)
Definition at line 371 of file MessageManager.cc.
References hasNative(), SideCar::IO::Preamble::kCDRStreamSize, Log(), LOGDEBUG, LOGERROR, and SideCar::IO::MessageManager::MetaData::native.
Referenced by SideCar::Algorithms::Recorder::stop(), SideCar::IO::FileWriterTask::svc(), and SideCar::IO::Writer::write().
ACE_Message_Block* SideCar::IO::MessageManager::getMessage () inline
Obtain a shallow copy of the held ACE_Message_Block.
Caller is responsible for releasing it. This is a very fast operation since new ACE_Message_Block objects are fetched from an allocation pool, and they only contain pointers and offset into an ACE_Data_Block, which is not replicated but shared among ACE_Message_Block instances.
Returns
new ACE_Message_Block object
Definition at line 309 of file MessageManager.h.
Referenced by SideCar::IO::ServerSocketWriterTask::close(), SideCar::Algorithms::Controller::close(), InputTask::deliverDataMessage(), SideCar::IO::Task::doClearStatsRequest(), SideCar::IO::VMEReaderTask::openAndInit(), SideCar::GUI::PRIEmitter::MainWindow::openFile(), SideCar::IO::Task::putInChannel(), and SideCar::GUI::Playback::Emitter::setEmitting().
size_t SideCar::IO::MessageManager::getMessageSize () const inline
Obtain the number of bytes of managed data.
If the data was given to the MessageManager in encoded form, then the value is the number of raw bytes received. Otherwise, it is the number of samples in the message, the value returned by Header::getSize() method.
Returns
message size
Definition at line 300 of file MessageManager.h.
Referenced by PRIChunkerOutputTask::deliverDataMessage().
static int SideCar::IO::MessageManager::GetMessageType (ACE_Message_Block * data) inline static
Obtain the message type found in a data block.
Parameters
data message block to query
Returns
message type
Definition at line 140 of file MessageManager.h.
ACE_Message_Block::ACE_Message_Type SideCar::IO::MessageManager::getMessageType () const inline
Obtain the raw message type of the held data block.
Note that this value should match one of the values defined in MessageTypes.
Returns
ACE_Message_Block::ACE_Message_Type value.
Definition at line 211 of file MessageManager.h.
Referenced by SideCar::IO::FileWriterTask::svc().
template<typename T > boost::shared_ptr<T> SideCar::IO::MessageManager::getNative (bool checked = true) const inline
Obtain a shared reference to a held native message.
NOTE: the reference may point to nothing if the type of the held message is not compatible with the type requested in the template call (or there is no native message held by the MessageManager)
Parameters
checked if true and the cast fails, throws std::bad_cast
\return shared reference to held native SideCar message
Definition at line 326 of file MessageManager.h.
Referenced by SideCar::IO::IOTask::acquireExternalMessage(), SideCar::GUI::MessageReader::addRawData(), ConverterInputTask::deliverDataMessage(), InputTask::deliverDataMessage(), PRIInfoInputTask::deliverDataMessage(), SideCar::Algorithms::Controller::injectProcessingStateChange(), SideCar::GUI::RTCLMessageReader::Make(), SideCar::IO::Task::put(), SideCar::GUI::Playback::Emitter::setEmitting(), and SideCar::IO::FileWriterTask::svc().
Messages::Header::Ref SideCar::IO::MessageManager::getNative () const inline
Obtain a reference to the native SideCar message.
Only valid if hasNative() returns true.
Returns
shared reference to held native SideCar message
Definition at line 337 of file MessageManager.h.
Messages::MetaTypeInfo::Value SideCar::IO::MessageManager::getNativeMessageType () const inline
Obtain the message type key for the held message.
Returns
current message type key, kInvalid if not a valid message
Definition at line 282 of file MessageManager.h.
Referenced by SideCar::Algorithms::Sink::deliverDataMessage(), and SideCar::Algorithms::Controller::injectProcessingStateChange().
bool SideCar::IO::MessageManager::hasControlMessage () const inline
Determine if the held data block contains a control message.
Returns
true if so
Definition at line 229 of file MessageManager.h.
bool SideCar::IO::MessageManager::hasEncoded () const inline
Determine if there is encoded (marshalled) data available.
NOTE: although this is thread-safe, another thread could give the held message encoded data at any time. See getEncoded().
Returns
true if so
Definition at line 276 of file MessageManager.h.
bool SideCar::IO::MessageManager::hasMetaData () const inline
Determine if the held data block contains a native SideCar message, in either raw or encoded form.
Returns
true if so
Definition at line 223 of file MessageManager.h.
bool SideCar::IO::MessageManager::hasNative () const inline
Determine if there is a native SideCar message associated with the data block.
Returns
true if native message
Definition at line 269 of file MessageManager.h.
Referenced by SideCar::Algorithms::Sink::deliverDataMessage(), getEncoded(), and SideCar::IO::ClientSocketWriterTask::Make().
bool SideCar::IO::MessageManager::hasNativeMessageType (Messages::MetaTypeInfo::Value key) const inline
Determine if the held message has a given message type key.
Parameters
key value to check for
Returns
true if so
Definition at line 292 of file MessageManager.h.
Referenced by SideCar::IO::FileWriterTask::svc().
bool SideCar::IO::MessageManager::hasRawData () const inline
Determine if the held data block is non-native.
Returns
true if so
Definition at line 217 of file MessageManager.h.
static bool SideCar::IO::MessageManager::IsControlMessage (ACE_Message_Block * data) inline static
Determine if the given data block contains a control message.
Parameters
data message block to query
Returns
true if so
Definition at line 164 of file MessageManager.h.
Referenced by MessageManager(), SideCar::IO::Task::processMessage(), and SideCar::IO::Task::put().
static bool SideCar::IO::MessageManager::IsDataMessage (ACE_Message_Block * data) inline static
Determine if the given data block contains a native message.
Parameters
data message block to query
Returns
true if so
Definition at line 156 of file MessageManager.h.
Referenced by SideCar::IO::ServerSocketWriterTask::close(), and SideCar::IO::Task::put().
bool SideCar::IO::MessageManager::isParametersChangeRequest () const inline
Determine if held data message is a ParametersChangeRequest control message.
Returns
true if so
Definition at line 242 of file MessageManager.h.
bool SideCar::IO::MessageManager::isProcessingStateChangeRequest () const inline
Determine if held data message is a ProcessingStateChangeRequest control message.
Returns
true if so
Definition at line 249 of file MessageManager.h.
static bool SideCar::IO::MessageManager::IsRawMessage (ACE_Message_Block * data) inline static
Determine if the given data block is a raw, non-native message.
Parameters
data message block to query
Returns
true if so
Definition at line 148 of file MessageManager.h.
bool SideCar::IO::MessageManager::isRecordingStateChangeRequest () const inline
Determine if held data message is a RecordingStateChangeRequest control message.
Returns
true if so
Definition at line 256 of file MessageManager.h.
bool SideCar::IO::MessageManager::isShutdownRequest () const inline
Determine if held data message is a ShutdownRequest control message.
Returns
true if so
Definition at line 263 of file MessageManager.h.
Referenced by ConverterInputTask::deliverDataMessage(), InputTask::deliverDataMessage(), PRIInfoInputTask::deliverDataMessage(), and PRIChunkerOutputTask::deliverDataMessage().
bool SideCar::IO::MessageManager::isValid () const inline
Determine if there is a message held by this MessageManager object.
Returns
true if so
Definition at line 204 of file MessageManager.h.
Logger::Log & MessageManager::Log () static
Obtain the log device for MessageManager objects.
Returns
log device
Definition at line 231 of file MessageManager.cc.
References Logger::Log::Find().
Referenced by getEncoded(), MessageManager(), and ~MessageManager().
ACE_Message_Block * MessageManager::MakeControlMessage (ControlMessage::Type type, size_t size) static
Create a new ACE_Message_Block with the type kStateChangeType.
These messages signal service threads to change their processing state.
Returns
new ACE_Message_Block object
Definition at line 255 of file MessageManager.cc.
References PoolAllocator::Log(), and LOGINFO.
Referenced by SideCar::Algorithms::Controller::calculateUsingDataValue().
ACE_Message_Block * MessageManager::MakeMessageBlock (size_t size, int type = kRawData) static
Create a new ACE_Message_Block with a given capacity.
The block and its underlying ACE_Data_Block come from the custom allocators defined for MessageManager, and the block uses a mutex locking strategy to protect the resulting message block from multithreaded access/change.
Parameters
size initial capacity for the block
Returns
new ACE_Message_Block object
Definition at line 238 of file MessageManager.cc.
Referenced by SideCar::IO::StreamReader::fetchInput(), SideCar::IO::DatagramReader::makeIncomingBuffer(), SideCar::IO::StreamReader::reset(), and SideCar::GUI::MulticastMessageReader::~MulticastMessageReader().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/MessageManager.h
/Users/howes/src/sidecar/IO/MessageManager.cc