SideCar: SideCar::GUI::Setting Class Reference
SideCar::GUI::Setting Class Reference
A general name/value object that holds QVariant values.
#include </Users/howes/src/sidecar/GUI/Setting.h>
Public Slots
void setEnabled (bool state)
Signals
void save (int index, const QVariant &value)
Notification sent out by the Setting object when the held value changes due to the setValue() method.
void enabledChanged (bool state)
Notification sent out by the Setting object when its enabled state changes.
void valueChanged ()
Public Member Functions
Setting (PresetManager *mgr, const QString &name, bool global=false)
Constructor without a default setting value.
Setting (PresetManager *mgr, const QString &name, const QVariant &value, bool global=false)
Constructor with a default setting value.
const QString & getName () const
Obtain the name of the Setting object.
const QVariant & getOpaqueValue () const
Obtain the current value of the Setting object.
void setOpaqueValue (const QVariant &value)
Set the Setting's value and emit the opaqueValueChanged() signal followed by the save() signal.
bool isEnabled () const
Static Public Member Functions
static Logger::Log & Log ()
Log device for Setting objects.
Protected Member Functions
virtual void valueUpdated ()
Hook method used to detect when the internal value changes.
void resetOpaqueValue ()
void connectWidget (QWidget *widget)
void disconnectWidget (QWidget *widget)
Friends
class Preset
class PresetManager
Detailed Description
A general name/value object that holds QVariant values.
Changing the object's value emits the opaqueValueChanged() signal, and possibly the save() signal depending on the method used to invoke the change, restoreValue() or setValue().
The PresetManager class manages one or more Setting objects along with a set of preset values.
Definition at line 22 of file Setting.h.
Constructor & Destructor Documentation
Setting::Setting (PresetManager * mgr, const QString & name, bool global = false)
Constructor without a default setting value.
Parameters
mgr the PrestMangager object that manages the Setting
name the name of the Setting object
global if true, register setting as a global setting
Definition at line 17 of file Setting.cc.
References SideCar::GUI::PresetManager::addSetting(), Log(), and LOGINFO.
Setting::Setting (PresetManager * mgr, const QString & name, const QVariant & value, bool global = false)
Constructor with a default setting value.
Parameters
mgr the PrestMangager object that manages the Setting
name the name of the Setting object
value the initial value of the Setting object
global if true, register setting as a global setting
Definition at line 25 of file Setting.cc.
References SideCar::GUI::PresetManager::addSetting(), Log(), LOGINFO, and valueUpdated().
Member Function Documentation
void SideCar::GUI::Setting::enabledChanged (bool state) signal
Notification sent out by the Setting object when its enabled state changes.
Parameters
state new state
Referenced by setOpaqueValue().
const QString& SideCar::GUI::Setting::getName () const inline
Obtain the name of the Setting object.
Returns
Setting name
Definition at line 61 of file Setting.h.
Referenced by SideCar::GUI::PresetManager::addSetting(), SideCar::GUI::ChannelSetting::Log(), SideCar::GUI::PresetManager::restoreAllPresets(), SideCar::GUI::Preset::restoreOne(), SideCar::GUI::PresetManager::saveAllPresets(), SideCar::GUI::DoubleSetting::setValue(), SideCar::GUI::Preset::setValue(), and SideCar::GUI::DoubleSetting::valueUpdated().
const QVariant& SideCar::GUI::Setting::getOpaqueValue () const inline
Obtain the current value of the Setting object.
Returns
read-only value reference
Definition at line 67 of file Setting.h.
Referenced by SideCar::GUI::PresetManager::addSetting(), SideCar::GUI::PresetManager::restoreAllPresets(), SideCar::GUI::Preset::restoreOne(), SideCar::GUI::PresetManager::saveAllPresets(), SideCar::GUI::BoolSetting::setValue(), SideCar::GUI::StringListSetting::StringListSetting(), SideCar::GUI::TimeSetting::TimeSetting(), SideCar::GUI::QColorSetting::valueUpdated(), SideCar::GUI::StringSetting::valueUpdated(), SideCar::GUI::StringListSetting::valueUpdated(), SideCar::GUI::TimeSetting::valueUpdated(), SideCar::GUI::IntSetting::valueUpdated(), and SideCar::GUI::DoubleSetting::valueUpdated().
Logger::Log & Setting::Log () static
Log device for Setting objects.
Returns
Log reference
Definition at line 11 of file Setting.cc.
References Logger::Log::Find().
Referenced by setOpaqueValue(), and Setting().
void SideCar::GUI::Setting::save (int index, const QVariant & value) signal
Notification sent out by the Setting object when the held value changes due to the setValue() method.
If the Setting object has been registered with a PresetManager object using the PresetManager::addSetting() or PresetManager::addGlobal() method, then this signal will invoke the PresetManager::settingSave() or PresetManager::globalSave() method respectively.
Parameters
index value assigned by PresetManager
value new Setting value
Referenced by setOpaqueValue().
void Setting::setOpaqueValue (const QVariant & value)
Set the Setting's value and emit the opaqueValueChanged() signal followed by the save() signal.
Parameters
value
Definition at line 49 of file Setting.cc.
References enabledChanged(), Log(), LOGINFO, save(), and valueUpdated().
Referenced by SideCar::GUI::PresetManager::addSetting(), SideCar::GUI::StringSetting::setValue(), SideCar::GUI::StringListSetting::setValue(), SideCar::GUI::QColorSetting::setValue(), SideCar::GUI::TimeSetting::setValue(), SideCar::GUI::IntSetting::setValue(), SideCar::GUI::DoubleSetting::setValue(), and SideCar::GUI::BoolSetting::setValue().
virtual void SideCar::GUI::Setting::valueUpdated () inline protected virtual
Hook method used to detect when the internal value changes.
Derived classes should override to perform actions when the value changes.
Reimplemented in SideCar::GUI::DoubleSetting, SideCar::GUI::IntSetting, SideCar::GUI::TimeSetting, SideCar::GUI::StringListSetting, SideCar::GUI::StringSetting, and SideCar::GUI::QColorSetting.
Definition at line 107 of file Setting.h.
Referenced by setOpaqueValue(), and Setting().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Setting.h
/Users/howes/src/sidecar/GUI/Setting.cc