SideCar: SideCar::IO::Stream Class Reference
SideCar::IO::Stream Class Reference
A SideCar data stream.
#include </Users/howes/src/sidecar/IO/Stream.h>
Public Types
using Ref = boost::shared_ptr< Stream >
using StatusEmitterBaseRef = boost::shared_ptr< StatusEmitterBase >
Public Member Functions
const std::string & getName () const
Obtain the name of the stream.
Task::Ref getTask (int index) const
Obtain the task at a given position from the head of the stream.
void fillStatus (StatusBase &status)
Fill out a StreamStatus status collection with information from all of the tasks in the stream.
void getChangedParameters (XmlRpc::XmlRpcValue &value) const
Obtain a collection of key/value pairs that describe the parameters changed since startup.
void emitStatus () const
Force a status emission for the stream.
Static Public Member Functions
static Logger::Log & Log ()
static Ref Make (const std::string &name, const StatusEmitterBaseRef &emitter=StatusEmitterBaseRef())
Detailed Description
A SideCar data stream.
Contains one or more Module objects (which contain a Task object) that process data given to the head of the stream. Note that the ACE_MT_SYNCH template parameter given to ACE_Stream denotes the type of ACE_Task objects the stream holds, and not that there is any locking going on within ACE_Stream. Also, abide by the warnings in ACE Stream.h: there is some tricky stuff involved in overriding certain methods. This class does no overriding, only extending.
Definition at line 26 of file Stream.h.
Member Function Documentation
void Stream::fillStatus (StatusBase & status)
Fill out a StreamStatus status collection with information from all of the tasks in the stream.
Parameters
status container to hold the status information
Definition at line 45 of file Stream.cc.
References getTask(), SideCar::IO::StatusBase::getXMLData(), LOGDEBUG, LOGINFO, and SideCar::IO::StatusBase::setSlot().
void Stream::getChangedParameters (XmlRpc::XmlRpcValue & value) const
Obtain a collection of key/value pairs that describe the parameters changed since startup.
Parameters
value XML container to hold the changes.
Definition at line 79 of file Stream.cc.
References getName(), getTask(), LOGDEBUG, LOGINFO, XmlRpc::XmlRpcValue::setSize(), and XmlRpc::XmlRpcValue::toXml().
const std::string& SideCar::IO::Stream::getName () const inline
Obtain the name of the stream.
Returns
stream name
Definition at line 41 of file Stream.h.
Referenced by getChangedParameters().
Task::Ref Stream::getTask (int index) const
Obtain the task at a given position from the head of the stream.
Parameters
index id of the task to get
Returns
Task shared reference
Definition at line 20 of file Stream.cc.
Referenced by fillStatus(), and getChangedParameters().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/Stream.h
/Users/howes/src/sidecar/IO/Stream.cc