SideCar: SideCar::GUI::StringListSetting Class Reference
SideCar::GUI::StringListSetting Class Reference
Derivation of the Setting class that manages boolean values.
#include </Users/howes/src/sidecar/GUI/StringListSetting.h>
Public Slots
void setValue (const QStringList &value)
Change the setting value.
Public Slots inherited from SideCar::GUI::Setting
void setEnabled (bool state)
Signals
void valueChanged (const QStringList &value)
Notification sent out when the held value changes.
Signals inherited from SideCar::GUI::Setting
void save (int index, const QVariant &value)
Notification sent out by the Setting object when the held value changes due to the setValue() method.
void enabledChanged (bool state)
Notification sent out by the Setting object when its enabled state changes.
void valueChanged ()
Public Member Functions
StringListSetting (PresetManager *mgr, const QString &name, bool global=false)
Constructor.
StringListSetting (PresetManager *mgr, const QString &name, const QStringList &value, bool global=false)
Constructor.
const QStringList & getValue () const
Obtain the current setting value.
Public Member Functions inherited from SideCar::GUI::Setting
Setting (PresetManager *mgr, const QString &name, bool global=false)
Constructor without a default setting value.
Setting (PresetManager *mgr, const QString &name, const QVariant &value, bool global=false)
Constructor with a default setting value.
const QString & getName () const
Obtain the name of the Setting object.
const QVariant & getOpaqueValue () const
Obtain the current value of the Setting object.
void setOpaqueValue (const QVariant &value)
Set the Setting's value and emit the opaqueValueChanged() signal followed by the save() signal.
bool isEnabled () const
Protected Member Functions
void valueUpdated ()
Override of Setting::valueUpdated() method.
Protected Member Functions inherited from SideCar::GUI::Setting
void resetOpaqueValue ()
void connectWidget (QWidget *widget)
void disconnectWidget (QWidget *widget)
Additional Inherited Members
Static Public Member Functions inherited from SideCar::GUI::Setting
static Logger::Log & Log ()
Log device for Setting objects.
Detailed Description
Derivation of the Setting class that manages boolean values.
Definition at line 13 of file StringListSetting.h.
Constructor & Destructor Documentation
StringListSetting::StringListSetting (PresetManager * mgr, const QString & name, bool global = false)
Constructor.
Parameters
mgr
name
global
Definition at line 5 of file StringListSetting.cc.
References SideCar::GUI::Setting::getOpaqueValue().
StringListSetting::StringListSetting (PresetManager * mgr, const QString & name, const QStringList & value, bool global = false)
Constructor.
Parameters
mgr
name
value
global
Definition at line 12 of file StringListSetting.cc.
References SideCar::GUI::Setting::getOpaqueValue().
Member Function Documentation
const QStringList& SideCar::GUI::StringListSetting::getValue () const inline
Obtain the current setting value.
Returns
setting value
Definition at line 47 of file StringListSetting.h.
References setValue(), valueChanged(), and valueUpdated().
void StringListSetting::setValue (const QStringList & value) slot
Change the setting value.
Emits the valueChanged() signal if the given value is diferent than the held one.
Parameters
value new value to use
Definition at line 21 of file StringListSetting.cc.
References SideCar::GUI::Setting::setOpaqueValue().
Referenced by getValue().
void SideCar::GUI::StringListSetting::valueChanged (const QStringList & value) signal
Notification sent out when the held value changes.
Parameters
value new held value
Referenced by getValue(), and valueUpdated().
void StringListSetting::valueUpdated () protected virtual
Override of Setting::valueUpdated() method.
Records the new value and emits the valueChanged() signal.
Reimplemented from SideCar::GUI::Setting.
Definition at line 28 of file StringListSetting.cc.
References SideCar::GUI::Setting::getOpaqueValue(), and valueChanged().
Referenced by getValue().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/StringListSetting.h
/Users/howes/src/sidecar/GUI/StringListSetting.cc