SideCar: SideCar::GUI::OnOffSettingsBlock Class Reference
SideCar::GUI::OnOffSettingsBlock Class Reference
Derivation of SettingsBlock that has a BoolSetting object which acts as an 'enabled' setting.
#include </Users/howes/src/sidecar/GUI/OnOffSettingsBlock.h>
Signals
void enabledChanged (bool state)
Notification sent out when the enabled state has changed.
Signals inherited from SideCar::GUI::SettingsBlock
void settingChanged ()
Notification sent out when a registered value has changed.
Public Member Functions
OnOffSettingsBlock (BoolSetting *enabled)
Constructor.
bool isEnabled () const
Determine if the settings block is enabled.
void toggleEnabled ()
Toggle the enabled state of this settings block.
void setToggleEnabledAction (QAction *action)
Install a QAction object to control the on/off state of the settings block.
void connectWidget (QCheckBox *widget)
Public Member Functions inherited from SideCar::GUI::SettingsBlock
SettingsBlock (QObject *parent=0)
Constructor.
Additional Inherited Members
Protected Slots inherited from SideCar::GUI::SettingsBlock
virtual void postSettingChanged ()
Notification handler invoked when a Setting object that was registered with one of the add() methods emits its valueChanged() signal.
virtual void emitSettingChanged ()
Notification handler invoked when the QTimer object registered by the postSettingChanged() method fires.
Protected Member Functions inherited from SideCar::GUI::SettingsBlock
void add (Setting *setting)
Relate a Setting object to this SettingsBlock object.
Detailed Description
Derivation of SettingsBlock that has a BoolSetting object which acts as an 'enabled' setting.
Defines an additional signal, enabledChanged(), which is emitted whenever the enabled state changes. NOTE: enabled state changes do not emit the SettingsBlock::settingsChanged() signal.
Definition at line 15 of file OnOffSettingsBlock.h.
Constructor & Destructor Documentation
OnOffSettingsBlock::OnOffSettingsBlock (BoolSetting * enabled)
Constructor.
Parameters
enabled setting that controls this object's enabled state
Definition at line 5 of file OnOffSettingsBlock.cc.
References enabledChanged().
Member Function Documentation
bool SideCar::GUI::OnOffSettingsBlock::isEnabled () const inline
Determine if the settings block is enabled.
Returns
true if so
Definition at line 31 of file OnOffSettingsBlock.h.
References SideCar::GUI::BoolSetting::getValue().
Referenced by SideCar::GUI::PPIDisplay::App::App(), SideCar::GUI::AScope::App::App(), SideCar::GUI::AScope::ChannelConnectionModel::flags(), SideCar::GUI::AScope::HistoryControlWidget::HistoryControlWidget(), SideCar::GUI::PPIDisplay::PPIWidget::localToRealWorld(), SideCar::GUI::PPIDisplay::MainWindow::MainWindow(), SideCar::GUI::BScope::MainWindow::MainWindow(), SideCar::GUI::ESScope::MainWindow::MainWindow(), SideCar::GUI::AScope::MainWindow::MainWindow(), SideCar::GUI::BScope::PPIWidget::PPIWidget(), SideCar::GUI::PPIDisplay::PPIWidget::renderScene(), and SideCar::GUI::ESScope::XYWidget::XYWidget().
void OnOffSettingsBlock::setToggleEnabledAction (QAction * action)
Install a QAction object to control the on/off state of the settings block.
Parameters
action the QAction to use
Definition at line 13 of file OnOffSettingsBlock.cc.
Referenced by SideCar::GUI::PPIDisplay::MainWindow::MainWindow(), SideCar::GUI::BScope::MainWindow::MainWindow(), SideCar::GUI::ESScope::MainWindow::MainWindow(), and toggleEnabled().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/OnOffSettingsBlock.h
/Users/howes/src/sidecar/GUI/OnOffSettingsBlock.cc