SideCar: SideCar::Messages::Extraction Class Reference
SideCar::Messages::Extraction Class Reference
Data type for a video artifact extraction.
#include </Users/howes/src/sidecar/Messages/Extraction.h>
Public Member Functions
Extraction (const Time::TimeStamp &when, double range, double azimuth, double elevation)
Constructor for new extraction entries.
Extraction (ACE_InputCDR &cdr)
Constructor for objects loaded from an ACE input stream.
Extraction (XmlStreamReader &xsr)
Constructor for objects loaded from an ACE input stream.
const Time::TimeStamp & getWhen () const
double getRange () const
Obtain the range of the extraction.
double getAzimuth () const
Obtain the azimuth of the extraction.
double getElevation () const
Obtain the elevation of the extraction.
bool getCorrelated () const
Obtain whether this extraction is correlated.
void setCorrelated (bool corr)
Set whether this extraction is correlated.
int getNumCorrelations () const
Obtain the number of scans this extraction has been correlated for.
void setNumCorrelations (int corr)
Sets the number of scans this extraction has been correlated for.
double getX () const
Obtain the X coordinate of the extraction.
double getY () const
Obtain the Y coordinate of the extraction.
void addAttribute (const std::string &name, const XmlRpc::XmlRpcValue &value)
const Attributes & getAttributes () const
ACE_OutputCDR & write (ACE_OutputCDR &cdr) const
Write out binary representation to a CDR stream.
std::ostream & print (std::ostream &os) const
std::ostream & printXML (std::ostream &os) const
void loadXML (XmlStreamReader &xsr)
Detailed Description
Data type for a video artifact extraction.
Contains range and azimumth information, and derived X, Y rectangular coordinates. NOTE: the conversion follows the nautical convention that 0 degrees is north, and not the mathematical one (ie x := r * sin(a), not r * cos(a)).
Definition at line 21 of file Extraction.h.
Constructor & Destructor Documentation
Extraction::Extraction (const Time::TimeStamp & when, double range, double azimuth, double elevation)
Constructor for new extraction entries.
Parameters
range range of the artifact
azimuth azimuth of the artifact (radians)
Definition at line 13 of file Extraction.cc.
Referenced by SideCar::Messages::Extractions::printDataXML().
Extraction::Extraction (ACE_InputCDR & cdr)
Constructor for objects loaded from an ACE input stream.
Parameters
cdr stream to read from
Definition at line 28 of file Extraction.cc.
Extraction::Extraction (XmlStreamReader & xsr)
Constructor for objects loaded from an ACE input stream.
Parameters
cdr stream to read from
Definition at line 20 of file Extraction.cc.
References SideCar::Messages::XmlStreamReader::getAttribute(), SideCar::Time::TimeStamp::Min(), and SideCar::Time::TimeStamp::ParseSpecification().
Member Function Documentation
double SideCar::Messages::Extraction::getAzimuth () const inline
Obtain the azimuth of the extraction.
Returns
value in radians
Definition at line 57 of file Extraction.h.
Referenced by SideCar::Algorithms::TrackInitiator::reset(), and SideCar::Algorithms::ABTracker::shutdown().
bool SideCar::Messages::Extraction::getCorrelated () const inline
Obtain whether this extraction is correlated.
Returns
boolean
Definition at line 69 of file Extraction.h.
Referenced by SideCar::Algorithms::TrackInitiator::reset().
double SideCar::Messages::Extraction::getElevation () const inline
Obtain the elevation of the extraction.
Returns
value in meters
Definition at line 63 of file Extraction.h.
Referenced by SideCar::Algorithms::ABTracker::shutdown().
int SideCar::Messages::Extraction::getNumCorrelations () const inline
Obtain the number of scans this extraction has been correlated for.
Returns
num correlations
Definition at line 81 of file Extraction.h.
Referenced by SideCar::Algorithms::TrackInitiator::reset(), and SideCar::Algorithms::ScanCorrelator::reset().
double SideCar::Messages::Extraction::getRange () const inline
Obtain the range of the extraction.
Returns
value in kilometers
Definition at line 51 of file Extraction.h.
Referenced by SideCar::Algorithms::TrackInitiator::reset(), and SideCar::Algorithms::ABTracker::shutdown().
double SideCar::Messages::Extraction::getX () const inline
Obtain the X coordinate of the extraction.
Returns
value in kilometers
Definition at line 93 of file Extraction.h.
Referenced by SideCar::Algorithms::TrackInitiator::reset(), SideCar::Algorithms::ScanCorrelator::reset(), and SideCar::Algorithms::ABTracker::shutdown().
double SideCar::Messages::Extraction::getY () const inline
Obtain the Y coordinate of the extraction.
Returns
value in kilometers
Definition at line 99 of file Extraction.h.
Referenced by SideCar::Algorithms::TrackInitiator::reset(), SideCar::Algorithms::ScanCorrelator::reset(), and SideCar::Algorithms::ABTracker::shutdown().
void SideCar::Messages::Extraction::setCorrelated (bool corr) inline
Set whether this extraction is correlated.
Parameters
corr correlated
Definition at line 75 of file Extraction.h.
Referenced by SideCar::Algorithms::TrackInitiator::reset(), and SideCar::Algorithms::ScanCorrelator::reset().
void SideCar::Messages::Extraction::setNumCorrelations (int corr) inline
Sets the number of scans this extraction has been correlated for.
Parameters
corr – # of scans
Definition at line 87 of file Extraction.h.
Referenced by SideCar::Algorithms::TrackInitiator::reset(), and SideCar::Algorithms::ScanCorrelator::reset().
ACE_OutputCDR & Extraction::write (ACE_OutputCDR & cdr) const
Write out binary representation to a CDR stream.
Parameters
cdr stream to write to
Returns
stream written to
Definition at line 40 of file Extraction.cc.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Messages/Extraction.h
/Users/howes/src/sidecar/Messages/Extraction.cc