SideCar: SideCar::Zeroconf::Publisher Class Reference
SideCar::Zeroconf::Publisher Class Reference
Zeroconf publisher of information regarding an available service.
#include </Users/howes/src/sidecar/Zeroconf/Publisher.h>
Public Types
using Ref = boost::shared_ptr< Publisher >
using SignalConnection = boost::signals2::connection
using PublishedSignal = boost::signals2::signal< void(bool)>
using PublishedSignalProc = PublishedSignal::slot_function_type
using StringMap = std::map< std::string, std::string >
Public Types inherited from SideCar::Zeroconf::Transaction
using Ref = boost::shared_ptr< Transaction >
Public Member Functions
const std::string & getName () const
Obtain the name of the service.
const std::string & getType () const
Obtain the service type.
const std::string & getDomain () const
Obtain the domain we are registered in.
uint32_t getInterface () const
Obtain the network interface to publish for.
uint16_t getPort () const
Obtain the port number of our address.
void setType (const std::string &type)
Change the type of the service being published.
void setDomain (const std::string &domain)
Change the domain of the service being published.
void setHost (const std::string &host)
Change the host of the service being published.
void setPort (uint16_t port)
Change the port of the service being published.
void setInterface (uint32_t interface)
Change the interface to publish on.
SignalConnection connectToPublishedSignal (PublishedSignalProc observer)
Connect an observer to the PublishedSignal signal to receive a notification when the published state has changed.
bool setTextData (const std::string &key, const std::string &value, bool postNow=true)
Set or modify an entry in the service's published TXT record.
bool postTextData ()
Post any changes to the entry's TXT record.
bool publish (const std::string &name, bool noRename)
Initiate the publishing of information regarding this service.
bool isPublished () const
Obtain whether we are published or not.
Public Member Functions inherited from SideCar::Zeroconf::Transaction
virtual ~Transaction ()
Destructor.
bool stop ()
Stop a Zeroconf service.
bool isRunning () const
Determine if a Zeroconf service is running.
int getConnection () const
Obtain the underlying IPC descriptor used to communicate with the Zeroconf daemon.
bool processConnection ()
Data is available from the Zeroconf daemon.
Static Public Member Functions
static Logger::Log & Log ()
Log device for all Publisher objects.
static Ref Make (Monitor *monitor)
Factory method used to create a new Publisher instance.
Static Public Member Functions inherited from SideCar::Zeroconf::Transaction
static Logger::Log & Log ()
Obtain the log device for all Transaction objects.
Protected Member Functions
Publisher (Monitor *monitor)
Constructor.
virtual void processResponse (DNSServiceErrorType err, const char *name, const char *type, const char *domain)
Overridable hook method called to process a DNSServiceRegister response from the DNSSD server.
virtual void notifyObservers (bool published)
Overridable hook method called to notify all PublishedSignal observers that our publishing state has changed.
Protected Member Functions inherited from SideCar::Zeroconf::Transaction
Transaction (Monitor *monitor)
Constructor.
virtual void serviceStarted ()
Hook for derived classes for notification that a service has started.
void setSelf (const Ref &self)
Set a weak reference to ourselves so that we can give out shared_ptr refences to ourselves.
void finished ()
void finish ()
template<typename T >
boost::shared_ptr< T > getSelf () const
Obtain a shared_ptr reference to ourselves.
DNSServiceRef & getDNSServiceRef ()
const DNSServiceRef & getDNSServiceRef () const
Detailed Description
Zeroconf publisher of information regarding an available service.
Each SideCar data publisher uses a Zeroconf Publisher to publish its connection information, most importantly the host, port pair that allow subscribers to connect to the publisher. Maintains a connection to the multicast DNS (mdns) server running locally, and the data publication remains valid for the life of the connection. Supports publishing of key/value pairs.
Accessing published information in a mdns server is performed by the Browser class. Valid published types are defined in IO/ZeroconfRegistry.h.
Definition at line 27 of file Publisher.h.
Constructor & Destructor Documentation
Publisher::Publisher (Monitor * monitor) protected
Constructor.
Restricted to derived classes and to the Make() factory method.
Definition at line 23 of file Publisher.cc.
References Log(), and LOGINFO.
Referenced by Make().
Member Function Documentation
SignalConnection SideCar::Zeroconf::Publisher::connectToPublishedSignal (PublishedSignalProc observer) inline
Connect an observer to the PublishedSignal signal to receive a notification when the published state has changed.
The observer must be a function object that takes two parameters:
Publisher::Ref - reference to the object doing the signalling
boolean indicating the state of the publishing
To disconnect, simply invoke the disconnect() method of the returned object.
\param observer object to receive notifications
\return object identifying the signal connection
Definition at line 129 of file Publisher.h.
const std::string& SideCar::Zeroconf::Publisher::getDomain () const inline
Obtain the domain we are registered in.
Returns
domain name
Definition at line 65 of file Publisher.h.
uint32_t SideCar::Zeroconf::Publisher::getInterface () const inline
Obtain the network interface to publish for.
Returns
network interface index
Definition at line 71 of file Publisher.h.
const std::string& SideCar::Zeroconf::Publisher::getName () const inline
Obtain the name of the service.
Returns
service name
Definition at line 53 of file Publisher.h.
uint16_t SideCar::Zeroconf::Publisher::getPort () const inline
Obtain the port number of our address.
Returns
port number
Definition at line 77 of file Publisher.h.
const std::string& SideCar::Zeroconf::Publisher::getType () const inline
Obtain the service type.
Returns
service type
Definition at line 59 of file Publisher.h.
bool SideCar::Zeroconf::Publisher::isPublished () const inline
Obtain whether we are published or not.
Returns
true if so
Definition at line 165 of file Publisher.h.
Logger::Log & Publisher::Log () static
Log device for all Publisher objects.
Returns
log device
Definition at line 9 of file Publisher.cc.
References Logger::Log::Find().
Referenced by processResponse(), publish(), Publisher(), and setTextData().
Publisher::Ref Publisher::Make (Monitor * monitor) static
Factory method used to create a new Publisher instance.
Returns
reference to new Publisher
Definition at line 16 of file Publisher.cc.
References Publisher().
void Publisher::notifyObservers (bool published) protected virtual
Overridable hook method called to notify all PublishedSignal observers that our publishing state has changed.
Parameters
published true if currently publishing
Definition at line 152 of file Publisher.cc.
References processResponse(), and SideCar::Zeroconf::Transaction::serviceStopping().
Referenced by processResponse().
void Publisher::processResponse (DNSServiceErrorType err, const char * name, const char * type, const char * domain) protected virtual
Overridable hook method called to process a DNSServiceRegister response from the DNSSD server.
This implementation sets the isPublished_ attribute and then invokes publishedService().
Parameters
err error code from the DNSSD server
name the name that was actually published
type the type that was published
domain the domain under which everything was published
Definition at line 130 of file Publisher.cc.
References Log(), LOGWARNING, and notifyObservers().
Referenced by notifyObservers().
bool Publisher::publish (const std::string & name, bool noRename)
Initiate the publishing of information regarding this service.
Note that successful publishing is not indicated by a good result from this routine, but rather when the method published() is invoked, with a true state value. To stop publishing, invoke Transaction::stop().
Parameters
name name of this service
noRename if true, fail to publish if another service with the same name exists. Otherwise, let Zeroconf deconflict names, giving us a new one in the PublishedSignalProc callback.
Returns
true if successful, false otherwise
Definition at line 83 of file Publisher.cc.
References SideCar::Zeroconf::Transaction::isRunning(), Log(), LOGDEBUG, LOGERROR, LOGINFO, LOGWARNING, SideCar::Zeroconf::Transaction::serviceStarted(), and SideCar::Zeroconf::Transaction::stop().
void SideCar::Zeroconf::Publisher::setDomain (const std::string & domain) inline
Change the domain of the service being published.
Note that the change does not affect any publishing that is in effect; one must stop() and then start() to have the change take effect.
Parameters
domain the new service domain
Definition at line 91 of file Publisher.h.
void SideCar::Zeroconf::Publisher::setHost (const std::string & host) inline
Change the host of the service being published.
Does not perform any validation on the value given. Note that the change does not affect any publishing that is in effect; one must stop() and then start() to have the change take effect.
Parameters
host the new host identifier
Definition at line 99 of file Publisher.h.
void SideCar::Zeroconf::Publisher::setInterface (uint32_t interface) inline
Change the interface to publish on.
Hosts may have more than one network interface active. The default behavior of mdns is to publish connection information on all active interfaces. Use this method to restrict publishing to a specific network interface.
Parameters
interface network interface to use
Definition at line 115 of file Publisher.h.
void SideCar::Zeroconf::Publisher::setPort (uint16_t port) inline
Change the port of the service being published.
Note that the change does not affect any publishing that is in effect; one must stop() and then start() to have the change take effect.
Parameters
port the number of the socket port on the local host used by the service
Definition at line 107 of file Publisher.h.
bool Publisher::setTextData (const std::string & key, const std::string & value, bool postNow = true)
Set or modify an entry in the service's published TXT record.
Parameters
key name of the value to add/change
value value to store for the given key
postNow if true, submit the change to the DNS server now
\return true if successful, false otherwise
Definition at line 32 of file Publisher.cc.
References Log(), LOGINFO, and postTextData().
void SideCar::Zeroconf::Publisher::setType (const std::string & type) inline
Change the type of the service being published.
Note that the change does not affect any publishing that is in effect; one must stop() and then start() to have the change take effect.
Parameters
type the new service type
Definition at line 84 of file Publisher.h.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Zeroconf/Publisher.h
/Users/howes/src/sidecar/Zeroconf/Publisher.cc