SideCar: SideCar::GUI::AScope::RenderInfo Class Reference
SideCar::GUI::AScope::RenderInfo Class Reference
Collection of render attributes associated with a particular ChannelConnection object.
#include </Users/howes/src/sidecar/GUI/AScope/RenderInfo.h>
Public Types
using QPointFVector = std::vector< QPointF >
Public Slots
void setColor (const QColor &color)
Change the rendering color for the channel.
void setVisible (bool state)
Change the visibility state of the channel.
void setFrozen (bool state)
Change the frozen state of the channel.
void setShowPeakBars (bool state)
Public Member Functions
RenderInfo (Visualizer &visualizer, PeakBarCollection &peakBars, const QColor &color, bool visible, bool showPeakBars)
Constructor.
void setHistorySlot (size_t historySlot)
Assign a unique slot from the History manager for this instance.
bool isVisible () const
Obtain whether channel data is visibile.
bool isFrozen () const
Obtain whether channel data is frozen at some frame.
bool showPeakBars () const
Friends
class Visualizer
class PeakBarCollection
Detailed Description
Collection of render attributes associated with a particular ChannelConnection object.
Contains state and cached data to improve rendering times when data from a channel does not change.
A Visualizer widget may subscribe to one or more input channels. To keep rendering as fast as possible, input data is first converted into render data, and then at the next Visualizer update, it draws the render data of all of the input channels in one shot.
Definition at line 30 of file RenderInfo.h.
Constructor & Destructor Documentation
SideCar::GUI::AScope::RenderInfo::RenderInfo (Visualizer & visualizer, PeakBarCollection & peakBars, const QColor & color, bool visible, bool showPeakBars)
Constructor.
Parameters
visualizer the Visualizer that uses data in this instance
color the color to use when rendering data
visible state of visibility for the channel
Member Function Documentation
bool SideCar::GUI::AScope::RenderInfo::isFrozen () const inline
Obtain whether channel data is frozen at some frame.
Returns
true if so
Definition at line 63 of file RenderInfo.h.
bool SideCar::GUI::AScope::RenderInfo::isVisible () const inline
Obtain whether channel data is visibile.
Returns
true if so
Definition at line 57 of file RenderInfo.h.
void RenderInfo::setColor (const QColor & color) slot
Change the rendering color for the channel.
Parameters
color new color to use
Definition at line 41 of file RenderInfo.cc.
Referenced by showPeakBars().
void RenderInfo::setFrozen (bool state) slot
Change the frozen state of the channel.
If frozen, future data messages will not change the rendering of a channel.
Parameters
state new state
Definition at line 55 of file RenderInfo.cc.
Referenced by showPeakBars().
void SideCar::GUI::AScope::RenderInfo::setHistorySlot (size_t historySlot) inline
Assign a unique slot from the History manager for this instance.
Parameters
historySlot value to assign
Definition at line 51 of file RenderInfo.h.
void RenderInfo::setShowPeakBars (bool state) slot
Parameters
state
Definition at line 61 of file RenderInfo.cc.
Referenced by showPeakBars().
void RenderInfo::setVisible (bool state) slot
Change the visibility state of the channel.
Parameters
state new state
Definition at line 48 of file RenderInfo.cc.
Referenced by showPeakBars().
bool SideCar::GUI::AScope::RenderInfo::showPeakBars () const inline
Returns
Definition at line 69 of file RenderInfo.h.
References setColor(), setFrozen(), setShowPeakBars(), and setVisible().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/AScope/RenderInfo.h
/Users/howes/src/sidecar/GUI/AScope/RenderInfo.cc