SideCar: Utils::SineCosineLUT Class Reference
Utils::SineCosineLUT Class Reference
Simple table lookup class for sine/cosine values.
#include </Users/howes/src/sidecar/Utils/SineCosineLUT.h>
Data Structures
struct InvalidSize
Exception thrown if the requested table size is not a multiple of 4.
Public Member Functions
SineCosineLUT (size_t size) throw (InvalidSize)
Constructor.
void lookup (size_t index, double &sine, double &cosine) const
Obtain the sine and cosine values for a given lookup index.
size_t size () const
Static Public Member Functions
static Logger::Log & Log ()
Obtain the Log device to use for objects of this class.
static SineCosineLUT * Make (size_t size)
Factory method that creates a new lookup table.
Detailed Description
Simple table lookup class for sine/cosine values.
Note that this does not support interpolation, only indexed lookup, where the indices range from [0,size) and linearly map to [0,2*PI) radians. One source of indices that behave like this is a radar shaft encoder that emits a unique integer value depending on where the antenna is pointing, with a resolution of N values.
The lookup table contains sine and cosine values calculated for N / 4 indices. The lookup() method uses various trig identities to calculate the remaining values for the rest of the indices. Because of this space reduction, the size of the lookup table must be a multiple of 4.
Definition at line 22 of file SineCosineLUT.h.
Constructor & Destructor Documentation
SineCosineLUT::SineCosineLUT (size_t size) throw (InvalidSize)
Constructor.
Creates and populates the lookup table. Throws an exception if the given size is not a multiple of 4.
Parameters
size number of integral values in a circle (2 * PI)
Definition at line 28 of file SineCosineLUT.cc.
Referenced by Make().
Member Function Documentation
Logger::Log & SineCosineLUT::Log () static
Obtain the Log device to use for objects of this class.
Returns
Loggger::Log reference
Definition at line 9 of file SineCosineLUT.cc.
References Logger::Log::Find().
Referenced by Make().
void SineCosineLUT::lookup (size_t index, double & sine, double & cosine) const
Obtain the sine and cosine values for a given lookup index.
Parameters
index integral value in [0,size) to fetch
sine reference to storage for sine value
cosine reference to storage for cosine value
Definition at line 48 of file SineCosineLUT.cc.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::initializeContext(), and SideCar::GUI::PPIDisplay::PPIWidget::renderScene().
SineCosineLUT * SineCosineLUT::Make (size_t size) static
Factory method that creates a new lookup table.
Checks the size argument to see that it is a multiple of 4.
Parameters
size number of integral values in a circle (2 * PI)
Returns
new SineCosineLUT object or NULL if invalid size
Definition at line 16 of file SineCosineLUT.cc.
References Log(), LOGERROR, and SineCosineLUT().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Utils/SineCosineLUT.h
/Users/howes/src/sidecar/Utils/SineCosineLUT.cc