SideCar: Utils::BeamWidthFilter Class Reference
Utils::BeamWidthFilter Class Reference
Simple averaging filter for azimuth deltas.
#include </Users/howes/src/sidecar/Utils/BeamWidthFilter.h>
Public Member Functions
BeamWidthFilter (size_t windowSize=2000)
Constructor.
double add (double beamWidth)
Add a new value to the running average.
double getFilterValue () const
Obtain the current damped value.
size_t getRadialCount () const
Obtain the number of radials in a circle that corresponds to the current filter value.
std::ostream & print (std::ostream &os) const
Dump the contents of the filter to a C++ text output stream.
Detailed Description
Simple averaging filter for azimuth deltas.
Maintains a running average of N (2000 default) beam widths in order to obtain a slowly varying beam width value. Also provides the average number of radials one would expect to find in a complete rotation of the radar. The expectation when using this filter is that the angular velocity of the radar remains fairly constant, even when subjected to wind gusts.
Definition at line 16 of file BeamWidthFilter.h.
Constructor & Destructor Documentation
Utils::BeamWidthFilter::BeamWidthFilter (size_t windowSize = 2000) inline
Constructor.
Parameters
windowSize number of width samples to keep around in the running average calculation. The larget the number, the more damping occurs.
Definition at line 25 of file BeamWidthFilter.h.
References add().
Member Function Documentation
double BeamWidthFilter::add (double beamWidth)
Add a new value to the running average.
Parameters
beamWidth new sample value
Returns
running average
Definition at line 8 of file BeamWidthFilter.cc.
Referenced by BeamWidthFilter().
double Utils::BeamWidthFilter::getFilterValue () const inline
Obtain the current damped value.
Returns
damped beam width value
Definition at line 40 of file BeamWidthFilter.h.
size_t Utils::BeamWidthFilter::getRadialCount () const inline
Obtain the number of radials in a circle that corresponds to the current filter value.
Returns
radial count
Definition at line 46 of file BeamWidthFilter.h.
References print().
std::ostream & BeamWidthFilter::print (std::ostream & os) const
Dump the contents of the filter to a C++ text output stream.
Parameters
os stream to write to
Returns
stream written to
Definition at line 26 of file BeamWidthFilter.cc.
Referenced by getRadialCount().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Utils/BeamWidthFilter.h
/Users/howes/src/sidecar/Utils/BeamWidthFilter.cc