SideCar: SideCar::GUI::TargetPlotSymbolsWidget Class Reference
SideCar::GUI::TargetPlotSymbolsWidget Class Reference
Widget that shows the current plot symbols for the extractions (E), range truths (T) and user pick (P) imaging sources.
#include </Users/howes/src/sidecar/GUI/TargetPlotSymbolsWidget.h>
Public Member Functions
TargetPlotSymbolsWidget (QWidget *parent=0)
Constructor.
void connectExtractionsSymbolType (TargetPlotImaging *setting)
Associate the extractions symbol QComboBox with the given TargetPlotImaging instance.
void connectRangeTruthsSymbolType (TargetPlotImaging *setting)
Associate the range truths symbol QComboBox with the given TargetPlotImaging instance.
void connectBugPlotsSymbolType (TargetPlotImaging *setting)
Associate the user picks symbol QComboBox with the given TargetPlotImaging instance.
Detailed Description
Widget that shows the current plot symbols for the extractions (E), range truths (T) and user pick (P) imaging sources.
Definition at line 15 of file TargetPlotSymbolsWidget.h.
Constructor & Destructor Documentation
TargetPlotSymbolsWidget::TargetPlotSymbolsWidget (QWidget * parent = 0)
Constructor.
Parameters
parent parent for auto-destruction
Definition at line 8 of file TargetPlotSymbolsWidget.cc.
Member Function Documentation
void TargetPlotSymbolsWidget::connectBugPlotsSymbolType (TargetPlotImaging * setting)
Associate the user picks symbol QComboBox with the given TargetPlotImaging instance.
Parameters
setting TargetPlotImaging instance to associate with
Definition at line 29 of file TargetPlotSymbolsWidget.cc.
Referenced by SideCar::GUI::PPIDisplay::MainWindow::MainWindow(), SideCar::GUI::BScope::MainWindow::MainWindow(), and SideCar::GUI::ESScope::MainWindow::MainWindow().
void TargetPlotSymbolsWidget::connectExtractionsSymbolType (TargetPlotImaging * setting)
Associate the extractions symbol QComboBox with the given TargetPlotImaging instance.
Parameters
setting TargetPlotImaging instance to associate with
Definition at line 15 of file TargetPlotSymbolsWidget.cc.
Referenced by SideCar::GUI::PPIDisplay::MainWindow::MainWindow(), SideCar::GUI::BScope::MainWindow::MainWindow(), and SideCar::GUI::ESScope::MainWindow::MainWindow().
void TargetPlotSymbolsWidget::connectRangeTruthsSymbolType (TargetPlotImaging * setting)
Associate the range truths symbol QComboBox with the given TargetPlotImaging instance.
Parameters
setting TargetPlotImaging instance to associate with
Definition at line 22 of file TargetPlotSymbolsWidget.cc.
Referenced by SideCar::GUI::PPIDisplay::MainWindow::MainWindow(), SideCar::GUI::BScope::MainWindow::MainWindow(), and SideCar::GUI::ESScope::MainWindow::MainWindow().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/TargetPlotSymbolsWidget.h
/Users/howes/src/sidecar/GUI/TargetPlotSymbolsWidget.cc