SideCar: SideCar::Algorithms::BugCollectorUtils::BugPlotSubscriber Class Reference
SideCar::Algorithms::BugCollectorUtils::BugPlotSubscriber Class Reference
Automatic BugPlot channel subscriber.
#include </Users/howes/src/sidecar/Algorithms/BugCollector/BugPlotSubscriber.h>
Public Types
using ServiceEntryVector = Zeroconf::Browser::ServiceEntryVector
Public Member Functions
BugPlotSubscriber (BugCollector &bugCollector, const std::string &prefix)
Constructor.
~BugPlotSubscriber ()
Destructor.
size_t size () const
Obtain the number of active BugPlotReader instances.
void setPrefix (const std::string &value)
Change the publisher name filter.
int handle_timeout (const ACE_Time_Value &duration, const void *arg)
Override of ACE_Event_Handler::handle_timeout().
Detailed Description
Automatic BugPlot channel subscriber.
Creates a Zeroconf::Browser for BugPlot publishers, and creates a new BugPlotReader for each one it finds. Note that it will only subscribe to a publisher whose name starts with a specific prefix value.
Definition at line 94 of file BugPlotSubscriber.h.
Constructor & Destructor Documentation
BugPlotSubscriber::BugPlotSubscriber (BugCollector & bugCollector, const std::string & prefix)
Constructor.
Creates a new Zeroconf::Browser and starts it.
Parameters
bugCollector the algorithm to give to new BugPlotReader objects
prefix the filter to apply for BugPlot publishers
Definition at line 116 of file BugPlotSubscriber.cc.
References SideCar::Messages::BugPlot::GetMetaTypeInfo(), SideCar::IO::ZeroconfRegistry::GetType(), SideCar::Zeroconf::Browser::Make(), SideCar::Zeroconf::ACEMonitorFactory::Make(), and SideCar::IO::ZeroconfRegistry::MakeZeroconfType().
BugPlotSubscriber::~BugPlotSubscriber ()
Destructor.
Shut down all BugPlotReader instances.
Definition at line 133 of file BugPlotSubscriber.cc.
Member Function Documentation
int BugPlotSubscriber::handle_timeout (const ACE_Time_Value & duration, const void * arg)
Override of ACE_Event_Handler::handle_timeout().
Emits heartbeats for all active BugPlotReader objects.
Parameters
duration ignored
arg ignored
Returns
0
Definition at line 197 of file BugPlotSubscriber.cc.
void BugPlotSubscriber::setPrefix (const std::string & value)
Change the publisher name filter.
NOTE: this will destroy any existing BugPlotReader instances.
Parameters
value new prefix value
Definition at line 143 of file BugPlotSubscriber.cc.
References SideCar::Algorithms::BugCollectorUtils::BugPlotReader::openAndInit().
size_t SideCar::Algorithms::BugCollectorUtils::BugPlotSubscriber::size () const inline
Obtain the number of active BugPlotReader instances.
Returns
Definition at line 115 of file BugPlotSubscriber.h.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/BugCollector/BugPlotSubscriber.h
/Users/howes/src/sidecar/Algorithms/BugCollector/BugPlotSubscriber.cc