SideCar: SideCar::GUI::Master::ConfigurationInfo Class Reference
SideCar::GUI::Master::ConfigurationInfo Class Reference
Class that holds information about a particular configuration file.
#include </Users/howes/src/sidecar/GUI/Master/ConfigurationInfo.h>
Public Types
enum Status {
kError, kNotRunning, kPartial, kRunning,
kRecording
}
Set of values for the ocnfiguration status.
Public Slots
void diskSpaceUpdate (double percentUsed, QString freeSpace)
Slot for disk space updates.
Public Member Functions
ConfigurationInfo (QObject *parent, ConfigurationModel *model, const QString &path)
Constructor.
~ConfigurationInfo ()
Destructor.
ConfigurationEditor * getEditor ()
Obtain an editor for the configuration file.
Status getStatus () const
Obtain the current configuration status.
QString getErrorText () const
Obtain the error text generated when the configuration file was loaded.
QString getStatusText () const
Get the status text for the configuration, based on the current status value.
QStringList getHostNames () const
Obtain the list of host names that run remote Runner processes as defined in the loaded configuration file.
QStringList getIncludePaths () const
Obtain the list of files that the configuration file included during loading.
QString getName () const
Obtain the name of the configuration file.
QString getPath () const
Obtain the path of the configuraton file.
QString getLogsDirectory () const
Obtain the log directory defined in the configuration file.
QString getRecordingsDirectory () const
Obtain the recording directory defined in the configuration file.
double getRecordingDirPercentUsed () const
Obtain the perentage of recording space in use.
QString getRecordingDirFreeSpace () const
Obtain the amount of free space in the recording path.
bool hasValidRecordingDirectory () const
Determine if the recording directory exists on the system.
bool reload ()
Attempt to reload the configuration file.
bool load (bool hideErrors)
Load the configuration file.
bool startup ()
Start the remote Runner processes defined by the configuration file.
void setStatus (Status status)
Change the status to the given value.
void shuttingDown ()
Set a flag indicating that the configuration is shutting down.
bool isStartingUp () const
Determine if the configuration file is currently starting up.
bool isShuttingDown () const
Determine if the configuration file is currently shutting down.
bool hasError () const
Determine if there was an error loading the configuration file.
bool isNotRunning () const
Determine if the configuration is not running at all.
bool isRunning () const
Determine if the configuration has at least one Runner running.
bool isRecording () const
Determine if the configuration is currently recording.
void setRecordingState (bool state)
Change the recording state of the configuration.
void foundRunner (const RunnerItem *runner)
The Master application detected status for a remote Runner.
void lostRunner (const QString &runner)
The Master application detected that a remote Runner is no longer running.
bool isRecordable () const
Determine if the configuration is recordable.
void setRecordable (bool state)
Change the recordability for this configuration.
bool isViewable () const
Determine if the Runner status should be viewable for this configuration.
void setViewable (bool state)
Change the visibility of the Runner status for this configuration.
bool canRecord () const
Determin if this configuration can record data.
int getRunningRunnerCount () const
Obtain the current number of found remote Runner processes.
int getConfiguredRunnerCount () const
Obtain the configured number of remote Runner processes.
Static Public Member Functions
static Logger::Log & Log ()
Log device for ConfigurationInfo instances.
Detailed Description
Class that holds information about a particular configuration file.
Also manages startup / shutdown for remote Runner processes.
Definition at line 27 of file ConfigurationInfo.h.
Member Enumeration Documentation
enum SideCar::GUI::Master::ConfigurationInfo::Status
Set of values for the ocnfiguration status.
Enumerator
kError
Configuration has an error.
kNotRunning
Configuration is not running.
kPartial
Configuration is running but incomplete.
kRunning
Configuration is running and complete.
Definition at line 35 of file ConfigurationInfo.h.
Constructor & Destructor Documentation
ConfigurationInfo::ConfigurationInfo (QObject * parent, ConfigurationModel * model, const QString & path)
Constructor.
Parameters
path location of the XML configuration file to load
Definition at line 48 of file ConfigurationInfo.cc.
References Log(), and LOGINFO.
Member Function Documentation
bool SideCar::GUI::Master::ConfigurationInfo::canRecord () const inline
Determin if this configuration can record data.
Returns
Definition at line 261 of file ConfigurationInfo.h.
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController().
void ConfigurationInfo::diskSpaceUpdate (double percentUsed, QString freeSpace) slot
Slot for disk space updates.
Parameters
percentUsed current percentage used
freeSpace current free space available
Definition at line 489 of file ConfigurationInfo.cc.
Referenced by load().
void ConfigurationInfo::foundRunner (const RunnerItem * runner)
The Master application detected status for a remote Runner.
Update the status of this configuration.
Parameters
runner name of the remote Runner that was found
Definition at line 303 of file ConfigurationInfo.cc.
References SideCar::Configuration::Loader::getRunnerConfig(), SideCar::GUI::Master::RunnerItem::getServiceName(), SideCar::Configuration::RunnerConfig::getServiceName(), Log(), LOGDEBUG, LOGINFO, and setRecordingState().
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController().
int SideCar::GUI::Master::ConfigurationInfo::getConfiguredRunnerCount () const inline
Obtain the configured number of remote Runner processes.
Returns
count
Definition at line 274 of file ConfigurationInfo.h.
ConfigurationEditor * ConfigurationInfo::getEditor ()
Obtain an editor for the configuration file.
Returns
ConfigurationEditor instance.
Definition at line 547 of file ConfigurationInfo.cc.
References SideCar::GUI::MainWindowBase::initialize().
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController().
QString SideCar::GUI::Master::ConfigurationInfo::getErrorText () const inline
Obtain the error text generated when the configuration file was loaded.
Returns
error text
Definition at line 77 of file ConfigurationInfo.h.
QStringList SideCar::GUI::Master::ConfigurationInfo::getHostNames () const inline
Obtain the list of host names that run remote Runner processes as defined in the loaded configuration file.
Returns
host name list
Definition at line 91 of file ConfigurationInfo.h.
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController().
QStringList SideCar::GUI::Master::ConfigurationInfo::getIncludePaths () const inline
Obtain the list of files that the configuration file included during loading.
Returns
include path list
Definition at line 97 of file ConfigurationInfo.h.
QString SideCar::GUI::Master::ConfigurationInfo::getLogsDirectory () const inline
Obtain the log directory defined in the configuration file.
Returns
directory path
Definition at line 116 of file ConfigurationInfo.h.
QString SideCar::GUI::Master::ConfigurationInfo::getName () const inline
Obtain the name of the configuration file.
This value appears in the confiugration status table in the main window.
Returns
configuration name
Definition at line 104 of file ConfigurationInfo.h.
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController(), SideCar::GUI::Master::ConfigurationEditor::ConfigurationEditor(), load(), lostRunner(), SideCar::GUI::Master::MainWindow::MainWindow(), setRecordable(), setStatus(), and setViewable().
QString SideCar::GUI::Master::ConfigurationInfo::getPath () const inline
Obtain the path of the configuraton file.
Returns
configuraton path
Definition at line 110 of file ConfigurationInfo.h.
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController(), SideCar::GUI::Master::ConfigurationEditor::ConfigurationEditor(), and SideCar::GUI::Master::RecordingController::Log().
QString SideCar::GUI::Master::ConfigurationInfo::getRecordingDirFreeSpace () const inline
Obtain the amount of free space in the recording path.
Formatted as a numeric value followed by a unit, such as 'MB' or 'GB'.
Returns
formatted disk space
Definition at line 138 of file ConfigurationInfo.h.
double SideCar::GUI::Master::ConfigurationInfo::getRecordingDirPercentUsed () const inline
Obtain the perentage of recording space in use.
Returns
value between 0 and 100
Definition at line 130 of file ConfigurationInfo.h.
QString SideCar::GUI::Master::ConfigurationInfo::getRecordingsDirectory () const inline
Obtain the recording directory defined in the configuration file.
Returns
directory path
Definition at line 123 of file ConfigurationInfo.h.
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController(), and SideCar::GUI::Master::RecordingController::Log().
int SideCar::GUI::Master::ConfigurationInfo::getRunningRunnerCount () const inline
Obtain the current number of found remote Runner processes.
Returns
count
Definition at line 268 of file ConfigurationInfo.h.
Status SideCar::GUI::Master::ConfigurationInfo::getStatus () const inline
Obtain the current configuration status.
Returns
current status
Definition at line 70 of file ConfigurationInfo.h.
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController(), getStatusText(), lostRunner(), and SideCar::GUI::Master::MainWindow::MainWindow().
QString ConfigurationInfo::getStatusText () const
Get the status text for the configuration, based on the current status value.
This value appears in the configuration status table in the main window.
Returns
status text
Definition at line 524 of file ConfigurationInfo.cc.
References getStatus(), and kPartial.
bool SideCar::GUI::Master::ConfigurationInfo::hasError () const inline
Determine if there was an error loading the configuration file.
Returns
true if so
Definition at line 194 of file ConfigurationInfo.h.
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController(), and SideCar::GUI::Master::ConfigurationEditor::ConfigurationEditor().
bool ConfigurationInfo::hasValidRecordingDirectory () const
Determine if the recording directory exists on the system.
Returns
true if so
Definition at line 460 of file ConfigurationInfo.cc.
References SideCar::GUI::Master::App::GetApp(), SideCar::Configuration::Loader::getRecordingsDirectory(), kError, Log(), LOGERROR, and setStatus().
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController().
bool SideCar::GUI::Master::ConfigurationInfo::isNotRunning () const inline
Determine if the configuration is not running at all.
Returns
true if so
Definition at line 200 of file ConfigurationInfo.h.
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController().
bool SideCar::GUI::Master::ConfigurationInfo::isRecordable () const inline
Determine if the configuration is recordable.
Returns
true if so
Definition at line 237 of file ConfigurationInfo.h.
bool SideCar::GUI::Master::ConfigurationInfo::isRecording () const inline
Determine if the configuration is currently recording.
Returns
true if so
Definition at line 212 of file ConfigurationInfo.h.
Referenced by SideCar::GUI::Master::MainWindow::MainWindow().
bool SideCar::GUI::Master::ConfigurationInfo::isRunning () const inline
Determine if the configuration has at least one Runner running.
Returns
true if so
Definition at line 206 of file ConfigurationInfo.h.
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController(), and lostRunner().
bool SideCar::GUI::Master::ConfigurationInfo::isShuttingDown () const inline
Determine if the configuration file is currently shutting down.
Returns
true if so
Definition at line 188 of file ConfigurationInfo.h.
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController().
bool SideCar::GUI::Master::ConfigurationInfo::isStartingUp () const inline
Determine if the configuration file is currently starting up.
Returns
true if so
Definition at line 182 of file ConfigurationInfo.h.
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController().
bool SideCar::GUI::Master::ConfigurationInfo::isViewable () const inline
Determine if the Runner status should be viewable for this configuration.
Returns
true if so
Definition at line 249 of file ConfigurationInfo.h.
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController().
bool ConfigurationInfo::load (bool hideErrors)
Load the configuration file.
Parameters
hideErrors don't show syntax error prompt if true
Returns
true if successsful
Definition at line 72 of file ConfigurationInfo.cc.
References diskSpaceUpdate(), SideCar::GUI::Master::App::GetApp(), SideCar::Configuration::Loader::getConfigurationName(), SideCar::Configuration::Loader::getLastLoadResult(), getName(), SideCar::Configuration::Loader::getNumRunnerConfigs(), SideCar::Configuration::Loader::getParseErrorInfo(), SideCar::Configuration::Loader::getParseFilePath(), SideCar::Configuration::Loader::getRecordingsDirectory(), kNotRunning, SideCar::Configuration::Loader::load(), Log(), LOGINFO, and setStatus().
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController(), and startup().
Logger::Log & ConfigurationInfo::Log () static
Log device for ConfigurationInfo instances.
Returns
log device
Definition at line 42 of file ConfigurationInfo.cc.
References Logger::Log::Find().
Referenced by ConfigurationInfo(), foundRunner(), hasValidRecordingDirectory(), load(), lostRunner(), setStatus(), and startup().
void ConfigurationInfo::lostRunner (const QString & runner)
The Master application detected that a remote Runner is no longer running.
Update the status of this configuration.
Parameters
runner name of the remote Runner that was found
Definition at line 332 of file ConfigurationInfo.cc.
References SideCar::Configuration::Loader::getConfigurationName(), SideCar::Configuration::RunnerConfig::getHostName(), getName(), SideCar::Configuration::Loader::getRunnerConfig(), SideCar::Configuration::RunnerConfig::getRunnerName(), SideCar::Configuration::RunnerConfig::getServiceName(), getStatus(), isRunning(), kNotRunning, kPartial, kRunning, Log(), LOGINFO, and setStatus().
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController().
bool SideCar::GUI::Master::ConfigurationInfo::reload () inline
Attempt to reload the configuration file.
Returns
true if successsful
Definition at line 151 of file ConfigurationInfo.h.
Referenced by SideCar::GUI::Master::ConfigurationEditor::ConfigurationEditor().
void ConfigurationInfo::setRecordable (bool state)
Change the recordability for this configuration.
Parameters
state new state
Definition at line 512 of file ConfigurationInfo.cc.
References getName().
void ConfigurationInfo::setRecordingState (bool state)
Change the recording state of the configuration.
Parameters
state new state
Definition at line 445 of file ConfigurationInfo.cc.
References SideCar::GUI::Master::App::GetApp().
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController(), and foundRunner().
void ConfigurationInfo::setStatus (Status status)
Change the status to the given value.
Parameters
status new value to use
Definition at line 424 of file ConfigurationInfo.cc.
References getName(), kError, kNotRunning, kRunning, Log(), and LOGINFO.
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController(), hasValidRecordingDirectory(), load(), and lostRunner().
void ConfigurationInfo::setViewable (bool state)
Change the visibility of the Runner status for this configuration.
Parameters
state new state.
Definition at line 500 of file ConfigurationInfo.cc.
References getName().
void SideCar::GUI::Master::ConfigurationInfo::shuttingDown () inline
Set a flag indicating that the configuration is shutting down.
Inhibits the error prompt that shows up when a remote process exits.
Definition at line 176 of file ConfigurationInfo.h.
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController(), and SideCar::GUI::Master::MainWindow::MainWindow().
bool ConfigurationInfo::startup ()
Start the remote Runner processes defined by the configuration file.
Returns
true if successsful
Definition at line 201 of file ConfigurationInfo.cc.
References SideCar::Configuration::Loader::getConfigurationName(), SideCar::Configuration::RunnerConfig::getHostName(), SideCar::Configuration::Loader::getRunnerConfig(), SideCar::Configuration::RunnerConfig::getRunnerName(), load(), Log(), LOGINFO, and SideCar::GUI::Master::Launcher::start().
Referenced by SideCar::GUI::Master::ConfigurationController::ConfigurationController().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/ConfigurationInfo.h
/Users/howes/src/sidecar/GUI/Master/ConfigurationInfo.cc