SideCar: SideCar::Runner::RemoteController Class Reference
SideCar::Runner::RemoteController Class Reference
A remote controller class for App objects.
#include </Users/howes/src/sidecar/Runner/RemoteController.h>
Public Member Functions
RemoteController (App &app)
Constructor.
bool start (const QString &serviceName, long threadFlags=THR_NEW_LWP|THR_JOINABLE|THR_INHERIT_SCHED, long priority=ACE_DEFAULT_THREAD_PRIORITY)
Start the XML-RPC service.
Public Member Functions inherited from SideCar::Algorithms::RemoteControllerBase
RemoteControllerBase (const char *zerconfType)
Constructor.
~RemoteControllerBase ()
Destructor.
bool start (const std::string &serviceName, long threadFlags=THR_NEW_LWP|THR_JOINABLE|THR_INHERIT_SCHED, long priority=ACE_DEFAULT_THREAD_PRIORITY)
Start the remote controller.
bool stop ()
Stop the remote controller.
int close (u_long flags=0) override
Shutdown the controller if it is running.
Static Public Member Functions
static Logger::Log & Log ()
Log device for objects of this type.
Static Public Member Functions inherited from SideCar::Algorithms::RemoteControllerBase
static Logger::Log & Log ()
Log device for objects of this type.
Static Public Member Functions inherited from SideCar::IO::ZeroconfTypes::TZCType< id >
static const char * GetZeroconfType ()
Obtain the configured Zeroconf type for objects derived from this class.
static const char * GetTwinZeroconfType ()
Obtain the "twin" Zeroconf type for objects derived from this class.
static std::string MakeZeroconfType (const std::string &subType)
Construct a valid SideCar Zeroconf type string for a given subtype.
static std::string MakeTwinZeroconfType (const std::string &subType)
Construct the twin SideCar Zeroconf type string for a given subtype.
Static Public Member Functions inherited from SideCar::IO::ZeroconfRegistry
static const char * GetType (ID id)
Obtain the Zeroconf type string for a given ID.
static ID GetTwin (ID id)
Locate the twin of this ID.
static std::string MakeZeroconfType (const char *type, const std::string &subType)
Construct a valid SideCar Zeroconf type string for a type and a subtype.
Additional Inherited Members
Public Types inherited from SideCar::Algorithms::RemoteControllerBase
using ZCPublisherRef = boost::shared_ptr< Zeroconf::Publisher >
Public Types inherited from SideCar::IO::ZeroconfRegistry
enum ID {
kPublisher = 0, kSubscriber, kRunnerStatusCollector, kRunnerStatusEmitter,
kStateEmitter, kStateCollector, kRunnerRemoteController, kNumTypes
}
Defined Zeroconf types.
Detailed Description
A remote controller class for App objects.
Definition at line 17 of file RemoteController.h.
Constructor & Destructor Documentation
SideCar::Runner::RemoteController::RemoteController (App & app) inline
Constructor.
Parameters
app reference to the App object to control
Definition at line 31 of file RemoteController.h.
References SideCar::IO::ZeroconfTypes::TZCType< id >::GetZeroconfType(), and start().
Member Function Documentation
Logger::Log & RemoteController::Log () static
Log device for objects of this type.
Returns
log device
Definition at line 225 of file RemoteController.cc.
References Logger::Log::Find().
bool RemoteController::start (const QString & serviceName, long threadFlags = THR_NEW_LWP | THR_JOINABLE | THR_INHERIT_SCHED, long priority = ACE_DEFAULT_THREAD_PRIORITY)
Start the XML-RPC service.
Parameters
serviceName the name to advertise
threadFlags flags controlling the service thread
priority priority of the service thread
Returns
true if started, false otherwise
Definition at line 232 of file RemoteController.cc.
References XmlRpc::XmlRpcServer::enableIntrospection(), LOGERROR, and LOGINFO.
Referenced by RemoteController().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Runner/RemoteController.h
/Users/howes/src/sidecar/Runner/RemoteController.cc