SideCar: SideCar::GUI::Master::TreeViewItem Class Reference
SideCar::GUI::Master::TreeViewItem Class Reference abstract
Base class for a row in a QTreeView display.
#include </Users/howes/src/sidecar/GUI/Master/TreeViewItem.h>
Public Types
enum ActiveState { kIdle, kPartial, kActive, kNotUsingData }
using Children = QList< TreeViewItem * >
using ChildrenIterator = QListIterator< TreeViewItem * >
Public Member Functions
~TreeViewItem ()
Destructor.
virtual void initialize ()
Initialize this object's internal state.
const IO::StatusBase & getStatus () const
Obtain the latest IO::StatusBase object received for this object.
bool update (const IO::StatusBase &status)
Update the TreeViewItem held status.
bool isOK () const
bool isProcessing () const
Determine if the object is in a 'processing' state: auto-diagnostic, calibration, or run.
ActiveState getActiveState () const
Obtain the current ActiveState value for this object.
QVariant getData (int column, int role) const
Obtain the data point to use for a specific role in a given column.
virtual QVariant getNameDataValue (int role) const
Obtain the data value for the ServicesModel::kName column, which displays the name of the TreeViewItem.
virtual QVariant getHostDataValue (int role) const
Obtain the data value for the ServicesModel::kHost column, which displays the host name of the machine where the object is running.
virtual QVariant getStateDataValue (int role) const
Obtain the data value for the ServicesModel::kState column, which displays the processing state of the TreeViewItem.
virtual QVariant getRecordingDataValue (int role) const
Obtain the data value for the ServicesModel::kRecording column, which displays the recording state of the TreeViewItem.
virtual QVariant getPendingCountValue (int role) const
Obtain the data value for the ServicesModel::kPending column, which displays the pending queue size of this item.
virtual QVariant getRateDataValue (int role) const
Obtain the data value for the ServicesModel::kRate column, which displays the message processing rate of the TreeViewItem.
virtual QVariant getErrorDataValue (int role) const
Obtain the data value for the ServicesModel::kError column, which displays any error text from the TreeViewItem.
virtual QVariant getInfoDataValue (int role) const
Obtain the data value for the ServicesModel::kInfo column, which displays miscellaneous informational data of the TreeViewItem.
virtual QColor getForegroundColor (int column) const
Obtain the foreground color to use for the contents of a given column.
virtual QFont getFont (int column) const
Obtain the font to use for the contents of a given column.
virtual int getAlignment (int columnt) const
Obtain the alignment (horizontal and vertical) to use for the contents of a given column.
virtual bool canEdit () const
Determine if the TreeViewItem supports editing of runtime parameter values.
virtual bool canExpand () const
Determine if the TreeViewItem is expandable.
const QString & getName () const
Obtain the object's name.
const QString & getFullName () const
Get the full name of the item.
void insertChild (int row, TreeViewItem *child)
Insert a child, renumbering the indices of all children after it.
void appendChild (TreeViewItem *child)
Add a child.
void removeChild (int index)
Remove the child at a given index.
TreeViewItem * getChild (int index) const
Obtain the child associated with a given index value.
int getNumChildren () const
Obtain the number of children.
int getIndex () const
Obtain the index of this object in the context of our parent's children array.
TreeViewItem * getParent () const
Obtain the parent of this TreeViewItem object.
int getParentIndex () const
Obtain the index value of the parent object (equivalent to getParent()->getIndex().
ChildrenIterator getChildrenIterator () const
Obtain a Java-style iterator for the children array.
bool isExpanded () const
Determine if the object is expanded.
void setExpanded (bool expanded)
Change the expansion attribute of the object.
virtual void updateCollectionStats (CollectionStats &stats) const =0
Prototype for method to update a CollectionStats object with statistics provided by a TreeViewItem derivative.
int getInsertionPoint (const QString &name) const
Obtain the row where the given name could be inserted without disturbing the ordering of the existing rows.
virtual bool isFiltered (const QString &filter) const
Determine if this item contains the given filter string.
Static Public Member Functions
static QVariant GetRecordingDataValue (bool canRecord, int role)
Utility class method that returns an appropriate value for the recording state depicted by the two arguments.
static QColor GetTextColor ()
Class method that returns the default (black) text color for all Qt::Foreground roles.
static QColor GetOKColor ()
Class method that returns the OK text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetWarningColor ()
Class method that returns the 'warning text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetFailureColor ()
Class method that returns the 'failure' text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
static QColor GetRecordingColor ()
Class method that returns the text color to use to show when a task is currently recording.
static QFont GetTextFont ()
Obtain the normal font to use for displayed text.
Protected Member Functions
TreeViewItem ()
Constructor for the RootItem object (which has no parent).
TreeViewItem (const IO::StatusBase &status, TreeViewItem *parent)
Constructor for all derived classes except RootItem.
void setName (const QString &name)
void setOK (bool ok)
void setProcessing (bool processing)
void setProcessingState (IO::ProcessingState::Value state)
void setActiveState (ActiveState activeState)
virtual void beforeUpdate ()
Hook invoked before a status update.
virtual void afterUpdate ()
Hook invoked after a status update.
template<typename T >
const T & getStatusT () const
virtual void childAdded (TreeViewItem *child)
virtual void childRemoved (TreeViewItem *child)
Detailed Description
Base class for a row in a QTreeView display.
All TreeViewItem objects have a parent (though the parent may be NULL), and a TreeViewItem may have children. Supports adding and removing of children and fetching of a particular child by index. Defines the display interface used by ServicesModel to obtain the data to display in a column.
The TreeViewItem::getData() method is the main entry point for data retrieval from an item. It is called by the ServicesModel::data() method. Internally, getData() switches on the column index, calling the appropriate virtual method for the column. There are five columns (ServicesModel::kNumColumns) of data, and thus five methods:
getNameDataValue
getStateDataValue
getRecordingDataValue
getRateDataValue
getInfoDataValue
Each method takes a display role as its sole argument, which specify the type of data to return. If a method has no value to return, it must return a null QVariant instance, obtained by QVariant(). If the method returns a null QVariant, getData() will, for certain display roles, attempt to get values from the following virtual methods:
getAlignment
getFont
getForegroundColor
Each method takes a column index as its sole argument.
Definition at line 46 of file TreeViewItem.h.
Member Enumeration Documentation
enum SideCar::GUI::Master::TreeViewItem::ActiveState
Enumerator
kIdle
Item has not processed data recently.
kPartial
Some but not all chilren are kIdle.
kActive
Item or all children are processing data.
kNotUsingData
Item is not pulling data.
Definition at line 53 of file TreeViewItem.h.
Constructor & Destructor Documentation
TreeViewItem::~TreeViewItem ()
Destructor.
Deletes all held children.
Definition at line 73 of file TreeViewItem.cc.
TreeViewItem::TreeViewItem (const IO::StatusBase & status, TreeViewItem * parent) protected
Constructor for all derived classes except RootItem.
Parameters
status the initial status value for the object
parent the parent of the item
Definition at line 63 of file TreeViewItem.cc.
Member Function Documentation
virtual void SideCar::GUI::Master::TreeViewItem::afterUpdate () inline protected virtual
Hook invoked after a status update.
This implementation does nothing.
Reimplemented in SideCar::GUI::Master::RunnerItem, SideCar::GUI::Master::ControllerItem, SideCar::GUI::Master::TaskItem, and SideCar::GUI::Master::CollectionItem.
Definition at line 412 of file TreeViewItem.h.
References getStatus().
Referenced by SideCar::GUI::Master::TaskItem::afterUpdate(), initialize(), and update().
void TreeViewItem::appendChild (TreeViewItem * child)
Add a child.
Parameters
child the TreeViewItem to remember
Definition at line 253 of file TreeViewItem.cc.
References initialize().
Referenced by getFullName(), and SideCar::GUI::Master::StreamItem::StreamItem().
virtual void SideCar::GUI::Master::TreeViewItem::beforeUpdate () inline protected virtual
Hook invoked before a status update.
This implementation does nothing.
Reimplemented in SideCar::GUI::Master::TaskItem, and SideCar::GUI::Master::CollectionItem.
Definition at line 408 of file TreeViewItem.h.
Referenced by initialize(), and update().
virtual bool SideCar::GUI::Master::TreeViewItem::canEdit () const inline virtual
Determine if the TreeViewItem supports editing of runtime parameter values.
Derived classes must redefine if they do.
Returns
always returns false
Reimplemented in SideCar::GUI::Master::ControllerItem.
Definition at line 261 of file TreeViewItem.h.
Referenced by SideCar::GUI::Master::ServicesView::setModel().
virtual bool SideCar::GUI::Master::TreeViewItem::canExpand () const inline virtual
Determine if the TreeViewItem is expandable.
Returns
true if so.
Reimplemented in SideCar::GUI::Master::CollectionItem.
Definition at line 267 of file TreeViewItem.h.
Referenced by SideCar::GUI::Master::ServicesView::setModel().
ActiveState SideCar::GUI::Master::TreeViewItem::getActiveState () const inline
Obtain the current ActiveState value for this object.
Returns
ActiveState value
Definition at line 146 of file TreeViewItem.h.
References getData(), and getNameDataValue().
Referenced by SideCar::GUI::Master::CollectionItem::getRateDataValue(), and SideCar::GUI::Master::TaskItem::updateCollectionStats().
int TreeViewItem::getAlignment (int columnt) const virtual
Obtain the alignment (horizontal and vertical) to use for the contents of a given column.
Parameters
column the column to work on
\return alignment flags
Definition at line 219 of file TreeViewItem.cc.
Referenced by getData(), and getHostDataValue().
TreeViewItem* SideCar::GUI::Master::TreeViewItem::getChild (int index) const inline
Obtain the child associated with a given index value.
Parameters
index which child to return
Returns
TreeViewItem pointer
Definition at line 309 of file TreeViewItem.h.
Referenced by SideCar::GUI::Master::CollectionItem::afterUpdate(), SideCar::GUI::Master::RootItem::find(), SideCar::GUI::Master::StreamItem::getChild(), SideCar::GUI::Master::ConfigurationItem::getChild(), SideCar::GUI::Master::RunnerItem::getChild(), and getInsertionPoint().
ChildrenIterator SideCar::GUI::Master::TreeViewItem::getChildrenIterator () const inline
Obtain a Java-style iterator for the children array.
Returns
iterator
Definition at line 339 of file TreeViewItem.h.
QVariant TreeViewItem::getData (int column, int role) const
Obtain the data point to use for a specific role in a given column.
Parameters
column the column to fetch
role the display role that determines the type of data to return
Returns
found value or QVariant() if nothing special to display
Definition at line 89 of file TreeViewItem.cc.
References getAlignment(), getErrorDataValue(), getForegroundColor(), getHostDataValue(), getInfoDataValue(), getNameDataValue(), getPendingCountValue(), getRateDataValue(), getRecordingDataValue(), and getStateDataValue().
Referenced by getActiveState().
QVariant TreeViewItem::getErrorDataValue (int role) const virtual
Obtain the data value for the ServicesModel::kError column, which displays any error text from the TreeViewItem.
Parameters
role the display role that determines the type of data to return
Returns
null QVariant
Reimplemented in SideCar::GUI::Master::TaskItem, and SideCar::GUI::Master::CollectionItem.
Definition at line 167 of file TreeViewItem.cc.
Referenced by getData(), SideCar::GUI::Master::CollectionItem::getErrorDataValue(), SideCar::GUI::Master::TaskItem::getErrorDataValue(), and getHostDataValue().
QColor TreeViewItem::GetFailureColor () static
Class method that returns the 'failure' text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
Returns
dark red color
Definition at line 42 of file TreeViewItem.cc.
Referenced by getForegroundColor(), SideCar::GUI::Master::RunnerItem::getInfoDataValue(), SideCar::GUI::Master::CollectionItem::getRateDataValue(), SideCar::GUI::Master::TaskItem::getRateDataValue(), SideCar::GUI::Master::LogViewWindow::Log(), and SideCar::GUI::Master::MainWindow::MainWindow().
QFont TreeViewItem::getFont (int column) const virtual
Obtain the font to use for the contents of a given column.
Parameters
column the column to work on
Returns
QFont value
Definition at line 207 of file TreeViewItem.cc.
References GetTextFont().
Referenced by getHostDataValue().
QColor TreeViewItem::getForegroundColor (int column) const virtual
Obtain the foreground color to use for the contents of a given column.
Parameters
column the column to work on
Returns
QColor value
Definition at line 179 of file TreeViewItem.cc.
References GetFailureColor(), GetOKColor(), GetTextColor(), GetWarningColor(), and kActive.
Referenced by getData(), and getHostDataValue().
const QString& SideCar::GUI::Master::TreeViewItem::getFullName () const inline
Get the full name of the item.
This is a colon-separated list of names that depict the inheritance relationship for this item. The first name in the list is the name of a RunnerItem. The last name is this items's name.
Returns
full name
Definition at line 281 of file TreeViewItem.h.
References appendChild(), insertChild(), and removeChild().
Referenced by GetRecordingDataValue(), SideCar::GUI::Master::ServicesView::rowsInserted(), and SideCar::GUI::Master::ServicesView::setModel().
virtual QVariant SideCar::GUI::Master::TreeViewItem::getHostDataValue (int role) const inline virtual
Obtain the data value for the ServicesModel::kHost column, which displays the host name of the machine where the object is running.
Parameters
role the display role that determines the type of data to return
Returns
null QVariant
Reimplemented in SideCar::GUI::Master::RunnerItem.
Definition at line 173 of file TreeViewItem.h.
References getAlignment(), getErrorDataValue(), getFont(), getForegroundColor(), getInfoDataValue(), getPendingCountValue(), getRateDataValue(), getRecordingDataValue(), and getStateDataValue().
Referenced by getData(), and SideCar::GUI::Master::RunnerItem::getHostDataValue().
int SideCar::GUI::Master::TreeViewItem::getIndex () const inline
Obtain the index of this object in the context of our parent's children array.
Returns
index of self
Definition at line 321 of file TreeViewItem.h.
Referenced by SideCar::GUI::Master::ServicesModel::getChangedParameters(), SideCar::GUI::Master::ControllerItem::getParameters(), SideCar::GUI::Master::RunnerItem::RunnerItem(), and SideCar::GUI::Master::ControllerItem::setParameters().
QVariant TreeViewItem::getInfoDataValue (int role) const virtual
Obtain the data value for the ServicesModel::kInfo column, which displays miscellaneous informational data of the TreeViewItem.
Parameters
role the display role that determines the type of data to return
Returns
null QVariant
Reimplemented in SideCar::GUI::Master::RunnerItem, SideCar::GUI::Master::ControllerItem, SideCar::GUI::Master::TaskItem, and SideCar::GUI::Master::RawPRIItem.
Definition at line 173 of file TreeViewItem.cc.
Referenced by getData(), getHostDataValue(), SideCar::GUI::Master::TaskItem::getInfoDataValue(), and SideCar::GUI::Master::RunnerItem::getInfoDataValue().
int TreeViewItem::getInsertionPoint (const QString & name) const
Obtain the row where the given name could be inserted without disturbing the ordering of the existing rows.
Uses the name_ attribute of its children to determine ordering.
Parameters
name the value to check
Returns
location to insert, 0 for beginning of children_ and children_.size() for end.
Definition at line 325 of file TreeViewItem.cc.
References getChild(), getName(), and getNumChildren().
Referenced by SideCar::GUI::Master::ServicesModel::getChangedParameters(), SideCar::GUI::Master::RunnerItem::RunnerItem(), and setExpanded().
const QString& SideCar::GUI::Master::TreeViewItem::getName () const inline
Obtain the object's name.
Returns
name value
Definition at line 273 of file TreeViewItem.h.
Referenced by SideCar::GUI::Master::LogViewWindowManager::addLogInfo(), SideCar::GUI::Master::RunnerItem::afterUpdate(), SideCar::GUI::Master::RootItem::find(), SideCar::GUI::Master::ServicesModel::getChangedParameters(), getInsertionPoint(), SideCar::GUI::Master::NotificationParam::revertToOriginal(), SideCar::GUI::Master::ServicesView::rowsInserted(), SideCar::GUI::Master::RunnerItem::RunnerItem(), SideCar::GUI::Master::ServicesView::setModel(), and SideCar::GUI::Master::TaskItem::updateCollectionStats().
QVariant TreeViewItem::getNameDataValue (int role) const virtual
Obtain the data value for the ServicesModel::kName column, which displays the name of the TreeViewItem.
Parameters
role the display role that determines the type of data to return
Returns
object name if role is Qt::DisplayRole
Reimplemented in SideCar::GUI::Master::ControllerItem, SideCar::GUI::Master::TaskItem, and SideCar::GUI::Master::CollectionItem.
Definition at line 136 of file TreeViewItem.cc.
Referenced by getActiveState(), getData(), SideCar::GUI::Master::CollectionItem::getNameDataValue(), and SideCar::GUI::Master::TaskItem::getNameDataValue().
int SideCar::GUI::Master::TreeViewItem::getNumChildren () const inline
Obtain the number of children.
Returns
child count
Definition at line 315 of file TreeViewItem.h.
Referenced by SideCar::GUI::Master::CollectionItem::afterUpdate(), SideCar::GUI::Master::ConfigurationItem::ConfigurationItem(), SideCar::GUI::Master::ConfigurationItem::executeRequest(), SideCar::GUI::Master::RootItem::find(), SideCar::GUI::Master::ServicesModel::getChangedParameters(), SideCar::GUI::Master::RunnerItem::getChangedParameters(), SideCar::GUI::Master::StreamItem::getChild(), getInsertionPoint(), SideCar::GUI::Master::RunnerItem::RunnerItem(), and SideCar::GUI::Master::StreamItem::StreamItem().
QColor TreeViewItem::GetOKColor () static
Class method that returns the OK text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
Returns
dark green color
Definition at line 28 of file TreeViewItem.cc.
Referenced by getForegroundColor(), SideCar::GUI::Master::RunnerItem::getInfoDataValue(), and SideCar::GUI::Master::CollectionItem::getRateDataValue().
TreeViewItem* SideCar::GUI::Master::TreeViewItem::getParent () const inline
Obtain the parent of this TreeViewItem object.
Returns
TreeViewItem object (may be NULL)
Definition at line 327 of file TreeViewItem.h.
Referenced by SideCar::GUI::Master::TaskItem::getInfoDataValue(), SideCar::GUI::Master::StreamItem::getParent(), GetRecordingDataValue(), and SideCar::GUI::Master::TaskItem::updateCollectionStats().
int SideCar::GUI::Master::TreeViewItem::getParentIndex () const inline
Obtain the index value of the parent object (equivalent to getParent()->getIndex().
Returns
index of parent
Definition at line 333 of file TreeViewItem.h.
QVariant TreeViewItem::getPendingCountValue (int role) const virtual
Obtain the data value for the ServicesModel::kPending column, which displays the pending queue size of this item.
Parameters
role the display role that determines the type of data to return
Returns
null QVariant
null QVariant
Reimplemented in SideCar::GUI::Master::ControllerItem, SideCar::GUI::Master::TaskItem, and SideCar::GUI::Master::CollectionItem.
Definition at line 155 of file TreeViewItem.cc.
Referenced by getData(), getHostDataValue(), SideCar::GUI::Master::CollectionItem::getPendingCountValue(), and SideCar::GUI::Master::TaskItem::getPendingCountValue().
QVariant TreeViewItem::getRateDataValue (int role) const virtual
Obtain the data value for the ServicesModel::kRate column, which displays the message processing rate of the TreeViewItem.
Parameters
role the display role that determines the type of data to return
Returns
returns "Active" if the message counts of the last two status updates are different.
Reimplemented in SideCar::GUI::Master::ControllerItem, SideCar::GUI::Master::TaskItem, and SideCar::GUI::Master::CollectionItem.
Definition at line 161 of file TreeViewItem.cc.
Referenced by getData(), getHostDataValue(), SideCar::GUI::Master::CollectionItem::getRateDataValue(), and SideCar::GUI::Master::TaskItem::getRateDataValue().
QColor TreeViewItem::GetRecordingColor () static
Class method that returns the text color to use to show when a task is currently recording.
Returns
dark red color
Definition at line 21 of file TreeViewItem.cc.
Referenced by GetRecordingDataValue(), and SideCar::GUI::Master::MainWindow::MainWindow().
QVariant TreeViewItem::GetRecordingDataValue (bool canRecord, int role) static
Utility class method that returns an appropriate value for the recording state depicted by the two arguments.
Parameters
canRecord true if the item is enabled for recording
role the display role of the data to return
Returns
display data
Definition at line 272 of file TreeViewItem.cc.
References SideCar::GUI::Master::App::GetApp(), getFullName(), getParent(), GetRecordingColor(), SideCar::IO::ProcessingState::kAutoDiagnostic, SideCar::IO::ProcessingState::kCalibrate, SideCar::IO::ProcessingState::kFailure, and SideCar::IO::ProcessingState::kRun.
Referenced by SideCar::GUI::Master::CollectionItem::getRecordingDataValue(), and SideCar::GUI::Master::ControllerItem::getRecordingDataValue().
QVariant TreeViewItem::getRecordingDataValue (int role) const virtual
Obtain the data value for the ServicesModel::kRecording column, which displays the recording state of the TreeViewItem.
Parameters
role the display role that determines the type of data to return
Returns
null QVariant
Reimplemented in SideCar::GUI::Master::ControllerItem, and SideCar::GUI::Master::CollectionItem.
Definition at line 149 of file TreeViewItem.cc.
Referenced by getData(), and getHostDataValue().
QVariant TreeViewItem::getStateDataValue (int role) const virtual
Obtain the data value for the ServicesModel::kState column, which displays the processing state of the TreeViewItem.
Parameters
role the display role that determines the type of data to return
Returns
processing state name if role is Qt::DisplayRole
Reimplemented in SideCar::GUI::Master::TaskItem, and SideCar::GUI::Master::CollectionItem.
Definition at line 143 of file TreeViewItem.cc.
Referenced by getData(), getHostDataValue(), and SideCar::GUI::Master::CollectionItem::getStateDataValue().
const IO::StatusBase& SideCar::GUI::Master::TreeViewItem::getStatus () const inline
Obtain the latest IO::StatusBase object received for this object.
Returns
IO::StatusBase reference.
Definition at line 123 of file TreeViewItem.h.
References update().
Referenced by afterUpdate().
QColor TreeViewItem::GetTextColor () static
Class method that returns the default (black) text color for all Qt::Foreground roles.
Returns
black color
Definition at line 14 of file TreeViewItem.cc.
Referenced by getForegroundColor(), and SideCar::GUI::Master::CollectionItem::getNameDataValue().
QFont TreeViewItem::GetTextFont () static
Obtain the normal font to use for displayed text.
Returns
QFont value
Definition at line 49 of file TreeViewItem.cc.
Referenced by getFont().
QColor TreeViewItem::GetWarningColor () static
Class method that returns the 'warning text color for those Qt::Foreground roles that distinguish among an 'OK', 'warning', or 'failure' state.
Returns
dark yellow color
Definition at line 35 of file TreeViewItem.cc.
Referenced by getForegroundColor(), SideCar::GUI::Master::RunnerItem::getInfoDataValue(), and SideCar::GUI::Master::CollectionItem::getRateDataValue().
virtual void SideCar::GUI::Master::TreeViewItem::initialize () inline virtual
Initialize this object's internal state.
Derived classes may override. This implementation simply invokes beforeUpdate() followed by afterUpdate().
Definition at line 117 of file TreeViewItem.h.
References afterUpdate(), and beforeUpdate().
Referenced by appendChild(), and insertChild().
void TreeViewItem::insertChild (int row, TreeViewItem * child)
Insert a child, renumbering the indices of all children after it.
Parameters
index where to insert
\param child the TreeViewItem to remember
Definition at line 243 of file TreeViewItem.cc.
References initialize().
Referenced by SideCar::GUI::Master::ServicesModel::getChangedParameters(), getFullName(), and SideCar::GUI::Master::RunnerItem::RunnerItem().
bool SideCar::GUI::Master::TreeViewItem::isExpanded () const inline
Determine if the object is expanded.
Returns
true if so
Definition at line 345 of file TreeViewItem.h.
Referenced by SideCar::GUI::Master::CollectionItem::getErrorDataValue(), SideCar::GUI::Master::CollectionItem::getNameDataValue(), SideCar::GUI::Master::CollectionItem::getPendingCountValue(), SideCar::GUI::Master::CollectionItem::getRateDataValue(), SideCar::GUI::Master::CollectionItem::getRecordingDataValue(), and SideCar::GUI::Master::CollectionItem::getStateDataValue().
virtual bool SideCar::GUI::Master::TreeViewItem::isFiltered (const QString & filter) const inline virtual
Determine if this item contains the given filter string.
This implementation looks in the item's name_ attribute. Derivations are free to choose alternative filtering means, though they should always call this implementation for uniform behavior.
Parameters
filter the text to look for
Returns
true if found
Reimplemented in SideCar::GUI::Master::RunnerItem.
Definition at line 378 of file TreeViewItem.h.
References TreeViewItem().
Referenced by SideCar::GUI::Master::ServicesView::rowsInserted().
bool SideCar::GUI::Master::TreeViewItem::isProcessing () const inline
Determine if the object is in a 'processing' state: auto-diagnostic, calibration, or run.
Returns
true if so, false otherwise
Definition at line 140 of file TreeViewItem.h.
void TreeViewItem::removeChild (int index)
Remove the child at a given index.
Parameters
index which child to remove
Definition at line 262 of file TreeViewItem.cc.
Referenced by SideCar::GUI::Master::ServicesModel::getChangedParameters(), and getFullName().
void SideCar::GUI::Master::TreeViewItem::setExpanded (bool expanded) inline
Change the expansion attribute of the object.
Parameters
expanded new state
Definition at line 351 of file TreeViewItem.h.
References getInsertionPoint(), and updateCollectionStats().
Referenced by SideCar::GUI::Master::ServicesView::rowsInserted().
bool TreeViewItem::update (const IO::StatusBase & status)
Update the TreeViewItem held status.
If the new status is different than the held status value, calls performUpdate().
Parameters
status new status value to install
Returns
true if new status was changed
Definition at line 79 of file TreeViewItem.cc.
References afterUpdate(), and beforeUpdate().
Referenced by SideCar::GUI::Master::ConfigurationItem::executeRequest(), getStatus(), SideCar::GUI::Master::RunnerItem::RunnerItem(), and SideCar::GUI::Master::StreamItem::StreamItem().
virtual void SideCar::GUI::Master::TreeViewItem::updateCollectionStats (CollectionStats & stats) const pure virtual
Prototype for method to update a CollectionStats object with statistics provided by a TreeViewItem derivative.
Derived classes must define.
Parameters
stats object to update
Implemented in SideCar::GUI::Master::TaskItem, and SideCar::GUI::Master::CollectionItem.
Referenced by SideCar::GUI::Master::CollectionItem::afterUpdate(), and setExpanded().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/TreeViewItem.h
/Users/howes/src/sidecar/GUI/Master/TreeViewItem.cc