SideCar: SideCar::Algorithms::Despeckle Class Reference
SideCar::Algorithms::Despeckle Class Reference
Attempts to suppress noise using a modified median filter.
#include </Users/howes/src/sidecar/Algorithms/Despeckle/Despeckle.h>
Public Member Functions
Despeckle (Controller &controller, Logger::Log &log)
bool startup ()
Hook called once after the DLL is loaded and before processing begins.
bool reset ()
Hook called when the algorithm is transitioning from a stopped to a running state (one of Task::kAutoDiagnostic, Task::kCalibrate, or Task::kRun).
void setVarianceMultiplier (double value)
Public Member Functions inherited from SideCar::Algorithms::Algorithm
Algorithm (Controller &controller, Logger::Log &log)
Constructor.
virtual ~Algorithm ()
Destructor.
Controller & getController () const
Obtain the Controller object managing the algorithm.
Logger::Log & getLog () const
Obtain the log device to use for by the algorithm for log messages.
const std::string & getName () const
Obtain the name of the algorithm.
bool registerParameter (const Parameter::Ref &parameter)
Add a configuration parameter to the runtime system.
bool unregisterParameter (const Parameter::Ref &parameter)
Remove a configuration parameter from the runtime system.
template<typename A , typename M >
void registerProcessor (boost::function< bool(A *, typename M::Ref)> proc)
Install a method to process a particular message type.
template<typename A , typename M >
void registerProcessor (const std::string &channelName, boost::function< bool(A *, typename M::Ref)> proc)
Same as above method, but allows user to pick the channel by name.
template<typename A , typename M >
void registerProcessor (size_t channelIndex, boost::function< bool(A *, typename M::Ref)> proc)
Same as above method, but allows user to pick the channel by index.
template<typename A >
void registerProcessor (const std::string &channelName, const Messages::MetaTypeInfo &metaTypeInfo, boost::function< bool(A *, typename Messages::Header::Ref)> proc)
template<typename A >
void registerProcessor (size_t channelIndex, const Messages::MetaTypeInfo &metaTypeInfo, boost::function< bool(A *, typename Messages::Header::Ref)> proc)
size_t addProcessor (const std::string &channelName, const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
size_t addProcessor (const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
size_t addProcessor (size_t index, const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
void removeProcessor (size_t index)
Remove a processor from a given channel.
size_t getOutputChannelIndex (const std::string &name) const
Obtain an output channel index with a given name.
bool send (const Messages::Header::Ref &msg, size_t channelIndex=0)
Submit a message object to the controller for sending out on a given data channel.
bool sendAsIs (const Messages::Header::Ref &msg, size_t channelIndex=0)
Hand a message to the controller for sending out on a given data channel.
virtual size_t getNumInfoSlots () const
Obtain the number of data slots found in the ControllerStatus XML array.
virtual void setInfoSlots (IO::StatusBase &status)
Obtain custom status information from an algorithm.
size_t getActiveChannelIndex () const
Obtain the index of the input channel that last received a message for the algorithm to process.
Additional Inherited Members
Static Public Member Functions inherited from SideCar::Algorithms::Algorithm
static void * FormatInfoValue (const QString &value)
Obtain a C-safe value for the given QString string.
static void * FormatInfoValue (const char *value)
Obtain a C-safe value for the given character string.
Protected Member Functions inherited from SideCar::Algorithms::Algorithm
void setAlarm (int secs)
This method can be used by an Algorithm to schedule a periodic alarm to go off for itself.
virtual bool clearStats ()
Hook called when the algorithm is commaned to clear any statistics.
virtual bool beginAutoDiag ()
Hook called when the algorithm is entering the Task::kAutoDiagnostic state.
virtual bool beginCalibration ()
Hook called when the algorithm is entering the Task::kCalibrate state.
virtual bool beginRun ()
Hook called when the algorithm is entering the Task::kRun state.
virtual bool stop ()
Hook called when the algorithm is entering the Task::kStop state.
virtual bool shutdown ()
Hook called when the processing system shuts down.
virtual void recordingStarted ()
Hook called when a recording has started.
virtual void recordingStopped ()
Hook called when a recording has stopped.
virtual void beginParameterChanges ()
Hook called just before algorithm runtime parameters are changed.
virtual void endParameterChanges ()
Hook called just after algorithm runtime parameters have been changed.
virtual void processAlarm ()
This method will get called whenever an alarm expires for this Algorithm.
Detailed Description
Attempts to suppress noise using a modified median filter.
Delays the output by 2 PRIs.
Pseudocode:
In the 3x3 block about each cell,
Find the median of the samples not in this PRI
Find the variance of those samples about their median
If the center > median + k*variance, set center=median
Input Messages:
Messages::Video containing the video data
Output Messages:
Messages::Video containing the despeckled data
Run-time Parameters:
float "k" = 2
Specifies the allowed variance.
Definition at line 31 of file Despeckle.h.
Member Function Documentation
bool Despeckle::reset () virtual
Hook called when the algorithm is transitioning from a stopped to a running state (one of Task::kAutoDiagnostic, Task::kCalibrate, or Task::kRun).
Derived classes should override this method and perform whatever actions necessary to return the algorithm to a known state.
Returns
true if successful
Reimplemented from SideCar::Algorithms::Algorithm.
Definition at line 28 of file Despeckle.cc.
References SideCar::Algorithms::Algorithm::getLog(), SideCar::Algorithms::Algorithm::getName(), LOGDEBUG, LOGERROR, LOGINFO, LOGTIN, LOGTOUT, SideCar::Messages::Video::Make(), and SideCar::Algorithms::Algorithm::send().
bool Despeckle::startup () virtual
Hook called once after the DLL is loaded and before processing begins.
If a service fails to start up for any reason, it should return false. Any configurable parameters must be registered here. The processor's config file will be loaded after this routine returns.
Returns
true if successful.
Reimplemented from SideCar::Algorithms::Algorithm.
Definition at line 21 of file Despeckle.cc.
References SideCar::Algorithms::Algorithm::registerParameter(), and SideCar::Algorithms::Algorithm::startup().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/Despeckle/Despeckle.h
/Users/howes/src/sidecar/Algorithms/Despeckle/Despeckle.cc