SideCar: SideCar::Messages::Video Class Reference
SideCar::Messages::Video Class Reference
Collection of sample values for one PRI message from a radar.
#include </Users/howes/src/sidecar/Messages/Video.h>
Public Types
using Super = TPRIMessage< Traits::Int16 >
using Ref = TPRIMessageRef< Video >
Public Types inherited from SideCar::Messages::TPRIMessage< Traits::Int16 >
using TraitsType = Traits::Int16
using DatumType = typename Traits::Int16::Type
using value_type = typename Traits::Int16::Type
using Self = TPRIMessage< Traits::Int16 >
using Ref = boost::shared_ptr< Self >
using Super = PRIMessage
using Container = std::vector< DatumType >
using iterator = typename Container::iterator
using const_iterator = typename Container::const_iterator
Public Types inherited from SideCar::Messages::PRIMessage
using Super = Header
using Ref = boost::shared_ptr< PRIMessage >
Public Types inherited from SideCar::Messages::Header
using Ref = boost::shared_ptr< Header >
Public Member Functions
Video::Ref getVideoBasis () const
Obtain the Video message that was the basis for this instance.
Public Member Functions inherited from SideCar::Messages::TPRIMessage< Traits::Int16 >
Container & getData ()
Obtain a writeable reference to the underlying sample data container.
const Container & getData () const
double getRangeAt (double gate) const
double getRangeAt (const_iterator pos) const
Obtain the range of a particular sample.
void reserve (size_t size)
Allocate enough space in the sample container to hold a certain number of samples.
size_t size () const
Obtain the number of data elements in the message.
void resize (size_t size, DatumType init=DatumType())
Change the size of the container to hold a given number of values.
bool empty () const
Determine if the message has any data at all.
void push_back (const DatumType &value)
Append a sample value to the end of the message.
DatumType & operator[] (size_t index)
Index operator to access samples using array notation.
const DatumType & operator[] (size_t index) const
Read-only index operator to access samples using array notation.
const_iterator begin () const
Obtain read-only iterator to the first sample value in the message.
iterator begin ()
Obtain writable iterator to the first sample value in the message.
const_iterator end () const
Obtain read-only iterator to the last + 1 sample value in the message.
iterator end ()
Obtain writable iterator to the last + 1 sample value in the message.
size_t getSize () const
Obtain the C++ structure size for this object.
ACE_InputCDR & load (ACE_InputCDR &cdr)
Read in binary data from a CDR stream.
ACE_OutputCDR & write (ACE_OutputCDR &cdr) const
Write out our binary data to a CDR stream.
std::ostream & printData (std::ostream &os) const
Write out the message values to a C++ text output stream.
void loadXML (XmlStreamReader &xsr)
Obtain new instance data from an XML input stream.
std::ostream & printDataXML (std::ostream &os) const
Write out the message values to a C++ text output stream.
Public Member Functions inherited from SideCar::Messages::PRIMessage
RIUInfo & getRIUInfo ()
Obtain a reference to the VME header attributes.
uint32_t getSequenceCounter () const
uint32_t getShaftEncoding () const
Obtain the shaft encoding value for the message.
bool hasIRIGTime () const
double getIRIGTime () const
double getRangeMin () const
double getRangeMax () const
double getRangeFactor () const
double getRangeAt (double gate) const
double getAzimuthStart () const
Obtain an azimuth value in radians for the PRI message, based on the shaft encoder and the north mark values from the VME syatem.
double getAzimuthEnd () const
Obtain the value of getAzimuthStart() + RadarConfig::GetBeamWidth().
std::ostream & printHeader (std::ostream &os) const
Write out the message values to a C++ text output stream.
Public Member Functions inherited from SideCar::Messages::Header
Header (const MetaTypeInfo &metaTypeInfo)
Constructor for messages read in from an external device.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis, MetaTypeInfo::SequenceType sequenceNumber)
Constructor for new messages.
virtual ~Header ()
Destructor.
const MetaTypeInfo & getMetaTypeInfo () const
Obtain the type specification for the message.
const GUID & getGloballyUniqueID () const
Get the globally-unique ID of the message.
MetaTypeInfo::SequenceType getMessageSequenceNumber () const
Get the message sequence number for the message.
void setMessageSequenceNumber (MetaTypeInfo::SequenceType msn)
Set the sequence number for this message.
const Time::TimeStamp & getCreatedTimeStamp () const
Obtain when the message was created.
Time::TimeStamp setCreatedTimeStamp (const Time::TimeStamp &timeStamp)
Revise the creation message timestamp.
const Time::TimeStamp & getEmittedTimeStamp () const
Obtain when the message was written to an external device (file or network).
Time::TimeStamp setEmittedTimeStamp (const Time::TimeStamp &timeStamp)
Set the emitted time stamp with the given value.
HeaderPrinter headerPrinter () const
Convenience method that simply returns a new HeaderPrinter functor for this header object.
DataPrinter dataPrinter () const
Convenience method that simply returns a new DataPrinter functor for this header object.
XMLPrinter xmlPrinter () const
Convenience method that simply returns a new XMLPrinter functor for this header object.
virtual std::ostream & print (std::ostream &os) const
Write out the entire message to a C++ text output stream.
virtual std::ostream & printXML (std::ostream &os) const
Write out the message to a C++ text output stream in XML format.
bool hasBasis () const
Determine if the message has a basis message attached to it.
Ref getBasis () const
Obtain a reference to the message that this one was based on.
template<typename T >
T::Ref getBasis () const
Templated version of the above method.
Static Public Member Functions
static const MetaTypeInfo & GetMetaTypeInfo ()
Obtain the message type information for Video objects.
static Ref Make (const std::string &producer, const VMEDataMessage &vme, size_t count)
Factory method that generates a new, empty Video message.
static Ref Make (const std::string &producer, const VMEDataMessage &vme, const DatumType *first, const DatumType *end)
Factory method that generates a new Video message filled with values taken from a pointer.
static Ref Make (const std::string &producer, const VMEDataMessage &vme, const Container &data)
Factory method that generates a new Video message filled with values taken from a std::vector of values.
static Ref Make (const std::string &producer, const PRIMessage::Ref &basis)
Class factory used to create a Video object from another Video object.
static Ref Make (ACE_InputCDR &cdr)
Class factory used to create a new Video object from an byte stream.
Static Public Member Functions inherited from SideCar::Messages::PRIMessage
static Logger::Log & Log ()
Obtain the log device for PRIMessage objects.
Static Public Member Functions inherited from SideCar::Messages::Header
static Logger::Log & Log ()
Obtain log device to use for objects of this class.
static const MetaTypeInfo * GetMessageMetaTypeInfo (ACE_InputCDR &cdr)
Additional Inherited Members
Protected Member Functions inherited from SideCar::Messages::TPRIMessage< Traits::Int16 >
TPRIMessage (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const VMEDataMessage &vme, size_t size)
Constructor for new PRI messages created from a VME RIU message.
TPRIMessage (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const VMEDataMessage &vme, const Container &data)
TPRIMessage (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const PRIMessage::Ref &copy, size_t size)
Constructor for messages derived from another PRIMessage type.
TPRIMessage (const MetaTypeInfo &metaTypeInfo)
Constructor for messages loaded from a CDR stream.
TPRIMessage (const std::string &producer, const MetaTypeInfo &metaTypeInfo)
Constructor for messages loaded from a CDR stream.
Protected Member Functions inherited from SideCar::Messages::PRIMessage
PRIMessage (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const PRIMessage::Ref &copy)
Constructor used to create a new message that is derived from another one.
PRIMessage (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const VMEDataMessage &vme)
Constructor used to create a new message.
PRIMessage (const MetaTypeInfo &metaTypeInfo)
Constructor used to create a new message populated with data from a raw buffer.
PRIMessage (const std::string &producer, const MetaTypeInfo &metaTypeInfo)
Constructor used to create a new message populated with data from a raw buffer.
ACE_InputCDR & loadArray (ACE_InputCDR &cdr, uint32_t &count)
Read in binary data from a CDR stream.
ACE_OutputCDR & writeArray (ACE_OutputCDR &cdr, uint32_t size) const
Write out our binary data to a CDR stream.
Protected Attributes inherited from SideCar::Messages::TPRIMessage< Traits::Int16 >
Container data_
Collection of PRIDatum values.
Detailed Description
Collection of sample values for one PRI message from a radar.
The sample values are fixed-point, 16-bit values (normally treated as integers).
Definition at line 12 of file Video.h.
Member Function Documentation
const MetaTypeInfo & Video::GetMetaTypeInfo () static
Obtain the message type information for Video objects.
Returns
MetaTypeInfo reference
Definition at line 11 of file Video.cc.
Referenced by SideCar::GUI::AScope::ChannelConnectionModel::ChannelConnectionModel(), SideCar::GUI::HealthAndStatus::ChannelConnectionModel::Log(), SideCar::GUI::PRIEmitter::MainWindow::MainWindow(), Make(), SideCar::Algorithms::CPISimpleOp::shutdown(), SideCar::Algorithms::FanOut::startup(), SideCar::Algorithms::Recorder::startup(), SideCar::Algorithms::FanIn::startup(), SideCar::Algorithms::DownConverter::startup(), SideCar::Algorithms::Delay::startup(), SideCar::Algorithms::CPIAlgorithm::startup(), and SideCar::Algorithms::CPISimpleOp::startup().
Video::Ref SideCar::Messages::Video::getVideoBasis () const inline
Obtain the Video message that was the basis for this instance.
Returns
Video message or NULL if none exist
Definition at line 88 of file Video.h.
References SideCar::Messages::TPRIMessage< Traits::Int16 >::size().
Video::Ref Video::Make (const std::string & producer, const VMEDataMessage & vme, size_t count) static
Factory method that generates a new, empty Video message.
Reserves (allocates) space for count values, but the message is initially empty.
Parameters
producer the name of the task that created the message
vmeHeader the VME parameters that define the message
count the number of values to reserve
Returns
new Video message reference
Definition at line 17 of file Video.cc.
Referenced by SideCar::Messages::RawVideo::convert(), SideCar::Algorithms::GeoFilter::GeoFilter(), Make(), SideCar::GUI::PRIEmitter::MainWindow::openFile(), SideCar::Algorithms::DownConverter::process(), SideCar::Algorithms::CPIIntegrate::processCPI(), SideCar::Algorithms::Despeckle::reset(), SideCar::Algorithms::Filter::reset(), SideCar::Algorithms::MatchedFilter::reset(), SideCar::GUI::SignalGenerator::MainWindow::saveToSettings(), SideCar::Algorithms::Clamp::setMaxValue(), SideCar::Algorithms::RGBConverter::shutdown(), SideCar::Algorithms::Decimator::shutdown(), SideCar::Algorithms::CPIMarker::shutdown(), SideCar::Algorithms::Sum::shutdown(), SideCar::Algorithms::SumNDiff::shutdown(), SideCar::Algorithms::Delay::shutdown(), SideCar::Algorithms::LowPassFilter::shutdown(), SideCar::Algorithms::CPISimpleOp::shutdown(), SideCar::Algorithms::MatchedFilter::shutdown(), SideCar::Algorithms::SimpleOp::SimpleOp(), SideCar::Algorithms::NOOP::startup(), SideCar::Algorithms::Offset::startup(), SideCar::Algorithms::Scale::startup(), SideCar::Algorithms::SimpleNOOP::startup(), SideCar::Algorithms::Volts2Power::startup(), SideCar::Algorithms::SandBox::startup(), SideCar::Algorithms::Trimmer::startup(), SideCar::Algorithms::RangeDopplerMap::startup(), SideCar::Algorithms::WindowedMinMax::startup(), SideCar::Algorithms::SlidingOp::startup(), SideCar::Algorithms::CIntegrate::startup(), SideCar::Algorithms::IQFilter::startup(), and SideCar::Algorithms::Summer::Summer().
Video::Ref Video::Make (const std::string & producer, const VMEDataMessage & vme, const DatumType * first, const DatumType * end) static
Factory method that generates a new Video message filled with values taken from a pointer.
Parameters
producer the name of the task that created the message
vmeHeader the VME parameters that define the message
first pointer to the first value to use
end pointer to the last+1 value to use
\return new Video message reference
Definition at line 24 of file Video.cc.
Video::Ref Video::Make (const std::string & producer, const VMEDataMessage & vme, const Container & data) static
Factory method that generates a new Video message filled with values taken from a std::vector of values.
Parameters
producer the name of the task that created the message
vmeHeader the VME parameters that define the message
data container of values to copy
Returns
Definition at line 37 of file Video.cc.
Video::Ref Video::Make (const std::string & producer, const PRIMessage::Ref & basis) static
Class factory used to create a Video object from another Video object.
Parameters
producer name of the entity that is creating the new object
\param basis message that forms the basis for the new one
\return reference to new Video object
Definition at line 44 of file Video.cc.
Video::Ref Video::Make (ACE_InputCDR & cdr) static
Class factory used to create a new Video object from an byte stream.
Parameters
cdr input stream to load from
Returns
reference to new Video object
Definition at line 51 of file Video.cc.
References GetMetaTypeInfo(), Make(), and SideCar::Messages::TPRIMessage< Traits::Int16 >::size().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Messages/Video.h
/Users/howes/src/sidecar/Messages/Video.cc