SideCar: SideCar::Algorithms::ClutterMap Class Reference
SideCar::Algorithms::ClutterMap Class Reference
Clutter map filter.
#include </Users/howes/src/sidecar/Algorithms/ClutterMap/ClutterMap.h>
Public Types
enum InfoSlot { kLearning = ControllerStatus::kNumSlots, kRemaining, kEnabled, kNumSlots }
Public Member Functions
ClutterMap (Controller &controller, Logger::Log &log)
Constructor.
bool startup ()
Implementation of the Algorithm::startup interface.
bool reset ()
Hook called when the algorithm is transitioning from a stopped to a running state (one of Task::kAutoDiagnostic, Task::kCalibrate, or Task::kRun).
void setAlpha (double value)
Assign a new value to the low-pass filter alpha parameter.
void setLearningScanCount (int value)
Set the number of radar scans to use to build the clutter map.
void setRadialPartitionCount (int value)
Set the number of radials in the map buffer.
void setLoadFilePath (const std::string &path)
Load a previously-saved clutter map from a system file.
void setSaveFilePath (const std::string &path)
Save a frozen clutter map to a system file.
size_t getNumInfoSlots () const
Obtain the number of data slots found in the ControllerStatus XML array.
void setInfoSlots (IO::StatusBase &status)
Implementation of Algorithm::getInfoData() interface.
bool loadMap (const std::string &path)
Load a built clutter map from a system file.
bool saveMap (const std::string &path)
Save a built clutter map to a system file.
Public Member Functions inherited from SideCar::Algorithms::Algorithm
Algorithm (Controller &controller, Logger::Log &log)
Constructor.
virtual ~Algorithm ()
Destructor.
Controller & getController () const
Obtain the Controller object managing the algorithm.
Logger::Log & getLog () const
Obtain the log device to use for by the algorithm for log messages.
const std::string & getName () const
Obtain the name of the algorithm.
bool registerParameter (const Parameter::Ref &parameter)
Add a configuration parameter to the runtime system.
bool unregisterParameter (const Parameter::Ref &parameter)
Remove a configuration parameter from the runtime system.
template<typename A , typename M >
void registerProcessor (boost::function< bool(A *, typename M::Ref)> proc)
Install a method to process a particular message type.
template<typename A , typename M >
void registerProcessor (const std::string &channelName, boost::function< bool(A *, typename M::Ref)> proc)
Same as above method, but allows user to pick the channel by name.
template<typename A , typename M >
void registerProcessor (size_t channelIndex, boost::function< bool(A *, typename M::Ref)> proc)
Same as above method, but allows user to pick the channel by index.
template<typename A >
void registerProcessor (const std::string &channelName, const Messages::MetaTypeInfo &metaTypeInfo, boost::function< bool(A *, typename Messages::Header::Ref)> proc)
template<typename A >
void registerProcessor (size_t channelIndex, const Messages::MetaTypeInfo &metaTypeInfo, boost::function< bool(A *, typename Messages::Header::Ref)> proc)
size_t addProcessor (const std::string &channelName, const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
size_t addProcessor (const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
size_t addProcessor (size_t index, const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
void removeProcessor (size_t index)
Remove a processor from a given channel.
size_t getOutputChannelIndex (const std::string &name) const
Obtain an output channel index with a given name.
bool send (const Messages::Header::Ref &msg, size_t channelIndex=0)
Submit a message object to the controller for sending out on a given data channel.
bool sendAsIs (const Messages::Header::Ref &msg, size_t channelIndex=0)
Hand a message to the controller for sending out on a given data channel.
size_t getActiveChannelIndex () const
Obtain the index of the input channel that last received a message for the algorithm to process.
Additional Inherited Members
Static Public Member Functions inherited from SideCar::Algorithms::Algorithm
static void * FormatInfoValue (const QString &value)
Obtain a C-safe value for the given QString string.
static void * FormatInfoValue (const char *value)
Obtain a C-safe value for the given character string.
Protected Member Functions inherited from SideCar::Algorithms::Algorithm
void setAlarm (int secs)
This method can be used by an Algorithm to schedule a periodic alarm to go off for itself.
virtual bool clearStats ()
Hook called when the algorithm is commaned to clear any statistics.
virtual bool beginAutoDiag ()
Hook called when the algorithm is entering the Task::kAutoDiagnostic state.
virtual bool beginCalibration ()
Hook called when the algorithm is entering the Task::kCalibrate state.
virtual bool beginRun ()
Hook called when the algorithm is entering the Task::kRun state.
virtual bool stop ()
Hook called when the algorithm is entering the Task::kStop state.
virtual bool shutdown ()
Hook called when the processing system shuts down.
virtual void recordingStarted ()
Hook called when a recording has started.
virtual void recordingStopped ()
Hook called when a recording has stopped.
virtual void beginParameterChanges ()
Hook called just before algorithm runtime parameters are changed.
virtual void endParameterChanges ()
Hook called just after algorithm runtime parameters have been changed.
virtual void processAlarm ()
This method will get called whenever an alarm expires for this Algorithm.
Detailed Description
Clutter map filter.
Creates the clutter map from the first learningScanCount scans worth of PRI samples, at which point the map is frozen and subsequent PRIs update it through a low-pass filter (single pole IIR) controlled by the alpha parameter.
The map consists of a collection of radial buffers, of size radialPartitionCount. The PRI's shaft encoding value dictates which radial buffer to use. All map manipulations happen inside the MapBuffer class.
alpha non-negative real value that determines how much of an effect new PRIs have on a frozen clutter map. The MapBuffer class uese a single-pole lowpass filter parameter to update a radial buffer from a frozen clutter map:
map[i] = (1 - alpha) * map[i] + alpha * PRI
where i is the partition index calculated from the PRI shaft encoding value.
learningScanCount specifies how many complete radar scans / rotations to use when building the clutter map. After initial startup or reset, the algorithm will ignore PRIs until it detects a zero azimuth (north) crossing, at which point it will apply incoming PRIs to the map buffer.
radialPartitionCount specifies the numter of radials in the map buffer. Larger values improve azimuthal resolution in the map at the expense of memory, and possibly learning time if the resolution is such that some radials fail to receive an update during one scan due to rotation speed and accuracy of the shaft encoder.
loadFilePath path of file containg the values of a previously-saved clutter map. A loaded map is automatically frozen.
saveFilePath path of a file to hold the values of clutter map. If set, it does not have any effect until the clutter map becomes frozen.
resetBuffer notification to clear the clutter map and enter the map building phase.
ClutterMap overrides the getInfoData() to return the following attributes:
learning boolean value that is false when the map is frozen, true otherwise.
remaining contains the number of scans remainging before the map transitions from learning to frozen state.
Definition at line 61 of file ClutterMap.h.
Constructor & Destructor Documentation
ClutterMap::ClutterMap (Controller & controller, Logger::Log & log)
Constructor.
Parameters
controller object that controls us
log device used for log messages
Definition at line 20 of file ClutterMap.cc.
Referenced by saveMap().
Member Function Documentation
size_t SideCar::Algorithms::ClutterMap::getNumInfoSlots () const inline virtual
Obtain the number of data slots found in the ControllerStatus XML array.
Any custom Algorithm slots will appear after the last defined ControllerStatus slot. NOTE: implementations must be thread-safe, since this routine will execute in the alorithm's StatusEmitter thread.
Returns
ControllerStats::kNumSlots
Reimplemented from SideCar::Algorithms::Algorithm.
Definition at line 122 of file ClutterMap.h.
References loadMap(), saveMap(), and setInfoSlots().
bool ClutterMap::loadMap (const std::string & path)
Load a built clutter map from a system file.
Parameters
path locate of the file to read from
Definition at line 210 of file ClutterMap.cc.
References SideCar::Algorithms::Algorithm::getLog(), SideCar::Algorithms::Algorithm::getName(), and LOGERROR.
Referenced by getNumInfoSlots(), and reset().
bool ClutterMap::reset () virtual
Hook called when the algorithm is transitioning from a stopped to a running state (one of Task::kAutoDiagnostic, Task::kCalibrate, or Task::kRun).
Derived classes should override this method and perform whatever actions necessary to return the algorithm to a known state.
Returns
true if successful
Reimplemented from SideCar::Algorithms::Algorithm.
Definition at line 66 of file ClutterMap.cc.
References SideCar::Algorithms::Algorithm::getLog(), SideCar::Algorithms::Algorithm::getName(), SideCar::Parameter::TValue< ParamDef >::getValue(), loadMap(), LOGDEBUG, LOGERROR, LOGINFO, LOGWARNING, saveMap(), and SideCar::Algorithms::Algorithm::send().
bool ClutterMap::saveMap (const std::string & path)
Save a built clutter map to a system file.
Parameters
path location of the file to write to
Definition at line 230 of file ClutterMap.cc.
References ClutterMap(), SideCar::Algorithms::Algorithm::FormatInfoValue(), SideCar::Algorithms::Algorithm::getLog(), and LOGERROR.
Referenced by getNumInfoSlots(), and reset().
void SideCar::Algorithms::ClutterMap::setAlpha (double value) inline
Assign a new value to the low-pass filter alpha parameter.
Must be non-negative.
Parameters
value new value to use
Definition at line 92 of file ClutterMap.h.
void ClutterMap::setInfoSlots (IO::StatusBase & status) virtual
Implementation of Algorithm::getInfoData() interface.
Parameters
infoData XML structure to store into
Returns
the string "ClutterMap"
Reimplemented from SideCar::Algorithms::Algorithm.
Definition at line 195 of file ClutterMap.cc.
References SideCar::IO::StatusBase::setSlot().
Referenced by getNumInfoSlots().
void SideCar::Algorithms::ClutterMap::setLearningScanCount (int value) inline
Set the number of radar scans to use to build the clutter map.
Parameters
value new value to use
Definition at line 98 of file ClutterMap.h.
void SideCar::Algorithms::ClutterMap::setLoadFilePath (const std::string & path) inline
Load a previously-saved clutter map from a system file.
Parameters
path location of the file
Definition at line 112 of file ClutterMap.h.
void SideCar::Algorithms::ClutterMap::setRadialPartitionCount (int value) inline
Set the number of radials in the map buffer.
Parameters
value new value to use
Definition at line 105 of file ClutterMap.h.
void SideCar::Algorithms::ClutterMap::setSaveFilePath (const std::string & path) inline
Save a frozen clutter map to a system file.
Parameters
path location of the file
Definition at line 119 of file ClutterMap.h.
bool ClutterMap::startup () virtual
Implementation of the Algorithm::startup interface.
Register runtime parameters with the controller.
Returns
true if successful, false otherwise
Reimplemented from SideCar::Algorithms::Algorithm.
Definition at line 46 of file ClutterMap.cc.
References SideCar::Algorithms::Algorithm::getLog(), LOGERROR, SideCar::Algorithms::Algorithm::registerParameter(), and SideCar::Algorithms::Algorithm::startup().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/ClutterMap/ClutterMap.h
/Users/howes/src/sidecar/Algorithms/ClutterMap/ClutterMap.cc