SideCar: SideCar::GUI::ESScope::History Class Reference
SideCar::GUI::ESScope::History Class Reference
Data Structures
struct AlphaBetaInfo
Public Types
using AlphaRangeData = std::vector< AlphaRangeColumn >
using AlphaBetaData = std::vector< AlphaBetaInfo >
Public Slots
void processVideo (const MessageList &data)
void processExtractions (const MessageList &data)
void processRangeTruths (const MessageList &data)
void processBugPlots (const MessageList &data)
void pruneTargets ()
void clearAll ()
void clearVideo ()
void clearExtractions ()
void clearRangeTruths ()
void clearBugPlots ()
Signals
void alphasChanged (const AlphaIndices &indices)
void currentMessage (const Messages::PRIMessage::Ref &msg)
Public Member Functions
History (QObject *parent, RadarSettings *radarSettings, TargetPlotImaging *extractionsImaging, RangeTruthsImaging *rangeTruthsImaging, TargetPlotImaging *bugPlotsImaging, BoolSetting *allynHack)
Constructor.
int getAlphaBetaValue (size_t index) const
const AlphaRangeColumn & getAlphaRangeData (size_t alphaIndex) const
const TargetPlotList & getExtractions () const
Obtain a read-only reference to the Extraction message collection.
const TargetPlotListList & getRangeTruths () const
Obtain a read-only reference to the TSPI message collection.
const TargetPlotList & getBugPlots () const
Obtain a read-only reference to the user bug plot entries.
void addBugPlot (const Messages::BugPlot::Ref &msg)
Static Public Member Functions
static Logger::Log & Log ()
Detailed Description
Definition at line 30 of file History.h.
Member Function Documentation
const AlphaRangeColumn& SideCar::GUI::ESScope::History::getAlphaRangeData (size_t alphaIndex) const inline
Parameters
alphaIndex
Returns
Definition at line 65 of file History.h.
const TargetPlotList& SideCar::GUI::ESScope::History::getBugPlots () const inline
Obtain a read-only reference to the user bug plot entries.
Returns
TargetPlotList reference
Definition at line 84 of file History.h.
Referenced by SideCar::GUI::ESScope::XYWidget::XYWidget().
const TargetPlotList& SideCar::GUI::ESScope::History::getExtractions () const inline
Obtain a read-only reference to the Extraction message collection.
Returns
TargetPlotList reference
Definition at line 72 of file History.h.
Referenced by SideCar::GUI::ESScope::XYWidget::XYWidget().
const TargetPlotListList& SideCar::GUI::ESScope::History::getRangeTruths () const inline
Obtain a read-only reference to the TSPI message collection.
Returns
TargetPlotList reference
Definition at line 78 of file History.h.
Referenced by SideCar::GUI::ESScope::XYWidget::XYWidget().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/ESScope/History.h
/Users/howes/src/sidecar/GUI/ESScope/History.cc