SideCar: SideCar::GUI::Playback::FileModel Class Reference
SideCar::GUI::Playback::FileModel Class Reference
A model of Emitter objects.
#include </Users/howes/src/sidecar/GUI/Playback/FileModel.h>
Data Structures
class LoaderProgress
Derivation of QProgressDialog used by FileModel to indicate that a long load is in progress.
Public Types
enum Columns {
kEmitting = 0, kName, kStartTime, kEndTime,
kDuration, kSubscriberCount, kNumColumns
}
Indices of the data columns provided by the model.
Signals
void loadComplete ()
Public Member Functions
FileModel (MainWindow *parent)
Constructor.
~FileModel ()
Destructor.
Emitter * getEmitter (int row) const
void beginLoad (const QString &path)
Create new Emitter objects for all of the recording files found in a the path directory.
int columnCount (const QModelIndex &parent=QModelIndex()) const
Implementation of QAbstractItemModel method.
int rowCount (const QModelIndex &parent=QModelIndex()) const
Implementation of QAbstractItemModel method.
QVariant data (const QModelIndex &pos, int role=Qt::DisplayRole) const
Implementation of QAbstractItemModel method.
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Implementation of QAbstractItemModel method.
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Implementation of QAbstractItemModel method.
Qt::ItemFlags flags (const QModelIndex &index) const
Implementation of QAbstractItemModel method.
const Time::TimeStamp & getStartTime () const
Obtain the earliest start time for all Emitter objects.
const Time::TimeStamp & getEndTime () const
Obtain the latest end time for all Emitter objects.
Static Public Member Functions
static Logger::Log & Log ()
Log device for instances of this class.
Detailed Description
A model of Emitter objects.
Provides display data for the MainWindow files_ attribute, a QTableView. Each entry in the model is an Emitter object. The model provides five columns of information to its QTableView clients:
kEmitting a checkbox that indicates whether the channel will emit data during playback
kName the name of the recording file used for playback (without the extension '.pri')
kStartTime the time of the first record in the recording file
kEndTime the time of the last record in the recording file
kDuration the about of time between kStart and kEnd
The kStartTime and kEndTime fields contain times formatted as HH:MM:SS, with midnight of the day of the recording begin 00:00:00.
The model manages playback start and stop for all of the held Emitter objects, and it maintains a playback clock which sends out wall time updates via the currentTime() signal.
Definition at line 39 of file FileModel.h.
Constructor & Destructor Documentation
FileModel::FileModel (MainWindow * parent)
Constructor.
Parameters
parent owner of the object
Definition at line 65 of file FileModel.cc.
Member Function Documentation
void FileModel::beginLoad (const QString & path)
Create new Emitter objects for all of the recording files found in a the path directory.
Parameters
path location of the recording directory to process
Returns
true if at least one Emitter object is valid
Definition at line 81 of file FileModel.cc.
References SideCar::GUI::Playback::Emitter::getEndTime(), SideCar::GUI::Playback::Emitter::getName(), SideCar::GUI::Playback::Emitter::getStartTime(), Log(), LOGDEBUG, LOGERROR, LOGINFO, SideCar::Time::TimeStamp::Max(), and SideCar::Time::TimeStamp::Min().
Referenced by SideCar::GUI::Playback::MainWindow::MainWindow().
int FileModel::columnCount (const QModelIndex & parent = QModelIndex()) const
Implementation of QAbstractItemModel method.
Obtain the number of columns in the model data.
Parameters
parent model index of containing parent model (not used)
Returns
number of columns (kNumColumns)
Definition at line 272 of file FileModel.cc.
Referenced by SideCar::GUI::Playback::MainWindow::getWallClockRate().
QVariant FileModel::data (const QModelIndex & pos, int role = Qt::DisplayRole) const
Implementation of QAbstractItemModel method.
Obtain a piece of data from the model for a particular location (row,column) and purpose.
Parameters
index location of the datum to get
role how the data will be used
Returns
value to use for the given purpose
Definition at line 284 of file FileModel.cc.
References flags(), SideCar::GUI::Playback::Emitter::getEmitting(), SideCar::GUI::Playback::Emitter::getName(), and rowCount().
Qt::ItemFlags FileModel::flags (const QModelIndex & index) const
Implementation of QAbstractItemModel method.
Obtain the display flags for a particular location. All elements have Qt::ItemIsEnabled set, and the kVisible column has Qt::ItemIsUserCheckable set.
Parameters
index location of the flags to get
Returns
display flags
Definition at line 375 of file FileModel.cc.
Referenced by data().
const Time::TimeStamp& SideCar::GUI::Playback::FileModel::getEndTime () const inline
Obtain the latest end time for all Emitter objects.
Returns
Time::TimeStamp value
Definition at line 158 of file FileModel.h.
Referenced by SideCar::GUI::Playback::MainWindow::MainWindow().
const Time::TimeStamp& SideCar::GUI::Playback::FileModel::getStartTime () const inline
Obtain the earliest start time for all Emitter objects.
Returns
earliest Time::TimeStamp value
Definition at line 152 of file FileModel.h.
Referenced by SideCar::GUI::Playback::MainWindow::MainWindow().
QVariant FileModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
Implementation of QAbstractItemModel method.
Obtain a piece of data from the model to display in the horizontal or vertical header. The horizontal header contains column names, while the vertical header contains row numbers (one-based).
Parameters
section which row or column to fetch
orientation which header, horizontal or vertical, to fetch for
role how the data will be used
Returns
value to use for the given purpose
Definition at line 350 of file FileModel.cc.
Logger::Log & FileModel::Log () static
Log device for instances of this class.
Returns
log device
Definition at line 59 of file FileModel.cc.
References Logger::Log::Find().
Referenced by beginLoad().
int FileModel::rowCount (const QModelIndex & parent = QModelIndex()) const
Implementation of QAbstractItemModel method.
Obtain the number of rows in the model data.
Parameters
parent model index of containing parent model (not used)
Returns
number of rows
Definition at line 278 of file FileModel.cc.
Referenced by data(), and setData().
bool FileModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole)
Implementation of QAbstractItemModel method.
Change the data in the model at a particular location and display purpose.
Parameters
index location of the datum to set
value new value to use
role how the data will be used
Returns
true if the value was successfully set, false otherwise.
Definition at line 389 of file FileModel.cc.
References SideCar::GUI::Playback::Emitter::getName(), rowCount(), and SideCar::GUI::Playback::Emitter::setEmitting().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Playback/FileModel.h
/Users/howes/src/sidecar/GUI/Playback/FileModel.cc