SideCar: SideCar::GUI::Master::StringParam Class Reference
SideCar::GUI::Master::StringParam Class Reference
String parameter editor.
#include </Users/howes/src/sidecar/GUI/Master/ParamEditor.h>
Public Member Functions
StringParam (QVBoxLayout *parentLayout, const XmlRpc::XmlRpcValue &entry)
Constructor.
void setValue (const XmlRpc::XmlRpcValue &value)
bool hasChanged () const
Determine if the parameter value has changed.
bool notOriginal () const
void acceptChange ()
Commit the value change.
void undoChange ()
Undo any changes in the editor by updating it with the current parameter value.
void revertToOriginal ()
Revert the current value to the original configuration value.
Public Member Functions inherited from SideCar::GUI::Master::ParamBase
ParamBase (QVBoxLayout *parentLayout, const XmlRpc::XmlRpcValue &entry)
Constructor.
const std::string & getName () const
Obtain the name of the parameter.
const std::string & getLabel () const
void addIfChanged (XmlRpc::XmlRpcValue &values, QStringList &changes)
If the editor has a changed value, update the held parameter value, and add XML data that will update the parameter with a new value.
ParamBase & add (QWidget *widget)
Add an editor widget.
void done ()
Additional Inherited Members
Public Slots inherited from SideCar::GUI::Master::ParamBase
void setVisible (bool state)
Signals inherited from SideCar::GUI::Master::ParamBase
void valueChanged ()
Notification sent out by the editor when it holds a value that is different from the parameter's current value.
Static Public Member Functions inherited from SideCar::GUI::Master::ParamBase
static QString GetString (const std::string &value)
static QString GetQuotedString (const QString &value)
Protected Member Functions inherited from SideCar::GUI::Master::ParamBase
QLabel * makeLabel (QString text="")
QWidget * getParent ()
Detailed Description
String parameter editor.
Uses a QLineEdit to perform the value editing.
Definition at line 233 of file ParamEditor.h.
Constructor & Destructor Documentation
StringParam::StringParam (QVBoxLayout * parentLayout, const XmlRpc::XmlRpcValue & entry)
Constructor.
Creates a layout into which the label and QLineEdit reside.
Parameters
parentLayout the layout to add to
entry definition of the parameter being edited.
Definition at line 217 of file ParamEditor.cc.
References SideCar::GUI::Master::ParamBase::add(), undoChange(), and SideCar::GUI::Master::ParamBase::valueChanged().
Member Function Documentation
bool StringParam::hasChanged () const virtual
Determine if the parameter value has changed.
Returns
true if so
Implements SideCar::GUI::Master::ParamBase.
Definition at line 237 of file ParamEditor.cc.
void StringParam::undoChange () virtual
Undo any changes in the editor by updating it with the current parameter value.
Derived classes must define.
Implements SideCar::GUI::Master::ParamBase.
Definition at line 249 of file ParamEditor.cc.
Referenced by StringParam().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/ParamEditor.h
/Users/howes/src/sidecar/GUI/Master/ParamEditor.cc