SideCar: SideCar::GUI::Master::InfoFormatter Class Reference
SideCar::GUI::Master::InfoFormatter Class Reference
The InfoFormatter class represents a formatter for the 'info' status field of Algorithm/Controller objects.
#include </Users/howes/src/sidecar/GUI/Master/InfoFormatter.h>
Public Member Functions
const QString & getName () const
Obtain the name for the InfoFormatter object.
QVariant format (const IO::StatusBase &status, int role)
Obtain formatting information for status information in a IO::StatusBase object.
void release ()
Static Public Member Functions
static Logger::Log & Log ()
Obtain log device for InfoFormatter objects.
static InfoFormatter * Find (const QString &name)
Locate or create an InfoFormatter object with the given name.
Detailed Description
The InfoFormatter class represents a formatter for the 'info' status field of Algorithm/Controller objects.
One cannot create InfoFormatter objects directly, rather one must call the Find() class method in order to obtain an InfoFormatter object for a given name. If the object does not exist, the Find() method will create a new one and register it with the class formatters_ attribute, Otherwise, Find() returns the already-registered object.
Definition at line 21 of file InfoFormatter.h.
Member Function Documentation
InfoFormatter * InfoFormatter::Find (const QString & name) static
Locate or create an InfoFormatter object with the given name.
Uses the QLibrary class to load a DLL with the name 'lib' + name. It then tries to resolve the symbol 'FormatInfo' in the loaded DLL.
Parameters
name the name of the formatter to locate
Returns
reference to InfoFormatter object
Definition at line 20 of file InfoFormatter.cc.
References Log(), and LOGINFO.
Referenced by SideCar::GUI::Master::ControllerItem::afterUpdate().
QVariant InfoFormatter::format (const IO::StatusBase & status, int role)
Obtain formatting information for status information in a IO::StatusBase object.
Parameters
status
role
Returns
Definition at line 54 of file InfoFormatter.cc.
Referenced by SideCar::GUI::Master::ControllerItem::getInfoDataValue().
const QString& SideCar::GUI::Master::InfoFormatter::getName () const inline
Obtain the name for the InfoFormatter object.
Returns
formatter name
Definition at line 44 of file InfoFormatter.h.
Referenced by SideCar::GUI::Master::ControllerItem::afterUpdate().
Logger::Log & InfoFormatter::Log () static
Obtain log device for InfoFormatter objects.
Returns
log device reference
Definition at line 13 of file InfoFormatter.cc.
References Logger::Log::Find().
Referenced by Find().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/InfoFormatter.h
/Users/howes/src/sidecar/GUI/Master/InfoFormatter.cc