SideCar: SideCar::GUI::HealthAndStatus::ChannelConnectionModel Class Reference
SideCar::GUI::HealthAndStatus::ChannelConnectionModel Class Reference
Signals
void availableServicesChanged (const QStringList &names)
Public Member Functions
ChannelConnectionModel (QObject *parent=0)
ChannelConnection * getConnection (int row) const
QModelIndex add (ChannelConnection *channelConnection, int beforeRow)
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
void moveUp (int row)
void moveDown (int row)
int getRowFor (ChannelConnection *channelConnection) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
QModelIndex index (int row, int column=0, const QModelIndex &parent=QModelIndex()) const
bool hasChannel (const QString &name) const
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for instances of this class.
static ChannelConnection * GetObject (const QModelIndex &index)
Detailed Description
Definition at line 17 of file ChannelConnectionModel.h.
Member Function Documentation
Logger::Log & ChannelConnectionModel::Log () static
Obtain the log device for instances of this class.
Returns
log device
Definition at line 14 of file ChannelConnectionModel.cc.
References Logger::Log::Find(), SideCar::Messages::Video::GetMetaTypeInfo(), SideCar::GUI::ServiceBrowser::getServiceEntry(), LOGDEBUG, LOGINFO, SideCar::IO::ZeroconfTypes::TZCType< id >::MakeZeroconfType(), and SideCar::GUI::ServiceBrowser::start().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/HealthAndStatus/ChannelConnectionModel.h
/Users/howes/src/sidecar/GUI/HealthAndStatus/ChannelConnectionModel.cc