SideCar: SideCar::Messages::RadarConfig Class Reference
SideCar::Messages::RadarConfig Class Reference
Run-time configuration parameters that describe the radar.
#include </Users/howes/src/sidecar/Messages/RadarConfig.h>
Static Public Member Functions
static Logger::Log & Log ()
Log device for RadarConfig messages.
static bool SetConfigurationFilePath (std::string path)
Use a new file path for radar configuration values.
static bool Load (const QDomElement &config)
Load in a new radar configuration from an XML DOM node.
static void Load (const std::string &name, uint32_t gateCountMax, uint32_t shaftEncodingMax, double rotationRate, double rangeMin, double rangeMax, double beamWidth)
Load in new radar configuration from raw values.
static const std::string & GetName ()
Obtain the current radar configuration name.
static uint32_t GetGateCountMax ()
Obtain the current max gate count value.
static uint32_t GetShaftEncodingMax ()
Obtain the current max shaft encoding value.
static double GetRotationRate ()
Obtain the current rotation rate value.
static double GetRangeMin_deprecated ()
Obtain the current min range value, the range value associated with the first sample.
static double GetRangeMax ()
Obtain the current max range value, the range value associated with the gateCountMax_ - 1 sample.
static double GetRangeFactor_deprecated ()
Obtain the multiplier used to convert from gate sample index values to a range value in kilometers.
static double GetBeamWidth ()
Obtain the current beam width value.
static uint32_t GetRadialCount ()
Obtain the number radials in one revolution of the radar.
static double GetRangeAt_deprecated (uint32_t gateIndex)
Obtain the range value for a gate sample index.
static double GetAzimuth (uint32_t shaftEncoding)
Obtain an azimuth reading in radians from a shaft encoding value.
static double GetRotationDuration ()
Obtain the duration in seconds of one rotation of the radar.
static double GetSiteLatitude ()
Obtain the latitude (north/south) of the site location.
static double GetSiteLongitude ()
Obtain the longitude (east/west) of the site location.
static double GetSiteHeight ()
Obtain the height of the site location.
Detailed Description
Run-time configuration parameters that describe the radar.
Since there is only one radar configuration in use at a time, this class supports no instances; all methods and attributes belong to the class.
The RadarConfig 'instance' relies on data found in an XML configuration file. The internal Initializer class looks in the following locations (where SIDECAR_CONFIG and SIDECAR are process environment variables):
${SIDECAR_CONFIG}
${SIDECAR}/data/configuration.xml
/opt/sidecar/data/configuration.xml
The above locations are ordered by priority – a configuration file found via ${SIDECAR_CONFIG} will override one the could be found via ${SIDECAR}/data/configuration.xml.
NOTE: do not inline the accessor methods below. We need to execute code in RadarConfig.cc in order to make sure that the static attributes initialize properly; C++ does not guarantee initialization of class (static) attributes until code containing the attribubtes first executes.
NOTE: the rationale for having RadarConfig done this way versus a singleton is lost to history. Perhaps backwards capability with some other system?
Definition at line 37 of file RadarConfig.h.
Member Function Documentation
static double SideCar::Messages::RadarConfig::GetAzimuth (uint32_t shaftEncoding) inline static
Obtain an azimuth reading in radians from a shaft encoding value.
Parameters
shaftEncoding value to convert
Returns
azimuth in radians
Definition at line 151 of file RadarConfig.h.
Referenced by SideCar::Messages::PRIMessage::getAzimuthEnd(), and SideCar::Messages::PRIMessage::getAzimuthStart().
double RadarConfig::GetBeamWidth () static
Obtain the current beam width value.
Returns
beam width
Definition at line 108 of file RadarConfig.cc.
Referenced by PRIInfoInputTask::deliverDataMessage(), SideCar::Messages::PRIMessage::getAzimuthEnd(), and SideCar::GUI::PRIEmitter::MainWindow::openFile().
uint32_t RadarConfig::GetGateCountMax () static
Obtain the current max gate count value.
Returns
max gate count
Definition at line 90 of file RadarConfig.cc.
const std::string & RadarConfig::GetName () static
Obtain the current radar configuration name.
Returns
config name
Definition at line 87 of file RadarConfig.cc.
static uint32_t SideCar::Messages::RadarConfig::GetRadialCount () inline static
Obtain the number radials in one revolution of the radar.
This is an upper bound.
Returns
Definition at line 134 of file RadarConfig.h.
static double SideCar::Messages::RadarConfig::GetRangeAt_deprecated (uint32_t gateIndex) inline static
Obtain the range value for a gate sample index.
Parameters
gateIndex value to convert
Returns
range in kilometers
Definition at line 142 of file RadarConfig.h.
double RadarConfig::GetRangeFactor_deprecated () static
Obtain the multiplier used to convert from gate sample index values to a range value in kilometers.
Returns
range factor
Definition at line 105 of file RadarConfig.cc.
Referenced by SideCar::Messages::PRIMessage::RIUInfo::load().
double RadarConfig::GetRangeMax () static
Obtain the current max range value, the range value associated with the gateCountMax_ - 1 sample.
Returns
max range value
Definition at line 102 of file RadarConfig.cc.
Referenced by SideCar::GUI::PRIEmitter::MainWindow::openFile().
double RadarConfig::GetRangeMin_deprecated () static
Obtain the current min range value, the range value associated with the first sample.
Returns
min range value
Definition at line 99 of file RadarConfig.cc.
Referenced by SideCar::Messages::PRIMessage::RIUInfo::load(), and SideCar::GUI::PRIEmitter::MainWindow::openFile().
static double SideCar::Messages::RadarConfig::GetRotationDuration () inline static
Obtain the duration in seconds of one rotation of the radar.
Returns
duration in seconds
Definition at line 158 of file RadarConfig.h.
double RadarConfig::GetRotationRate () static
Obtain the current rotation rate value.
Returns
rotation rate in RPMs
Definition at line 96 of file RadarConfig.cc.
uint32_t RadarConfig::GetShaftEncodingMax () static
Obtain the current max shaft encoding value.
Returns
max shaft encoding value
Definition at line 93 of file RadarConfig.cc.
Referenced by SideCar::Messages::CircularBuffer::CircularBuffer(), SideCar::Messages::PRIMessage::getAzimuthEnd(), SideCar::GUI::PRIEmitter::MainWindow::openFile(), and SideCar::Algorithms::SectorMask::shutdown().
double RadarConfig::GetSiteHeight () static
Obtain the height of the site location.
Returns
height in meters
Definition at line 129 of file RadarConfig.cc.
Referenced by SideCar::Messages::TSPI::GetMetaTypeInfo().
double RadarConfig::GetSiteLatitude () static
Obtain the latitude (north/south) of the site location.
Returns
degrees latitude
Definition at line 123 of file RadarConfig.cc.
Referenced by SideCar::Messages::TSPI::GetMetaTypeInfo(), and SideCar::GUI::RangeMap::RangeMap().
double RadarConfig::GetSiteLongitude () static
Obtain the longitude (east/west) of the site location.
Returns
degrees longitude
Definition at line 117 of file RadarConfig.cc.
Referenced by SideCar::Messages::TSPI::GetMetaTypeInfo(), and SideCar::GUI::RangeMap::RangeMap().
bool RadarConfig::Load (const QDomElement & config) static
Load in a new radar configuration from an XML DOM node.
Parameters
config the DOM node containing the configuration
Returns
true if successful
Definition at line 177 of file RadarConfig.cc.
References Log(), and LOGERROR.
void RadarConfig::Load (const std::string & name, uint32_t gateCountMax, uint32_t shaftEncodingMax, double rotationRate, double rangeMin, double rangeMax, double beamWidth) static
Load in new radar configuration from raw values.
Parameters
name name of the configuration
gateCountMax max number of gate samples in a message
shaftEncodingMax max shaft encoding value
rotationRate expected rotation rate of the radar in RPMs
rangeMin range value of first gate sample in kilometers
rangeMax range value of last gate sample in kilometers
beamWidth width of radar beam for one PRI
Definition at line 141 of file RadarConfig.cc.
References Log(), LOGDEBUG, and LOGWARNING.
Logger::Log & RadarConfig::Log () static
Log device for RadarConfig messages.
Returns
Log device
Definition at line 80 of file RadarConfig.cc.
References Logger::Log::Find().
Referenced by Load().
bool RadarConfig::SetConfigurationFilePath (std::string path) static
Use a new file path for radar configuration values.
Parameters
path file path to use
Returns
true if successfully installed
Definition at line 135 of file RadarConfig.cc.
Referenced by PRIInfoInputTask::deliverDataMessage(), PRIChunkerOutputTask::deliverDataMessage(), and SideCar::GUI::PRIEmitter::MainWindow::openFile().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Messages/RadarConfig.h
/Users/howes/src/sidecar/Messages/RadarConfig.cc