SideCar: SideCar::GUI::Master::NotificationParam Class Reference
SideCar::GUI::Master::NotificationParam Class Reference
Notification parameter 'editor'.
#include </Users/howes/src/sidecar/GUI/Master/ParamEditor.h>
Signals
void sendNotification ()
Signals inherited from SideCar::GUI::Master::ParamBase
void valueChanged ()
Notification sent out by the editor when it holds a value that is different from the parameter's current value.
Public Member Functions
NotificationParam (QVBoxLayout *parentLayout, const XmlRpc::XmlRpcValue &entry)
Constructor.
void setValue (const XmlRpc::XmlRpcValue &value)
bool hasChanged () const
Determine if the parameter value has changed.
bool notOriginal () const
void acceptChange ()
Commit the value change.
void undoChange ()
Undo any changes in the editor by updating it with the current parameter value.
void revertToOriginal ()
Revert the current value to the original configuration value.
Public Member Functions inherited from SideCar::GUI::Master::ParamBase
ParamBase (QVBoxLayout *parentLayout, const XmlRpc::XmlRpcValue &entry)
Constructor.
const std::string & getName () const
Obtain the name of the parameter.
const std::string & getLabel () const
void addIfChanged (XmlRpc::XmlRpcValue &values, QStringList &changes)
If the editor has a changed value, update the held parameter value, and add XML data that will update the parameter with a new value.
ParamBase & add (QWidget *widget)
Add an editor widget.
void done ()
Additional Inherited Members
Public Slots inherited from SideCar::GUI::Master::ParamBase
void setVisible (bool state)
Static Public Member Functions inherited from SideCar::GUI::Master::ParamBase
static QString GetString (const std::string &value)
static QString GetQuotedString (const QString &value)
Protected Member Functions inherited from SideCar::GUI::Master::ParamBase
QLabel * makeLabel (QString text="")
QWidget * getParent ()
Detailed Description
Notification parameter 'editor'.
Shows a QPushButton, which when clicked, emits a parameter change request. Used for push buttons such as "Reset" or "Rewind".
Definition at line 456 of file ParamEditor.h.
Constructor & Destructor Documentation
NotificationParam::NotificationParam (QVBoxLayout * parentLayout, const XmlRpc::XmlRpcValue & entry)
Constructor.
Creates a layout into which the label and QPushButton reside.
Parameters
parentLayout the layout to add to
entry definition of the parameter being edited.
Definition at line 491 of file ParamEditor.cc.
References SideCar::GUI::Master::ParamBase::add(), and undoChange().
Referenced by revertToOriginal().
Member Function Documentation
bool NotificationParam::hasChanged () const virtual
Determine if the parameter value has changed.
Returns
true if so
Implements SideCar::GUI::Master::ParamBase.
Definition at line 516 of file ParamEditor.cc.
Referenced by revertToOriginal().
void NotificationParam::undoChange () virtual
Undo any changes in the editor by updating it with the current parameter value.
Derived classes must define.
Implements SideCar::GUI::Master::ParamBase.
Definition at line 528 of file ParamEditor.cc.
Referenced by NotificationParam(), and revertToOriginal().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/ParamEditor.h
/Users/howes/src/sidecar/GUI/Master/ParamEditor.cc