SideCar: SideCar::GUI::Master::ParamBase Class Reference
SideCar::GUI::Master::ParamBase Class Reference abstract
Abstract base class for a parameter editor.
#include </Users/howes/src/sidecar/GUI/Master/ParamEditor.h>
Public Slots
void setVisible (bool state)
Signals
void valueChanged ()
Notification sent out by the editor when it holds a value that is different from the parameter's current value.
Public Member Functions
ParamBase (QVBoxLayout *parentLayout, const XmlRpc::XmlRpcValue &entry)
Constructor.
const std::string & getName () const
Obtain the name of the parameter.
const std::string & getLabel () const
virtual bool hasChanged () const =0
Determine if the parameter value has changed.
virtual bool notOriginal () const =0
virtual void acceptChange ()=0
Commit the value change.
virtual void undoChange ()=0
Undo any changes in the editor by updating it with the current parameter value.
virtual void setValue (const XmlRpc::XmlRpcValue &value)=0
virtual void revertToOriginal ()=0
void addIfChanged (XmlRpc::XmlRpcValue &values, QStringList &changes)
If the editor has a changed value, update the held parameter value, and add XML data that will update the parameter with a new value.
ParamBase & add (QWidget *widget)
Add an editor widget.
void done ()
Static Public Member Functions
static QString GetString (const std::string &value)
static QString GetQuotedString (const QString &value)
Protected Member Functions
virtual QString fillInChange (XmlRpc::XmlRpcValue &values)=0
Add XML data that will update the parameter with a new value.
QLabel * makeLabel (QString text="")
QWidget * getParent ()
Detailed Description
Abstract base class for a parameter editor.
Contains a label and a value editor, the type of which is dependent on the type of the parameter being edited. Defines the interface that all typed editors must define.
Definition at line 36 of file ParamEditor.h.
Constructor & Destructor Documentation
ParamBase::ParamBase (QVBoxLayout * parentLayout, const XmlRpc::XmlRpcValue & entry)
Constructor.
Creates a layout into which the label and (future) editor widget reside.
Parameters
parentLayout the layout to add to
entry definition of the parameter being edited.
Definition at line 29 of file ParamEditor.cc.
Member Function Documentation
virtual void SideCar::GUI::Master::ParamBase::acceptChange () pure virtual
Commit the value change.
Derived classes must define.
Implemented in SideCar::GUI::Master::NotificationParam, SideCar::GUI::Master::BoolParam, SideCar::GUI::Master::EnumParam, SideCar::GUI::Master::PathParam, SideCar::GUI::Master::StringParam, SideCar::GUI::Master::DoubleParam, and SideCar::GUI::Master::IntParam.
Referenced by addIfChanged().
ParamBase & ParamBase::add (QWidget * widget)
Add an editor widget.
Parameters
widget the editor widget to use
Definition at line 53 of file ParamEditor.cc.
Referenced by SideCar::GUI::Master::BoolParam::BoolParam(), SideCar::GUI::Master::DoubleParam::DoubleParam(), SideCar::GUI::Master::EnumParam::EnumParam(), SideCar::GUI::Master::IntParam::IntParam(), SideCar::GUI::Master::NotificationParam::NotificationParam(), SideCar::GUI::Master::PathParam::PathParam(), and SideCar::GUI::Master::StringParam::StringParam().
void ParamBase::addIfChanged (XmlRpc::XmlRpcValue & values, QStringList & changes)
If the editor has a changed value, update the held parameter value, and add XML data that will update the parameter with a new value.
Parameters
values an XML array that holds the changes
Definition at line 82 of file ParamEditor.cc.
References acceptChange(), fillInChange(), Logger::Log::Find(), and hasChanged().
Referenced by SideCar::GUI::Master::NotificationParam::revertToOriginal().
virtual QString SideCar::GUI::Master::ParamBase::fillInChange (XmlRpc::XmlRpcValue & values) protected pure virtual
Add XML data that will update the parameter with a new value.
Derived classes must define.
Parameters
values an XML array that holds the changes
Referenced by addIfChanged().
const std::string& SideCar::GUI::Master::ParamBase::getName () const inline
Obtain the name of the parameter.
Returns
parameter name
Definition at line 59 of file ParamEditor.h.
Referenced by SideCar::GUI::Master::EnumParam::acceptChange(), SideCar::GUI::Master::EnumParam::EnumParam(), SideCar::GUI::Master::EnumParam::revertToOriginal(), and SideCar::GUI::Master::EnumParam::undoChange().
virtual bool SideCar::GUI::Master::ParamBase::hasChanged () const pure virtual
Determine if the parameter value has changed.
Derived classes must define.
Returns
true if so
Implemented in SideCar::GUI::Master::NotificationParam, SideCar::GUI::Master::BoolParam, SideCar::GUI::Master::EnumParam, SideCar::GUI::Master::PathParam, SideCar::GUI::Master::StringParam, SideCar::GUI::Master::DoubleParam, and SideCar::GUI::Master::IntParam.
Referenced by addIfChanged().
virtual void SideCar::GUI::Master::ParamBase::undoChange () pure virtual
Undo any changes in the editor by updating it with the current parameter value.
Derived classes must define.
Implemented in SideCar::GUI::Master::NotificationParam, SideCar::GUI::Master::BoolParam, SideCar::GUI::Master::EnumParam, SideCar::GUI::Master::PathParam, SideCar::GUI::Master::StringParam, SideCar::GUI::Master::DoubleParam, and SideCar::GUI::Master::IntParam.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/ParamEditor.h
/Users/howes/src/sidecar/GUI/Master/ParamEditor.cc