SideCar: SideCar::IO::StateEmitter Class Reference
SideCar::IO::StateEmitter Class Reference
Data Structures
struct Private
Public Member Functions
StateEmitter ()
Constructor.
virtual ~StateEmitter ()
Destructor.
bool open (const std::string &emitterName, long threadFlags=THR_NEW_LWP|THR_JOINABLE|THR_INHERIT_SCHED, long priority=ACE_DEFAULT_THREAD_PRIORITY)
Open a datagram socket and publish connection information.
void close ()
Close the datagram socket and shutdown Zeroconf publisher.
void setState (const std::string &key, const std::string &value)
Set the value of a key and update the published state of the emitter.
void removeState (const std::string &key)
Remove a key from the published state.
void publish ()
Publish the current state to any subscribers.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device used by StatusEmitter objects.
Static Public Member Functions inherited from SideCar::IO::ZeroconfTypes::TZCType< id >
static const char * GetZeroconfType ()
Obtain the configured Zeroconf type for objects derived from this class.
static const char * GetTwinZeroconfType ()
Obtain the "twin" Zeroconf type for objects derived from this class.
static std::string MakeZeroconfType (const std::string &subType)
Construct a valid SideCar Zeroconf type string for a given subtype.
static std::string MakeTwinZeroconfType (const std::string &subType)
Construct the twin SideCar Zeroconf type string for a given subtype.
Static Public Member Functions inherited from SideCar::IO::ZeroconfRegistry
static const char * GetType (ID id)
Obtain the Zeroconf type string for a given ID.
static ID GetTwin (ID id)
Locate the twin of this ID.
static std::string MakeZeroconfType (const char *type, const std::string &subType)
Construct a valid SideCar Zeroconf type string for a type and a subtype.
Additional Inherited Members
Public Types inherited from SideCar::IO::ZeroconfRegistry
enum ID {
kPublisher = 0, kSubscriber, kRunnerStatusCollector, kRunnerStatusEmitter,
kStateEmitter, kStateCollector, kRunnerRemoteController, kNumTypes
}
Defined Zeroconf types.
Detailed Description
Definition at line 17 of file StateEmitter.h.
Constructor & Destructor Documentation
StateEmitter::~StateEmitter () virtual
Destructor.
Shutdown any active Emitter object
Definition at line 411 of file StateEmitter.cc.
References close().
Member Function Documentation
Logger::Log & StateEmitter::Log () static
Obtain the log device used by StatusEmitter objects.
Returns
log device
Definition at line 76 of file StateEmitter.cc.
References Logger::Log::Find(), SideCar::Zeroconf::ResolvedEntry::getFullName(), SideCar::Zeroconf::ResolvedEntry::getHost(), SideCar::Zeroconf::ResolvedEntry::getPort(), SideCar::IO::ZeroconfTypes::TZCType< id >::GetZeroconfType(), LOGDEBUG, LOGERROR, LOGFATAL, LOGINFO, LOGWARNING, SideCar::Zeroconf::Browser::Make(), and SideCar::Zeroconf::ACEMonitorFactory::Make().
bool StateEmitter::open (const std::string & emitterName, long threadFlags = THR_NEW_LWP | THR_JOINABLE | THR_INHERIT_SCHED, long priority = ACE_DEFAULT_THREAD_PRIORITY)
Open a datagram socket and publish connection information.
Returns
true if successful
Definition at line 417 of file StateEmitter.cc.
void StateEmitter::removeState (const std::string & key)
Remove a key from the published state.
Parameters
key the key to remove
Definition at line 435 of file StateEmitter.cc.
void StateEmitter::setState (const std::string & key, const std::string & value)
Set the value of a key and update the published state of the emitter.
Parameters
key the key to change
value the value to assign to the key
Definition at line 429 of file StateEmitter.cc.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/StateEmitter.h
/Users/howes/src/sidecar/IO/StateEmitter.cc