SideCar: SideCar::IO::Task Class Reference
SideCar::IO::Task Class Reference abstract
Derivation of ACE_Task for SideCar processing modules.
#include </Users/howes/src/sidecar/IO/Task.h>
Data Structures
struct ThreadParams
Parameters used by the activateThreads() method that control how threads operate.
Public Types
enum { kDefaultThreadFlags = THR_NEW_LWP | THR_JOINABLE | THR_SCHED_DEFAULT | THR_INHERIT_SCHED }
Default flags to use for processing threads.
using Ref = boost::shared_ptr< Task >
Shared reference counter for Task objects.
using ParameterMap = std::map< std::string, size_t >
Container of Parameter object references.
using ParameterVector = std::vector< Parameter::Ref >
Public Member Functions
Task (bool usingData=false)
Constructor.
~Task ()
Destructor.
const std::string & getTaskName () const
Obtain the name of the task.
void setTaskName (const std::string &taskName)
Set the task's internal name.
boost::weak_ptr< Stream > getStream () const
Obtain the stream to which this task belongs.
void setStream (const boost::shared_ptr< Stream > &stream)
Set the Stream object in which this Task object resides.
bool putInChannel (const Messages::Header::Ref &msg, size_t channel)
Place a given message into this Tasks's input processing queue.
int put (ACE_Message_Block *data, ACE_Time_Value *timeout=0) override
Override of ACE_Task method.
void setError (const std::string &text, bool force=false)
Record an error message.
const std::string & getError () const
Fetch the current error text.
void clearError ()
Clear the held error text.
bool hasError () const
Determine if the task has an error posted.
bool registerParameter (const Parameter::Ref &property)
Register a configurable parameter with the controller.
bool unregisterParameter (const Parameter::Ref &property)
Unregister a configurable parameter with the controller.
bool hasChangedParameters () const
Determine if this task has any parameter objects that have values that differ from their startup configuration.
ProcessingState::Value getProcessingState () const
Obtain the current processing state indicator.
bool isActive () const
Determine if the task is in a message processing state.
bool isInCalibrationState () const
Determine if the task is in the calibration state.
bool isInRunState () const
Determine if the task is in the run state.
bool isInStopState () const
Determine if the task is in the stop state.
const Stats & getInputStats (size_t channelIndex) const
Obtain a read-only reference to the message Stats object for this Task object.
void updateInputStats (size_t channelIndex, size_t byteCount, uint32_t sequenceCounter)
Update internal processing statistics using values from the latest message received by the task.
void setTaskIndex (size_t taskIndex)
Set the unique ID for this task.
size_t getTaskIndex () const
Obtain the unique ID for this task.
void addInputChannel (const Channel &channel)
Add an input channel to the task.
void addOutputChannel (const Channel &channel)
Add an input channel to the task.
const ChannelVector & getInputChannels () const
Obtain an existing input channel.
size_t getNumInputChannels () const
Obtain the number of input channels defined for this task.
const Channel & getInputChannel (size_t index)
Obtain a specific input channel defined for this task.
size_t getInputChannelIndex (const std::string &name)
Obtain the index of an input channel with a given name.
const ChannelVector & getOutputChannels () const
Obtain an existing output channel.
size_t getNumOutputChannels () const
Obtain the number of output channels defined for this task.
const Channel & getOutputChannel (size_t index)
Obtain a specific output channel defined for this task.
size_t getOutputChannelIndex (const std::string &name)
Obtain the index of an output channel with a given name.
void getCurrentParameters (XmlRpc::XmlRpcValue &value) const
Obtain an XML-RPC definition of the current runtime parameter values.
void getChangedParameters (XmlRpc::XmlRpcValue &value) const
Obtain an XML-RPC definition of all changed runtime parameter values, those with values different from that found in the configuration file or at initialization time.
virtual const char * getStatusClassName () const
Obtain the status class name for this class.
virtual size_t getStatusSize () const
Obtain the number of slots in the TaskStatus XML status object.
virtual void fillStatus (StatusBase &status)
Obtain status information from the task.
bool isUsingData () const
Obtain the current usingData_ setting.
void updateUsingDataValue ()
Update this object's usingData_ value.
virtual void setUsingData (bool value)
Set a new usingData_ value.
virtual bool calculateUsingDataValue () const
Obtain a desired usingData_ value depending on othe Task settings, such as recipient usingData_ values, the alwaysUsingData_ parameter, and the current processing state.
void setThreadParams (const ThreadParams &threadParams)
Set the thread parameters that the task will use in its activateThreads() call.
const ThreadParams & getThreadParams () const
Obtain the current thread parameter settings.
bool activateThreads (int count)
Spawn count threads that will each run in the task's svc() method, which derived classes must define (see ACE_Task::svc()).
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for objects of this class.
Protected Member Functions
bool enterProcessingState (ProcessingState::Value state)
Change the tasks processing state indicator.
bool enterLastProcessingState ()
Change to the last non-failure processing state.
virtual bool enterInitializeState ()
Processor for the transition into the initialize state.
virtual bool enterAutoDiagnosticsState ()
Processor for the transition into the auto-diagnostic state.
virtual bool enterCalibrateState ()
Processor for the transition into the calibrate state.
virtual bool enterRunState ()
Processor for the transition into the run state.
virtual bool enterStopState ()
Processor for the transition into the stop state.
virtual bool enterFailureState ()
Processor for the transition into the failure state.
void resetProcessedStats ()
Reset the processed counters.
virtual bool deliverControlMessage (ACE_Message_Block *data, ACE_Time_Value *timeout)
Give a control message to the task.
virtual bool deliverDataMessage (ACE_Message_Block *data, ACE_Time_Value *timeout)=0
Give a message to the task to do with as it pleases.
bool processMessage (ACE_Message_Block *data)
Process a message, data or control.
virtual bool processDataMessage (ACE_Message_Block *data)
Process a data message.
virtual bool doTimeout ()
Process a timeout expired control message.
virtual bool processControlMessage (ACE_Message_Block *data)
Process a control message.
virtual bool doParametersChange (const ParametersChangeRequest &request)
Process runtime parameter changes from an XML-RPC request.
virtual bool doProcessingStateChange (const ProcessingStateChangeRequest &request)
Respond to a processing state change meessage.
virtual bool doRecordingStateChange (const RecordingStateChangeRequest &request)
Respond to a recording state change meessage.
virtual bool doShutdownRequest ()
Respond to a SHUTDOOWN control meessage.
virtual bool doClearStatsRequest ()
Respond to a ClearStatsRequest control messsage.
void setConnectionInfo (const std::string &connectionInfo)
Set the status text that represents the connection information for the task.
virtual bool send (const Messages::Header::Ref &msg, size_t channelIndex)
bool sendManaged (MessageManager &mgr, size_t channelIndex)
Detailed Description
Derivation of ACE_Task for SideCar processing modules.
An ACE_Task object may belong to an ACE_Module for processing in an ACE_Stream. Also, the ACE_Task class supports threaded processing via its svc() and activate() methods. Additional information on the ACE_Task, ACE_Module, and ACE_Stream components exist in the booksC++ Network Programming: Mastering Complexity Using ACE and Patterns'', andC++ Network Programming: Systematic Reuse with ACE and Frameworks''.
A Task object is always in one of the following processing states:
kInitialize – task is initialized
kAutoDiagnostic – task is performming an auto-diagnostic check
kCalibrate – task is performing a calibration
kRun – task is in normal run mode
kStop – task is not processing
kFailure – task has encountered an unrecoverable/fatal error
Transitions among the above states occur by calling enterProcessingState() with the new state. Enter a new state invokes a virtual method associated with the state; for instance, kCalibrate will run the calibrateStateProcessor(). If any processor method returns false, the task immediately transitions into the kFailure state, where it will remain until directed to enter the kInitialize state.
The Task object keeps track of statistics in the form of message and byte counts processed by the task. These values are reset whenever the Task enters the kAutoDiagnostic, kCalibrate, and kRun. States.
Connections
SideCar tasks support directed connections among other tasks. Each task may have zero or more input connections from other other tasks as well as zero or more output connections to other tasks.
Note
Due to the way messages are delivered by following connections, cycles must be avoided
On-Demand Processing
A Task object only receives data when its isUsingData() method returns true (the value of the usingData_ attribute). This attribute may be changed by others through the setUsingData() method, but the value given to this method may be amended by the return of calculateUsingDataValue().
Normally, a Task will return true from isUsingData() when one of the following is true:
any of its recipients isUsingData() returns true
the alwaysUsingData_ parameter is enabled
the current processing state is ProcessingState::kAutoDiagnostic
Derived classes may override calculateUsingDataValue() in order to amend the above conditions.
The setUsingData() of Task will invoke calculateUsingDataValue() only if the value given to it is false. This supports the case where a downstream input task turns off for some reason, but there are other output tasks asking for data (or other conditions listed above are met). Due to this linkage, care must be exercised when overriding the setUsingData() or calculateUsingDataValue() methods: it is fragile and easy to break.
Note
The on-demand processing logic described above operates in a multi-threaded environment. Currently, changes to the boolean usingData_ attribute occur without mutex protection which may be bad mojo.
Definition at line 87 of file Task.h.
Member Enumeration Documentation
anonymous enum
Default flags to use for processing threads.
See ace/Task_T.h
Definition at line 94 of file Task.h.
Constructor & Destructor Documentation
Task::Task (bool usingData = false)
Constructor.
Since this is an abstract base class, only derived classes may be instantiated.
Definition at line 35 of file Task.cc.
References Log(), LOGINFO, and registerParameter().
Task::~Task ()
Destructor.
Here only to emit a logging message.
Definition at line 87 of file Task.cc.
References Log(), and LOGINFO.
Member Function Documentation
bool Task::activateThreads (int count)
Spawn count threads that will each run in the task's svc() method, which derived classes must define (see ACE_Task::svc()).
Parameters
count the number of threads to launch
Returns
true if successful, false otherwise
Definition at line 846 of file Task.cc.
References Log(), and LOGINFO.
void Task::addInputChannel (const Channel & channel)
Add an input channel to the task.
Parameters
channel the channel to add
Definition at line 805 of file Task.cc.
References SideCar::IO::Channel::updateSenderUsingData().
void SideCar::IO::Task::addOutputChannel (const Channel & channel) inline
Add an input channel to the task.
Parameters
channel the channel to add
Definition at line 302 of file Task.h.
bool Task::calculateUsingDataValue () const virtual
Obtain a desired usingData_ value depending on othe Task settings, such as recipient usingData_ values, the alwaysUsingData_ parameter, and the current processing state.
Note
Exercise care if changing this or overriding it in a derived class. Derived classes should usually invoke this method in a boolean clause such as:
return return (foobar_ == 3) || Super::calculateUsingDataValue();
\return true if using data
Reimplemented in SideCar::Algorithms::Controller.
Definition at line 819 of file Task.cc.
References SideCar::IO::ProcessingState::kAutoDiagnostic.
Referenced by SideCar::Algorithms::Controller::calculateUsingDataValue(), SideCar::IO::TCPDataPublisher::deliverDataMessage(), SideCar::IO::MulticastDataPublisher::deliverDataMessage(), and setUsingData().
bool Task::deliverControlMessage (ACE_Message_Block * data, ACE_Time_Value * timeout) protected virtual
Give a control message to the task.
This implementation just invokes processControlMessage().
Parameters
data message to deliver
timeout amount of time to spend trying to deliver message
Returns
true if successful
Reimplemented in PRIChunkerOutputTask, PRIInfoInputTask, PRIInfoInputTask, InputTask, PRIInfoInputTask, InputTask, PRIChunkerInputTask, and ConverterInputTask.
Definition at line 446 of file Task.cc.
References Log(), LOGTIN, and processControlMessage().
Referenced by put().
virtual bool SideCar::IO::Task::deliverDataMessage (ACE_Message_Block * data, ACE_Time_Value * timeout) protected pure virtual
Give a message to the task to do with as it pleases.
Derived classes must define.
Parameters
data message to deliver
timeout amount of time to spend trying to deliver message
Returns
true if successful
Implemented in SideCar::IO::MulticastDataPublisher, PRIChunkerOutputTask, SideCar::IO::TCPDataPublisher, PRIInfoInputTask, SideCar::Algorithms::Sink, PRIInfoInputTask, InputTask, PRIInfoInputTask, InputTask, PRIChunkerInputTask, ConverterInputTask, and SideCar::Algorithms::ShutdownMonitor.
Referenced by put().
bool Task::doClearStatsRequest () protected virtual
Respond to a ClearStatsRequest control messsage.
Resets the running message tally to zeros.
Returns
true if successful
Definition at line 627 of file Task.cc.
References SideCar::IO::Channel::deliver(), SideCar::IO::ChannelVector::getChannel(), SideCar::IO::MessageManager::getMessage(), Log(), LOGINFO, resetProcessedStats(), and SideCar::IO::ChannelVector::size().
Referenced by SideCar::Algorithms::Controller::injectProcessingStateChange(), and processControlMessage().
bool Task::doParametersChange (const ParametersChangeRequest & request) protected virtual
Process runtime parameter changes from an XML-RPC request.
Parameters
msg new parameter settings
Returns
true if successful
Definition at line 553 of file Task.cc.
References SideCar::IO::ParametersChangeRequest::getValue(), Log(), LOGDEBUG, LOGERROR, LOGINFO, LOGWARNING, setError(), updateUsingDataValue(), and Utils::Exception::what().
Referenced by SideCar::Algorithms::Controller::injectProcessingStateChange(), and processControlMessage().
bool Task::doProcessingStateChange (const ProcessingStateChangeRequest & request) protected virtual
Respond to a processing state change meessage.
Calls enterProcessingState() to perform the state change.
Parameters
request new state to enter
Returns
true if successful
Reimplemented in SideCar::IO::DataSubscriber.
Definition at line 611 of file Task.cc.
References enterProcessingState(), Log(), and LOGINFO.
Referenced by SideCar::IO::DataSubscriber::doProcessingStateChange(), and processControlMessage().
bool Task::doRecordingStateChange (const RecordingStateChangeRequest & request) protected virtual
Respond to a recording state change meessage.
This implementation ignores such a request.
Returns
true if successful
Definition at line 603 of file Task.cc.
References Log(), and LOGINFO.
Referenced by processControlMessage().
bool Task::doShutdownRequest () protected virtual
Respond to a SHUTDOOWN control meessage.
This implementation ignores such a request, but derived classes may override to handle the situation the application shuts down.
Note
This is different than entering the kStop processing state – a SHUTDOWN message signals a ShutdownMonitor task to halt ACE processing.
Returns
true if successful
Reimplemented in SideCar::Algorithms::ShutdownMonitor.
Definition at line 619 of file Task.cc.
References Log(), and LOGINFO.
Referenced by processControlMessage().
bool Task::doTimeout () protected virtual
Process a timeout expired control message.
Warning
WARNING: this implementation throws an exception if invoked.
Returns
true if successful
Definition at line 491 of file Task.cc.
References Log(), LOGINFO, and Logger::ProcLog::thrower().
Referenced by processControlMessage().
bool Task::enterAutoDiagnosticsState () protected virtual
Processor for the transition into the auto-diagnostic state.
This implementation simply resets the processing statistics.
Returns
true if successful.
Definition at line 314 of file Task.cc.
References Log(), and LOGINFO.
Referenced by enterProcessingState(), and SideCar::Algorithms::Controller::injectProcessingStateChange().
bool Task::enterCalibrateState () protected virtual
Processor for the transition into the calibrate state.
This implementation simply resets the processing statistics.
Returns
true if successful.
Definition at line 322 of file Task.cc.
References Log(), and LOGINFO.
Referenced by enterProcessingState(), and SideCar::Algorithms::Controller::injectProcessingStateChange().
bool Task::enterFailureState () protected virtual
Processor for the transition into the failure state.
This implementation does nothing.
Returns
true if successful.
Definition at line 346 of file Task.cc.
References enterStopState(), SideCar::IO::ProcessingState::kFailure, SideCar::IO::ProcessingState::kStop, Log(), and LOGINFO.
Referenced by enterProcessingState().
bool Task::enterInitializeState () protected virtual
Processor for the transition into the initialize state.
This implementation does nothing.
Returns
true if successful.
Definition at line 301 of file Task.cc.
References clearError(), Log(), LOGINFO, and resetProcessedStats().
Referenced by enterProcessingState(), and SideCar::Algorithms::Controller::injectProcessingStateChange().
bool Task::enterLastProcessingState () protected
Change to the last non-failure processing state.
Returns
true if successful
Definition at line 362 of file Task.cc.
References clearError(), enterProcessingState(), Log(), and LOGINFO.
Referenced by SideCar::IO::DataPublisher::close().
bool Task::enterProcessingState (ProcessingState::Value state) protected
Change the tasks processing state indicator.
Invokes the appropriate processor method for the new state, iff the transition from the current state to the new one is valid.
Parameters
state new state to enter
Returns
true if successful, false if entered kFailure state
Definition at line 231 of file Task.cc.
References enterAutoDiagnosticsState(), enterCalibrateState(), enterFailureState(), enterInitializeState(), enterRunState(), enterStopState(), SideCar::IO::ProcessingState::GetName(), hasError(), SideCar::IO::ProcessingState::IsNormal(), SideCar::IO::ProcessingState::kAutoDiagnostic, SideCar::IO::ProcessingState::kCalibrate, SideCar::IO::ProcessingState::kInitialize, SideCar::IO::ProcessingState::kRun, SideCar::IO::ProcessingState::kStop, Log(), LOGDEBUG, LOGINFO, SideCar::Parameter::Defs::BasicEnumTypeDef< EnumDefs >::None(), setError(), and updateUsingDataValue().
Referenced by doProcessingStateChange(), enterLastProcessingState(), getChangedParameters(), and setError().
bool Task::enterRunState () protected virtual
Processor for the transition into the run state.
This implementation simply resets the processing statistics.
Returns
true if successful.
Reimplemented in SideCar::IO::FileReaderTask.
Definition at line 330 of file Task.cc.
References Log(), and LOGINFO.
Referenced by SideCar::IO::TSPIReaderTask::close(), SideCar::IO::MulticastVMEReaderTask::close(), enterProcessingState(), and SideCar::Algorithms::Controller::injectProcessingStateChange().
bool Task::enterStopState () protected virtual
Processor for the transition into the stop state.
This implementation does nothing.
Returns
true if successful.
Definition at line 338 of file Task.cc.
References Log(), and LOGINFO.
Referenced by enterFailureState(), enterProcessingState(), and SideCar::Algorithms::Controller::injectProcessingStateChange().
void Task::fillStatus (StatusBase & status) virtual
Obtain status information from the task.
Fills in message processing stats.
Parameters
status status object to fill in
Reimplemented in SideCar::Algorithms::Controller.
Definition at line 676 of file Task.cc.
References SideCar::IO::Stats::calculateRates(), SideCar::IO::Stats::getByteRate(), SideCar::IO::Stats::getDropCount(), SideCar::IO::Stats::getDupeCount(), SideCar::IO::Stats::getMessageCount(), SideCar::IO::Stats::getMessageRate(), Log(), LOGDEBUG, and SideCar::IO::StatusBase::setSlot().
Referenced by SideCar::Algorithms::Controller::fillStatus().
void Task::getChangedParameters (XmlRpc::XmlRpcValue & value) const
Obtain an XML-RPC definition of all changed runtime parameter values, those with values different from that found in the configuration file or at initialization time.
Parameters
value container to hold the definitions
Definition at line 772 of file Task.cc.
References enterProcessingState(), SideCar::Parameter::TValue< ParamDef >::getValue(), Log(), LOGINFO, and XmlRpc::XmlRpcValue::setSize().
void Task::getCurrentParameters (XmlRpc::XmlRpcValue & value) const
Obtain an XML-RPC definition of the current runtime parameter values.
Parameters
value container to hold the definitions
Definition at line 737 of file Task.cc.
References XmlRpc::XmlRpcValue::setSize().
const std::string& SideCar::IO::Task::getError () const inline
Fetch the current error text.
Returns
error text
Definition at line 197 of file Task.h.
const Channel& SideCar::IO::Task::getInputChannel (size_t index) inline
Obtain a specific input channel defined for this task.
Parameters
index which input channel to fetch
Returns
read-only reference to the Channel
Definition at line 324 of file Task.h.
Referenced by SideCar::Algorithms::Algorithm::addProcessor().
size_t SideCar::IO::Task::getInputChannelIndex (const std::string & name) inline
Obtain the index of an input channel with a given name.
Parameters
name the name to look for
Returns
index of found input channel, or -1 if none found
Definition at line 332 of file Task.h.
Referenced by SideCar::Algorithms::Algorithm::addProcessor(), and SideCar::Algorithms::ManyInAlgorithm::processMessageReceived().
const ChannelVector& SideCar::IO::Task::getInputChannels () const inline
Obtain an existing input channel.
Parameters
index the position of the channel to fetch
Returns
read-only Channel reference
Definition at line 310 of file Task.h.
const Stats& SideCar::IO::Task::getInputStats (size_t channelIndex) const inline
Obtain a read-only reference to the message Stats object for this Task object.
Returns
Stats reference
Definition at line 270 of file Task.h.
size_t SideCar::IO::Task::getNumInputChannels () const inline
Obtain the number of input channels defined for this task.
Returns
number of input channels
Definition at line 316 of file Task.h.
Referenced by SideCar::Algorithms::Algorithm::addProcessor(), SideCar::Algorithms::ManyInAlgorithm::processMessageReceived(), SideCar::Algorithms::FanIn::startup(), SideCar::Algorithms::Router::startup(), and SideCar::Algorithms::ManyInAlgorithm::startup().
size_t SideCar::IO::Task::getNumOutputChannels () const inline
Obtain the number of output channels defined for this task.
Returns
number of output channels
Definition at line 346 of file Task.h.
Referenced by SideCar::Algorithms::Controller::injectProcessingStateChange(), SideCar::Algorithms::Algorithm::send(), SideCar::Algorithms::FanOut::shutdown(), and SideCar::Algorithms::Router::startup().
const Channel& SideCar::IO::Task::getOutputChannel (size_t index) inline
Obtain a specific output channel defined for this task.
Parameters
index which output channel to fetch
Returns
read-only reference to the Channel
Definition at line 354 of file Task.h.
size_t SideCar::IO::Task::getOutputChannelIndex (const std::string & name) inline
Obtain the index of an output channel with a given name.
Parameters
name the name to look for
Returns
index of found output channel, or -1 if none found
Definition at line 362 of file Task.h.
const ChannelVector& SideCar::IO::Task::getOutputChannels () const inline
Obtain an existing output channel.
Parameters
index the position of the channel to fetch
Returns
read-only Channel reference
Definition at line 340 of file Task.h.
ProcessingState::Value SideCar::IO::Task::getProcessingState () const inline
Obtain the current processing state indicator.
Returns
current state
Definition at line 236 of file Task.h.
virtual const char* SideCar::IO::Task::getStatusClassName () const inline virtual
Obtain the status class name for this class.
Derived classes should override to return a value unique to the class.
Returns
NULL-terminated C string
Reimplemented in SideCar::Algorithms::Controller.
Definition at line 382 of file Task.h.
virtual size_t SideCar::IO::Task::getStatusSize () const inline virtual
Obtain the number of slots in the TaskStatus XML status object.
Returns
slot count
Reimplemented in SideCar::Algorithms::Controller.
Definition at line 388 of file Task.h.
boost::weak_ptr<Stream> SideCar::IO::Task::getStream () const inline
Obtain the stream to which this task belongs.
Returns
Stream pointer or NULL if not part of a stream.
Definition at line 154 of file Task.h.
Referenced by SideCar::Algorithms::ShutdownMonitor::handle_timeout().
size_t SideCar::IO::Task::getTaskIndex () const inline
Obtain the unique ID for this task.
Returns
task ID
Definition at line 290 of file Task.h.
const std::string& SideCar::IO::Task::getTaskName () const inline
Obtain the name of the task.
Returns
task name
Definition at line 141 of file Task.h.
Referenced by SideCar::Algorithms::Controller::calculateUsingDataValue(), SideCar::IO::MulticastVMEReaderTask::close(), SideCar::IO::DataPublisher::close(), SideCar::IO::MulticastDataSubscriber::ReaderThread::close(), SideCar::Algorithms::Controller::injectProcessingStateChange(), SideCar::IO::UDPSocketWriterTask::openAndInit(), SideCar::IO::FileWriterTask::openAndInit(), SideCar::IO::VMEReaderTask::openAndInit(), SideCar::IO::ClientSocketReaderTask::openAndInit(), SideCar::IO::TSPIReaderTask::openAndInit(), SideCar::IO::TCPDataSubscriber::openAndInit(), SideCar::IO::FileReaderTask::openAndInit(), SideCar::IO::UDPSocketReaderTask::openAndInit(), SideCar::IO::MulticastVMEReaderTask::openAndInit(), SideCar::IO::ServerSocketReaderTask::openAndInit(), SideCar::IO::MulticastDataSubscriber::ReaderThread::openAndInit(), SideCar::IO::ServerSocketWriterTask::openAndInit(), SideCar::Algorithms::Controller::openAndInit(), SideCar::IO::DataPublisher::publish(), SideCar::IO::TCPDataSubscriber::setServiceName(), and SideCar::Algorithms::Controller::setTimerSecs().
const ThreadParams& SideCar::IO::Task::getThreadParams () const inline
Obtain the current thread parameter settings.
Returns
Definition at line 443 of file Task.h.
bool Task::hasChangedParameters () const
Determine if this task has any parameter objects that have values that differ from their startup configuration.
Returns
true if so
Definition at line 749 of file Task.cc.
References SideCar::Parameter::ValueBase::isNotOriginal().
bool SideCar::IO::Task::hasError () const inline
Determine if the task has an error posted.
Returns
true if so
Definition at line 207 of file Task.h.
Referenced by enterProcessingState(), and SideCar::Algorithms::Controller::injectProcessingStateChange().
bool SideCar::IO::Task::isActive () const inline
Determine if the task is in a message processing state.
Currently, there are three processing states:
1) kAutoDiagnostic 2) kCalibrate 3) kRun
\return true if so
Definition at line 246 of file Task.h.
Referenced by SideCar::Algorithms::Controller::injectProcessingStateChange(), and SideCar::Algorithms::Controller::setTimerSecs().
bool SideCar::IO::Task::isInCalibrationState () const inline
Determine if the task is in the calibration state.
Returns
true if so
Definition at line 252 of file Task.h.
bool SideCar::IO::Task::isInRunState () const inline
Determine if the task is in the run state.
Returns
true if so
Definition at line 258 of file Task.h.
bool SideCar::IO::Task::isInStopState () const inline
Determine if the task is in the stop state.
Returns
true if so
Definition at line 264 of file Task.h.
bool SideCar::IO::Task::isUsingData () const inline
Obtain the current usingData_ setting.
Returns
true if Task uses data
Definition at line 400 of file Task.h.
Referenced by SideCar::IO::TCPConnector::attemptConnection(), and SideCar::IO::MulticastDataPublisher::deliverDataMessage().
Logger::Log & Task::Log () static
Obtain the log device for objects of this class.
Returns
log device
Definition at line 29 of file Task.cc.
References Logger::Log::Find().
Referenced by activateThreads(), deliverControlMessage(), doClearStatsRequest(), doParametersChange(), doProcessingStateChange(), doRecordingStateChange(), doShutdownRequest(), doTimeout(), enterAutoDiagnosticsState(), enterCalibrateState(), enterFailureState(), enterInitializeState(), enterLastProcessingState(), enterProcessingState(), enterRunState(), enterStopState(), fillStatus(), getChangedParameters(), processControlMessage(), processDataMessage(), processMessage(), put(), putInChannel(), registerParameter(), setError(), setUsingData(), Task(), unregisterParameter(), and ~Task().
bool Task::processControlMessage (ACE_Message_Block * data) protected virtual
Process a control message.
Dispatches on the control type to the appropriate 'do' method (eg. doProcessingStateChange()).
Parameters
data control message data
Returns
true if successful
Definition at line 501 of file Task.cc.
References doClearStatsRequest(), doParametersChange(), doProcessingStateChange(), doRecordingStateChange(), doShutdownRequest(), doTimeout(), SideCar::IO::ControlMessage::kClearStats, SideCar::IO::ControlMessage::kParametersChange, SideCar::IO::ControlMessage::kProcessingStateChange, SideCar::IO::ControlMessage::kRecordingStateChange, SideCar::IO::ControlMessage::kShutdown, SideCar::IO::ControlMessage::kTimeout, Log(), LOGERROR, LOGTIN, and setError().
Referenced by deliverControlMessage(), and processMessage().
bool Task::processDataMessage (ACE_Message_Block * data) protected virtual
Process a data message.
Warning
WARNING: this implementation throws an exception if invoked.
Parameters
data data message
Returns
true if successful
Definition at line 481 of file Task.cc.
References Log(), LOGINFO, and Logger::ProcLog::thrower().
Referenced by processMessage().
bool Task::processMessage (ACE_Message_Block * data) protected
Process a message, data or control.
This is a helper routine for derived classes that perform their message processing in a separate thread (it is not used by Task itself). Depending on the type of message held in the given data parameter, it invokes processDataMessage() or processControlMessage().
Parameters
data the message to process
Returns
true if successful
Definition at line 454 of file Task.cc.
References SideCar::IO::MessageManager::IsControlMessage(), SideCar::IO::MessageManager::kMetaData, Log(), LOGDEBUG, LOGFATAL, LOGINFO, processControlMessage(), processDataMessage(), and setError().
Referenced by SideCar::Algorithms::Controller::injectProcessingStateChange().
int Task::put (ACE_Message_Block * data, ACE_Time_Value * timeout = 0) override
Override of ACE_Task method.
Handles delivery of incoming messages for the task. Invokes deliverControlMessage() for control messages, and if the task is the next recipient, it invokes deliverDataMessage() for data messages.
Parameters
data message data
timeout amount of time to try to deliver the message
Returns
0 if successful, -1 otherwise
Definition at line 392 of file Task.cc.
References deliverControlMessage(), deliverDataMessage(), SideCar::IO::MessageManager::GetControlMessageType(), SideCar::IO::MessageManager::getNative(), SideCar::IO::MessageManager::IsControlMessage(), SideCar::IO::MessageManager::IsDataMessage(), SideCar::IO::ControlMessage::kTimeout, Log(), LOGERROR, LOGINFO, LOGWARNING, setError(), and updateInputStats().
Referenced by SideCar::Algorithms::Controller::calculateUsingDataValue(), SideCar::Algorithms::Controller::close(), and putInChannel().
bool Task::putInChannel (const Messages::Header::Ref & msg, size_t channel)
Place a given message into this Tasks's input processing queue.
Identify it as coming from a given channel.
Parameters
msg the input message to use
channel the input channel to use
\return true if successful
Definition at line 375 of file Task.cc.
References SideCar::IO::MessageManager::getMessage(), Log(), LOGINFO, and put().
bool Task::registerParameter (const Parameter::Ref & property)
Register a configurable parameter with the controller.
Only invoked by the algorithm DLL.
Parameters
parameter the parameter value to register
Returns
true if registered, false if name already registered
Definition at line 109 of file Task.cc.
References Log(), LOGERROR, and LOGINFO.
Referenced by SideCar::Algorithms::Controller::Make(), and Task().
void SideCar::IO::Task::setConnectionInfo (const std::string & connectionInfo) inline protected
Set the status text that represents the connection information for the task.
This value will be used when updating TaskStatus XML values.
Parameters
connectionInfo new value to assign
Definition at line 611 of file Task.h.
Referenced by SideCar::IO::TCPDataPublisher::close(), SideCar::IO::UDPSocketWriterTask::openAndInit(), SideCar::IO::TSPIReaderTask::openAndInit(), SideCar::IO::UDPSocketReaderTask::openAndInit(), SideCar::IO::TCPDataPublisher::openAndInit(), and SideCar::IO::TCPDataSubscriber::setServiceName().
void Task::setError (const std::string & text, bool force = false)
Record an error message.
The error will remain held until clearError() is called.
Parameters
text the text describing the error
force if true, overwrite any existing error message
Definition at line 94 of file Task.cc.
References enterProcessingState(), SideCar::IO::ProcessingState::kFailure, Log(), and LOGERROR.
Referenced by SideCar::IO::TCPConnector::attemptConnection(), SideCar::IO::DataSubscriber::close(), SideCar::IO::TSPIReaderTask::close(), SideCar::IO::MulticastVMEReaderTask::close(), SideCar::IO::DataPublisher::close(), SideCar::Algorithms::Controller::close(), doParametersChange(), SideCar::IO::DataSubscriber::doProcessingStateChange(), enterProcessingState(), SideCar::Algorithms::GeoFilter::GeoFilter(), SideCar::Algorithms::Controller::getStatusSize(), SideCar::IO::TCPInputHandler::handle_input(), SideCar::IO::DataPublisher::handle_timeout(), SideCar::IO::DataSubscriber::handle_timeout(), SideCar::Algorithms::Controller::injectControlMessage(), SideCar::Algorithms::Controller::injectProcessingStateChange(), SideCar::IO::DataSubscriber::openAndInit(), SideCar::IO::ClientSocketReaderTask::openAndInit(), SideCar::IO::TCPDataSubscriber::openAndInit(), SideCar::IO::TCPDataPublisher::openAndInit(), SideCar::IO::MulticastDataSubscriber::ReaderThread::openAndInit(), SideCar::Algorithms::Controller::openAndInit(), processControlMessage(), processMessage(), SideCar::IO::DataPublisher::publish(), put(), SideCar::Algorithms::MatchedFilter::reset(), SideCar::IO::TCPDataSubscriber::setServiceName(), SideCar::Algorithms::MatchedFilter::shutdown(), SideCar::Algorithms::Recorder::start(), and SideCar::Algorithms::OSCFAR::startup().
void SideCar::IO::Task::setStream (const boost::shared_ptr< Stream > & stream) inline
Set the Stream object in which this Task object resides.
May be NULL>
Parameters
stream the Stream object to associate with
Definition at line 160 of file Task.h.
void SideCar::IO::Task::setTaskIndex (size_t taskIndex) inline
Set the unique ID for this task.
Used when checking whether it is a
recipient of a message from another task.
Definition at line 284 of file Task.h.
void SideCar::IO::Task::setTaskName (const std::string & taskName) inline
Set the task's internal name.
This is used in log messages, and as the value for the StatusBase::kName field.
Parameters
taskName name to use.
Definition at line 148 of file Task.h.
Referenced by SideCar::Algorithms::ShutdownMonitor::Make(), SideCar::IO::UDPSocketWriterTask::openAndInit(), SideCar::IO::FileWriterTask::openAndInit(), SideCar::IO::VMEReaderTask::openAndInit(), SideCar::IO::ClientSocketReaderTask::openAndInit(), SideCar::IO::TSPIReaderTask::openAndInit(), SideCar::IO::FileReaderTask::openAndInit(), SideCar::IO::UDPSocketReaderTask::openAndInit(), SideCar::IO::MulticastVMEReaderTask::openAndInit(), SideCar::IO::ServerSocketReaderTask::openAndInit(), SideCar::IO::ClientSocketWriterTask::openAndInit(), SideCar::IO::ServerSocketWriterTask::openAndInit(), SideCar::Algorithms::Controller::openAndInit(), SideCar::IO::TCPDataSubscriber::setServiceName(), SideCar::IO::MulticastDataPublisher::setServiceName(), and SideCar::IO::TCPDataPublisher::TCPDataPublisher().
void SideCar::IO::Task::setThreadParams (const ThreadParams & threadParams) inline
Set the thread parameters that the task will use in its activateThreads() call.
The task records the thread parameters since initialization and configuration may not immediately invoke activateThreads().
Parameters
threadParams the new thread parameters to use.
Definition at line 437 of file Task.h.
void Task::setUsingData (bool value) virtual
Set a new usingData_ value.
If it is false, the value may be changed due to a true value returned by calculateUsingDataValue(). If the new state is different from then current usingData_ value, this routine will invoke resetProcessedStats() and notify upstream connections of the status change.
Note
Exercise care if changing this or overriding it in a derived class. A more appropriate override may be the calculateUsingDataValue() methd if the derived class has additional conditions to determine whether data should flow. At the least, derived methods must invoke this one.
Parameters
value new value to use
Reimplemented in SideCar::IO::MulticastDataSubscriber, and SideCar::IO::FileWriterTask.
Definition at line 826 of file Task.cc.
References calculateUsingDataValue(), Log(), LOGINFO, and resetProcessedStats().
Referenced by SideCar::IO::TCPConnector::attemptConnection(), and SideCar::IO::Channel::updateSenderUsingData().
bool Task::unregisterParameter (const Parameter::Ref & property)
Unregister a configurable parameter with the controller.
Only invoked by the algorithm DLL.
Parameters
parameter the parameter value to unregister
Returns
true if unregistered, false if not found
Definition at line 128 of file Task.cc.
References SideCar::IO::ProcessingState::kAutoDiagnostic, SideCar::IO::ProcessingState::kCalibrate, SideCar::IO::ProcessingState::kFailure, SideCar::IO::ProcessingState::kInitialize, SideCar::IO::ProcessingState::kRun, SideCar::IO::ProcessingState::kStop, Log(), LOGERROR, and LOGINFO.
void Task::updateInputStats (size_t channelIndex, size_t byteCount, uint32_t sequenceCounter)
Update internal processing statistics using values from the latest message received by the task.
Parameters
byteCount number of bytes received
sequenceCounter sequence counter of the received message
Definition at line 813 of file Task.cc.
Referenced by SideCar::IO::TSPIReaderTask::openAndInit(), SideCar::IO::MulticastVMEReaderTask::openAndInit(), SideCar::Algorithms::BugCollector::process(), and put().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/Task.h
/Users/howes/src/sidecar/IO/Task.cc