SideCar: SideCar::GUI::Master::DoubleParam Class Reference
SideCar::GUI::Master::DoubleParam Class Reference
Double parameter editor.
#include </Users/howes/src/sidecar/GUI/Master/ParamEditor.h>
Public Member Functions
DoubleParam (QVBoxLayout *parentLayout, const XmlRpc::XmlRpcValue &entry)
Constructor.
void setValue (const XmlRpc::XmlRpcValue &value)
bool hasChanged () const
Determine if the parameter value has changed.
bool notOriginal () const
void acceptChange ()
Commit the value change.
void undoChange ()
Undo any changes in the editor by updating it with the current parameter value.
void revertToOriginal ()
Revert the current value to the original configuration value.
Public Member Functions inherited from SideCar::GUI::Master::ParamBase
ParamBase (QVBoxLayout *parentLayout, const XmlRpc::XmlRpcValue &entry)
Constructor.
const std::string & getName () const
Obtain the name of the parameter.
const std::string & getLabel () const
void addIfChanged (XmlRpc::XmlRpcValue &values, QStringList &changes)
If the editor has a changed value, update the held parameter value, and add XML data that will update the parameter with a new value.
ParamBase & add (QWidget *widget)
Add an editor widget.
void done ()
Additional Inherited Members
Public Slots inherited from SideCar::GUI::Master::ParamBase
void setVisible (bool state)
Signals inherited from SideCar::GUI::Master::ParamBase
void valueChanged ()
Notification sent out by the editor when it holds a value that is different from the parameter's current value.
Static Public Member Functions inherited from SideCar::GUI::Master::ParamBase
static QString GetString (const std::string &value)
static QString GetQuotedString (const QString &value)
Protected Member Functions inherited from SideCar::GUI::Master::ParamBase
QLabel * makeLabel (QString text="")
QWidget * getParent ()
Detailed Description
Double parameter editor.
Uses a QLineEdit plus a validator to perform the value editing.
Definition at line 183 of file ParamEditor.h.
Constructor & Destructor Documentation
DoubleParam::DoubleParam (QVBoxLayout * parentLayout, const XmlRpc::XmlRpcValue & entry)
Constructor.
Creates a layout into which the label and QLineEdit reside.
Parameters
parentLayout the layout to add to
entry definition of the parameter being edited.
Definition at line 159 of file ParamEditor.cc.
References SideCar::GUI::Master::ParamBase::add(), XmlRpc::XmlRpcValue::hasMember(), undoChange(), and SideCar::GUI::Master::ParamBase::valueChanged().
Member Function Documentation
bool DoubleParam::hasChanged () const virtual
Determine if the parameter value has changed.
Returns
true if so
Implements SideCar::GUI::Master::ParamBase.
Definition at line 187 of file ParamEditor.cc.
void DoubleParam::undoChange () virtual
Undo any changes in the editor by updating it with the current parameter value.
Derived classes must define.
Implements SideCar::GUI::Master::ParamBase.
Definition at line 199 of file ParamEditor.cc.
Referenced by DoubleParam().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/ParamEditor.h
/Users/howes/src/sidecar/GUI/Master/ParamEditor.cc