SideCar: SideCar::GUI::AScope::HistoryControlWindow Class Reference
SideCar::GUI::AScope::HistoryControlWindow Class Reference
Tool window that allows the user to move back in time to a previous frame of data.
#include </Users/howes/src/sidecar/GUI/AScope/HistoryControlWindow.h>
Public Slots
void activeMainWindowChanged (MainWindowBase *window)
Signal handler invoked when the active MainWindow changes.
Public Slots inherited from SideCar::GUI::ToolWindowBase
virtual void activeMainWindowChanged (MainWindowBase *window)
virtual void applyInitialVisibility ()
virtual void toggleVisibility ()
virtual void showAndRaise ()
Public Member Functions
HistoryControlWindow (int shortcut, const History *history)
Constructor.
Public Member Functions inherited from SideCar::GUI::ToolWindowBase
ToolWindowBase (const QString &name, const QString &actionTitle, int shortcut=0)
Constructor.
QAction * getShowHideAction () const
Obtain the QAction object that toggles the tool window's visibility.
void setFixedSize ()
Configure the window so that the user may not resize it.
bool getInitialVisibility () const
Determine if the application should show the window at startup.
Static Public Member Functions
static Logger::Log & Log ()
Static Public Member Functions inherited from SideCar::GUI::ToolWindowBase
static Logger::Log & Log ()
Log device for instances of this class.
static AppBase * getApp ()
Convenience method that obtains the AppBase singleton.
Additional Inherited Members
Protected Member Functions inherited from SideCar::GUI::ToolWindowBase
void showEvent (QShowEvent *event)
Event handler for show events.
void closeEvent (QCloseEvent *event)
Event handler for close events.
void hideEvent (QHideEvent *event)
Event handler for hide events.
Detailed Description
Tool window that allows the user to move back in time to a previous frame of data.
Shows information about the previous frame as well as the size of the history buffer. It does not manipulate the application's History object, only reports information about it. It will change the active MainWindow's HistoryPosition when the user adjusts the history position slider.
Definition at line 27 of file HistoryControlWindow.h.
Constructor & Destructor Documentation
HistoryControlWindow::HistoryControlWindow (int shortcut, const History * history)
Constructor.
Creates and initializes window widgets.
Parameters
shortcut key sequence to change window visibility
history application History object to work with
Definition at line 19 of file HistoryControlWindow.cc.
Member Function Documentation
void HistoryControlWindow::activeMainWindowChanged (MainWindowBase * window) slot
Signal handler invoked when the active MainWindow changes.
Parameters
window new active window
Definition at line 32 of file HistoryControlWindow.cc.
References SideCar::GUI::AScope::History::getFrameCount(), SideCar::GUI::AScope::History::isEnabled(), LOGINFO, and SideCar::GUI::AScope::HistoryPosition::setPosition().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/AScope/HistoryControlWindow.h
/Users/howes/src/sidecar/GUI/AScope/HistoryControlWindow.cc