SideCar: SideCar::GUI::ReaderThread Class Reference
SideCar::GUI::ReaderThread Class Reference
A class that manages a TCP/UDP reader that runs in a separate thread.
#include </Users/howes/src/sidecar/GUI/ReaderThread.h>
Public Slots
void stop ()
If a thread is running, stop it and wait for it to exit.
Signals
void connected ()
Notification sent out when the internal MessageReader object emits its connected signal.
void dataAvailable ()
Notification sent out when the internal MessageReader object emits its incoming signal.
void disconnected ()
Notification sent out when the internal MessageReader object emits its disconnected signal.
Public Member Functions
ReaderThread ()
Constructor.
~ReaderThread ()
Destructor.
void useServiceEntry (const ServiceEntry *serviceEntry)
Use the connection information from a ServiceEntry object.
const Messages::MetaTypeInfo * getMetaTypeInfo () const
Obtain the Zeroconf sub-type last assigned in useServiceEntry()
const MessageList & getMessages ()
Obtain the list of data messages received from the internal MessageReader object.
Static Public Member Functions
static Logger::Log & Log ()
Protected Member Functions
void run ()
Method run in a separate process.
Detailed Description
A class that manages a TCP/UDP reader that runs in a separate thread.
Implements the signaling interface defined by the GUI::MessageReader class. A new thread starts when useServiceEntry() is called with a valid ServiceEntry object (called with a NULL object will stop any running thread). The thread runs the run() method, which creates a new MessageReader object, hooks up its signals to the reader* slots below, and then starts up a new Qt event loop.
Definition at line 26 of file ReaderThread.h.
Constructor & Destructor Documentation
ReaderThread::ReaderThread ()
Constructor.
Initializes state. NOTE: changes thread ownership from the main thread to the this QThead object. Any signal/slot connections to this object will be handled by queued events.
Definition at line 17 of file ReaderThread.cc.
References LOGINFO.
ReaderThread::~ReaderThread ()
Destructor.
Stops the thread if it is still running.
Definition at line 35 of file ReaderThread.cc.
References LOGINFO, and stop().
Member Function Documentation
const Messages::MetaTypeInfo* SideCar::GUI::ReaderThread::getMetaTypeInfo () const inline
Obtain the Zeroconf sub-type last assigned in useServiceEntry()
Returns
sub-type value
Definition at line 55 of file ReaderThread.h.
void ReaderThread::run () protected
Method run in a separate process.
Implements QThread interface. Creates a new MessageReader object to do the reading, and starts a new Qt event loop. The thread runs until stopped by the stop() method.
Definition at line 117 of file ReaderThread.cc.
References connected(), disconnected(), LOGINFO, and SideCar::GUI::MessageReader::Make().
void ReaderThread::useServiceEntry (const ServiceEntry * serviceEntry)
Use the connection information from a ServiceEntry object.
Stops any active thread, and starts a new one.
Parameters
serviceEntry object containing the resolved connection information for the MessageReader to use
Definition at line 44 of file ReaderThread.cc.
References SideCar::GUI::ServiceEntry::duplicate(), LOGINFO, and stop().
Referenced by SideCar::GUI::Subscriber::useServiceEntry().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/ReaderThread.h
/Users/howes/src/sidecar/GUI/ReaderThread.cc