SideCar: SideCar::GUI::Subscriber Class Reference
SideCar::GUI::Subscriber Class Reference
The input side of a publisher/subscriber pair.
#include </Users/howes/src/sidecar/GUI/Subscriber.h>
Public Slots
void shutdown ()
Shut down any active connection to a publisher.
Signals
void connected ()
Notification that a connection has been established to a publisher.
void dataAvailable ()
Notification that one or more messages are available to fetch via the getMessages().
void disconnected ()
Notification that a connection has been dropped.
Public Member Functions
Subscriber (QObject *parent=0)
Constructor.
~Subscriber ()
Destructor.
void useServiceEntry (ServiceEntry *serviceEntry)
Set publisher connection info to use.
bool isConnected () const
Obtain the connection state of the subscriber.
const MessageList & getMessages () const
Obtain the set of messages available from the publisher.
Static Public Member Functions
static Logger::Log & Log ()
Detailed Description
The input side of a publisher/subscriber pair.
Manages a separate thread that hosts a TCP/UDP reader which obtains data from the publisher. Uses the incoming() signal to announce the arrival of new messages.
The useServiceEntry() method gives the subscriber connection information of a publichser to connect to.
Definition at line 21 of file Subscriber.h.
Constructor & Destructor Documentation
Subscriber::Subscriber (QObject * parent = 0)
Constructor.
Parameters
parent owner for the purposes of destruction via Qt hierarchy
Definition at line 23 of file Subscriber.cc.
References connected(), dataAvailable(), disconnected(), and LOGINFO.
Subscriber::~Subscriber ()
Destructor.
Terminates any active reader thread.
Definition at line 34 of file Subscriber.cc.
References LOGINFO, and SideCar::GUI::ReaderThread::stop().
Member Function Documentation
const MessageList & Subscriber::getMessages () const
Obtain the set of messages available from the publisher.
May be NULL if there is no connection to a publisher.
Returns
list of Messages::Header::Ref references
Definition at line 127 of file Subscriber.cc.
References SideCar::GUI::ReaderThread::getMessages().
Referenced by SideCar::GUI::ChannelSetting::Log(), SideCar::GUI::AScope::VideoChannel::readerIncoming(), and SideCar::GUI::ChannelGroup::shutdown().
bool SideCar::GUI::Subscriber::isConnected () const inline
Obtain the connection state of the subscriber.
Returns
true if connected
Definition at line 49 of file Subscriber.h.
Referenced by SideCar::GUI::AScope::VideoChannel::isConnected().
void Subscriber::useServiceEntry (ServiceEntry * serviceEntry)
Set publisher connection info to use.
May be NULL which will close any active connection.
Parameters
serviceEntry data publisher connection info
Definition at line 51 of file Subscriber.cc.
References connected(), disconnected(), SideCar::GUI::ServiceEntry::getName(), LOGDEBUG, LOGFATAL, LOGINFO, SideCar::GUI::ServiceEntry::resolve(), SideCar::GUI::ReaderThread::stop(), and SideCar::GUI::ReaderThread::useServiceEntry().
Referenced by SideCar::GUI::ChannelSetting::Log(), SideCar::GUI::ChannelGroup::shutdown(), shutdown(), and SideCar::GUI::AScope::VideoChannel::useServiceEntry().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Subscriber.h
/Users/howes/src/sidecar/GUI/Subscriber.cc