SideCar: SideCar::IO::TCPDataSubscriber Class Reference
SideCar::IO::TCPDataSubscriber Class Reference
Public Types
using Ref = boost::shared_ptr< TCPDataSubscriber >
Public Types inherited from SideCar::IO::DataSubscriber
using Ref = boost::shared_ptr< DataSubscriber >
using ServiceEntryVector = Zeroconf::Browser::ServiceEntryVector
Public Types inherited from SideCar::IO::Task
enum { kDefaultThreadFlags = THR_NEW_LWP | THR_JOINABLE | THR_SCHED_DEFAULT | THR_INHERIT_SCHED }
Default flags to use for processing threads.
using Ref = boost::shared_ptr< Task >
Shared reference counter for Task objects.
using ParameterMap = std::map< std::string, size_t >
Container of Parameter object references.
using ParameterVector = std::vector< Parameter::Ref >
Public Types inherited from SideCar::IO::ZeroconfRegistry
enum ID {
kPublisher = 0, kSubscriber, kRunnerStatusCollector, kRunnerStatusEmitter,
kStateEmitter, kStateCollector, kRunnerRemoteController, kNumTypes
}
Defined Zeroconf types.
Public Member Functions
bool openAndInit (const std::string &key, const std::string &serviceName, int bufferSize=0, int interface=0)
Prepare to subscribe to a data publisher with a given service name.
int close (u_long flags=0)
Public Member Functions inherited from SideCar::IO::DataSubscriber
bool openAndInit (const std::string &key, const std::string &serviceName, const std::string &type, int interface=0)
Prepare to subscribe to a data publisher with a given service name.
int close (u_long flags=0) override
Shut down the subscriber.
Zeroconf::ServiceEntry::Ref getServiceEntry () const
Obtain information about the publisher we are trying to subscribed to.
const std::string & getServiceName () const
Obtain the service name of the current publisher we are subscribed to.
void restartBrowser ()
Restart the service and the Zeroconf browser that looks for publishers to connect to.
Public Member Functions inherited from SideCar::IO::IOTask
const Messages::MetaTypeInfo * getMetaTypeInfo () const
Obtain the MetaTypeInfo object registered with the task.
const std::string & getMetaTypeInfoKeyName () const
Obtain the message type name.
Messages::MetaTypeInfo::Value getMetaTypeInfoKey () const
Obtain the message type key.
Messages::MetaTypeInfo::CDRLoader getMetaTypeInfoCDRLoader () const
Obtain the loader for the message type.
Messages::MetaTypeInfo::XMLLoader getMetaTypeInfoXMLLoader () const
Obtain the loader for the message type.
virtual void establishedConnection ()
Notification that a valid connection to a data source/sink has been made.
virtual void acquireExternalMessage (ACE_Message_Block *data)
Acquire a message from an external source.
Public Member Functions inherited from SideCar::IO::Task
Task (bool usingData=false)
Constructor.
~Task ()
Destructor.
const std::string & getTaskName () const
Obtain the name of the task.
void setTaskName (const std::string &taskName)
Set the task's internal name.
boost::weak_ptr< Stream > getStream () const
Obtain the stream to which this task belongs.
void setStream (const boost::shared_ptr< Stream > &stream)
Set the Stream object in which this Task object resides.
bool putInChannel (const Messages::Header::Ref &msg, size_t channel)
Place a given message into this Tasks's input processing queue.
int put (ACE_Message_Block *data, ACE_Time_Value *timeout=0) override
Override of ACE_Task method.
void setError (const std::string &text, bool force=false)
Record an error message.
const std::string & getError () const
Fetch the current error text.
void clearError ()
Clear the held error text.
bool hasError () const
Determine if the task has an error posted.
bool registerParameter (const Parameter::Ref &property)
Register a configurable parameter with the controller.
bool unregisterParameter (const Parameter::Ref &property)
Unregister a configurable parameter with the controller.
bool hasChangedParameters () const
Determine if this task has any parameter objects that have values that differ from their startup configuration.
ProcessingState::Value getProcessingState () const
Obtain the current processing state indicator.
bool isActive () const
Determine if the task is in a message processing state.
bool isInCalibrationState () const
Determine if the task is in the calibration state.
bool isInRunState () const
Determine if the task is in the run state.
bool isInStopState () const
Determine if the task is in the stop state.
const Stats & getInputStats (size_t channelIndex) const
Obtain a read-only reference to the message Stats object for this Task object.
void updateInputStats (size_t channelIndex, size_t byteCount, uint32_t sequenceCounter)
Update internal processing statistics using values from the latest message received by the task.
void setTaskIndex (size_t taskIndex)
Set the unique ID for this task.
size_t getTaskIndex () const
Obtain the unique ID for this task.
void addInputChannel (const Channel &channel)
Add an input channel to the task.
void addOutputChannel (const Channel &channel)
Add an input channel to the task.
const ChannelVector & getInputChannels () const
Obtain an existing input channel.
size_t getNumInputChannels () const
Obtain the number of input channels defined for this task.
const Channel & getInputChannel (size_t index)
Obtain a specific input channel defined for this task.
size_t getInputChannelIndex (const std::string &name)
Obtain the index of an input channel with a given name.
const ChannelVector & getOutputChannels () const
Obtain an existing output channel.
size_t getNumOutputChannels () const
Obtain the number of output channels defined for this task.
const Channel & getOutputChannel (size_t index)
Obtain a specific output channel defined for this task.
size_t getOutputChannelIndex (const std::string &name)
Obtain the index of an output channel with a given name.
void getCurrentParameters (XmlRpc::XmlRpcValue &value) const
Obtain an XML-RPC definition of the current runtime parameter values.
void getChangedParameters (XmlRpc::XmlRpcValue &value) const
Obtain an XML-RPC definition of all changed runtime parameter values, those with values different from that found in the configuration file or at initialization time.
virtual const char * getStatusClassName () const
Obtain the status class name for this class.
virtual size_t getStatusSize () const
Obtain the number of slots in the TaskStatus XML status object.
virtual void fillStatus (StatusBase &status)
Obtain status information from the task.
bool isUsingData () const
Obtain the current usingData_ setting.
void updateUsingDataValue ()
Update this object's usingData_ value.
virtual void setUsingData (bool value)
Set a new usingData_ value.
virtual bool calculateUsingDataValue () const
Obtain a desired usingData_ value depending on othe Task settings, such as recipient usingData_ values, the alwaysUsingData_ parameter, and the current processing state.
void setThreadParams (const ThreadParams &threadParams)
Set the thread parameters that the task will use in its activateThreads() call.
const ThreadParams & getThreadParams () const
Obtain the current thread parameter settings.
bool activateThreads (int count)
Spawn count threads that will each run in the task's svc() method, which derived classes must define (see ACE_Task::svc()).
Static Public Member Functions
static Logger::Log & Log ()
Log device for objects of this type.
static Ref Make ()
Factory method for creating new TCPDataSubscriber objects.
Static Public Member Functions inherited from SideCar::IO::DataSubscriber
static Logger::Log & Log ()
Log device for objects of this type.
Static Public Member Functions inherited from SideCar::IO::IOTask
static Logger::Log & Log ()
Static Public Member Functions inherited from SideCar::IO::Task
static Logger::Log & Log ()
Obtain the log device for objects of this class.
Static Public Member Functions inherited from SideCar::IO::ZeroconfTypes::TZCType< id >
static const char * GetZeroconfType ()
Obtain the configured Zeroconf type for objects derived from this class.
static const char * GetTwinZeroconfType ()
Obtain the "twin" Zeroconf type for objects derived from this class.
static std::string MakeZeroconfType (const std::string &subType)
Construct a valid SideCar Zeroconf type string for a given subtype.
static std::string MakeTwinZeroconfType (const std::string &subType)
Construct the twin SideCar Zeroconf type string for a given subtype.
Static Public Member Functions inherited from SideCar::IO::ZeroconfRegistry
static const char * GetType (ID id)
Obtain the Zeroconf type string for a given ID.
static ID GetTwin (ID id)
Locate the twin of this ID.
static std::string MakeZeroconfType (const char *type, const std::string &subType)
Construct a valid SideCar Zeroconf type string for a type and a subtype.
Protected Member Functions
TCPDataSubscriber ()
Constructor.
void setServiceName (const std::string &serviceName)
Set the name of the publisher we are subscribed to.
Protected Member Functions inherited from SideCar::IO::DataSubscriber
DataSubscriber ()
Constructor.
bool doProcessingStateChange (const ProcessingStateChangeRequest &msg) override
Override of Task::doProcessingStateChange method.
int handle_timeout (const ACE_Time_Value &duration, const void *arg) override
Override of ACE_Event_Handler method.
Protected Member Functions inherited from SideCar::IO::IOTask
IOTask (const Messages::MetaTypeInfo *metaType=0)
Constructor for derived classes.
void setMetaTypeInfoKeyName (const std::string &keyName)
Install the MetaTypeInfo object to use.
Protected Member Functions inherited from SideCar::IO::Task
bool enterProcessingState (ProcessingState::Value state)
Change the tasks processing state indicator.
bool enterLastProcessingState ()
Change to the last non-failure processing state.
virtual bool enterInitializeState ()
Processor for the transition into the initialize state.
virtual bool enterAutoDiagnosticsState ()
Processor for the transition into the auto-diagnostic state.
virtual bool enterCalibrateState ()
Processor for the transition into the calibrate state.
virtual bool enterRunState ()
Processor for the transition into the run state.
virtual bool enterStopState ()
Processor for the transition into the stop state.
virtual bool enterFailureState ()
Processor for the transition into the failure state.
void resetProcessedStats ()
Reset the processed counters.
virtual bool deliverControlMessage (ACE_Message_Block *data, ACE_Time_Value *timeout)
Give a control message to the task.
bool processMessage (ACE_Message_Block *data)
Process a message, data or control.
virtual bool processDataMessage (ACE_Message_Block *data)
Process a data message.
virtual bool doTimeout ()
Process a timeout expired control message.
virtual bool processControlMessage (ACE_Message_Block *data)
Process a control message.
virtual bool doParametersChange (const ParametersChangeRequest &request)
Process runtime parameter changes from an XML-RPC request.
virtual bool doRecordingStateChange (const RecordingStateChangeRequest &request)
Respond to a recording state change meessage.
virtual bool doShutdownRequest ()
Respond to a SHUTDOOWN control meessage.
virtual bool doClearStatsRequest ()
Respond to a ClearStatsRequest control messsage.
void setConnectionInfo (const std::string &connectionInfo)
Set the status text that represents the connection information for the task.
virtual bool send (const Messages::Header::Ref &msg, size_t channelIndex)
bool sendManaged (MessageManager &mgr, size_t channelIndex)
Detailed Description
Definition at line 15 of file TCPDataSubscriber.h.
Constructor & Destructor Documentation
TCPDataSubscriber::TCPDataSubscriber () protected
Constructor.
Does nothing – like most ACE classes, all initialization is done in the init and open methods.
Definition at line 24 of file TCPDataSubscriber.cc.
References Log(), and LOGINFO.
Member Function Documentation
Logger::Log & TCPDataSubscriber::Log () static
Log device for objects of this type.
Returns
log device
Definition at line 10 of file TCPDataSubscriber.cc.
References Logger::Log::Find().
Referenced by openAndInit(), setServiceName(), and TCPDataSubscriber().
TCPDataSubscriber::Ref TCPDataSubscriber::Make () static
Factory method for creating new TCPDataSubscriber objects.
Returns
reference to new TCPDataSubscriber object
Definition at line 18 of file TCPDataSubscriber.cc.
bool TCPDataSubscriber::openAndInit (const std::string & key, const std::string & serviceName, int bufferSize = 0, int interface = 0)
Prepare to subscribe to a data publisher with a given service name.
Starts a Zeroconf::Browser to watch for DataPublisher objects bearing the service name. Only after a DataPublisher object is found and resolved is the ClientSocketReaderTask::open() method invoked.
Parameters
key message type key of data coming in
serviceName Zeroconf name of service publishing the data
\return true if successful, false otherwise
Definition at line 32 of file TCPDataSubscriber.cc.
References SideCar::IO::DataSubscriber::close(), SideCar::IO::TCPConnector::close(), SideCar::IO::Task::getTaskName(), Log(), LOGDEBUG, LOGINFO, SideCar::IO::ZeroconfTypes::TZCType< id >::MakeTwinZeroconfType(), SideCar::IO::DataSubscriber::openAndInit(), SideCar::IO::Task::setError(), and SideCar::IO::IOTask::setMetaTypeInfoKeyName().
void TCPDataSubscriber::setServiceName (const std::string & serviceName) protected virtual
Set the name of the publisher we are subscribed to.
Parameters
serviceName the name of the publisher
Reimplemented from SideCar::IO::DataSubscriber.
Definition at line 67 of file TCPDataSubscriber.cc.
References SideCar::IO::TCPConnector::close(), SideCar::Zeroconf::ResolvedEntry::getHost(), SideCar::Zeroconf::ResolvedEntry::getPort(), SideCar::IO::Task::getTaskName(), Log(), LOGERROR, LOGINFO, SideCar::IO::TCPConnector::openAndInit(), SideCar::IO::Task::setConnectionInfo(), SideCar::IO::Task::setError(), SideCar::IO::DataSubscriber::setServiceName(), and SideCar::IO::Task::setTaskName().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/TCPDataSubscriber.h
/Users/howes/src/sidecar/IO/TCPDataSubscriber.cc