SideCar: Utils::Exception Class Reference
Utils::Exception Class Reference
Base exception class.
#include </Users/howes/src/sidecar/Utils/Exception.h>
Public Member Functions
Exception () throw ()
Default constructor.
Exception (const char *err) throw (std::invalid_argument)
Constructor.
Exception (const std::string &err) throw ()
Constructor.
Exception (const Exception &rhs) throw ()
Copy constructor.
virtual ~Exception () throw ()
Destructor.
Exception & operator= (const Exception &rhs) throw ()
Assignment operator.
const std::string & err () const throw ()
Accessor for the error text of the exception.
virtual const char * what () const throw ()
Override of std::exception method.
template<typename T >
void append (const T &value)
Append a value to the exception text.
Detailed Description
Base exception class.
Nothing too special about this over the stock C++ exception class, except that it does have the wonderful ability to accumulate error information via the append() method.
Definition at line 24 of file Exception.h.
Constructor & Destructor Documentation
Exception::Exception (const char * err) throw (std::invalid_argument)
Constructor.
Parameters
err C character string to use as the start of the error. Throws exception if NULL pointer is passed in. text.
Definition at line 5 of file Exception.cc.
Utils::Exception::Exception (const std::string & err) throw () inline
Constructor.
Parameters
err C++ string to use as the start of the error text.
Definition at line 43 of file Exception.h.
Exception::Exception (const Exception & rhs) throw ()
Copy constructor.
Seeds the output formatter with the value from the given instance.
Parameters
rhs instance to copy from
Definition at line 13 of file Exception.cc.
Exception::~Exception () throw () virtual
Destructor.
Dispose of any active ostringstream object.
Definition at line 21 of file Exception.cc.
Member Function Documentation
template<typename T > void Utils::Exception::append (const T & value) inline
Append a value to the exception text.
Parameters
value data to write to exception data capture stream
Definition at line 79 of file Exception.h.
const std::string & Exception::err () const throw ()
Accessor for the error text of the exception.
Returns
error text
Definition at line 49 of file Exception.cc.
Referenced by Logger::Configurator::ConfiguratorException< MissingNumVersions >::ConfiguratorException(), Logger::Log::GetNames(), SideCar::IO::RecordIndex::RecordIndex(), SideCar::IO::TimeIndex::TimeIndex(), what(), and Announcer::~Announcer().
Exception & Exception::operator= (const Exception & rhs) throw ()
Assignment operator.
Parameters
rhs value to copy from
Returns
reference to self
Definition at line 27 of file Exception.cc.
Referenced by Threading::Mutex::getMutexID(), and Threading::Thread::isActive().
const char * Exception::what () const throw () virtual
Override of std::exception method.
Takes error text from formatted string stream.
Returns
error text
Definition at line 62 of file Exception.cc.
References err().
Referenced by Args::Args(), and SideCar::IO::Task::doParametersChange().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Utils/Exception.h
/Users/howes/src/sidecar/Utils/Exception.cc