SideCar: SideCar::GUI::AScope::ChannelConnection Class Reference
SideCar::GUI::AScope::ChannelConnection Class Reference
Instances represent a link between an AScope Visualizer and a VideoChannel.
#include </Users/howes/src/sidecar/GUI/AScope/ChannelConnection.h>
Public Slots
void setVisible (bool state)
Change the visibility state of the connetion.
void setShowPeakBars (bool state)
void setFrozen (bool state)
Change the frozen state of the connetion.
void setColor (const QColor &color)
Signals
void redisplay ()
Public Member Functions
ChannelConnection (Visualizer &visualizer, VideoChannel &channel, bool visible, bool showPeakBars)
Constructor.
~ChannelConnection ()
Destructor.
VideoChannel & getChannel () const
Obtain the video channel associated with the connection.
Visualizer & getVisualizer () const
Obtain the visualizer associated with the connection.
bool isVisible () const
Obtain the visibility state of the channel.
bool isShowingPeakBars () const
Determine if peak bars are shown for this channel connection.
bool isReallyShowingPeakBars () const
bool isFrozen () const
Obtain the frozen state of the channel.
bool isReallyFrozen () const
const QColor & getColor () const
int getHistorySlot () const
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for instances of this class.
Friends
class Visualizer
Detailed Description
Instances represent a link between an AScope Visualizer and a VideoChannel.
More than one Visualizer may have a connection to the same VideoChannel object. A channel connection may be frozen so that future updates from the video channel have no effect on the Visualizer.
Definition at line 24 of file ChannelConnection.h.
Constructor & Destructor Documentation
ChannelConnection::ChannelConnection (Visualizer & visualizer, VideoChannel & channel, bool visible, bool showPeakBars)
Constructor.
Connect signal/slots between two Plotter and VideoChannel objects.
Parameters
visualizer Visualizer object to connect
channel VideoChannel object to connect
Definition at line 19 of file ChannelConnection.cc.
ChannelConnection::~ChannelConnection ()
Destructor.
Drops the link with the VideoChannel.
Definition at line 35 of file ChannelConnection.cc.
References SideCar::GUI::AScope::VideoChannel::displayDropped(), Log(), and LOGINFO.
Member Function Documentation
VideoChannel& SideCar::GUI::AScope::ChannelConnection::getChannel () const inline
Obtain the video channel associated with the connection.
Returns
VideoChannel reference
Definition at line 52 of file ChannelConnection.h.
Referenced by SideCar::GUI::AScope::ChannelConnectionView::ChannelConnectionView(), SideCar::GUI::AScope::ChannelConnectionModel::data(), and SideCar::GUI::AScope::Visualizer::Visualizer().
Visualizer& SideCar::GUI::AScope::ChannelConnection::getVisualizer () const inline
Obtain the visualizer associated with the connection.
This is the object that is responsible for rendering the channel data.
Returns
Visualizer reference
Definition at line 59 of file ChannelConnection.h.
bool SideCar::GUI::AScope::ChannelConnection::isFrozen () const inline
Obtain the frozen state of the channel.
Returns
true if frozen
Definition at line 80 of file ChannelConnection.h.
Referenced by SideCar::GUI::AScope::ChannelConnectionModel::data().
bool SideCar::GUI::AScope::ChannelConnection::isShowingPeakBars () const inline
Determine if peak bars are shown for this channel connection.
Combines the channel-specific setting with the setting from the global PeakBarSettings object.
Returns
Definition at line 72 of file ChannelConnection.h.
Referenced by SideCar::GUI::AScope::ChannelConnectionView::ChannelConnectionView(), SideCar::GUI::AScope::ChannelConnectionModel::data(), and SideCar::GUI::AScope::Visualizer::Visualizer().
bool SideCar::GUI::AScope::ChannelConnection::isVisible () const inline
Obtain the visibility state of the channel.
Returns
true if visible
Definition at line 65 of file ChannelConnection.h.
Referenced by SideCar::GUI::AScope::ChannelConnectionView::ChannelConnectionView(), SideCar::GUI::AScope::ChannelConnectionModel::data(), and SideCar::GUI::AScope::Visualizer::Visualizer().
Logger::Log & ChannelConnection::Log () static
Obtain the log device for instances of this class.
Returns
log device
Definition at line 13 of file ChannelConnection.cc.
References Logger::Log::Find().
Referenced by ~ChannelConnection().
void ChannelConnection::setFrozen (bool state) slot
Change the frozen state of the connetion.
Parameters
state new frozen state
Definition at line 61 of file ChannelConnection.cc.
References SideCar::GUI::AScope::VideoChannel::setColor().
Referenced by SideCar::GUI::AScope::ChannelConnectionModel::setData().
void ChannelConnection::setVisible (bool state) slot
Change the visibility state of the connetion.
Parameters
state new visibility state
Definition at line 43 of file ChannelConnection.cc.
Referenced by SideCar::GUI::AScope::ChannelConnectionView::ChannelConnectionView(), and SideCar::GUI::AScope::ChannelConnectionModel::setData().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/AScope/ChannelConnection.h
/Users/howes/src/sidecar/GUI/AScope/ChannelConnection.cc