SideCar: SideCar::Algorithms::RemoteControllerBase Class Reference
SideCar::Algorithms::RemoteControllerBase Class Reference abstract
An XML-RPC remote controller abstract base class.
#include </Users/howes/src/sidecar/Algorithms/RemoteControllerBase.h>
Public Types
using ZCPublisherRef = boost::shared_ptr< Zeroconf::Publisher >
Public Member Functions
RemoteControllerBase (const char *zerconfType)
Constructor.
~RemoteControllerBase ()
Destructor.
bool start (const std::string &serviceName, long threadFlags=THR_NEW_LWP|THR_JOINABLE|THR_INHERIT_SCHED, long priority=ACE_DEFAULT_THREAD_PRIORITY)
Start the remote controller.
bool stop ()
Stop the remote controller.
int close (u_long flags=0) override
Shutdown the controller if it is running.
Static Public Member Functions
static Logger::Log & Log ()
Log device for objects of this type.
Protected Member Functions
virtual void installServices (XmlRpc::XmlRpcServer *server)=0
Install the XML-RPC event handlers.
virtual void serviceNameChanged (const std::string &name)
Notification from the Zeroconf connection publisher that our name changed due to a conflict.
Detailed Description
An XML-RPC remote controller abstract base class.
Allows an XML-RPC server to run within the ACE framework. Derived classes must define an installServices() method to install handlers for external XML-RPC requests.
Definition at line 22 of file RemoteControllerBase.h.
Constructor & Destructor Documentation
RemoteControllerBase::RemoteControllerBase (const char * zerconfType)
Constructor.
Parameters
zeroconfType identifier to use to identify the service in mDNS
Definition at line 27 of file RemoteControllerBase.cc.
References Log(), and LOGINFO.
RemoteControllerBase::~RemoteControllerBase ()
Destructor.
Here only to emit a log message.
Definition at line 34 of file RemoteControllerBase.cc.
References Log(), and LOGINFO.
Member Function Documentation
int RemoteControllerBase::close (u_long flags = 0) override
Shutdown the controller if it is running.
Override of ACE_Task method.
Parameters
flags indication if task is being closed by a module (non-zero)
Returns
0 if successful, -1 otherwise
Definition at line 41 of file RemoteControllerBase.cc.
References Log(), LOGERROR, LOGINFO, and stop().
virtual void SideCar::Algorithms::RemoteControllerBase::installServices (XmlRpc::XmlRpcServer * server) protected pure virtual
Install the XML-RPC event handlers.
Derived classes must define.
Parameters
server the XML-RPC server to install into
Referenced by start().
Logger::Log & RemoteControllerBase::Log () static
Log device for objects of this type.
Returns
log device
Definition at line 21 of file RemoteControllerBase.cc.
References Logger::Log::Find().
Referenced by close(), RemoteControllerBase(), start(), stop(), and ~RemoteControllerBase().
virtual void SideCar::Algorithms::RemoteControllerBase::serviceNameChanged (const std::string & name) inline protected virtual
Notification from the Zeroconf connection publisher that our name changed due to a conflict.
Derived classes may override to receive this notification.
Parameters
name the new service name
Definition at line 84 of file RemoteControllerBase.h.
Referenced by start().
bool RemoteControllerBase::start (const std::string & serviceName, long threadFlags = THR_NEW_LWP | THR_JOINABLE | THR_INHERIT_SCHED, long priority = ACE_DEFAULT_THREAD_PRIORITY)
Start the remote controller.
Creates a new XML-RPC server, registers remote methods with the server, and then creates a new Zeroconf::Publisher to announce the availability of the XML-RPC server. Spawns a new thread that gives time to the XML-RPC server. The thread runs the method svc().
Parameters
name of the Zeroconf service to publish under
\return true if successful, false otherwise
Definition at line 56 of file RemoteControllerBase.cc.
References installServices(), Log(), LOGERROR, LOGFATAL, LOGINFO, and serviceNameChanged().
bool RemoteControllerBase::stop ()
Stop the remote controller.
Signals the XML-RPC processing thread to stop, then waits for the thread to exit. After the thread has terminated, the routine stops and disposes of the Zeroconf::Publisher object, and then deletes the XML-RPC server.
Returns
true if successful, false otherwise
Definition at line 132 of file RemoteControllerBase.cc.
References Log(), LOGDEBUG, LOGERROR, and LOGINFO.
Referenced by close().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/RemoteControllerBase.h
/Users/howes/src/sidecar/Algorithms/RemoteControllerBase.cc