SideCar: SideCar::IO::WriterDevices::File Class Reference
SideCar::IO::WriterDevices::File Class Reference
Device that writes to a file.
#include </Users/howes/src/sidecar/IO/Writers.h>
Public Member Functions
File ()
Constructor for new device.
ACE_FILE_IO & getDevice ()
Obtain reference to ACE file device.
const ACE_FILE_IO & getDevice () const
Obtain reference to ACE file device.
Protected Member Functions
ssize_t writeToDevice (const iovec *iov, int count)
Send data to the device.
Detailed Description
Device that writes to a file.
Definition at line 34 of file Writers.h.
Member Function Documentation
ACE_FILE_IO& SideCar::IO::WriterDevices::File::getDevice () inline
Obtain reference to ACE file device.
Returns
file device
Definition at line 46 of file Writers.h.
Referenced by SideCar::IO::FileWriterTask::openAndInit(), SideCar::Algorithms::Recorder::start(), SideCar::Algorithms::Recorder::stop(), and SideCar::IO::FileWriterTask::svc().
const ACE_FILE_IO& SideCar::IO::WriterDevices::File::getDevice () const inline
Obtain reference to ACE file device.
Returns
file device
Definition at line 52 of file Writers.h.
ssize_t SideCar::IO::WriterDevices::File::writeToDevice (const iovec * iov, int count) inline protected
Send data to the device.
Parameters
iov address of first iovec structure to use
count number of iovec structures to process
Returns
number of bytes successfully written to device, or -1 if error
Definition at line 64 of file Writers.h.
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/IO/Writers.h