SideCar: SideCar::Configuration::Loader Class Reference
SideCar::Configuration::Loader Class Reference
Configuration file loader.
#include </Users/howes/src/sidecar/Configuration/Loader.h>
Data Structures
struct Private
Private implementation class the performs the work for the Loader class.
Public Types
enum LoadResult {
kOK = 0, kFailedFileOpen, kFailedXMLParse, kMissingEntityNode,
kMissingSidecarNode, kMissingRadarNode, kInvalidRadarNode, kMissingDPNode,
kMissingStreams, kMissingRunners, kNotLoaded
}
Result codes from the last load() operation.
using RunnerConfigList = QList< RunnerConfig * >
Container type for the list of RunnerConfig objects.
Public Member Functions
Loader ()
Constructor.
~Loader ()
Destructor.
bool load (const QString &configurationPath)
Attempt to load a SideCar configuration file.
bool isLoaded () const
Determine if a configuration file has been successfully loaded.
QStringList getIncludePaths () const
Obtain a list of file paths that were given in 'file' attributes in the <radar> and/or <runner> entities.
QStringList getHostNames () const
Obtain a list of host names found in <runner> entity 'host' attributes.
LoadResult getLastLoadResult () const
Obtain the result of the last load operation.
RunnerConfig * getRunnerConfig (const QString &name) const
Obtain a RunnerConfig with a given name.
RunnerConfig * getRunnerConfig (size_t index) const
Obtain a RunnerConfig by its position in the configuration file.
size_t getNumRunnerConfigs () const
Obtain the number of RunnerConfig objects defined by the loaded configuration file.
const RunnerConfigList & getRunnerConfigs () const
Obtain a read-only reference to the list of loaded RunnerConfig objects.
QString getParseFilePath () const
Obtain the full path of the file that the Qt XML library failed to parse.
QString getParseErrorInfo (int &line, int &column) const
Obtain parse error information returned by the Qt XML library.
QString getConfigurationPath () const
Obtain the full path of the file given in the last call to load().
QString getConfigurationName () const
Obtain the name of the configuration represented by the configuration file.
QString getLogsDirectory () const
Obtain the log directory value found in 'logDirectory.
QString getRecordingsDirectory () const
Obtain the directory where new recordings will reside.
QString getLoggerConfiguration () const
Obtain the file to give to Logger::ConfiguratorFile to configure Logger::Log devices.
Detailed Description
Configuration file loader.
Reads in a SideCar configuration file, and parses <radar> and <runner> entity tags. For the former, it parses the <radar> children and initializes a Messages::RadarConfig instance with the children values. For the <runner> entities, it creates an instance of the RunnerConfig class to store the <runner> attributes and to hold the XML DOM node that contains one or more <stream> entities.
Uses the Qt XML library (QtXml) to parse the whole configuration file.
Definition at line 23 of file Loader.h.
Member Enumeration Documentation
enum SideCar::Configuration::Loader::LoadResult
Result codes from the last load() operation.
Obtained from getLastLoadResult().
Enumerator
kOK
The load succeeded.
kFailedFileOpen
Unable to open the configuration file.
kFailedXMLParse
Failed to parse the configuration file.
kMissingEntityNode
Missing a required/expected entity node.
kMissingSidecarNode
Missing a <sidecar> entity node.
kMissingRadarNode
Missing a <radar> entity node.
kInvalidRadarNode
Invalid <radar> entity node.
kMissingDPNode
Missing a <dp> entity node.
kMissingStreams
Missing a <stream> entity node.
kMissingRunners
Missing a <runner> entity node.
kNotLoaded
The load() method has not been called.
Definition at line 33 of file Loader.h.
Constructor & Destructor Documentation
Loader::Loader ()
Constructor.
Intializes instance but does nothing else.
Definition at line 394 of file Loader.cc.
Loader::~Loader ()
Destructor.
Necessary to allow incomplete boost::scoped_ptr below.
Definition at line 400 of file Loader.cc.
Member Function Documentation
QString Loader::getConfigurationName () const
Obtain the name of the configuration represented by the configuration file.
Returns
base name of the configuration file without extension
Definition at line 462 of file Loader.cc.
Referenced by isLoaded(), SideCar::GUI::Master::ConfigurationInfo::load(), SideCar::GUI::Master::ConfigurationInfo::lostRunner(), and SideCar::GUI::Master::ConfigurationInfo::startup().
QString Loader::getConfigurationPath () const
Obtain the full path of the file given in the last call to load().
Returns
the configuration file path
Definition at line 456 of file Loader.cc.
Referenced by isLoaded(), and SideCar::Configuration::RunnerConfig::RunnerConfig().
QStringList Loader::getHostNames () const
Obtain a list of host names found in <runner> entity 'host' attributes.
This is the list of hosts that will run remote runner processes.
Returns
list of host names (must not be empty)
Definition at line 492 of file Loader.cc.
Referenced by isLoaded().
QStringList Loader::getIncludePaths () const
Obtain a list of file paths that were given in 'file' attributes in the <radar> and/or <runner> entities.
Returns
list of file paths (may be empty)
Definition at line 486 of file Loader.cc.
Referenced by isLoaded().
Loader::LoadResult Loader::getLastLoadResult () const
Obtain the result of the last load operation.
Returns
LoadResult code
Definition at line 412 of file Loader.cc.
Referenced by SideCar::Runner::App::App(), isLoaded(), and SideCar::GUI::Master::ConfigurationInfo::load().
QString Loader::getLoggerConfiguration () const
Obtain the file to give to Logger::ConfiguratorFile to configure Logger::Log devices.
Returns
file path
Definition at line 468 of file Loader.cc.
Referenced by isLoaded().
QString Loader::getLogsDirectory () const
Obtain the log directory value found in 'logDirectory.
Returns
log directory path
Definition at line 474 of file Loader.cc.
Referenced by isLoaded(), and SideCar::Configuration::RunnerConfig::RunnerConfig().
size_t Loader::getNumRunnerConfigs () const
Obtain the number of RunnerConfig objects defined by the loaded configuration file.
Only valid if isLoaded() returns true.
Returns
number defined RunnerConfig objects
Definition at line 424 of file Loader.cc.
Referenced by isLoaded(), SideCar::GUI::Master::Launcher::Launcher(), SideCar::GUI::Master::ConfigurationInfo::load(), and SideCar::GUI::Master::Launcher::start().
QString Loader::getParseErrorInfo (int & line, int & column) const
Obtain parse error information returned by the Qt XML library.
Only valid if getLastLoadResult() is kFailedXMLParse.
Parameters
line the number of the line where the parse failed
column the column of line where the parse failed
Returns
error text from the XML library
Definition at line 448 of file Loader.cc.
Referenced by isLoaded(), and SideCar::GUI::Master::ConfigurationInfo::load().
QString Loader::getParseFilePath () const
Obtain the full path of the file that the Qt XML library failed to parse.
This may not be the configuration file; it could be an include file found in a <radar> or <runner> entity.
Returns
file path
Definition at line 442 of file Loader.cc.
Referenced by isLoaded(), and SideCar::GUI::Master::ConfigurationInfo::load().
QString Loader::getRecordingsDirectory () const
Obtain the directory where new recordings will reside.
Returns
recording directory path
Definition at line 480 of file Loader.cc.
Referenced by SideCar::GUI::Master::ConfigurationInfo::hasValidRecordingDirectory(), isLoaded(), and SideCar::GUI::Master::ConfigurationInfo::load().
RunnerConfig * Loader::getRunnerConfig (const QString & name) const
Obtain a RunnerConfig with a given name.
Each RunnerConfig has a name that was found in the 'name' attribute of a <runner> entity.
Parameters
name the name of the RunnerConfig to locate
Returns
found RunnerConfig object, ur NULL
Definition at line 430 of file Loader.cc.
Referenced by SideCar::Runner::App::App(), SideCar::GUI::Master::ConfigurationInfo::foundRunner(), isLoaded(), SideCar::GUI::Master::ConfigurationInfo::lostRunner(), SideCar::GUI::Master::Launcher::start(), and SideCar::GUI::Master::ConfigurationInfo::startup().
RunnerConfig * Loader::getRunnerConfig (size_t index) const
Obtain a RunnerConfig by its position in the configuration file.
Parameters
index position of the RunnerConfig to fetch. Must be less than getNumRunnerConfigs().
Returns
found RunnerConfig object, or NULL
Definition at line 436 of file Loader.cc.
const Loader::RunnerConfigList & Loader::getRunnerConfigs () const
Obtain a read-only reference to the list of loaded RunnerConfig objects.
Returns
reference to RunnerConfig list
Definition at line 418 of file Loader.cc.
Referenced by isLoaded().
bool SideCar::Configuration::Loader::isLoaded () const inline
Determine if a configuration file has been successfully loaded.
Returns
true if so
Definition at line 67 of file Loader.h.
References getConfigurationName(), getConfigurationPath(), getHostNames(), getIncludePaths(), getLastLoadResult(), getLoggerConfiguration(), getLogsDirectory(), getNumRunnerConfigs(), getParseErrorInfo(), getParseFilePath(), getRecordingsDirectory(), getRunnerConfig(), getRunnerConfigs(), and kOK.
bool Loader::load (const QString & configurationPath)
Attempt to load a SideCar configuration file.
Parameters
configurationPath location of the file
Returns
true if successful
Definition at line 406 of file Loader.cc.
Referenced by SideCar::Runner::App::App(), and SideCar::GUI::Master::ConfigurationInfo::load().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Configuration/Loader.h
/Users/howes/src/sidecar/Configuration/Loader.cc