SideCar: Logger::ConfiguratorFile Class Reference
Logger::ConfiguratorFile Class Reference
Derivation of Configurator that takes configuration settings from a file.
#include </Users/howes/src/sidecar/Logger/ConfiguratorFile.h>
Data Structures
struct CannotAccessConfigFile
Exception thrown if unable to access (see) the configuration file.
struct CannotOpenConfigFile
Exception thrown if unable to open a configuration file.
Public Member Functions
ConfiguratorFile (const std::string &path)
Constructor.
~ConfiguratorFile ()
Destructor.
void reload ()
Reread the configuration settings and update all managed Log objects.
time_t getModificationTime () const
Obtain the system's modification time for the configuration file.
bool isStale () const
Check if configuration file is newer than when it was last read in.
void check ()
See if configuration file has changed, and if so reload its contents.
void startMonitor (double period)
Spawn a new thread that will periodically check to see if the configuration file has changed, and if so it will reload it.
void stopMonitor ()
Stop a previously-started monitor.
Public Member Functions inherited from Logger::Configurator
Configurator ()
Default constructor.
Configurator (std::istream &is)
Constructor.
void load (std::istream &is)
Read configuration settings from a stream.
Additional Inherited Members
Protected Member Functions inherited from Logger::Configurator
const std::set< Log * > & managed () const
Accessor for the set of Log objects created by Configurator::load.
Detailed Description
Derivation of Configurator that takes configuration settings from a file.
Supports configuration reloading and detection of changed configuration files. For information on the configuration file format, see Configurator.
Definition at line 18 of file ConfiguratorFile.h.
Constructor & Destructor Documentation
ConfiguratorFile::ConfiguratorFile (const std::string & path)
Constructor.
Use configuration settings found in a file.
Parameters
path location of file to use
Definition at line 21 of file ConfiguratorFile.cc.
References reload().
ConfiguratorFile::~ConfiguratorFile ()
Destructor.
Stop monitor thread if active.
Definition at line 27 of file ConfiguratorFile.cc.
References stopMonitor().
Member Function Documentation
time_t ConfiguratorFile::getModificationTime () const
Obtain the system's modification time for the configuration file.
Returns
time when file was last modified
Definition at line 64 of file ConfiguratorFile.cc.
Referenced by isStale(), and reload().
bool Logger::ConfiguratorFile::isStale () const inline
Check if configuration file is newer than when it was last read in.
Returns
true if newer
Definition at line 56 of file ConfiguratorFile.h.
References getModificationTime().
Referenced by check().
void ConfiguratorFile::startMonitor (double period)
Spawn a new thread that will periodically check to see if the configuration file has changed, and if so it will reload it.
NOTE: this routine starts a new thread.
Parameters
period number of seconds to sleep between check calls
Returns
result of pthread_create call (0 is OK)
Definition at line 117 of file ConfiguratorFile.cc.
Referenced by check(), and SideCar::GUI::AppBase::setLogConfigurationFile().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Logger/ConfiguratorFile.h
/Users/howes/src/sidecar/Logger/ConfiguratorFile.cc