SideCar: SideCar::GUI::PresetsWindow Class Reference
SideCar::GUI::PresetsWindow Class Reference
Floating tool window that shows the message time for the data shown in a PPIWidget, and the range/azimuth values for the cursor.
#include </Users/howes/src/sidecar/GUI/PresetsWindow.h>
Public Member Functions
PresetsWindow (int shortcut, PresetManager *presetManager)
Constructor.
Public Member Functions inherited from SideCar::GUI::ToolWindowBase
ToolWindowBase (const QString &name, const QString &actionTitle, int shortcut=0)
Constructor.
QAction * getShowHideAction () const
Obtain the QAction object that toggles the tool window's visibility.
void setFixedSize ()
Configure the window so that the user may not resize it.
bool getInitialVisibility () const
Determine if the application should show the window at startup.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the Log device to use for PresetsWindow objects.
Static Public Member Functions inherited from SideCar::GUI::ToolWindowBase
static Logger::Log & Log ()
Log device for instances of this class.
static AppBase * getApp ()
Convenience method that obtains the AppBase singleton.
Additional Inherited Members
Public Slots inherited from SideCar::GUI::ToolWindowBase
virtual void activeMainWindowChanged (MainWindowBase *window)
virtual void applyInitialVisibility ()
virtual void toggleVisibility ()
virtual void showAndRaise ()
Protected Member Functions inherited from SideCar::GUI::ToolWindowBase
void showEvent (QShowEvent *event)
Event handler for show events.
void closeEvent (QCloseEvent *event)
Event handler for close events.
void hideEvent (QHideEvent *event)
Event handler for hide events.
Detailed Description
Floating tool window that shows the message time for the data shown in a PPIWidget, and the range/azimuth values for the cursor.
The message values may be current or historical.
Definition at line 20 of file PresetsWindow.h.
Constructor & Destructor Documentation
PresetsWindow::PresetsWindow (int shortcut, PresetManager * presetManager)
Constructor.
Creates and initializes window widgets.
Parameters
action the QAction object that controls window visibility
presetManager the PresetManager that manages the collection of active Preset objects.
Definition at line 22 of file PresetsWindow.cc.
References SideCar::GUI::PresetManager::addPreset(), SideCar::GUI::PresetManager::applyPreset(), SideCar::GUI::PresetManager::getActivePresetIndex(), SideCar::GUI::PresetManager::getPresetIsDirty(), SideCar::GUI::PresetManager::getPresetName(), SideCar::GUI::PresetManager::getPresetNames(), Log(), LOGDEBUG, LOGINFO, SideCar::GUI::PresetManager::removePreset(), SideCar::GUI::PresetManager::restorePreset(), SideCar::GUI::PresetManager::savePreset(), and SideCar::GUI::ToolWindowBase::showEvent().
Member Function Documentation
Logger::Log & PresetsWindow::Log () static
Obtain the Log device to use for PresetsWindow objects.
Returns
Log reference
Definition at line 16 of file PresetsWindow.cc.
References Logger::Log::Find().
Referenced by PresetsWindow().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/PresetsWindow.h
/Users/howes/src/sidecar/GUI/PresetsWindow.cc