SideCar: SideCar::GUI::Master::StatusCollector Class Reference
SideCar::GUI::Master::StatusCollector Class Reference
Status collector for Runner StatusEmitter objects.
#include </Users/howes/src/sidecar/GUI/Master/StatusCollector.h>
Public Types
using ZCPublisherRef = boost::shared_ptr< Zeroconf::Publisher >
Signals
void statusUpdates (const QList< QByteArray > &statusUpdates)
Signal sent out whenever a new status message is received.
Public Member Functions
StatusCollector ()
Constructor.
bool open ()
Creates a UDP socket to use to receive status data, and then publishes the UDP port number for StatusEmitters to use to when sending status data.
void close ()
Shutdown the Zeroconf publisher, and close the UDP socket.
Static Public Member Functions
static Logger::Log & Log ()
Log device for all StatusCollector objects.
static const char * GetCollectorType ()
Obtain the Zeroconf type for all Runner StatusEmitter objects associated with this StatusCollector class.
Detailed Description
Status collector for Runner StatusEmitter objects.
Accepts XML status information from a StatusEmitter that details the status of the IO::Stream and IO::Task objects owned by the Runner. Hands off incoming status data to a ServiceModel object via ServicesModel::updateStatus() method.
Definition at line 26 of file StatusCollector.h.
Constructor & Destructor Documentation
StatusCollector::StatusCollector ()
Constructor.
Parameters
model the object to notify when new status arrives.
Definition at line 23 of file StatusCollector.cc.
References GetCollectorType(), Log(), and LOGINFO.
Member Function Documentation
static const char* SideCar::GUI::Master::StatusCollector::GetCollectorType () inline static
Obtain the Zeroconf type for all Runner StatusEmitter objects associated with this StatusCollector class.
Returns
NULL-terminated C string
Definition at line 44 of file StatusCollector.h.
Referenced by SideCar::GUI::Master::MainWindow::MainWindow(), and StatusCollector().
Logger::Log & StatusCollector::Log () static
Log device for all StatusCollector objects.
Returns
log device
Definition at line 17 of file StatusCollector.cc.
References Logger::Log::Find().
Referenced by close(), open(), and StatusCollector().
bool StatusCollector::open ()
Creates a UDP socket to use to receive status data, and then publishes the UDP port number for StatusEmitters to use to when sending status data.
Returns
true if successful
Definition at line 34 of file StatusCollector.cc.
References Log(), LOGDEBUG, and LOGFATAL.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/StatusCollector.h
/Users/howes/src/sidecar/GUI/Master/StatusCollector.cc