SideCar: SideCar::Algorithms::MatchedFilterUtils::WorkRequest Class Reference
SideCar::Algorithms::MatchedFilterUtils::WorkRequest Class Reference
Collection of data values that will be used for a windowed SLC processing.
#include </Users/howes/src/sidecar/Algorithms/MatchedFilter/WorkRequest.h>
Public Member Functions
void reconfigure (VsipComplexVector *txPulseVec, int numFFTThreads, int fftSize)
Reconfigure the work request with new values.
void beginRequest (const Messages::Video::Ref &input, const Messages::Video::Ref &output, size_t offset)
Initialize a new work request.
void process ()
Perform the work on the given data.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for WorkRequest objects.
static ACE_Message_Block * Make (VsipComplexVector *txPulseVec, int numFFTThreads, int fftSize)
Create a new WorkRequest object with memory provided by an ACE_Message_Block.
static void Destroy (ACE_Message_Block *data)
Dispose of the WorkRequest object held within an ACE_Message_Block, and release the ACE_Message_Block memory.
static WorkRequest * FromMessageBlock (ACE_Message_Block *data)
Class method that returns a WorkRequest pointer from an ACE_Message_Block pointer.
Detailed Description
Collection of data values that will be used for a windowed SLC processing.
Encapsulates the values that must not change while in use by a thread.
Definition at line 24 of file WorkRequest.h.
Member Function Documentation
void WorkRequest::beginRequest (const Messages::Video::Ref & input, const Messages::Video::Ref & output, size_t offset)
Initialize a new work request.
Parameters
name the name of the algorithm
\param filterStart the first sample to filter
\param filterSpan the numbe of samples to filter
\param main the main message to process
Definition at line 103 of file WorkRequest.cc.
Referenced by SideCar::Algorithms::MatchedFilter::reset().
void WorkRequest::Destroy (ACE_Message_Block * data) static
Dispose of the WorkRequest object held within an ACE_Message_Block, and release the ACE_Message_Block memory.
Parameters
data
Definition at line 53 of file WorkRequest.cc.
References FromMessageBlock(), Log(), LOGDEBUG, LOGINFO, and reconfigure().
WorkRequest * WorkRequest::FromMessageBlock (ACE_Message_Block * data) static
Class method that returns a WorkRequest pointer from an ACE_Message_Block pointer.
Parameters
data ACE_Message_Block holding the WorkRequest data
Returns
WorkRequest pointer
Definition at line 24 of file WorkRequest.cc.
Referenced by Destroy(), and SideCar::Algorithms::MatchedFilterUtils::WorkerThreads::svc().
Logger::Log & WorkRequest::Log () static
Obtain the log device for WorkRequest objects.
Returns
Logger::Log reference
Definition at line 16 of file WorkRequest.cc.
References Logger::Log::Find().
Referenced by Destroy(), Make(), and process().
ACE_Message_Block * WorkRequest::Make (VsipComplexVector * txPulseVec, int numFFTThreads, int fftSize) static
Create a new WorkRequest object with memory provided by an ACE_Message_Block.
Parameters
enabledSize
corrSpan
Returns
Definition at line 30 of file WorkRequest.cc.
References Log().
void WorkRequest::reconfigure (VsipComplexVector * txPulseVec, int numFFTThreads, int fftSize)
Reconfigure the work request with new values.
Reallocates some VSIPL objects.
Definition at line 82 of file WorkRequest.cc.
Referenced by Destroy().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/MatchedFilter/WorkRequest.h
/Users/howes/src/sidecar/Algorithms/MatchedFilter/WorkRequest.cc