SideCar: SideCar::Messages::CircularBuffer Class Reference
SideCar::Messages::CircularBuffer Class Reference
Base class for message-specific circular buffers.
#include </Users/howes/src/sidecar/Messages/CircularBuffer.h>
Public Types
using MessageRef = Messages::PRIMessage::Ref
Public Member Functions
Messages::MetaTypeInfo::Value getType () const
Obtain the type enumeration of the messages held in the buffer.
size_t size () const
Obtain the number of messages in the buffer.
bool empty () const
Determine if the buffer is void of messages.
void clear ()
Remove all messages from the buffer.
Static Public Member Functions
static Logger::Log & Log ()
Log device used by instances.
Protected Member Functions
CircularBuffer (const Messages::MetaTypeInfo &type)
Constructor.
~CircularBuffer ()
Destructor.
void add (const MessageRef &msg)
Store a message into the buffer.
CircularBufferIterator locate (const MessageRef &msg) const
Obtain an iterator that points to the slot that contains a given message.
CircularBufferIterator newest () const
Obtain iterator to the newest element in the buffer.
CircularBufferIterator oldest () const
Obtain iterator to the oldest element in the buffer.
Static Protected Member Functions
static void Install (const std::string &name, CircularBuffer *buffer)
Class utility method that installs a new CircularBuffer into the global collection of circular buffers.
static const CircularBuffer * Get (const std::string &name, const Messages::MetaTypeInfo &typeInfo)
Class utility method that returns a previously-registered CircularBuffer object.
Friends
class CircularBufferIterator
Detailed Description
Base class for message-specific circular buffers.
A circular buffer holds a finite number of PRIMessage objects. The value obtained from the message PRIMessageInfo::getShaftEncoding() method determines where in the buffer it is stored.
This class does all of the type-neutral work. However, it prohibits creation of instances. Type-specific classes provide that functionality.
Definition at line 28 of file CircularBuffer.h.
Constructor & Destructor Documentation
CircularBuffer::CircularBuffer (const Messages::MetaTypeInfo & type) protected
Constructor.
Parameters
type type type descriptor for the messages being held
Definition at line 67 of file CircularBuffer.cc.
References SideCar::Messages::RadarConfig::GetShaftEncodingMax(), Log(), and LOGINFO.
Member Function Documentation
void CircularBuffer::add (const MessageRef & msg) protected
Store a message into the buffer.
The position where the message will be placed is determined by the value of PRIMesageInfo::getShaftEncoding().
Parameters
msg the message to store
Definition at line 93 of file CircularBuffer.cc.
References SideCar::Messages::MetaTypeInfo::Find(), SideCar::Messages::MetaTypeInfo::getName(), Log(), LOGDEBUG, LOGINFO, and Logger::ProcLog::thrower().
void CircularBuffer::clear ()
Remove all messages from the buffer.
Iterators remain valid, but they will point to an invalid reference-counted value, whose get() method will return NULL.
Definition at line 83 of file CircularBuffer.cc.
References Log(), and LOGINFO.
bool SideCar::Messages::CircularBuffer::empty () const inline
Determine if the buffer is void of messages.
Returns
true if so
Definition at line 55 of file CircularBuffer.h.
const CircularBuffer * CircularBuffer::Get (const std::string & name, const Messages::MetaTypeInfo & typeInfo) static protected
Class utility method that returns a previously-registered CircularBuffer object.
Throws an exception if the buffer does not exist, or if the buffer does not work with the given message type.
Parameters
name the name of the buffer to fetch
typeInfo the message type specification the buffer must handle
Returns
found CircularBuffer object
Definition at line 20 of file CircularBuffer.cc.
References SideCar::Messages::MetaTypeInfo::getKey(), Log(), LOGINFO, and Logger::ProcLog::thrower().
Messages::MetaTypeInfo::Value SideCar::Messages::CircularBuffer::getType () const inline
Obtain the type enumeration of the messages held in the buffer.
Returns
MetaTypeInfo enumeration value
Definition at line 43 of file CircularBuffer.h.
void CircularBuffer::Install (const std::string & name, CircularBuffer * buffer) static protected
Class utility method that installs a new CircularBuffer into the global collection of circular buffers.
Throws an error if there is already an entry registered under the given name.
Parameters
name the name to register the buffer under
buffer the object to register
Definition at line 46 of file CircularBuffer.cc.
References Log(), LOGINFO, and Logger::ProcLog::thrower().
CircularBufferIterator CircularBuffer::locate (const MessageRef & msg) const protected
Obtain an iterator that points to the slot that contains a given message.
Uses the value from PRIMessageInfo::getShaftEncoding(), but does not check that the actual messages are the same.
Parameters
msg the message to look for
Returns
iterator pointing to the message
Definition at line 146 of file CircularBuffer.cc.
References Log(), LOGDEBUG, and LOGINFO.
Logger::Log & CircularBuffer::Log () static
Log device used by instances.
Returns
log device
Definition at line 12 of file CircularBuffer.cc.
References Logger::Log::Find().
Referenced by add(), CircularBuffer(), clear(), Get(), Install(), locate(), and ~CircularBuffer().
CircularBufferIterator CircularBuffer::newest () const protected
Obtain iterator to the newest element in the buffer.
NOTE: if another thread adds to the the buffer, then this will no longer refer to the newest entry.
Returns
iterator
Definition at line 138 of file CircularBuffer.cc.
CircularBufferIterator CircularBuffer::oldest () const protected
Obtain iterator to the oldest element in the buffer.
NOTE: if another thread adds to the the buffer, then this will no longer refer to the oldest entry, and instead point to newer entries.
Returns
iterator
Definition at line 132 of file CircularBuffer.cc.
size_t SideCar::Messages::CircularBuffer::size () const inline
Obtain the number of messages in the buffer.
Returns
message count
Definition at line 49 of file CircularBuffer.h.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Messages/CircularBuffer.h
/Users/howes/src/sidecar/Messages/CircularBuffer.cc