SideCar: ByteOrder Class Reference
ByteOrder Class Reference
Class to determine and support the byte-order on a particular platform.
#include </Users/howes/src/sidecar/IO/ByteOrder.h>
Public Types
enum Type { kLittleEndian = 0, kBigEndian, kNetwork = kBigEndian }
Public Member Functions
ByteOrder ()
Constructor.
void setDecodingByteOrder (Type value)
Set the byte-order of data being read.
void setEncodingByteOrder (Type value)
Set the byte-order of data being written.
Type getDecodingByteOrder () const
Get the byte-order of data being read.
Type getEncodingByteOrder () const
Get the byte-order of data being written.
template<typename T >
void decode (T &value) const
Convert in-place a value that was read in from an external source.
template<typename T >
void encode (T &value) const
Convert in-place a value before it is written out to an external sink.
void decode (void *ptr, size_t size) const
Convert in-place a consecutive sequence of bytes that was read in from an external source.
void encode (void *ptr, size_t size) const
Convert in-place a consecutive sequence of bytes before it is written out to a sink.
Static Public Member Functions
static bool HostIsNetwork ()
Determine if the host we are running on has network (big-endian) byte-order.
Detailed Description
Class to determine and support the byte-order on a particular platform.
There are only two byte-orders currently supported: big-endian and little-endian. All of the RWSL code base should read and write data in big-endian mode, which is the same as network byte-order. Its nice that the Sun SPARC and Motorola/IBM PowerPC both operate in this mode, since those are the most common platforms we run on. However, if given an Intel, we should be able to run correctly on it.
NOTE: Only used by SideCar::GUI::PRIEmittter. Everything else should use the IO::Encoder and IO::Decoder classes, which use the ACE CDR streaming classes.
Definition at line 16 of file ByteOrder.h.
Constructor & Destructor Documentation
ByteOrder::ByteOrder () inline
Constructor.
Determine if we are little-endian and need to swap bytes.
Definition at line 48 of file ByteOrder.h.
Member Function Documentation
template<typename T > void ByteOrder::decode (T & value) const inline
Convert in-place a value that was read in from an external source.
Parameters
value read-write reference to value to convert `
Definition at line 82 of file ByteOrder.h.
References decode().
Referenced by decode(), and SideCar::GUI::PRIEmitter::MainWindow::openFile().
void ByteOrder::decode (void * ptr, size_t size) const inline
Convert in-place a consecutive sequence of bytes that was read in from an external source.
Parameters
ptr start of the sequence
size number of bytes in the sequence
Definition at line 97 of file ByteOrder.h.
template<typename T > void ByteOrder::encode (T & value) const inline
Convert in-place a value before it is written out to an external sink.
Parameters
value read-write reference to value to convert
Definition at line 89 of file ByteOrder.h.
References encode().
Referenced by encode().
void ByteOrder::encode (void * ptr, size_t size) const inline
Convert in-place a consecutive sequence of bytes before it is written out to a sink.
Parameters
ptr start of the sequence
size number of bytes in the sequence
Definition at line 105 of file ByteOrder.h.
Type ByteOrder::getDecodingByteOrder () const inline
Get the byte-order of data being read.
Returns
byte order
Definition at line 69 of file ByteOrder.h.
Type ByteOrder::getEncodingByteOrder () const inline
Get the byte-order of data being written.
Returns
byte order
Definition at line 75 of file ByteOrder.h.
static bool ByteOrder::HostIsNetwork () inline static
Determine if the host we are running on has network (big-endian) byte-order.
Returns
true if so
Definition at line 44 of file ByteOrder.h.
void ByteOrder::setDecodingByteOrder (Type value) inline
Set the byte-order of data being read.
If the value is NOT the same as the host value, then we will byte-swap incoming data.
Parameters
value new byte order setting.
Definition at line 56 of file ByteOrder.h.
void ByteOrder::setEncodingByteOrder (Type value) inline
Set the byte-order of data being written.
If the value is NOT the same as the host value, the we will byte-swap outgoing data.
Parameters
value new byte order setting
Definition at line 63 of file ByteOrder.h.
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/IO/ByteOrder.h