SideCar: Utils::Format Class Reference
Utils::Format Class Reference
Formatting settings for a C++ input or output stream.
#include </Users/howes/src/sidecar/Utils/Format.h>
Public Types
using fmtflags = std::ios_base::fmtflags
Public Member Functions
Format ()
Constructor.
Format (int precision)
Constructor.
Format (int width, int precision)
Constructor.
Format (const std::ios &s)
Constructor.
Format & flags (std::ios_base::fmtflags flags)
Set all formatting bits at once.
std::ios_base::fmtflags flags () const
Format & setf (fmtflags flags)
Turn on one or more formatting flags.
Format & setf (fmtflags flags, fmtflags mask)
Turn on one or more formatting flags, after first masking out the existing flags with a mask.
Format & unsetf (fmtflags flags)
Turn off one or more formatting flags.
Format & precision (int precision)
Set the number of digits to display after the decimal point.
int precision () const
Format & width (int width)
Set the minimum number of characters used to format a value.
int width () const
Format & fill (char fill)
Set the character to use when aligning a formatted value within a field.
char fill () const
void put (std::ios &io) const
Apply our format settings to a stream.
Format & boolalpha ()
Enable translation of boolean values into strings.
Format & noboolalpha ()
Disable translation of boolean values into strings.
Format & dec ()
Generate integer output in decimal (base 10) format.
Format & oct ()
Generate integer output in octal (base 8) format.
Format & hex ()
Generate integer output in hexadecimal (base 16) format.
Format & showbase ()
Output a prefix indicating the numeric base for integer output.
Format & noshowbase ()
Do not output a prefix indicating the numeric base for integer output.
Format & fixed ()
Generate floating-point output in fixed-point notation.
Format & scientific ()
Generate floating-point output in scientific notation.
Format & showpoint ()
Force output of a decimal-point character in floating-point output.
Format & noshowpoint ()
Do not force output of a decimal-point character in floating-point output.
Format & left ()
Adds fill characters on the right of certain generated output.
Format & right ()
Adds fill characters on the left of certain generated output.
Format & internal ()
Adds fill characters at a designated internal point in certain generated output.
Format & showpos ()
Output a `+' sign in non-negative generated numeric output.
Format & noshowpos ()
Do not output a `+' sign in non-negative generated numeric output.
Format & skipws ()
Skip leading white space before certain input operations.
Format & noskipws ()
Do not skip leading white space before certain input operations.
Format & uppercase ()
Replace certain lowercase letters with their uppercase equivalents in generated output.
Format & nouppercase ()
Do not replace certain lowercase letters with their uppercase equivalents in generated output.
template<class T >
Formatter< T > operator() (const T &v) const
Template method that returns a new Formatter instance to hold a reference to us and to a particular value to format.
Detailed Description
Formatting settings for a C++ input or output stream.
Mimics the format control capabilities of std::ios_base + std::ios (for the fill character). Allows one to define and save a specific formatting, and then apply them to values within an output stream.
int main()
{
  double d = 1234.56789;
  Utils::Format gen4(4);
  Utils::Format sci8(gen4);
  sci8.scientific().precision(8);
  // Should print out the following: 1234.57 1235 1.23456789e+03 1234.57
  //
  std::cout << d << ' ' << gen4(d) << ' ' << sci8(d) << ' ' << d << '\n';
}
Definition at line 57 of file Format.h.
Constructor & Destructor Documentation
Utils::Format::Format () inline
Constructor.
Use default values for everything.
Definition at line 64 of file Format.h.
Utils::Format::Format (int precision) inline explicit
Constructor.
Set number of digits shown after decimal point in floating-point formats.
Parameters
precision number of digits after the decimal point to display
Definition at line 70 of file Format.h.
Utils::Format::Format (int width, int precision) inline
Constructor.
Set field width for all formats, and number of digits shown after decimal point in floating-point formats.
Parameters
width number of characters to use for formatting.
precision number of digits after the decimal point to display
Definition at line 79 of file Format.h.
Utils::Format::Format (const std::ios & s) inline
Constructor.
Obtain format settings from an input or output stream.
Parameters
s stream to query for format settings
Definition at line 86 of file Format.h.
Member Function Documentation
Format& Utils::Format::boolalpha () inline
Enable translation of boolean values into strings.
Returns
self
Definition at line 174 of file Format.h.
Format& Utils::Format::dec () inline
Generate integer output in decimal (base 10) format.
Returns
self
Definition at line 186 of file Format.h.
Format& Utils::Format::fill (char fill) inline
Set the character to use when aligning a formatted value within a field.
Parameters
fill character to use
Returns
self
Definition at line 158 of file Format.h.
References fill().
Referenced by Utils::dashLine::dashLine(), PRIInfoInputTask::deliverDataMessage(), and fill().
char Utils::Format::fill () const inline
Returns
current fill character.
Definition at line 162 of file Format.h.
Format& Utils::Format::fixed () inline
Generate floating-point output in fixed-point notation.
Returns
self
Definition at line 216 of file Format.h.
Referenced by PRIInfoInputTask::deliverDataMessage().
Format& Utils::Format::flags (std::ios_base::fmtflags flags) inline
Set all formatting bits at once.
Parameters
flags value to use for the formatting bits
Returns
self
Definition at line 95 of file Format.h.
References flags().
Referenced by flags().
std::ios_base::fmtflags Utils::Format::flags () const inline
Returns
all formatting flag bits.
Definition at line 99 of file Format.h.
Format& Utils::Format::hex () inline
Generate integer output in hexadecimal (base 16) format.
Returns
self
Definition at line 198 of file Format.h.
Format& Utils::Format::internal () inline
Adds fill characters at a designated internal point in certain generated output.
If no such point is designated, its identical to `right'.
Returns
self
Definition at line 253 of file Format.h.
Format& Utils::Format::left () inline
Adds fill characters on the right of certain generated output.
Returns
self
Definition at line 240 of file Format.h.
Format& Utils::Format::noboolalpha () inline
Disable translation of boolean values into strings.
Returns
self
Definition at line 180 of file Format.h.
Format& Utils::Format::noshowbase () inline
Do not output a prefix indicating the numeric base for integer output.
Returns
self
Definition at line 210 of file Format.h.
Format& Utils::Format::noshowpoint () inline
Do not force output of a decimal-point character in floating-point output.
Returns
self
Definition at line 234 of file Format.h.
Format& Utils::Format::noshowpos () inline
Do not output a `+' sign in non-negative generated numeric output.
Returns
self
Definition at line 265 of file Format.h.
Format& Utils::Format::noskipws () inline
Do not skip leading white space before certain input operations.
Returns
self
Definition at line 277 of file Format.h.
Format& Utils::Format::nouppercase () inline
Do not replace certain lowercase letters with their uppercase equivalents in generated output.
Returns
self
Definition at line 289 of file Format.h.
Format& Utils::Format::oct () inline
Generate integer output in octal (base 8) format.
Returns
self
Definition at line 192 of file Format.h.
template<class T > Formatter<T> Utils::Format::operator() (const T & v) const inline
Template method that returns a new Formatter instance to hold a reference to us and to a particular value to format.
Parameters
v value to format
Returns
new Formatter instance
Definition at line 298 of file Format.h.
Format& Utils::Format::precision (int precision) inline
Set the number of digits to display after the decimal point.
Parameters
precision number of digits
Returns
self
Definition at line 133 of file Format.h.
References precision().
Referenced by precision().
int Utils::Format::precision () const inline
Returns
current precision setting
Definition at line 137 of file Format.h.
void Utils::Format::put (std::ios & io) const
Apply our format settings to a stream.
Parameters
io stream to act on
Definition at line 50 of file Format.cc.
Referenced by std::operator<<(), and Utils::PushFormat::PushFormat().
Format& Utils::Format::right () inline
Adds fill characters on the left of certain generated output.
Returns
self
Definition at line 246 of file Format.h.
Format& Utils::Format::scientific () inline
Generate floating-point output in scientific notation.
Returns
self
Definition at line 222 of file Format.h.
Format& Utils::Format::setf (fmtflags flags) inline
Turn on one or more formatting flags.
Parameters
flags bits to turn on
Returns
self
Definition at line 107 of file Format.h.
Format& Utils::Format::setf (fmtflags flags, fmtflags mask) inline
Turn on one or more formatting flags, after first masking out the existing flags with a mask.
Parameters
flags bits to turn on
mask bits to turn off before applying the new flags
Returns
self
Definition at line 117 of file Format.h.
Format& Utils::Format::showbase () inline
Output a prefix indicating the numeric base for integer output.
Returns
self
Definition at line 204 of file Format.h.
Format& Utils::Format::showpoint () inline
Force output of a decimal-point character in floating-point output.
Returns
self
Definition at line 228 of file Format.h.
Referenced by PRIInfoInputTask::deliverDataMessage().
Format& Utils::Format::showpos () inline
Output a `+' sign in non-negative generated numeric output.
Returns
self
Definition at line 259 of file Format.h.
Format& Utils::Format::skipws () inline
Skip leading white space before certain input operations.
Returns
self
Definition at line 271 of file Format.h.
Format& Utils::Format::unsetf (fmtflags flags) inline
Turn off one or more formatting flags.
Parameters
flags bits to turn off
Returns
self
Definition at line 125 of file Format.h.
Format& Utils::Format::uppercase () inline
Replace certain lowercase letters with their uppercase equivalents in generated output.
Returns
self
Definition at line 283 of file Format.h.
Format& Utils::Format::width (int width) inline
Set the minimum number of characters used to format a value.
If a value must use more characters, it will do so; this is only a minimum field width.
Parameters
width number of characters
Returns
self
Definition at line 146 of file Format.h.
References width().
Referenced by width().
int Utils::Format::width () const inline
Returns
current width setting
Definition at line 150 of file Format.h.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Utils/Format.h
/Users/howes/src/sidecar/Utils/Format.cc