SideCar: SideCar::Zeroconf::ServiceEntry Class Reference
SideCar::Zeroconf::ServiceEntry Class Reference
Information about of a Zeroconf service published by a Publisher object.
#include </Users/howes/src/sidecar/Zeroconf/ServiceEntry.h>
Public Types
using Ref = boost::shared_ptr< ServiceEntry >
using SignalConnection = boost::signals2::connection
using ResolvedSignal = boost::signals2::signal< void(const ServiceEntry::Ref &)>
using ResolvedSignalProc = ResolvedSignal::slot_function_type
Public Types inherited from SideCar::Zeroconf::Transaction
using Ref = boost::shared_ptr< Transaction >
Public Member Functions
~ServiceEntry ()
Destructor.
SignalConnection connectToResolvedSignal (ResolvedSignalProc observer)
Connect an observer to the ResolvedSignal signal to receive a notification when the ServiceEntry has been resolved to a host/port address.
const std::string & getName () const
Obtain the name of the service.
const std::string & getType () const
Obtain the type of the service.
const std::string & getDomain () const
Obtain the domain in which the service resides.
uint32_t getInterface () const
Obtain the interface ID on which one can contact the service.
std::string getInterfaceName () const
Obtain the system's name for the Ethernet interface.
bool resolve (bool blocking=false)
Begin the resolution process for this ServiceEntry object.
bool isResolved () const
Determine if the service has been resolved.
const ResolvedEntry & getResolvedEntry () const
Obtain a previously-resolved service entry.
Public Member Functions inherited from SideCar::Zeroconf::Transaction
virtual ~Transaction ()
Destructor.
bool stop ()
Stop a Zeroconf service.
bool isRunning () const
Determine if a Zeroconf service is running.
int getConnection () const
Obtain the underlying IPC descriptor used to communicate with the Zeroconf daemon.
bool processConnection ()
Data is available from the Zeroconf daemon.
Static Public Member Functions
static Logger::Log & Log ()
Log device for all ServiceEntry objects.
static Ref Make (Monitor *monitor, const std::string &name, const std::string &type, const std::string &domain, uint32_t interface)
Factory method used to create a new ServiceEntry instance.
Static Public Member Functions inherited from SideCar::Zeroconf::Transaction
static Logger::Log & Log ()
Obtain the log device for all Transaction objects.
Additional Inherited Members
Protected Member Functions inherited from SideCar::Zeroconf::Transaction
Transaction (Monitor *monitor)
Constructor.
virtual void serviceStarted ()
Hook for derived classes for notification that a service has started.
virtual void serviceStopping ()
Hook for derived classes for notification that a sservice is being stopped.
void setSelf (const Ref &self)
Set a weak reference to ourselves so that we can give out shared_ptr refences to ourselves.
void finished ()
void finish ()
template<typename T >
boost::shared_ptr< T > getSelf () const
Obtain a shared_ptr reference to ourselves.
DNSServiceRef & getDNSServiceRef ()
const DNSServiceRef & getDNSServiceRef () const
Detailed Description
Information about of a Zeroconf service published by a Publisher object.
Contains the name, type, and domain of the published service. Also supports resolution of a service into a host and port address, encapsulated in a ResolvedEntry object.
ServiceEntry objects get created by a Browser whenever the multicast DNS server tells it that a new service is available, due it using a Publisher to publish its connection information. The ServiceEntry just contains the name, type, domain, and the network interface over which the service may be found. However, users must invoke the ServiceEntry::resolve() method in order to obtain actual host/port connection information.
Definition at line 28 of file ServiceEntry.h.
Member Function Documentation
SignalConnection SideCar::Zeroconf::ServiceEntry::connectToResolvedSignal (ResolvedSignalProc observer) inline
Connect an observer to the ResolvedSignal signal to receive a notification when the ServiceEntry has been resolved to a host/port address.
The observer must be a function object that takes two parameters:
ServiceEntry::Ref - reference to the object doing the signalling - ResolvedEntry::Ref - reference to the resolved information. If the resolved request failed, then the reference will be invalid. To disconnect, simply invoke the disconnect() method of the returned object.
Parameters
observer object to receive notifications
Returns
object identifying the signal connection
Definition at line 71 of file ServiceEntry.h.
const std::string& SideCar::Zeroconf::ServiceEntry::getDomain () const inline
Obtain the domain in which the service resides.
Returns
service domain
Definition at line 90 of file ServiceEntry.h.
uint32_t SideCar::Zeroconf::ServiceEntry::getInterface () const inline
Obtain the interface ID on which one can contact the service.
Returns
interface ID
Definition at line 96 of file ServiceEntry.h.
std::string ServiceEntry::getInterfaceName () const
Obtain the system's name for the Ethernet interface.
Returns
interface name
Definition at line 43 of file ServiceEntry.cc.
const std::string& SideCar::Zeroconf::ServiceEntry::getName () const inline
Obtain the name of the service.
Returns
service name
Definition at line 78 of file ServiceEntry.h.
const ResolvedEntry& SideCar::Zeroconf::ServiceEntry::getResolvedEntry () const inline
Obtain a previously-resolved service entry.
NOTE: this is only valid if isResolved() returns true, and it is unwise to keep a reference of this around.
Returns
reference to ResolvedEntry object
Definition at line 125 of file ServiceEntry.h.
const std::string& SideCar::Zeroconf::ServiceEntry::getType () const inline
Obtain the type of the service.
Returns
service type
Definition at line 84 of file ServiceEntry.h.
bool SideCar::Zeroconf::ServiceEntry::isResolved () const inline
Determine if the service has been resolved.
NOTE: it is possible that previously resolved service information is no longer accurate. The only way to know is to attempt to connect to it.
Returns
Definition at line 118 of file ServiceEntry.h.
Logger::Log & ServiceEntry::Log () static
Log device for all ServiceEntry objects.
Returns
log device
Definition at line 13 of file ServiceEntry.cc.
References Logger::Log::Find().
Referenced by Make(), and resolve().
ServiceEntry::Ref ServiceEntry::Make (Monitor * monitor, const std::string & name, const std::string & type, const std::string & domain, uint32_t interface) static
Factory method used to create a new ServiceEntry instance.
Parameters
name the name of the service
type the type of the service (eg '_sidecar._tcp')
domain the domainn in which the service resides (eg. 'local.')
interface the system interface on which the service is available
Returns
reference to new ServiceEntry
Definition at line 20 of file ServiceEntry.cc.
References Log(), LOGINFO, and SideCar::Zeroconf::Transaction::Transaction().
bool ServiceEntry::resolve (bool blocking = false)
Begin the resolution process for this ServiceEntry object.
Asks the DNSSD server to do the work. When the resolution is finished, the ResolvedSignal is emitted.
Parameters
blocking if true, do not return until the service has resolved
\return true if successful, false otherwise
Definition at line 50 of file ServiceEntry.cc.
References SideCar::Zeroconf::Transaction::isRunning(), Log(), LOGDEBUG, LOGERROR, LOGINFO, SideCar::Zeroconf::Transaction::serviceStarted(), and SideCar::Zeroconf::Transaction::stop().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Zeroconf/ServiceEntry.h
/Users/howes/src/sidecar/Zeroconf/ServiceEntry.cc