SideCar: SideCar::Messages::VoidLoaderRegistry Class Reference
SideCar::Messages::VoidLoaderRegistry Class Reference
Registry of methods that perform version-specific loads of raw data.
#include </Users/howes/src/sidecar/Messages/LoaderRegistry.h>
Data Structures
struct VersionedVoidLoader
Pairing of specific version value with a class loader procedure.
Public Types
using VoidLoader = ACE_InputCDR &(*)(void *object, ACE_InputCDR &cdr)
Type specification for loader procedures.
using VersionType = uint16_t
Type specification for version indicators.
Public Member Functions
VersionType getCurrentVersion () const
Obtain the latest version registered.
Static Public Member Functions
static Logger::Log & Log ()
Obtain log device for instances of this class.
Protected Member Functions
VoidLoaderRegistry (VersionType version, VoidLoader loader)
Constructor.
VoidLoaderRegistry (const VersionedVoidLoader *first, size_t numVersions) throw (Utils::Exception)
Constructor.
void addVoidLoader (VersionType version, VoidLoader loader) throw (Utils::Exception)
Register a new version/loader combination.
VoidLoader getVoidLoader (VersionType version) const throw (Utils::Exception)
Obtain the appropriate loader for a given version.
Detailed Description
Registry of methods that perform version-specific loads of raw data.
A load procedure is a non-member function (eg. class method or plain C/C++ function pointer) with the following prototype:
ACE_InputCDR& PROC(void* OBJ, ACE_InputCDR& CDR)
where the PROC is the name of the function, OBJ is a pointer to an instance of a class that will be loaded, and CDR is a writable reference to an ACE_InputCDR stream class that handles unmarshalling of data from an external data source. When called, the function should fill in the object with values from the input stream, and it should return a reference to the stream when it is done.
The LoaderRegistry::getLoader() method returns the appropriate loader for a particular version indicator. If a specific version is not found, the routine will return the loader with the closest version indicator greater than that requested. If there is none, the routine issues a warning message and returns the last registered loader Note that a class load method using the LoaderRegistry should never have this happen if the corresponding write method always writes out the version indicator obtained from LoaderRegistry::getCurrentVersion().
Note that the class serves as a base class for the TLoaderRegistry template class below; constructor access restrictions prohibit direct instantiations.
Definition at line 40 of file LoaderRegistry.h.
Member Typedef Documentation
using SideCar::Messages::VoidLoaderRegistry::VoidLoader = ACE_InputCDR& (*)(void* object, ACE_InputCDR& cdr)
Type specification for loader procedures.
Note that type-specific loaders exist and are specified in the TLoaderRegistry class.
Definition at line 47 of file LoaderRegistry.h.
Constructor & Destructor Documentation
VoidLoaderRegistry::VoidLoaderRegistry (VersionType version, VoidLoader loader) protected
Constructor.
Registers a single loader.
Parameters
version version indicator to register
loader procedure to register
Definition at line 14 of file LoaderRegistry.cc.
References addVoidLoader(), Log(), and LOGINFO.
VoidLoaderRegistry::VoidLoaderRegistry (const VersionedVoidLoader * first, size_t numVersions) throw (Utils::Exception) protected
Constructor.
Registers an array of loaders and their versions. NOTE: throws an exception if numVersions is zero.
Parameters
first pointer to the first entry to register
numVersions number of entries to register
Definition at line 22 of file LoaderRegistry.cc.
References addVoidLoader(), Log(), LOGDEBUG, LOGINFO, and Logger::ProcLog::thrower().
Member Function Documentation
void VoidLoaderRegistry::addVoidLoader (VersionType version, VoidLoader loader) throw (Utils::Exception) protected
Register a new version/loader combination.
NOTE: if the version is already registered, the routine thruws an exception.
Parameters
version version indicator to register
loader procedure to register
Definition at line 58 of file LoaderRegistry.cc.
References Log(), LOGDEBUG, LOGINFO, and Logger::ProcLog::thrower().
Referenced by VoidLoaderRegistry().
VersionType SideCar::Messages::VoidLoaderRegistry::getCurrentVersion () const inline
Obtain the latest version registered.
Returns
version indicator
Definition at line 63 of file LoaderRegistry.h.
Referenced by SideCar::Messages::Track::write(), SideCar::Messages::TSPI::write(), and SideCar::Messages::PRIMessage::writeArray().
VoidLoaderRegistry::VoidLoader VoidLoaderRegistry::getVoidLoader (VersionType version) const throw (Utils::Exception) protected
Obtain the appropriate loader for a given version.
Note that if the version indicator is greater than the last registered version indicator, the routine will return the last loader. Throws an exception if the collection of loaders is empty.
Parameters
version version indicator to look for
Returns
found Loader method
Definition at line 106 of file LoaderRegistry.cc.
References Log(), LOGDEBUG, LOGINFO, LOGWARNING, and Logger::ProcLog::thrower().
Logger::Log & VoidLoaderRegistry::Log () static
Obtain log device for instances of this class.
Returns
log device
Definition at line 8 of file LoaderRegistry.cc.
References Logger::Log::Find().
Referenced by addVoidLoader(), getVoidLoader(), and VoidLoaderRegistry().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Messages/LoaderRegistry.h
/Users/howes/src/sidecar/Messages/LoaderRegistry.cc