SideCar: SideCar::GUI::AScope::PeakBar Class Reference
SideCar::GUI::AScope::PeakBar Class Reference
Model of a maximum value "peak bar".
#include </Users/howes/src/sidecar/GUI/AScope/PeakBar.h>
Public Member Functions
PeakBar ()
Constructor.
bool update (Messages::Video::const_iterator pos, Messages::Video::const_iterator end, bool reset)
Scan the values found within two iterators and acquire the maximum.
int getValue () const
Obtain the current peak value.
int getAge () const
Obtain the age of the peak value.
double getDecay () const
Obtain the opacity value that corresponds to the bar's current age.
Static Public Member Functions
static Logger::Log & Log ()
static void SetLifeTime (int lifeTime)
Set the lifetime of each PeakBar.
static double GetDecay (int age)
Obtain the opacity value for a given age.
Detailed Description
Model of a maximum value "peak bar".
Holds the largest value seen over a certain time period (set with the SetLifeTime() class method). After the time period has expired, the held value resets to the last seen value, and a new time period begins.
Definition at line 18 of file PeakBar.h.
Constructor & Destructor Documentation
SideCar::GUI::AScope::PeakBar::PeakBar () inline
Constructor.
Initializes a new peak bar instance.
Definition at line 42 of file PeakBar.h.
Member Function Documentation
int SideCar::GUI::AScope::PeakBar::getAge () const inline
Obtain the age of the peak value.
This is the number of update() calls seen by the object without a change in the bar's value.
Returns
age
Definition at line 66 of file PeakBar.h.
double PeakBar::GetDecay (int age) static
Obtain the opacity value for a given age.
Decay values range from 1.0 for new peak bar values, and ~0.3 for those at near the end of their lifetime.
Parameters
age the age to convert
Returns
opacity value
Definition at line 37 of file PeakBar.cc.
References SetLifeTime().
double SideCar::GUI::AScope::PeakBar::getDecay () const inline
Obtain the opacity value that corresponds to the bar's current age.
Returns
Definition at line 72 of file PeakBar.h.
int SideCar::GUI::AScope::PeakBar::getValue () const inline
Obtain the current peak value.
Returns
peak value
Definition at line 59 of file PeakBar.h.
void PeakBar::SetLifeTime (int lifeTime) static
Set the lifetime of each PeakBar.
This is the number of setMaxValue() calls before the PeakBar will relinquish a held max value and pick a new one.
Parameters
lifeTime
Definition at line 22 of file PeakBar.cc.
Referenced by GetDecay(), and SideCar::GUI::AScope::PeakBarSettings::PeakBarSettings().
bool PeakBar::update (Messages::Video::const_iterator pos, Messages::Video::const_iterator end, bool reset)
Scan the values found within two iterators and acquire the maximum.
Parameters
pos first gate to check
end last gate to check
Returns
true if value changed
Definition at line 45 of file PeakBar.cc.
References LOGDEBUG, and LOGINFO.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/AScope/PeakBar.h
/Users/howes/src/sidecar/GUI/AScope/PeakBar.cc