SideCar: SideCar::GUI::Master::RecordingController Class Reference
SideCar::GUI::Master::RecordingController Class Reference
Public Types
enum Status {
kOK = 0, kNoLoadedConfig, kFailedCreateDirectory, kFailedRecordingSetup,
kFailedPostRecordingStateChange
}
enum { kServerPort = 4465 }
Public Slots
void startStop ()
Signals
void statusChanged (const QStringList &configNames, bool isRecording)
Public Member Functions
RecordingController (MainWindow &mainWindow)
QStringList restore (const ConfigurationController &controller)
QStringList restore (const QString &path)
QString getNow () const
Status start (const QStringList &configNames)
Status start ()
Status stop (bool byDuration=false)
void restoreActiveRecording ()
RecordingInfo * getActiveRecording () const
RecordingInfo * getLastRecording () const
RecordingInfo * getRecordingInfo (const QString &name) const
void reset ()
Static Public Member Functions
static Logger::Log & Log ()
Log device to use for RecordingController log messages.
Detailed Description
Definition at line 23 of file RecordingController.h.
Member Function Documentation
Logger::Log & RecordingController::Log () static
Log device to use for RecordingController log messages.
Returns
Log device
Definition at line 32 of file RecordingController.cc.
References Logger::Log::Find(), SideCar::GUI::Master::RecordingInfo::getConfigurationNames(), SideCar::GUI::Master::ConfigurationInfo::getPath(), SideCar::GUI::Master::ConfigurationInfo::getRecordingsDirectory(), SideCar::GUI::Master::RecordingInfo::hasDurationPassed(), SideCar::GUI::Master::RecordingInfo::isDone(), LOGDEBUG, LOGERROR, LOGINFO, SideCar::GUI::RemoveDirectory(), and SideCar::GUI::Master::RecordingInfo::showNotesWindow().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/RecordingController.h
/Users/howes/src/sidecar/GUI/Master/RecordingController.cc