SideCar: SideCar::GUI::PPIDisplay::History::Entry Class Reference
SideCar::GUI::PPIDisplay::History::Entry Class Reference
Collection of Video & Extraction objects for one revolution of the radar.
#include </Users/howes/src/sidecar/GUI/PPIDisplay/History.h>
Public Member Functions
Entry (size_t videoCapacity, size_t binaryCapacity)
Constructor.
Messages::Video::DatumType getVideoValue (double azimuth, double range, bool &isValid) const
Messages::BinaryVideo::DatumType getBinaryValue (double azimuth, double range, bool &isValid) const
bool hasVideo () const
Determine if there is no data.
const MessageVector & getVideo () const
Obtain a read-only reference to the Video collection.
const MessageVector & getBinary () const
Obtain a read-only reference to the BinaryVideo collection.
const TargetPlotList & getExtractions () const
Obtain a read-only reference to the Extraction message collection.
const TargetPlotListList & getRangeTruths () const
Obtain a read-only reference to the RangeTruth entries.
const TargetPlotList & getBugPlots () const
Obtain a read-only reference to the BugPlot entries.
void clearAll ()
Remove all entries from the container.
void clearVideo ()
void clearBinary ()
void clearExtractions ()
void clearRangeTruths ()
void clearBugPlots ()
Friends
class History
Grant access to push_back() and clear()
Detailed Description
Collection of Video & Extraction objects for one revolution of the radar.
The message data is stored in std::vector objects used as a circular-buffer.
Definition at line 49 of file History.h.
Member Function Documentation
const MessageVector& SideCar::GUI::PPIDisplay::History::Entry::getBinary () const inline
Obtain a read-only reference to the BinaryVideo collection.
Returns
MessageVector reference
Definition at line 80 of file History.h.
Referenced by SideCar::GUI::PPIDisplay::History::addVideo().
const TargetPlotList& SideCar::GUI::PPIDisplay::History::Entry::getBugPlots () const inline
Obtain a read-only reference to the BugPlot entries.
Returns
TargetPlotList reference
Definition at line 100 of file History.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::processBugPlots().
const TargetPlotList& SideCar::GUI::PPIDisplay::History::Entry::getExtractions () const inline
Obtain a read-only reference to the Extraction message collection.
Returns
TargetPlotList reference
Definition at line 86 of file History.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::processBugPlots().
const TargetPlotListList& SideCar::GUI::PPIDisplay::History::Entry::getRangeTruths () const inline
Obtain a read-only reference to the RangeTruth entries.
Returns
TargetPlotList reference
Definition at line 93 of file History.h.
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::processBugPlots().
const MessageVector& SideCar::GUI::PPIDisplay::History::Entry::getVideo () const inline
Obtain a read-only reference to the Video collection.
Returns
MessageVector reference
Definition at line 74 of file History.h.
Referenced by SideCar::GUI::PPIDisplay::History::addVideo().
bool SideCar::GUI::PPIDisplay::History::Entry::hasVideo () const inline
Determine if there is no data.
Note that we only check for Video, since we must have them in order to do any rotation.
Returns
true if empty
Definition at line 68 of file History.h.
Referenced by SideCar::GUI::PPIDisplay::History::addBinary(), and SideCar::GUI::PPIDisplay::History::addExtractions().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/PPIDisplay/History.h
/Users/howes/src/sidecar/GUI/PPIDisplay/History.cc