SideCar: SideCar::Messages::Attributes Class Reference
SideCar::Messages::Attributes Class Reference
Collection of name/value pairs for SideCar messages.
#include </Users/howes/src/sidecar/Messages/Attributes.h>
Data Structures
class DuplicateAttribute
Exception thrown when a duplicate attribute name is detected.
Public Member Functions
Attributes ()
Constructor.
void add (const std::string &name, const XmlRpc::XmlRpcValue &value) throw (DuplicateAttribute)
Add a new attribute to the container.
bool contains (const std::string &name) const
Determines if there is an attribute with the given name.
const XmlRpc::XmlRpcValue & find (const std::string &name) const
Find an attribute with the given name.
const XmlRpc::XmlRpcValue & operator[] (const std::string &name) const
Obtain an attribute with the given name.
ACE_InputCDR & load (ACE_InputCDR &cdr)
Build an Attributes container from an ACE CDR stream.
ACE_OutputCDR & write (ACE_OutputCDR &cdr) const
Write an Attributes container to an ACE CDR stream.
std::ostream & print (std::ostream &os) const
Write XML representation of Attributes container to given C++ text stream.
Detailed Description
Collection of name/value pairs for SideCar messages.
Relies on the XMLRPC library for marshalling the values to/from network or disk. Currently, the Extraction and BugPlot messages support attributes. If enough messsage classes do, it may make sense to have Header acquire an Attributes slot.
Definition at line 18 of file Attributes.h.
Constructor & Destructor Documentation
Attributes::Attributes ()
Constructor.
Initialize empty container of attributes.
Definition at line 15 of file Attributes.cc.
Member Function Documentation
void Attributes::add (const std::string & name, const XmlRpc::XmlRpcValue & value) throw (DuplicateAttribute)
Add a new attribute to the container.
Throws DuplicateAttribute exception if one already exists with the same name.
Parameters
name the attribute name
value the attribute value
Definition at line 22 of file Attributes.cc.
References XmlRpc::XmlRpcValue::hasMember().
bool SideCar::Messages::Attributes::contains (const std::string & name) const inline
Determines if there is an attribute with the given name.
Parameters
name the attribute name
Returns
true if exists
Definition at line 54 of file Attributes.h.
const XmlRpc::XmlRpcValue& SideCar::Messages::Attributes::find (const std::string & name) const inline
Find an attribute with the given name.
Parameters
name the attribute name
Returns
attribute value if found; 'invalid' XMLRPC value if not.
Definition at line 62 of file Attributes.h.
Referenced by operator[]().
ACE_InputCDR & Attributes::load (ACE_InputCDR & cdr)
Build an Attributes container from an ACE CDR stream.
Parameters
cdr stream to read from
Returns
stream read from
Definition at line 34 of file Attributes.cc.
References XmlRpc::XmlRpcValue::fromXml().
Referenced by operator[]().
const XmlRpc::XmlRpcValue& SideCar::Messages::Attributes::operator[] (const std::string & name) const inline
Obtain an attribute with the given name.
Parameters
name the attribute name
Returns
attribute value if found; 'invalid' XMLRPC value if not.
Definition at line 70 of file Attributes.h.
References find(), load(), and write().
std::ostream& SideCar::Messages::Attributes::print (std::ostream & os) const inline
Write XML representation of Attributes container to given C++ text stream.
Parameters
os stream to write to
Returns
stream written to
Definition at line 94 of file Attributes.h.
ACE_OutputCDR & Attributes::write (ACE_OutputCDR & cdr) const
Write an Attributes container to an ACE CDR stream.
Parameters
cdr stream to write to
Returns
stream written to
Definition at line 44 of file Attributes.cc.
References XmlRpc::XmlRpcValue::toXml().
Referenced by operator[]().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Messages/Attributes.h
/Users/howes/src/sidecar/Messages/Attributes.cc