SideCar: Utils::FilePath Class Reference
Utils::FilePath Class Reference
Simple wrapper around the std string class that can decompose a file path into three parts: directory path, file name, and extension.
#include </Users/howes/src/sidecar/Utils/FilePath.h>
Public Member Functions
FilePath (const std::string &path)
Constructor using C++ string for path.
FilePath (const char *path)
Constructor using C string for path.
FilePath (const std::string &dir, const std::string &file)
Create a file path from a directory path and a file name.
virtual ~FilePath ()=default
Destructor.
std::string pathPart () const
Returns the directory path component of the file path.
std::string filePart () const
Returns the file name component of the file path.
std::string extension () const
Returns the extension found at the end of the file name.
bool exists () const
Returns true if the instance points to a valid file.
void relocate (const std::string &path)
Change the directory path component to the given value.
void setExtension (const std::string &ext)
Change the extension of the file path to the given value.
const std::string & filePath () const
Fetch the entire file path.
const char * c_str () const
Fetch the entire file path as a C string.
operator const std::string & () const
Type conversion operator for C++ string.
operator const char * () const
Type conversion operator into C string.
std::ostream & print (std::ostream &os) const
Implementation of Printable interface.
bool empty () const
int size () const
Get the number of characters in the full path.
time_t getModificationTime () const
Get the time of the last modification to this file.
Detailed Description
Simple wrapper around the std string class that can decompose a file path into three parts: directory path, file name, and extension.
It will also expand embedded shell variables such as `$FOO' or `${HOME}'.
Definition at line 22 of file FilePath.h.
Constructor & Destructor Documentation
Utils::FilePath::FilePath (const std::string & path) inline
Constructor using C++ string for path.
Parameters
path name and location of file
Definition at line 30 of file FilePath.h.
Referenced by FilePath(), and getModificationTime().
Utils::FilePath::FilePath (const char * path) inline
Constructor using C string for path.
Parameters
path name and location of file
Definition at line 36 of file FilePath.h.
References exists(), extension(), filePart(), FilePath(), pathPart(), relocate(), setExtension(), and ~FilePath().
FilePath::FilePath (const std::string & dir, const std::string & file)
Create a file path from a directory path and a file name.
Parameters
dir directory path
file file name
Definition at line 11 of file FilePath.cc.
virtual Utils::FilePath::~FilePath () virtual default
Destructor.
Here to silence GCC warnings.
Referenced by FilePath().
Member Function Documentation
const char* Utils::FilePath::c_str () const inline
Fetch the entire file path as a C string.
Returns
NULL-terminated C string
Definition at line 97 of file FilePath.h.
Referenced by SideCar::IO::RecordIndex::RecordIndex(), and SideCar::IO::TimeIndex::TimeIndex().
bool FilePath::exists () const
Returns true if the instance points to a valid file.
This only checks that the file exists; it does not indicate whether the user can open the file.
Returns
true if the file exists, false otherwise
Definition at line 43 of file FilePath.cc.
Referenced by PRIInfoInputTask::deliverDataMessage(), FilePath(), getModificationTime(), SideCar::IO::RecordIndex::RecordIndex(), and SideCar::IO::TimeIndex::TimeIndex().
std::string FilePath::extension () const
Returns the extension found at the end of the file name.
An extension is defined as any characters following the last `.' found in the file path. If there are more than one `.' in the path, only the last one is treated as the extension.
Definition at line 35 of file FilePath.cc.
References filePart().
Referenced by FilePath().
std::string FilePath::filePart () const
Returns the file name component of the file path.
If there is no file component (the file path ends in a '/'), returns an empty string.
Definition at line 28 of file FilePath.cc.
Referenced by extension(), FilePath(), and relocate().
const std::string& Utils::FilePath::filePath () const inline
Fetch the entire file path.
Returns
file path
Definition at line 91 of file FilePath.h.
Referenced by getModificationTime().
time_t FilePath::getModificationTime () const
Get the time of the last modification to this file.
File must exist or else an exception is thrown.
Returns
modification time
Definition at line 160 of file FilePath.cc.
References exists(), FilePath(), filePath(), and relocate().
Referenced by size().
Utils::FilePath::operator const char * () const inline
Type conversion operator into C string.
Returns
NULL-terminated C string
Definition at line 109 of file FilePath.h.
References print().
Utils::FilePath::operator const std::string & () const inline
Type conversion operator for C++ string.
Returns
C++ string
Definition at line 103 of file FilePath.h.
std::string FilePath::pathPart () const
Returns the directory path component of the file path.
If there is no directory component, returns an empty string. All non-empty directory components end in a '/' character.
Definition at line 21 of file FilePath.cc.
Referenced by FilePath().
std::ostream & FilePath::print (std::ostream & os) const virtual
Implementation of Printable interface.
Write out full file path to given stream as a string.
Parameters
os stream to write to
Returns
stream written to
Implements Utils::Printable.
Definition at line 95 of file FilePath.cc.
Referenced by operator const char *().
void FilePath::relocate (const std::string & path)
Change the directory path component to the given value.
Parameters
path new directory path to assign to the file path.
Definition at line 51 of file FilePath.cc.
References filePart().
Referenced by FilePath(), and getModificationTime().
void FilePath::setExtension (const std::string & ext)
Change the extension of the file path to the given value.
The extention text may start with a `.' character; if one is not present, the method will add one before using.
Parameters
ext extension value to use
Definition at line 62 of file FilePath.cc.
Referenced by Args::Args(), PRIInfoInputTask::deliverDataMessage(), and FilePath().
int Utils::FilePath::size () const inline
Get the number of characters in the full path.
Returns
full path length
Definition at line 125 of file FilePath.h.
References getModificationTime().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Utils/FilePath.h
/Users/howes/src/sidecar/Utils/FilePath.cc