SideCar: SideCar::Algorithms::ABTracker Class Reference
SideCar::Algorithms::ABTracker Class Reference
Documentation for the algorithm ABTracker.
#include </Users/howes/src/sidecar/Algorithms/ABTracker/ABTracker.h>
Public Types
enum InfoSlots {
kEnabled = ControllerStatus::kNumSlots, kAlpha, kBeta, kTrackCount,
kTimeScaling, kNumSlots
}
Public Member Functions
ABTracker (Controller &controller, Logger::Log &log)
Constructor.
bool startup ()
Implementation of the Algorithm::startup interface.
bool shutdown ()
Implementation of the Algorithm::shutdown interface.
void setRotationDuration (double value)
double getRotationDuration () const
void setTimeScaling (double value)
double getTimeScaling () const
void setAlpha (double value)
double getAlpha () const
void setBeta (double value)
double getBeta () const
void setAssociationRadius (double value)
double getAssociationRadius () const
void setInitiationCount (int value)
uint32_t getInitiationCount () const
void setInitiationRotationCount (double value)
double getInitiationRotationCount () const
void setCoastRotationCount (double value)
double getCoastRotationCount () const
void setMinRange (double value)
double getMinRange () const
double getScaledMaxInitiationDuration () const
double getScaledMaxCoastDuration () const
Public Member Functions inherited from SideCar::Algorithms::Algorithm
Algorithm (Controller &controller, Logger::Log &log)
Constructor.
virtual ~Algorithm ()
Destructor.
Controller & getController () const
Obtain the Controller object managing the algorithm.
Logger::Log & getLog () const
Obtain the log device to use for by the algorithm for log messages.
const std::string & getName () const
Obtain the name of the algorithm.
bool registerParameter (const Parameter::Ref &parameter)
Add a configuration parameter to the runtime system.
bool unregisterParameter (const Parameter::Ref &parameter)
Remove a configuration parameter from the runtime system.
template<typename A , typename M >
void registerProcessor (boost::function< bool(A *, typename M::Ref)> proc)
Install a method to process a particular message type.
template<typename A , typename M >
void registerProcessor (const std::string &channelName, boost::function< bool(A *, typename M::Ref)> proc)
Same as above method, but allows user to pick the channel by name.
template<typename A , typename M >
void registerProcessor (size_t channelIndex, boost::function< bool(A *, typename M::Ref)> proc)
Same as above method, but allows user to pick the channel by index.
template<typename A >
void registerProcessor (const std::string &channelName, const Messages::MetaTypeInfo &metaTypeInfo, boost::function< bool(A *, typename Messages::Header::Ref)> proc)
template<typename A >
void registerProcessor (size_t channelIndex, const Messages::MetaTypeInfo &metaTypeInfo, boost::function< bool(A *, typename Messages::Header::Ref)> proc)
size_t addProcessor (const std::string &channelName, const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
size_t addProcessor (const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
size_t addProcessor (size_t index, const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
void removeProcessor (size_t index)
Remove a processor from a given channel.
size_t getOutputChannelIndex (const std::string &name) const
Obtain an output channel index with a given name.
bool send (const Messages::Header::Ref &msg, size_t channelIndex=0)
Submit a message object to the controller for sending out on a given data channel.
bool sendAsIs (const Messages::Header::Ref &msg, size_t channelIndex=0)
Hand a message to the controller for sending out on a given data channel.
size_t getActiveChannelIndex () const
Obtain the index of the input channel that last received a message for the algorithm to process.
Additional Inherited Members
Static Public Member Functions inherited from SideCar::Algorithms::Algorithm
static void * FormatInfoValue (const QString &value)
Obtain a C-safe value for the given QString string.
static void * FormatInfoValue (const char *value)
Obtain a C-safe value for the given character string.
Protected Member Functions inherited from SideCar::Algorithms::Algorithm
void setAlarm (int secs)
This method can be used by an Algorithm to schedule a periodic alarm to go off for itself.
virtual bool reset ()
Hook called when the algorithm is transitioning from a stopped to a running state (one of Task::kAutoDiagnostic, Task::kCalibrate, or Task::kRun).
virtual bool clearStats ()
Hook called when the algorithm is commaned to clear any statistics.
virtual bool beginAutoDiag ()
Hook called when the algorithm is entering the Task::kAutoDiagnostic state.
virtual bool beginCalibration ()
Hook called when the algorithm is entering the Task::kCalibrate state.
virtual bool beginRun ()
Hook called when the algorithm is entering the Task::kRun state.
virtual bool stop ()
Hook called when the algorithm is entering the Task::kStop state.
virtual void recordingStarted ()
Hook called when a recording has started.
virtual void recordingStopped ()
Hook called when a recording has stopped.
virtual void beginParameterChanges ()
Hook called just before algorithm runtime parameters are changed.
virtual void processAlarm ()
This method will get called whenever an alarm expires for this Algorithm.
Detailed Description
Documentation for the algorithm ABTracker.
Please describe what the algorithm does, in layman's terms and, if possible, mathematical terms.
Definition at line 17 of file ABTracker.h.
Constructor & Destructor Documentation
ABTracker::ABTracker (Controller & controller, Logger::Log & log)
Constructor.
Parameters
controller object that controls us
log device used for log messages
Definition at line 19 of file ABTracker.cc.
Referenced by shutdown().
Member Function Documentation
bool ABTracker::shutdown () virtual
Implementation of the Algorithm::shutdown interface.
Dispose of any resources (such as memory) allocated from within the startup() method.
Returns
true if successful, false otherwise
Reimplemented from SideCar::Algorithms::Algorithm.
Definition at line 66 of file ABTracker.cc.
References ABTracker(), SideCar::Time::TimeStamp::asDouble(), SideCar::Algorithms::ABTrackerUtils::Track::drop(), SideCar::Algorithms::ABTrackerUtils::Track::emitPosition(), SideCar::Algorithms::Algorithm::FormatInfoValue(), SideCar::Messages::Extraction::getAzimuth(), SideCar::Messages::Extraction::getElevation(), SideCar::Algorithms::ABTrackerUtils::Track::getId(), SideCar::Algorithms::Algorithm::getLog(), SideCar::Algorithms::ABTrackerUtils::Track::getProximityTo(), SideCar::Messages::Extraction::getRange(), SideCar::Parameter::TValue< ParamDef >::getValue(), SideCar::Messages::Extraction::getX(), SideCar::Messages::Extraction::getY(), SideCar::Algorithms::ABTrackerUtils::Track::isDropping(), LOGINFO, SideCar::IO::StatusBase::setSlot(), SideCar::Algorithms::Algorithm::shutdown(), and SideCar::Algorithms::ABTrackerUtils::Track::updatePosition().
bool ABTracker::startup () virtual
Implementation of the Algorithm::startup interface.
Register runtime parameters and data processors.
Returns
true if successful, false otherwise
Reimplemented from SideCar::Algorithms::Algorithm.
Definition at line 47 of file ABTracker.cc.
References SideCar::Algorithms::Algorithm::registerParameter(), and SideCar::Algorithms::Algorithm::startup().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/ABTracker/ABTracker.h
/Users/howes/src/sidecar/Algorithms/ABTracker/ABTracker.cc