SideCar: SideCar::GUI::Master::LogViewWindowManager Class Reference
SideCar::GUI::Master::LogViewWindowManager Class Reference
Derivation of QComboBox that manages the set of known RunnerItem objects and their LogViewWindow windows.
#include </Users/howes/src/sidecar/GUI/Master/LogViewWindowManager.h>
Data Structures
struct ConfigMap
Internal mapping from configuration names to a list of LogInfo entries.
Public Member Functions
LogViewWindowManager (QWidget *parent=0)
Constructor.
~LogViewWindowManager ()
Destructor.
void addLogInfo (const RunnerItem *runnerItem)
Add an entry for the given RunnerItem.
void addLogInfo (const SideCar::Configuration::RunnerConfig *runnerConfig)
Add an entry for the given Configuration::RunnerConfig entry.
void removeConfiguration (const QString &configName)
Remove the entries associated with a specific configuration.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for LogViewWindowManager objects.
Detailed Description
Derivation of QComboBox that manages the set of known RunnerItem objects and their LogViewWindow windows.
The QComboBox contains the runner names, segmented by their configuration names. Selecting a runner name will show and bring to the front the LogViewWindow window for that runner.
Definition at line 20 of file LogViewWindowManager.h.
Constructor & Destructor Documentation
LogViewWindowManager::LogViewWindowManager (QWidget * parent = 0)
Constructor.
Initializes an empty QComboBox object
Parameters
parent parent for auto-destruction
Definition at line 93 of file LogViewWindowManager.cc.
LogViewWindowManager::~LogViewWindowManager ()
Destructor.
Delete the configuration mapping.
Definition at line 100 of file LogViewWindowManager.cc.
Member Function Documentation
void LogViewWindowManager::addLogInfo (const RunnerItem * runnerItem)
Add an entry for the given RunnerItem.
Parameters
runnerItem RunnerItem to add
Definition at line 114 of file LogViewWindowManager.cc.
References SideCar::GUI::Master::RunnerItem::getConfigName(), SideCar::GUI::Master::TreeViewItem::getName(), SideCar::GUI::Master::RunnerItem::getServiceName(), and SideCar::GUI::Master::RunnerLog::Make().
Referenced by addLogInfo().
void LogViewWindowManager::addLogInfo (const SideCar::Configuration::RunnerConfig * runnerConfig)
Add an entry for the given Configuration::RunnerConfig entry.
Parameters
runnerConfig RunnerConfig to add
Definition at line 106 of file LogViewWindowManager.cc.
References addLogInfo(), SideCar::Configuration::RunnerConfig::getConfigurationName(), SideCar::Configuration::RunnerConfig::getRunnerName(), and SideCar::Configuration::RunnerConfig::getServiceName().
Logger::Log & LogViewWindowManager::Log () static
Obtain the log device for LogViewWindowManager objects.
Returns
Logger::Log device
Definition at line 22 of file LogViewWindowManager.cc.
References Logger::Log::Find().
Referenced by removeConfiguration().
void LogViewWindowManager::removeConfiguration (const QString & configName)
Remove the entries associated with a specific configuration.
Parameters
configName name of the configuration to remove
Definition at line 181 of file LogViewWindowManager.cc.
References SideCar::GUI::Master::RunnerLog::Find(), Log(), LOGDEBUG, LOGINFO, and SideCar::GUI::Master::RunnerLog::showWindow().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/LogViewWindowManager.h
/Users/howes/src/sidecar/GUI/Master/LogViewWindowManager.cc