SideCar: SideCar::Messages::TSPI Class Reference
SideCar::Messages::TSPI Class Reference
Public Types
enum Flags { kDropping = (1 << 0) }
using Super = Header
using Ref = boost::shared_ptr< TSPI >
using Coord = std::vector< double >
Public Types inherited from SideCar::Messages::Header
using Ref = boost::shared_ptr< Header >
Public Member Functions
~TSPI ()
Destructor.
ACE_InputCDR & load (ACE_InputCDR &cdr)
Read in a TSPI message from an CDR input stream.
ACE_OutputCDR & write (ACE_OutputCDR &cdr) const
Write out a TSPI message to a CDR output stream.
std::ostream & printData (std::ostream &os) const
Print out a textual representation of the TSPI message.
std::ostream & printDataXML (std::ostream &os) const
Write out a TSPI message to a C++ output stream in XML format.
const double * getEarthCentered () const
Obtain the position in earth-centered coordinates.
double getE () const
Obtain the E component of the earth-centered position.
double getF () const
Obtain the F component of the earth-centered position.
double getG () const
Obtain the G component of the earth-centered position.
const Coord & getLatitudeLongitudeHeight () const
Obtain the position in latitude, longitude, height.
double getLatitude () const
Obtain the latitude component.
double getLongitude () const
Obtain the longitude component.
double getHeight () const
Obtain the height component.
const Coord & getRangeAzimuthElevation () const
Obtain the position in range, azimuth, elevation from the radar origin.
double getRange () const
Obtain the range component.
double getAzimuth () const
Obtain the azimuth component.
double getElevation () const
Obtain the elevation component.
const Coord & getXYZ () const
Obtain the 3-D offsets from the radar origin.
double getX () const
Obtain the X component.
double getY () const
Obtain the Y component.
double getZ () const
Obtain the Z component.
double getWhen () const
Obtain the timestamp for the position report.
const std::string & getTag () const
Obtain the name assigned to the report.
bool isDropping () const
Determine if the report is dropping.
void setDropping ()
Set the dropping indicator.
void dump () const
Write the current position values to the debug logger.
void addAttribute (const std::string &name, const XmlRpc::XmlRpcValue &value)
Add an attribute to the position report.
const Attributes & getAttributes () const
Obtain the Attributes object for this report.
void loadXML (XmlStreamReader &xsr)
Set internal state from an XML message.
Public Member Functions inherited from SideCar::Messages::Header
Header (const MetaTypeInfo &metaTypeInfo)
Constructor for messages read in from an external device.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis)
Constructor for new messages.
Header (const std::string &producer, const MetaTypeInfo &metaTypeInfo, const Ref &basis, MetaTypeInfo::SequenceType sequenceNumber)
Constructor for new messages.
virtual ~Header ()
Destructor.
const MetaTypeInfo & getMetaTypeInfo () const
Obtain the type specification for the message.
const GUID & getGloballyUniqueID () const
Get the globally-unique ID of the message.
MetaTypeInfo::SequenceType getMessageSequenceNumber () const
Get the message sequence number for the message.
void setMessageSequenceNumber (MetaTypeInfo::SequenceType msn)
Set the sequence number for this message.
const Time::TimeStamp & getCreatedTimeStamp () const
Obtain when the message was created.
Time::TimeStamp setCreatedTimeStamp (const Time::TimeStamp &timeStamp)
Revise the creation message timestamp.
const Time::TimeStamp & getEmittedTimeStamp () const
Obtain when the message was written to an external device (file or network).
Time::TimeStamp setEmittedTimeStamp (const Time::TimeStamp &timeStamp)
Set the emitted time stamp with the given value.
virtual size_t getSize () const
Obtain the C++ structure size for this object.
HeaderPrinter headerPrinter () const
Convenience method that simply returns a new HeaderPrinter functor for this header object.
DataPrinter dataPrinter () const
Convenience method that simply returns a new DataPrinter functor for this header object.
XMLPrinter xmlPrinter () const
Convenience method that simply returns a new XMLPrinter functor for this header object.
virtual std::ostream & print (std::ostream &os) const
Write out the entire message to a C++ text output stream.
virtual std::ostream & printHeader (std::ostream &os) const
Write out the message header to a C++ text output stream.
virtual std::ostream & printXML (std::ostream &os) const
Write out the message to a C++ text output stream in XML format.
bool hasBasis () const
Determine if the message has a basis message attached to it.
Ref getBasis () const
Obtain a reference to the message that this one was based on.
template<typename T >
T::Ref getBasis () const
Templated version of the above method.
Static Public Member Functions
static Logger::Log & Log ()
static const MetaTypeInfo & GetMetaTypeInfo ()
Obtain the message type information for RawVideo objects.
static const GEO_LOCATION * GetOrigin ()
static std::string GetSystemIdTag (uint16_t systemId)
static double MakeEFGCoordinateFromRawBytes (const uint8_t *ptr)
Utility that converts 4 raw bytes into a double value, taking into account endianess of the host, where big-endian is taken as-is and little-endian is byte-swapped.
static Ref MakeRaw (const std::string &producer, ACE_Message_Block *raw)
Class factory that creates new reference-counted TSPI message objects.
static Ref MakeRAE (const std::string &producer, const std::string &tag, double when, double range, double azimuth, double elevation)
Class factory that creates new reference-counted TSPI message objects from range, azimuth, and elevation values.
static Ref MakeLLH (const std::string &producer, const std::string &tag, double when, double latitude, double longitude, double height)
Class factory that creates new reference-counted TSPI message objects from latitude, longitude, and height values.
static Ref MakeXYZ (const std::string &producer, const std::string &tag, double when, double x, double y, double z)
Class factory that creates new reference-counted TSPI message objects using offsets from the radar position (given by RadarConfig)
static Ref Make (ACE_InputCDR &cdr)
Class factory that creates new reference-counted TSPI message objects using data from an input CDR stream.
Static Public Member Functions inherited from SideCar::Messages::Header
static Logger::Log & Log ()
Obtain log device to use for objects of this class.
static const MetaTypeInfo * GetMessageMetaTypeInfo (ACE_InputCDR &cdr)
Additional Inherited Members
Detailed Description
Definition at line 20 of file TSPI.h.
Member Function Documentation
void SideCar::Messages::TSPI::addAttribute (const std::string & name, const XmlRpc::XmlRpcValue & value) inline
Add an attribute to the position report.
Parameters
name the name of the value
value the value to use
Definition at line 310 of file TSPI.h.
const Attributes& SideCar::Messages::TSPI::getAttributes () const inline
Obtain the Attributes object for this report.
Returns
Attributes object
Definition at line 318 of file TSPI.h.
double SideCar::Messages::TSPI::getAzimuth () const inline
Obtain the azimuth component.
Returns
value in radians
Definition at line 244 of file TSPI.h.
Referenced by dump(), printData(), and printDataXML().
double SideCar::Messages::TSPI::getE () const inline
Obtain the E component of the earth-centered position.
Returns
E value
Definition at line 186 of file TSPI.h.
const double* SideCar::Messages::TSPI::getEarthCentered () const inline
Obtain the position in earth-centered coordinates.
Returns
earth-centered cartesian coordinates in meters
Definition at line 180 of file TSPI.h.
double SideCar::Messages::TSPI::getElevation () const inline
Obtain the elevation component.
Returns
value in radians
Definition at line 251 of file TSPI.h.
Referenced by dump(), printData(), and printDataXML().
double SideCar::Messages::TSPI::getF () const inline
Obtain the F component of the earth-centered position.
Returns
F value
Definition at line 192 of file TSPI.h.
double SideCar::Messages::TSPI::getG () const inline
Obtain the G component of the earth-centered position.
Returns
G value
Definition at line 198 of file TSPI.h.
double SideCar::Messages::TSPI::getHeight () const inline
Obtain the height component.
Returns
value in meters
Definition at line 224 of file TSPI.h.
Referenced by dump().
double SideCar::Messages::TSPI::getLatitude () const inline
Obtain the latitude component.
Returns
value in radians
Definition at line 210 of file TSPI.h.
Referenced by dump().
const TSPI::Coord & TSPI::getLatitudeLongitudeHeight () const
Obtain the position in latitude, longitude, height.
Returns
latitude (radians), longitude (radians), and height (meters).
Definition at line 320 of file TSPI.cc.
References LOGINFO.
double SideCar::Messages::TSPI::getLongitude () const inline
Obtain the longitude component.
Returns
value in radians
Definition at line 217 of file TSPI.h.
Referenced by dump().
const MetaTypeInfo & TSPI::GetMetaTypeInfo () static
Obtain the message type information for RawVideo objects.
Returns
MetaTypeInfo reference
Definition at line 36 of file TSPI.cc.
References SideCar::Messages::RadarConfig::GetSiteHeight(), SideCar::Messages::RadarConfig::GetSiteLatitude(), SideCar::Messages::RadarConfig::GetSiteLongitude(), and LOGINFO.
Referenced by MakeEFGCoordinateFromRawBytes().
double SideCar::Messages::TSPI::getRange () const inline
Obtain the range component.
Returns
value in meters
Definition at line 237 of file TSPI.h.
Referenced by dump(), printData(), and printDataXML().
const TSPI::Coord & TSPI::getRangeAzimuthElevation () const
Obtain the position in range, azimuth, elevation from the radar origin.
Returns
range (meters), azimuth (radians), elevation (radians)
Definition at line 351 of file TSPI.cc.
const std::string& SideCar::Messages::TSPI::getTag () const inline
Obtain the name assigned to the report.
Returns
name
Definition at line 288 of file TSPI.h.
double SideCar::Messages::TSPI::getWhen () const inline
Obtain the timestamp for the position report.
Returns
time value
Definition at line 282 of file TSPI.h.
double SideCar::Messages::TSPI::getX () const inline
Obtain the X component.
Returns
value in meters
Definition at line 264 of file TSPI.h.
Referenced by dump().
const TSPI::Coord & TSPI::getXYZ () const
Obtain the 3-D offsets from the radar origin.
Returns
x (meters), y (meters), z (meters) offsets from radar
Definition at line 378 of file TSPI.cc.
double SideCar::Messages::TSPI::getY () const inline
Obtain the Y component.
Returns
value in meters
Definition at line 270 of file TSPI.h.
Referenced by dump().
double SideCar::Messages::TSPI::getZ () const inline
Obtain the Z component.
Returns
value in meters
Definition at line 276 of file TSPI.h.
Referenced by dump().
bool SideCar::Messages::TSPI::isDropping () const inline
Determine if the report is dropping.
Returns
true if so
Definition at line 294 of file TSPI.h.
ACE_InputCDR & TSPI::load (ACE_InputCDR & cdr) virtual
Read in a TSPI message from an CDR input stream.
Override of Header::load().
Parameters
cdr stream to read from
Returns
stream read from
Reimplemented from SideCar::Messages::Header.
Definition at line 386 of file TSPI.cc.
References SideCar::Messages::Header::load(), SideCar::Messages::TLoaderRegistry< T >::load(), LOGDEBUG, and LOGINFO.
void TSPI::loadXML (XmlStreamReader & xsr) virtual
Set internal state from an XML message.
Parameters
xsr input XML stream to read from
Reimplemented from SideCar::Messages::Header.
Definition at line 456 of file TSPI.cc.
References SideCar::Messages::XmlStreamReader::getAttribute(), SideCar::Messages::Header::loadXML(), and SideCar::Messages::XmlStreamReader::readNextEntityAndValidate().
TSPI::Ref TSPI::Make (ACE_InputCDR & cdr) static
Class factory that creates new reference-counted TSPI message objects using data from an input CDR stream.
Parameters
cdr input CDR stream to read from
\return reference to new TSPI object
Definition at line 152 of file TSPI.cc.
References LOGINFO.
double TSPI::MakeEFGCoordinateFromRawBytes (const uint8_t * ptr) static
Utility that converts 4 raw bytes into a double value, taking into account endianess of the host, where big-endian is taken as-is and little-endian is byte-swapped.
Parameters
ptr address of 4 bytes to use
Returns
floating-point value
Definition at line 176 of file TSPI.cc.
References dump(), GetMetaTypeInfo(), SideCar::Messages::Header::Header(), LOGINFO, and Logger::ProcLog::showsDebug1().
TSPI::Ref TSPI::MakeLLH (const std::string & producer, const std::string & tag, double when, double latitude, double longitude, double height) static
Class factory that creates new reference-counted TSPI message objects from latitude, longitude, and height values.
Parameters
producer name of the entity that created the message
tag name for the TSPI plot
when time of the plot
\param latitude degrees latitude of the target
\param longitude degrees longitude of the target
\param height vertical distance to target in meters
\return reference to new TSPI object
Definition at line 136 of file TSPI.cc.
TSPI::Ref TSPI::MakeRAE (const std::string & producer, const std::string & tag, double when, double range, double azimuth, double elevation) static
Class factory that creates new reference-counted TSPI message objects from range, azimuth, and elevation values.
Parameters
producer name of the entity that created the message
tag name for the TSPI plot
when time of the plot
\param range distance (slant-range) to target in meters
\param azimuth angle from 0 north to target in radians
\param elevation angle from horizontal to target in radians
\param latitude degrees latitude of the target
\param longitude degrees longitude of the target
\param height vertical distance to target in meters
\return reference to new TSPI object
Definition at line 128 of file TSPI.cc.
TSPI::Ref TSPI::MakeRaw (const std::string & producer, ACE_Message_Block * raw) static
Class factory that creates new reference-counted TSPI message objects.
Parameters
producer name of the entity that is creating the new object
raw data block containing the raw TSPI message
\return reference to new TSPI object
Definition at line 116 of file TSPI.cc.
References LOGINFO.
Referenced by SideCar::IO::TSPIReaderTask::openAndInit().
TSPI::Ref TSPI::MakeXYZ (const std::string & producer, const std::string & tag, double when, double x, double y, double z) static
Class factory that creates new reference-counted TSPI message objects using offsets from the radar position (given by RadarConfig)
Parameters
producer name of the entity that created the message
tag name for the TSPI plot
when time of the plot
\param x north offset from radar in meters
\param y east offset from radar in meters
\param z up offset from radar in meters
\return reference to new TSPI object
Definition at line 144 of file TSPI.cc.
std::ostream & TSPI::printData (std::ostream & os) const virtual
Print out a textual representation of the TSPI message.
Override of Header::print().
Parameters
os C++ text stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Definition at line 435 of file TSPI.cc.
References getAzimuth(), getElevation(), and getRange().
std::ostream & TSPI::printDataXML (std::ostream & os) const virtual
Write out a TSPI message to a C++ output stream in XML format.
Parameters
os stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Definition at line 444 of file TSPI.cc.
References getAzimuth(), getElevation(), and getRange().
ACE_OutputCDR & TSPI::write (ACE_OutputCDR & cdr) const virtual
Write out a TSPI message to a CDR output stream.
Override of Header::write().
Parameters
cdr stream to write to
Returns
stream written to
Reimplemented from SideCar::Messages::Header.
Definition at line 422 of file TSPI.cc.
References SideCar::Messages::VoidLoaderRegistry::getCurrentVersion(), and SideCar::Messages::Header::write().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Messages/TSPI.h
/Users/howes/src/sidecar/Messages/TSPI.cc