SideCar: SideCar::GUI::RangeMap Class Reference
SideCar::GUI::RangeMap Class Reference
Set of points that define lines that make up a range map.
#include </Users/howes/src/sidecar/GUI/RangeMap.h>
Data Structures
struct LatLon
Structure of the raw point data in latitude/longitude.
Public Member Functions
RangeMap ()
Constructor.
virtual ~RangeMap ()
Destructor.
void render ()
Begin a OpenGL GL_LINE_STRIP and fill it with vertices generated by regenerateMap().
void clearMap ()
Protected Member Functions
virtual void generateMap ()
Create the vertices for the map by calling makeVertex() on each of the elements in the internal latitude/longitude map data.
virtual void addVertex (const Vertex &vertex)
Add a vertex to the cache.
bool empty () const
Determine if there is any data in the vertex cache.
Detailed Description
Set of points that define lines that make up a range map.
Supports rendering of the lines into an OpenGL buffer via the render() method (line color, thickness, etc. should be already at the time render() is called).
The first time render() method runs, it invokes regenerateMap() to build the set of line vertices. Derived classes may override regenerateMap() to receive notification that the map is being generated, and they will probably override addVertex() to change the vertex data before it is added to the map's line point vector.
Definition at line 21 of file RangeMap.h.
Member Function Documentation
void RangeMap::addVertex (const Vertex & vertex) protected virtual
Add a vertex to the cache.
Parameters
vertex the Vertex object to add.
Definition at line 298 of file RangeMap.cc.
Referenced by generateMap(), and ~RangeMap().
bool SideCar::GUI::RangeMap::empty () const inline protected
Determine if there is any data in the vertex cache.
Returns
true if so
Definition at line 66 of file RangeMap.h.
void RangeMap::generateMap () protected virtual
Create the vertices for the map by calling makeVertex() on each of the elements in the internal latitude/longitude map data.
Invokes makeVertex() followed by addVertex().
Definition at line 304 of file RangeMap.cc.
References addVertex().
Referenced by render(), and ~RangeMap().
void RangeMap::render ()
Begin a OpenGL GL_LINE_STRIP and fill it with vertices generated by regenerateMap().
Invokes regenerateMap() if there are no vertices. The OpenGL drawing environment must already be setup when render() is called.
Definition at line 315 of file RangeMap.cc.
References generateMap().
Referenced by SideCar::GUI::PPIDisplay::PPIWidget::initializeContext(), SideCar::GUI::BScope::PPIWidget::PPIWidget(), and ~RangeMap().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/RangeMap.h
/Users/howes/src/sidecar/GUI/RangeMap.cc