SideCar: SideCar::GUI::ESScope::CursorWidget Class Reference
SideCar::GUI::ESScope::CursorWidget Class Reference
QToolBar widget that shows the mouse cursor postion in real-world values such as range and sample value.
#include </Users/howes/src/sidecar/GUI/ESScope/CursorWidget.h>
Public Slots
void setAlphaBeta (double alpha, double beta)
void setRange (double dummy, double range)
void refresh ()
void refreshAlphaBeta ()
void refreshRange ()
Public Member Functions
CursorWidget (QWidget *parent=0)
Constructor.
Public Member Functions inherited from SideCar::GUI::CursorWidget
CursorWidget (QWidget *parent=0)
Constructor.
QString getValue () const
Additional Inherited Members
Protected Member Functions inherited from SideCar::GUI::CursorWidget
void setValue (const QString &value)
Detailed Description
QToolBar widget that shows the mouse cursor postion in real-world values such as range and sample value.
Updates to the widget come from the showCursorPosition() and setLastMessage() slots.
This class performs a lot of data caching in order to minimize the time spent in showCursorPosition(), and to speed up widget updates. Within showCursorPosition(), the class takes in the raw data, and sets various boolean flags if the raw data is different than what was seen before. An internal timer periodically checks the boolean flags to see if the widget needs an update. If so, the makeLabel() routine will rebuild a QString value for the widget's label text. The CursorWidget class keesp around the individual QString objects associated with raw values so that they only get regenerated by mouse position changes.
Definition at line 28 of file CursorWidget.h.
Constructor & Destructor Documentation
CursorWidget::CursorWidget (QWidget * parent = 0)
Constructor.
Creates and initializes window widgets.
Definition at line 14 of file CursorWidget.cc.
References SideCar::GUI::ESScope::App::GetApp(), SideCar::GUI::AppBase::getFormattedAngleRadians(), and SideCar::GUI::AppBase::getFormattedDistance().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/ESScope/CursorWidget.h
/Users/howes/src/sidecar/GUI/ESScope/CursorWidget.cc