SideCar: SideCar::GUI::Spectrum::SpectrographWidget Class Reference
SideCar::GUI::Spectrum::SpectrographWidget Class Reference
Public Slots
void clear ()
void processBins (const QVector< QPointF > &bins)
void needUpdate ()
void setFrozen (bool state)
Signals
void currentCursorPosition (const QPointF &pos)
Public Member Functions
SpectrographWidget (QWidget *parent=0)
Constructor.
Static Public Member Functions
static Logger::Log & Log ()
static QGLFormat GetGLFormat ()
Obtain the OpenGL configuration we want to use.
Detailed Description
Definition at line 26 of file SpectrographWidget.h.
Constructor & Destructor Documentation
SpectrographWidget::SpectrographWidget (QWidget * parent = 0)
Constructor.
Parameters
parent parent object
Definition at line 135 of file SpectrographWidget.cc.
References SideCar::GUI::VertexColorArray::checkCapacity(), SideCar::GUI::VertexColorArray::draw(), SideCar::GUI::Spectrum::App::GetApp(), SideCar::GUI::ChannelImaging::getSize(), LOGERROR, LOGINFO, and SideCar::GUI::VertexColorArray::push_back().
Member Function Documentation
QGLFormat SpectrographWidget::GetGLFormat () static
Obtain the OpenGL configuration we want to use.
Returns
OpenGL format
Definition at line 123 of file SpectrographWidget.cc.
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Spectrum/SpectrographWidget.h
/Users/howes/src/sidecar/GUI/Spectrum/SpectrographWidget.cc