SideCar: SideCar::Algorithms::CPIAlgorithm Class Reference
SideCar::Algorithms::CPIAlgorithm Class Reference abstract
Documentation for the algorithm CPIAlgorithm.
#include </Users/howes/src/sidecar/Algorithms/CPIAlgorithm.h>
Public Types
enum InfoSlots { kEnabled = ControllerStatus::kNumSlots, kNumSlots }
Public Member Functions
CPIAlgorithm (Controller &controller, Logger::Log &log, bool enabled, int span)
Constructor.
bool startup ()
Implementation of the Algorithm::startup interface.
bool shutdown ()
Implementation of the Algorithm::shutdown interface.
size_t maxMsgSize () const
Public Member Functions inherited from SideCar::Algorithms::Algorithm
Algorithm (Controller &controller, Logger::Log &log)
Constructor.
virtual ~Algorithm ()
Destructor.
Controller & getController () const
Obtain the Controller object managing the algorithm.
Logger::Log & getLog () const
Obtain the log device to use for by the algorithm for log messages.
const std::string & getName () const
Obtain the name of the algorithm.
bool registerParameter (const Parameter::Ref &parameter)
Add a configuration parameter to the runtime system.
bool unregisterParameter (const Parameter::Ref &parameter)
Remove a configuration parameter from the runtime system.
template<typename A , typename M >
void registerProcessor (boost::function< bool(A *, typename M::Ref)> proc)
Install a method to process a particular message type.
template<typename A , typename M >
void registerProcessor (const std::string &channelName, boost::function< bool(A *, typename M::Ref)> proc)
Same as above method, but allows user to pick the channel by name.
template<typename A , typename M >
void registerProcessor (size_t channelIndex, boost::function< bool(A *, typename M::Ref)> proc)
Same as above method, but allows user to pick the channel by index.
template<typename A >
void registerProcessor (const std::string &channelName, const Messages::MetaTypeInfo &metaTypeInfo, boost::function< bool(A *, typename Messages::Header::Ref)> proc)
template<typename A >
void registerProcessor (size_t channelIndex, const Messages::MetaTypeInfo &metaTypeInfo, boost::function< bool(A *, typename Messages::Header::Ref)> proc)
size_t addProcessor (const std::string &channelName, const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
size_t addProcessor (const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
size_t addProcessor (size_t index, const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
void removeProcessor (size_t index)
Remove a processor from a given channel.
size_t getOutputChannelIndex (const std::string &name) const
Obtain an output channel index with a given name.
bool send (const Messages::Header::Ref &msg, size_t channelIndex=0)
Submit a message object to the controller for sending out on a given data channel.
bool sendAsIs (const Messages::Header::Ref &msg, size_t channelIndex=0)
Hand a message to the controller for sending out on a given data channel.
size_t getActiveChannelIndex () const
Obtain the index of the input channel that last received a message for the algorithm to process.
Static Public Member Functions
static QString GetFormattedStats (const IO::StatusBase &status)
Static Public Member Functions inherited from SideCar::Algorithms::Algorithm
static void * FormatInfoValue (const QString &value)
Obtain a C-safe value for the given QString string.
static void * FormatInfoValue (const char *value)
Obtain a C-safe value for the given character string.
Protected Types
using MessageQueue = std::deque< Messages::PRIMessage::Ref >
Protected Member Functions
size_t getNumInfoSlots () const
Obtain the number of data slots found in the ControllerStatus XML array.
void setInfoSlots (IO::StatusBase &status)
Obtain custom status information from an algorithm.
virtual bool processCPI ()=0
Protected Member Functions inherited from SideCar::Algorithms::Algorithm
void setAlarm (int secs)
This method can be used by an Algorithm to schedule a periodic alarm to go off for itself.
virtual bool reset ()
Hook called when the algorithm is transitioning from a stopped to a running state (one of Task::kAutoDiagnostic, Task::kCalibrate, or Task::kRun).
virtual bool clearStats ()
Hook called when the algorithm is commaned to clear any statistics.
virtual bool beginAutoDiag ()
Hook called when the algorithm is entering the Task::kAutoDiagnostic state.
virtual bool beginCalibration ()
Hook called when the algorithm is entering the Task::kCalibrate state.
virtual bool beginRun ()
Hook called when the algorithm is entering the Task::kRun state.
virtual bool stop ()
Hook called when the algorithm is entering the Task::kStop state.
virtual void recordingStarted ()
Hook called when a recording has started.
virtual void recordingStopped ()
Hook called when a recording has stopped.
virtual void beginParameterChanges ()
Hook called just before algorithm runtime parameters are changed.
virtual void endParameterChanges ()
Hook called just after algorithm runtime parameters have been changed.
virtual void processAlarm ()
This method will get called whenever an alarm expires for this Algorithm.
Protected Attributes
Parameter::PositiveIntValue::Ref cpiSpan_
MessageQueue buffer_
Detailed Description
Documentation for the algorithm CPIAlgorithm.
Please describe what the algorithm does, in layman's terms and, if possible, mathematical terms.
Definition at line 19 of file CPIAlgorithm.h.
Constructor & Destructor Documentation
CPIAlgorithm::CPIAlgorithm (Controller & controller, Logger::Log & log, bool enabled, int span)
Constructor.
Parameters
controller object that controls us
log device used for log messages
Definition at line 18 of file CPIAlgorithm.cc.
Member Function Documentation
size_t SideCar::Algorithms::CPIAlgorithm::getNumInfoSlots () const inline protected virtual
Obtain the number of data slots found in the ControllerStatus XML array.
Any custom Algorithm slots will appear after the last defined ControllerStatus slot. NOTE: implementations must be thread-safe, since this routine will execute in the alorithm's StatusEmitter thread.
Returns
ControllerStats::kNumSlots
Reimplemented from SideCar::Algorithms::Algorithm.
Definition at line 59 of file CPIAlgorithm.h.
References setInfoSlots().
void CPIAlgorithm::setInfoSlots (IO::StatusBase & status) protected virtual
Obtain custom status information from an algorithm.
All algorithms report generic status information to external entities via the ControllerStatus object. However, an algorithm with special reporting needs can provide custom data by appending to array whatever values it wants. NOTE: implementations must be thread-safe, since this routine will execute in the algorithm's StatusEmitter thread.
\param array container to hold the custom status information
Reimplemented from SideCar::Algorithms::Algorithm.
Definition at line 137 of file CPIAlgorithm.cc.
References SideCar::IO::StatusBase::setSlot().
Referenced by getNumInfoSlots().
bool CPIAlgorithm::shutdown () virtual
Implementation of the Algorithm::shutdown interface.
Dispose of any resources (such as memory) allocated from within the startup() method.
Returns
true if successful, false otherwise
Reimplemented from SideCar::Algorithms::Algorithm.
Reimplemented in SideCar::Algorithms::CPISimpleOp, SideCar::Algorithms::RGBConverter, SideCar::Algorithms::CPIIntegrate, and SideCar::Algorithms::SpreadMofN.
Definition at line 61 of file CPIAlgorithm.cc.
References SideCar::Algorithms::Controller::addProcessingStatSample(), SideCar::Algorithms::Algorithm::getController(), SideCar::Algorithms::Algorithm::getLog(), LOGDEBUG, LOGINFO, SideCar::Time::TimeStamp::Now(), and SideCar::Algorithms::Algorithm::shutdown().
Referenced by SideCar::Algorithms::CPIIntegrate::shutdown(), SideCar::Algorithms::SpreadMofN::shutdown(), SideCar::Algorithms::RGBConverter::shutdown(), and SideCar::Algorithms::CPISimpleOp::shutdown().
bool CPIAlgorithm::startup () virtual
Implementation of the Algorithm::startup interface.
Register runtime parameters and data processors.
Returns
true if successful, false otherwise
Reimplemented from SideCar::Algorithms::Algorithm.
Reimplemented in SideCar::Algorithms::CPISimpleOp, SideCar::Algorithms::RangeDopplerMap, SideCar::Algorithms::RGBConverter, SideCar::Algorithms::CPIIntegrate, and SideCar::Algorithms::SpreadMofN.
Definition at line 35 of file CPIAlgorithm.cc.
References SideCar::Algorithms::Algorithm::getController(), SideCar::Messages::MetaTypeInfo::getKey(), SideCar::Messages::BinaryVideo::GetMetaTypeInfo(), SideCar::Messages::Video::GetMetaTypeInfo(), SideCar::IO::Channel::getTypeKey(), SideCar::Algorithms::Algorithm::registerParameter(), SideCar::Algorithms::Controller::setStatsManaged(), and SideCar::Algorithms::Algorithm::startup().
Referenced by SideCar::Algorithms::CPIIntegrate::startup(), SideCar::Algorithms::SpreadMofN::startup(), SideCar::Algorithms::RGBConverter::startup(), SideCar::Algorithms::RangeDopplerMap::startup(), and SideCar::Algorithms::CPISimpleOp::startup().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/CPIAlgorithm.h
/Users/howes/src/sidecar/Algorithms/CPIAlgorithm.cc