SideCar: SideCar::GUI::PresetManager Class Reference
SideCar::GUI::PresetManager Class Reference
Manager for Preset objects and associated Setting objects.
#include </Users/howes/src/sidecar/GUI/PresetManager.h>
Public Slots
virtual bool applyPreset (int index)
Make an indicated Preset object active, and apply its values to registered Setting objects.
virtual void restoreAllPresets ()
Restore preset settings and global values from a QSettings file.
virtual void saveAllPresets (bool saveChanges=true)
Save all preset settings and global values to a QSettings file.
Signals
void presetDirtyStateChanged (int index, bool isDirty)
Notification sent out when a preset's dirty state changes.
void activePresetChanged (int index)
Notification sent out when the active preset changes.
void presetNamesChanged (const QStringList &names)
Notification sent out when the list of preset names changes due to preset addition, removal, or name change.
Public Member Functions
PresetManager (const QString &prefix, QObject *parent=0)
Constructor.
size_t addSetting (Setting *setting, bool global=false)
Add a Setting object to the list of preset values.
virtual QVariant upgradeSetting (const QString &name, const QVariant &value)
Setting * getSetting (int index) const
Obtain a preset Setting object at a given index.
Setting * getSetting (const QString &name) const
Obtain a preset Setting object with a given name.
Setting * getGlobal (int index) const
Obtain a global Setting object at a given index.
Setting * getGlobal (const QString &name) const
Preset * getPreset (const QString &name) const
bool isRestoring () const
virtual void savePreset (int index)
Save the values associated with a specific preset.
virtual void restorePreset (int index)
Restore the values associated with a specific preset.
virtual bool addPreset (const QString &name)
Create a new Preset object, duplicated from the active Preset object, and save it.
virtual bool removePreset (int index)
Remove an existing Preset object.
QStringList getPresetNames () const
Obtain a list of names of defined Preset objects.
const QString & getPresetName (int index) const
Obtain the name of a particular Preset object.
int getActivePresetIndex () const
Obtain the index of the active preset.
bool getPresetIsDirty (int index) const
Determine if a given preset has changed since it was last saved to disk.
bool getAnyIsDirty () const
Determine if any preset has changed since it was last saved to disk.
bool getActiveIsDirty () const
Determine if the active preset is 'dirty', containing a Settting object with a value different than what is saved in the QSettings file.
virtual int getCurrentVersion () const
int getSavedVersion () const
bool isOldVersion () const
Static Public Member Functions
static Logger::Log & Log ()
Protected Slots
void settingSave (int index, const QVariant &value)
Save one preset Setting object to a QSettings file.
void globalSave (int index, const QVariant &value)
Save one global Setting object to a QSettings file.
Detailed Description
Manager for Preset objects and associated Setting objects.
A Preset contains a set of values for a collection of Setting objects. When a Setting object changes due to a GUI widget change or programatically, the PresetManager saves the new setting value in a QSettings file. When the active Preset object changes due to a call to applyPreset(), all Setting objects receive new values from the active Preset object.
Definition at line 24 of file PresetManager.h.
Constructor & Destructor Documentation
PresetManager::PresetManager (const QString & prefix, QObject * parent = 0)
Constructor.
Parameters
prefix name to use for this collection of presets.
parent optional parent used for Qt automated destruction
Definition at line 27 of file PresetManager.cc.
Member Function Documentation
void SideCar::GUI::PresetManager::activePresetChanged (int index) signal
Notification sent out when the active preset changes.
Parameters
index which preset is active
Referenced by addPreset(), applyPreset(), removePreset(), and restoreAllPresets().
bool PresetManager::addPreset (const QString & name) virtual
Create a new Preset object, duplicated from the active Preset object, and save it.
Parameters
name name of the new Preset object
Definition at line 369 of file PresetManager.cc.
References activePresetChanged(), getPresetNames(), and presetNamesChanged().
Referenced by SideCar::GUI::PresetsWindow::PresetsWindow().
size_t PresetManager::addSetting (Setting * setting, bool global = false)
Add a Setting object to the list of preset values.
A preset Setting object has values stored in Preset objects, and thus they may change values when the active Preset object changes.
Parameters
setting the Setting object to register
global if true, register as a global setting
\return internal index of the Setting object that may be used in a
later getSetting() call.
Definition at line 233 of file PresetManager.cc.
References SideCar::GUI::Setting::getName(), SideCar::GUI::Setting::getOpaqueValue(), globalSave(), SideCar::GUI::Setting::setOpaqueValue(), and settingSave().
Referenced by SideCar::GUI::Setting::Setting().
bool PresetManager::applyPreset (int index) virtual slot
Make an indicated Preset object active, and apply its values to registered Setting objects.
Parameters
index the index of the Preset object to make active
Definition at line 463 of file PresetManager.cc.
References activePresetChanged().
Referenced by SideCar::GUI::PresetsWindow::PresetsWindow().
bool SideCar::GUI::PresetManager::getActiveIsDirty () const inline
Determine if the active preset is 'dirty', containing a Settting object with a value different than what is saved in the QSettings file.
Returns
if so
See also
getPresetIsDirty(), getAnyIsDirty()
Definition at line 155 of file PresetManager.h.
Referenced by SideCar::GUI::BScope::MainWindow::initialize(), SideCar::GUI::PPIDisplay::MainWindow::MainWindow(), SideCar::GUI::ESScope::MainWindow::MainWindow(), and settingSave().
int SideCar::GUI::PresetManager::getActivePresetIndex () const inline
Obtain the index of the active preset.
Returns
Definition at line 131 of file PresetManager.h.
Referenced by SideCar::GUI::BScope::MainWindow::initialize(), SideCar::GUI::PPIDisplay::MainWindow::MainWindow(), SideCar::GUI::ESScope::MainWindow::MainWindow(), and SideCar::GUI::PresetsWindow::PresetsWindow().
bool PresetManager::getAnyIsDirty () const
Determine if any preset has changed since it was last saved to disk.
Returns
true if so
See also
getPresetIsDirty()
Definition at line 499 of file PresetManager.cc.
Setting* SideCar::GUI::PresetManager::getGlobal (int index) const inline
Obtain a global Setting object at a given index.
Parameters
index the index of the Setting object to return
Returns
Setting object
Definition at line 79 of file PresetManager.h.
Referenced by getSetting().
bool PresetManager::getPresetIsDirty (int index) const
Determine if a given preset has changed since it was last saved to disk.
Parameters
index which index to check
Returns
true if so
See also
getAnyIsDirty()
Definition at line 490 of file PresetManager.cc.
Referenced by SideCar::GUI::PresetsWindow::PresetsWindow(), and saveAllPresets().
const QString & PresetManager::getPresetName (int index) const
Obtain the name of a particular Preset object.
Parameters
index which preset to work with
Returns
Preset name
Definition at line 52 of file PresetManager.cc.
Referenced by SideCar::GUI::PresetsWindow::PresetsWindow().
QStringList PresetManager::getPresetNames () const
Obtain a list of names of defined Preset objects.
Returns
QString list
Definition at line 41 of file PresetManager.cc.
Referenced by addPreset(), SideCar::GUI::PresetsWindow::PresetsWindow(), removePreset(), and restoreAllPresets().
Setting* SideCar::GUI::PresetManager::getSetting (int index) const inline
Obtain a preset Setting object at a given index.
Parameters
index the index of the Setting object to return
Returns
Setting object
Definition at line 62 of file PresetManager.h.
Referenced by SideCar::GUI::Preset::setValue().
Setting * PresetManager::getSetting (const QString & name) const
Obtain a preset Setting object with a given name.
Parameters
name
Returns
Definition at line 293 of file PresetManager.cc.
References getGlobal().
void PresetManager::globalSave (int index, const QVariant & value) protected slot
Save one global Setting object to a QSettings file.
Parameters
index the index of the Setting object to save
value the new value of the Setting object
Definition at line 353 of file PresetManager.cc.
Referenced by addSetting().
void SideCar::GUI::PresetManager::presetDirtyStateChanged (int index, bool isDirty) signal
Notification sent out when a preset's dirty state changes.
Parameters
index which preset changed
isDirty true if the preset is dirty, false if not
Referenced by restoreAllPresets(), restorePreset(), saveAllPresets(), savePreset(), and settingSave().
void SideCar::GUI::PresetManager::presetNamesChanged (const QStringList & names) signal
Notification sent out when the list of preset names changes due to preset addition, removal, or name change.
Parameters
names the list of current preset names
Referenced by addPreset(), removePreset(), and restoreAllPresets().
bool PresetManager::removePreset (int index) virtual
Remove an existing Preset object.
If the Preset object is the active one, the changes the active Preset object to the default one.
Parameters
index the index of the Preset object to remove
Definition at line 413 of file PresetManager.cc.
References activePresetChanged(), getPresetNames(), and presetNamesChanged().
Referenced by SideCar::GUI::PresetsWindow::PresetsWindow().
void PresetManager::restorePreset (int index) virtual
Restore the values associated with a specific preset.
Parameters
index which preset to restore
Definition at line 197 of file PresetManager.cc.
References presetDirtyStateChanged().
Referenced by SideCar::GUI::BScope::MainWindow::initialize(), SideCar::GUI::PPIDisplay::MainWindow::MainWindow(), SideCar::GUI::ESScope::MainWindow::MainWindow(), and SideCar::GUI::PresetsWindow::PresetsWindow().
void PresetManager::savePreset (int index) virtual
Save the values associated with a specific preset.
Parameters
index which preset to save
Definition at line 216 of file PresetManager.cc.
References presetDirtyStateChanged().
Referenced by SideCar::GUI::BScope::MainWindow::initialize(), SideCar::GUI::PPIDisplay::MainWindow::MainWindow(), SideCar::GUI::ESScope::MainWindow::MainWindow(), and SideCar::GUI::PresetsWindow::PresetsWindow().
void PresetManager::settingSave (int index, const QVariant & value) protected slot
Save one preset Setting object to a QSettings file.
Parameters
index the index of the Setting object to save
value the new value of the Setting object
Definition at line 315 of file PresetManager.cc.
References getActiveIsDirty(), LOGDEBUG, LOGINFO, and presetDirtyStateChanged().
Referenced by addSetting().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/PresetManager.h
/Users/howes/src/sidecar/GUI/PresetManager.cc