SideCar: SideCar::GUI::Master::RunnerLog Class Reference
SideCar::GUI::Master::RunnerLog Class Reference
Log message collector object for a Runner applications.
#include </Users/howes/src/sidecar/GUI/Master/RunnerLog.h>
Public Slots
void showWindow ()
Show the log window.
Public Member Functions
~RunnerLog ()
Destructor.
void appendLogMessages (const XmlRpc::XmlRpcValue &logMessages)
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device to use for RunnerLog objects.
static RunnerLog * Find (const QString &serviceName)
static void Make (const QString &name, const QString &configName, const QString &serviceName)
static void CleanUp ()
Detailed Description
Log message collector object for a Runner applications.
Runner applications can run anywhere on the SideCar LAN. While they run, they deposite log messages into a well-known file on their host machine:
<DIR>/runner_<CONFIG>_<TAG>.log,
where <DIR> is the value of the 'logOutputBasePath' XML attribute from the configuration file; <CONFIG> is the name of the configuration file defining the Runner; and <TAG> is the optional 'tag' attribute value in the host stanza of the configuration file that generated the Runner instance.
This class runs a tail command on host where the log file exists, and appends output from it to an internal QTextDocument object. A separate LogViewWindow object may be opened to view the contents of the QTextDocument object.
The RunnerLog objects exist as singletons: once created, they never disappear from the Master application, since they can always access the remote log data. The RunnerLog restarts its log monitoring process when its restart() method is called. Currently, this is called when a new Runner process appears to the application's ServicesModel object, and there is already an active RunnerLog for the Runner's name / configuration tuple.
Definition at line 45 of file RunnerLog.h.
Constructor & Destructor Documentation
RunnerLog::~RunnerLog ()
Destructor.
Closes and deletes any managed LogWindow.
Definition at line 98 of file RunnerLog.cc.
Member Function Documentation
RunnerLog * RunnerLog::Find (const QString & serviceName) static
Parameters
runnerName
configName
Returns
Definition at line 38 of file RunnerLog.cc.
References LOGINFO.
Referenced by SideCar::GUI::Master::RunnerItem::afterUpdate(), SideCar::GUI::Master::RunnerItem::getChild(), SideCar::GUI::Master::LogViewWindowManager::removeConfiguration(), and SideCar::GUI::Master::ServicesView::rowsInserted().
Logger::Log & RunnerLog::Log () static
Obtain the log device to use for RunnerLog objects.
Returns
Log device
Definition at line 31 of file RunnerLog.cc.
References Logger::Log::Find().
Referenced by SideCar::GUI::Master::ServicesModel::getChangedParameters().
void RunnerLog::Make (const QString & name, const QString & configName, const QString & serviceName) static
Parameters
runnerName
configName
Returns
Definition at line 55 of file RunnerLog.cc.
References SideCar::GUI::Master::App::GetApp(), and LOGINFO.
Referenced by SideCar::GUI::Master::LogViewWindowManager::addLogInfo().
void RunnerLog::showWindow () slot
Show the log window.
Creates a new LogViewWindow if none exits.
Definition at line 107 of file RunnerLog.cc.
References Logger::Priority::GetLongName(), LOGDEBUG, LOGINFO, and XmlRpc::XmlRpcValue::size().
Referenced by SideCar::GUI::Master::LogViewWindowManager::removeConfiguration(), and SideCar::GUI::Master::ServicesView::rowsInserted().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Master/RunnerLog.h
/Users/howes/src/sidecar/GUI/Master/RunnerLog.cc