SideCar: SideCar::Zeroconf::Transaction Class Reference
SideCar::Zeroconf::Transaction Class Reference
Base class for all Zeroconf classes that interact with the DNSSD library.
#include </Users/howes/src/sidecar/Zeroconf/Transaction.h>
Public Types
using Ref = boost::shared_ptr< Transaction >
Public Member Functions
virtual ~Transaction ()
Destructor.
bool stop ()
Stop a Zeroconf service.
bool isRunning () const
Determine if a Zeroconf service is running.
int getConnection () const
Obtain the underlying IPC descriptor used to communicate with the Zeroconf daemon.
bool processConnection ()
Data is available from the Zeroconf daemon.
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for all Transaction objects.
Protected Member Functions
Transaction (Monitor *monitor)
Constructor.
virtual void serviceStarted ()
Hook for derived classes for notification that a service has started.
virtual void serviceStopping ()
Hook for derived classes for notification that a sservice is being stopped.
void setSelf (const Ref &self)
Set a weak reference to ourselves so that we can give out shared_ptr refences to ourselves.
void finished ()
void finish ()
template<typename T >
boost::shared_ptr< T > getSelf () const
Obtain a shared_ptr reference to ourselves.
DNSServiceRef & getDNSServiceRef ()
const DNSServiceRef & getDNSServiceRef () const
Detailed Description
Base class for all Zeroconf classes that interact with the DNSSD library.
Holds a opaque connection to the DNSSD library whenever a transaction with the library is in progress. The class requires external monitoring of the DNSSD connection by instances of the Monitor class. The Transaction class contains connection-neutral policy.
Derived classes may override serviceStarted() and serviceStopping() methods to receive notification when those events occur. However, the overrides must invoke the methods in this class to maintain proper monitor behavior.
Definition at line 25 of file Transaction.h.
Constructor & Destructor Documentation
Transaction::~Transaction () virtual
Destructor.
NOTE: if service is running when this is reached, bad things are probably in the works. At this point we cannot dispatch virtual methods correctly, so the best we can do is tell our held Monitor object to stop.
Definition at line 22 of file Transaction.cc.
References Log(), LOGINFO, and stop().
Transaction::Transaction (Monitor * monitor) protected
Constructor.
Restricted to derived classes.
Definition at line 16 of file Transaction.cc.
Referenced by SideCar::Zeroconf::ServiceEntry::Make().
Member Function Documentation
int SideCar::Zeroconf::Transaction::getConnection () const inline
Obtain the underlying IPC descriptor used to communicate with the Zeroconf daemon.
Returns
valid IPC descriptor, or -1 if not running
Definition at line 58 of file Transaction.h.
Referenced by SideCar::Zeroconf::ACEMonitor::~ACEMonitor(), and SideCar::GUI::QtMonitor::~QtMonitor().
template<typename T > boost::shared_ptr<T> SideCar::Zeroconf::Transaction::getSelf () const inline protected
Obtain a shared_ptr reference to ourselves.
The template parameter indicates a derived class that is the actual type of 'this'.
\return new shared_ptr reference
Definition at line 99 of file Transaction.h.
bool SideCar::Zeroconf::Transaction::isRunning () const inline
Determine if a Zeroconf service is running.
Returns
true if so
Definition at line 52 of file Transaction.h.
Referenced by SideCar::Zeroconf::Publisher::postTextData(), processConnection(), SideCar::Zeroconf::Publisher::publish(), SideCar::Zeroconf::ServiceEntry::resolve(), SideCar::Zeroconf::Browser::start(), and stop().
Logger::Log & Transaction::Log () static
Obtain the log device for all Transaction objects.
Returns
log device
Definition at line 10 of file Transaction.cc.
References Logger::Log::Find().
Referenced by processConnection(), serviceStarted(), serviceStopping(), stop(), and ~Transaction().
bool Transaction::processConnection ()
Data is available from the Zeroconf daemon.
Let the DNSSD library do its work. NOTE: this should not be called unless there really is data available, otherwise it will block until there is data.
Returns
true if successful, false if not running or error
Definition at line 58 of file Transaction.cc.
References isRunning(), Log(), LOGINFO, and stop().
Referenced by SideCar::Zeroconf::ACEMonitor::~ACEMonitor(), and SideCar::GUI::QtMonitor::~QtMonitor().
void Transaction::serviceStarted () protected virtual
Hook for derived classes for notification that a service has started.
At this point, a call to getConnection() should not return -1.
Definition at line 42 of file Transaction.cc.
References Log(), and LOGINFO.
Referenced by SideCar::Zeroconf::Publisher::publish(), SideCar::Zeroconf::ServiceEntry::resolve(), and SideCar::Zeroconf::Browser::start().
void Transaction::serviceStopping () protected virtual
Hook for derived classes for notification that a sservice is being stopped.
At this point, a call to getConnection() still should not return -1, but afterwards it will.
Definition at line 50 of file Transaction.cc.
References Log(), and LOGINFO.
Referenced by SideCar::Zeroconf::Publisher::notifyObservers(), and stop().
void SideCar::Zeroconf::Transaction::setSelf (const Ref & self) inline protected
Set a weak reference to ourselves so that we can give out shared_ptr refences to ourselves.
Parameters
self reference to initialize with
Definition at line 87 of file Transaction.h.
bool Transaction::stop ()
Stop a Zeroconf service.
Returns
true if successful, false otherwise
Definition at line 30 of file Transaction.cc.
References isRunning(), Log(), LOGINFO, and serviceStopping().
Referenced by processConnection(), SideCar::Zeroconf::Publisher::publish(), SideCar::Zeroconf::ServiceEntry::resolve(), SideCar::Zeroconf::Browser::start(), SideCar::Zeroconf::Browser::~Browser(), and ~Transaction().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Zeroconf/Transaction.h
/Users/howes/src/sidecar/Zeroconf/Transaction.cc