SideCar: SideCar::Zeroconf::ResolvedEntry Class Reference
SideCar::Zeroconf::ResolvedEntry Class Reference
Contains information obtained from resolving a ServiceEntry object.
#include </Users/howes/src/sidecar/Zeroconf/ResolvedEntry.h>
Public Types
using StringMap = std::map< std::string, std::string >
Public Member Functions
ResolvedEntry (const std::string &fullName, const std::string &host, uint16_t port, uint16_t textSize, const unsigned char *textData)
Constructor.
const std::string & getFullName () const
Obtain the full name of the service.
const std::string & getNativeHost () const
const std::string & getHost () const
Obtain the host where the service is running.
uint16_t getPort () const
Obtain the port where the service is running.
const StringMap & getTextEntries () const
Obtain the TXT record of the entry as a key/value map.
bool hasTextEntry (const std::string &key, std::string *value=0) const
Determine if a key exist in the TXT record.
std::string getTextEntry (const std::string &key) const
Obtain the value in a TXT record for a given key.
Detailed Description
Contains information obtained from resolving a ServiceEntry object.
In the Zeroconf world, services found by a Browser do not reveal concrete connection information, they only contain a name and a type. Client applications of a Browser must ask a ServiceEntry for its connection information via ServiceEntry::resolve(). This queries the multicast DNS server running locally, which returns the host/port connection pair.
Definition at line 16 of file ResolvedEntry.h.
Constructor & Destructor Documentation
ResolvedEntry::ResolvedEntry (const std::string & fullName, const std::string & host, uint16_t port, uint16_t textSize, const unsigned char * textData)
Constructor.
Fills in a new ResolvedEntry object with information from the mdns server.
Parameters
fullName the full service name
host the host identifier where the service is running
port the port of the host where the service is running
textSize the number of bytes in the entry's TXT record
textData a pointer to the first byte of TXT record data
Definition at line 7 of file ResolvedEntry.cc.
References hasTextEntry().
Member Function Documentation
const std::string& SideCar::Zeroconf::ResolvedEntry::getFullName () const inline
Obtain the full name of the service.
Returns
full name
Definition at line 40 of file ResolvedEntry.h.
Referenced by SideCar::GUI::ServiceEntry::hasTextEntry(), SideCar::IO::StateEmitter::Log(), and SideCar::IO::StatusEmitterBase::Log().
const std::string& SideCar::Zeroconf::ResolvedEntry::getHost () const inline
Obtain the host where the service is running.
Returns
host identifier
Definition at line 48 of file ResolvedEntry.h.
Referenced by SideCar::IO::DataSubscriber::close(), SideCar::GUI::ServiceEntry::hasTextEntry(), SideCar::IO::StateEmitter::Log(), SideCar::IO::StatusEmitterBase::Log(), SideCar::Algorithms::BugCollectorUtils::BugPlotReader::openAndInit(), and SideCar::IO::TCPDataSubscriber::setServiceName().
uint16_t SideCar::Zeroconf::ResolvedEntry::getPort () const inline
Obtain the port where the service is running.
Returns
port id
Definition at line 54 of file ResolvedEntry.h.
Referenced by SideCar::IO::DataSubscriber::close(), SideCar::GUI::ServiceEntry::getPort(), SideCar::GUI::ServiceEntry::hasTextEntry(), SideCar::IO::StateEmitter::Log(), SideCar::IO::StatusEmitterBase::Log(), SideCar::Algorithms::BugCollectorUtils::BugPlotReader::openAndInit(), and SideCar::IO::TCPDataSubscriber::setServiceName().
const StringMap& SideCar::Zeroconf::ResolvedEntry::getTextEntries () const inline
Obtain the TXT record of the entry as a key/value map.
Returns
read-only string map
Definition at line 60 of file ResolvedEntry.h.
References getTextEntry(), and hasTextEntry().
std::string ResolvedEntry::getTextEntry (const std::string & key) const
Obtain the value in a TXT record for a given key.
Parameters
key the value to search for
Returns
true if key found, false otherwise
Definition at line 49 of file ResolvedEntry.cc.
Referenced by getTextEntries(), SideCar::GUI::ServiceEntry::hasTextEntry(), and SideCar::Algorithms::BugCollectorUtils::BugPlotReader::openAndInit().
bool ResolvedEntry::hasTextEntry (const std::string & key, std::string * value = 0) const
Determine if a key exist in the TXT record.
Parameters
key the value to search for
value if non-zero, storage for the value found for the given key
Returns
true if key found, false otherwise
Definition at line 37 of file ResolvedEntry.cc.
Referenced by getTextEntries(), SideCar::GUI::ServiceEntry::hasTextEntry(), and ResolvedEntry().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Zeroconf/ResolvedEntry.h
/Users/howes/src/sidecar/Zeroconf/ResolvedEntry.cc