SideCar: SideCar::IO::StatusBase Class Reference
SideCar::IO::StatusBase Class Reference
Base class for all status collections.
#include </Users/howes/src/sidecar/IO/StatusBase.h>
Public Types
enum Index { kVersion = 0, kClassName, kName, kNumSlots }
Indices for status elements managed by this class.
Public Member Functions
StatusBase (size_t numSlots, const std::string &className, const std::string &name)
StatusBase (const XmlRpc::XmlRpcValue &status)
Conversion constructor.
const XmlRpc::XmlRpcValue & getXMLData () const
Creates an XML value from the internal data.
bool isValid () const
Determine if the held value is valid.
const XmlRpc::XmlRpcValue & getSlot (size_t index) const
Obtain a status value at a particular index.
void setSlot (size_t index, const XmlRpc::XmlRpcValue &value)
Obtain a status value at a particular index.
std::string getVersion () const
bool isLatestVersion () const
std::string getClassName () const
Obtain the class name held in the status container.
std::string getName () const
Obtain the object name held in the status container.
const XmlRpc::XmlRpcValue & operator[] (size_t index) const
bool operator== (const StatusBase &rhs) const
Determine if the held status information is the same as that in another status container.
bool operator!= (const StatusBase &rhs) const
Determine if the held status information is not the same as that in another status container.
std::ostream & print (std::ostream &os) const
Print out an XML representation of the held status values.
Static Public Member Functions
static std::string GetCompiledVersion ()
static void Make (XmlRpc::XmlRpcValue &status, size_t numSlots, const std::string &className, const std::string &name)
Detailed Description
Base class for all status collections.
A status collection is a vector of XML-RPC values that is sent out by a StatusEmitter object to one or more listening StatusCollector objects.
The base collection contains the class name of the status collection, and the name of the object that filled in the status.
Definition at line 19 of file StatusBase.h.
Constructor & Destructor Documentation
SideCar::IO::StatusBase::StatusBase (const XmlRpc::XmlRpcValue & status) inline
Conversion constructor.
Acquires status values from an XML-RPC container.
Parameters
status values to acquire
Definition at line 47 of file StatusBase.h.
Member Function Documentation
std::string SideCar::IO::StatusBase::getClassName () const inline
Obtain the class name held in the status container.
Returns
class name
Definition at line 85 of file StatusBase.h.
References getSlot().
std::string SideCar::IO::StatusBase::getName () const inline
Obtain the object name held in the status container.
Returns
object name
Definition at line 91 of file StatusBase.h.
References getSlot().
const XmlRpc::XmlRpcValue& SideCar::IO::StatusBase::getSlot (size_t index) const inline
Obtain a status value at a particular index.
Parameters
index location to fetch
Returns
read-only reference to found value
Definition at line 67 of file StatusBase.h.
Referenced by getClassName(), SideCar::IO::TaskStatus::getMessageCount(), getName(), SideCar::IO::TaskStatus::getProcessingState(), and setSlot().
const XmlRpc::XmlRpcValue& SideCar::IO::StatusBase::getXMLData () const inline
Creates an XML value from the internal data.
Returns
Definition at line 53 of file StatusBase.h.
Referenced by SideCar::IO::Stream::fillStatus().
bool SideCar::IO::StatusBase::isValid () const inline
Determine if the held value is valid.
Returns
true if so
Definition at line 59 of file StatusBase.h.
References XmlRpc::XmlRpcValue::valid().
bool SideCar::IO::StatusBase::operator!= (const StatusBase & rhs) const inline
Determine if the held status information is not the same as that in another status container.
Parameters
rhs value to compare with
Returns
true if so
Definition at line 109 of file StatusBase.h.
References operator==().
bool SideCar::IO::StatusBase::operator== (const StatusBase & rhs) const inline
Determine if the held status information is the same as that in another status container.
Parameters
rhs value to compare with
Returns
true if so
Definition at line 101 of file StatusBase.h.
Referenced by operator!=().
std::ostream& SideCar::IO::StatusBase::print (std::ostream & os) const inline
Print out an XML representation of the held status values.
Parameters
os stream to write to
Returns
stream written to.
Definition at line 117 of file StatusBase.h.
References XmlRpc::XmlRpcValue::toXml().
void SideCar::IO::StatusBase::setSlot (size_t index, const XmlRpc::XmlRpcValue & value) inline
Obtain a status value at a particular index.
Parameters
index location to fetch
Returns
read-only reference to found value
Definition at line 75 of file StatusBase.h.
References getSlot().
Referenced by SideCar::Algorithms::BinaryOp::BinaryOp(), SideCar::IO::Stream::fillStatus(), SideCar::Algorithms::Controller::fillStatus(), SideCar::IO::Task::fillStatus(), SideCar::Algorithms::GeoFilter::GeoFilter(), SideCar::Algorithms::BugCollector::process(), SideCar::Algorithms::EdgeDetector::reset(), SideCar::Algorithms::MatchedFilter::reset(), SideCar::Algorithms::CIntegrate::reset(), SideCar::Algorithms::CPIAlgorithm::setInfoSlots(), SideCar::Algorithms::IQFilter::setInfoSlots(), SideCar::Algorithms::ClutterMap::setInfoSlots(), SideCar::Algorithms::ManyInAlgorithm::setInfoSlots(), SideCar::Algorithms::Clamp::setMaxValue(), SideCar::Algorithms::Alarmer::shutdown(), SideCar::Algorithms::Decimator::shutdown(), SideCar::Algorithms::CPIMarker::shutdown(), SideCar::Algorithms::ComposeExtractions::shutdown(), SideCar::Algorithms::ComposeTracks::shutdown(), SideCar::Algorithms::ProcessTracks::shutdown(), SideCar::Algorithms::SectorMask::shutdown(), SideCar::Algorithms::Sum::shutdown(), SideCar::Algorithms::SumNDiff::shutdown(), SideCar::Algorithms::ABTracker::shutdown(), SideCar::Algorithms::Router::shutdown(), SideCar::Algorithms::Delay::shutdown(), SideCar::Algorithms::TrackMaintainer::shutdown(), SideCar::Algorithms::LowPassFilter::shutdown(), SideCar::Algorithms::SimpleOp::SimpleOp(), SideCar::Algorithms::Trimmer::startup(), SideCar::Algorithms::ShiftBins::startup(), SideCar::Algorithms::OSCFAR::startup(), SideCar::Algorithms::DynamicThreshold::startup(), SideCar::Algorithms::WindowedMinMax::startup(), and SideCar::Algorithms::SlidingOp::startup().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/IO/StatusBase.h
/Users/howes/src/sidecar/IO/StatusBase.cc