SideCar: SideCar::GUI::Splittable Class Reference
SideCar::GUI::Splittable Class Reference
Container widget that allows its contents to be split into two widgets controlled by a QSplitter object.
#include </Users/howes/src/sidecar/GUI/Splittable.h>
Public Slots
virtual void split (Qt::Orientation how, QWidget *other, int topLeftWeight, int bottomRightWeight)
Perform the splitting of our contents.
virtual void split (Qt::Orientation how, QWidget *other)
Perform the splitting of our contents.
virtual void unsplitWith (Splittable *keeper)
Restore a previously-split widget.
virtual void closeView ()
Restore a previously-split widget by removing ourselves.
virtual void closeOtherView ()
Restore a previously-split widget by removing our twin.
Public Member Functions
Splittable (QWidget *parent)
Constructor.The container starts with no contents.
void setContents (QWidget *widget)
Install a widget as the one to show for the widget representation.
Splittable * topLeft () const
Obtain the widget in the top/left position of our QSplitter widget.
Splittable * bottomRight () const
Obtain the widget in the bottom/right position of our QSplitter widget.
QSplitter * getSplitter () const
Obtain the QSplitter object that is in use in a split view.
bool isSplit () const
Determine if the view shown by this widget is split.
Protected Member Functions
virtual QSplitter * splitterFactory (Qt::Orientation how)
Obtain a new QSplitter object to use when splitting our contents.
virtual Splittable * splittableFactory (QSplitter *parent)
Obtain a new Splittable object to use as a wrapper for a QWidget.
virtual void addSplitContents (QSplitter *parent, QWidget *contents)
Create a new Splittable object to wrap a given QWidget and install in a QSplitter.
void resizeEvent (QResizeEvent *event)
Override of QWidget::resizeEvent().
Splittable * locateChild (bool secondOne) const
Obtain the top/left or bottom/right widget of a split representation.
Splittable * locateTwin (QSplitter *splitter) const
Obtain the Splitter widget in the QSplitter widget that is not the given widget.
Detailed Description
Container widget that allows its contents to be split into two widgets controlled by a QSplitter object.
Each split component may be further split to any level. Finally, any split widget may be unsplit by moving the slider all the way in either direction, resulting in one of the widgets having zero size in one of its dimensions. The widget that was minimized is removed from the widget hierarchy along with the QSplitter object, and the remaining widget is left in the place where the QSplitter object was.
Definition at line 16 of file Splittable.h.
Constructor & Destructor Documentation
SideCar::GUI::Splittable::Splittable (QWidget * parent) inline
Constructor.The container starts with no contents.
Parameters
parent parent widget for this one
Definition at line 26 of file Splittable.h.
References setContents().
Referenced by splittableFactory().
Member Function Documentation
void Splittable::addSplitContents (QSplitter * parent, QWidget * contents) protected virtual
Create a new Splittable object to wrap a given QWidget and install in a QSplitter.
Parameters
splitter QSplitter object to host the new widget
contents widget to wrap
Definition at line 103 of file Splittable.cc.
References setContents(), and splittableFactory().
Referenced by isSplit(), and split().
Splittable* SideCar::GUI::Splittable::bottomRight () const inline
Obtain the widget in the bottom/right position of our QSplitter widget.
Only valid if isSplit() returns true.
Returns
QWidget object
Definition at line 47 of file Splittable.h.
References locateChild().
Referenced by SideCar::GUI::AScope::MainWindow::MainWindow().
void Splittable::closeOtherView () virtual slot
Restore a previously-split widget by removing our twin.
The resulting view will just contain ourselves.
Definition at line 73 of file Splittable.cc.
References unsplitWith().
Referenced by SideCar::GUI::AScope::MainWindow::isDisplayViewSplit(), and isSplit().
void Splittable::closeView () virtual slot
Restore a previously-split widget by removing ourselves.
The resulting view will just contain our twin.
Definition at line 63 of file Splittable.cc.
References locateTwin(), and unsplitWith().
Referenced by isSplit(), and resizeEvent().
QSplitter* SideCar::GUI::Splittable::getSplitter () const inline
Obtain the QSplitter object that is in use in a split view.
Only valid if isSplit() returns true.
Returns
QSplitter object or NULL
Definition at line 53 of file Splittable.h.
Referenced by isSplit(), and SideCar::GUI::AScope::MainWindow::MainWindow().
bool SideCar::GUI::Splittable::isSplit () const inline
Determine if the view shown by this widget is split.
Returns
true if so.
Definition at line 60 of file Splittable.h.
References addSplitContents(), closeOtherView(), closeView(), getSplitter(), locateChild(), locateTwin(), resizeEvent(), split(), splittableFactory(), splitterFactory(), and unsplitWith().
Splittable * Splittable::locateChild (bool secondOne) const protected
Obtain the top/left or bottom/right widget of a split representation.
Only valid if isSplit() returns true.
Parameters
secondOne if true, obtain the bottom/right widget.
Returns
found widget.
Definition at line 13 of file Splittable.cc.
Referenced by bottomRight(), isSplit(), and topLeft().
Splittable * Splittable::locateTwin (QSplitter * splitter) const protected
Obtain the Splitter widget in the QSplitter widget that is not the given widget.
Used in the resizeEvent() routine to determine the widget to keep when unsplitting our representation.
Parameters
splitter widget that contains the two split representations
Returns
Splitter object whose contents we will keep during the unsplit operation.
Definition at line 83 of file Splittable.cc.
Referenced by closeView(), and isSplit().
void Splittable::resizeEvent (QResizeEvent * event) protected
Override of QWidget::resizeEvent().
Detect when we have been resized to zero in either dimension. If so, remove the split and make one of the split widgets our new representation.
Parameters
event description of the resizing that occured.
Definition at line 54 of file Splittable.cc.
References closeView().
Referenced by isSplit().
void Splittable::setContents (QWidget * widget)
Install a widget as the one to show for the widget representation.
This widget will also become a child of a QSplitter if we are ever split.
Parameters
widget widget to use
Definition at line 6 of file Splittable.cc.
Referenced by addSplitContents(), SideCar::GUI::AScope::MainWindow::MainWindow(), split(), Splittable(), and unsplitWith().
void Splittable::split (Qt::Orientation how, QWidget * other, int topLeftWeight, int bottomRightWeight) virtual slot
Perform the splitting of our contents.
The widget that is set as our contents will become to the top or left part of a new QSplitter object, while user-supplied widget will be used as the bottom/right one. Each of these QWidget objects will be wrapped by a new Splittable object so that they too may be split.
Parameters
how direction in which the split will occur.
other widget to use for the right or bottom part of the new QSplitter object.
topLeftWeight how much space to allocate to the top/left widget in the new split view
bottomRightWeight how much space to allocate to the bottom/right widget in the new split view
Definition at line 27 of file Splittable.cc.
References addSplitContents(), setContents(), and splitterFactory().
Referenced by isSplit(), SideCar::GUI::AScope::MainWindow::MainWindow(), SideCar::GUI::AScope::MainWindow::restoreFromSettings(), and split().
void Splittable::split (Qt::Orientation how, QWidget * other) virtual slot
Perform the splitting of our contents.
Same as above with 50/50 distribution of space to the two widgets.
Parameters
how direction in which the split will occur.
other widget to use for the right or bottom part of the new QSplitter object.
Definition at line 21 of file Splittable.cc.
References split().
Splittable * Splittable::splittableFactory (QSplitter * parent) protected virtual
Obtain a new Splittable object to use as a wrapper for a QWidget.
Only used when splitting our contents.
Parameters
splitter QSplitter object hosting the split representation
Returns
new Splittable object
Definition at line 97 of file Splittable.cc.
References Splittable().
Referenced by addSplitContents(), and isSplit().
QSplitter * Splittable::splitterFactory (Qt::Orientation how) protected virtual
Obtain a new QSplitter object to use when splitting our contents.
Parameters
how orientation of the split (Qt::Horizontal or Qt::Vertical)
Returns
new QSplitter object
Definition at line 91 of file Splittable.cc.
Referenced by isSplit(), and split().
Splittable* SideCar::GUI::Splittable::topLeft () const inline
Obtain the widget in the top/left position of our QSplitter widget.
Only valud if isSplit() returns true.
Returns
QWidget object
Definition at line 40 of file Splittable.h.
References locateChild().
Referenced by SideCar::GUI::AScope::MainWindow::MainWindow().
void Splittable::unsplitWith (Splittable * keeper) virtual slot
Restore a previously-split widget.
The QSplitter hosting the split representations is removed from the widget stack, and the given widget is used as our representation.
Parameters
keeper widget to use for our representation
Definition at line 45 of file Splittable.cc.
References setContents().
Referenced by closeOtherView(), closeView(), and isSplit().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/Splittable.h
/Users/howes/src/sidecar/GUI/Splittable.cc