SideCar: SideCar::IO::ReaderDevices::File Class Reference
SideCar::IO::ReaderDevices::File Class Reference
Device that gets data from a file.
#include </Users/howes/src/sidecar/IO/Readers.h>
Public Member Functions
File ()
Constructor for new reader.
ACE_FILE_IO & getDevice ()
Obtain reference to file device.
const ACE_FILE_IO & getDevice () const
Obtain read-only reference to file device.
Protected Member Functions
ssize_t fetchFromDevice (void *addr, size_t size)
Obtain data from the device.
Detailed Description
Device that gets data from a file.
Definition at line 29 of file Readers.h.
Member Function Documentation
ssize_t SideCar::IO::ReaderDevices::File::fetchFromDevice (void * addr, size_t size) inline protected
Obtain data from the device.
Parameters
addr where to place fetched data
size how much data to fetch
Returns
number of bytes fetched if > 0; EOF if == 0; and error condition if < 0
Definition at line 59 of file Readers.h.
ACE_FILE_IO& SideCar::IO::ReaderDevices::File::getDevice () inline
Obtain reference to file device.
Returns
file device
Definition at line 41 of file Readers.h.
Referenced by SideCar::IO::FileReaderTask::openAndInit(), SideCar::GUI::Playback::Emitter::setEmitting(), and SideCar::GUI::Playback::Emitter::~Emitter().
const ACE_FILE_IO& SideCar::IO::ReaderDevices::File::getDevice () const inline
Obtain read-only reference to file device.
Returns
file device
Definition at line 47 of file Readers.h.
The documentation for this class was generated from the following file:
/Users/howes/src/sidecar/IO/Readers.h