SideCar: SideCar::Algorithms::ManyInCPIAlgorithm Class Reference
SideCar::Algorithms::ManyInCPIAlgorithm Class Reference abstract
Documentation for the algorithm Summer.
#include </Users/howes/src/sidecar/Algorithms/ManyInCPIAlgorithm.h>
Public Member Functions
ManyInCPIAlgorithm (Controller &controller, Logger::Log &log, bool enabled=true, size_t maxBuffersize=100, size_t cpiSpan=10)
Constructor.
bool startup ()
Implementation of the Algorithm::startup interface.
Public Member Functions inherited from SideCar::Algorithms::ManyInAlgorithm
ManyInAlgorithm (Controller &controller, Logger::Log &log, bool enabled=true, size_t maxBufferSize=10)
Constructor.
bool shutdown () override
Override of Algorithm::shutdown().
bool isEnabled () const
Obtain enabled state for the algorithm.
size_t getMaxBufferSize () const
Obtain the current max buffer size.
size_t getChannelCount () const
Obtain the number of active ChannelBuffer objects.
template<typename T >
TChannelBuffer< T > * getChannelBuffer (const std::string &name) const
Obtain a type-safe ChannelBuffer object using the channel name.
template<typename T >
TChannelBuffer< T > * getChannelBuffer (size_t index) const
Obtain a type-safe ChannelBuffer object using the channel index.
ChannelBuffer * getGenericChannelBuffer (size_t index) const
Obtain the ChannelBuffer object at a given channel index.
bool reset () override
Hook called when the algorithm is transitioning from a stopped to a running state (one of Task::kAutoDiagnostic, Task::kCalibrate, or Task::kRun).
virtual void channelEnabledChanged (ChannelBuffer *channel)
Notification handler invoked when the enabled state of a ChannelBuffer object changes.
Public Member Functions inherited from SideCar::Algorithms::Algorithm
Algorithm (Controller &controller, Logger::Log &log)
Constructor.
virtual ~Algorithm ()
Destructor.
Controller & getController () const
Obtain the Controller object managing the algorithm.
Logger::Log & getLog () const
Obtain the log device to use for by the algorithm for log messages.
const std::string & getName () const
Obtain the name of the algorithm.
bool registerParameter (const Parameter::Ref &parameter)
Add a configuration parameter to the runtime system.
bool unregisterParameter (const Parameter::Ref &parameter)
Remove a configuration parameter from the runtime system.
template<typename A , typename M >
void registerProcessor (boost::function< bool(A *, typename M::Ref)> proc)
Install a method to process a particular message type.
template<typename A , typename M >
void registerProcessor (const std::string &channelName, boost::function< bool(A *, typename M::Ref)> proc)
Same as above method, but allows user to pick the channel by name.
template<typename A , typename M >
void registerProcessor (size_t channelIndex, boost::function< bool(A *, typename M::Ref)> proc)
Same as above method, but allows user to pick the channel by index.
template<typename A >
void registerProcessor (const std::string &channelName, const Messages::MetaTypeInfo &metaTypeInfo, boost::function< bool(A *, typename Messages::Header::Ref)> proc)
template<typename A >
void registerProcessor (size_t channelIndex, const Messages::MetaTypeInfo &metaTypeInfo, boost::function< bool(A *, typename Messages::Header::Ref)> proc)
size_t addProcessor (const std::string &channelName, const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
size_t addProcessor (const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
size_t addProcessor (size_t index, const Messages::MetaTypeInfo &metaTypeInfo, Processor *processor)
Add a message processor for a channel.
void removeProcessor (size_t index)
Remove a processor from a given channel.
size_t getOutputChannelIndex (const std::string &name) const
Obtain an output channel index with a given name.
bool send (const Messages::Header::Ref &msg, size_t channelIndex=0)
Submit a message object to the controller for sending out on a given data channel.
bool sendAsIs (const Messages::Header::Ref &msg, size_t channelIndex=0)
Hand a message to the controller for sending out on a given data channel.
size_t getActiveChannelIndex () const
Obtain the index of the input channel that last received a message for the algorithm to process.
Protected Member Functions
virtual bool processMessageReceived ()
Process the ChannelBuffer objects.
bool pruneToCPIBoundary (size_t cpiSpan)
Prune the channels of any incomplete CPIs.
bool verifyChannelSize (size_t cpiSpan)
Verify the buffer contains enough PRIs to form a CPI.
virtual bool processCPI ()=0
Protected Member Functions inherited from SideCar::Algorithms::ManyInAlgorithm
size_t getNumInfoSlots () const override
Obtain the number of info slots defined by this algorithm.
void setInfoSlots (IO::StatusBase &status) override
Override of Algorithm::setInfoSlots().
uint32_t getMaxSequenceCounter () const
Obtain the maximum sequence counter seen in the first message of all of the ChannelBuffer objects.
bool pruneToSequenceCounter (uint32_t sequenceCounter)
Prune the active ChannelBuffer objects so that the first message in each one has the given sequence counter value.
virtual ChannelBuffer * makeChannelBuffer (int channelIndex, const std::string &name, size_t maxBufferSize)=0
Create a new type-safe TChannelBuffer object.
ChannelBuffer * findChannelBuffer (const std::string &name) const
template<typename T >
size_t fetchEnabledChannelMessages (std::vector< typename T::Ref > &inputs)
Protected Member Functions inherited from SideCar::Algorithms::Algorithm
void setAlarm (int secs)
This method can be used by an Algorithm to schedule a periodic alarm to go off for itself.
virtual bool clearStats ()
Hook called when the algorithm is commaned to clear any statistics.
virtual bool beginAutoDiag ()
Hook called when the algorithm is entering the Task::kAutoDiagnostic state.
virtual bool beginCalibration ()
Hook called when the algorithm is entering the Task::kCalibrate state.
virtual bool beginRun ()
Hook called when the algorithm is entering the Task::kRun state.
virtual bool stop ()
Hook called when the algorithm is entering the Task::kStop state.
virtual void recordingStarted ()
Hook called when a recording has started.
virtual void recordingStopped ()
Hook called when a recording has stopped.
virtual void beginParameterChanges ()
Hook called just before algorithm runtime parameters are changed.
virtual void endParameterChanges ()
Hook called just after algorithm runtime parameters have been changed.
virtual void processAlarm ()
This method will get called whenever an alarm expires for this Algorithm.
Protected Attributes
Parameter::PositiveIntValue::Ref cpiSpan_
Run-time parameter for a channel's internal buffer size.
Protected Attributes inherited from SideCar::Algorithms::ManyInAlgorithm
ChannelBufferVector channels_
Additional Inherited Members
Public Types inherited from SideCar::Algorithms::ManyInAlgorithm
enum InfoSlot { kEnabled = ControllerStatus::kNumSlots, kChannelStats, kNumSlots }
Static Public Member Functions inherited from SideCar::Algorithms::ManyInAlgorithm
static QString GetFormattedStats (const IO::StatusBase &status)
Static Public Member Functions inherited from SideCar::Algorithms::Algorithm
static void * FormatInfoValue (const QString &value)
Obtain a C-safe value for the given QString string.
static void * FormatInfoValue (const char *value)
Obtain a C-safe value for the given character string.
Protected Types inherited from SideCar::Algorithms::ManyInAlgorithm
using ChannelBufferVector = std::vector< ChannelBuffer * >
Detailed Description
Documentation for the algorithm Summer.
Generates summed output of N input messages from different sources. The messages used in the summation will all have the same sequence counter value. Also, if an enabled channel has somehow missed a message (a message 'drop'), then there will not be an summed output for that sequence number. In other words, the sequence number must be present on all enabled channels for the algorithm to emit a summed messages.
Definition at line 18 of file ManyInCPIAlgorithm.h.
Constructor & Destructor Documentation
ManyInCPIAlgorithm::ManyInCPIAlgorithm (Controller & controller, Logger::Log & log, bool enabled = true, size_t maxBuffersize = 100, size_t cpiSpan = 10)
Constructor.
Parameters
controller object that controls us
log device used for log messages
cpiSpan size of the CPI in PRIs
Definition at line 17 of file ManyInCPIAlgorithm.cc.
Member Function Documentation
bool ManyInCPIAlgorithm::processMessageReceived () protected virtual
Process the ChannelBuffer objects.
Called whenever an active ChannelBuffer object receives a message.
Returns
true if successful
Reimplemented from SideCar::Algorithms::ManyInAlgorithm.
Definition at line 137 of file ManyInCPIAlgorithm.cc.
References cpiSpan_, SideCar::Algorithms::ManyInAlgorithm::getMaxSequenceCounter(), pruneToCPIBoundary(), SideCar::Algorithms::ManyInAlgorithm::pruneToSequenceCounter(), and verifyChannelSize().
bool ManyInCPIAlgorithm::pruneToCPIBoundary (size_t cpiSpan) protected
Prune the channels of any incomplete CPIs.
Note, "incomplete" does not include those CPIs whose messages are still arriving.
Parameters
the expected size of CPIs
Returns
true if all channels have a complete CPI
Definition at line 121 of file ManyInCPIAlgorithm.cc.
Referenced by processMessageReceived().
bool ManyInCPIAlgorithm::startup () virtual
Implementation of the Algorithm::startup interface.
Register runtime parameters. Processors are registered in parent class.
Returns
true if successful, false otherwise
Reimplemented from SideCar::Algorithms::ManyInAlgorithm.
Definition at line 30 of file ManyInCPIAlgorithm.cc.
References cpiSpan_, SideCar::Algorithms::Algorithm::registerParameter(), and SideCar::Algorithms::ManyInAlgorithm::startup().
bool ManyInCPIAlgorithm::verifyChannelSize (size_t cpiSpan) protected
Verify the buffer contains enough PRIs to form a CPI.
Parameters
the expected size of a CPI
Returns
if there are at least CPI + 1 messages in the channel buffer
Definition at line 114 of file ManyInCPIAlgorithm.cc.
Referenced by processMessageReceived().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/Algorithms/ManyInCPIAlgorithm.h
/Users/howes/src/sidecar/Algorithms/ManyInCPIAlgorithm.cc