SideCar: SideCar::GUI::ServiceEntry Class Reference
SideCar::GUI::ServiceEntry Class Reference
Bridge class that brings together the Zeroconf::ServiceEntry interface and the Qt QObject interface.
#include </Users/howes/src/sidecar/GUI/ServiceEntry.h>
Data Structures
struct Private
Public Types
using ZCServiceEntryRef = boost::shared_ptr< Zeroconf::ServiceEntry >
Signals
void resolved (ServiceEntry *serivceEntry)
Signal sent out when the service entry connection information has been resolved.
Public Member Functions
ServiceEntry (QObject *parent, const Messages::MetaTypeInfo *metaTypeInfo, const ZCServiceEntryRef &service)
Constructor.
~ServiceEntry ()
Destructor.
ServiceEntry * duplicate () const
Create a duplicate of this object, including any cached connection information.
const ZCServiceEntryRef & getZeroconfServiceEntry () const
Obtain a reference to the original Zeroconf::ServiceEntry object.
const Zeroconf::ResolvedEntry & getZeroconfResolvedEntry () const
Obtain the Zeroconf::ResolvedEntry object for a resolved Zeroconf::ServiceEntry object.
const Messages::MetaTypeInfo * getMetaTypeInfo () const
Obtain the sub-type of the service (eg.
const QString & getName () const
Obtain the name of the service.
const QString & getType () const
Obtain the type of the service (eg.
const QString & getDomain () const
Obtain the domain of the service (eg.
const QString & getFullName () const
Obtain the full name of the service.
const QString & getNativeHost () const
const QString & getHost () const
Obtain the host on which the service is running.
const QString & getTransport () const
uint32_t getInterface () const
Obtain the interface on which the service may be contacted.
uint16_t getPort () const
Obtain the port on the host getHost() over which the service may be contacted .
bool isResolved () const
Determine whether the service host/port information has been previously resolved.
bool resolve ()
Ask to service to resolve its host/port information.
QString getTextEntry (const QString &key) const
Obtain the value in a TXT record for a given key.
bool hasTextEntry (const QString &key, QString *value=0) const
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for ServiceEntry objects.
Detailed Description
Bridge class that brings together the Zeroconf::ServiceEntry interface and the Qt QObject interface.
A ServiceEntry may be queried for connection information, and whether its connection information has been resolved to a host/port. If it has not, calling its resolve() method will do so.
Definition at line 22 of file ServiceEntry.h.
Constructor & Destructor Documentation
ServiceEntry::ServiceEntry (QObject * parent, const Messages::MetaTypeInfo * metaTypeInfo, const ZCServiceEntryRef & service)
Constructor.
Parameters
parent owner of the ServiceEntry object
info internal object holding that holds the actual service information.
Definition at line 26 of file ServiceEntry.cc.
References Log(), and LOGINFO.
Referenced by duplicate().
ServiceEntry::~ServiceEntry ()
Destructor.
Defined here so that we may keep ServiceInfo undefined until ServiceBrowser.cc.
Definition at line 44 of file ServiceEntry.cc.
Member Function Documentation
ServiceEntry * ServiceEntry::duplicate () const
Create a duplicate of this object, including any cached connection information.
Returns
new ServiceEntry object
Definition at line 51 of file ServiceEntry.cc.
References ServiceEntry().
Referenced by SideCar::GUI::ReaderThread::useServiceEntry().
const QString& SideCar::GUI::ServiceEntry::getDomain () const inline
Obtain the domain of the service (eg.
'local.')
Returns
service domain
Definition at line 92 of file ServiceEntry.h.
const QString& SideCar::GUI::ServiceEntry::getFullName () const inline
Obtain the full name of the service.
This is the name + domain.
Returns
full service name
Definition at line 98 of file ServiceEntry.h.
const QString& SideCar::GUI::ServiceEntry::getHost () const inline
Obtain the host on which the service is running.
Only valid if the service has been resolved.
Returns
service host name
Definition at line 110 of file ServiceEntry.h.
Referenced by SideCar::GUI::Master::ConfigurationItem::executeRequest(), SideCar::GUI::MessageReader::Make(), and SideCar::GUI::MulticastMessageReader::~MulticastMessageReader().
uint32_t ServiceEntry::getInterface () const
Obtain the interface on which the service may be contacted.
Only valid if the service has been resolved.
Returns
interface ID
Definition at line 72 of file ServiceEntry.cc.
const Messages::MetaTypeInfo* SideCar::GUI::ServiceEntry::getMetaTypeInfo () const inline
Obtain the sub-type of the service (eg.
'Video' or 'Extractions')
Returns
service sub-type
Definition at line 73 of file ServiceEntry.h.
Referenced by SideCar::GUI::MulticastMessageReader::Make().
const QString& SideCar::GUI::ServiceEntry::getName () const inline
Obtain the name of the service.
Returns
service name
Definition at line 80 of file ServiceEntry.h.
Referenced by SideCar::GUI::Master::ConfigurationItem::ConfigurationItem(), SideCar::GUI::Master::ServicesModel::getChangedParameters(), SideCar::GUI::Master::RunnerItem::getChild(), SideCar::GUI::AScope::ChannelConnectionWindow::getSelectedChannelConnection(), SideCar::GUI::MessageReader::Make(), and SideCar::GUI::Subscriber::useServiceEntry().
const QString& SideCar::GUI::ServiceEntry::getNativeHost () const inline
Returns
Definition at line 104 of file ServiceEntry.h.
Referenced by SideCar::GUI::MulticastMessageReader::~MulticastMessageReader().
uint16_t ServiceEntry::getPort () const
Obtain the port on the host getHost() over which the service may be contacted .
Returns
Definition at line 78 of file ServiceEntry.cc.
References SideCar::Zeroconf::ResolvedEntry::getPort(), and getZeroconfResolvedEntry().
Referenced by SideCar::GUI::Master::ConfigurationItem::executeRequest(), SideCar::GUI::Master::RunnerItem::executeRequest(), SideCar::GUI::Master::RunnerItem::getHostDataValue(), SideCar::GUI::MessageReader::Make(), and SideCar::GUI::MulticastMessageReader::~MulticastMessageReader().
QString ServiceEntry::getTextEntry (const QString & key) const
Obtain the value in a TXT record for a given key.
Parameters
key the value to search for
Returns
true if key found, false otherwise
Definition at line 99 of file ServiceEntry.cc.
References getZeroconfResolvedEntry().
Referenced by SideCar::GUI::MulticastMessageReader::~MulticastMessageReader().
const QString& SideCar::GUI::ServiceEntry::getTransport () const inline
Returns
Definition at line 116 of file ServiceEntry.h.
Referenced by SideCar::GUI::MessageReader::Make().
const QString& SideCar::GUI::ServiceEntry::getType () const inline
Obtain the type of the service (eg.
'_sidecar._tcp')
Returns
service type
Definition at line 86 of file ServiceEntry.h.
const Zeroconf::ResolvedEntry & ServiceEntry::getZeroconfResolvedEntry () const
Obtain the Zeroconf::ResolvedEntry object for a resolved Zeroconf::ServiceEntry object.
NOTE: only valid if isResolved() returns true.
Returns
Zeroconf::ResolvedEntry reference
Definition at line 66 of file ServiceEntry.cc.
Referenced by getPort(), getTextEntry(), and hasTextEntry().
const ZCServiceEntryRef& SideCar::GUI::ServiceEntry::getZeroconfServiceEntry () const inline
Obtain a reference to the original Zeroconf::ServiceEntry object.
Returns
Zeroconf ServiceEntry reference
Definition at line 59 of file ServiceEntry.h.
bool ServiceEntry::hasTextEntry (const QString & key, QString * value = 0) const
Parameters
key
value
Returns
Definition at line 106 of file ServiceEntry.cc.
References SideCar::Zeroconf::ResolvedEntry::getFullName(), SideCar::Zeroconf::ResolvedEntry::getHost(), SideCar::Zeroconf::ResolvedEntry::getPort(), SideCar::Zeroconf::ResolvedEntry::getTextEntry(), getZeroconfResolvedEntry(), SideCar::Zeroconf::ResolvedEntry::hasTextEntry(), Log(), LOGINFO, and resolved().
bool ServiceEntry::isResolved () const
Determine whether the service host/port information has been previously resolved.
Returns
true if so
Definition at line 84 of file ServiceEntry.cc.
Referenced by SideCar::GUI::Master::ServicesModel::getChangedParameters(), and resolve().
Logger::Log & ServiceEntry::Log () static
Obtain the log device for ServiceEntry objects.
Returns
log device
Definition at line 19 of file ServiceEntry.cc.
References Logger::Log::Find().
Referenced by hasTextEntry(), and ServiceEntry().
bool ServiceEntry::resolve ()
Ask to service to resolve its host/port information.
Returns
true if successful, false otherwise.
Definition at line 90 of file ServiceEntry.cc.
References isResolved(), and resolved().
Referenced by SideCar::GUI::Master::ServicesModel::getChangedParameters(), and SideCar::GUI::Subscriber::useServiceEntry().
void SideCar::GUI::ServiceEntry::resolved (ServiceEntry * serivceEntry) signal
Signal sent out when the service entry connection information has been resolved.
Parameters
serivceEntry the service that was resolved
Referenced by hasTextEntry(), and resolve().
The documentation for this class was generated from the following files:
/Users/howes/src/sidecar/GUI/ServiceEntry.h
/Users/howes/src/sidecar/GUI/ServiceEntry.cc