SideCar: /Users/howes/src/sidecar/Utils/IO.h File Reference
IO.h File Reference
#include <string>
Namespaces
Utils
Namespace for utility classes and such used by other components.
Functions
bool operator>> (ACE_InputCDR &cdr, std::string &string)
Utility ACE CDR input stream extractor for C++ string objects.
bool operator<< (ACE_OutputCDR &cdr, const std::string &string)
Utility ACE CDR output stream inserter for C++ string objects.
std::string Utils::INETAddrToString (const ACE_INET_Addr &address)
Function Documentation
bool operator<< (ACE_OutputCDR & cdr, const std::string & string)
Utility ACE CDR output stream inserter for C++ string objects.
Writes out a 4 byte size followed by the characters from the string.
Parameters
cdr stream to write to
string string to write
Returns
stream written to
Definition at line 23 of file IO.cc.
Referenced by SideCar::Messages::MetaTypeInfo::isa(), std::operator<<(), SideCar::Algorithms::NCIntegrate::reset(), and XmlRpc::XmlRpcValue::setDoubleFormat().
bool operator>> (ACE_InputCDR & cdr, std::string & string)
Utility ACE CDR input stream extractor for C++ string objects.
Reads in a 4 byte size followed by that number of characters.
Parameters
cdr stream to read from
string string to change
Returns
stream read from
Definition at line 7 of file IO.cc.
Referenced by SideCar::Messages::MetaTypeInfo::isa().