SideCar: Utils Namespace Reference
Utils Namespace Reference
Namespace for utility classes and such used by other components.
Data Structures
class AtomicOp
Class that increments and decrements an integral value in an atomic way, thus safe for use in threaded processing.
class AzimuthSweep
class BeamWidthFilter
Simple averaging filter for azimuth deltas.
class center
Simple output stream manipulator that spits out text centered in a field of a given width.
class CmdLineArgs
Command-line processor.
class ConfigFilePath
Specialization of FilePath that used the environment variable $AP_CONFIG_DIR to locate configuration files.
class ConverterAdapter
Adapter for an iterator that performs some type of conversion for each value obtained from a forward iterator.
class dashLine
Output stream manipulator that spits out a sequence of one character (a `-' by default).
struct dumpHex
class Exception
Base exception class.
struct ExceptionInserter
Define a stream inserter operator to use for Exception objects that returns the appropriate type.
class FilePath
Simple wrapper around the std string class that can decompose a file path into three parts: directory path, file name, and extension.
class FileWatcher
Abstract base class that monitors a file for changes to its modification timestamp.
class Format
Formatting settings for a C++ input or output stream.
class formatHeading
Output stream formatter for heading values.
struct Formatter
Helper class that binds a value to a Format object for use with standard C++ output streams.
class formatTime
class hexPtr
Output stream formatter for void* pointers.
class MD5
MD5 hash generator.
class OrderedIndex
Container of sortable keys that maintains index associations with the keys.
class Pluralist
Utility template class used by the plural template function to temporarily save the data to be written to an ostream.
class Pool
An allocator for same-size memory chunks.
struct PowerOf2
Meta-program that calculates 2**M from within the compiler.
struct PowerOf2< 0 >
Meta-program that calculates 2**0 from within the compiler.
class Printable
Declare an abstract base class that defines an interface for all `printable' objects, those that can be inserted into an output stream with the `<<' operator.
class PtrRingBuffer
Template class for ring buffers that contain pointers to user-defined types.
class PushFormat
Utility class that records the format settings of a stream, and then applies the settings found in a Format object.
class RingBufferBase
Common base class for ring buffers.
class RunningAverage
Container class the maintains a running average value for a stream of values.
class RunningMedian
Container class the maintains a running median (and mean) value for a stream of values.
class showErrno
class SineCosineLUT
Simple table lookup class for sine/cosine values.
class StringConverterAdapter
Iterator adapter that attempts to convert std::string values into other types.
class TemporaryFilePath
Wrapper for a file path that attempts to remove existing files at the given path during construction and destruction.
class TRingBuffer
Template class that defines a type-safe ring buffer.
class Uncopyable
Simple class that prohibits derived classes from begin copied.
class VoidRingBuffer
Specialization of TRingBuffer for memory pointer objects.
class Wrapper
Utility class that will print out a string of text with lines no longer than a certain maximum, breaking the line at spaces.
Functions
std::string INETAddrToString (const ACE_INET_Addr &address)
template<typename T >
Utils::Pluralist< T > plural (const T &value, const std::string &sing, std::string plur="")
Utility (silly?) template function that prints out a value followed by a text tag that is plural when necessary.
template<typename RandomAccessIterator >
std::iterator_traits< RandomAccessIterator >::value_type QuickSelect (RandomAccessIterator low, RandomAccessIterator high, size_t k)
Implementation of the in-place Quickselect algorithm.
template<typename RandomAccessIterator >
void QuickSort (RandomAccessIterator low, RandomAccessIterator high)
Implementation of the in-place Quicksort algorithm.
double el_from_range_and_alt (double range, double altitude, double refLatitudeRadians)
Find elevation from range and altitude, taking the curvature of the earth into consideration.
template<typename T >
constexpr T GCD (T x, T y)
Calculate the greatest common divisor for two integral numbers.
template<typename T >
constexpr T LCM (T x, T y)
Calculate the least common multiple for two integral numbers.
std::string makePath (const std::string &path, const std::string &file)
Create a full path from the given file and path values.
double radiansToDegrees (double value)
double degreesToRadians (double value)
double normalizeRadians (double value)
double normalizeDegrees (double value)
uint32_t leastPowerOf2 (uint32_t value)
double feetToMeters (double value)
double metersToFeet (double value)
template<typename _Operation , typename _Converter >
ConverterAdapter< _Operation, _Converter > converterAdapter (const _Operation &__fn, const _Converter &__co)
Factory function that returns a new ConverterAdapter object.
template<class _Iterator >
StringConverterAdapter< _Iterator > stringConverterAdapter (const _Iterator &__fn)
Wrapper wrap (const std::string &data, int width=80, int cursor=0, const std::string &prefix="... ")
Utility that creates a new Wrapper instance.
Wrapper wrap (const std::string &data, const std::string &prefix)
Utility that creates a new Wrapper instance.
Variables
double const kCircleRadians = M_PI * 2.0
Detailed Description
Namespace for utility classes and such used by other components.
Sort of like a garage or attic where things get placed and then forgotten.
Function Documentation
template<typename _Operation , typename _Converter > ConverterAdapter<_Operation,_Converter> Utils::converterAdapter (const _Operation & __fn, const _Converter & __co) inline
Factory function that returns a new ConverterAdapter object.
Parameters
__fn iterator to use
__co functor to use
Returns
Definition at line 165 of file Utils.h.
double Utils::el_from_range_and_alt (double range, double altitude, double refLatitudeRadians)
Find elevation from range and altitude, taking the curvature of the earth into consideration.
Parameters
range slant range in meters
altitude altitude in meters
refLatitudeRadians latitude of the vector's origin in radians
Returns
elevation in radians
Definition at line 33 of file Utils.cc.
Referenced by SideCar::Algorithms::TrackInitiator::reset().
template<typename T > constexpr T Utils::GCD (T x, T y)
Calculate the greatest common divisor for two integral numbers.
Parameters
x first number
y second number
Returns
GCD value
Definition at line 36 of file Utils.h.
Referenced by LCM().
template<typename T > constexpr T Utils::LCM (T x, T y)
Calculate the least common multiple for two integral numbers.
Parameters
x first number
y second number
Returns
LCM value
Definition at line 53 of file Utils.h.
References GCD(), and makePath().
std::string Utils::makePath (const std::string & path, const std::string & file)
Create a full path from the given file and path values.
Any previous path is stripped from the file before it is used. Assumes, but does not check, that path ends in a '/'.
Parameters
path value for path to file
file value for the file name
Returns
path + file
Referenced by LCM().
template<typename T > Utils::Pluralist<T> Utils::plural (const T & value, const std::string & sing, std::string plur = "") inline
Utility (silly?) template function that prints out a value followed by a text tag that is plural when necessary.
To be used as an output stream inserter, like
 std::cout << Utils::plural(10, "chipmunk") <<
std::endl;
Parameters
value numeric value to write out
sing text representing a singular tag
plur text representing a plural tag. If none is given, one is created by appending an `s' to the sing value.
Returns
new Pluralist<T> output stream inserter
Definition at line 53 of file Pluralist.h.
template<typename RandomAccessIterator > std::iterator_traits<RandomAccessIterator>::value_type Utils::QuickSelect (RandomAccessIterator low, RandomAccessIterator high, size_t k)
Implementation of the in-place Quickselect algorithm.
Freely manipulates the elements in a container in the range [low, high).
Parameters
low iterator to first element to order
high iterator to first element to not order
k the ordered statistic to return
Definition at line 23 of file QuickSelect.h.
template<typename RandomAccessIterator > void Utils::QuickSort (RandomAccessIterator low, RandomAccessIterator high)
Implementation of the in-place Quicksort algorithm.
Orders the elements in a container in the range [low, high).
Parameters
low iterator to first element to order
high iterator to first element to not order
Definition at line 16 of file QuickSort.h.
Wrapper Utils::wrap (const std::string & data, int width = 80, int cursor = 0, const std::string & prefix = "... ") inline
Utility that creates a new Wrapper instance.
Parameters
data text to print out
width maximum line length to generate
cursor initial value to use for the character count
prefix text to write at the start of new lines
Returns
new Wrapper instance
Definition at line 58 of file Wrapper.h.
Referenced by SideCar::GUI::BScope::History::getBugPlots(), PrintDetailOpt::operator()(), and PrintDetailArg::operator()().
Wrapper Utils::wrap (const std::string & data, const std::string & prefix) inline
Utility that creates a new Wrapper instance.
Parameters
data text to print out
prefix text to write at the start of new lines
Returns
new Wrapper instance
Definition at line 70 of file Wrapper.h.