SideCar: SideCar::GUI Namespace Reference
SideCar::GUI Namespace Reference
Namespace for the GUI applications.
Namespaces
AScope
Namespace for the AScope application.
BScope
Namespace for the BScope application.
ESScope
Namespace for the ESScope application.
ExtractionEmitter
Namespace for the ExtractionEmitter application.
HealthAndStatus
Namespace for the HealthAndStatus (hands) application.
Master
Namespace for the Master application.
Playback
Namespace for the Playback application.
PPIDisplay
Namespace for the PPIDisplay application.
PRIEmitter
Namespace for the PRIEmitter application.
RangeTruthEmitter
Namespace for the RangeTruthEmitter application.
SignalGenerator
Namespace for the SignalGenerator application.
Spectrum
Namespace for the Spectrum application.
ZeroconfMonitor
Namespace for the ZeroconfMonitor application.
Data Structures
class AppBase
Base application class used by all GUI applications.
class BoolSetting
Derivation of the Setting class that manages boolean values.
class BugPlotEmitterSettings
class ChannelGroup
A manager of a collection of subscription channels for a particular message type (eg.
class ChannelImaging
Collection of display attributes for a data channel or artifact.
class ChannelInfoWidget
class ChannelMenu
class ChannelSelectorWindow
Tool window that shows three QComboBox buttons that allow the user to select which Video, BinaryVideo, and Extractions publisher to connect to for data.
class ChannelSetting
Derivation of StringSetting that works with a QComboBox widget to display and change a subscription channel setting.
class CLUT
General color lookup table class.
class CLUTSetting
struct Color
Utility OpenGL color class that expands on the primitive RGBColor class to hold an opacity (alpha) value.
class ColorButtonSetting
Derivation of QColorSetting that works with a QPushButton widget to show the current color setting, and to provide a way to edit the color value when the button is pressed.
class ColorButtonWidget
Derivation of QPushButton that shows a color setting, and provides a way to edit the color value when pressed.
class ColorMapWidget
Floating tool window that shows the message time for the data shown in a PPIWidget, and the range/azimuth values for the cursor.
class ControlsWidget
class ControlsWindow
class CursorWidget
QToolBar widget that shows the mouse cursor postion in real-world values such as range and sample value.
class DoubleMinMaxValidator
class DoubleSetting
Derivation of the Setting class that manages 'double' floating-point values.
class GLFont
class GLInitLock
class IntMinMaxValidator
class IntSetting
Derivation of the Setting class that manages integer values.
class KeySeq
A wrapper around QKeySequence that better handles conversions to a QString than that found in QKeySequence when run on OS X.
class KeySetting
class LED
class LoggerModel
class LoggerTreeItem
class LoggerView
class LoggerWindow
Floating tool window that shows the various Logger::Log devices in use by a GUI program.
class MainWindowBase
Common base class for all SideCar GUI projects.
class ManualWindow
class MessageBlockList
Collection of ACE_Message_Block objects received from a network connection.
class MessageList
Collection of SideCar::Messages::Header objects received from a network connection.
class MessageReader
Base class for SideCar message readers used by the GUI applications.
class MessageWriter
Abstract base class for Qt data publishers.
class MulticastMessageReader
Derivation of MessageReader that obtains messages over a UDP multicast socket.
class OffscreenBuffer
Manager of an OpenGL framebuffer object that allows for direct rendering into a texture object.
class OnOffSettingsBlock
Derivation of SettingsBlock that has a BoolSetting object which acts as an 'enabled' setting.
class OpacitySetting
class PathSetting
class PeakDetector
class PhantomCursorImaging
class PlotPositionFunctor
Abstract base class that defines the interface for plot positioners.
class PlotSymbolWidget
Derivation of a QComboBox that works with a TargetPlotImaging instance to show the available target plot symbols and the current symbol setting in use by the TargetPlotImaging instance.
class Potentiometer
class Preset
Collection of Setting values that represent a defined preset for an application.
class PresetChooser
class PresetManager
Manager for Preset objects and associated Setting objects.
class PresetsWindow
Floating tool window that shows the message time for the data shown in a PPIWidget, and the range/azimuth values for the cursor.
class PriorityWidget
class QCheckBoxSetting
Derivation of BoolSetting that works with a QCheckBox widget to display and change setting values.
class QColorSetting
Derivation of the Setting class that works with QColor values.
class QComboBoxSetting
Derivation of StringSetting that works with a QComboBox widget to display and change setting values.
class QDoubleSpinBoxSetting
Derivation of DoubleSetting that works with a QDoubleSpinBox widget to display and change setting values.
class QGroupBoxSetting
class QLineEditSetting
class QRadioButtonSetting
class QSliderSetting
class QSpinBoxSetting
Derivation of IntSetting that works with a QSpinBox widget to display and change setting values.
class QTabWidgetSetting
class QTimeEditSetting
Derivation of BoolSetting that works with a QCheckBox widget to display and change setting values.
class QtMonitor
Concrete implementation of the Monitor class that relies on QSocketNotifier object to determine when a Transaction object has data available for processing.
class QtMonitorFactory
class RadarInfoWidget
QToolBar widget that shows the azimuth and message time of the last message processed by the application.
class RangeMap
Set of points that define lines that make up a range map.
class RangeRingsImaging
Extension of the ChannelImaging class for the display of range rings.
class RangeTruthsImaging
class ReaderThread
A class that manages a TCP/UDP reader that runs in a separate thread.
struct RGBColor
Primitive color class that holds OpenGL RGB values for a specific color.
class RTCLMessageReader
Derivation of MessageReader that obtains messages over an RTCL topic.
class SampleImaging
Derivation of the ChannelImaging settings collection class that contains additional settings for OpenGL texture size and sample decimation.
class SCStyle
class ServiceBrowser
A refined Zeroconf browser for use by Qt widgets.
class ServiceEntry
Bridge class that brings together the Zeroconf::ServiceEntry interface and the Qt QObject interface.
class Setting
A general name/value object that holds QVariant values.
class SettingsBlock
Base class for a collection of Setting objects that conceptually belong together as a unit.
class SocketWriter
Derivation of an IO::TWriter class that uses QAbstractSocket objects to perform data writes.
class SocketWriterDevice
SideCar data network writer that uses a QAbstractSocket to to the actual writing.
class Splittable
Container widget that allows its contents to be split into two widgets controlled by a QSplitter object.
class SquareButton
Generic square UI widget button that supports on/off color states and a 'pending' state for transitioning between the two.
class StencilBufferState
Utility class that turns on Open/GL stencil buffer tesing only if it is used, and disables it when destructed.
class StringListSetting
Derivation of the Setting class that manages boolean values.
class StringSetting
Derivation of the Setting class that manages boolean values.
class Subscriber
The input side of a publisher/subscriber pair.
class SvgIconMaker
class TargetPlot
Extension of the Messages::Extraction class that plots for extractions and user picks.
class TargetPlotImaging
Extension of the ChannelImaging class that contains display settings for target plots.
class TargetPlotSymbolsWidget
Widget that shows the current plot symbols for the extractions (E), range truths (T) and user pick (P) imaging sources.
class TCPMessageReader
class TCPMessageWriter
Qt message writer that uses QTcpServer/QTcpSocket to write data over a TCP connection.
class TCPSocketReader
class TCPSocketReaderDevice
class Texture
Utility class that encapsulates some attributes of an OpenGL texture.
class TimeSetting
Derivation of the Setting class that manages QTime values (HH:MM:SS)
class ToolBar
Simple derivation of the QToolBar widget that can show a context menu containing a QAction to hide itself when selected.
class ToolWindowBase
Common base class for all SideCar GUI tool windows.
class UDPMessageWriter
Qt message writer that uses IO::UDPSocketWriter to do the writing.
struct Vertex
struct VertexColor
Combination of Vertex and Color objects.
class VertexColorArray
Resizable array of Vertex/Color pairs, interleaved in hopes of getting the best performance out of glVertexPointer and glColorPointer operations.
struct VertexColorTag
Combination of Vertex and Color objects.
class VertexColorTagArray
Resizable array of Vertex/Color/QString tuple, interleaved in hopes of getting the best performance out of glVertexPointer and glColorPointer operations.
class VertexGenerator
Abstract base class that defines the interface for classes that generate Vertex and Color values from Messages::PRIMessage data.
class VideoSampleCountTransform
Converts sample count information contained in Messages::Video messages into values between 0 and 1, inclusive.
class VTick
Perhaps the silliest class in all of SideCar.
class WindowManager
Manager of an application's 'Window' menu.
Typedefs
using ServiceEntryHash = QHash< QString, ServiceEntry * >
using ServiceEntryList = QList< ServiceEntry * >
using TargetPlotList = QList< TargetPlot >
using TargetPlotListList = QList< TargetPlotList >
using VertexVector = std::vector< Vertex >
using MessageVector = std::vector< Messages::PRIMessage::Ref >
Functions
std::string GetOpenGLErrorString (int glErr)
QChar DegreeSymbol ()
Obtain the Unicode character that represents a degree symbol.
QChar BulletSymbol ()
Obtain the Unicode character that represents a bullet symbol.
QChar HorizontalEllipses ()
Obtain the Unicode character that represents an ellipses symbol (...)
QString DistanceToString (double value, int precision, int fieldWidth)
Return a text representation for a distance value.
QString RadiansToString (double value, bool decimalFormat=false, int precision=2, int valueWidth=6)
Format an angular radian value into one of two formats:
QString DegreesToString (double value, bool decimalFormat=false, int precision=1, int fieldWidth=5)
Format an angular degree value into one of two formats:
QAction * MakeMenuAction (const QString &text, QObject *parent=0, const char *slot=0, int shortcut=0)
Create a new QAction object with a given text.
void UpdateToggleAction (QAction *action, bool newCheckedState)
Update a show/hide QAction object so that its text reflects the given show/hide state.
QString ByteAmountToString (double value, int precision=1)
Format a byte count into a human-readable string.
bool RemoveDirectory (const QDir &directory)
Recursively remove a given directory and all of its contents.
bool ProjectPoint (double objx, double objy, double objz, const double modelMatrix[16], const double projMatrix[16], const int viewport[4], double *winx, double *winy, double *winz)
Project a 3D model point into a 3D view point.
bool UnProjectPoint (double winx, double winy, double winz, const double modelMatrix[16], const double projMatrix[16], const int viewport[4], double *objx, double *objy, double *objz)
Inverse of ProjectPoint.
Vertex operator* (const Vertex &lhs, float rhs)
Vertex operator+ (const Vertex &lhs, const Vertex &rhs)
Detailed Description
Namespace for the GUI applications.
Each application has its own namespace with the same name as the application. The application namespaces are listed below.
Function Documentation
QChar SideCar::GUI::BulletSymbol () inline
Obtain the Unicode character that represents a bullet symbol.
Returns
QChar value
Definition at line 26 of file Utils.h.
QString SideCar::GUI::ByteAmountToString (double value, int precision = 1)
Format a byte count into a human-readable string.
Example: 3223323648 -> "3.0 GB"
Parameters
value the value to format
precision the number of digits to show to the right of a decimal point.
Returns
formatted value
Definition at line 141 of file Utils.cc.
Referenced by SideCar::GUI::Master::RunnerItem::getInfoDataValue(), and HorizontalEllipses().
QString SideCar::GUI::DegreesToString (double value, bool decimalFormat = false, int precision = 1, int fieldWidth = 5)
Format an angular degree value into one of two formats:
ddd.frac: whole degrees followed by fractional degrees after a decimal point.
ddd mm ss: formatted as DDD MM' SS" format
Parameters
value degree value to format
decimalFormat if true, format in ddd.frac format
Returns
formatted value
Definition at line 104 of file Utils.cc.
References DegreeSymbol().
Referenced by SideCar::GUI::AppBase::getFormattedAngleDegrees(), HorizontalEllipses(), and RadiansToString().
QChar SideCar::GUI::DegreeSymbol () inline
Obtain the Unicode character that represents a degree symbol.
Returns
QChar value
Definition at line 20 of file Utils.h.
Referenced by DegreesToString().
QString SideCar::GUI::DistanceToString (double value, int precision, int fieldWidth)
Return a text representation for a distance value.
Parameters
value the value to format
precision how many digits to the right of the decimal point to show
fieldWidth how many characters to show
Returns
formatted result
Definition at line 90 of file Utils.cc.
Referenced by SideCar::GUI::AppBase::getFormattedDistance(), and HorizontalEllipses().
QChar SideCar::GUI::HorizontalEllipses () inline
Obtain the Unicode character that represents an ellipses symbol (...)
Returns
QChar value
Definition at line 32 of file Utils.h.
References ByteAmountToString(), DegreesToString(), DistanceToString(), MakeMenuAction(), ProjectPoint(), RadiansToString(), RemoveDirectory(), UnProjectPoint(), and UpdateToggleAction().
QAction * SideCar::GUI::MakeMenuAction (const QString & text, QObject * parent = 0, const char * slot = 0, int shortcut = 0)
Create a new QAction object with a given text.
If the parent and slot arguments are not NULL, connect the QAction::triggered signal to the slot of the parent. Finally, if the given shortcut value is not zero, pass it to QAction::setShortcut().
Parameters
text label to use for the action
parent hierarchical parent if not NULL. Also the receiver to use if the slot parameter is not NULL.
slot the optional slot to connect to if not NULL. Note that for a connection to take place parent must not be NULL.
shortcut optional key sequence to use for the action shortcut.
Returns
Definition at line 20 of file Utils.cc.
Referenced by SideCar::GUI::AppBase::addToolWindow(), HorizontalEllipses(), SideCar::GUI::MainWindowBase::makeMenuAction(), and SideCar::GUI::WindowManager::makeWindowMenu().
bool SideCar::GUI::ProjectPoint (double objx, double objy, double objz, const double modelMatrix[16], const double projMatrix[16], const int viewport[4], double * winx, double * winy, double * winz)
Project a 3D model point into a 3D view point.
Parameters
objx X value of model point
objy Y value of model point
objz Z value of model point
modelMatrix[16] definition of model space
projMatrix[16] transformation matrix into view space
viewport[4] description of view showing projected points
winx resulting X value
winy resulting Y value
winz resulting Z value
Returns
true if successful, false otherwise
Definition at line 234 of file Utils.cc.
Referenced by HorizontalEllipses(), and SideCar::GUI::TargetPlotImaging::render().
QString SideCar::GUI::RadiansToString (double value, bool decimalFormat = false, int precision = 2, int valueWidth = 6)
Format an angular radian value into one of two formats:
ddd.frac: whole degrees followed by fractional degrees after a decimal point.
ddd mm ss: formatted as DDD MM' SS" format
Parameters
value radian value to format
decimalFormat if true, format in ddd.frac format
Returns
formatted value
Definition at line 97 of file Utils.cc.
References DegreesToString().
Referenced by SideCar::GUI::AppBase::getFormattedAngleRadians(), and HorizontalEllipses().
bool SideCar::GUI::RemoveDirectory (const QDir & directory)
Recursively remove a given directory and all of its contents.
Should really be called 'DeleteDirectory'
Parameters
directory the directory to remove
Returns
true if successful, false otherwise.
Definition at line 164 of file Utils.cc.
References RemoveDirectory().
Referenced by HorizontalEllipses(), SideCar::GUI::Master::RecordingController::Log(), and RemoveDirectory().
bool SideCar::GUI::UnProjectPoint (double winx, double winy, double winz, const double modelMatrix[16], const double projMatrix[16], const int viewport[4], double * objx, double * objy, double * objz)
Inverse of ProjectPoint.
Project a view point into model space.
Parameters
winx X value of view point
winy Y value of view point
winz Z value of view point
modelMatrix[16] definition of model space
projMatrix[16] transformation matrix into view space
viewport[4] description of view showing projected points
objx resulting X value
objy resulting Y value
objz resultin Z value
Returns
true if successful, false otherwise
Definition at line 324 of file Utils.cc.
Referenced by HorizontalEllipses(), and SideCar::GUI::PPIDisplay::PPIWidget::localToRealWorld().
void SideCar::GUI::UpdateToggleAction (QAction * action, bool newCheckedState)
Update a show/hide QAction object so that its text reflects the given show/hide state.
Implements a SideCar GUI application standard for QAction objects that control the visibility of a window. Adjusts the action text so that it has "Show" or "Hide" at the beginning to reflect what will happen if the action is triggered: if state is true, append "Hide"; otherwise, append "Show".
Parameters
action the QAction object to adjust
state true if reflecting a shown state, false for a hidden state
Returns
Definition at line 37 of file Utils.cc.
Referenced by SideCar::GUI::ToolWindowBase::getInitialVisibility(), HorizontalEllipses(), SideCar::GUI::AScope::MainWindow::isDisplayViewSplit(), SideCar::GUI::Spectrum::MainWindow::MainWindow(), SideCar::GUI::AScope::MainWindow::MainWindow(), SideCar::GUI::AScope::MainWindow::restoreFromSettings(), SideCar::GUI::AppBase::setPhantomCursor(), SideCar::GUI::BoolSetting::setValue(), and SideCar::GUI::WindowManager::unmanageWindow().