SideCar: Args Struct Reference
Args Struct Reference
Command-line argument processor.
Public Member Functions
Args (int argc, char **argv)
Constructor.
Data Fields
std::string inputFile
Path of file to read.
std::string recordIndex
Path to RecordIndex data file.
std::string timeIndex
Path to TimeIndex data file.
int gap
Number of seconds between TimeIndex records.
int searchKey
Time to search for if != -1.
Detailed Description
Command-line argument processor.
Uses Utils::CmdLineArgs to the parsing.
Definition at line 32 of file poser.cc.
Constructor & Destructor Documentation
Args::Args (int argc, char ** argv)
Constructor.
Validate command-line arguments.
Parameters
argc command-line argument count
argv command-line argument value vector
Definition at line 49 of file poser.cc.
References Utils::CmdLineArgs::argc(), SideCar::IO::TimeIndex::findOnOrBefore(), gap, Utils::CmdLineArgs::hasArg(), Utils::CmdLineArgs::hasOpt(), inputFile, recordIndex, searchKey, Utils::FilePath::setExtension(), timeIndex, Utils::CmdLineArgs::usage(), and Utils::Exception::what().
The documentation for this struct was generated from the following file:
/Users/howes/src/sidecar/IO/poser.cc