SideCar: SideCar::Parameter::Defs::XMLMixin Struct Reference
SideCar::Parameter::Defs::XMLMixin Struct Reference
Helper class that initializes an XML-RPC value object with a name and type.
#include </Users/howes/src/sidecar/Parameter/Parameter.h>
Static Public Member Functions
static Logger::Log & Log ()
Obtain the log device for XMLMixin log messages.
static void Init (XmlRpc::XmlRpcValue &xml, const std::string &name, const std::string &typeName, const std::string &label, bool isAdvanced)
Initialize an XML-RPC container object with a parameter's name, type, GUI label, and 'advanced' flag.
static void AddEnumNames (XmlRpc::XmlRpcValue &xml, const char *const *names, size_t size)
Add enumeration tags to an XML-RPC conainer.
static void AddEnumNames (XmlRpc::XmlRpcValue &xml, const std::vector< std::string > &names)
Add enumeration tags to an XML-RPC conainer.
Detailed Description
Helper class that initializes an XML-RPC value object with a name and type.
Isolates type-independent functionality from the template classes below, thus minimizing the amount of generated template code.
Definition at line 530 of file Parameter.h.
Member Function Documentation
void Defs::XMLMixin::AddEnumNames (XmlRpc::XmlRpcValue & xml, const char *const * names, size_t size) static
Add enumeration tags to an XML-RPC conainer.
Only used by the Enum parameter class to store the names shown to the user in a GUI pop-up menu widget.
Parameters
xml XML-RPC container to write into
names array of C strings to write
size number of C strings in the array
Definition at line 34 of file Parameter.cc.
References LOGDEBUG, LOGINFO, and XmlRpc::XmlRpcValue::setSize().
void Defs::XMLMixin::AddEnumNames (XmlRpc::XmlRpcValue & xml, const std::vector< std::string > & names) static
Add enumeration tags to an XML-RPC conainer.
Only used by the Enum parameter class to store the names shown to the user in a GUI pop-up menu widget.
Parameters
xml XML-RPC container to write into
names vector containing the name strings to add
Definition at line 48 of file Parameter.cc.
References LOGDEBUG, LOGINFO, and XmlRpc::XmlRpcValue::setSize().
void Defs::XMLMixin::Init (XmlRpc::XmlRpcValue & xml, const std::string & name, const std::string & typeName, const std::string & label, bool isAdvanced) static
Initialize an XML-RPC container object with a parameter's name, type, GUI label, and 'advanced' flag.
Parameters
xml XML-RPC container to write into
name parameter name to record
typeName parameter type to record
label parameter GUI label to record
isAdvanced true if parameter is for advanced use
Definition at line 21 of file Parameter.cc.
References XmlRpc::XmlRpcValue::clear(), and LOGDEBUG.
Logger::Log & Defs::XMLMixin::Log () static
Obtain the log device for XMLMixin log messages.
Returns
Log reference
Definition at line 14 of file Parameter.cc.
References Logger::Log::Find().
The documentation for this struct was generated from the following files:
/Users/howes/src/sidecar/Parameter/Parameter.h
/Users/howes/src/sidecar/Parameter/Parameter.cc