SideCar: PerThreadInfo Struct Reference
PerThreadInfo Struct Reference
Internal collection of Log attributes associated with a specific thread.
Public Member Functions
PerThreadInfo ()
Constructor.
std::ostream & getStream (Log *log, Priority::Level level)
Obtain a reference to the C++ output stream.
std::ostream & getNullStream () const
Obtain a reference to the C++ output stream that never collects any data due to its badbit being set.
Detailed Description
Internal collection of Log attributes associated with a specific thread.
To keep threads from stepping on each other as they build a log message, each thread has its own private LogStreamBuf object.
Definition at line 136 of file Log.cc.
Constructor & Destructor Documentation
PerThreadInfo::PerThreadInfo ()
Constructor.
Create a new LogStreamBuf, and a new C++ output stream object that uses it.
Definition at line 160 of file Log.cc.
Referenced by RuntimeData::getNullStream(), and RuntimeData::getStream().
Member Function Documentation
std::ostream& PerThreadInfo::getNullStream () const inline
Obtain a reference to the C++ output stream that never collects any data due to its badbit being set.
Returns
std::ostream reference
Definition at line 152 of file Log.cc.
Referenced by RuntimeData::getNullStream(), and RuntimeData::getStream().
std::ostream & PerThreadInfo::getStream (Log * log, Priority::Level level)
Obtain a reference to the C++ output stream.
Returns
std::ostream reference
Definition at line 167 of file Log.cc.
The documentation for this struct was generated from the following file:
/Users/howes/src/sidecar/Logger/Log.cc