SideCar: FindLongName Struct Reference
FindLongName Struct Reference
Functor used to locate an OptionDef with a certain longName value.
Public Member Functions
FindLongName (const std::string &name)
Constructor.
bool operator() (const CmdLineArgs::OptionDef &def) const
Functor method that checks if an OptionDef entry has the long name we are looking for.
Detailed Description
Functor used to locate an OptionDef with a certain longName value.
Definition at line 262 of file CmdLineArgs.cc.
Constructor & Destructor Documentation
FindLongName::FindLongName (const std::string & name) inline
Constructor.
Parameters
name option to look for
Definition at line 268 of file CmdLineArgs.cc.
Member Function Documentation
bool FindLongName::operator() (const CmdLineArgs::OptionDef & def) const inline
Functor method that checks if an OptionDef entry has the long name we are looking for.
Parameters
def OptionDef entry to compare
Returns
true if matched
Definition at line 276 of file CmdLineArgs.cc.
References Utils::CmdLineArgs::help(), Utils::CmdLineArgs::opt(), and Utils::CmdLineArgs::usage().
The documentation for this struct was generated from the following file:
/Users/howes/src/sidecar/Utils/CmdLineArgs.cc