SideCar: SideCar::Messages::PRIMessage::RIUInfo Struct Reference
SideCar::Messages::PRIMessage::RIUInfo Struct Reference
Internal collection of VME/RIU header attributes.
#include </Users/howes/src/sidecar/Messages/PRIMessage.h>
Public Member Functions
RIUInfo ()
Default constructor.
RIUInfo (const VMEDataMessage &vme)
Conversion constructor.
double getRangeAt (double gate) const
ACE_InputCDR & load (ACE_InputCDR &cdr, int version)
Load values from a CDR input stream.
ACE_OutputCDR & write (ACE_OutputCDR &cdr) const
Write values to a CDR output stream.
std::ostream & print (std::ostream &os) const
Print values to a C++ text stream.
std::ostream & printXML (std::ostream &os) const
void loadXML (XmlStreamReader &xsr)
Data Fields
uint32_t msgDesc
Description of the raw VME data.
uint32_t timeStamp
VME timestamp value.
uint32_t sequenceCounter
VME sequence counter.
uint32_t shaftEncoding
Value of the shaft encoder at trigger.
uint32_t prfEncoding
*** This used to be northMark ***
double irigTime
VME IRIG timestamp.
double rangeMin
Range value of the first gate.
double rangeFactor
Range change for subsequent gates.
Detailed Description
Internal collection of VME/RIU header attributes.
Definition at line 37 of file PRIMessage.h.
Constructor & Destructor Documentation
SideCar::Messages::PRIMessage::RIUInfo::RIUInfo () inline
Default constructor.
Used when loading from a file.
Definition at line 41 of file PRIMessage.h.
PRIMessage::RIUInfo::RIUInfo (const VMEDataMessage & vme)
Conversion constructor.
Acquire values from a VME message header.
Parameters
vme header to copy
Definition at line 39 of file PRIMessage.cc.
Member Function Documentation
ACE_InputCDR & PRIMessage::RIUInfo::load (ACE_InputCDR & cdr, int version)
Load values from a CDR input stream.
Parameters
cdr stream to read from
Returns
stream read from
Definition at line 48 of file PRIMessage.cc.
References SideCar::Messages::RadarConfig::GetRangeFactor_deprecated(), SideCar::Messages::RadarConfig::GetRangeMin_deprecated(), irigTime, msgDesc, prfEncoding, rangeFactor, rangeMin, sequenceCounter, shaftEncoding, and timeStamp.
Referenced by SideCar::Messages::PRIMessage::getAzimuthEnd().
std::ostream & PRIMessage::RIUInfo::print (std::ostream & os) const
Print values to a C++ text stream.
Parameters
os stream to write to
Returns
stream written to
Definition at line 87 of file PRIMessage.cc.
References SideCar::Messages::XmlStreamReader::getAttribute(), irigTime, msgDesc, prfEncoding, rangeFactor, rangeMin, sequenceCounter, shaftEncoding, and timeStamp.
Referenced by SideCar::Messages::PRIMessage::printHeader().
ACE_OutputCDR & PRIMessage::RIUInfo::write (ACE_OutputCDR & cdr) const
Write values to a CDR output stream.
Parameters
cdr stream to write to
Returns
stream written to
Definition at line 69 of file PRIMessage.cc.
References irigTime, SideCar::Messages::PRIMessage::Log(), LOGTIN, LOGTOUT, msgDesc, prfEncoding, rangeFactor, rangeMin, sequenceCounter, shaftEncoding, and timeStamp.
The documentation for this struct was generated from the following files:
/Users/howes/src/sidecar/Messages/PRIMessage.h
/Users/howes/src/sidecar/Messages/PRIMessage.cc