SideCar: RuntimeData Struct Reference
RuntimeData Struct Reference
Internal collection of attributes that must be initialized only once at startup.
Public Member Functions
LogMap & logMap ()
Obtain the global Log device map container.
std::ostream & getNullStream ()
Obtain the output stream object used for log messages with a priority level such that the log message written to the stream will NOT be written out to an output device.
std::ostream & getStream (Log *log, Priority::Level level)
Obtain the output stream object use for log messages with a priority level such that the log message writtine to the stream will be written out to an output device.
ClockSource::Ref clock ()
Obtain the global ClockSource object for message timestamps.
ClockSource::Ref setClock (const ClockSource::Ref &obj)
Set the global ClockSource object for message timestamps.
Static Public Member Functions
static void Initialize ()
Class method that creates the RuntimeData singleton.
static RuntimeData & Singleton ()
Obtain the RuntimeData singleton value.
Detailed Description
Internal collection of attributes that must be initialized only once at startup.
Contains the global Log device map, and the global ClockSource that provides the timestamps for log messages. There is only one RuntimeData object in existence during the application's lifetime.
Definition at line 177 of file Log.cc.
Member Function Documentation
ClockSource::Ref RuntimeData::clock ()
Obtain the global ClockSource object for message timestamps.
Returns
ClockSource object
Definition at line 321 of file Log.cc.
Referenced by Logger::Log::GetClockSource().
std::ostream & RuntimeData::getNullStream ()
Obtain the output stream object used for log messages with a priority level such that the log message written to the stream will NOT be written out to an output device.
Returns
C++ output stream reference.
Definition at line 289 of file Log.cc.
References PerThreadInfo::getNullStream(), and PerThreadInfo::PerThreadInfo().
std::ostream & RuntimeData::getStream (Log * log, Priority::Level level)
Obtain the output stream object use for log messages with a priority level such that the log message writtine to the stream will be written out to an output device.
Returns
C++ output stream reference.
Definition at line 301 of file Log.cc.
References Logger::Log::fullName(), PerThreadInfo::getNullStream(), Logger::Log::isAccepting(), and PerThreadInfo::PerThreadInfo().
Referenced by Logger::Log::getStream().
void RuntimeData::Initialize () static
Class method that creates the RuntimeData singleton.
Invoked from pthread_once() to guarantee only one RuntimeData object. Note that there is no way to delete the singleton value.
Definition at line 252 of file Log.cc.
LogMap & RuntimeData::logMap ()
Obtain the global Log device map container.
Returns
std::map reference
Definition at line 283 of file Log.cc.
Referenced by Logger::Log::GetNames().
ClockSource::Ref RuntimeData::setClock (const ClockSource::Ref & obj)
Set the global ClockSource object for message timestamps.
Parameters
obj new ClockSource object to use
\return old object value
Definition at line 327 of file Log.cc.
References setClock(), and Singleton().
Referenced by setClock().
RuntimeData & RuntimeData::Singleton () static
Obtain the RuntimeData singleton value.
Uses pthread_once to guarantee only one instance is created, regardless of threading.
Returns
RuntimeData reference
Definition at line 261 of file Log.cc.
Referenced by Logger::Log::GetClockSource(), Logger::Log::GetNames(), Logger::Log::getStream(), and setClock().
The documentation for this struct was generated from the following file:
/Users/howes/src/sidecar/Logger/Log.cc